.github/workflows/android.yml, .github/workflows/manual-release.yml, .github/workflows/matrix.yml, .github/workflows/msvc-full-features.yml, .github/workflows/release.yml
SUMMARY: Infrastructure "bump versionas and use new output syntax GITHUB_OUTPUT on CI"
old syntax for setting output is getting deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples
actions are using node16: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- uses shiny new `echo "foo=bar" >> $GITHUB_OUTPUT` syntax
- bump workflow versions to latest
=> ci: bump actions versions and use `GITHUB_OUTPUT`

data/json/scenarios.json, data/mods/more_classes_scenarios/cs_scenarios.json
SUMMARY: Balance "Add more existing professions to scenarios with a low variety of available professions"
This aims to add a few more profession options to some of the scenarios that lack variety, as once more failing to go the fuck to sleep proves to be the best time to work on an idea.
1. Added crackhead, naked and afraid, rat prince, and prototype cyborg to Really Bad Day scenario. The first since tweaker is already allowed, the second because it's even worse off than shower victim, rat prince mostly because it'd be humorous trying to wrangle a baker's dozen of pet rats in what is already the quintessential meme scenario. And finally, broken cyborg is the most infamous and challenging profession I ever added, so it'd allow players to opt into just a bit more masochism if they so …
=> Expand profession options for scenarios a bit

data/json/items/ammo/20x66mm.json, data/json/items/ammo/shot.json, data/json/items/ammo/signal_flare.json, data/json/items/tool/lighting.json
SUMMARY: Balance "Flare ammo and dragon's breath deal heat-type damage like other incendiaries, lit flares and torches gain fire damage when thrown"
Another minor item on the "easy stuff that'd be interesting to add" list.
Main changes:
1. Set it so that lit hand flares deal heat-type damage when thrown. Went with 8 damage, half what the signal flare ammo deals when fired out of a flaregun. This is also the max roll of the bonus damage the `FLAMING` flag adds to melee.
2. Related, changed it so that flaregun ammo and 20x66mm flare shells deals heat-type damage instead of bullet, for consistency.
Secondary changes:
3. Being the only other item involving an open flame potentially big enough to throw at things, additionally added heat damage to lit torches when thrown. Set it to 4, half …
=> More use of heat-type damage for flares, torches, and dragon's breath

data/mods/Aftershock/mobs/uplifted_monsters.json
SUMMARY: [Bugfixes] "Fixes invalid harvest targets in uplifted Aftershock animals"
The uplifted animals from Aftershock had invalid harvests, and butchered into nothing. This replaces those with their mammal equivalents. 
I replaced demihuman_fur and demihuman_large_fur with mammal_fur and mammal_large_fur to make them have a valid harvest target, so butchery could work.
Demihuman seems to imply they are closer to human, so maybe it should be cannibalism. I see no reason why it would be considered cannibalism however, an uplifted bear is still a bear. An uplifted monkey is more questionable and maybe that one could be close enough to cannibalism.
I changed the JSON, launched the game with it, and butchered the 3 animals in question. No crashes, butchery worked.
Aftershock is pain.
=> Aftershock butcher fixes

data/json/furniture_and_terrain/terrain-manufactured.json
SUMMARY: Balance "Ported the Broken Generator deconstruct from DDA"
The broken generator is one of few furnitures/furniture terrains that have no deconstruct recipe. This ports the [DDA](https://github.com/CleverRaven/Cataclysm-DDA/pull/41731) deconstruct. 
I copied their deconstruct recipe but replaced pipe fittings with 0-1 scrap metal as this item does not exist in BN. 
Changing the resulting items so it doesn't give a whole plastic jerrycan. Leaving it as smashing required.
I opened the game with the changes and successfully deconstructed a broken generator for parts. No crashes or errors.
If I run into any other common furnitures that isn't deconstructible but should, I'll be sure to tackle them.
=> Broken Generator deconstruct port from DDA

src/rot.cpp
SUMMARY: Bugfixes "Incorrect storage conditions display for vehicle freezer and fridges"
- fix #2647
looks like `vpart_info` caches `vehicle_part` struct each time. previously, the flags were always 0 because it was uninitialized. tracked in #2651.
changed to use `vpart_info` to get correct vehicle part info.
created test vehicle with minifridge. it correctly displayed that it partially prevented the food from rot.
i'm getting gaslighted by the codebase
=> fix: incorrect temperature for vehicle parts

data/json/professions.json, data/json/scenarios.json, data/json/vehicle_groups.json, data/json/vehicles/custom_vehicles.json
SUMMARY: Content "Restore old post-apoc professions previously removed from the game"
Follow up PR to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2540, bringing back some interesting post-apoc professions that DDA had dummied out.
1. Giving the road warrior a dog instead of or in addition to a car.
2. Some missions could maybe be set to spawn a wasteland interceptor later on as a bandit vehicle maybe, or just say "fuck it" and allow spawning one in bandit vehiclegroup maybe?
3. Adding a tank part that goes on the center vehiclepart slot so it's visible in the back.
4. If we ever work on that idea of being able to talk your way into being on speaking terms with Hells Raiders, I plan for certain professions to have a profession trait that makes that easier to accomplish, with the …
=> Reimplement and rebalance post-apoc professions

.github/workflows/msvc-full-features.yml, build-scripts/build.sh, build-scripts/problem-matchers/catch2.json, build-scripts/problem-matchers/debugmsg.json, build-scripts/requirements.sh, src/cached_options.cpp, src/cached_options.h, src/debug.cpp, src/json.cpp, tests/Makefile, tests/json_test.cpp, tests/test_main.cpp
SUMMARY: Infrastructure "Port DDA ci problem matchers"
- fix #2661 
ported
- https://github.com/CleverRaven/Cataclysm-DDA/commit/493f6d4e83ffa2ca62133f96dc3a9b8851a5bc4a by @Qrox 
- https://github.com/CleverRaven/Cataclysm-DDA/pull/44111 by @jbytheway 
- https://github.com/CleverRaven/Cataclysm-DDA/pull/44126 by @jbytheway 
added
- https://github.com/marketplace/actions/msvc-problem-matcher
[flake8](https://github.com/CleverRaven/Cataclysm-DDA/pull/44192) is omitted due to BN migrating to typescript for tool scripts.
cry in pain
TODO: add android problem matchers: https://github.com/marketplace/actions/android-problem-matchers
=> ci: add problem matchers

src/game.cpp
SUMMARY: Features "Auto-move now takes distraction manager into account, "
I was getting sick of "monster spotted" queries constantly interrupting fast-travel, testing how to fix it turned out to be easy enough even for someone with my level of inexperienced.
1. In `game::process_voluntary_act_interrupt`, changed the check for monsters that're dangerously close to also occur if you're fast traveling, and not just performing standard activities. I'm going to hope that doesn't cause performance issues, but it's needed to prevent fast-travel with "monster spotted" disabled from letting you walk face-first into zombies.
2. In `game::cancel_activity_or_ignore_query`, added a check in the fast-travel section that has it bail out if the current distraction is one you've set to ignore.
3. Also …
=> Auto-move uses distraction manager, prompts on danger-close

data/json/items/tool/med.json
SUMMARY: Infrastructure "Made blood draw kit a tool, not a weapon"
Blood draw kit is used as a tool, it shouldn't be in the weapons category
Added "category": "tools" to the item
Ponder on why this is the only item in the entire tool folder that does not have its category defined.
Spawn the item, it is now in the tool category
=> Added tool category to blood draw kit

src/character.cpp, src/character_display.cpp, src/debug_menu.cpp
SUMMARY: Features "Allow changing gender in debug menu"
because why not? 
gender is purely cosmetic like name, age, and height but it wasn't configurable unlike others. allowing it makes roleplaying easier.
player can now change their gender in `player` - `Edit [D]escription` in the debug menu. selecting it toggles between `male` <-> `female`.
use the uncivilized method, savefile editing
how the debug menu looks like
| Setting the gender to male | tileset uses male portrait |
|--------|--------|
| ![Cataclysm: Bright Nights - cbn-experimental-2023-04-19-1517_02](https://user-images.githubusercontent.com/54838975/233126940-6ab1b199-4845-4e34-a725-c24c2443900b.png) | ![Cataclysm: Bright Nights - cbn-experimental-2023-04-19-1517_03](https://user-images.githubusercontent.com/54838975/233126944 …
=> feat: allow changing gender in debug menu

doc/MAGIC.md
SUMMARY: [Infrastructure] "Update Magic documentation with recent discoveries"
The magic documentation is lacking a fair bit of details that I discovered through trial and error, plus pestering Chaosvolt on discord. I'd like to add some of these revalations to the documentation so others can have a better idea of what they're doing.
I have updated target attack to explain negative damage will heal a target, that when using spawn item the damage specified determines quantity of items given, and that mutations can grant spells.
Keeping magic as much a mystery in the documentation as it is in any fantasy setting. Revamping the entire magic document from the ground up to be as clear and concise as possible.
I checked my changes on Github and made sure they still worked. I also made sure they …
=> Magic.md documentation update

data/json/mutations/mutations.json, src/game_inventory.cpp
SUMMARY: Features "allow installing non-sterile CBM when `Infection Immune`"
inspired by https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/60
`Infection Immune`(INFRESIST) trait will ignore checking for CBM sterileness.
| Before `Infection Immune` | After `Infection Immune` |
|--------|--------|
| ![Cataclysm: Bright Nights - cbn-experimental-2023-04-19-1517_06](https://user-images.githubusercontent.com/54838975/233318327-25a75000-53dc-416a-98c4-f090fe8fdfcb.png) |  ![Cataclysm: Bright Nights - cbn-experimental-2023-04-19-1517_07](https://user-images.githubusercontent.com/54838975/233318339-624c3f28-5604-47dc-abe9-e32a1b975ecd.png) |
=> feat: allow installing non-sterile CBM when `Infection Immune`

src/ranged.cpp
SUMMARY: Balance "Prevent range 1 autoattacks from non-directly-up/down z-level attacks"
Preventing the unintended and hard to balance trick, where you stand on a roof and autoattack the zombies below with fully melee (not reach) attacks.
Special-cased the range 1 autoattacks to allow attacks only if the target is on same z-level, or directly up/down.
* Spawn a 1 tile wall and zombie next to it
* Teleport onto the wall
* Confirm autoattack won't target the zombie
* Repeat with a spear to confirm that spears can still autoattack "z-diagonally"
* Spawn a cylinder of 3x3 metal walls, with hole in the middle, 2 z-levels tall
* Teleport to the middle
* Spawn a zombie above yourself
* Confirm the autoattack targets the zombie
Related to: #2575
Ensures symmetry by having both the player and …
=> Prevent range 1 from diagonal-z-attacks

data/json/items/melee/unarmed_weapons.json
SUMMARY: [Balance] "Changed the punch dagger to no longer have a to-hit penalty."
The punch dagger is, effectively, a blade protruding between two fingers; it would make your punches hit harder thanks to the blade, but it wouldn't hamper your ability to punch.
I removed a single line from the json, thus removing its attack penalty.
=> Removed "to_hit" from punch dagger

src/iuse_actor.cpp
SUMMARY: Features "Manual Bionic Installation function now also checks for Infection Immune trait when attempting to install a non-sterile CBM"
Follow-up to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2671, figured it'd be dead easy to just do the thing I noticed was missing as a separate PR since it's like a whole two-line change.
In game.cpp, set `install_bionic_actor::can_use` so that the check for non-sterile bionics also considers whether you have the Infection Immune trait, allowing manual bionic installation to carry on if you have the trait (if the setting is enabled via using the mod).
Pestering Scarf to do it. :3
2. Tested a world without manual installation mod enabled, correctly doesn't allow self-installs even if I have Infection Immune …
=> Infection Immune now also affects self-installs when enabled

src/explosion.cpp, src/map.cpp, src/map.h, src/options.cpp
SUMMARY: Features "Debug option for explosive traps and items to detonate on impact"
continuation of #1348 by @DeltaEpsilon7787 
1. allow clearing minefield with [explosives](https://www.youtube.com/watch?v=a52-rOC8_Zk) and guns
2. chain reaction
adds an option `MADE_OF_EXPLODIUM`, which gets disabled if value is 0.
if explosive power exceeds MADE_OF_EXPLODIUM value, trap or item will detonate.
1. currently only items that explodes on fire will explode. maybe create more generic member function to check if item will explode?
2. mines could be JSONized.
https://user-images.githubusercontent.com/54838975/230722499-74ee7ee7-6ce5-4d16-a20f-fffa602990ce.mp4
chain reaction of traps(landmine).
https://user-images.githubusercontent.com/54838975/230722503-2aad109e-22e6-439b-ae03-7616112e1d88.mp4 …
=> feat: Rule Of Cool explosions v0.2: Made of explodium

data/json/field_type.json, data/json/furniture_and_terrain/terrain-walls.json, src/explosion.cpp, src/game.cpp, src/game.h, src/map.cpp
SUMMARY: [Feature] "Explosions are made more spectacular; also make it possible to climb solid rock (thus craters too)"
https://tvtropes.org/pmwiki/pmwiki.php/Main/ImpressivePyrotechnics
This is a further improvement to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1348, with the intention to both improve the appearance of explosions, make them have a bit more instrumental value and address a few issues that were reported.
1. The whole explosion function is rewritten to now be a process with an event queue. Thanks to this, the explosion can animate itself. This addressed the growing complexity of "do_blast_new".
2. Shrapnel functionality is merged with the explosion process as just one of the events. This addresses the duplication of functionality that was necessary to animate the …
=> Rule of Cool explosions v0.2: Impressive Pyrotechnics

src/game.cpp
SUMMARY: Bugfixes "No stripping non-ally NPCs."
Xindage on the Discord noted that you can strip down non-allied NPCs, this includes hostiles you are in combat with.
You can no longer access the sort armour menu for non-allied NPCs.
Expand on NPC menu to account for hostility instead of just "is ally" and "not mounted".
- Probably something to do _eventually_, but not right now.
Spawn into world, spawn NPC, check that I can't access the sort armour menu. Using debug mind control, convert them into an ally, then note that I can strip them down and dress them up.
You know, maybe one day we can simulate a bit of DF's systems, if only so we can engage in [strip combat.](https://www.youtube.com/watch?v=y4fKibUs9jg)
=> No stripping non-ally NPCs.

.github/workflows/documentation.yml
SUMMARY: Infrastructure "Use concurrency in documentation"
hopefully fix documentation build failure when merging multiple PRs in succession
use [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)
=> ci: use concurrency in documentation

data/mods/DinoMod/harvest.json
SUMMARY: Mods "[DinoMod] fix CBM harvest"
Fixes CBM harvests in DinoMod
Restores CBM harvest groups accidentally deleted with the giant rollup PRs and adds down feathers to them as appropriate
N/A
Tests passing, looks good
Thanks to Phoenix of the Chorus on Discord for flagging this
=> [DinoMod] fix CBM harvest

src/character.cpp, src/game.cpp, src/monmove.cpp, src/teleport.cpp
SUMMARY: BugFixes "Activate trap on force-moved enemies"
To fix #2684 : Trap wont activated on forced moved enemies
To check for traps when a creature is knocked back
knocked zombies into traps
=> Activate trap on force-moved enemies

src/explosion.cpp
SUMMARY: [Performance] "Explosion animation speed made consistent with animation delay"
Addresses and closes #2698. Additionally makes 0 animation delay not animate the explosion at all.
Also a number of bugfixes related to Made of Explodium update (https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2601).
Explosion animation system uses wall clock to time events instead of relying on nanosleep which disregarded rendering overhead, causing animation delay option to have a non-linear relationship with actual animation speed.
#2699
Check "rule of cool explosion merge conflict resolving" [thread in BN Discord](https://discord.com/channels/830879262763909202/1099620716023910470).
N/A
=> Rule of Cool explosions v0.2: animation system fixes

.github/workflows/pull-translations.yml
SUMMARY: I18N "Use ISO timestamp for automated translation pull"
Improve readability by using the YYYY-MM-DD format. 
It is more natural to read time in YYYY-MM-DD HH:MM:SS than in DD-MM-YYYY HH:MM:SS because the former aligns from big to small.
use `nanzm/get-time-action` from `release.yml`.
=> ci: use ISO timestamp for automated translation pull

data/json/bionics.json, src/character.cpp, src/vehicle.cpp
SUMMARY: Balance "buff speed and power usage of Joint Servo CBM"
got bug report & idea from https://gall.dcinside.com/board/view/?id=rlike&no=438546
some excerpts:
> When riding a bike, the joint servo CBM uses power in kilojoules, whereas running uses power in joules.
> The joint servo only increases speed by 8 to 10, yet its disadvantages outweigh the advantages. 
> To make it at least usable, the offline penalty should be removed and the online speed bonus should be doubled.
1. buffed joint servo.
|         | Before | After |
| ------- | ------ | ----- |
| Running | 15%    | 25%   |
| Walking | 5%     | 10%   |
| Offline | -10%   | 5%    |
2. reduced power consumption while pedaling the vehicle.
port https://github.com/CleverRaven/Cataclysm-DDA/pull/47274
default walking speed
default …
=> feat(balance): buff speed and power usage of `Joint Servo` CBM

data/json/items/ammo.json, data/json/items/ranged/slings.json, data/json/recipes/ammo/other.json
SUMMARY: Content "Changed sling and staff sling to be capable of using both rocks and pebbles as ammo, as well as added in new 'sling bullet' and 'small sling bullet' ammo as a higher-end lead ammo for slings and staff slings."
Slings have been used to huck larger rocks historically, and staff slings are just a sling on the end of a staff. Furthermore, lead sling bullets are historically accurate and would serve as a nice alternative to ball bearings.
It's a minor change to two items, two new items, and two new recipes.
You could keep the staff sling and sling as using rocks and pebbles respectively, but it's kind of a strange distinction to begin with.
I've made sure there are no json errors and it seems fairly balanced in terms of stats and crafting.
=> feat(content): allow rocks for (staff) sling, add {big,small} lead sling bullets

data/mods/Aftershock/recipes/uncraft.json
SUMMARY: [Balance] "Adds an uncraft to the atomic butter churn"
There's no uncraft for the atomic butter churn, this adds one.
This requires some context to fully explain. All of the Aftershock atomic appliances have bad uncrafts which do not respect their mass, rather than rebalance all of them I currently chose to go with the existing balance by making the atomic butter churn have the same uncraft as the atomic coffee maker. Their weight is only off by 1 pound, so it's very close.
Rebalance every single atomic item to have their uncraft respect their mass.
Loaded game, did the uncraft. It worked, no crashes.
I'll rebalance the uncrafts for all atomic items later, even DDA Aftershock seems to lack an uncraft for the atomic butter churn.
=> Aftershock atomic butter churn uncraft

src/map.cpp
SUMMARY: Bugfixes "Fixed impassable furniture stopping the player from climbing"
During gameplay I have noticed that having too many furniture around a downspout will cause it to no longer be climbable, as far I know this is unintended behaviour. This issue should also affect everything that is climbable, with a few exceptions.
Fixes #2704
Made the return unable to return anything lower than 0, makes it so that the move cost won't go negative and thus stop the player from climbing.
Do nothing, it might be intended.
Cry because I accidentally removed everything I wrote.
1. Try to climb with 5 impassable furniture around, can climb
2. Try to climb with 6 impassable furniture around, can now climb unlike before.
=> Fixed impassable furniture stopping the player from climbing

data/json/furniture_and_terrain/furniture-medical.json, data/json/items/ammo.json, data/json/obsoletion/migration.json, data/json/snippets/fliers.json
SUMMARY: Balance "Fix spawn of now-useless betavoltiac item, migrate it out"
Fixes for stuff overlooked in a PR I merged, hecc: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2725
1. Added a migration converting betavolatics to plutonium cells.
2. Set centrifuges to yield plutonium cells instead of betavolatics on deconstruct.
3. Updated a flier snippet to not refer to any specific item now and instead just nuclear energy in general.
Screaming. More seriously, also migrating the RTG item at some point, assuming I don't find a way to use that to make plutonium generators a valid grid furniture balanced towards a low level of infinite power instead of burning plutonium cells (in which case I'd still use the minireactor for that).
1. Checked affected files for syntax and lint errors, …
=> Migrate out betavoltaic item

data/json/recipes/armor/torso.json
Allows Survivors to craft Kevlar Vests at tailoring level 6 by adding recipe.
The Kevlar Vest is the 'basic' lightweight bullet armor that is worn as the innermost part. However, Kevlar vests can only be farmed in police-related elements, and even this is rare. And as long as there are XL Kevlar vests, I am uploading this PR because I decided that it would be nice if it was possible to produce a normal size Kevlar vest.
By adding a Kevlar vest, I think it will be the answer to survivors who are wondering what to wear underneath.
It is to increase the supply of Kevlar vests not only to the police, but also to the military and gunsmiths.
No problem, works fine.
=> Add Kevlar Vest's Recipe

data/json/items/melee/misc.json
SUMMARY: Balance "Buff whip damage"
Bullwhip would looks more like good dedicated weapon.
cutting dmg 3 changes to 14
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/a40a4def5d6beaa8cd690d5d684d71918d0001ea/doc/GAME_BALANCE.md#weapon-tiers As it describing, bullwhip is but a "good dedicated weapon", not an "improvised weapon", whose damage is 2 to 5.
**before**
**after**
Look at melee damage!
It is just changing one integer value. Does not bring any bug.
=> Buff whip damage

data/json/vehicleparts/combustion.json
SUMMARY: [Balance] "Avgas can be used in gasoline engines"
From a balance perspective, I see no issue with using avgas as gasoline since you're using a harder to find and more valuable fuel (you know for helicopters) to power weaker engines than a gas turbine engine. From a realism perspective, see this thread over at DDA for tons of research. https://github.com/CleverRaven/Cataclysm-DDA/pull/58181 I see no compelling reason on the realism side that this CANT be done, even if it's not a great idea. If you go through each of the links and arrive at a different conclusion, mention that in the pull.
We do not model vehicle wear and tear, and we also don't model engine modifications so both of these can be done as future solutions if desired.
I added the fuel options field to gasoline …
=> avgas can be used in gasoline engines

src/line.cpp, src/line.h, src/monmove.cpp
SUMMARY: Bugfixes "Allow monsters to attack directly up/down"
Fix #1317
Changed `std::vector<tripoint> squares_closer_to( const tripoint &from, const tripoint &to )` in `line.{h,cpp}` when it's given a pair of points that differ on z axis.
Before: Adds `from + tripoint( sgn( diff.x ), sgn( diff.y ), sgn( diff.z ) )` (full diagonal) as first option
Now: Adds `from + tripoint( 0, 0, sgn( diff.z ) )` (just up/down) as first option
This function was used in exactly one place: monsters picking next point to move to.
Monster movement code in z cases split into:
* Z movement allowed
* Z movement not allowed, but attack allowed (new one)
* No Z interactions at all
There may be an issue in that completely surrounded zombies may fail to pick new targets or even attack the old ones, because of some …
=> Allow monsters to attack directly up/down

data/json/itemgroups/Locations_MapExtras/locations.json, data/json/itemgroups/collections_trades.json, data/json/itemgroups/supplies.json, data/json/items/generic/spares.json, data/json/items/generic/string.json, data/json/recipes/other/vehicles.json, data/json/requirements/materials.json, data/json/uncraft/generic.json, data/json/vehicleparts/vehicle_parts.json, tests/vehicle_efficiency_test.cpp
SUMMARY: [Content] "[Briefly describe the change in these quotation marks]"
I recently saw this pull https://github.com/CleverRaven/Cataclysm-DDA/pull/64834 and decided it was a good way of also adding a source of synthetic fabric. Now the seatbelts have an item AND we have a source of synthetic fabric. Thanks to @Fris0uman for the concept and much of the PR. 
Adds seatbelts and 5-point harnesses, which are used for their vehicle parts. Adds a recipe to make a 5-point harness from 3 seatbelts plus hammering and cutting (My guess here is messing with the belt buckles, I figure you'd handle more on the installation side anyway), also adds an uncraft of seatbelt into synthetic fabric. In a separate PR I am merging lycra into nylon to remove this redundant material. Scarf suggested 3 nylon …
=> Add seatbelts and 5-point harness items

src/options.cpp
SUMMARY: Infrastructure "Simplify options panel code"
tidy up `options.cpp` before adding debug flags support.
- used constexpr keys for `sPageIn` to make them safe.
- used auto for page_id
- extracted font size options to array
compiled and confirmed that the panels look identical before and after refactoring.
| Before | After |
|--------|--------|
| ![Cataclysm: Bright Nights - cbn-experimental-2023-04-29-0458-1-gf36970c7c3ca_01](https://user-images.githubusercontent.com/54838975/235304754-6f58d6dc-9724-40ef-bb68-4dfb469c6295.png) | ![image](https://user-images.githubusercontent.com/54838975/235304770-de3be1c0-90fd-461b-9c36-f3d5e026c9a9.png) |
=> refactor(infrastructure): simplify options panel code

data/json/mapgen_palettes/microlab.json
SUMMARY: Balance "Microlab mapgen palette spawns generic science stuff in specific furniture instead of being all over all of them, other adjustments"
This starts some of the basic work pertaining to that idea I had of making the content of microlabs a bit less bland, starting with some easy updates to the palette. The main flaw with it is how a solid half of the spawns in the mapgen palette call the exact same itengroups, making it a bland mess.
Related issue, which this is a start on: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/971
1. Made the `repeat` numbers for the glass fridge spawns on `F` more consistent, phasing out variable-repeat for these. These will be the main place where `supplies_reagents_lab` and `supplies_samples_lab` spawn, in storage where they belong.
2. …
=> Clean up and rebalance microlab palette item spawns

data/json/items/gun/ups.json
SUMMARY: Content "Fix v29 laser pistol being unable to install laser gunmods"
v29 laser pistol was based on `pistol_base`, preventing installation of laser gunmods like lens.
change `copy-from` to `pistol_base` -> `pistol_energy`
spawnwed v29 laser pistol and lens gunmod. confirmed it could be installed to v29.
=> fix(content): enable laser gunmods for v29 laser pistol

data/json/overmap/overmap_terrain/overmap_terrain_lab.json, data/json/overmap/overmap_terrain/overmap_terrain_microlab.json
SUMMARY: Balance "Pull spawn totals in labs and microlabs a bit closer together, spawning a more a bit monsters in labs and a bit less in microlabs"
As noted in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2740, another flaw with microlabs I wanted to address was how they're infamous for being a slog through a massive hoard of zombies for so little gain. Conversely, regular labs are extremely barren and underpopulated, so adjusting the two a bit makes a degree of sense.
On the one hand, on average a regular lab will likely contain maybe 5 times as many tiles as a microlab (hard to tell for sure) so an individual microlab tile will need to have a higher population count for the two locations to have similar total spawns, but these values can in many ways be nudged a bit closer …
=> Adjust monster density of labs vs microlabs

data/json/professions.json
SUMMARY: Bugfixes "Fix road warrior profession having a redundant set of pliers"
Mild lil thing I noticed in my laptop playthrough, evidently I'd forgotten to delete the pliers from loose inventory after I'd set them to start in the profession's tool belt.
Literally just delete the extra pair of pliers.
Screaming. Also possibly giving them a backpack or some other basic storage and dumping those in loose (along with starting the binocs as no-auto-worn) so they don't start with a toolbelt that clashes with the bandolier, but it's a minor thing for a profession that's expected to live out of their car.
Checked affected file for syntax and lint errors. Also counting to confirm that one instance of `pliers` in the profession entry is indeed a smaller number than two instances.
=> Minor fix for road warrior profession

src/options.cpp
SUMMARY: Bugfixes "Fix incorrect default font width caused by previous refactoring"
fixes regression caused by #2728
removed font width entry from loop and called it explictly
=> fix: default font width should be 8

src/avatar_functions.cpp, src/character.cpp, src/iuse.cpp, src/wish.cpp
SUMMARY: Bugfixes "Allow debug menu to directly spawn irremovable item mods"
Requiring people to debug spawn irremovable item/gun mods like conversion kits via map editor is unintuitive and annoying.
Removes that consideration in `i_add_or_drop()`. Instead the check is done directly on mod removal. Also updates the wish function for non-count_by_charges items to be slightly more efficient.
Spawn conversion mods without issue. Still can't uninstall irremovable mods.
Game doesn't even allow you to try to uninstall irremovable mods, so this seems somewhat extraneous.
=> Allow debug menu to directly spawn irremovable item mods

data/json/professions.json, data/json/scenarios.json
SUMMARY: Balance "Merge Last Flight and Ride of The Valkyries scenario"
This merges together two fairly bare-bones scenarios that're basically the same general concept, both involving a pilot being forced to land.
1. Merged the Last Flight and Ride of The Valkyries scenarios together. Used the name, description (altered a bit to account for spawning with fuel), point cost, and starting mission of Last Flight, while using the start location options from Ride of The Valkyries, and removed the scenario-level vehicle spawn since we'll have profession-level ones.
2. Defined a scenario-only version of the standard helicopter pliot profession, using copy-from like how the blackhawk profession works. 2 points higher than the general version that lacks a vehicle. In exchange however, allowed them …
=> Merge helicopter scenarios into a single one

data/json/bionics.json, data/json/items/bionics.json, src/bionics.cpp, src/character.cpp, src/npc.cpp, src/npcmove.cpp, src/panels.cpp, src/player.cpp, src/suffer.cpp
SUMMARY: Bugfixes "Repair Nanobots properly accounts for splints and mutations"
In #2482 I used `get_all_effects_of_type()` for the mending list when refactoring it. This failed to account for lizard regen or splints as in the original implementation I used.
Also feels like Repair Nanobots drains really fast, so I'm tuning it down unless anyone has objections.
Do it again while retaining `std::vector<effect *> mending list`.
Also, it feels like the Repair Nanobots drain really fast and work really fast, turned it up to 2 minutes.
Apply `erase_if()` to the vector.
- Seems like a lot of extra steps for no reason. 
Install Repair Nanobots, increase bionic power to 100kJ, do not turn on. Break limb, wear splint, wait 30 minutes.
=> Repair Nanobots properly accounts for splints and mutations

src/avatar.cpp, src/avatar_action.cpp, src/bionics.cpp, src/character.cpp, src/character.h, src/item.cpp, src/melee.cpp, src/npc.cpp, src/npc.h, src/npcmove.cpp, src/ranged.cpp, src/savegame_json.cpp
SUMMARY: Bugfixes "Weapon Value Caches properly update"
#1705 revealed issues with weapon value cache for NPCs, where they try to store and read ideal and current values, leading to mismatch and incorrect evaluations.
Adds new `wielded_value()` function dedicated to updating value of currently wielded weapon. Accepts Character and bool as arguments, where the bool decides whether the value to be retrieved is the ideal value if the NPC had access to "infinite" ammo (set to magazine size otherwise values can get absurd).
Refactors `wield_better_weapon()` to solve secondary issue @scarf005 noticed in #1705 where NPC would swap to bionic weapon only to swap back due to how weapon swapping occurs in both `check_or_use_weapon_cbms()` and `wield_better_weapon()`. Now weapon swapping can _only_ …
=> Weapon Value Caches properly update

data/json/items/gun/57.json, data/json/items/gun/9mm.json
SUMMARY: Balance "Base MP5 and P90 Volume reduced to be more in line with existing SMGs."
The current volume of both guns make them significantly larger than most SMGs and even several rifles (see: Calico (1L) and Cx4 Storm 1.5L), lowering the volume makes them more uniform with other guns in their archetype and fit in gun slots that would make sense for their size.
This change reduces the MP5's volume to be about 15% smaller than the UMP45, which is a heavier SMG model that fires a larger caliber. P90 is set to be slightly larger than an MP5 and so the same as the UMP45. These values can probably stil be tweaked but they are simply way too huge at the moment.
I do it for my own games and it werks.
Pictured: Two different MP5 models lined up next to a UMP9; a UMP model that fires 9mm …
=> Reduced volume of the base MP5A2 and P90

src/iuse.cpp
SUMMARY: Bugfixes "Fixed electric chainsaw lajatang not working with UPS"
The item could not be turned on when an UPS was attached to it. (I want stable release 3)
Fixes #2104 
Removed `it->ammo_remaining() > 1` from the code, making it nearly identical to the electric chainsaw. Now it works with UPS.
Understand exactly why `ammo_remaining()` is not working.
1. Combined UPS conversion mod with chainsaw lajatang
2. Successfully turned it on.
3. Confirmed that all actions still work
4. Confirmed that both versions shut down when power is drained
Electric chainsaw lajatang now
Electric chainsaw
=> Fixed electric chainsaw lajatang not working with UPS

data/json/itemgroups/books.json, data/json/items/book/martial.json, data/json/martialarts.json, data/json/mutations/mutations.json, data/json/techniques.json
SUMMARY: Content: "Add the Kickboxing Martial Art style"
There was a new MA style added in the following pull on DDA [https://github.com/CleverRaven/Cataclysm-DDA/pull/59732](https://github.com/CleverRaven/Cataclysm-DDA/pull/59732), original creator [https://github.com/DamienRoyan](https://github.com/DamienRoyan) referenced for attribution if necessary, and there was an update to said MA under [https://github.com/CleverRaven/Cataclysm-DDA/pull/60649](https://github.com/CleverRaven/Cataclysm-DDA/pull/60649). This PR includes the changes from the latter.
Bring it over/recreate it in BN.
Not doing it was the big one. It can also just be made into a mod, and I could easily see how some folks would consider it 'clutter' on the grounds that it doesn't necessarily do something …
=> content: Add the Kickboxing Martial Art style

data/json/items/ammo.json
SUMMARY: [Balance] "Sling bullets, small sling bullets, and ball bearings now drop themselves upon hit."
Sling bullets already had "RECOVERY_100" in the flags, which made you recover them almost all of the time, but ball bearings did not. Scarf suggested I do this.
I modified the "RECOVERY_100" flag on sling bullets and small sling bullets to "RECOVERY_1000", and added it to ball bearings as well.
I attempted to use the 'drop' field, but it caused issues.
It doesn't give json errors and ball bearings now are recoverable.
=> Sling bullet/ball bearing recovery

src/hash_utils.h, src/om_direction.h, src/units_mass.h
SUMMARY: Build "Explicitly add <cstdint> headers"
fixes some complaints when using clang-16
added `<cstdint>` where fixed-width intergers like `uint32_t` are used.
it built on my machine!
=> build: explicitly add `<cstdint>` header

Makefile, src/string_utils.cpp, src/weather_gen.cpp
SUMMARY: Bugfixes "Fix the windows builds"
Get em building
Disable the warning and clean up a few small problems.
=> Fix the builds

src/action.cpp, src/character.h
SUMMARY: Infrastructure "Refactor registering actions/categories in action.cpp"
i was bored and the code looked bad.
replaced `REGISTER_ACTION` and `REGISTER_CATEGORY` macro with `make_register_actions` and `make_register_categories`.
they are curried functions which capture state then return another function which you can conveniently name `register_actions` and `register_categories`. pass it a set and you're good to go. also, it should be fairly performant because it's rvalue refed and uses std::transform under the hood.
put registering action and action for it in same function, because current system is very bug prone
```c++
// before
register("SOME_KEY");
// ...
if ( key == "SOME_KEY" ) {
// do something
}
```
```c++
// after
register("SOME_KEY", [&]() -> void {
// do something
})
``` …
=> refactor: registering actions/categories in action.cpp

data/json/items/melee/unarmed_weapons.json, data/json/recipes/weapon/piercing.json
SUMMARY: Bugfixes "[Briefly describe the change in these quotation marks]"
i've overlooked [chaosvolt's review](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2715#issuecomment-1535657338) in #2715 that the graphic glitch was due to overmap terrain and weapon sharing same id `sai`.
renamed id of `sai` to `sai_weapon`, which changes the two uses of sai:
- weapon sai
- crafting recipe sai
add a migration to change `sai` to `sai_weapon` but hopefully nobody downloaded today's experimental releases as i've deleted one with the PR #2715
=> fix: rename id of `sai` to `sai_weapon`

data/json/itemgroups/supplies.json, data/json/items/vehicle/rotor.json, data/json/recipes/other/vehicles.json, data/json/vehicleparts/rotor.json
SUMMARY: Content "Add a form of lightweight rotors the player can potentially craft"
On looking into some assorted things I was reminded that a form of craftable rotor may potentially be desirable. Regular helicopter rotors would be a bit beyond what might feel reasonable for the player to make, but gyrocopter rotors are something hobbyists put together.
1. Added item for homebuilt gyrocopter rotors. Uses steel and wood, hence lighter weight along with overall smaller size than helicopter rotors.
2. Added vehiclepart definition for gyro rotors. I went with a rotor diameter of 6, basing it off the 20-foot diameter of the Bensen autogyros that seem to be the most common sort of thing hobbyists tinker with.
3. Added recipe for gyro rotors. Based the recipe's overall requirements on wind …
=> Craftable gyrocopter rotors

src/avatar_functions.cpp, src/item.cpp, src/item.h
SUMMARY: Bugfixes "Fix gunmod installation checks for integral magazines."
- fixes #649
When gunmods are installed, warning for magazine adaptor appears in inappropriate situations. As the check does nothing within the same universe as what the warning is meant to indicate. It checks whether the gun's loaded magazine has a default ammo type. Meaning that if you could install a conversion kit while the gun was loaded (which is impossible), the check would pass.
Furthermore, it fails due to guns with integral magazines not returning a default ammo type, as they count as "not loaded" with a magazine. It also fails when unloaded guns are modified, even when the modification doesn't change the ammo type used by the gun.
Rewrite the entire check so it provides appropriate warning.
- Make the …
=> Fix gunmod checks

data/json/items/chemicals_and_resources.json, src/iuse.cpp
SUMMARY: Balance "Buff all water purification methods by 8x (250ml -> 2L)"
rationale:
1. water purification tablets are too inefficient
2. google says a single tablet can purify up to 1~2L of water
> Each tablet treats up to 2 quarts of clean water or 0.8 quart of dirty water
[ew, US measurements but that's not the point](https://www.rei.com/product/109906/aquatabs-water-purification-tablets-package-of-30)
modified charges used in `iuse::water_purifier` by 1/8
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/ae758574-6ea8-4adb-ad71-0839c292cdf7
<details><summary>using single tablet</summary>
1. spawn a 3L bottle, a bottle (0.5L), and 2 water purification tablet
2. fill the bottles with water
3. use tablets to each bottles
4. check that both are purified
</details> …
=> feat: buff all water purification methods by 8x (250ml -> 2L)

src/action.cpp
SUMMARY: Bugfixes "Main menu being unordered"
- fix #2821 
used `std::vector` over `std::set`.
<details><summary>GPT told me so.</summary>
git bisect tells me that this diff causes the game menu entry to not be sorted correctly. what's the problem?
```diff
diff --git a/src/action.cpp b/src/action.cpp
index 1c67074504b..62ad4de95b1 100644
--- a/src/action.cpp
+++ b/src/action.cpp
@@ -657,6 +657,16 @@ bool can_interact_at( action_id action, const tripoint &p )
}
}
+static auto make_register_actions( std::vector<uilist_entry> &entries, const input_context &ctxt )
+{
+    return [&entries, &ctxt]( std::set<action_id> names ) -> void {
+        std::transform( names.begin(), names.end(), std::back_inserter( entries ), [&]( action_id name ) -> uilist_entry
+        {
+            return { name, …
```
=> fix: main menu being unordered

data/json/monsters/feral_humans.json, data/json/speech.json, src/monattack.cpp
SUMMARY: Bugfixes "PARROT_AT_DANGER monster attack can now be triggered when targeting the player, added quotation marks to new feral speech lines."
Dumb thing I forgot in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2809 hecc
In addition, a side effect of this is Scarf discovered that PARROT_AT_DANGER doesn't work if the monster is after the player, they can only see monsters it seems.
1. Fixed new feral lines not having the second layer of quotes so that they'll properly be depicted saying the lines in-game.
2. Updated `mattack::parrot_at_danger` to actually check for if target of the monster has a target they're after (and not a hacky-as-fuck-looking check of all monsters), then if it has a valid target it can see proceeding with the parrot attack.
Screaming "I am the night …
=> Fix PARROT_AT_DANGER attack, proper quotes for new feral lines

data/json/field_type.json
SUMMARY: Balance "Allow thick smoke to affect player through vehicles, like most other gases"
As discussed recently, smoke should perhaps be able to seep into vehicles if heavy enough. I did test and found out that the immunity effect does actually consider if you're properly enclosed in a vehicle in some manner, so it'd be feasible to make the most intense fields get you through a vehicle like most gas fields can.
Closes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2734
Removed `immune_inside_vehicle` from intensity 3 of smoke. This makes it consistent with several other gas fields. One thing to note is that vehicle exhaust can rarely produce thick smoke, so I'd be leery of going too overboard with this lest players start wondering why they're coughing after driving through …
=> Thick smoke can get through vehicles like other gases

src/iexamine.cpp
SUMMARY: Interface "show cost on vending machine window"
- resolve #2820
also show cost on rightmost panel
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2820#issuecomment-1546590438
=> feat: show cost on vending machine window

data/json/npcs/isherwood_farm/NPC_Carlos_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Chris_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Claire_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Eddie_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Jack_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Jesse_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Lisa_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Luke_Isherwood.json
SUMMARY: Bugfixes "Fixes for Isherwood NPC weapons and outfits"
While rampaging around at the Isherwood farm again in my most recent playthrough, I noticed a mysterious lack of getting shot in the face by them and soon found out their weapons all spawn without ammo, along with some other problems encountered while digging deeper.
1. Split the worn item collection off between male and female variants for the Isherwoods, along with increasing the variety of clothing a bit.
2. Phased out the weird system of wielding an empty bow/crossbow and having an (also empty) rifle spawn loose in inventory. Instead their carry override has them pick between a bow, crossbow, or rifle which will always spawn with some spare ammo, a spare mag where relevant. Uses the same combined weights as the original …
=> Fixes to Isherwood weapons and clothing

data/json/itemgroups/Weapons_Mods_Ammo/ammo.json, data/json/mapgen/bunker.json, data/json/mapgen/lab/lab_floorplans_finale1level.json, data/mods/DinoMod/mapgen/DinoLabFinale.json, data/mods/No_Hope/Mapgen/bunker.json, src/monster.cpp
SUMMARY: Balance "Spawn mech battery separate from the mech, allowing for mechs to be placed without a power cell when needed"
Set this change aside separate from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2829 so it doesn't bog the other stuff down or vice-versa.
This is aimed specifically at making it less of a pain in the ass to add support for mechs that can be spawned via a `place_monster` item. Presently not useful in vanilla but it could be in the future, out of repo it's useful for Arcana.
1. In monster.cpp, change `monster::monster` so that mechs don't spawn with a battery pre-loaded.
The reason for this is, if you have a source of the monster from an item, there's the possbility that it may have been crafted or otherwise loaded, such that the player is well aware how …
=> Separate starting battery from mechs

src/game.cpp, src/main_menu.cpp, src/worldfactory.cpp, src/worldfactory.h
SUMMARY: Bugfixes "Update `last_world_pos` considerations"
Several issues noted with current version, namely
- Saving the game and returning to the main menu does not update last_world_name properly
- last_world_pos returns wrong offset on deleting/creating a world.
First issue has been solved on DDA but I was unable to git blame the commit, though I was able to find the solution code. If someone is willing to step forward with the commit I will add them as co-author.
Second issue was solved on DDA as well, but produced more issues and in my opinion was inefficient.
- CleverRaven/Cataclysm-DDA#64795 and subsequently  CleverRaven/Cataclysm-DDA#65124 solved it via making `last_world_pos` a class variable and incrementing/decrementing it on world create/delete
In general, I believe that …
=> Update `last_world_pos` considerations

data/json/recipes/food/meat.json
SUMMARY: Balance "Adjust chili recipe to make more feasible to craft and satisfy chili nerds"
Chili. It's always an interesting food item, but also one that is an endless source of arguments about what goes in it. Down in my part of the US it generally doesn't include beans or tomatoes (maybe, honestly for every 2-3 people online I've seen insist Texas-style chili doesn't have beans, I've seen 1 dissenting opinion insisting it should have it), but those ingredients are standard in other parts of the US.
The easiest way to allow both styles both would be to adjust the recipe a lil, so that the ingredients list reasonably allows the player to construct a version suiting either preference. This also improves availability of the recipe by making some of the recipe's component slots easier to …
=> Expand recipe options for chili con carne

src/grab.cpp
Balance "player can drag heavier vehicles"
port https://github.com/CleverRaven/Cataclysm-DDA/pull/64867 by @anoobindisguise
1. ported line changes.
2. extracted calculation functions from `grabbed_veh_move`.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/55ae56d4-0223-48f5-8a61-5c7ee7881931
=> feat: drag heavier vehicles

data/json/items/book/misc.json, data/json/mutations/mutations.json, data/json/npcs/necropolis/NPC_Old_Guard_Captain.json, data/json/npcs/necropolis/NPC_Old_Guard_Commo.json, data/json/npcs/necropolis/NPC_Old_Guard_Soldier.json, data/json/npcs/refugee_center/surface_visitors/NPC_old_guard_representative.json, data/json/professions.json, data/mods/CRT_EXPANSION/scenarios/crt_classes.json, data/mods/Fuji_Mil_Prof/prof/army.json, data/mods/Fuji_Mil_Prof/prof/spc.json, data/mods/more_classes_scenarios/cs_classes.json
SUMMARY: Content "Allow alternative ways to access necropolis quest chain"
One of the ideas on my todo list concerned making the necropolis actually factor into the existing questlines, and open additional ways to actually get the missions from them. This PR will set things up to allow that connection and make any other ways we want to open the mission chains up easier to implement too.
Actually making military identification a specific item the player has to have that all military professions start with. Seems pointless to me, and too easy to potentially confuse with military ID access cards.
2. Load-tested changes in test build.
3. Speedran the Old Guard rep mission chain, confirmed I got referred to a necropolis at the end of it.
4. …
=> Old Guard expansion: a trip to the necropolis

data/json/itemgroups/science_and_tech.json, data/json/mapgen/lab/lab_floorplans.json, data/json/mapgen/microlab/microlab_generic_edge.json, data/json/mapgen/microlab/microlab_special_tiles.json
SUMMARY: Content "Add new storage room variations to microlabs"
This works towards implementing the other half of https://github.com/cataclysmbnteam/Cataclysm-BN/issues/971 via adding more rooms that store different items. The goal is injecting some variations that provide materials that become useful later on as you explore regular labs, making microlabs better at serving as a supplement to labs and thus encouraging you to visit both.
1. Added three new variations to the `microlab_generic_edge` mapgen pool, containing mildly useful equipment and supplies (but less exciting than what the center tiles can yield). One's a simple electrical workstation with potential to find assorted goodies (including a suggestion by Lostman to find uncommon vehicleparts), another's a utility area in the …
=> Expand room variation of microlabs

data/json/items/tool/metalworking.json
SUMMARY: Content "Gave forge and char_forge the SAW_M and SAW_M_FINE tool properties to simulate the ability to melt metal items down into their base components."
Realistically, if you have access to a forge, you should be able to use it to melt down metal items into ingots or other metal items. This was simply a basic implementation of that.
I added one line to each of the two items under json/items/tool/metalworking.json, giving them the metal sawing and fine metal sawing tool properties.
We could implement a secondary disassembly requirement and give forges the ability to melt down steel items, but I am not good enough at coding to do that myself.
The json checks out, since it's just two lines added.
=> Made forges have metal sawing properties

data/json/itemgroups/art_antiques_crafts.json, data/json/items/armor/shields.json, data/json/recipes/armor/other.json
<!-- This section should consist of exactly one line, formatted like this:
SUMMARY: [Content] "Two new shields, one reinforced with leather and one reinforced with steel, plus recipes adding the steel one to the medieval itemgroup."
The wooden shields are a good start, but there needed to be shields in-between crude wood and modern riot shields. These serve that purpose.
There are two new shields, made using a basic wooden shield and either leather or steel and forging equipment. Each one has the sturdy flag and more armor than the basic wooden one.
We could add in pure metal and leather shields, but I feel like reinforcing an existing wooden shield would work best.
I tested out the json myself to make sure it functions.
=> Added in new shields

data/json/itemgroups/Clothing_Gear/clothing.json, data/json/itemgroups/Locations_MapExtras/mansion.json, data/json/items/armor/shields.json
SUMMARY: Balance "Minor JSON fixes for new shields, implement item spawns in a few more groups"
A couple followup updates pertaining to the new shields.
1. Fixed the `extend` to apply the flag to the baseline versions instead of re-applying a flag already asked for explicitly to the large ones.
2. Fixed large shield variants not having the same bash and to-hit as the large wooden shield.
3. Added a few more spawn injections derived from current use in the DDA version of Medieval Mod Reborn: https://github.com/chaosvolt/cdda_medieval_mod_reborn/blob/master/Medieval_Mod_Reborn/item_groups.json
Screaming.
=> Follow-up consistency updates for new shields

data/json/items/armor/shields.json
SUMMARY: [Bugfixes] "Fix flags on leather and banded shields."
Chaosvolt accidentally gave them an extend function, believing they were copying from the wooden shield; this merely returns their flags to them.
It's two lines in the json, mostly copying from the basic wooden shield.
We could make the leather and banded shields use the copy-from line instead. I don't particularly care either way.
It works fine. It's just two lines.
=> Fixed shield flags

data/json/items/melee/swords_and_blades.json, data/json/recipes/weapon/piercing.json
SUMMARY: [Content] "Swords with wooden handles are now nonconductive, plus a dagger weapon."
Melee is hampered by weapons which conduct electricity, since shocker and zapper zombies can quickly injure you using conductive equipment and weapons. If a sword has wood in its crafting recipe, that means it has a wooden handle, and that means it wouldn't conduct electricity to you when wielded. Furthermore, you can make a baselard, but you can't craft a genuine combat dagger that's better than the baselard, which is a shame.
I gave the nonconductive flag to every ingame sword that uses wood in its crafting recipe, plus a new item and corresponding recipe for a good player-made dagger.
We could keep swords as they are, but that hampers their usefulness when facing electrical zombies. As for the …
=> Nonconductive swords with wooden handles

data/json/recipes/other/vehicles.json
SUMMARY: [Balance] "[Add in rockwheel recipe]"
The rockwheel is a very useful ingame item for fortifying a base, but it's fairly rare and there are no other simple ways to dig large trenches, such as a construction recipe. Adding in a recipe for the rockwheel, requiring a lot of time and steel to make, simply makes it easier to get one.
I added in a recipe for the rockwheel.
We could make rockwheel-bearing vehicles more common, as they're pretty normal to find in construction sites.
It's just a recipe, so it's not difficult to test. The json works fine, though I'm not 100% on the recipe requirements.
=> Added in recipe for rockwheel

data/json/furniture_and_terrain/terrain-floors-outdoors.json, data/json/furniture_and_terrain/terrain-flora.json, data/json/furniture_and_terrain/terrain-fungal.json, data/json/furniture_and_terrain/terrain-traps.json, data/json/furniture_and_terrain/terrain-walls.json, data/json/items/tool/explosives.json, src/map_extras.cpp, src/mapgen_functions.cpp
SUMMARY: Features "Explosions blast terrain down to shallow and deep pits to form craters, before finally punching through z-levels"
So for quite a while I've wanted to make it so that explosions can leave craters on the ground instead of always punching big, janky holes in the floor. I recall running into problems last time I tried this, but I think I found what I did wrong.
JSON changes:
C++ changes:
A note on that while I'm at it: Having `bash_below` turned on has some weird, janky behavior if you try to implement decent-looking craters. It will let the explosion propagate down and then fill the "crater" with patches of rock floor.
1. Adding shallow and deep craters to rock floors, that can't normally be dug (unless we added that as a thing for pickaxes/jackhammers) but can be used to …
=> Explosions leave craters in the ground, update mapgen/MX craters accordingly

data/json/professions.json
SUMMARY: Balance "Allow riot control officer profession to start with riot shield, swat CQC specialist profession ballistic shield"
For a bit more flavor and to make a couple professions a bit more interesting to start as, not to mention more usage of the new shields.
1. Set the riot control officer profession to start with a riot shield. Fitting given the name, and its starting gear was a tad underwhelming for a 5-point profession anyway (pistol, gas mask, and helmet being the only real highlights, they notably don't start with riot armor itself).
2. Added the ballistic shield to the SWAT CQC specialist profession. Also an interesting fit for the profession, though compared to the riot control officer their gear is pretty decent overall.
3. Bumped the CQC profession's point cost up from …
=> Allow riot officer and swat CQC to start with shields

data/json/furniture_and_terrain/furniture-fireplaces.json, data/json/furniture_and_terrain/furniture-storage.json, data/json/furniture_and_terrain/terrain-fences-gates.json, data/json/recipes/armor/arms.json, data/json/recipes/armor/feet.json, data/json/recipes/armor/hands.json, data/json/recipes/armor/head.json, data/json/recipes/armor/legs.json, data/json/recipes/armor/storage.json, data/json/recipes/armor/suit.json, data/json/recipes/armor/torso.json, data/json/uncraft/generic.json
SUMMARY: Balance "Allow small metal sheets in some fitting recipes, adjust drop rates of sheet metal in certain furniture/terrain"
Makes a bit increased usage of sheet metal in improvised recipes, along with a tweak to make it a bit more feasible to get the larger one in certain situations.
1. Added small metal sheets as a material option to the recipes for metal greaves, large quivers, scrap arm guards, scrap boots, armored fingerless gloves, scrap helmet, scrap leg guards, XL holster, axe ring holster, bow sling, plated leather armor, scrap armor suit, scrap curiass, armored leather jacket, and armored leather vest. All at a rate of generally equal to the number of steel chunks used (or just 1 if less than 5 scrap is used), based off the uncraft returning 5 scrap metal. These are all …
=> Update sheet metal acquisition/usage

src/monexamine.cpp, src/monexamine.h
SUMMARY: Interface "Allow retrieving individual items from a mount's stored items"
This adds a QoL feature I'd been pondering about for a while. Having "dump everything that you stored in your mount's saddlebags" obviously is not ideal when you just want to grab a single item. Making menus is...clunky and weird but figured the rough basics out.
Added `monexamine::take_items_from` function to monexamine.cpp, cannibalized from random bits and bobs of `monexamine::dump_items`, `monexamine::add_leash`, and `monexamine::remove_leash` as references, plus @joveeater's help with the `erase` function at the end that actually removes the chosen item from the monster's inventory.
Removing the "dump all items" command, I'd say keep it for now because this menu makes you pick one item to retrieve at a …
=> Add command to pet menu for removing individual items from storage

data/json/uncraft/generic.json
SUMMARY: Balance "Engine blocks can be sawn down for steel lumps"
This adds the option to saw down engine blocks for scrap metal based on their weight, since as they are currently they aren't that useful once you've taken the entire engine apart.
Added uncrafts for tiny, small, medium, large, and massive engine blocks. Has the same basic requirements as most "turn this uncraftable metal thing into steel lumps" uncrafts, with escalating time as you go up in size. Steel lump yield matches the weight of the engine block exactly, due to each item weighing an exact amount of kg and steel lumps being 1 kg in weight each.
Also letting you craft your own engines if you find the parts for them, possibly allowing makeshift parts where relevant like with drive belts.
If we also made it so a …
=> Allow scrapping engine blocks for steel

data/json/recipes/chem/chemicals.json, data/json/requirements/materials.json
SUMMARY: Balance "Make lye powder 1 lye at a time, add crafting requirement for consistent recipe uses"
It was brought up in the BN discord that making lye powder 6 lye at a time was a bit bothersome.
Along the way it became clear that the ratio between lye powder and lye in recipes was wildly inconsistent.
1. Standardized the ratio of lye to lye powder at 1:30 (very close to the ratio for the recipe making lye poiwder from lye) via implementing a crafting requirement to use for it.
2. Changed the `from_lye` recipe for lye powder to only take 1 lye, output 30 lye powder, as per above. Updated time and heating requirements accordingly.
3. Updated other recipes in the chem folder to use the new crafting quality. Ammonia recipe was left untouched though since it uses a small amount of lye …
=> Standardize use of lye and lye powder, smaller batch recipe

data/json/furniture_and_terrain/terrain-floors-outdoors.json, data/json/furniture_and_terrain/terrain-flora.json, data/json/furniture_and_terrain/terrain-traps.json
SUMMARY: Bugfixes "Use NOCOLLIDE to make vehicles not crash into grass"
Found out I fucked something up and didn't realize that vehicles don't like stuff that can be bashed into non-null stuff if it also has a slow movement cost. Turns out it's an easy fix at least but oof.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2891
Added `NOCOLLIDE` flag to all terrain affected by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2842 to have a `move_cost` of 3 or higher.
1. Lowering move cost penalties or otherwise figuring out what will help reduce the problems this can still cause.
2. Reverting the PR that caused this because fuuuuck I didn't think it'd cause this much trouble.
2. Tested that running a car across …
=> Fixes for vehicles over grass

src/grab.cpp
SUMMARY: Bugfixes "Implement a cap on dragging strength requirement based on vehicle weight, fixing shopping carts getting stuck while empty"
This changes how difficulty for dragging a vehicle is determined, specifically so that lightweight vehicles don't get punished to a wacky extent such that a little bit of grass makes a shopping cart immobile while empty.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2897
1. In grab.cpp, defined `offroad_str_req_cap` that equals vehicle weight divided by 10 kg, or one tenth the effectiveness of `base_str_req`
2. In `game::grabbed_veh_move`, set it so it sanity-checks modified strength result by comparing the results of `get_vehicle_str_requirement` against `offroad_str_req_cap`. If they don't match up, as it generally does when you're …
=> Sanity-check effect of rough terrain on dragging light vehicles

src/avatar_functions.cpp, src/consumption.cpp, src/consumption.h
SUMMARY: Features "Make unloading faction owned items be considered stealing"
Fixes #2491 - makes it so that unloading an owned item is seen as stealing by the owned faction in the same way as eating owned food is
Borrowing from the system already in place for dealing with eating stolen food, I added the following:
- add and inherit for "pickup.h" to "avatar_functions.cpp" to leverage the same thief selection menu as when picking up a stolen item (Yes, No, Always, Never)
- Create function query_interaction_ownership copying from query_consume_ownership, using the same functions (query_thief, handle_theft witnesses) but with a reset for THIEF_MODE if THIEF_MODE_KEEP is not set to YES
-  Add a check using query_interaction_ownership - if the function returns false the player has chosen not …
=> Make unloading faction owned items be considered stealing

data/json/game_balance.json, src/options.cpp
SUMMARY: Features "Add Animal Spawn Rate scaling factor option to Worldgen"
Fixes #2795 - adds animal spawn rate to worldgen options in both initial setup and in-game menu
- Add option for SPAWN_ANIMAL_DENSITY within options.cpp, set min, max and default the same as Spawn Density
- Remove external option from game_balance.json in core data
Leaving this as an external and not internal option
- Built game in debug and release mode with the option change
- Created world, noted option was available in the world gen
- Loaded world, noted that settings had transferred to option screen after removing external option
- Upped scaling to 50.00, noted vastly increased animal spawns 
- Loaded older world created before change, animal spawn rate set as 1.00 due to external option setting
- Modified …
=> Add Animal Spawn Rate scaling factor option to Worldgen

data/json/mutations/mutations.json, src/npc.cpp
SUMMARY: Bugfixes "Killer Drive now rewards for killing innocent NPCs, prompts before committing cannibalism"
One annoyance I found was that Killer Drive clashed with the Psychopath trait, motivating you to kill but still prompting guilt when you kill an innocent NPC. It also had the flaw where the `CANNIBAL` trait flag would mark human flesh as safe to eat and fail to prompt you, but because the morale effect only looks for the Cannibal trait itself, you'd end up getting sad about it.
C++ changes:
1. In npc.cpp, set it so the check for inflicting morale from murdering an innoect NPC also excludes characters with the Killer Drive trait.
2. Additionally, set it so killing NPCs counts as a kill for the sake of the Killer Drive morale effects. This is separate from the other morale effects …
=> Fix Killer Drive trait not liking murder, not prompting on cannibalism

data/json/npcs/refugee_center/surface_refugees/NPC_Jenny_Forcette.json
SUMMARY: Bugfixes "Fix Jenny Forcette to acknowledge previous meeting"
To fix Jenny Forcette so she acknowledges meeting player before
Noticed during prep work on my mod after searching u_has_effect in core data that this should be u_has_var in Jennys dynamic line greeting to acknowledge previously meeting player, changed this in JSON file
Leaving it as is
Loaded into base game and tested, Jenny now greets properly second and subsequent times
=> Fix Jenny Forcette Greeting

data/json/obsoletion/recipes.json, data/json/recipes/other/containers.json
SUMMARY: Balance "Obsolete extra gallon jug recipe "
There were two recipes for gallon jugs. Both required the same ingredients and tools but one took 15 less fuel charges, 5 more minutes and 1 more difficulty in fabrication.
I obsoleted the extra one which took longer with less fuel charges, as using a campfire or a base setup with tons of power generation means consuming more charges for less time is always optimal.
This second recipe could lose the plastic mold requirement and take considerably longer, but almost every other plastic recipe requires a plastic mold AND there is few examples where not making a plastic mold is in your best interest as justifying this would mean it taking quite a bit longer, not to mention we'd want to add a mold-less version of every other recipe to keep …
=> Obsolete extra gallon jug recipe

data/json/mapgen/map_extras/wilderness.json, data/json/overmap/map_extras.json
SUMMARY: Bugfixes "Collapsed sheds have roofs over normal tiles and no roof over the actual collapse, fix appearance on minimap"
Fixes some assorted oddities observed with the collapsed shed map extra.
1. Set it so the basic tiles use the default tile of the palette and thus still have a roof.
2. Conversely, set the fixed piles of rubble, the presumed collapse of said collapsed sheds, to have outdoor dirt instead of dirt floor (which made them the only part of the interior to have a roof).
3. Added a bit around the edges of the rubble that add a bit of random chance of being intact or not, along with varying chance of also having rubble.
4. Fixed shed's auto-note being visible on the main map but becoming a solid black sqaure on the minimap, this was due to it lacking a symbol in its …
=> Adjustments to collapsed shed map extra

data/json/items/melee/bludgeons.json, data/json/items/melee/spears_and_polearms.json, data/json/items/melee/swords_and_blades.json, data/json/recipes/weapon/piercing.json
SUMMARY: Balance "Rebalance 2-by-sword and nail sword, add long pointy stick"
Per some discussion in the BN discord.
1. Moved the 2-by-sword and nail sword into the sword file, as it's a bit weird having the sword-like objects divided up like this, plus they're getting some related stat changes that will make their damage weight less towards bashing.
2. Changed the 2-by-sword's damage from 12/1 to 4/10, and gave it stabbing damage instead of cutting. Rationale being to balance it relative to the comparably easy to make pointy stick (where it skews slightly less damaging but with faster attacks) as well as give it a bit more to contrast with the cudgel. Stab damage is because you're more likely to be thrusting with the sharpened tip.
3. Likewise, changed the nail sword to 4/14 damage. Much …
=> Updates to low-tier wooden weapons

data/mods/Magiclysm/monsters/golems.json
SUMMARY: [Mods] "Removed regeneration from Magiclysm plastic golems"
It is well known to Magiclysm users that plastic golems from Wizard Towers can clear an entire city for you because they have good combat stats, insatiable bloodlust, and can regenerate health. Removing their regeneration fixes this, in my mind there's no reason the golems are enchanted to regenerate, or that it wore off due to a lack of maintenance.
Removed the regeneration field from their JSON.
Nerfing any other aspect of plastic golems instead.
Loaded up the change, spawned them in, watched the carnage.
Soon owlbears will lose their insatiable bloodlust.
=> Magiclysm: Plastic Golems no longer regenerate

src/avatar_action.cpp, src/monster.cpp
SUMMARY: Bugfixes "Feral survivors and Mycus properly displace friendly monsters instead of attacking, zombies ignore sounds near feral players"
Some related improvements to playable ferals to make some of the quirks I found previously less annoying, fixing two things I ran into while testing the Lost and Damned PR.
1. In monster.cpp, `monster::hear_sound` so that sounds made near a feral player are ignored by zombies/ferals, so they'll stop crowding around you, smashing up all your shit, and following your footsteps.
2. In avatar_action.cpp, added a bit to `avatar_action::move` to make certain the player won't take a swing a monster that's considered a friend when trying to move into their space. This not only fixes feral players taking a swing at their fellow zeds, it also fixes Mycus …
=> Improvements to feral survivor and Mycus experience

data/json/furniture_and_terrain/terrain-floors-outdoors.json, data/json/furniture_and_terrain/terrain-flora.json, data/json/furniture_and_terrain/terrain-traps.json, doc/JSON_FLAGS.md, src/map.cpp, src/vehicle_autodrive.cpp, src/vehicle_move.cpp
SUMMARY: Bugfixes "Vehicle collision stops when result is no longer a valid obstacle, also fix autodrive "
Yet another bug with craterization to resolve, this time fixing shrubs getting rammed directly into deep pits and usuully fucking up your wheels in the process.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2923
After a false start, I figured out a better method that makes more sense for fixing this, as well as being a less wacky alternative fix to https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2891 that doesn't cause medium boulders to ignore collision if they're in a shallow pit, and additionally fixes autodrive not treating long grass as valid terrain.
C++ changes:
1. In map.cpp, updated `map::is_bashable` to treat the presence of the new …
=> Fix vehicles turning bushes into pits

src/ranged.cpp
SUMMARY: Bugfixes "Fix RAS weapon range in `target_ui`"
- #2468 created issue #2915 due to ammo not being loaded until being fired.
Spawn temp item for use in range calculation.
- Load weapon before starting `target_ui`
- Considering the sheer amount of work I did to prevent that. No.
- Spawn sling, unload rock from it and spawn a marble. Set all attributes to 8 and skill to 0.
- #2468 really is the gift that keeps on giving.
=> Fix RAS weapon range in `target_ui`

data/json/scenarios.json
SUMMARY: Bugfixes "Swap obsoleted Ursine Eyes trait in mutant scenarios for High Night Vision"
While working on an unrelated thing I discovered that the ursine eye mutation had been obsoleted but was still used in mutant scenarios, since I didn't notice last time I touched the trait list that they were obsolete.
Swapped the obsolete `URSINE_EYE` mutation for High Night Vision in Lab Patient and Experiment scenarios, fitting since this is another interesting mutation to play with that's pre-threshold and doesn't have any weird prereq behavior.
1. Adding Infravision instead since it changes things up more. Only problem is it's post-thresh and has requirements it doesn't supersede.
2. Added Reptilian IR instead, it's not pre-thresh but also intended to be picked up alongside Reptilian Eyes …
=> Fix mutant scenarios adding an obsoleted trait

src/overmap.cpp
SUMMARY: Bugfixes "Fixes too many mods preventing some locations from spawning"
When too many mods are enabled it becomes common for overmap specials to crowd each other out. This results in only the first to be placed actually being able to fit.
Shuffle the order in which they're placed for every overmap tile.
I got a lab to spawn with a bunch of mods turned on after failing on 4-5 overmaps with the same set before the patch. It's hard to be sure what's rng though.
This isn't an ideal solution but it does do a lot to alleviate the problem and restore variety when too many mods are turned on.
=> Shuffle overmap specials

data/json/items/armor/shields.json
SUMMARY: Bugfixes "Buckler no longer inherits from banded shield, fixing unintended hand coverage"
Fixes bucklers so they don't suffer from the inheritance problems as reported in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2939. Does not fix the underlying code problem since I have no idea what causes that.
Converted bucklers to not inherit from the banded shield, so they correctly don't end up mysteriously inheriting hand coverage from it.
Screaming at the src folder until I find what ancient code spaghetti causes the underlying problem.
2. Load-tested in compiled test build, buckler showed it only covered one arm, no other stat differences evident.
=> Convert buckler to not inherit hand coverage from banded shield

data/json/recipes/other/other.json
SUMMARY: Balance "Cots can be crafted and uncrafted"
Cots had no crafting recipe nor uncraft, making them a portable bed that is fairly useless since generally you'd sleep in your car anyway. This lets you make them should you want one, and uncraft it for valuable aluminum in case you found one in the wild.
The cot is based on welding together aluminum ingots just like an extra-light frame, but I also included fine hammering, drilling, and fine metal sawing. While a frame needs to be one concise piece of metal, a cot is designed to be assembled and disassembled quickly. You can assemble one within 60 seconds IRL according to training videos on Youtube that U.S. Army veterans have made. Thus, the pieces have to correctly fit together, so drilling holes and sawing pieces to what they need …
=> Cots can be crafted & uncrafted

data/json/requirements/ammo.json, data/json/uncraft/ammo/10mm.json
SUMMARY: Balance "Set 10mm auto to use large pistol primers instead of small"
So I was looking at some things and, reminded that large pistol primers seem relatively underused among ammotypes, decided to look up what type some common ones use and only really found one case where an ammo uses the wrong primer type. In this case it does at least mean one more ammotype using large primers instead of the more commonly-used small ones.
1. Updated `ammo_10mm` crafting requirement and to use large primers instead of small. Quick search indicates that .40 S&W using small primers and 10mm auto using large primers is indeed a thing.
2. Likewise updated the uncraft for 10mm ammo.
1. Making other ammo use large primers anyway, realism be damned.
2. Migrating large pistol and rifle primers so we only …
=> Update 10mm auto to use large pistol primers

data/json/mutations/mutations.json
SUMMARY: Bugfixes "From 'though' to 'through'"
Fixes a very minor spelling error.
Adding a single letter.
Leaving it be.
A single letter change is all that is.
Good day to everyone.
=> style: typo in `Lost To The Cataclysm` profession

data/json/monsters/misc.json, src/character_functions.cpp, src/iuse_actor.cpp, src/npc.cpp
SUMMARY: Bugfixes "Fix how NPCs handle loose sheath/holsters"
- Fix #2947  
Caused by NPCs attempting to invoke the holster which causes a crash as it's not appropriately handled.
Route through the same code that allows them to wield an item from worn holsters/sheaths.
This PR also adjusts the `diff` value for debug monsters so they're still threatening enough to shoot at 100 but not so threatening most NPCs will run away in terror (2000+).
- ~~Fix holster iuse so NPCs can properly invoke it.~~
- ~~Maybe for the future, right now this works and is fairly clean.~~
- Done, but NPCs will still not use it in this iteration because the code is cleaner with fewer checks and branches, and if an NPC fails to wield an item from the holster, only one function need be checked. 
- Give NPC a sheathed …
=> Fix how NPCs handle loose sheath/holsters

data/json/monsters/nether.json
SUMMARY: Balance "Fix grackens lacking the monster flag I'd said I'd given them in last PR"
Noticed that I'd forgotten to actually give grackens the `HUMAN` flag like I said I did in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2926
Added the monster flag.
Screaming.
More seriously, giving them the `mutant_human` harvest entry instead of `human`, presumably still retaining the `HUMAN` flag.
Checked affected file for syntax and lint errors, used my fucking eyes to confirm I'd actually given it the flag this time like I said I did.
=> Fix forgotten monster flag

data/json/mapgen/house/house25.json
SUMMARY: Bugfixes "Belatedly port over fix to house variant with safe spawning on shrubs"
Every so often I'd see the one house variant that spawns an open safe over some shrubs indoors, go "that's weird, is that a Cata++ thing I didn't fix for Noct?" before finding out it was vanilla, resolving to fix it, and forgetting about it.
After I fixed it I went to check if it was still broken in DDA and found a PR fixed it but also removed some unused terrain and furniture from it. Ended up just deciding to make it a port PR via also doing those changes too I guess.
1. Set that one weird `house_25` variant with the safe to not place shrubs where the safe goes, and set it to spawn a locked safe instead of open.
2. Also as per DDA's implementation, removed some terrain and furniture defs that …
=> Fix open safe spawning on indoor shrub in house variant

src/bodypart.h, src/item_factory.cpp
SUMMARY: Bugfixes "Make `covers` field be overwritten properly."
When "overwritten", the `covers` field inherits the old and only adds newly set entries.
Add reset function that only triggers if `covers` is defined so that during `copy-from` it is properly overwritten
- Change away from bitset
- Not now, it's useful this way, though if we add json definable body plans in the future this will have to change somehow.
- Revert #2940
=> Make `covers` field be overwritten properly.

data/mods/Magiclysm/harvest.json
SUMMARY: [Mods] "Fix Harvest products in Magiclysm"
With the recent feral humans update I noticed they were dropping normal chunks of fat. I went over the file and found several harvests that could use updating.
First, their human override now gives human fat and human skin correctly. Dragons were giving two types of meat and were switched solely to dragon meat. Lemures gave tainted blood but normal meat and a note said they were meant to be tainted, so I switched them to tainted meat.
Not fixing this because eating people is half the game and cannibals unfairly get all the fun.
Changes loaded in and tested without issue, correct products below.
=> Magiclysm harvest fixes

src/bionics.cpp
SUMMARY: Bugfixes "Solar panel CBM now only provides power when outside in sunlight."
After installing the solar generator CBM and turning it on, I noticed that it produced power regardless of location or time. Obviously solar panels recharging bionics while at the bottom of a mine at night isn't working as intended.
The if/else chain for perpetual fuel types was continuing to the bottom "make power anyway" section if the fuel type was sunlight but you weren't in sunlight. That no longer happens, and if you aren't in sunlight it makes no power.
Accepting free power from the bionic wizards.
Debug installed the solar CBM and some power, turned it on.
1. No power when inside the evac center under a roof
2. No power when in the basement.
3. Power when walking outside.
4. No power after …
=> Solar panel CBM no longer provides power at all times

src/suffer.cpp
SUMMARY: Balance "Reduce wet effects on morale to reasonable levels"
Overall, wet effects in-game seem quite intolerable. You stand in some puddle for a single moment and now you are too depressed to even read a jovial book. As a result, I have decided to reduce the affects of water and its dastardly effects upon the player.
Simply put, being wet now no longer makes you questioning your existence.
Mermaids must've infiltrated the development team to convince us landgrubbers to despise their watery home to protect it from humanity's inhumanity or something because I can't exactly see how water constitutes such drastic influences on someone's morale.
Beep boop, some simple number changes, that's all.
Stay hydrated!
=> Reduce wet effects on morale to reasonable levels

data/json/recipes/food/seeds.json
**SUMMARY: [Bugfixes] "Allow creation of cabbage seeds from cabbages"**
**Purpose of change**
Adds cabbage seeds to recipes, following other vegetable seed recipes. Surprised this wasn't there when I tried to continue farming with them.
**Describe the solution**
Copied text from chamomile in the seeds.json
**Testing**
Fired up in existing game, no problems with recipe.
=> Allow creation of cabbage seeds from cabbages

data/json/scenarios.json, data/mods/Hydroponics/construction.json, data/mods/More_Locations/terrain.json
SUMMARY: Mods "Some updates to obsolete mods just in case anybody uses them"
While fiddling around with mods, I came across some bugs. More Locations and Hydroponics were throwing simple errors, so I took the liberty of quickly fixing them up.
Edit: Also changed the spelling "cataclysm" into "Cataclysm" for the Lost and Damned scenario.
Hydroponics used "post_terrain" for furniture which apparently got depreciated for "post_furniture" while More Locations had "t_rock_floor" as a roof when "t_rock_roof" existed. Kenan's Modpack appears to have altered it to a concrete roof, but I went through the game files and found out that indeed, rock floor had a matching rock roof palette. :)
Leaving them be.
Basic changes, so no errors or bugs.
Hope everyone is doing great 💯
=> Some updates to obsolete mods just in case anybody uses them (like yours truly)

src/handle_action.cpp
SUMMARY: Bugfixes "Add warning for smashing with glass item"
- Partially deal with #2925 by adding a warning.
Add warning so when you try to do something like this the game queries if you're _sure_ you want to hurt yourself.
- Code for items to be more or less of a material and be more discerning about how much damage and what items are eligible for hurting yourself.
- Would be nice but I don't wanna, it's a lot of work.
Wield a glass fridge, press s and be queried about my self-harm tendencies.
I don't see a good way to make it shatter the fridge, it currently already uses the `handle_melee_wear()` function on the refrigerator so it's clear that the steel is protecting the fridge. I can't set the code to fire for items made purely of glass as flasks and test tubes have rubber as a …
=> Add warning for smashing with glass item

data/json/items/tool/workshop.json
SUMMARY: Balance "Give Weapon Category to makeshift hammer"
I noticed while playing the game that stone hammers have a Weapon Category, while makeshift hammers did not. Both are nigh-identical, so I decided to give the makeshift hammer a Weapon Category befitting it.
Copying and pasting one line.
Makeshift hammers are hammers too. They deserve justice.
No issues.
Hope everyone is doing great!
=> Add Weapon Category to makeshift hammer (same as stone hammer)

data/json/construction.json, data/json/recipes/basecamps/recipe_modular_firestation1.json
SUMMARY: Bugfixes "Only call for solder once in grid constructions"
Fix this:
1. Removed cases of redundant calls to solder in grid constructions. All of them already included `soldering_standard` in the construction to begin with.
2. Updated faction camp blueprints.
Living with components list looking weird and bothering me.
2. Load-tested to confirm the code snek did its job.
=> Fix grid constructions calling for solder twice

lang/extract_json_strings.py
SUMMARY: I18N "Account for optional body part fields when extracting json"
- fix #2978 
made finding `heading_multiple` and `encumbrance_text` optional.
scream
it works on my machine! /s
<details><summary>Before</summary>
```
~/r/c/Cataclysm   $-  lang/update_pot.sh                                2023년 06월 20일 (화) 오후 08시 51분 17초
> Extracting strings from json
==> Generating the list of all Git tracked files
==> Parsing JSON
----> Traversing directory data/help
----> Traversing directory data/json
Traceback (most recent call last):
File "/home/scarf/repo/cata/Cataclysm/lang/extract_json_strings.py", line 1268, in <module>
extract_all_from_dir(state, i)
File "/home/scarf/repo/cata/Cataclysm/lang/extract_json_strings.py", line 1178, in extract_all_from_dir
extract_all_from_file(state, …
```
=> fix(L10n): make extracting bodypart fields optional

data/json/overmap/overmap_terrain/overmap_terrain_hardcoded.json, src/mapgen_functions.cpp, src/mapgen_functions.h, src/overmap.cpp, src/overmap.h
SUMMARY: Bugfixes "DDA port: Fix for acidic ant queens and acidic ant larvae spawning in ordinary ant tunnels"
Belatedly port over some fixes for acid anthills.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/786
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2968
1. Ported over changes to IDs of overmap terrain, adding acid variants.
2. Ported over changes to mapgen_functions.cpp and .h, defining acid ant variations on the larva and queen chamber rooms and reworking how the rooms are used.
3. Ported over changes to overmap.cpp and .h, where it properly uses the acid variants of the rooms.
Figuring out the least annoying way to JSONize anthills. DDA seems to rely on mutable overmap stuff which seems kinda eh.
1. Checked affected JSON file for syntax and lint …
=> Port over anthill fixes

src/iuse_actor.cpp
SUMMARY: Bugfixes "Fix invisible activation and idle messages for fire weapons"
While testing some stuff related to use actions, I noticed a familiar flaw with the fire weapon use actions. One of these days we might have use for these outside of No Hope, so.
1. In iuse_actor.cpp, set `fireweapon_off_actor::use` to also print the success message even if it also creates sound, because it doesn't actually print the results of `sounds::sound` in the message log in this case.
2. Likewise set `fireweapon_on_actor::use` to print the idle message so it actually shows on the player's message log.
Basically the same message concepts as used in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1487 to fix activation and noise messages not actually showing on message log.
1. Figuring out what the …
=> Fix fire weapon messages failing to print

data/json/recipes/other/containers.json, data/json/requirements/materials.json
SUMMARY: Balance "Allow cured hides/pelt as an alternative to leather/fur patches in clay container recipes"
This allows an additional use for cured hides/pelt, consistent with prior PRs having allowed you to use them for purposes that don't involve sewing.
1. Allowed cured hides and pelts as alternatives to leather and fur patches for hide lids in clay container recipes that use leather/fur as a makeshift lid presumably stretched over the opening (clay bowl, clay canister, clay hydria, large clay pot, clay jug).
2. Also implemented a crafting quality to extend to other recipes later on, used in the above changed recipes for now.
Allowing you to carve wooden lids instead.
=> Allow cured hides/pelts for clay containers

src/action.cpp
SUMMARY: Bugfixes "Hitting g will no longer highlight sealed crates/coffins/etc that have loot in them, spoiling which ones to open"
This fixes a problem with the code for checking whether to show the "valid direction" highlight, in which it didn't screen for whether you shouldn't be able to see the presence of valid items on that tile:
In action.cpp, changed `can_pickup_at` to make the "tile has items here" part of its return also verify that the tile in question lacks the `SEALED` flag, which would normally preclude being able to get items from them. This means you can't use `g` to sniff out whether a crate is worth prying or not anymore.
1. Letting you still use this exploit anyway just because.
2. If we want to go peak realism, let you do see the highlight if you have like 20+ …
=> Fix pickup key spoiling presence of loot in crates

src/item.cpp
SUMMARY: Features "Show (cold) or (very cold) for perishable food to indicate when fridges, freezers, root cellars etc are working at a glance"
One of the classic things I've been hoping to bring back was to make it so that storing food in a working fridge or freezer, or other conditions where the food is technically considered cold, would display a tagtext to make it easier for the player to see their fridge is actually working. Basically one of the main advantage of DDA's freezing system that was lost when the mechanic got purged for performance reasons.
Bringing it back wholesale seems like it'd be a pain in the ass to do and might still have performance worries, so adapting the current food preservation mechanics to at least accomplish that goal works too.
1. In `item::process_rot`, …
=> Temperature for food that can rot is displayed in tagtext

src/character_turn.cpp, src/game.cpp
SUMMARY: Bugfixes "NPC temporary morale sources will now decay with time."
I noticed that an NPC follower was perpetually unhappy with no apparent cause. The debug menu only showed the overall value and not the individual sources, so I poked into the save file and found piles of negative morale from all the books that I had made him read to skill up, all with age zero. Example: `{"type":"morale_book","subtype":{"subtype_type":"by_item","item_type":"atomic_survival"},"bonus":-45,"duration":3600,"decay_start":1800,"age":0}`. These were mostly balanced out by positive morale books, also all at age 0.
This can be reproduced by getting a fresh follower and making him read every 'for fun' book in a library, making him the happiest person in the apocalypse indefinitely. If you have NPC needs …
=> Allows NPC morale sources to decay

src/monmove.cpp
SUMMARY: Bugfixes "Fix monsters that can fly or climb phasing through underground terrain with CLIMBABLE flag"
This fixes weird behavior involving noclipping flying monsters.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2981
1. In monmove.cpp, set `monster::move_to` so that the check for `CLIMBABLE` terrain disallows monsters from climbing over terrain if there's a ceiling overhead.
2. Also in monmove.cpp, added similar checks to `monster::will_move_to` to further block them from moving over terrain they shouldn't be able to cross.
1. Removing `CLIMBABLE` flag from solid rock.
2. Throwing computer monitors at the offending monsters for hacking.
3. Teleported underground and debugged in some open space in between solid rock tiles.
4. Spawned in …
=> Fix monsters noclipping through underground climbable terrain

src/active_item_cache.cpp, src/visitable.cpp
SUMMARY: Bugfixes "Mitigate active item cache corruption"
Prevent stuff getting stuck in the active item cache.
The active item cache is keyed by processing time, but some items change their processing time. Such as a jar full of food becoming empty. This causes them to get stuck. It'll now search the whole cache for items it removes.
There's also a similar fix I found while looking for this. Some of the paths through visitable::remove_item weren't updating the cache properly.
Making sure that items move into the right cache as soon as their speed changes, but that's a lot more work and I'm pretty sure it's impossible to trigger this in meaningful way now.
Should be better.
Stuff getting stuck in the cache is what has been breaking the tests.
=> Fixes some active item cache problems

data/json/items/ammo/4570.json, data/json/recipes/ammo/other.json, data/json/recipes/ammo/rifle.json, data/json/requirements/materials.json, data/json/uncraft/ammo/4570.json
SUMMARY: Balance "Allow using bismuth in some recipes, related ammo fixes"
I noticed that bismuth was fairly lacking in recipe use, when its use as a lead substitute for bullets is fairly common.
1. Added bismuth to `ammo_bullet` crafting requirement, requiring 3 units (total 6 weight) per 1 unit (5 weight) of lead.
2. Added bismuth to `weights` crafting requirement, requiring 8 units (total 16 weight) per 5 units (15 weight) of lead.
3. Added bismuth to sling bullet recipes, requiring 125 units per 50 units of lead (actually matching in weight for once).
4. Fixed recipe for blackpowder .45-70 requiring some extra lead on top of calling for `ammo_bullet` already, despite being basically the cowboy load but with blackpowder.
5. Misc: Fixed some weirdness where for some reason the item …
=> Use bismuth in recipes, related ammo fixes

src/crafting_gui.cpp
SUMMARY: Interface "Replaced an example in the crafting menu with an item that exists"
When searching for items in the crafting menu one the examples uses "two by four" as an example, this exists as an id but to the player it's called "plank"
Switched "two by four" with "plank".
Ignore it.
Open the crafting menu and try to search, plank is now given as an example.
=> Updated crafting menu example with existing item

src/consumption.cpp
SUMMARY: Bugfixes "Fix display saying food is still cold after reheating"
Chaosvolt reported the display error that occurs when you automatically heat food before eating it.
1. Store if the food was "cold" or "very cold" in a bool
2. After the message that says the food was heated, unset the flags "cold" and "very_cold".
3. After the message that says you ate the food, reapply the flags to the item stack if the flags existed before. 
While the player only eats one food item the effects of the function apply to every item of the same type, so I have to ensure the flags remain afterwards.
Improve the system further by adding a "hot" flag so food items to be considered hot, as something that is recently cooked still needs to be reheated to be eaten as hot.
Before:
After:
=> Fix display saying food is still cold after reheating

data/json/recipes/other/materials.json
SUMMARY: Bugfixes "Fix paper recipe making only 1 at a time instead of 50"
Turns out when I did https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2356, I overlooked the fact that the paper recipe made 50 due to its stack size, so as a result the recipe was now making only 1 per batch. Given it takes an hour per batch that is kinda bad.
Added `"charges": 50,` to the recipe for paper, restoring prior behavior.
Screaming.
1. Converted paper back to comestible in a test build temporarily to confirm this problem did indeed exist.
2. Checked affected JSON for syntax and lint errors.
3. Ported change to test build, load-tested, confirmed the recipe now makes 50 paper at a time again.
=> Fix paper recipe making wrong amount

data/json/items/gun/700nx.json
SUMMARY: Balance "Port over changes from DDA converting elephant gun to a double rifle"
Minor improvement that's been on my to-do list for a while, back over in DDA it was noted that elephant guns tend to be double rifles, that the .700 NX rifle is in the right general size range for one weight-wise, and that giving it the ability to fire a follow-up shot gives it a bit more spice to make it more distinct from other old-school high-damage weapons like the flintlock or blunderbuss, to compliment its rarity.
Ported over changes from DDA that gives the elephant gun a clip size of 2, halves its hefty reload time (since gotta do it twice), adds `RELOAD_ONE`, and updates the description.
Adding a separate double-barrel version as an excuse to make the single-barrel version spawn in different …
=> Port over change making elephant gun a double rifle

data/json/recipes/weapon/ranged.json
SUMMARY: Balance "Net and bolas recipes can now be reversed back into base components"
Every time I spawn in a swamp shack, I get bugged about how it's impossible to take apart the net that always spawns there.
1. Added `reversible` to the recipe for nets, since it's a relatively simple recipe.
2. Also noticed bolas can't be taken apart either, so made those reversible too.
1. The need for a sewing tool could possibly be removed from the net recipe, as it's more along the lines of weaving than sewing.
2. Allowing natural cordage in the recipe could also reasonably be allowed.
=> Make net and bolas recipes reversible

data/json/recipes/ammo/components.json
SUMMARY: Balance "Make primer recipes in batches of 100 instead of 200 to be more granular, add copper as a component option"
Some things that came to mind to make primers a bit less of a pain to make.
Set it so that primers are made in batches of 100 instead of 200, cutting time and materials in half to make it a bit more granular. In addition, added copper and scrap copper to the materials for more variety.
1. Scrapping the use of cans and scrap metal in exchange for only allowing copper (maybe silver and a few other relevant small metals) to enable making them in even smaller batches. Hell if we wanted, most primers it seems weigh less than a gram, and the code does support using milligrams if I recall, meaning taking 5-10 units of copper and making a small number of primers would …
=> Make primer recipe more granular, add to component options

src/npcmove.cpp
SUMMARY: Bugfixes "Fix segfault when NPC is set to use silent weapons."
User on Discord reported that DDA NPCs caused segfaults when set to use silent weapons. Checked and the problem persists in BN, if slightly different, core issue is NPCs checking for `is_silent()` on non-gun items, causing null references.
Only check `is_silent()` if the object in question is a gun. Also restructured the arguments a bit so the faster ones are in front.
Mind Control NPC and give them a rule to use silent weapons, then give them a gun, check that they will not use the gun but instead attack the target in melee. Remove rule and check that they will then use the gun.
=> Fix segfault when NPC is set to use silent weapons

data/json/furniture_and_terrain/terrain-railroads.json, data/json/items/generic.json, data/json/items/melee/axes.json, data/json/items/melee/bludgeons.json, data/json/items/tool/metalworking.json, data/json/items/tool/woodworking.json, data/json/items/vehicle/plating.json, data/json/recipes/other/tools.json
SUMMARY: Balance "More use of mid-tier axe, hammer, and anvil quality for relative items"
This fixes some peculiarities here and there with tool qualities, making progression as skills escalate a bit more smooth, and lays some of the groundwork for once of these days when I eventually make variations in anvil quality actually matter some.
1. Increased axe quality of copper axe from 1 to 2, as it uses a harder to get material that takes more work than stone, plus this reasonably makes it in between the stone axe and a proper forged axe in quality.
2. In exchange, bumped the recipe for copper axe from 3 fabrication to 4, putting it in between stone axe and the proper wood axe.
3. Increased hammer quality of sledgehammers and warhammer from 1 to 2. Idea is, these are comparable to the …
=> Updates to axe, hammer, and anvil qualities

src/game.cpp, src/iexamine.cpp, src/map_functions.cpp, src/map_functions.h
SUMMARY: Features "Do not prompt whether to climb down when it's safe to do so"
Even it's perfectly safe to climb down a level (able to climb up), prompts are shown. 
1. made ledge actions UI entry use enums to make it easier to read
2. defined either monad, `climb_result` modeled after possible outcomes of climbing down:
| only one-way  | both-way |
| ------------- | -------- |
| dangerous     | easy     |
| unclimbable   | grapnel  |
| hard_to_climb |          |
3. used switch and `std::visitor` to exhaustively visit all possibilities
use the 'simple' way, use single enum, ret_val<T>, nested ternaries, etc.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/b19ed372-af59-4aba-b6c6-3cc915ae7807
it may be overly complex, but i'm just too anxious to use mutables and …
=> feat: do not prompt when it's safe to climb down

data/json/recipes/ammo/arrows.json, data/json/recipes/ammo/other.json, data/json/recipes/armor/feet.json, data/json/recipes/armor/hands.json, data/json/recipes/armor/head.json, data/json/recipes/armor/legs.json, data/json/recipes/armor/other.json, data/json/recipes/armor/suit.json, data/json/recipes/armor/torso.json, data/json/recipes/electronic/tools.json, data/json/recipes/other/containers.json, data/json/recipes/other/materials.json, data/json/recipes/other/parts.json, data/json/recipes/other/tools.json, data/json/recipes/other/traps.json, data/json/recipes/other/vehicles.json, data/json/recipes/weapon/bashing.json, data/json/recipes/weapon/cutting.json, data/json/recipes/weapon/piercing.json, data/json/recipes/weapon/ranged.json, data/json/requirements/toolsets.json, data/mods/DinoMod/DESIGN.md, data/mods/DinoMod/recipes/pets_bear.json, data/mods/DinoMod/recipes/pets_elephant.json, data/mods/DinoMod/recipes/pets_ostrich.json, data/mods/Generic_Guns/recipes/recipes_firearms_repeater.json, data/mods/Generic_Guns/recipes/recipes_firearms_single.json, data/mods/No_Hope/Recipes/recipes.json, data/mods/makeshift/recipe.json
SUMMARY: Balance "Standardize use of anvil quality to vary based on complexity of recipes"
At long last I figured I'd start to tackle the big overhaul of how anvil quality is used, to make anvil quality matter more and make the real-deal anvil less of a mountain for innawoods players to climb.
As I've referenced before, the basic outline is:
1. For basic no-frills recipes with no tools more advanced than tongs, permit anvil quality of 1. These have since been standardized to be any big hard striking surface not made of metal, which would be good enough for real basic hammering on metal that's been heated to temp.
2. The addition of a metalworking chisel bumps the required anvil quality up to level 2. Level 2 tools represent proper metal striking surfaces that aren't a full anvil, required …
=> Rework usage of anvil quality

src/activity_handlers.cpp, src/activity_item_handling.cpp
SUMMARY: Bugfixes "Fix a crash when chopping trees or logs from a zone"
Fix #3015 
Adds the item as the activity target when the activity is started from a zone as well. Also a check to turn the crash into red text.
Crashed every time previously. Doesn't crash now.
=> Fix a crash when using chop tree zones

data/json/scenarios.json
Removed golfcourse location from Really Bad Day
SUMMARY: [Bugfixes] "[Removing golf locations from Really Bad Day starting scenario]"
Related to #3019, this was bugging me for a while as well.
Really Bad Day challenge is ought to start in town and golf courses are outside of town. Thus they completely negate part of the challenge of this scenario, as fleeing the burning house and traversing streets full of zombies is part of the challenge.
Simply removed the locations from the scenario.
None.
Started the game and checked whether the starting locations are present.
=> Removing golf locations from RBD scenario

src/character.cpp, src/creature.cpp, src/npcmove.cpp, src/ranged.cpp, src/ranged.h
SUMMARY: Bugfixes "Cone AoE attack improvements - msg, npcs, armor wrecking"
Close #2791
Make cone AoE, like from birdshot, work more properly when used against the player in clothing and by NPCs.
* Being hit by gun AoE now prints proper body part - if exactly one was damaged - or "in total", if multiple body parts got damaged
* NPCs understand that anything in cone AoE is in confident range
* Armor damaged by attacks with low damage modifier - glancing shots, cone AoE - is less likely to be damaged
* Redesigning armor damage completely
* Dropping all armor damage
* Hacking armor damage from cone AoE with some tag
* Spawn a NPC
* Give it a shotgun with birdshot
* Anger it
* Get shot at while wearing thin clothing with some slots uncovered
* See clothing damaged, but not completely …
=> Cone AoE attack improvements - msg, npcs, armor wrecking

src/vehicle.cpp
SUMMARY: Interface "Displayed safe speed for animal-powered vehicles now matches the previously-hidden speed limit at which the slowest animal starts damaging its yoke"
This was a thing I'd wanted to do for a while now, fix an annoyance where the listed safe speed for an animal-pulled vehicle doesn't actually match up with the hidden code effect that prevents animals from exceeding a certain speed.
In vehicle.cpp, added a section to `vehicle::safe_ground_velocity` that checks for animal-powered vehicle parts, and if any valid animals are present on them, sifts through to track whoever is the slowest of them. If any are found then it returns that as the safe speed instead of whatever the engine power calcs claim it to be.
Additionally, it gives one final check to floor this resulting safe …
=> Set safe speed for wagons to hidden animal speed limit

data/json/item_actions.json, data/json/items/generic.json, data/json/items/tool/workshop.json, src/item_factory.cpp, src/iuse.cpp, src/iuse.h
SUMMARY: Feature "Add use action for pipe cleaners and repair kits to make gun fault mending more intuitive"
So a while back during https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1665 one thing that came up was adding a use/examine action to autoclaves to add an additional way to access the mend menu, since it being buried in the item summary menu is not newbie-friendly.
Logically, it might be good to extend that to gun cleaning since it's the other notable example of item mending at present.
C++ changes:
1. In item_factory.cpp, added `GUN_CLEAN` to the big iuse list in `Item_factory::init`.
2. In iuse.cpp and iuse.h, defined `iuse::gun_clean` function based off `iuse::gun_repair`, which brings up the mend menu when you select a valid faulty gun.
JSON changes:
1. Added `item_action` …
=> Add use action for bringing up gun cleaning mend menu

data/json/furniture_and_terrain/furniture-plumbing.json, data/json/furniture_and_terrain/terrain-manufactured.json, data/json/mapgen/hazardous_waste_sarcophagus.json, data/json/mapgen/mine/mine_entrance.json, data/json/mapgen/missile_silo.json, data/json/mapgen_palettes/basement.json, data/json/obsoletion/uncategorized.json, data/mods/Aftershock/maps/mapgen/millyficent_lab.json, data/mods/No_Hope/Mapgen/missile_silo.json
SUMMARY: Balance "Water dispensers converted from infinite clear water terrain to keg-style furniture holding a limited amount of clean water"
The BN discord once again reminded me that infinite clean water from a water dispenser may be a lil bit odd, and it wouldn't be too wacky to nerf it into behaving like a simple water container instead.
Of course, I figured it'd be simple but turns out that terrain doesn't play nice with the `keg` use action, so I guess we're getting a migration to furniture.
1. Added a furniture version of the water dispenser in the appropriate file. Made it a water container like water heaters instead of infinite clean water. Set a keg capacity of 75, so about 5 gallons (a common size for water cooler tanks).
2. Obsoleted the old terrain version.
2. Set the …
=> Convert water dispenser into furniture holding a limited amount

src/mondeath.cpp
SUMMARY: Bugfixes "Fix an overflow when big monsters splat"
When calculating splatter the game look at 15% of the weight. This is done by first multiplying by 15 and then dividing by 100. 32 bits isn't enough for some of the weights in secronom * 15. 
Use 64 bit unsigned for that calculation.
Rearranging the maths a bit, but it's not like performance is a concern for monster splatter.
I only noticed this because I was hunting another issue, but it's just a width upgrade.
=> Fixes an overflow in monster splatter

build-data/osx/dmgsettings.py
SUMMARY: Infrastructure "Fix 64bit macosx builds"
Build borked.
Set the dmg to be autosized rather than fixed limit.
Credit to @olanti-p for identifying the problem.
=> Auto size the dmg

.github/workflows/manual-release.yml
SUMMARY: Build "Updated manual release action"
Fix manual release action
Copy over changes from latest experimental release action.
Includes blind attempt at fixing android bundle release (it never worked).
https://docs.github.com/en/actions/using-workflows/reusing-workflows
Works on my fork: https://github.com/olanti-p/Cataclysm-BN/releases/tag/cbn-0.13.37
=> Update manual release action

src/panels.cpp
SUMMARY: Interface "Vehicle speed is shown when cruise control is disabled."
I tried to save some probably insignificant amount of fuel by disabling cruise control and coasting the final distance towards a destination, but noticed that the speed display vanished entirely. If the universal Vehicle Controls allow maintaining an exact speed via cruise control, presumably they have a regular speedometer (or whatever the equivalent would be for a boat or helicopter) so that seemed weird and unhelpful.
When cruise control is disabled, only the target speed stops being shown, the current speed remains.
When doing this, I noticed that the order of target speed / current speed was inconsistent between sidebar display styles, and decided to standardize them as `[Units] [Current Speed] > [Target …
=> Show vehicle speed when not using cruise control, standardize speed display

data/json/recipes/other/materials.json, data/json/requirements/toolsets.json
SUMMARY: Balance "Expand options for tools that can press paper, neoprene, and glass sheets"
An update to the paper recipe that came to mind, allowing a few options for the main roadblock to making paper the old-school way, making it so that having access to city resources or bootstrapping metalworking isn't needed to get paper.
Also applies similar consistency changes to other recipes in the same file that involve a flat sheet being laid out.
1. Changed the recipe for paper to allow small metal sheets, steel/alloy/hard plating, sheets of glass and tempered glass, wooden panels/sheets, and rigid plastic sheets as alternatives to sheet metal. Mil-comp and especially spiked plating excluded on the assumption that they might not be as good and flat, likewise reinforced glass mentions wiring …
=> Expand tool options for glass, paper, and neoprene crafting

data/json/itemgroups/Monsters_Animals_Lairs/monster_drops_advtech.json, data/json/items/bionics.json, src/activity_handlers.cpp, src/bionics.cpp
SUMMARY: Features "Uninstalling bionic complications yields burnt-out bionics instead of CBMs, replace spawns of useless bionic fault CBMs in cyborg harvest with bionic components"
This sets it so that faulty bionics no longer return a CBM item when extracted, as it's a bit weird to return it as a perfectly working faulty bionic you can then clean up and try to install in yourself.
C++ changes:
1. In activity_handlers.cpp, set `extract_or_wreck_cbms` so that CBMs with the `BIONIC_FAULTY` flag always convert into burnt-out bionics when harvested. Used mainly for dead players and NPCs, since below I'm changing harvest entries to do something a bit more interesting. Additionally fixed it so that it will remove the non-sterile fault from non-bionics obtained by this harvest. This fixes junk …
=> Broken cyborg bionics return as burnt-out bionics when extracted

data/json/requirements/toolsets.json
SUMMARY: Balance "Remove angle grinder from wall_floor_glass_removal_standard, lower CHISEL and PRY requirements"
It seemed remarkably strange for the deconstruction of wooden walls, empty window frames, and similar items to require an angle grinder. While this requirement makes sense for concrete and rebar, it does not make sense for wood and glass. I also noticed that the chiseling quality requirement of 2 was not actually held by any item, with only a quality of 1 or 3 being granted to an item in Vanilla so far as I could see. The prying requirement seemed somewhat unnecessarily restrictive, as a claw bar, crash axe, or ice axe all seemed like they could reasonably be used in this situation for any prying necessary.
-  Removed the Angle Grinder requirement from …
=> Make "wall_floor_glass_removal_standard" more rational

src/advanced_inv.cpp
SUMMARY: Performance "Port Advanced Inventory Management UI update optimization from DDA"
- port https://github.com/CleverRaven/Cataclysm-DDA/pull/67403 by @inogenous 
1. built cata with `RelWithDebugInfo` enabled.
2. invoked callgrind with:
```
valgrind --tool=callgrind --instr-atstart=no --collect-atstart=no '--toggle-collect=advanced_inventory::display()' ./cataclysm-tiles
```
3. created an empty world, dropped all items on the floor.
4. invoked `callgrind_control -i on` on other shell.
5. `alt-tabbed` to game, pressed up and down key ten times.
6. invoked `callgrind_control -i off` on other shell.
7. `ctrl-c`ed the process, with 3.7 billion IRs collected.
<details><summary>Details</summary>
```
~/D/CataclysmBN  valgrind --tool=callgrind --instr-atstart=no --collect-atstart=no …
```
=> perf: port AIM UI update optimization

data/mods/Aftershock/region_settings.json
SUMMARY: Mods "Stop aftershock mapgen turning the world into ocean"
https://gall.dcinside.com/board/view/?id=rlike&no=445258
https://gall.dcinside.com/board/view/?id=rlike&no=445260
issue reported by @NobleJake 
reset `river_scale` from 2 to 1
enjoy water contents
=> fix: reset aftershock `river_scale`

src/sdlsound.cpp
- fixes #114 
- fixes #2523
SUMMARY: Bugfixes "debugmsg on invalid sfx path on game startup. add more info to sfx error debug log"
invalid sfx file path can throw 5-second debug error backtrace when actually using that sfx. as it's not a crash and only logged in `debug.log`, it could be mistook as #2523
use `debugmsg` when loading game and sfx, as it's better to notice this kind of errors earlier
related: https://github.com/CleverRaven/Cataclysm-DDA/pull/53709
~~worked on my machine~~
=> feat: better error messages for sfx errors

src/cata_tiles.cpp, src/options.cpp
SUMMARY: Bugfixes "prefer renderers other than software for performance, fixed clang-tidy warning for font options"
- nudge players to choose renderers other than software to improve performance
- fix single space warning I've been conveniently ignoring it for 3 months since #2728
=> fix: font option style and renderer preference

data/json/npcs/robofac/NPC_ROBOFAC_INTERCOM.json
fixes the `Unknown Recipient` mission
SUMMARY: [Bugfix]: Fix the Unknown Recipient mission
Fixer the Unknown Recipient mission from the Refugee Center
Adds the necessary dialogue options to `the intercom` npc
=> Finally fix the Unknown Recipient mission

doc/JSON_INFO.md
SUMMARY: Infrastructure "Fixed documentation typo on `price_postapoc`"
it was wrongly written as `price_post` in docs.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/8548854c24573f240e5268257f3b6a061b26d90c/src/item_factory.cpp#L2409
=> docs: fix field typo on `price_postapoc`

src/ballistics.cpp, src/options.cpp
SUMMARY: Features "Add an option to draw bullets as lines"
Making burst fire not take forever, especially if it's a long burst.
Option to draw each bullet as one line rather than a dot that changes position once per frame.
* Batch multiple bullet "points" and draw lines that fly forward - actually tried that, but dropped due to it being relatively complicated, while not achieving much more than this one
* Enable the option in graphics
* Burst fire a gun
* Each bullet should only take one frame and show the entire flight path (clipped to viewport, of course)
* Repeat in curses mode
=> Add an option to draw bullets as lines

data/json/recipes/chem/chemicals.json
Content
Making sulphuric acid from sulfur and water.
Currently sulphuric acid can only be made from hydrogen peroxide (conc.) and sulfur. As it is not more difficult to make than nitric acid from ammonia, I added it according to the recipe described below.
Expanded chemicals.json to include sulphuric acid craft.
The reaction is done according to the contact process (https://en.wikipedia.org/wiki/Sulfuric_acid); there are also multiple other avenues for making sulfur into sulfuric acid, but that would be bloat. The industrial process is annoying, but can be replicated in a lab setting.
A liter of 98% sulph. acid is roughly 18.8 mol of the acid (https://www.quora.com/What-is-the-molarity-of-98-of-sulphuric-acid - can attest this post is correct in principle). Therefore a CBN unit is 4.7 mol …
=> Add sulphuric acid synthesis; Update chemicals.json

data/json/recipes/other/tools.json
Pressure cookers are missing a crafting recipe, and are currently loot only. 
A pressure cooker is reasonably craftable, so this change makes pressure cookers craftable from either various steel pots or scrap. Needs a barometer and thermometer, since the primary use for these is chemical crafting, and to not make them trivial to craft (i.e. 100 scrap metal equivalent and 5 rubber, just smash a car to bits). The additional steel required is for bracing/reinforcement, the rubber is for the seal. 2h crafting time might be low, let me know.
Not adding the recipe.
Built one in-game successfully.
Going through various chem recipes, nitric acid is the only place a pressure cooker is used afaik. Players can make more complicated and dangerous stuff than a pressure cooker, so adding the recipe …
=> Add pressure cooker recipe; Update tools.json

src/overmap.cpp, src/overmap.h, src/savegame.cpp
SUMMARY: Performance "DDA Port: Stop copying regional settings for every overmap"
performance gainz
port https://github.com/CleverRaven/Cataclysm-DDA/pull/59313 by @jbytheway 
i trust DDA and CI pipeline.
=> perf(port): do not copy regional settings for overmaps

src/explosion.cpp
SUMMARY: Build "remove extra ';' to make compiler stop complaining"
Build using Make was complaining about the extra ';'s.
```
$ ./build.sh
Using default system compiler: g++
Chosen compiler: CCACHE_SLOPPINESS=pch_defines,time_macros ccache g++
Chosen linker:   CCACHE_SLOPPINESS=pch_defines,time_macros ccache g++
explosion.o
src/explosion.cpp:234:2: error: extra ‘;’ [-Werror=pedantic]
234 | }; // namespace ExplosionConstants
|  ^
src/explosion.cpp:468:2: error: extra ‘;’ [-Werror=pedantic]
468 | };
|  ^
src/explosion.cpp:492:2: error: extra ‘;’ [-Werror=pedantic]
492 | };
|  ^
src/explosion.cpp:520:2: error: extra ‘;’ [-Werror=pedantic]
520 | };
|  ^
src/explosion.cpp:891:2: error: extra ‘;’ [-Werror=pedantic]
891 | };
|  ^
src/explosion.cpp:901:2: error: extra ‘;’ [-Werror=pedantic]
901 …
```
=> compile: fix extra ';' [-Werror=pedantic] complaints

src/debug_menu.cpp, src/json_export.h, src/vehicle_export.cpp
SUMMARY: Features "Added debug command to export vehicle as its JSON representation"
It's often easier to design a vehicle inside the game, but there were no easy way to export it. Major benefits are:
- modders: easier modding
- players: easier vehicle template sharing across saves
- added `json_export.h` to store all future JSON exports (e.g terrain, houses, etc)
- added `Copy [j]son representation` in debug/vehicle tab.
- format the output, however i'm not sure it's worth the effort to mainline `tools/format.cpp` inside `src/`
- generating items section/blueprint, however that would take too much time.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/de167c1e-de03-4a1f-aba7-d9ab70d9cb7e
generated (left) and original (right)
the error message from video is because existing …
=> feat: export vehicle as its JSON representation

src/debug_menu.cpp, src/vehicle_export.cpp
SUMMARY: Bugfixes "Fixed broken curses build caused by #3086"
fix curses build failure caused by #3086
- https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3086#discussion_r1305883096
- https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3086#discussion_r1305885400
- enabled clipboard only for tiles
- reworded debug command
- added `ammo` field back as i mistook it as number of rounds but [it was percentage](https://github.com/CleverRaven/Cataclysm-DDA/blob/afd4746d0e859d65652e5350b66cfa17d65180a1/doc/VEHICLES_JSON.md?plain=1#L59)
i'll check curses result on CI as it's been late
thanks @olanti-p for finding out the regression quickly.
=> fix: vehicle JSON export breaking curses build

data/json/recipes/other/other.json, data/json/requirements/toolsets.json
SUMMARY: Balance "Port the recipe to craft a body pillow from DDA"
We have body pillows, but due to their rarity, you may go many playthroughs without actually finding one. Now, with a simple recipe, you too can draw your ultimate waifu and cuddle them to sleep! (More seriously, I don't see any reason why the body pillow item shouldn't be craftable. It's not like it offers much of an advantage over a standard pillow, from what I understand.)
1. Add the drawing standard to the toolsets JSON (Which could be used by anything else that needs a convenient drawing tools standard)
2. Port over the recipe from DDA, changing it to fit our system
- Not porting this recipe
I see no reason to not port this over so long as body pillows remain in the game.
- Not porting / defining the drawing tool …
=> Port: Craftable Body Pillows from DDA

src/lua/lundump.c
SUMMARY: Bugfixes "lua compilation warnings"
fix compilation warnings emitted caused by pointer arithmetic
https://github.com/lua/lua/blob/9b4f39ab14fb2e55345c3d23537d129dac23b091/lundump.c#L294
=> fix: lua compilation warnings

data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json, data/json/itemgroups/Weapons_Mods_Ammo/guns.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_ammo.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json
SUMMARY: Balance "Fixes the few normal guns I left out of the previous Nested Guns and Everyday Carry PRs"
A few normal (i.e. Not Improvised) guns were left out of the previous Nested Guns and Everyday Carry PRs. This aims to fix that.
1. Add the missing 5x50mm ammo type to nested_ammo.json
2. Add the missing guns to nested_guns.json
3. Add the missing guns to everydaycarry_guns.json
4. Edit the existing itemgroups in guns.json (and in the case of the obscure SMGs, add the everyday carry category) 
- Also adding the improvised guns along with the normal ones
Less pressing of a concern, and I feel like they're relatively unimportant.
- Leaving it how it was previously
I mean, entirely possible, but I don't know *why* anyone would be against making it (more) complete and comprehensive.
1. …
=> Complete the "Nested" and Everyday carry Gun lists 

data/json/monsters/reptile_amphibian.json, src/iuse.cpp, src/mattack_actors.cpp, src/monster.cpp
SUMMARY: Balance "Feral survivors can no longer tame animals or become marloss vectors, some improvements to monster behavior with feral survivors"
Some more misc. code ideas related to feral survivors.
C++ changes:
1. In iuse.cpp, set `marloss_common` so that having Lost to The Cataclysm prevents gaining the marloss mutations and instead triggers a negative reaction, like with having a competing mutation threshold. Gameplay-wise, it prevents stacking up on permanent immunities to major monster factions. Lore-wise it'd be reasonable to assume that a feral survivor has been altered in some way given zombies see them as one of their own and the zombie-like physical symptoms referenced in monster descriptions. It also makes it possible that the Mycus might view them as unsuitable as a local …
=> Additional follow-up code tweaks for feral survivors

data/json/furniture_and_terrain/terrain-manufactured.json
SUMMARY: [Balance] "Sewage pipes and pumps are deconstructable into their bash products"
Sewer pipes and sewer pumps have no deconstruct, but they're just steel with some pipe fittings, so this lets you deconstruct them.
I used the exact bash products to be safe. If we should up the steel amount I leave that to a maintainer to balance as this is going to add a lot of steel platings in the sewers now. I also set the deconstruct terrain to the bridges in the sewers as you're not bashing the pipe to scrap so it should maintain structural integrity underneath. 
This gives you more reason to go into sewers and allows us to put these sewer connections in the way of building basements for urban development but still let you access the sewers with just tools and not bashing or mining. This source …
=> Deconstructable Sewer pipes & pumps

src/main.cpp, src/sdltiles.cpp
SUMMARY: Infrastructure "Improve behavior if on first game start SDL window creation fails"
If on first game launch SDL failed to initialize window for some reason, `options.json` is not created, so it is impossible to tweak the values to make the game run.
Create new `options.json` file as soon as possible, so the players can at least manually tweak values there in case the game experiences issues with window initialization.
Figuring out why we can't have backtraces when the game crashes inside SDL code.
Added a mock `std::abort()` in `WinCreate`.
Before: when running the game, it crashes, produces no `options.json`.
After: when running the game, it crashes, but produces `options.json`.
=> Improve behavior if on first game start SDL window creation fails

data/json/items/comestibles/meat_dishes.json, tests/basecamp_test.cpp
SUMMARY: [Balance] "Lowered SPAM morale penalty"
As it stands, SPAM has a fun value of -8, which is even worse than the canonically awful-tasting protein rations. Notably, potted meat, a very similar item, has +1, while fried SPAM has +8. 
-8 is the same amount as... cooked brains. A benign item like this really doesn't warrant such a harsh penalty for consumption, in my opinion.
Lowered the penalty to -2. While still unpleasant, it won't immediately ruin a character's day.
Maybe lower the penalty slightly less. Maybe even remove it entirely! Or just... leave it as is, I suppose.
Changed the value, loaded game, ate, gave -2.
It's really not that bad.
Also, the description still lists it as being "unnaturally pink, oddly rubbery, and not very tasty" and "completely unappetizing," but eh.
=> Balance: Make SPAM less terrible

data/mods/Magiclysm/requirements/cooking_components.json
SUMMARY: [Mods] "[Magiclysm dragon meat can be cooked]"
Dragon meat had only one use, that was to turn into essence that was then used to make body armor. I chose to add it to meat_raw_steak but also keep the description unchanged as to allow a backdoor for others to give it magical properties later or use in more magical crafting. If necessary we can change its description but I like the idea of magical steak.
I also think that even if it had a magic craft later, that eating it for food is still a good way to keep players from stockpiling it for stuff like potions as they will be tempted to waste a valuable resourced on day to day survival.
meat_dragon was added to meat_raw_steak. Magiclysm already had an override for it.
Not doing this. Making dragon meat a drug of some kind. Using it …
=> Magiclysm dragon meat can be cooked

data/json/items/ammo/shot.json, data/json/items/gun/monster_gun.json
SUMMARY: [Balance] "Buffed shotgun shells, nerfed feral biker shotgun."
Shotgun shells were fairly underpowered, doing barely any more damage than a 9mm round and with even less range.
Shotguns are now able to hit much harder and much further, but have an armor multiplier now to compensate; the feral biker's shotgun has had its dispersion and range decreased to compensate.
I'm not really sure what alternatives to take, to be honest. Shotguns as-is are weak, inaccurate, and ridiculously short-ranged, making them a genuinely inferior option compared to even a 9mm pistol, let alone a submachine gun.
The json checks out, and I did some basic testing of the shells themselves; the range feels good, albeit perhaps a bit _too_ good, and the power is strong enough to oneshot basic zombies but is …
=> Rebalanced shotgun shells

src/item_factory.cpp
SUMMARY: Bugfixes "Allowed speedloader capacity to be smaller than gun's capacity"
original discussion: https://discord.com/channels/830879262763909202/830916415182733322/1150400794189889606
e.g it should be ok to use a 4-rounds speedloader for shotgun of 8-rounds capacity.
changed the condition from `speedloader capacity != gun capacity` to `speedloader capacity > gun capacity`
remove the check altogether? tho using 20-rounds speedloader for shotgun of 8-rounds capacity might be weird.
local tests passed.
=> fix: allow speedloader capacity to be smaller than gun's

src/url_utility.cpp
SUMMARY: Bugfixes "Made 'Submit a bug report on Github debug' work correctly on windows"
- fixes #3128
https://chat.openai.com/share/af7046b4-832d-467f-a1d9-700546554c31
manually typing the command on CMD.exe worked
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3128#issuecomment-1712982005
=> fix: `open_url` not working on windows

data/json/items/melee/spears_and_polearms.json, data/json/items/tool/misc.json
SUMMARY: [Infrastructure] "json Move makeshift glaive from tools category to weapons category"
Makeshift glaives don't have any tool-like uses, only weapon-like uses.
This just changes the category of the makeshift glaive and moves the json to the appropriate file.
Ignoring it.
Loaded the game after making the change, confirmed the item shows up in the correct category on the advanced inventory management menu.
=> Move makeshift glaive from tools to weapons

src/crafting.cpp
SUMMARY: Mods "Allow recipes to declare `NUTRIENT_OVERRIDE` flag to ignore components used"
- fix #3025
added `NUTRIENT_OVERRIDE` flag check for recipes. it will propagate the flag to items, also ignoring any components.
- make it a separate flag, e.g `NUTRIENT_IGNORE_COMPONENTS` to distinguish it with items?
- do not discard components?
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/f6744b1d-d488-461e-a684-14b68eee2f81
```json
{
"type": "recipe",
"result": "carrot",
"id_suffix": "WithRocks",
"category": "CC_FOOD",
"subcategory": "CSC_FOOD_VEGGI",
"skill_used": "cooking",
"time": "1 s",
"result_mult": 1,
"batch_time_factors": [ 80, 2 ],
"autolearn": true,
"components": [ [ [ "rock", 2 ] ] ],
"flags": ["NUTRIENT_OVERRIDE"]
}
```
conjured carrot from rock. eating it …
=> feat: apply `NUTRIENT_OVERRIDE` for recipes

src/mattack_actors.cpp
SUMMARY: Bugfixes "Fixed segfault caused by attitude check when monster shooting vehicle"
When monster `target_moving_vehicles` it legitimely have nullptr `target`, and those `untargeted` shoots cause segfault due to friendliness check.
Added null check.
Pointing author at issue so i don't need to fill exhausting surveys.
Loaded bugged save, no more crashes.
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff611faf9fc in monster::attitude_to (this=0x31d32840, other=...) at src/monster.cpp:1047
1047        const monster *m = other.is_monster() ? static_cast< const monster *>( &other ) : nullptr;
(gdb) p other
$1 = (const Creature &) <error reading variable: Cannot access memory at address 0x0>
(gdb) bt
#0  0x00007ff611faf9fc in monster::attitude_to (this=0x31d32840, …
```
=> Fixed segfault caused by attitude check when monster shooting vehicle

src/debug.cpp, src/debug.h, src/main_menu.cpp
SUMMARY: Infrastructure "Warn when running x32 game on x64 system"
Many people _still_ don't know the difference between x64 and x32, and it's getting old explaining what these mean when they come complaining about OOM crashes.
Add a warning on game start that explains what's wrong and how it can be fixed.
The warning will show only when the game is completely sure it is a x32 build running on a x64 os; if detection fails, or cannot be done, the warning isn't shown to avoid false positives.
Additionally, the game will now report bitness in the debug log on launch.
Dropping x32 builds.
Warning shows properly on Windows with Visual Studio build (x32 and x64 builds on x64 os).
I didn't bother figuring out how to cross-compile for x32 on linux, but it should work as well.
=> Warn when running x32 game on x64 system

src/iuse.cpp
Bugfixes "Fixed 'Item canister_empty was loaded with charges' error"
`iuse::can_goo` firstly converts used item to "canister_empty" which doesn't have use cost, and at the end tries to consume `charges_to_use`, which is zero at that point. Explicit return of original\hardcoded cost also wouldn't work as `Character::invoke_item` wouldn't consume charges from generic item. In either case we're ending with "canister_empty" having a stray charge.
Force converted item to end with 0 charges. Also added fallback message so it won't fail silently when it can't find a room for goo, and made it work with any amount of charges, because why not.
Porting whole reworked `Character::invoke_item` infrastructure from DDA. Not today.
1) Start game
2) Spawn goo canister via debug
3) Use it
4) Save & Quit
5) …
=> Goo canister will correctly consume charges on use

src/avatar_action.cpp, src/game.cpp
SUMMARY: Features "Made ladders work like ramps and ledges auto-examinable"
There's two way of going down a ledge:
1. jump down (may hurt)
2. climb down
option 2 can only be accessed via `(e)xamine`, and 90% of time climbing down is a better choice.	
moving z-levels up and down with stepladders were also tiresome be
1. made `game::prompt_dangerous_tile` to call `iexamine::ledge` instead if and only if dangerous terrain is ledge.
2. made furniture with `LADDER` flag act as ramps. when climbing up, the check is done just before handling invalid moves to not interfere with walking, opening door, etc.
- make it an option?
- make auto ledge examine more granular depending on `Dangerous terrain warning prompt`?
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/73e3ee7c-c828-45d6-a8 …
=> feat: auto ladder climbing and ledge prompts

data/json/items/armor/holster.json
SUMMARY: Balance "Ankle holsters, holsters, and XL holsters can now hold a wider range of guns"
As mentioned in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3158, messing with the range of volumes holsters can fit was on my list as one idea to help alleviate various issues with fitting guns in storage being fairly fiddly, especially when magazines and gunmods get added to the fray.
1. Changed the regular holster's minimum volume from 300 ml to 250 ml, and its maximum volume from 800 ml to 1 liter. Change to the minimum notably affects the Walther P22 and SIG Mosquito (250 and 263 ml, both looking decent and not pocket-pistol size IRL from what I can tell). The change to maximum volume notably affects the Colt Navy (851 ml, standard barrel length IRL is a whole half an inch shorter …
=> Expand range of volume limits for certain holsters

data/json/furniture_and_terrain/terrain-walls.json, src/iuse.cpp
SUMMARY: Balance "Increase soil yield from digging back up to an amount more in line with construction demand, belated sanity-checking for bashing rammed earth walls"
When I sanity-checked digging I also reduced how much soil is produced by digging, but I'd overtuned it quite a bit compared to how much soil is used in the construction recipes I'd touched shortly before that.
Along the way, Royalfox on the BN discord pointed out that I forgot to adjust how much soil rammed earth walls give when smashed too, making them give more than they take to make.
1. In iuse.cpp, changed `digging_moves_and_byproducts` so that it produces a total of 600 liters of material when excavated, for a maximum of 120 soil per deep pit. This works with rammed earth walls taking 100 soil and earthbag walls taking …
=> Adjust soil from digging to match construction needs

data/json/furniture_and_terrain/terrain-walls.json
SUMMARY: Balance "Mining solid rock gives as much stone as mining large boulders, related stone surfaces give as much rock as medium boulders"
Something I made note of in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3161, boulders got an adjustment to how many rocks they're worth but solid rock and related terrain didn't get adjusted accordingly, and doing so would be reasonable for parity with how many rocks it takes to make stone walls.
1. Increased the number of rocks obtained by bashing solid rock to 65-85 (matching large boulders), and added 5-9 sharp rocks also from large boulders. This is quite a bit more than the 24 it takes to make one tile of rock wall, but tunneling through solid rock is more involved than digging pits so it may be reasonable for each tile to go into …
=> Scale up mining yield of solid rock to match boulders

src/iexamine.cpp, src/iexamine_elevator.cpp, src/mapdata.cpp, src/mapdata.h, src/point_rotate.cpp, src/point_rotate.h
SUMMARY: Features "Allows elevators transport vehicles as well"
the (not) long awaited sequel of #1531.
looting labs with shopping carts would be very convenient.
port https://github.com/CleverRaven/Cataclysm-DDA/pull/58840 by @andrei8l
port more overmap/submap PRs first?
vehicles are moved together (with their directions kept)
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/10f85b63-eab8-41a1-b82d-cf42077ea41e
creatures/npc are shoved away
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/5a4e91de-9952-431b-b8b6-f7b94bff1d26
vehicles can block the elevator from working
vehicles at destination floor is also checked to prevent amalgamation
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/4df13f70-8082-49a6-8093-ce43aa836116
might have to port …
=> feat(port): move vehicles in elevator

src/map_extras.cpp
SUMMARY: Bugfixes "Set burnt vegetation map extra to not leave deep pits hidden under ash piles"
Another obscure side effect of the PR that allows dirt to be blown into craters I overlooked, there's another map extra in the code that relies on bashing terrain that should be leaving shallow pits at most, not deep pits.
In map_extras.cpp, updated `burned_ground_parser` so that burnt vegetation checks for deep pits created by wrecking the ground when it creates ash piles, and converts them back to shallow pits. Mainly good because the ash furniture looks odd and in UDP it obscures the pit in a way that might lead to players blundering into one.
Left the section that doesn't place ash piles untouched, since main goal is preventing concealed deep pits, a few open pits being left seems okay to …
=> Fix burnt vegetation hiding deep pits under ash piles

src/iexamine_elevator.cpp
SUMMARY: Bugfixes "Hotfix build failure do to missing vehicle_part.h inclusion"
1. #3104 changed header inclusions, and fixed all header inclusions
2. #3151 was made without header inclusion in #3104 since it wasn't merged yet
3. #3151 got merged first, with all tests passing
4. #3104 got merged later, with all tests passing, however _it was a lie!_ the source code changed after merging #3151, but no additional tests were ran on #3104
include "vehicle_part.h" header to "iexamine_elevator.cpp"
screm
local build passed, should be merged ASAP, sorry
we should really use merge queue
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
=> fix: missing "vehicle_part.h" includes

data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json
SUMMARY: Bugfixes "Fixed nested_aksemi in nested_guns.json by actually using aksemi"
The nested_aksemi itemgroup should not be using a Marlin 1895 SBL instead of the real Semi-auto AK-47.
Replaced "1895sbl" with "aksemi" in the nested_aksemi itemgroup
N / A
In a sense, tested by obtaining the wrong gun for the mags and ammo I got from a minehead bridge spawn.
Bug originated in DDA, and they've been notified of it too.
=> Fixed AK Semi in nested_guns.json

data/json/npcs/missiondef.json
SUMMARY: Bugfixes "Turn in cattail stalk first then the bag"
same as https://github.com/CleverRaven/Cataclysm-DDA/pull/68077
=> fix(mission): turn in stalk first then the bag

src/mattack_actors.cpp
SUMMARY: Bugfixes "Fixed turrets aiming moving vehicle it cannot see"
while #2589 fixed turrets firing through walls and floors, turrets still ignored their visibility for moving vehicles.
fix https://gall.dcinside.com/board/view/?id=rlike&no=447553
also check for visibility in turrets
haha turrets go brrrrrrrrt
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/4cdf6c36-2b0b-401f-8637-fc2d6408bde4
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/7bca86e3-c15f-4932-b429-763e017a9b52
=> fix: turrets aiming moving vehicle it cannot see

data/json/items/chemicals_and_resources.json, data/json/items/comestibles/carnivore.json, data/json/items/comestibles/mushroom.json, data/json/items/comestibles/other.json, data/json/items/comestibles/raw_veggy.json, data/json/items/comestibles/seed.json
SUMMARY: Bugfixes "Add UNSAFE_CONSUME to several foods that triggered query on eat, to prevent them from softlocking when placed in an auto-eat zone"
Viss pointed out to me that if an item in an auto-eat zone has a poison use action or other thing that prompts you about if you want to eat them, but lacks the `UNSAFE_CONSUME` flag, you'll be trapped in an infinite loop should it decide to eat that item, where your only options are to either succumb to peer pressure and eat eat morel mushrooms, or to force-quit the game.
I figured fix all potential cases of this in the JSON for a quick fix to potential softlocks now, and look at the code to make it stop doing that in a separate PR.
1. Added `UNSAFE_CONSUME` flag to morel mushrooms.
2. Set it so cooked morel mushrooms remove the flag. Fried …
=> Prevent poisonous foods from softlocking the game

src/activity_item_handling.cpp
SUMMARY: Bugfixes "Prevent auto-eat code from selection items with use actions to avoid Y/N queries softlocking an auto-eat attempt"
As mentioned in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3183, I intended to also add a code PR to nip this issue in the bud full-stop via a code solution.
From what I can tell, the root issue is specifically items that have an iuse that brings up a yes/no query. Mundane inedible stuff like meat for an herbivore character is already handled by `will_eat`, but stuff like asking if you want to eat tainted meat is handled through the item having an iuse.
As far as I can tell, the only real ways to check that are `has_use` and `has_iuse`. The latter can check for specific use actions, but it's a member of item factory and not usable in the relevant …
=> Prevent auto-eating items with use actions

src/overmap.cpp, src/overmap.h
SUMMARY: Bugfixes "Smoother rivers connections on overmaps edges"
River connections and side touches are often generated with cut edge next to overmap border, without any shore. This change polish all those edges.
River polishing function will now be aware of adjacent tiles even if they're on different overmap, so it knows where shores should be placed. For not yet generated overmaps it assumes that water continues as it goes, leaving polishing to their mapgens, which can handle that nicely.
Rewriting `overmap::place_river` to make starting points of rivers always match each others, and never touch borders in any other places.
Jumped between overmaps in debug mode, following river. Looks much better now.
It's a bit difficult to show the difference due to map randomness, but that should …
=> Smoother rivers connections on overmaps edges

src/catalua_impl.cpp, src/catalua_impl.h, src/catalua_serde.cpp, tests/catalua_test.cpp, tests/stringmaker.h
SUMMARY: Infrastructure "Lua mods can now use non-strings as keys in storage table"
Fixes issue reported on Discord: if Lua table in mod_storage has a non-string key, the game would crash on save.
Overhaul table de-serialization to support same values as keys do.
Forbidding non-strings as keys in storage
Added tests
=> Lua table serde: allow non-string types as table keys

data/mods/default.json
SUMMARY: Mods "Made 'Prevent Zombie Revivification' and 'Limit Fungal Growth' as default-enabled mod"
[original discussion in discord](https://discord.com/channels/830879262763909202/830916329053487124/1154179815109300275)
- zombie revivification is often not fun as it's more work.
- in current status, fungals expand too rapidly, effectively soft-locking the whole area without proper reward.
following mods were added to default-enabled modlist on worldgen:
- Prevent Zombie Revivification
- Limit Fungal Growth
- implement #3188 to make fulgaloids more engaging
=> feat: default to no zombie revival and limited fungal growth

.github/workflows/documentation.yml
SUMMARY: Bugfixes "Hotfix made to fix deploying github pages"
missing github environments preventing workflow
disabled environments temporary, as they were originally a mean to run in another branch, the site should work without it as-is.
this will be reverted once environments are properly set up.
=> ci(fix): temporary disable github environments

.github/pull_request_template.md
Summary
SUMMARY: [Infrastructure] "Fixes Pull request template links"
When @scarf005 did the doc site a few files got moved around. Our PR template now has dead links. This redirects to the correct links now.
Change link destination
Describe alternatives you've considered
You gotta be in the know to know, you know? And that's why new contributors don't know.
Testing
I made sure the links actually worked.
Additional context
N/A
=> docs(fix): broken pull request template links

src/game.cpp, src/game_constants.h, src/item.cpp, src/item.h, src/timed_event.cpp, src/units_temperature.h, src/weather.cpp, src/weather.h, tests/ranged_aiming_test.cpp
SUMMARY: Infrastructure "Replace fahrenheit usage to celsius in codebase, part 1"
- partially fixes #2569 
- used `units::temperatures` for `temperatures` constants
- used `units::temperatures` for item rotpoint calculation
- hardcoded `rot_chart` as conversion from fahrenheit to celsius was tricky
- also simplified if-else pyramid of doom in acid rain function
screm
all local test passed.
help
=> refactor: fahrenheit to celsius in codebase, part 1

src/overmap.cpp, src/overmap_connection.cpp, src/overmap_connection.h
SUMMARY: Bugfixes "Fixed generation of disconnected bridges"
This change prevents generation of those wacky constructions: 
Connection points of specials will only accept uniform terrains with LINEAR flag.
Teleported around looking at bridges, looks good.
=> Fixed generation of glitched bridges

src/catalua.cpp
SUMMARY: Bugfixes "Fix CTD on debugmsg with no Lua instance"
Fix CTD when debugmsg tries to print Lua backtrace, but there is no Lua state available.
Add `nullptr` check
Added fake debugmsg on game start, game no longer CTDs from it.
=> Fix CTD on debugmsg with no Lua instance

.github/workflows/documentation.yml, README.ko.md, README.md, doc/src/content/docs/en/game/changelog.md
SUMMARY: Infrastructure "Fixed broken wiki links in documentation site"
- fix deprecated wiki links in documentation
- revert blunders made in #3191 
- reverted #3191 as
- it did not work
- `github-pages` environment is needed for deploying astro-based site on github pages
[host on other services](https://docs.astro.build/en/guides/deploy/#overview), such as 
- deno deploy
- netlify
- cloudflare pages
- vercel
checked that the links are valid in both http/relative redirects on local server.
=> docs: rollback github environments, fix broken wiki links

data/json/recipes/armor/feet.json, data/json/recipes/armor/head.json, data/json/recipes/armor/legs.json, data/json/recipes/armor/torso.json
SUMMARY: [Balance] "Adds recipes for existing clothing items"
A lot of clothes are missing crafting recipes, this adds some and attaches them to the existing books. I may have missed a few but balance is hard and this needs a lookover.
The skirts, dresses, maid outfit, and heels all have recipes of costs and difficulty I found reasonable based on coverage, warmth value, and how fancy it is. I also followed the same tailoring patterns I found of cloth using 2 sewing standard per rag, and clothing not having a reversible true field.
Heels are fully leather, but IRL they are mainly plastic. I figured I'd keep them fully leather for now and worry about it in post as it's easy to fix. http://www.madehow.com/Volume-5/High-Heel.html
Loaded it into the game and it worked.
Balance is hard. Help me …
=> More craftables 1: Clothing

data/json/obsoletion/recipes.json, data/json/recipes/other/materials.json, data/json/uncraft/generic.json
SUMMARY: Balance "Bring back deconstruction of pewter items, reimplement salvaging tin from cans via electroplating using new larger can sizes"
Back in the old days, you could simply scrap tin and pewter items to get tin directly, which back when I added bronze made it a bit more convenient.
Eventually, someone had the clever idea to allow extracting tin from tin cans using electrolysis. This is reasonable, while they aren't made wholly of tin it's still common to plate them, and the intended use case was just to get enough tin to make copper pots. Cans are super common so having to stockpile to make up for a low yield seems reasonable enough to me.
Then it went off the rails when someone else changed the recipe to only use pewter and tin items. This of course defeated literally the …
=> Rework and sanity-check harvesting of tin

.github/labeler.yml, .github/workflows/android.yml, .github/workflows/autofix.yml, .github/workflows/matrix.yml, .github/workflows/msvc-full-features.yml, .github/workflows/msys2.yml, .github/workflows/release.yml
SUMMARY: Build "Skip docs/script only changes in PRs and commits, but format them"
- skip unnecessary builds/releases
- we don't distribute docs in releases, that could be skipped as well
- make markdown/typescript only changes trigger autofix
- label docs and scripts
=> ci: format but skip build/release docs/scripts

data/json/items/armor/boots.json, data/json/items/armor/gloves.json
SUMMARY: Balance "Set armored gauntlets and boots to be steel/leather, to be plate-tier instead of iron-tier"
So, one thing I derped and forgot about while working on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3168 is that, for some reason, armored gauntlets and boots take plate-tier levels of fabrication to make, and have higher encumbrance than iron-tier stuff, but only provide iron-tier protection.
Also I suppose a much-belated followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/847 which also did a lot of making armor items within a set have consistent armor values for its individual pieces.
1. Changed material of armored gauntlets from iron/leather to steel/leather, making its protection go from 12/12/10 (iron tier) to 16/16/14 (plate tier).
2. Changed material …
=> Set armored gauntlets and boots to be made of steel

doc/astro.config.ts
SUMMARY: Bugfixes "Made documentation page redirects relative to fix edge cases"
if the docs page is hosted on subpath (e.g: `/bar` in `https://foo/bar`), absolute redirects such as `/` -> `/en` will redirect to `https://foo/en` not `https://foo/bar/en`.
- used relative redirect instead.
- made ENV debug output more helpful by the way
this can also be solved by using `base` parameter to astro config but this is easier and more robust.
worked in local environment.
=> docs: fix docs page redirection failing

data/json/monsters/zed_misc.json, src/monster.cpp, src/monstergenerator.cpp, src/mtype.h
SUMMARY: Features "Adds BIOPROOF, a new monster immunity flag for biological damage"
- fix #3193
added `BIOPROOF`
slep
1. spawn a zombie master
2. cast necrotic gaze to it
3. master is not affected
@RoyalFox2140 @RobbieNeko pls review
=> feat: monster immunity flag for biological damage

data/json/monsters/defense_bot.json, data/json/monsters/drones.json, data/json/monsters/turrets.json, data/json/monsters/utility_bot.json
SUMMARY: Balance "Gave the new BIOPROOF flag to the robots"
Adds the BIOPROOF flag to the robots (not cyborgs of any kind yet because that gets more of a disagreement going)
None
Made sure the game didn't error because of this change (it didn't), gazed at a Light Turret Necrotically and it was unfazed.
RoyalFox is handling giving BIOPROOF to poison monsters, and further ideas are up in the air at the moment.
Changes to Magiclysm in light of the flag (and including it in any relevant monsters) will come later.
=> BIOPROOF distribution: Robots

src/npcmove.cpp
SUMMARY: Bugfixes "Companion NPCs told to only attack what the player attacks no longer charge approaching enemies unless you've actually attacked the target first"
This fixes NPCs set to "attack only what I attack" being stupid and bum-rushing targets you haven't marked for death yet, AKA what used to be my preferred NPC RoE setting back in the old days.
In npcmove.cpp, changed `npc::method_of_attack` to add an extra boolean that checks if both the target has yet to be hit by the player and the NPC is set to engage targets you attack. If so, the bottom function for fallback behavior will tell them to hold fast as if they were not to not move, instead of going for a charge.
If anyone can remember any other NPC AI settings that visibly don't work right, lemme know.
1. Compiled and …
=> Fix NPCs set to attack what you attack charging blindly

data/json/items/armor/arms_armor.json, data/json/items/armor/boots.json, data/json/items/armor/cloaks.json, data/json/items/armor/coats.json, data/json/items/armor/gloves.json, data/json/items/armor/helmets.json, data/json/items/armor/legs_armor.json, data/json/items/armor/legs_clothes.json, data/json/items/armor/masks.json, data/json/items/armor/suits_clothes.json, data/json/items/armor/suits_protection.json, data/json/items/armor/torso_armor.json, data/json/items/armor/torso_clothes.json, data/json/items/armor/undergarment.json
SUMMARY: Balance "Add the steel and superalloy armor mod option to more gear related to items already moddable"
This adds the option to add steel and superalloy lining to a few more clothing items, based on other similar items to have the option.
1. Added steel and alloy lining options to leather corset, only undergarment that seemed like it might be reasonable for. Consistent with various leather clothing items having the option.
2. Added steel and alloy lining options to leather apron, again since leather garment noted to be usable for ersatz armor purposes.
3. Added the lining options to hoodie, it being a bulky jacket-type item, coinsistent with the wool hoodie having the option.
4. Added the lining options to lamellar cuirass. In addition to other (not already plated) leather armor …
=> Allow steel and superalloy lining for more items

src/monexamine.cpp, src/monexamine.h
SUMMARY: Features "Removed checks for pushing or swapping friendly monster"
- fix #640 
- swapping removed from friendly monster interaction as walking into them is simpler
- removed strength check for pushing friendly monster
my pet zombie hulk killed my friendly NPC!
closing old issues goes brrrrrr
=> feat: simplify friendly swap and pushing

data/mods/No_Hope/Mapgen/parking_garage.json
SUMMARY: Bugfixes "Fix No Hope palette override lacking terrain that caused the game to error on load"
In another fine example of "why do we even have that lever?" No Hope includes a full oiverride for some map palettes, including one recently touched by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3224 and this was why the buildbot was cryptically exploding.
Fixes this thing:
Added missing terrain defs to No Hope's version of `parking_palette`.
1. Removing palette overrides because it's really weird that No Hope overrides SO MUCH STUFF
2. Also implementing and testing working elevators in the No Hope version but I assume that is against the spirit of the mod. Also effort and it's past midnight and I need to do stuff tomorrow weh
=> Give No Hope the e

src/CMakeLists.txt, src/SetupLibrary.cmake, tools/clang-tidy-plugin/CMakeLists.txt
SUMMARY: Build "deduplicate setting up library for w/wo tiles in CMake"
DRY is good
- added `setup_library` function to setup common configuration
- also silenced [DOWNLOAD_EXTRACT_TIMESTAMP](https://cmake.org/cmake/help/latest/policy/CMP0135.html) warning
screm
was able to build tiles from source
=> build(cmake): deduplicate library setup

.github/workflows/matrix.yml
SUMMARY: Build "Used merge queue to prevent build breakages"
use merge queues to prevent breakages when merging multiple approved PRs.
added merge queue for general build matrix.
- https://github.blog/2023-07-12-github-merge-queue-is-generally-available/
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
- `Require merge queue` needs to be enabled in branch protection settings.
=> ci: use merge queue

src/CMakeLists.txt, tests/test_main.cpp
SUMMARY: Infrastructure "Fix stale config remaining between test invocations."
Fix stale config poisoning consecutive test runs https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3208#pullrequestreview-1640783348
Re-create test user dir before running tests
Before:
Run tests, change language in options to ru, run tests again, see error.
After:
No error occurs.
=> Refresh test user dir on each test run

src/CMakeLists.txt, src/ncurses_def.cpp
SUMMARY: None
Fix failing osx curses build
https://github.com/CleverRaven/Cataclysm-DDA/pull/56918
None, will have to be done by CI
=> Fix compile error on MacOS curses

src/CMakeLists.txt, src/monster.cpp
SUMMARY: Interface "Show monster immunity in extended description"
expose more info to players, in this PR, immunity
- reused `describe_flags` lambda
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/b545f49e93df7f4a42191c9512958f84b1ca32dc/src/damage.h#L23
- made it render as 'posion' and 'smoke' despite being a single m_flag (MF_BIOPROOF), because i couldn't figure out a better way
name its immunity `biohazard`
1. spawn a zombie, zombie firefighter, zombie master, and prototype robot.
2. e(x)amine then read (e)xtended description
3. its immunity is shown.
- which would be better? `biohazard` or `smoke` + `poison`?
- should we split this damage type into two?
- are there `smoke` or `poison` damage type?
=> feat: show monster immunity in description

src/iuse.cpp
SUMMARY: Interface "Using blood draw kit now asks what container to fill, only defaults to filling the item if you cancel"
Whenever I find myself needing to draw blood (usually for alchemical stuff in Arcana), I always have to unload the blood draw kit again and again, every single time I want to reuse it. This fixes it by having the iuse skip right to that step.
In iuse.cpp, changed `iuse::blood_draw` so that the blood being drawn up gets ran through `liquid_handler::handle_liquid` instead of immediately defaultin to filling the blood draw kit, so you can opt to fill another container with it immediately and go back to sucking blood.
Also means that if drawing acid blood destroys the item, it'll just not produce any acid for you instead of giving you a container of acid that's …
=> Allow filling containers directly from blood draw kit

src/item.cpp
SUMMARY: Performance "Speed up item::has_flag calls"
During my investigation of just why NPCs take so much time to process I discovered `item::has_flag` getting called a lot and taking up a large amount of the total processing time for NPCs. Looked into how the function is implemented and saw that a really expensive call to `json_flag::get( const std::string &)` is done first every time and that most of the time it continues on to checking itype flags and finally item instance flags.
Invert the execution a little. We don't care exactly what gunmod or toolmod has the flag. What we care about is if ANY has the flag. This is pretty cheap to check in the common case of `no gunmods, no toolmods` and we'll never need to check the more expensive `json_flag::get( flag )`.
Other minor change is to …
=> perf: speed up item::has_flag calls

src/filesystem.cpp, src/filesystem.h, tests/filesystem_test.cpp, tests/test_main.cpp
SUMMARY: None
This is #3259, but actually working
Let's try out some of the new C++17 features
Re-tested manually, + added automated tests with UTF-8 paths for the new function.
=> Properly remove stale test user dir

src/coordinate_conversions.cpp, src/coordinate_conversions.h
SUMMARY: Performance "port inlining of sm_to_ms_copy function for performance gain"
- port https://github.com/CleverRaven/Cataclysm-DDA/pull/66889 by @akrieger 
forgive me for changing to trailing auto return syntax, the header was very hard to read for me as the signatures weren't aligned
<details><summary>No noticable changes in wilderness</summary>
</details> 
around 16.67% improvement.
stay tuned for next PR port: https://github.com/CleverRaven/Cataclysm-DDA/pull/67535
=> perf(map): inline `sm_to_ms_copy`

data/json/items/tool/woodworking.json, data/json/recipes/other/tools.json
SUMMARY: Content "Mainlined Stone Chisel from Magiclysm"
The stone chisel wasn't actually in vanilla BN, with Magiclysm having me totally fooled and thinking it was already in vanilla. I see no good reason for vanilla to only have tools with chiseling 3. This will allow for more variety in chiseling requirements in recipes and constructions. I see no good reason for this to not be a vanilla BN item.
Adds the stone chisel found in Magiclysm to the list of tools, alongside its recipe. (placed in woodworking due to that being the major use-case I can see)
None
Made sure the game didn't explode in awe of the stone chisel, and confirmed that it is in fact craftable (after fixing the fact that it explicitly said difficulty 0, which the game didn't like)
=> Mainline Stone Chisel

src/npcmove.cpp
SUMMARY: Performance "Change frequency of NPC cached weapon value update"
One of the hotspots of NPC update is regeneration of the AI cache. One part in particular, `ai_cache.my_weapon_value = npc_ai::wielded_value( *this );`, is very slow to process taking around 1/3 of the total singular NPC update time. Looking deeper at where `ai_cache.my_weapon_value` is used we see a single access location in `npc::character_danger` which is itself only called from `npc::evaluate_enemy` when the passed parameter is an NPC or Player.
Because `ai_cache.my_weapon_value` is not the only consideration when evaluating perceived danger I don't think it will be harmful to the NPC to be a little inaccurate in that consideration by having mildly outdated information.
Pretty simple. Wrapped the line so that it …
=> perf: change frequency of cached weapon value update

src/mapgen_functions.cpp
SUMMARY: Bugfixes "Reworked lake shore mapgen for better connection with rivers"
Fixes #3185. More pics below.
Original mapgen shrinks away from lakes, and then tries to adjust shore points when it see familiar patterns. Due to their amount covering of all possibly layout it's very difficult tasks.
New mapgen works differently - it doesn't care that much about lakes, instead it looks for precise positions of junctions, and attach shores to them.
This approach have its pros and cons. I always know where shoreline should be connected. But determining how to connect them between each others it's a bit more difficult task, which... i didn't solved. Currently it connect two closest valid points, it works well, but can break apart 3-way conjunction which could been connected if done right(first …
=> Reworked lake shore mapgen for better connection with rivers

src/npcmove.cpp, src/suffer.cpp
SUMMARY: Bugfixes "Fix NPCs eternally drowning after being thrown into deep water despite afterwards getting out of it"
Prevent NPCs from drowning eternally if they are thrown into deep water, even after walking onto land again.
The first commit fixes a bug where an NPC, after being thrown into water (for instance by a kevlar hulk), would eternally drown, even after getting onto land (unless debugging was used to constantly give them health, they would constantly take torso damage and quickly die). This fix also has the second effect that NPCs now will be treated as being submerged when walking into deep water, causing drowning after enough time. This second effect has drawbacks due to the behaviour of NPCs not currently having drowning avoidance programmed into it. The fix is inspired by …
=> Fix eternal drowning when NPC is thrown into deep water.

src/character.cpp, src/character.h, src/creature.h, src/mutation.cpp, src/suffer.cpp
SUMMARY: Performance "Port character dead state caching from DDA"
ported
- https://github.com/CleverRaven/Cataclysm-DDA/pull/67535 by @akrieger 
- https://github.com/CleverRaven/Cataclysm-DDA/pull/44060 by @zhilkinSerg
=> perf: cache character's dead state

.github/workflows/matrix.yml
SUMMARY: Build "Fix merge queue ignoring status checks"
- fixes #3284  (hopefully)
=> ci: don't skip checks in merge group

src/character.cpp
SUMMARY: Bugfixes "NPCs being immortal and crashing the game"
- fixes #3286 
1. changed `<` to `<=` when setting bodypart to trigger death check for parts with hp 0
2. `cached_dead_state: std::optional<bool>` means
- `std::nullopt`: uninitialized 
- `true` : dead (cached)
- `false`: not dead (cached, should not be set from `is_dead_state`)
however previous code was setting `cached_dead_state` to false, which shouldn't happen.
spawned and killed npcs using guns and debug command.
maybe just use enum?
aaaaaaaaaahhhhh
=> fix: only set `cached_dead_state` if npc is actually dead

.github/workflows/android.yml, .github/workflows/manual-release.yml, .github/workflows/release.yml, android/.gitignore, android/app/build.gradle, android/app/jni/Application.mk, android/app/src/main/AndroidManifest.xml, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties
Bugfixes: "Fixed failing android build caused due to ndk version"
- fix #3280 
- port https://github.com/CleverRaven/Cataclysm-DDA/pull/64305 by @BrettDong
=> build: bump android ndk

src/monmove.cpp
SUMMARY: Bugfixes "Prevent monsters from wandering into an attack across zlevels when fov_3d is off."
A monster that wanders or scent moves into the player will ignore fov_3d restrictions when attacking them.
If fov_3d is off it prevents it from attacking across zlevels.
Spawned a giant wasp above me. It doesn't attack now.
=> Fix monsters attacking across z levels when wandering

src/bionics.cpp, src/npcmove.cpp
SUMMARY: Bugfixes "Revert one per minute frequency addition to npc::regen_ai_cache and fix cache invalidation"
Having wielded value to be calculated and cached only once per minute is a clunky solution caused by the bug in `deactivate_weapon_cbm`. The bug was forcing the cache to become invalid every turn so the following turn it was recalculated instead of actually being used.
Removed the `once_every` wrapping condition introduced in #3283 and move the cache invalidator from outside the loop to inside so the cached value is invalidated only when the NPC is actually turning off weapon cbms. Now, instead of possibly calculating other values using up-to 1 minute old data the NPC will use the most accurate data it can. More accuracy, fewer calls to the expensive function.
Waited several …
=> fix: remove wield value frequency, fix cache invalidation

data/json/recipes/food/drinks.json, data/json/recipes/recipe_deconstruction_package.json
SUMMARY: Balance "Make clean water recipe using purification match efficiency of activating water purifiers"
Belated followup updates for https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2832, making the use of water purification tablets consistent between its iuse and recipe, and other updates.
1. Changed it so that the clean water recipe using tablets takes 8 water and outputs 8 clean water, as per the ratio its iuse now uses. This also fits even with the water filter items, because those use the exact same use action as the tablets and thus were made 8x as effective too. It even affects vehicle water purifiers.
2. Reduced number of tablets gained from taking apart an MRE from 6 to just 1. Still a net increase from 1.5 liters of water purified to 2 relative to the original amounts, …
=> Water purification tablets now work consistently

src/activity_handlers.cpp, src/iuse.cpp
SUMMARY: [Balance] "Prying nails correctly deconstructs reinforced boarded window"
There was no way to deconstructed a reinforced boarded window. I used the hammers pry nails function to do so.
I added a new else if for the function in activity_handlers.cpp with the correct planks, nails, target terrain, and resulting terrain based on the construction recipe and the else if for boarded windows. I added it above the one for boarded window as its sequential.
Edit: I also added the two terrains to the iuse.cpp so they can be correctly targeted, and ensured you can't pry nails out while mounted.
JSONization via targeting a flag, which I can't do.
SDL is broken on compiling for me thanks to issues with the main branch. I could not test so it will need testing. This should be relatively simple …
=> Prying nails correctly deconstructs reinforced boarded window

src/character.cpp, src/character.h, src/creature.h
SUMMARY: Performance "Fix dead state caching again"
revert #3287, rollback #3282
use dynamic dispatch for all part hp modification methods, and invalidate dead state cache from there
duplicate codes are awful, but rewriting API involves editing lots of other files and conflicts with existing PR such as #2250 or #2776
could kill NPC using guns and melee. debug NPC killing works as well.
=> perf: correctly cache and invalidate dead state

src/bionics.cpp
SUMMARY: Bugfixes "Fix Repair Nanobots"
- #3054 caused an issue where repair nanobots weren't healing. Closer examination revealed it was due to damaged parts not being updated.
Add back code that marks limbs for repair, keep mending parts out of it.
Reworking Nanobots for the nth time to do new and weird things.
Spawned character, damaged torso and one limb to 60 HP. Added self-aware mutation to track HP.
Installed Repair Nanobots, added 100 kJ power.
=> Fix Repair Nanobots

tests/monster_test.cpp
SUMMARY: Infrastructure "Mark monster_speed_trig as mayfail"
It's failing, but if seems to be one of those RNG-dependent tests that exceed the thresholds with the right seed
Mark test as mayfail. A dedicated investigation may yield proper results.
Should work as is.
=> Mark monster_speed_trig as mayfail

data/mods/DinoMod/regional_overlay.json, data/mods/No_Hope/regional_map_settings.json, src/init.cpp, src/map_extras.cpp, src/regional_settings.cpp, src/regional_settings.h
SUMMARY: Bugfixes "Check mapextra ids for regions"
Trying to track down and fix random test failure from https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/6318661870/job/17158134285#step:11:2378
Check mapextra ids for regions
Waiting for test suite... Done, works as expected:
```
(continued from above) ERROR: Warnings for region_settings "desert_test":
defines unknown map extra 'mx_mass_grave_dino'
defines unknown map extra 'mx_nest_daspletosaurus'
01:35:26.208 ERROR DEBUGMSG : src/regional_settings.cpp:1115 [void check_regional_settings()] Warnings for region_settings "river":
defines unknown map extra 'mx_mass_grave_dino'
defines unknown map extra 'mx_nest_daspletosaurus'
01:35:26.208 ERROR DEBUGMSG : src/regional_settings.cpp:1115 [void check_regional_settings()] Warnings …
```
=> Check mx ids defined for region

.github/workflows/matrix.yml
SUMMARY: Build "Always run build matrix test for merge queue"
yet another continuation of #3285
remove all preconditions, will always run
hecc
can only be tested from CI
reference: https://scribe.rip/@kojoru/how-to-set-up-merge-queues-in-github-actions-59381e5f435a
=> ci: always run build matrix test for merge queue

data/json/items/ammo/shot.json, data/json/items/ammo/shotpaper.json
SUMMARY: Balance "Give shotshells baseline dispersion, consistency updates for scrap shells, paper shot, birdshot"
Consistency updates for some 12 gauge and 20 gauge shot loads.
1. Changed scrap shot's damage to be 0.75x that of 00 shot instead of 0.6x. This makes it correctly be more damaging (60) than birdshot is currently.
2. Changed birdshot to not override default dispersion to 1000. It doesn't matter statistically since it still uses AoE effects, but it does make it more visually consistent and makes it less hassle to tweak other dispersion values.
3. Gave 00 shot a baseline dispersion of 20. This makes the increased dispersion of black powder loads actually visible.
4. Set scrap shot to have 60 dispersion, to make its stated poor accuracy evident. Also set it to have an armor …
=> Further consistency updates for shotshells

src/iexamine.cpp
SUMMARY: Bugfixes "Set it so resuming a partial construction can be resumed in the dark if it's marked as being doable in the dark"
This fixes the inability to resume a partial construction in the dakr when the construction in question can be started in darkness just fine.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3331
In inexamine.cpp, changed `iexamine::trap` so that the check for whether you can resume a construction also checks for if the construction in question can be constructed in the dark. This also entailed moving the construction definition `&built` a bit earlier into the function so the construction can be checked for `dark_craftable`.
Figuring out how to make it use the related function `player_can_see_to_build` instead. I figured out how to get it to get …
=> Allow resuming dark-craftable constructions in the dark

data/json/construction.json, src/construction.cpp
SUMMARY: Bugfixes "Port over fix for deconstructing furniture over carpet, time change"
This ports over a fix related to deconstruction of simple items, along with also porting over a JSON improvement to simple deconstruction.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3330
Given rationale for the time change:
> Simple deconstruction is used basically exclusively for furniture that you "pick up". Examples: mattress, carpet, pallet of cement bags, band saw, oven, charcoal kiln, mannequin, hammock, indoor plant, stack of planks, resin pod. None of these deserve to take 10 entire minutes to disassemble.
C++ changes:
1. In construction.cpp, changed the bigger spicier version of `can_construct` so that its check for requested flags distinguishes between terrain and furniture. …
=> Port over two improvements to simple deconstruct

data/json/external_tileset/alternative_mutation.json
SUMMARY: Bugfixes "Strict JSON warnings when loading new mutation tileset"
```
DEBUG    : (json-error)
Json error: <unknown source file>:2:10: Invalid or misplaced field name "type" in JSON data
{
"type":
^
"mod_tileset",
"compatibility": [
"UNDEAD_PEOPLE_BASE",
FUNCTION : void JsonObject::report_unvisited() const
FILE     : /home/scarf/repo/cata/Cataclysm/src/json.cpp
LINE     : 125
VERSION  : BN 8b4336bb134b
```
hotfix for #3340.
for some reason object format errors wheras array format doesn't
wrap it in array
make the behavior same for objects...
loaded without errors.
=> fix: misplaced field name error on mutation tileset

.github/workflows/matrix.yml
SUMMARY: Build "Trigger workflow check on merge queue (for this time, real)"
make merge queue actually useful
github merge queue creates temporary branches under `gh-readonly/{target branch}/`. trigger workflow there instead.
1. add 'require status check' to PRs
2. PRs fail due to flaky tests
3. give everyone admin rights so it could be bypassed
4. ???
5. _chaos insurgency_
needs to be merged in order to test.
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-third-party-ci-providers
- https://github.com/orgs/community/discussions/46757#discussioncomment-6990903
=> ci: trigger workflow check on merge queue

src/item.cpp
SUMMARY: Bugfixes "Fixed some issues with displaying item's mods counter"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/212. Displayed name is formed by checking long `else if` chain, and because of that mods counter could be processed partially, or skipped, or override later parts.
Rearranged processing order to make sure game won't skip any of mods check, nor following formatting.
Not fixing this bug.
Spawned some items, looks good.
TOOL_ARMOR with both clothing and tool mods, and scabbard with both clothing mod and content:
=> Fixed some issues with displaying item's mods counter

data/json/ammo_effects.json, data/json/items/chemicals_and_resources.json
SUMMARY: Balance "Give acid fired out of a water cannon acid trail effects instead of using emit_actor hackery"
Some belated fixes for weird behavior with acid used in water cannons. In particular, for whatever reason it likes to only spawn acid at the very edge of its range or in front of any walls it hits, even if it has to shoot acid clean through an enemy it is clearly hitting to do so. I tested this with both the fiddly `emit_actor` method and with an aoe-type ammo effect and yeah, it doesn't work good either way.
1. Removed `RECOVER_10` from all acid items.
2. Instead, added ammo effects `ACID_TRAIL` and `ACID_TRAIL_WEAK` for all acid items that have an acid emit as their `drop_action`. Idea here is, instead of always just dumping a glob of maximum intensity at the end point of …
=> feat: acid trail for acid cannons

src/character_functions.cpp
SUMMARY: Interface "Grey out incompatible ammo in reload menu"
- closes #2817.
In reload menu ammo and magazines incompatible with target gun will be greyed out. They still can be used, if player wants to do that for some reason, it's just cosmetic thing.
Compared ammo types, colorized.
Using color from `item::color_in_inventory` it's also an interesting option, but that'd be misleading if there's another gun in inventory compatible with proposed options.
Spawned and reloaded bunch of items.
=> Grey out incompatible ammo in reload menu

data/json/items/ranged/archery.json, data/json/items/tool/misc.json, data/json/recipes/ammo/arrows.json, data/json/recipes/ammo/components.json, data/json/recipes/ammo/other.json
SUMMARY: Balance "Consistency updates for explosive/flammable arrows/bolts, allow using impact fuses in recipes"
This updates some explosive recipes to make use of impact fuzes as an alternative to primers where relevant, and to use an associated crafting requirement that expands on the options for what to feed explosive ammo with. A few other consistency updates too.
1. Set it so that explosive homemade rockets use any available explosive material instead of only blackpowder, increased explosive requirement a fair bit since its raw damage is MUCH higher than spiked rockets, and added the need for an impact fuze or primer.
2. Reworked explosive bolts to be made by applying explosive arrowheads to regular bolts, updated recipe to be consistent with explosive arrow recipe and allow using a …
=> Updates for homemade explosive/flame ammo

.github/workflows/i18n-extraction.yml, .github/workflows/i18n-printf-format.yml, lang/dedup_pot_file.py, lang/extract_json_strings.py
SUMMARY: build "Validate that template extraction works"
- fix #3350
- added `mutation_flag` section to 
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/f6afd6b1076e9d7b27a986e39d010da524ceb490/src/init.cpp#L247-L286
- run checks when `src/init.cpp` is modified (where types are defined)
- add more cpp files to look for?
- trigger on header file changes?
- rewrite `extract_json_strings.py` in typescript 
- add translation extraction feature to serde class
- _rewrite it in rust_
was able to run `lang/update_pot.sh` locally
=> ci: validate that template extraction works

.github/workflows/matrix.yml
SUMMARY: Build "Reverts cataclysmbnteam/Cataclysm-BN#3349"
1. now the workflow does run on merge queue but it still does not affect status checks. (unless [required status check is enabled on branch protection](https://github.com/orgs/community/discussions/46757#discussioncomment-7192504))
2. [adding only required status check to merge queue](https://github.com/orgs/community/discussions/46757#discussion-4836009) is not possible atm
3. runners are bottlenecked due to workflows running needlessly.
=> Revert "ci: trigger workflow check on merge queue"

.github/workflows/documentation.yml
SUMMARY: Build "Only deploy docs when needed"
There's no need to run workflow when no docs are changed.
Only run the workflow when files under `doc/` changes
create a separate repository, `cataclysmbnteam/doc`. i think it should be eventually done in long-term.
=> ci: only deploy docs when needed

src/avatar_action.cpp
SUMMARY: Bugfixes "Prevent stepladders from player to sink down a floor"
- fix #3366
check if there's a floor first
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/d003f7c5-d311-49a8-badf-f0dd85022f1f
=> fix: don't sink down a floor from stepladder

data/json/npcs/NPC_Brigitte_LaCroix.json, data/json/npcs/missiondef.json, data/json/npcs/refugee_center/surface_refugees/NPC_Uyen_Tran.json, data/json/npcs/refugee_center/surface_refugees/NPC_Vanessa_Toby.json, data/mods/DinoMod/NPC/NC_BO_BARONYX.json, src/missiondef.cpp, src/translations.h
SUMMARY: Bugfixes "Fixed mission names misused as mission description"
Fix #3229.
Prevent missions from having long and verbose names that look ugly in the UI.
The bug was caused by use of tags in mission name, but tags are supported only in mission description.
1st commit changes name into description for affected missions.
2nd commit adds automated check that discourages long names in favor of using the `description` field.
3rd commit tweaks names of the missions that trigger the new check.
40 is an arbitrary limit, can be changed.
(The name does not match because Leo is the NPC I've debug-added the mission to)
=> Fix mission names misused as mission description

src/overmap.cpp
SUMMARY: Bugfixes "Fixed infinite loop in mine gen"
There's a rare infinite loop condition in mine gen caused by generation point straying beyond overmap boundaries.
Limit amount of attempts, and add boundaries check.
Porting mutable overmapspecials.
I had it reproduce when running tests with seed 1696620459 on game version e82ebec7734021ad2ba56208a0bae5030ee15bfc compiled with Clang 15.0.7 (Kubuntu 22.04), after fix it no longer enters infinite loop.
=> Fix infinite loop in mine gen

data/json/items/melee/bludgeons.json
Summary [Feature]: "Add flashlight functionality to the Shock Tonfa"
The item description of the shock tonfa mentions an integrated flashlight, however when it is on there is no flashlight. This resolves that inconsistency.
Adds the `LIGHT_20` tag to shock tonfa (on), and updates the item description.
needs fixing, must be fixed
looks good to me
bug found by 𝖙𝖍𝖍𝖔𝖓𝖊𝖞օՑ on discord.
=> Add flashlight to the Shock Tonfa

src/bionics.cpp, src/item.h, src/npc.h, src/npcmove.cpp, src/ranged.cpp
SUMMARY: Bugfixes "Use std::optional for `best_mode_for_range()`"
- Fix #3293, fix #3288
- Update #2773 
- closes #3325
`best_mode_for_range()` can now return a null value for `gun_mode` if no valid mode is found. This will then be caught in `wield_better_weapon()` where the `mode_id` would be used to set `gun_mode` and in `ideal_ranged_dps(0` which now returns a dps value of 0 if `gun_mode` supplied is null.
- Turning the whole thing optional.
- Rejected on the basis of it preventing easy structured binding, as well as mode_id never needing to be null.
Load saves from [here](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3329#issuecomment-1741922208) and #3293. Test and see that it does not crash. 
God I love working with NPCs.
=> Use std::optional for `best_mode_for_range()`

src/sdlsound.cpp
SUMMARY: Performance "Prevent lag caused by frequent sfx"
- fix #3371 
don't generate stack backtrace when sfx fails to play
- make it WARN instead of DEBUG. iirc failing to find sound also generates this error?
- write proper de-spamming algorithm for repeated sfx to prevent channels chocking up, but it's harder than changing two lines of code.
=> perf: do not error on SDL sound failure

src/character.cpp, src/character_turn.cpp
SUMMARY: Performance "Remove unnecessary check for lifting equipment if unnecessary and store nontrivial calculations in variables"
In `recalc_speed_bonus` we were recalculating `weight_carried` and `weight_capacity` multiple times in the worst case. These are not trivial calculations, so store in local variables and reuse if necessary. Additionally, the most trivial call of the three to check for the `DEBUG_STORAGE` trait is done last rather than first. In the very rare case that it is available we will want to short circuit the logic and skip calling `weight_carried` / `weight_capacity` altogether.
In `weight_carried_reduced_by`, which is called as part of `weight_carried` calculation, there is an expensive check of the local area for something with the `"LIFT"` quality. This is done …
=> perf: slightly speed up `weight_carried_reduced_by` and `recalc_speed_bonus`

src/character.cpp, src/npc.cpp
SUMMARY: Bugfixes "NPCs drop items if overburdened instead of just overvolume, merchant restocking fix"
Merchant NPCs in the Refugee Center, `Christopher Flood, Merchant` and `Makayla Sanchez, Arsonist`, stay way overburdened even after calling `drop_invalid_inventory` because it was only able to drop items above volume limits. Combined with the checking for the `"LIFT"` quality when overburdened in `weight_carried_reduced_by`, a very slow check because it looks over all items in tiles (map and vehicle) within `PICKUP_RANGE` distance of the NPC, these two NPCs were using a lot of CPU time to do literally nothing but stand in place.
This problem is mitigated in #3385 since these NPCs do not carry weapons a lot of the time. They're also relatively shielded from the monsters hidden within …
=> fix: NPCs drop excess items if overburdened, merchants pick up and renew inventory if restocking

src/character.cpp
SUMMARY: Bugfixes "Only NPCs should be dropping items automatically when overencumbered"
Fixes issue with the speed test errors mentioned by Olanti [here](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3386#issuecomment-1751771907)
Only NPCs should be dropping items automatically when overencumbered. The player should not. The player can continue to just tumble items out if over volume capacity like they have been for a long time.
Add an early out of the function if Character is not an NPC.
Leave the player automatically dropping items, modify test to add a fake activity target. That wouldn't have actually fixed the issue though.
Compiled, ran relevant tests, they passed.
I need to be more on the ball about running the test suite for regressions.
=> fix: only NPCs drop items when overencumbered

data/json/items/vehicle/engine.json, data/json/vehicleparts/combustion.json
SUMMARY: Balance "Rebalance power of steam turbine to a 1 MW turbine like the small gas turbine, lower weight"
Some rebalancing brought about by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3387 prompting me to look more into what's typical for small power generation steam turbines. 1-5 MW seems more common for power generation turbines, and the low end of that gives me a value that matches the small gas turbine.
1. Updated steam turbine power to match that of the small gas turbine, and updated energy consumption to be consistent with the listed 45% energy efficiency. I avoided that value previously because I assumed it was better to not have power output identical to another engine of different fuel type, but this is already done with a good number of gas and diesel engines, and …
=> Rebalance steam turbine relative to small gas turbine

data/json/professions.json
=> Forgot the s

data/json/items/book/misc.json
SUMMARY: Bugfixes "Set required intelligence for Playboy magazine to 0"
Fixes #3374  - Allows use of playboy magazine while illiterate by lowering intelligence required to 0
Lowered the intelligence required for Playboy magazine to 0 so it is able to be "read" while illiterate, just like the First Aid Instruction Booklet
Possibly creating a category for illustrated books i.e. being able to mark a book as illustrated so it can be read - however 0 intel requirement covers this quite well I think
Made an illiterate character, spawned the magazine and "read" it successfully
=> Set required intelligence for Playboy magazine to 0

src/recipe_dictionary.cpp
SUMMARY: Bugfixes "Fix FPE on disassembly of very low volume books"
Fixes #3400 where we get an FPE due to autogenned book uncraft recipe time being directly correlated to volume.
Force autogen book uncraft recipes to assume at least 1 page of output regardless of item volume when calculating time required to uncraft.
Spawned a few books along with `computer printout` which is in the sub-12.5mL volume FPE induction zone. Butchered them all. No crash.
=> fix: books < 12.5mL may crash on disassembly

src/sounds.cpp
SUMMARY: Bugfixes "Prevent a rare UB in sounds"
Prevent a possible use after free. An npc hearing a sound could then make a sound themselves. In that event that this resizes the sound list this will invalidate the iterators and cause a UAF.
Make a copy of the list and iterate over that. Not perfect but it prevents the problem. 
Be more careful about how the list is modified in the first place.
It's very difficult to trigger it and it probably won't be noticeable without sanitizers on so...
I triggered it while testing the item identity branch but none of what's going on here has changed there.
=> Prevents possible use after free in sounds

data/json/uncraft/ammo/40x46mm.json
SUMMARY: Bugfixes "Add casings onto dissasembly recipie for M433, M576 and M651 grenades"
Fixes #1471 - Adds casings onto dissasembly recipie for M433, M576 and M651 grenades, M1106 already has casing in recipie and 40x46 flashbang is now marked as obsolete
Add appropriate casings onto dissasembly recipie for M433, M576 and M651 grenades
Don't add casings in
Loaded into built base game and tested
=> Add casings onto dissasembly recipie for M433, M576 and M651 grenades

src/item.cpp
SUMMARY: Bugfixes "Emit debugmessage on non-rigid armor capacity <= 0"
Fixes #3399 
Removes possibility of div-0 error (SIGFPE) when calculating volume-based encumbrance additions. Doesn't happen in the majority of cases, and only really showed up with Cata++'s ammo belts until recently. Clang-tidy gets really upset about it so it should get looked at.
Change condition from `capacity < 0` to `capacity <= 0` so that it can never be `== 0` during calculation and cause the SIGFPE.
Tell Clang-tidy to suck it up until we get more FPE reports.
On old Cata++ version emitted errors for its ammo belts
```text
06:11:04.185 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item …
```
=> fix: emit debugmsg on capacity <= 0

data/json/harvest.json
SUMMARY: Balance "Universally change chitin from bone to skin, and add specific harvest messages for chitinous animals."
Currently, chitin is classified as "bone" for _some_ (but not all!) animals with exoskeletons. This means that most animals with exoskeletons cannot be skinned for chitin, and have to be fully butchered as though the chitin were on the animal's _inside._ By changing chitin from bone to skin for every chitinous animal, Players are now able to "skin" the exoskeletons of giant bugs and the like for chitin. 
Furthermore, as a small flavor change, add the same message as when harvesting shellfish ("You carefully crack open its exoskeleton to get at the flesh beneath") for every animal with chitin except acid ant queen (which already had its own) and mutated mammals with …
=> Change Chitin from "Bone" to "Skin", and add a message when harvesting chitinous animals.

.github/workflows/matrix.yml
Follow-up to #3258.
There was a missing condition that caused matrix to run a step that should've been skipped.
=> Fix build matrix

src/armor_layers.cpp
SUMMARY: Bugfixes "armor layer not showing all first"
- fix #3423
comparison via "num_bp" was not working properly, let's just use tabindex, which is still hacky but at least it uses num_bp to indicate end which works and i want 0.4 merged fast afsdklasdjfsljk
rewriting this cursed thing
1. open a save.
2. open align armor display using `+`
3. now it shows `All` correctly
_i want conventional commits soooo bad, Summary isn't very helpful, let's either remove it completely or require it to be as polished as an blogpost section so we can actually use it in devlog or something_
=> fix: armor layer not showing all first

src/npcmove.cpp
SUMMARY: Bugfixes "NPCs no longer phase through solid rock when climbing"
Scarf told me to fix this and I cri
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3431
In npcmove.cpp, implemented a condescend version of the "check that neither current position nor" checks implemented back in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2982 to prevent NPCs from phasing through solid rock for no good reason.
1. Screaming.
2. Making Scarf do it.
2. Recruited my starter NPC and lined the shelter with walls of solid rock.
3. Confirmed they can't nope through the wall to get out anymore.
4. Reversed our positions, confirmed they can't break in via magic either.
5. Gave them a chain link fence outside to climb over, confirmed thst still works fine. …
=> fix: NPCs phasing through solid rock

data/json/items/tool/fire.json
SUMMARY: [Bugfix] "Fixed the electric lighter's description saying you cannot craft it."
You can craft the electric lighter, but the old description says you couldn't.
I changed its description.
I could just leave it as-is.
The json checks out.
=> Electric Lighter Description Fix

data/json/overmap/multitile_city_buildings.json
SUMMARY: Bugfixes "Add s_electronics_2 to multitile city buildings"
Fixes #1896 - links s_electronics_2 and s_electronics_roof_2 in multitile city buildings
link s_electronics_2 and s_electronics_roof_2 in multitile city buildings
None
Built game and tested, confirmed by going to electronics store with correct variation
=> fix: missing roof for `s_electronics_2` in multitile city buildings

src/avatar_action.cpp, src/bodypart.cpp, src/bodypart.h
SUMMARY: Bugfixes "Fix CTD after wearing power armor"
Fix CTD when trying to wear pa helmet anything after wearing power armor
Fix segfault caused by removing-while-iterating in `body_part_set`.
Make it so body_part_set operations don't unnecessarily copy the set.
Remove a duplicate code snippet.
Add `const` and comments where appropriate.
Does not crash anymore, lets you wear both PA and helmet
Fallout from #2776
=> Fix body_part_set operations

src/activity_item_handling.cpp, src/npcmove.cpp
SUMMARY: None
Housekeeping
Fix warnings
Getting rid of tidy
Should work (tm). Iteminfo-related warnings are left in to avoid conflicts with #3434
=> Fix tidy warnings

data/json/mapgen/isherwood_farms/cabin_isherwood.json, data/json/mapgen/isherwood_farms/farm_horse_isherwood.json
SUMMARY: Bugfixes "Add faction owner to Isherwood cabin and horse farm items"
Fixes #1201 - Adds faction owners to Isherwood cabin and horse farm items
- Add faction owner array for Isherwood cabin
- Expand faction owner array for Isherwood Horse Farm
- Add faction owner array for Isherwood Horse Farm second flooe
None
Loaded into base game and tested
=> Add faction owner to Isherwood cabin and horse farm items

src/recipe_dictionary.cpp
SUMMARY: Bugfixes "Fixed search in crafting menu by description"
Fixes #2903
Use correct iteminfo query.
I was able to search by martial style with this fix, as well as snippets from item description.
=> Fix search in crafting menu by description

src/character.cpp
SUMMARY: Bugfixes "Cost of starting fire with bionic should match activation cost"
Fixes #2340
Problem with that thing is that "enough bionic power" assumed by player doesn't really match game's expectations:
Starting fire with any bionic need 5kJ+, which is higher than activation cost of Finger Lighter CBM. Thus it can fail when stored energy below that hardcoded cost.
Cost of starting fire will match bionic activation cost for Finger Lighter(5->3) and Finger-Mounted Laser(5->30). Starting fire with Integrated Toolkit still hardcoded at 5kJ.
* It might make sense to reduce cost of lighting fire with Integrated Toolkit from 5 to 1, to match crafting costs, but that would make Finger Lighter even more pathetic than it currently is.
* Making Finger-Mounted Laser consume something like …
=> fix: match bionic firestarting cost same to its activation cost

src/armor_layers.cpp
SUMMARY: Bugfixes "bodypart layer ordering UI not displaying `All` first (again)"
- fix #3423
made tabindex default 0
hecc
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/3aafbad3-91df-4f76-981b-47739e99ecf6
_it works on my machine_
referenced DDA loc: https://github.com/CleverRaven/Cataclysm-DDA/blob/078a7b43be36c11f2431bf52f5f00d2d41c9a53a/src/armor_layers.cpp#L614-L615
~~i have no idea how string_id behave on flat_set~~
=> fix: bodypart layer not displaying `All` first (again)

.github/workflows/manual-release.yml
SUMMARY: None
Enable Lua in manual (stable) releases.
Copy over the define from `release.yml`.
Should work (tm)
This should bring manual release action up to date with experimental release action
=> Enable Lua in manual releases

src/iexamine.cpp, src/item.cpp, src/options.cpp
SUMMARY: Balance "Add growth scaling world option to control speed of crop growth instead of directly binding it to season length"
Season length in and of itself doesn't affect the game's balance all that much, or at least it shouldn't. A player, especially one switching over from DDA, may choose to set it higher simply due to the obvious appeal of realistic year length, but may not necessarily like that with it comes a heavy impact on the viability of early-game farming.
Mirror the existing world option 'Construction scaling' and introduce 'Growth scaling', a player-editable percentage value to apply to seed growth times, while keeping the existing season length scaling in place if set to 0 (this is the default).
Additionally, applying fertilizer to a plot used to advance a seed's growth …
=> Decouple crop growth time from season length, add separate scaling option

data/json/external_tileset/alternative_mutation.json
SUMMARY: Bugfixes "alternative ear mutation not being overriden"
it was reported that feline ears weren't being overriden after #3340.
UDP tileset, for some reason, generates both-gendered overlay. it has higher precedence than genderless varaint, so the overriding wasn't working properly. did the same to alternative overlays.
RIIR compose.py into something sensible
_it works on my machine_
=> fix: alternative ear mutation not being overriden

data/json/furniture_and_terrain/furniture-appliances.json
SUMMARY: Balance "Make grid appliances refund solder on deconstruction"
Deconstructing grid furniture does not return the 20 solder spent on connecting it. Solder can be somewhat hard to procure early on, so simply rearranging items in player's base comes at an unreasonable cost that's both unrealistic and adds nothing gameplay-wise, especially considering that installing those same appliances into a vehicle is free, not counting tool charges.
In short, moving around things player already has should not have noticeable resource costs.
Adjust JSON entries for all grid furniture, adding 20 solder to deconstruct items, as well as range of 10-20 solder to bash items (10 and 5-10 respectively for the few articles that cost 10 to install). Additionally, adjust both battery chargers to always …
=> Make grid appliances refund solder on deconstruction

src/armor_layers.cpp
SUMMARY: Bugfixes "Properly Highlight combined opposite bodyparts"
- fix #3454
check whether bodyparts are combined and is opposite
aaaaahhhhhh
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/59f0709c-5657-4ee8-9eba-a3b3af0ebcdd
=> fix: no highlights in combined opposite bodyparts

data/json/mapgen/warehouse.json, data/json/vehicle_groups.json
SUMMARY: "Fix vehicles placement in "warehouse" aka small warehouse"
Correct misplaced vehicles and remove some.
Change the placement point of "flatbed_truck" because is wrecked on walls.
"flatbed_truck"/Flatbed Truck and "tatra_truck"/Heavy Duty Cargo Truck are wrecked if they appear at the same time, so delete "tatra_truck".
Make a bigger small warehouse...
Before:
After:
=> Fix vehicles placement in small warehouse

.github/workflows/release.yml
SUMMARY: Build "Change the Ubuntu version used for Linux builds from 22.04 to 20.04"
- fix #2778
Port of https://github.com/CleverRaven/Cataclysm-DDA/pull/64264 because a Debian user brought up their inability to play recent releases due to this
Changes the workflow to use Ubuntu 20.04 for Linux builds rather than 22.04
Let the users of these distros suffer!
It worked for DDA, and I can't exactly test how github builds it without creating the PR in the first place. (So far as I know)
Hopefully the co-authorship and link to original PR is worthy enough credit to original PR author over on DDA's side.
=> Change the Ubuntu version used from 22.04 to 20.04 for Linux Builds

data/json/furniture_and_terrain/terrain-fences-gates.json
SUMMARY: Bugfixes "Fix privacy fences refunding incorrect materials on deconstruct"
Regular segments of wooden privacy fence return 1-2 door hinges, which is not used for its construction and should be reserved for gate tiles only. They also return 2 more planks than it takes to build them.
Finally, the gate section refunds 1-2 out of 2 hinges. The random element here makes little sense, there's no reason not to return the full amount.
Fix the JSON values to not magically create or vanish any materials.
Deconstruct private wooden gate and fence tiles. Make sure the materials returned match the building components.
=> fix: privacy fence refunding incorrect materials on deconstruct

data/json/obsoletion/terrains.json, data/json/overmap/multitile_city_buildings.json, data/json/overmap/overmap_connections.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_transportation.json, data/json/overmap/special_locations.json, src/options.cpp, src/overmap.cpp, src/overmap.h, src/overmap_special.h, src/overmapbuffer.cpp, src/savegame.cpp, src/start_location.cpp, tests/overmap_test.cpp
SUMMARY: Content "Specials placement rework"
Specials placement is sucks. It's almost impossible to see things with restrictive placement conditions, like marina. That's a draft attempt to make it suck less.
Instead of throwing things at random and hoping for the best mapgen will actually search for place where to put things, and as long as overmap *can* fit requested special - it will be placed, no random failures anymore.
Amount of specials is also changed. Old implementation balance that naturally - if 90% of map is covered by water, then 90% of attempts to place farm will fail hitting wrong terrains.
Here, if we're asking game to place 10 farm - it will do that, even if it'll need to put them side by side on tiny island, which is looks ugly. To avoid that overmap calculates its …
=> feat(content): specials placement rework

data/json/construction.json, data/json/construction_group.json
SUMMARY: Features "Added the ability to build the most common wall. its called t_wall. its under 'build standard wall'"
Because you could not build the most used wall in the game. we could paint, and remove them, but not build them.
Added the wall to construction_group.json under 'constr_wall_standard' and added it to construction.json under 'constr_wall'
none really, it should have been in the game a while ago.
debug built the wall in different area's, everything looked fine to me, its modeled after the wooden wall already in the game.
=> feat: 'Build Standard Wall' to the build menu

.github/pull_request_template.md
SUMMARY: Infrastructure "Updated PR template on GitHub for better readability, added new information"
The template text became somewhat inconsistent in style over time, and there is new information that would be useful for PR authors.
1. Explain how to allow maintainers to edit the PR
2. Use website links for documentation
3. Add explanation on code style, and link to the general "Code style" docs. Make code style section into a visually distinct section.
4. Add a small note on choosing PR titles
5. Get rid of square brackets in Summary explanation, they only serve to confuse people
6. Move summary line template out of comment to make it more obvious how it should look (glimpsed in DDA PR template)
7. Get rid of an outdated snippet about changelog
8. Don't ask people do delete the `` …
=> Update PR template for better readability, add new information

.github/workflows/release.yml
SUMMARY: Build "Revert previous PR to release"
Turns out there's a good reason why it was on 22.04, and the compiler downgrade made build very unhappy. Thus, this PR to revert.
Changes the version of Ubuntu used for Linux builds back to 22.04
N/A
Reverting back to how it was before I borked it ought to un-bork it
Sorry Debian 11 users, at least I tried. Guess you'll have to use Debian 12.
=> Revert previous PR to release.yml

build-data/osx/Info.plist
SUMMARY: Build "Set application name to Cataclysm BN on OSX"
As described in #3501, having the same application name as CDDA causes problems for some interactions on OSX when you have both installed.
Fixes #3501
It's just a static metadata change
It's possible the bundle name should change, but I'm not sure, so I left it
This will cause save data to become located at `~/Library/Application Support/Cataclysm BN` instead of `..../Cataclysm`. This means that after this is released, OSX users will need to `mv` their old save files or rename them in Finder.
As a side benefit, this means that CDDA save data and BN save data are now in separate locations
=> Set application name to Cataclysm BN on OSX

data/json/itemgroups/supplies.json, data/json/monsterdrops/zombie_survivor.json
SUMMARY: Balance "Basic survivor zombies have a random smattering of their associated itemgroups, sometimes yield post-apoc currency instead of cash cards"
A minor item on my idea list that came up a while ago, also being something Tefnut mentioned wanting to look at. Their idea if I recall was more along the lines of making the itemgroup contents use a lot more stuff that the average player is likely to end up favoring, which we can always do on top of this later on. Right now my focus is actually using the related item groups more, the contents of which can be tweaked later on if desired.
Updated the monster drops for basic survivor zombies. In summary:
1. Instead of calling for `clothing_outdoor_set`, it's split up into the relevant component itemgroups, with roughly a 10% chance of …
=> feat(balance): fleshing out survivor zombie drops

data/json/construction.json, data/json/construction_group.json, data/json/furniture_and_terrain/terrain-floors-outdoors.json, data/json/itemgroups/Locations_MapExtras/locations.json, data/json/items/chemicals_and_resources.json, data/json/recipes/other/materials.json, data/json/regional_map_settings.json
SUMMARY: Content "Port over iron ore and bog iron from Innawoods and Mining Mods"
The continued saga of doing literally anything but work on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3419 due to how convoluted it's looking to be, this time I figured I'd tackle a misc feature on my todo list pertaining to innawoods metalworking.
Takes aspects from both DDA's Innawoods mod and DN's old Mining Mod.
1. Added generic iron ore items. Could be hematite, could be magnetite, could be a mess of iron-eating bacteria infested mud (currently the latter's the main source so), gods forbid it better not be limonite. Volume and weight leans more on the side of Mining Mod's interpretation of hematite, scaled down to an amount that fits for being processed into a single lump of steel.
2. Added …
=> feat(content, port): bog iron

data/json/recipes/electronic/tools.json, data/json/uncraft/generic.json
SUMMARY: Balance "Added a voltmeter recipe"
Voltmeters are an important item for messing about with grids but weren't craftable. Now they're a little less random to obtain.
I used the uncraft to make a craft recipe, gave it the same time and components plus added cutting, I made it take electronics 2 as it's probably a bit harder than other recipes. I pruned the uncraft instead of obsoletion because this is reversible so it won't change.
Wait, people use the electric grid?
The pure json ran on my copy. Maybe the tests will break so I can be mad about it.
a
=> feat(balance): craftable voltmeter

src/worldfactory.cpp
SUMMARY: Bugfixes "Prevent crash when `lastworld.json` is corrupted or empty."
Had an issue today where someone's computer didn't end the game appropriately, corrupting `lastworld.json`, this caused a crash that would consistently prevent the game from starting with no warning except crash log messages.
Use try and catch to catch exceptions and report them when they occur loading `lastworld.json`
Need others to test for me, my computer is down. This should be tested via creating `lastworld.json` in the config folder. Either leave it empty or in various states of incomplete/wrong format.
=> Prevent crash when `lastworld.json` is corrupted or empty.

data/json/uncraft/generic.json
SUMMARY: Balance "Faster uncraft for rags and fibrous stalks"
As I have discussed with @scarf005 rags and fibrous stalks have a very punishing uncraft time of 1 hour.
1. I believe an uncraft time of 1 hour for a single rag or fibrous stalk is unnecessary and tedium. The counterargument is that it encourages you to gain thread from looting locations or from strings, but I feel it is an unnecessary game mechanic to discourage uncrafting rags on bulk and encourages players to hoard a massive supply of rags that they are unwilling to use for thread and won't need for tailoring after a certain point. Example is that uncrafting 4 mattresses gives you more rags than you'll ever need.
2. You can receive 6 short strings from a long string in 5 minutes, and 50 thread per short string in 5 minutes, …
=> feat(balance): shorten uncraft time for rags and fibrous stalks

data/json/itemgroups/Weapons_Mods_Ammo/gunmod.json, data/json/itemgroups/art_antiques_crafts.json, data/json/itemgroups/main.json, data/json/items/gunmod/accessories.json, data/json/items/ranged/crossbows.json, data/json/recipes/weapon/mods.json
SUMMARY: Content "Add a spanning lever gunmod for crossbows"
This adds an idea that came up while discussing https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3441 on the discord, that it was decided oughta be set aside as a separate PR to avoid bogging that one down.
1. Added item for a crossbow spanning lever, based off medieval examples. Toned down the reloading bonus from 50% off to only 25% off compared to my first mockup of it. Realistically it'd be more in the vein of reducing strength requirements to reload, but the way `STR_RELOAD` works means there's nothing to reallly mess with. It's all just a big reload time and a reduction in reload time that scales with strength, and trying to tweak that from either end means faster reloads in the end.
2. Added `accessories` slots to …
=> feat(content): crossbow loading lever gunmod

data/json/overmap/overmap_terrain/overmap_terrain_recreational.json
SUMMARY: "Move "stadium_3_2" to the right place."
"stadium_3_2" should not be displayed as a stadium field.
From the Hitchhiker's Guide to the Cataclysm (Bright Nights Editon).
"stadium_3_2" appears as a field on the map:
After, without tile on the map:
=> fix: stadium overmap terrain

src/character.cpp, src/creature.cpp, src/creature.h, src/npc.cpp, src/savegame_json.cpp
SUMMARY: Bugfixes "Fix crash in ranged accuracy test related to dead NPC cleanup"
Fix test that's randomly failing on macOS, and MSYS2.
According to the debugger, the crash happens when the code tries to cast a non-null raw pointer `Creature* killer` that's stored inside the `Creature` class to the pointer of type `Character*` in `npc::die` function. What I suspect happens here is that the killer gets deallocated before their victim, so the cast results in an attempt to use stale pointer.
There's also a random crash in tests on MSYS2 build, and @Vollch examined it and it turned out to have very similar source (`clear_all_state() -> clear_map() -> clear_npcs() -> g->cleanup_dead()` in ranged tests), so I believe this should fix that issue as well.
Solution is to switch `killer` from raw C …
=> fix: crash in ranged accuracy test related to dead NPC cleanup

src/character.cpp, src/item.cpp
SUMMARY: Balance "Fix shields not blocking ranged hits anymore, port over arpen being reduced by multi-layered armor from DDA"
This addresses an issue that was pointed out a while back with the ammo rebalance affects, namely that a high armor penetration is good and working as intended against a single high-armor item, but undermines the effectiveness of layering low-mid value items. Or as the PR OP put it:
> Armor penetration is broken, both because it has absurdly high values and also because it renders single armor layers useless (you could wear 20 individual hypothetical 1mm kevlar shirts and still take full damage from a 5.56 nato round, which has 6 armor penetration, but if you had a single 8mm thick kevlar shirt, it would stop the bullet almost entirely)
This is actually more …
=> feat(balance, port): arpen reduction via layered armor, make shields block ranged hits

.github/workflows/matrix.yml
SUMMARY: Build "[DDA Port] Fixed clang 14 build in GHA"
Clang14 asan tests are failing to build.
GitHub has installed gcc 13 on runners, so now clang tries to compile against gcc 13 toolchain and fails.
Solution is to trick clang into using an older gcc toolchain.
Original PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/62405
This could've been done with a single argument if we had clang 16 and its `--gcc-install-dir` option.
Waiting for GHA to complete the checks.
tony_stark_tired_face.jpg
=> ci(port): Fix clang 14 build in GHA

data/json/mapgen/bus_station.json, data/json/mapgen/pizza_parlor.json
SUMMARY: "Fix: bus station, pizza parlor mapgen"
Fix misplaced vehicles and replace wooden floors under street lights and traffic lights with correct floors.
Use "mapping" to get the right floor under street lights and traffic lights.
Change the y point of the buses.
It works.
=> fix(map): bus station, pizza parlor mapgen

data/mods/DinoMod/items/helmets.json
SUMMARY: Mods "[DinoMod] dino helmets do something"
Updates dino helmets to have same stats as wolf skull helmets
Adds coverage, encumbrance, warmth, and a looks_like to match wolf skull helmets (actually wolf skulls don't offer warmth, but I think it should)
Add armor stats to this and wolf skulls, beyond scope. These are intended to match wolf skulls
Simple JSON copy and paste
Thanks to MisterWytt on Discord for reporting this
N/A
=> [DinoMod] more dino helmet stats

data/json/harvest.json
SUMMARY: Balance "More kevlar plates when skinning kevlar zombies"
Kevlar zombie and kevlar hulk ought to be this massive creature with kevlar armor fused in and yet skinning them gives pretty low amount of kevlar plates, to the point that it's not worth the time.
With 5 survival and hunting knife i got 3 kevlar plates from kevlar zombie and 6 from kevlar hulk. I find this number underwhelming so i doubled this number and a bit. This should make kevlar hulks and zombies a useful resource of materials, given the time spent on this task.
Simply changed mass ratio of harvestable "skin" in harvest.json.
Change their description.
Loaded the game, and tested how many plates i get with survival 5 and hunting knife.
=> feat(balance): buff kevlar zombie skinning

src/armor_layers.cpp
SUMMARY: Bugfixes "Prevent debugmsg when removing armor while resorting"
Get rid of the bad debugmsg.
Make sure the iterator is out of scope when we call takeoff.
=> fix: debugmsg when removing npc armor

src/vehicle.cpp, src/vehicle.h, src/vehicle_part.cpp, src/vehicle_part.h
SUMMARY: Bugfix "Fix problem resizing vehicle parts"
Fixes #3545.
I forgot that resizing the parts list causes a copy which breaks the locations. It now repairs them afterwards. 
This is in with the rest of the vehicle hack stuff that's getting removed when they're made into game objects.
=> Fix vehicles going glitchy when parts are added

src/player_activity.cpp
SUMMARY: Bugfixes "Remove UB on test suite exit"
I'm hoping this fixes #3551.
When the player's activity is set to null it doesn't clean up the activities targets as well. When global deconstruction happens stuff gets cleaned up in a random order. If the target safe_references get cleaned up after the global structures they use it causes UB.
Can't reproduce this one locally so we'll have to see if the suite here works.
=> fix: prevent UB on test suite exit.

src/mapgen.cpp, src/monster.cpp, src/monster.h, src/vehicle.cpp, src/vehicle.h, src/vehicle_part.cpp, src/vehicle_part.h
SUMMARY: Bugfixes "Fixes a crash when vehicles are split"
Fixes #3552.
Rejig the constructors for vehicles and their parts. Also cleanup the removed parts right after the split to prevent further bugs.
I've also done a bit of cleanup and removed an unused monster constructor and added their missed inventory to the other. There's also a few references added to remove unnecessary copies.
=> fix: vehicle split crash

src/activity_handlers.cpp
SUMMARY: Bugfixes "Fix filling containers from maps ending early"
Fixes #3556.
Backwards conditional was causing it to end early.
=> fix: filling containers from the map

data/mods/Magiclysm/recipes/materials.json
SUMMARY: Mods "Actually add in the recipes for processing owlbear pelts"
I **somehow** didn't include the actual recipes for processing the pelts previously.
Dig the recipes file out of the trash bin, and put it in the proper place.
Actually working more on Orcs instead of playing excessive amounts of Mount and Blade Warband
Went in game, made sure the recipes existed.
Me upon being informed of this error:
=> feat(mods/magiclysm): add missing owlbear pelts recipe

src/player_activity.cpp, tests/player_helpers.cpp
SUMMARY: Bugfixes "Fix broken activities"
Fixes #3564. Turns out a lot of activities are broken right now.
The pr to get rid of UB in the test suite was misguided and caused way more problems than it solved. I didn't realise activities are calling set_to_null at the top of their handlers so removing the targets there broke a lot of stuff.
I've reverted that and added something to the test suite state clean to scrub that explicitly. I might come back to look at null activity setting at some point but this should fix the problems for now.
=> fix: broken activities

src/inventory.cpp, src/pickup.cpp
SUMMARY: Bugfixes "make items sorted again"
Fixes #3542. 
Places where it was previously using item's < operator had a layer of indirection added and so it was happily using the pointer's < instead. * dereferences and fixes this.
=> fix: item sorting

src/locations.cpp
SUMMARY: Bugfixes "Update vehicle weight when items are moved to/from it with aim"
Fixes #3553. 
Invalidate the vehicle's mass when moving items around using the new location stuff.
=> fix: invalidate mass when moving items to/from vehicles

src/game.cpp
SUMMARY: Bugfixes "Fix mending vehicles from the menu"
Fixes #3570. 
Was checking the act incorrectly meaning even when veh_interact::run returns a null action it would still be used overwriting the action created by mend_item.
=> fix: mending vehicles

data/json/items/armor/boots.json, data/json/items/armor/gloves.json, data/json/recipes/armor/feet.json, data/json/recipes/armor/hands.json, data/json/recipes/armor/head.json, data/json/recipes/armor/torso.json, data/json/recipes/other/tools.json, data/json/uncraft/armor.json, data/json/uncraft/generic.json, data/json/uncraft/tools.json
SUMMARY: Balance "Improve crafting and disassembling consistency for common clothing and other items"
Item disassembly is annoying for two reasons. Firstly, some clothing articles commonly encountered in loot take way too long to take apart for no good reason despite not producing anything particularly valuable.
Secondly, way too many items slip through the cracks of the generic salvage system while having no specific disassembly recipes of their own. After handling another haul of loot you're often left with a bunch of garbage items that are so utterly useless you end up just having to throw them into fire. Or, alternatively, you have to pick and choose your loot more carefully, but that's just one annoyance to escape another.
UPDATE: Wow this went outside of initial scope fast. I first …
=> feat(balance): tweaks for crafting and disassembly consistency

data/json/items/classes/range.json, data/json/items/ranged/crossbows.json, src/character.cpp
SUMMARY: Balance "Sanity-check behavior of STR_RELOAD flag, re-add it to crossbows"
So it was a while back brought to my attention that crossbows don't seem to be benefiting from strength anyway. I went into this assuming that the `STR_RELOAD` flag doesn't work, and on looking at its code it is indeed a bit janky and weird-looking.
Then I eventually found the real problem: most crossbows had the flag removed from them ages ago, but their description still implies they should be using them. Instead only a few items use them. There was a "fix" on DDA's end that just amounted to removing it from most weapons and fixing the description, but this fix was still pretty half-baked. Yes, in theory, drawing the crossbow to full draw is only part of the reloading process and being super-strong will …
=> feat: fix and add `STR_RELOAD` to crossbows

src/inventory.cpp
SUMMARY: Bugfixes "Fix bad clear on inventories"
Fixes dump_remove not actually removing the items and potentially causing all sorts of location problems. 
Actually clears the inventory.
=> fix: bad clears on inventories

src/item.cpp
SUMMARY: Bugfixes "Fix being unable to consume favorited items"
Fix a missing property in item cloning.
Add it. Writing the autogen stuff so we don't have to do this stuff manually is my next goal once the refactor has settled.
=> fix: Add missing favorite on item copy

src/item.cpp, src/location_vector.cpp, src/npcmove.cpp
SUMMARY: Bugfixes "Npcs removing splints no longer gives a debugmsg"
Fixes #3590. Adds a missing copy property. Also makes the iterator errors not cancel the action. This was how I originally imagined them, I must have autopiloted to make them abort early.
Move the removal outside the loop. Turning it into a call to something like remove_with would be the ideal way but this won't conflict with the other pr fixing their AI.
=> fix: npc splints and clean up iterator errors

src/item.cpp
SUMMARY: Bugfixes "Fix crafting leaving 0 item stacks"
Fixes #3596.
Bad comparison.
=> fix: crafting leaving 0 item stacks

src/mapgen_functions.cpp
SUMMARY: Bugfixes "Better fallback for cut lake shoreline"
To make better shore. I missed this case during previous shore rework. There wasn't a lot of marinas to stumble upon it...
Currently when there's no pairing shore second point is mirrored from first one, but as can be seen on pic below it's not always works well. New approach - find non-water neighbour, and set connection point at the middle of its edge.
Connecting to the corner point between water and non-water tiles should also work. But middle seems more robust.
Regenerated few maps.
Ignore rotation, that's the same case.
Before:
After:
=> fix: Better fallback for cut lake shoreline

src/activity_handlers.cpp
SUMMARY: Bugfixes "Fix Repair Item activity occasionally encountering a bad pointer when initiated from vehicle/grid"
- Should fix #3591.
Repair Item activity was crashing because it tries to construct an item from an invalid pointer when the activity is initiated from vehicle/grid, as the fake_item used to initiate the activity stops existing after initiating the activity. Prior to item identity this wasn't an issue as item location can lead to invalid locations so long as you don't actually use it.
Cleaned up `repair_item_finish` a bit, restructuring it so it doesn't even try to call the pointer unless it's confirmed it should have a valid one.
- Remove the hack for grid/vehicles.
- Ideal, won't be me though since I don't really know how to do this properly, it was a struggle hooking in …
=> fix: Repair Item activity occasionally encountering a bad pointer when initiated from vehicle/grid

data/json/items/comestibles/protein.json
SUMMARY: Balance "Carnivores can eat protein drinks"
Carnivores are tagged to only eat certain materials, such as flesh or milk. Protein drinks are set to water and shakes are set to fruit. Since protein powder is made directly from dried meat, it seems fitting to let them drink it.
I set protein shakes to flesh and fruit, and protein drinks to flesh. The reason flesh is the crafting recipe, we don't have a way to extract the whey from cheese to make protein powder so instead its made from meat.
Set them to milk and add the ability to extract whey, plus differentiate between meat powder and whey powder.
I can eat them now.
=> feat(balance): carnivores can eat protein drinks

src/veh_interact.h
SUMMARY: Bugfixes "Fix crash during save when working on a vehicle"
Fixes a crash that could happen when the game autosaves while you work on a vehicle. Don't think there's an issue for this one.
Initialize a variable.
=> fix: crash in vehicle activities

data/json/mapgen/gunsmith.json, data/json/mapgen/mil_surplus.json, data/json/mapgen/s_gun.json, data/json/mapgen/store/s_hunting.json, data/json/monstergroups/zombies.json
SUMMARY: Balance "Define a monstergroup for zeds spawning at gunstores, hunting supply stores, and military surplus stores"
One of those misc ideas brought up back when I was adding ferals to monstergroups if I recall, and came up again while adjusting balance of survivor zombie monsterdrops.
1. Defined monstergroup `GROUP_ZOMBIE_GUNSTORE`, meant to have a higher than normal number of survivor zombies and ferals, though not as high as prepper house spawns. Has survivor zombies/ferals (elites and ferals being offset to spawn later as is normal) about 25% of the time in total, cop/soldier zombies 10% of the time, assorted zombie dogs 5% of the time, and assorted civilian non-profession zeds 25% of the time.
2. Set gunstores and hunting supply stores to use `GROUP_ZOMBIE_GUNSTORE` instead of …
=> feat(content): monstergroup for gunstores, milsurp, etc

src/character.cpp, src/item.cpp
SUMMARY: Bugfixes "Fix crafting destroying tools sometimes"
Crafting was sometimes destroying tools that it shouldn't be.
Rejig the code so it just consumes ammo rather than destroying.
=> fix: crafting destroying tools sometimes

src/activity_handlers.cpp, src/activity_item_handling.cpp, src/avatar.cpp, src/character.cpp, src/character.h, src/iuse.cpp, src/iuse_actor.cpp, src/locations.cpp, src/melee.cpp, src/monattack.cpp, src/monexamine.cpp, src/npcmove.cpp, src/npctalk.cpp, src/npctalk_funcs.cpp, src/player.cpp, src/ranged.cpp, tests/behavior_test.cpp, tests/crafting_test.cpp, tests/invlet_test.cpp
SUMMARY: Bugfixes "Fixed error dropping wielded count-by-charges items"
Fixes #3606. 
Removed character::i_rem(item*). This function is a bit awkward and slow, doesn't work right with cbc items and can be easily replaced with item->detach().
=> fix: Dropping wielded `count-by-charges` items causing errors

src/npcmove.cpp
SUMMARY: Bugfixes "Fix errors when npcs pickup items"
Fixes #3607. 
Don't erase the items from the stack as they're being collected. They'll be detached later anyway.
=> fix: errors when npcs pickup items

src/locations.cpp
SUMMARY: Bugfixes "Unseal modified containers"
Fixes #3588. 
Call on_contents_changed when manipulating contained items via locations.
=> fix: Unseal modified containers

src/magic_spell_effect.cpp
SUMMARY: Features "Liquid summoned by spells can be stored and used"
To make liquid summoning spells actually useful.
Trivial.
None.
Made a spell for testing(not included in PR), it works.
=> feat: Liquid summoned by spells can be stored and used

src/consumption.cpp, src/item.cpp, src/item.h, src/locations.cpp, src/locations.h
SUMMARY: Bugfixes "Fix a few item related bugs"
Fixes #3631, more completely this time.
Missed the case where attempt_detach is used to remove the item. I've improved the logic on attempt_detach in general so property changes during the handler are better respected and the remerging is forced.
=> fix: Better attempt detach logic

src/active_item_cache.cpp
SUMMARY: Bugfixes "Fix food rotting incorrectly"
Fixes half of #3610. Technically that issue is two separate bugs. This fixes the food not rotting away. The food rotting too quickly is fixed by PR #3639. 
The num_to_process was being used after it had been iterated down to -1, meaning it would just repeatedly process the first item. This moves the use above the loop.
=> fix: food rotting incorrectly

src/veh_interact.cpp
SUMMARY: Bugfixes "Fix red text when refilling cars"
Fixes red text when filling a car.
Get rid of the bit that's trying to remove 0 charge remnants. That's not needed anymore.
=> fix: red text when refilling cars

src/item_factory.cpp, src/npcmove.cpp, src/ranged.cpp
SUMMARY: Bugfixes "Prevent segfault caused by not calculating modes in gunmods"
- fix #3315
- possibly fix #3014
~~- `item::gun_all_modes`
- before: require item to **BE** `gun` and **NOT** `gunmod`
- after: require item to be **EITHER** `gun` **OR** `gunmod`, as the following loop seemed to handle both.~~
- added debugmsg in `[confident_shoot_range](https://github.com/cataclysmbnteam/Cataclysm-BN/commit/0666c90d4bab4b54fbc9679157537d0dac56307e)` to warn empty modes (and prevent segfault)
EDIT:
followed suggestion from
- [kheir](https://discord.com/channels/830879262763909202/830916451517857894/1172521526378123264)
- [olanti](https://discord.com/channels/830879262763909202/830916451517857894/1172528443250970684)
and prevented gunmods from being calculated.
cri …
=> fix: calculate modes in gunmods too

data/json/overmap/overmap_special/specials.json
SUMMARY: Balance "Rebalanced occurrences of some specials"
With latest changes some specials went way off balance, that an attempt to improve it.
For reference: [context](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3520#issuecomment-1801283529), [documentation](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/5b43ade4b2f86fc48589e25a6521cf6d59723ab7/doc/src/content/docs/en/mod/json/reference/map/overmap.md#placement-rules).
There might be more things which need adjustments, feedback welcome.
Lakes changes:
* All islands increased from 0-1 to 0-3, and untied from cities. Raw occurrences assumes a full lake overmap, so even with 0-3 lakes are desolated enough. And islands shouldn't care about cities at all.
* Island prison got bigger min distance from city - it won't noticeable …
=> feat(balance): Rebalanced occurrences of some specials

.github/workflows/manual-release.yml, .github/workflows/release.yml
SUMMARY: Build "bump dmgbuild to 1.6.1 to prevent build failure in macos" 
- fix #3578
=> ci: bump dmgbuild to 1.6.1

data/json/ammo_effects.json, data/json/ammo_effects_simple.json, data/json/flags.json, data/json/items/ammo.json, data/json/items/ammo/metal_rail.json, data/json/items/ammo/nail.json, data/json/items/classes/gun.json, data/json/items/gun/flammable.json, data/json/items/gun/misc.json, data/json/items/gun/paintball.json, data/json/items/gunmod/rail.json, data/json/items/ranged/spearguns.json, data/json/obsoletion/items.json, data/mods/Aftershock/items/bioparts.json, data/mods/Aftershock/items/gun/laser.json, data/mods/Aftershock/items/weapons.json, data/mods/CRT_EXPANSION/items/crt_gun.json, data/mods/No_Hope/Items/gunmods.json, data/mods/No_Hope/Items/guns.json, data/mods/TEST_DATA/items.json, src/ranged.cpp
SUMMARY: Bugfixes "Fix NON_FOULING flag not working due to typo"
- fixes #3645
DDA removed their accidental hyphen-based item flags to underscore based ones, BN didn't follow. Thus BN was using `NON-FOULING`. #3354 introduced `NON_FOULING`, which made the hardcoded flag look for `NON_FOULING`.
search and replace
hecc.
spawned and fired A7 laser rifle a lot.
before: got fouling
after: got no fouling
=> fix(content): `NON_FOULING` flag not working due to typo

.github/workflows/manual-release.yml, .github/workflows/release.yml
SUMMARY: Build "Only release daily"
we have too much releases, 99% are unused and makes navigating painful
release daily iff there were commits yesterday.
maybe set cron to run 23:00?
will run on fork.
=> ci: release daily

data/json/overmap/overmap_mutable/slimepit.json, data/json/overmap/overmap_special/specials.json, src/mapgen.cpp, src/overmap.cpp, src/overmap.h
SUMMARY: Content "Converted slimepit special to mutable"
Yet another step on my crusade to unhardcode specials.
Slimepit have very simple layout, mutable one is pretty much identical.
Also, you might notice that i'm removing `oter_above == "forest_water"` -> `ter_set("cavern" )`. This thing does not work since `forest_water` is in `skip_above`. Some ancient relic.
DDA got fancy pit entrace with slopes, which can also be ported and integrated in mutable slimepit. That's a pure JSON thing, so it won't be difficult to port if someone likes it. I wasn't excited enough by its appearance to bother.
Generated few slimepits.
Slimepit used to merge with neighbors years ago, but it's been broken during one of very old refactors. Salvaged that by the way.
Before:
After:
=> refactor(content): Convert slimepit special to mutable

src/character_turn.cpp, src/magic_enchantment.cpp
SUMMARY: Bugfixes "Stat changes from relics persist across save/load"
So after returning to the problem of enchantment effects not kicking in properly until a turn later, I figured out what should be a less clunky solution than what I sought to do in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2965.
This at least will fix the issue of save/load negating stat effects, but I'd like to figure out away to also fix the "have to wait a turn for transforming relic effects to kick in" thing. Though, making transforming items have `moves` set high enough might be a good enough work around for that I guess so maybe this'll be good enough.
1. In magic_enchantment.cpp, took the stat increases out of `enchantment::activate_passive`...
2. And in character_turn.cpp, put them directly into …
=> fix: save/load breaking effect of relic stat boosts

src/mapgen.cpp, src/overmap.cpp
SUMMARY: Bugfixes "Fixed mutable copy-from"
Should fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3665
On my system it cause segfaults, but it comes from same mod and same special. Must be a build difference.
And it kinda makes sense that it starts ranting about unresolvable joins, if `outward_joins` got duplicated during second finalize.
Added some checks to clean old data on finalize, which is happens *twice* when special is copy-from'ed. And some more small adjustments to make it more copy-from proof.
Also, by the way, removed obsolete anthill check in mapgen.cpp. It's currently handled by json.
Rewriting copy-froms -_-
Start game with PKs_Rebalancing(it does copy-from Anthill) mod, spawn regular anthill. Before fix it used to segfault me, not anymore.
=> Fixed mutable copy-from

data/json/items/corpses/corpses.json
SUMMARY: Bugfixes "Add NO_SALVAGE flag to corpse item, preventing it from being targeted by 'cut up everything' selection"
So somehow salvage by weight inflicted...this on us:
Far as I can tell it's because some janky behavior buried in the code changes means that, while it correctly still skips over corpses as valid targets for individual salvage, the "cut up everything" prompt can see corpses as valid now.
Added `NO_SALVAGE` to the base corpse item. Turns out it's really that simple a workaround, you shouldn't be able to try and salvage corpses instead of butchering them so they shouldn't be salvageable, simple as.
Hunting down the mistake in the code and fixing it there when I barely understand the PR I ported over in the first place.
1. Checked affected file for syntax and lint …
=> fix: don't allow cutting up corpses

.github/pull_request_template.md, .github/semantic.yml, .github/workflows/pull-translations.yml, doc/src/content/docs/en/contribute/changelog_guidelines.md
- enforce [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for PR titles
- remove redundant `## Summary`
install https://github.com/apps/semantic-prs to enforce PR title
pain
used them on other projects, they work as intended
Q: Nooo, do i have to edit all those PR titles, i don't know how to do that
A: No worries, i've been doing that manually for months and this app just prevents me from overlooking one
Q: Then can i just write whatever on PR title and you'll fix it for me?
A: It'd be very nice if you could follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), tho.
Semantic PR bot also needs to be approved to enforce the PR title consistency.
=> ci: semantic PR title via conventional commits

src/character.cpp, src/character.h, src/character_turn.cpp, src/game.cpp, src/iuse_actor.cpp, src/player.cpp
This salvages another of the fixes from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2965 and puts it in a separate PR.
In iuse_actor.cpp, set `iuse_transform::use` to include a call to `recalc_sight_limits` in case the transformation in question affects vision. Fixes vision items like infrared goggles requiring you to wait a turn after toggling them before the visual effects update. Also affects stuff like changing eye encumbrance restricting night vision, like raising or lowering the visor on the welding mask.
Per Olanti's suggestion, adjusted the way night vision is checked for to not use a weird cache that seems custom-made to do nothing but delay the night vision effect kicking in for a turn, via adjusting `recalc_sight_limits` to check for NV effects directly, same way that. …
=> fix: update eye encumbrance, infravision when transforming items

.github/labeler.yml, doc/src/content/docs/en/mod/json/reference/creatures/effects_json.md, src/character_turn.cpp, src/effect.cpp
We had no way of using effects to add or remove sleep deprivation, now we do.
It appears under effect.cpp adding a new "member" for SLEEPDEBT and the relevant json fields happen there, and under character_turn.cpp is the part that hooks into mod_sleep_deprivation to cause the relevant effect to change a players stats.
I don't know the underlying code, this was reworked from the thirst effect and modified to work for sleep.
scream
I loaded one of my old worlds from 0.4 stable and this change had no related bugs. I have successfully tested it using a spell effect from my mod. You can add the json field `"sleepdebt_min": [ -100 ]` to any effect you want on testing.
Here's some screenshots.
We need to update all effects documentation. That is out of scope right now.
If this is a C++ PR that …
=> feat(content): Add sleepdebt effect

.github/workflows/matrix.yml
Bandaid for #3664. ASan/UBSan builds don't properly work at the moment, but take up available VMs and prevent mac build from running.
Temporary disable ASan/UBSan until the issue is resolved.
No idea what's up with it. The ASan/UBSan build fails intermittently, so maybe running it under debugger and waiting till it hangs would reveal the issue, but that's not something I have any desire to deal with at the moment.
The checks on this PR
I've left it as a comment so we don't forget and it stays there as a constant reminder.
=> ci: temporary disable ASan/UBSan builds

src/catalua.cpp
Fix crash when when trying to load a world while missing one of the mods that the world uses.
Skip invalid mods when de-/serializing data.
Banning modded saves from being eligible to be reported for bugs.
Save from #3665 now loads on vanilla BN
=> fix: crash when trying to load a world while missing a mod

data/json/itemgroups/Locations_MapExtras/map_extras.json, data/json/mapgen/map_extras/mass_grave.json
fix: mass_grave map extras because mass_grave doesn't appear correctly.
Debug mass_grave and it looks correct.
Before:
After:
=> fix: mass_grave map extras

data/json/overmap/overmap_connections.json, src/mapgen_functions.cpp, src/mapgen_functions.h, src/overmap.cpp, src/overmap.h
Mostly to remove sewers generation from `generate_sub()`. To eventually(after mutable mines) remove whole that loop iterating over all overmap tiles.
And it also fixes few sewers-related bugs, such us when sewer entrance is disconnected from tunnel(due to missing end mapgen), or when sewer leads to the point with no entrance at all(due to lack of manhole in city center).
Sewer mapgens combined in one function, to implement mapgen for end tiles, and reduce clutter.
Roads used to override manholes due to terrains order in overmap_connections.json, fixed now. Chance to generate manhole reduced from 1/2 to 1/8 to compensate increased amount.
City centers now have manholes - sewer specials connects to center, so it need to way in. Also, all manholes generate subways during city generation, so …
=> fix: sewer rework

data/json/items/gunmod/laser_gunmods.json
Discord described issue with some non-pistol energy weapon mods not applying due to mod target category being narrow. Expanded it to all energy weapons as this doesn't change vanilla behavior but allows mods to use it in more versatile ways without overwriting it.
Trimmed down the mod target category to any weapon with energy weapons
- Add machine gun category so that it fits more closely with original format that included both pistol and rifle skill using guns.
- I can't see the harm in allowing it on SMG and Shotguns from mods. If/when we add new energy weapons we may then balance this at our leisure.
=> feat: Convert non-pistol only energy weapon mods to be compatible with all energy weapons.

data/json/obsoletion/terrains.json, src/savegame.cpp
Hotfix for migration hotfix(https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3661). To cover missing case(https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3666#issuecomment-1811692042).
As per testing migrating of ill-migrated terrains doesn't really work - such OMT becomes "nothing" on load, without preserving old\converted IDs. Thus previously added crutches are not doing anything, and can be removed.
None.
It builds, runs, and still didn't exploded my PC.
=> fix: another fix for anthill migration

src/character.cpp, src/character.h, src/player_activity.cpp
Fixes #3686.
Have restore_outbounds_activity use the players current activity rather than accepting an argument.
=> fix: Crash in npc activities

data/json/overmap/overmap_mutable/lab.json, data/json/overmap/overmap_mutable/mine.json, data/json/overmap/overmap_special/mine.json, doc/src/content/docs/en/mod/json/reference/json_flags.md, src/mapgen.cpp, src/overmap.cpp, src/overmap.h, src/start_location.cpp
More unhardcding. That terrible loop in `generate_sub()` is now completely emptied, and removed.
Mine layout is pretty much same as it used to be - one lengthy tunnel with stairs down and finale.
Mapgen function is *slightly* adjusted, to get rid of those ugly corners in 2x2 empty spaces. They always annoyed me. Now it's nice round support.
Nested mines special is a bit hacky(starts with solid rock above the tunnel) to make it resemble old mines as much as possible.
Added "RESTRICTED" special flag. Strictly speaking, this thing is *not* necessary, as nested things wouldn't be spawned as starting location anyway(not in default region at least), due to terrain checks. But. Game does not knows that, and would search for valid place anyway, which used to be painfully slow. It's very rare …
=> refactor(content): convert mine special to mutable

data/json/monsters/mechsuits.json, src/character.cpp, src/monexamine.cpp
Some minor tweaks/fixes to mechs.
C++ changes:
1. In character.cpp, fixed `Character::mount_creature` printing the "you hear your X whir to life" message twice.
2. In monexamine.cpp, set `monexamine::mech_hack` so that the default card needed for mechs is an industrial ID card, which is changed to a military ID card if the mech has the `MILITARY_MECH` monster flag. This also officially adds an actual use of the monster flag literally anywhere in the code, instead of sitting there being defined but not used.
JSON changes:
1. Removed `MILITARY_MECH` flag from lifter mechs so they'll require an industrial ID card.
Overhauling spawning locations so industrial mechs can spawn in more locations that fit. I already plan to audit some spawns in the future when I rebalance military locations, and …
=> feat(balance): MILITARY_MECH flag affects ID card needed, fix duplicate message

src/character.cpp, src/rot.cpp
Fixes #3634. Also removes a bad debugmsg.
Don't consume the liquid in the case it can't find a tank for it, pass it back as expected. Also the debugmsg would trigger when the item was in a tank rather than a cargo part.
=> fix: Indefinite vehicle refill

data/json/mapgen/campground.json, data/json/mapgen_palettes/campground.json
Fix waterless toilets.
Fix vehicle placement to avoid vehicles placed on a tree, dead tree, young tree, tourist table, brazier, bush,...
#3692
Change the placement of some vehicles.
I reloaded the campground many times to make sure all the vehicles were placed correctly.
Think it's okay.
=> fix: campground mapgen

data/json/recipes/chem/fuel.json
Crafting time of biodiesel is currently just outrageous. Long base time plus stingy batch factors means a batch of 50 takes 
about 3 days to make. That doesn't make any sense since it's a chemical reaction that should have a more or less constant speed regardless of scale. Also, it's annoying.
1. Change batch time reduction to 99% at > 1. The process is obviously easily scalable, further confirmed by the fact DDA currently uses the same values.
2. Reduce base crafting time to 4 hours. This part is a bit arbitrary, but I couldn't find any hard data on why transesterification of fats has to take specifically 7 hours, no more and no less, and I suspect it was picked somewhat arbitrarily in the first place. Even if it has some basis in reality, having overly long crafting times for regularly …
=> feat(balance): adjust biodiesel recipe for more reasonable crafting time

data/json/items/tool/fire.json, data/json/recipes/electronic/tools.json
The electric firestarter recipe accidentally used regular steel wires instead of copper wire.
I changed the wire component in its recipe to cable.
No json errors.
=> fix(content): correct electric firestarter recipe

data/json/mapgen/farm.json
Bathtub with two tiles instead of one in the house.
Place NPC farmer inside the house.
Move placement of zombie group to center of barn to avoid some of them appearing outside.
Replace the grass tile with a dirt tile in the building left of the house.
I didn't see any zombies appearing outside the barn during my tests.
The NPC is correctly placed inside the house.
NPC:
=> fix: farm mapgen

data/json/items/armor/power_armor.json
When I did https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3625 one of the misc updates was making light power draw a bit less power, and heavy power armor draw a bit more power. I got that completely and entirely wrong for the helmets.
Swapped the power draw values of light and heavy power helmets.
Screaming.
Demonstrated I know how to read this time.
=> fix(bugfixes): Fix light and helmet power helms having each other's power draw

data/json/mapgen/toxic_dump.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_waste_junk.json
Add a roof to the toxic waste dump.
Replace dirt tiles under furniture.
=> fix: toxic dump mapgen

src/overmap.cpp
Better performance
Added two more placement overlays. River overlay prevents attempting of placing river specials on ground and vice versa. Underground overlay allows placing underground special(microlabs in vanilla game) within range of surface specials without conflicts.
Added locations check to land overlay to prevent expensive attempts of placing specials over existing cities.
Limited max amount of attempts to build connections. It could been *terribly* slow - i've seen minute long hangs during placing of *single* special, when it physically can't be connected anywhere, due to being on unreachable island, or fully surrounded by other buildings.
With all that generation speed of crowded maps with big cities will be magnitude faster than before. On default settings with plenty of empty …
=> perf: specials placement optimizations

data/json/items/armor/holster.json, data/json/items/armor/power_armor.json
Updates some items I overlooked back when I updated holster sizes in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3159, plus expand on one item's role.
1. Per Scarf's suggestion, increased max volume of back holster from 9 liters to 10 liters, matching that of power armor back holster.
2. Increased maximum volume of power armor holster from 800 ml to 1 liter and minimum volume from 100 ml to 250 ml, matching standard holster.
3. Altered the power armor chest rig a bit, renaming it to "power armor magazine carrier" to distinguish it from from the carry stats of the standard chest rig. Reduced its max mags down to only 2, but bumped its max volume to 1500 ml and allowed it to hold items with the `MAG_BULKY` flag. This gives it the ability to stash spare heavy batteries, like what a …
=> feat(balance): update capacity of power armor holsters

.github/workflows/autofix.yml
fix #3395
there was a [typo in input field](https://github.com/autofix-ci/action/issues/9), which prevented the bot from adding comments when it made a commit.
- [bumped up action version with fixes](https://github.com/autofix-ci/action/issues/9#issuecomment-1812521148)
- renamed field name: `commment` -> `comment`
=> ci: fix autofix bot not adding comments

src/overmap.cpp
Might fix crash due to stack overflow in debug MSVS builds.
`place_specials()` allocates heavy specials_overlay's on stack, moving them to heap should reduce strain.
(For context: https://discord.com/channels/830879262763909202/830916451517857894/1177226958036275280)
None.
I don't have MSVS to actually test it, for me it changes nothing.
=> fix: potential fix for stack overflow in debug MSVS builds

src/iexamine.cpp, src/map.cpp
Might fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3698
Working theory is that MSVC optimizes all three liquid iexamine functions intro one, as the are identical. And then when they compared - they all have *same* pointer, which breaks check in `map::water_from()`.
One of possible solutions - make those functions actually different.
It's not the nicest solution, as i ended  duplicating code between `water_from()` and iexamine, but it's *simple* solution.
Can't properly test it. That bug seems to appear only on MSVC builds, which i can't build. On my MSYS2 build it works both with, and without this fix. So, best i can say - it's that it doesn't *seems* to break it worse.
* Important note for testing: iexamine will not call water_from() anymore, which have that problematic …
=> fix: potential fix for liquid iexamine

src/character.cpp, src/skill.cpp
This finally fixes the whole "can occasionally get your skills past 10 even though everything is built around" thing. As a bonus it makes maxed-out skills marked as such on the `@` screen and prevents focus loss from pinging that skill. Was reminded to look at this by MisterWytt in the BN discord having recently discovered fungal tendrils can grind your dodge skill up to 13.
In skill.cpp, changed `SkillLevel::can_train` to also check for if the skill in question is maxed out or not, meaning skills at `MAX_SKILL` (set to 10 in game_constants.h) will cause `Character::practice` to go "oh wait we're free to return early" in response.
Changed comment in character.cpp accordingly.
Saying "fuck it" and rebalancing the game to build around the ability to just keep training your skills …
=> fix(balance): no more EXP gain when a skill is maxed out

src/mission_util.cpp, src/overmapbuffer.cpp, src/overmapbuffer.h, src/start_location.cpp
Should fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3730
Added min range argument to specials placement: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3730#issuecomment-1821450385
None.
Restarted few times as assassin with x0 specials(to make sure mission will actually need to spawn airport) as per https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3730#issuecomment-1821555011. No more errors.
Piece of code that makes a copy of special shouldn't be needed now. It used to override occurrences with 1 before placement rework, but not anymore.
=> fix: specials spawned for missions will respect min range

data/json/martialarts.json
There are multiple unarmed martial arts weapons ingame that perform a variety of damage types, but many martial arts techniques and buffs only buffed bashing damage.
All martial arts techniques and buffs that only buffed one or two of the three main melee damage types (bash, cut, stab) now buff all three.
=> fix: martial arts damage buffs apply to all damage types

data/mods/Aftershock/mobs/robots.json, doc/src/content/docs/en/mod/json/reference/creatures/monsters.md, src/damage.cpp, src/monster.cpp, src/monstergenerator.cpp, src/mtype.h
- resolves #3671 
- added `armor_cold` and `armor_electric`, by copy-pasting implementation of `armor_fire`.
- gave tankbot cold and electricity armor.
a better JSON format to group monster armor together, but it seemed like too much endeavor.
1. added magiclysm.
2. spawned tank UGV and debug monster.
3. casted lighting bolt.
4. tankbot took much less damage than debug monster, due to their 72 electric armor.
spent 30 minutes figuring out why cold resistance wasn't working, then found out i was editing tankbot in _aftershock._ fun times.
=> feat: monster armor for `cold` and `electric`

src/iuse.cpp
make mopping wide area a bit less painful.
- removed restriction on mounts because if one can play [polo](https://en.wikipedia.org/wiki/Polo), one can mop.
- removed tile validity check in `iuse::mop` as it was checked again in `map::mop_spills` anyways.
- counts mopped tiles and uses time accordingly multiplied. it doesn't for charges because that seemed overly wasteful.
- zone for mopping? ~~that'd be too much work~~
- it's a bad news for some who like to draw zombie blood art using carefully coordinated application of mops
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/28538e0b-57e9-4b46-a6d5-01ef1d74d94e
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/a18f9e6a-5a2e-46cc-a3f2-16efcad15e8c
[original discussion on …
=> feat: mop 3x3 area around

src/ranged.cpp
- resolves #3644
used `closest_points_first` to check for mountable terrain in 3x3 radius.
taking direction into account, but this seemed simpler.
https://discord.com/channels/830879262763909202/830916329053487124/1173138811555946527
=> feat: allow using `MOUNTABLE` terrains nearby when firing heavy weapon

src/creature.cpp
- fixes #2702
- extracted stun strength calculation logic.
- made environmental resist apply to `stun`, `blind`, `sap`, `paralysis`, so power armor doesn't get pwned by riot control platform
centralize all damage mechanism and screm
1. spawn riot control platform
2. turn on debug invincibility and confirm it get stunned. (maybe should add a `Debug Effect Repellant` mutation?)
3. spawn and wear heavy power armor (env. protection: 16)
4. turn off debug invincibility and confirm no stun is applied.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/280ff91c-1fac-4396-8037-58e92bddaada
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/6093efb5-7d50-4d24-890c-0736ba893bd3
=> fix: use env. resist for `stun`, `blind`, `sap`, `paralysis`

data/json/items/tool/tailoring.json, doc/src/content/docs/en/mod/json/reference/json_info.md, src/iuse_actor.cpp
It was pointed out in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3720 that you need literally superhuman tailoring skill to be able to reinforce uncraftable items (if they have no `repairs_like` defined), specifically level 16.
C++ changes:
1. In iuse_actor.cpp, changed how `repair_item_actor::repair_chance` determines `action_difficulty` when reinforcing, from favoring `recipe_difficulty` to instead being 50% harder than the value used for refitting, which in turn is set to the difficulty of repairing a max-damage item. Since max damage would return a value of 4, this makes the `action_difficulty` always 6, instead of being anywhere from 4 to 10 depending on how easy it is to craft (when `recipe_difficulty` is already used later on so how easy it is to craft doesn't need to be …
=> fix(balance): repair chance rebalancing

data/json/monsters/fungus.json
`It is hard to recognize a human child in this creature.`
It was brought up a little while ago that fungal children trigger wacky amounts of guilt due to technically not counting as zombies, which is what normally brings the massive penalty for guilt down to a mere annoyance.
Removed `GUILT` flag from fungal children, on the basis that more monstrous zombie child evos explicitly lack the `GUILT` flag due to no longer reminding the PC of children, which the monster description implies.
1. Adding `ZOMBIE` to the species lists for all fungal zeds. This would fix it and make them consistent, with the only visible side effect being fungal zeds will count as friendly towards a feral survivor in the Lost and Damned scenario. I'd want to test to make sure that doesn't cause anything stupid like …
=> fix(balance): remove GULIT flag from fungal children

data/json/professions.json, data/json/scenarios.json
Adds an idea I'd been tinkering with for a bit. Best reserved for after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3758 is merged since it'll affect the balancing of this profession.
Added power armor solder profession. Starts with light power armor and supplementary gear to fill the niches military recruits get (storage, knife, two-way radio, helmet will provide the ear-pro so no earplugs). Starting skills takes the basics of military recruit but swaps the dodging for mechanics skill.
Equipment includes an M240, UPS (implying that rollout of advanced UPS wasn't 100% complete by the time of the cataclysm, because advanced UPS' balance is in a weird state due to https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3765 but will be both more powerful yet harder to keep running …
=> feat(content): power armored profession

src/diary.cpp, src/diary.h, src/overmap_ui.cpp, src/overmap_ui.h
SUMMARY: Interface "Add map position to each diary page"
One information I felt was missing from the diary is the location where the player wrote a page.
It can be especially useful for players who travel a lot
Add the information
- new character with existing diary pages. They just don't display the map position line
- new page, the position is added and it's the right one
- teleport, new page, the position is added and it's the right one
- save and reload, the pages still have the correct positions
I'm displaying the player's map position as "Location: (z, x, y)".
I couldn't give more informations without it overflowing on phone.
I think a player will quickly understand since it's the same as on the map and the first digit will always be close to 0
=> feat(UI): Add map position to each diary page

data/json/items/armor/ammo_pouch.json, data/json/items/armor/bandolier.json, data/json/items/magazine/8x40mm.json, data/json/items/magazine/chemical_spray.json, data/json/items/magazine/liquid.json, data/json/items/magazine/weldgas.json, data/json/items/tool/explosives.json
Some misc things that came to mind while looking at items and pondering ideas.
1. Added `MAG_BULKY` to the 250-round and 500-round 8x40 magazines. Nothing in vanilla can hold the 500-rounder currently, but this enables mods that might add more options to support them, along with consistency since all other 8x40mm mags have storage flags.
2. Added `MAG_BULKY` to fuel tanks for welding gas, chemicals, flamethrower fuel, etc lacking the flag already. Consistent with other hardware with military uses, namely batteries, getting storage flags and some flamethrower tanks already being storable.
3. Expanded the size range of the generic crappy ammo satchel, allowing it to hold any magazine or speedloader from 250 ml up to 2 liters. Reasoning being it's a waist-slot item that only holds a single …
=> feat(balance): ammo pouch storage adjustments

data/json/bionics.json, data/json/items/bionics.json
#2694 made the Joint Servo CBM all-positive with no tradeoffs, but the item description doesn't reflect that.
Updated the description for the Joint Servo CBM's item form to make clear that it provides a lesser bonus instead of a malus when turned off. Also while at it, slightly changed the installed form's description to expand on the idea (which is that the system enforces correct running technique, so it's beneficial even when not directly providing extra power).
Staying away from a useful upgrade due to misleading description.
Made sure JSON syntax is not affected by the change. Made sure the game loads and the description changes are present.
=> fix(content): update Joint Servo CBM descriptions

data/json/professions.json, data/mods/Fuji_Mil_Prof/prof/army.json, data/mods/Fuji_Mil_Prof/scenarios.json
Some assorted adjustments to professions for modernization and consistency. Also sets things up so in the future I can start adding some more military professions too.
1. Set it so that electrician spawns with a voltmeter, soldering iron in their toolbelt, those being the basic tools needed to expand a grid connection. Reworded the profession description to not be something that only makes sense in the evacuee scenario.
2. Stashed the home mechanic's screwdriver in their toolbelt. Updated description of home mechanic to not insist you don't have a driver's license. Profession doesn't start with driving skill, but the player can obviously start with points in the skill anyway, making it a weird detail to emphasis.
3. Renamed the military recruit to military rifleman, to reflavor as the …
=> feat(balance): assorted profession updates

data/json/items/comestibles/dairy.json
Saw this: [Cataclysm-DDA/pull/69526](https://github.com/CleverRaven/Cataclysm-DDA/pull/69526)
So :
Evaporated milk quench to 10.
Change 25 to 10.
=> fix(balance,port): evaporated milk quench

data/json/monsters/slimes.json
As pointed out by a member in the Discord, slimesprings don't currently avoid traps. Fixing this seems like a no-brainer to me, since I doubt it's intended for the cute lil guys to be walking into traps like that.
Adds `"PATH_AVOID_DANGER_1"` to the slimespring. This *should* fix the issue, assuming this flag does what I assume it does.
None
Admittedly, none. However, I hope this is a simple enough fix that, in the words of a certain man, "It just works."
Another user suggested [changing the aggression of the slimesprings](https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/3794) so that they aren't so hostile towards non-hostile monsters, but I have no clue what the correct aggression value for that would be.
=> feat(balance): Make slimesprings avoid traps

data/json/achievements.json
- fixes #739
use fixed day duration for description instead.
make achievement parser to take variable seasons into account, which would be highly painful.
loaded without errors.
fixing old abandoned bugs
=> fix: use fixed duration in survival achievement description

data/json/mutations/mutations.json, src/character.cpp
sometimes it's useful to have infinite stamina to test stuff (e.g testing marathon achievement).
added `Debug Infinite Stamina` trait, which lets you... have infinite stamina.
works by hooking into `Character::get_stamina` and returning max stamina
might affect performance negatively.
ran some few hundred tiles. stamina was full.
=> feat: debug infinite stamina

data/json/mapgen/house/house_fence04.json
Fix cat hoarder variant because concrete floor under cats, windows instead of trees.
JSON changes.
Before:
After:
=> fix: `house_fence04` mapgen

src/vehicle.cpp
- fix #3583
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/2703a29ff42c6961cc57193c26dca6229804dde7/src/vehicle.cpp#L4054-L4056
make it only double noises if it's actually airborne.
making the rotor toggleable, but i think this effectively achieves the same.
cc @Krwak
=> fix: only increase noise when vehicle is airborne

data/json/vehicleparts/wheel.json, data/json/vehicles/military.json, src/grab.cpp
Some things to balance out pushing around of vehicles on dirt, which have been a bit fucky every since I started messing with craterization but also had some other underlying issues. In particular, I aimed to balance things so that a more reasonable selection of vehicles can be pushed off-road if you have above-average strength, and make it possible for a weaker character to get a logical way around it...
C++ changes:
1. In grab.cpp, changed `game::grabbed_veh_move` so the strength function calls `character_funcs::get_lift_strength_with_helpers`. This not only automatically includes the check for ahauler mech's strength (allowing me to remove it here), but more importantly allows companion NPCs to participate in hauling vehicles.
2. Included character_functions.h in grab.cpp.
JSON …
=> feat(balance): NPCs can now help push vehicles, adjustments to wooden cart wheels

src/character.cpp, src/consumption.cpp, src/player_hardcoded_effects.cpp, tests/stomach_contents_test.cpp
SUMMARY: Bugfixes "Fix impossible hibernation"
Fixes #2010
1) Hibernation could only be triggered with an obscure system taking into account the possible calories you could burn in a day. Even if it could be triggered, the mechanic wasn't clear enough for the average player
- now you can hibernate when you're above 90% of maximum stored calories, it's just as simple as that
- it was also impossible to hibernate since your character would wake up after your fatigue level reached 0. I added an extra condition to ignore the fatigue level
- also, the rate of hunger was divided by 7 when hibernating, but it did close to nothing. I even tried to reduce it by 100000, this didn't change a thing. So I used a system to compensate the lost calories, taking into account the metabolic rate of the …
=> fix: impossible hibernation

data/json/bionics.json, data/json/items/bionics.json, src/bionics.cpp, src/character.cpp, src/regen.cpp, src/regen.h
- fixes #3786 
1. removed mentions of repair nanobots requiring splints (so its behavior matches with #3054)
2. extracted `is_broken` logic into `has_broken_limb_penalty`. hidden ATM to encourage encap?sulation in future
3. extracted `broken_heal` logic into `heal_adjusted`. it takes account of whether limb gets penalty from being broken and not splinted.
4. made repair nanobot logic use `heal_adjusted`.
- making `heal_adjusted` the default behavior of `character::heal`
in both cases player waited ~6 hours with arms broken and repair nanobots active.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/a930e87e-d247-4581-9d1b-08602a442e11
it heals slowly.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/8803bcc4-0aea-4606-a726-fca440bffa0b
it heals quickly.
- …
=> fix: repair nanobots not working at all on broken limbs

.github/workflows/autofix.yml, data/mods/saveload_lua_test/main.lua, data/mods/saveload_lua_test/preload.lua, data/mods/smart_house_remotes/main.lua, data/mods/smart_house_remotes/preload.lua, data/mods/teleportation_mod/main.lua, data/mods/teleportation_mod/preload.lua, data/raw/generate_docs.lua, data/raw/on_game_start.lua, deno.jsonc, deno.lock, doc/src/content/docs/en/contribute/contributing.md, doc/src/content/docs/en/mod/json/explanation/json_style.md, doc/src/content/docs/en/mod/lua/explanation/lua_style.md, dprint.json, tests/catalua_test.cpp, tests/lua/called_cpp_func_throws.lua, tests/lua/called_error_on_cpp_side.lua, tests/lua/called_error_on_lua_side.lua, tests/lua/called_from_cpp_test.lua, tests/lua/class_members_test.lua, tests/lua/global_functions_test.lua, tests/lua/id_conversions.lua, tests/lua/id_conversions_no_int_id.lua, tests/lua/regression_sol_1444.lua, tests/lua/runtime_error.lua
Using formatter improves readability and diff output.
use https://github.com/RubixDev/dprint-plugin-stylua to format Lua files.
- compatibility: being written in WASM, plugins are cross-platform and works on browser.
- low friction: deno uses `dprint` internally, so it's easy to migrate in the future.
- unification: in the future, we'd be able to format JSON, markdown, typescript, Lua, C++ files with
- `dprint` VSCode extension
- `deno task dprint fmt`
migrate formatting ecosystem to use `dprint` with its configuration set to match with `deno`.
followup task for #3165
=> style: format Lua files

src/profession.cpp
- fix #3813
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3814#issuecomment-1842917642
=> fix: starting item sorting differently on mac

src/ranged.cpp
continuation of #3751, it was not possible to use sandbags to stabilize guns, which was counterintuitive compared to real life.
- only check whether it's passable on vehicle parts.
- check climb difficulty on terrain/furniture instead
make climb check functions sane and not spread throughout source code with slightly different usage and return value
=> fix: allow mounting gun on climbables

src/wish.cpp
it's inconvenient that debug spawned clothings are always `(poor fit)`. together we can stop this.
terrible spaghetti duplicate code to set `FIT` flag if it's `VARSIZE`
overhaul items to be immutable and configurable
they all fit nicely.
quick PR while working on #3814
=> fix: make debug spawned clothings fit to body

data/json/overmap/overmap_mutable/lab.json, doc/src/content/docs/en/mod/json/reference/map/overmap.md, src/cube_direction.h, src/om_direction.h, src/overmap.cpp, src/overmap.h, src/overmap_special.h
Properly separate fixed and mutable data, and match mutable connections format with DDA.
Based on following PRs:
* https://github.com/CleverRaven/Cataclysm-DDA/pull/52234
* https://github.com/CleverRaven/Cataclysm-DDA/pull/59822
They got bunch of changes here and there, as BN expanded some of related coded, but overall this PR serve same purpose, and reduces distance between codebases for easier maintaining.
JSON format of mutable connections changed to what currently used in DDA. Implementation is a bit different as i didn't wanted to duplicate code, but now we're using same notation, which was the goal.
Changed connections comes with tiny regress. Old format was allowing to declare "disconnected connections", i.e. connections without `from` property. If that feature will be demanded it …
=> refactor(port): tidy specials data and mutable connections

data/raw/keybindings/keybindings.json, doc/src/content/docs/en/index.mdx, src/action.cpp, src/action.h, src/game.cpp, src/handle_action.cpp
- resolves #3844
added shortcut `w` to open [documentation page](https://docs.cataclysmbn.org/) (you could call it wiki).
- move its position to bottom?
- use other shortcuts?
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/0ad62648-d89b-4be4-9fab-db42e2431a5a
- footage taken before changing shortcut from `-` to `w`
- wiki redirects path without locale by country, thus korean UI
=> feat: open wiki in menu

data/json/recipes/weapon/explosive.json
The existing smoke bomb recipe is weird. I'm no chemist and can't say with certainty if it would or wouldn't work, but at the very least it's oddly specific and needlessly requires items player may be short on or have better use for. Meanwhile, a commonly known and definitely realistic recipe for a homemade smoke bomb exists but isn't available in the game.
Replaced components for the existing recipe with roughly 3 parts fuel (sugar) and 2 parts oxidizer (saltpeter or oxidizer powder), by volume. The recipe you can find online calls for saltpeter specifically but I added oxidizer powder as an alternative because it fits by description and is reasonably easy to make, while saltpeter can be less accessible. A smoke bomb is a situationally useful item, hardly an OP consumable, so it makes no …
=> feat(balance): replace smoke bomb recipe with a more realistic version

data/json/furniture_and_terrain/furniture-barriers.json, data/json/furniture_and_terrain/furniture-domestic_plants.json, data/json/furniture_and_terrain/furniture-signs.json, data/json/furniture_and_terrain/furniture-storage.json, data/json/furniture_and_terrain/terrain-bridges-docks.json, data/json/furniture_and_terrain/terrain-doors.json, data/json/furniture_and_terrain/terrain-fences-gates.json, data/json/furniture_and_terrain/terrain-manufactured.json, data/json/furniture_and_terrain/terrain-railroads.json, data/json/furniture_and_terrain/terrain-windows.json
Belated follow-up to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3649 now covering terrain, with the same goal of "you get back out of something what you put into it" as much as is practical.
Set consistent deconstruct yields for the following constructables:
<details>
<summary>List:</summary>
* Closed wood door (this one actually gave more planks than it needed to make, on top of the usual issue of not giving back all its nails)
* closed wood door with peephole
* other related doors
* reinforced wooden doors
* window with curtains (interestingly, the hardcoded examine action for tearing down curtains in general was already set to give a consistent number of nails, so only deconstruct was randomized)
* small railroad track (dafuq, the yields for bash vs deconstruct had clearly …
=> feat(balance): consistent deconstruct yields, part 2

src/catalua.cpp, src/debug.cpp, src/debug_menu.cpp, src/descriptions.cpp, src/dump.cpp, src/filesystem.cpp, src/handle_action.cpp, src/init.cpp, src/main.cpp, src/savegame.cpp, src/veh_interact.cpp, src/weather_gen.cpp, tests/explosion_balance_test.cpp, tests/invlet_test.cpp, tests/line_test.cpp, tests/melee_test.cpp, tests/overmap_noise_test.cpp, tests/ranged_balance_test.cpp, tools/format/format.cpp
https://clang.llvm.org/extra/clang-tidy/checks/performance/avoid-endl.html
found and replaced usages of `std::endl` to `\n`. this clang-tidy warning 
also apply the fix to catch2.hpp but that'd cause huge rebuild.
this check is added in clang-tools 18.0.0
=> perf: `performance-avoid-endl`

data/json/mapgen/church.json, data/json/mapgen_palettes/church.json
Fix waterless toilet.
Use "t_region_groundcover_urban" for outdoor flooring.
Add downspouts.
JSON changes.
None.
Before:
After:
=> fix: church mapgen

data/json/mapgen/radio_tower.json
Fix because can't climb on roof and wrong type of terrain under "&".
JSON changes.
Before:
After:
=> fix: radio_tower_1 roof

data/json/mapgen/house/house_fence07.json
Place concrete floor instead of waxed floor under the planters, because waxed floor creates flying roofs on the level above.
JSON changes.
None.
Before:
After:
=> fix: remove house_fence07 flying roofs

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/android.yml, .github/workflows/clang-tidy.yml, .github/workflows/documentation.yml, .github/workflows/matrix.yml, .github/workflows/msvc-full-features-cmake.yml, .github/workflows/msvc-full-features.yml, .github/workflows/msys2-cmake.yml, .github/workflows/msys2.yml, .github/workflows/pull-translations.yml, data/raw/generate_docs.lua, doc/astro.config.ts, doc/src/content/docs/en/contribute/contributing.md, doc/src/content/docs/en/dev/guides/building/makefile.md, doc/src/content/docs/en/dev/guides/working_with_both_bn_and_dda_in_git.md, doc/src/content/docs/en/dev/reference/tooling.md, doc/src/content/docs/en/mod/json/guides/map/mapgen.md, doc/src/content/docs/en/mod/json/reference/items/json_inheritance.md, doc/src/content/docs/en/mod/json/reference/json_info.md, doc/src/content/docs/en/mod/lua/reference/lua.md, doc/src/content/docs/ko/contribute/contributing.md
- resolves #673
renamed all references of `upload` to `main`.
none.
old links should work.
https://github.com/github/renaming
=> chore: rename `upload` branch to `main`

src/mapgen_functions.cpp
To get rid of all those `// NOLINTNEXTLINE`. There's no functional changes it's just a tidying.
Used point arithmetic. And also slightly refactored neighbor terrain check, so it won't need to check same thing multiple times - should be a couple nanoseconds faster.
None.
Shores still works.
I could get rid of all those `const bool ...`, but it makes slots assignment below much less readable.
=> refactor: apply `cata-use-point-arithmetic` to shore mapgen

data/json/recipes/electronic/parts.json, data/json/recipes/other/tools.json
Of the items needed to make an RV kitchen unit, one of them can potentially be softlocked due to being the only one to insist on using cast-iron frying pans only, and not the steel frying pans you can craft.
1. Changed the recipe for RV kitchen units to allow steel and frying pans as well as cast-iron frying pans. Same cooking-related crafting qualities provided, only difference was cast-iron provides the holy power of level 1 hammering quality, as any rock or chunk of steel does.
2. Also set it to permit the use of cast-iron pots, thus making it consistent in terms of what pots and pans it allows.
3. Added a recipe for making copper frying pans in the vein of copper pots being craftable, with materials scaled down consistent with how steel pans are relative to standard pots. Figured I …
=> fix: allow other pots and pans for kitchen unit recipe, related fixes

data/json/furniture_and_terrain/furniture-storage.json, data/json/furniture_and_terrain/terrain-doors.json, data/json/furniture_and_terrain/terrain-liquids.json
Fixes some issues with terrain ported over for the underwater research station.
1. Fixed bulkhead floors and related terrain counting as slow terrain, by giving it the same flags as metal floors.
2. Fixed open bulkhead doors still blocking vision, replacing its flags with that of open metal doors.
3. Removed the exodii crates, those aren't used in the research station and we aren't planning to port over aliens who invented bionics.
4. Also removed the unused wooden chests. We can always re-add them later for buried treasure or something like that when we actually want to use them.
5. Made it possible to walk onto foot lockers at a move cost penalty instead of blocking movement outright.
6. Also edited description of bulkhead floors to make it clear how it's being used currently.
7. Fixed …
=> fix: freshwater research terrain fixes

data/json/vehicles/helicopters.json
1. intact apache helicopters can be found in aircraft carrier(#3892)
2. they are hard to use because they lack wheels
added wheels to apache helicopter so it can be drived.
- adding wheels to other helicopters, but there's rather a large amount of them
=> feat(content): wheels for apache helicopter

src/game.cpp, src/map.h, src/options.cpp, tests/ground_destroy_test.cpp, tests/monster_vision_test.cpp, tests/test_main.cpp
- fixes #3906
- fixes #3907
remove mentions of `get_option<bool>( "ZLEVELS" )`. also referenced https://github.com/CleverRaven/Cataclysm-DDA/pull/41707
keeping the system as-is, however not having one causes issues like #3096 and complicates z-level features like elevated bridges.
was able to load, z-levels were present.
this change was approved by players via poll in #3533.
=> feat: remove option to not use z-levels

src/character_functions.cpp
- fix #3898 
make `fine_detail_vision_mod` which is used to check everything related to vision.
screm
1. spawned architect's cube.
2. light level went bright.
3. was able to read books.
4. was able to install vehicle parts.
=> fix: `debug_clairvoyance` not working on reading and vehicle modification

src/game.cpp
make it easier to debug position related bugs (e.g #3892)
display mouse cursor point on e`x`amine
the location and display format could change.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/8c6a3001-a3f3-47a3-976e-7eb2f6851519
=> feat(UI): display mouse cursor position on examine

src/vehicle_move.cpp
* fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3903
Check whether vehicle is rotorcraft before falling, if so - start flying instead.
Rewriting all flying code, it's a mess with hardcode checks for specific z levels, and tons of bugs. But for now this will work as a quick fix, it's not the best idea to jump into rewriting flying while we're in middle of obsoleting legacy zlevels.
Flied off deck on wheeled apache from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3901
=> fix: controlled rotorcrafts shouldn't fall when loosing ground

src/veh_interact.cpp
Shard pointed out that the multi-engine skill requirement was one of the main reasons to have the soft cap of 10 not properly enforce itself. Well I looked into it and while engine install requirements are already capped at 10, axle requirements are still uncapped.
In veh_interact.cpp, changed `veh_interact::update_part_requirements` so that `dif_steering` gets hit with the `std::min` stick just as `dif_eng` does directly above it, capping it at a maximum skill requirement of 10. Current form is a bit messier than intended, just running `axles.size() + 5` produced errors about loss of precision.
Figuring out some janky math to make it so that difficulties above 10 are internally calculated, artifically lowered to 10, and then rig it to tell you "no, stop that, you can't install any more …
=> feat(balance): cap axle install penalty at 10, like engine penalty

data/json/items/armor/jewelry.json
Regular non-jeweled cufflinks and intricate cufflinks are missing their rightful fancy flag. 0/10, literally unplayable.
- Made regular cufflinks `FANCY`. Duh
- Made intricate cufflinks `SUPER_FANCY`. There's precious few "very fancy" items that stylish characters can wear for that sweet sweet morale boost that don't also make you look like a deranged psycho given the circumstances. Let's provide at least one more sane alternative to killing zombies in a wedding dress.
Killing zombies in a wedding dress. While also wearing a top hat and a monocle. Because that's what you call "stylish".
Made sure the JSON changes are reflected in the game.
=> fix: cufflinks are fancy!

.github/workflows/matrix.yml
- fix #3560 
- add `always-test` flag 
- fix incorrect boolean logic that made matrix marked as 'always run on draft' _skip_ draft PRs
- simplified environment variables
currently there's not much point in separating build step and test step because we don't cache executable and test binary.
1. also release tests binary daily (probably on separate repo?)
2. create separate workflow for C++ changes and JSON changes
3. make JSON workflow download [recent binary from releases](https://github.com/marketplace/actions/release-downloader) and use the binary for quick testing
should build on CI
at least one CI will run tests regardless of state.
=> ci: prevent JSON PRs skipping tests

src/item_contents.cpp
Fixes #3763 and generally makes item contents stack when appropriate. 
Tries to merge things before adding it.
I think this was present in 0.4 as well.
=> fix: Stack cbc item contents

src/computer_session.cpp
- fix #3852
`temporary` -> `temporarily`
=> fix(i18n): typo in computer session

src/animation.cpp
- fix #3908
return early in `test_mode` to prevent referencing null tilecontext.
decouple core logic from UI.
local tests pass without segfaults.
un-optimizing individual functions with [`[[clang::optnone]]`](https://clang.llvm.org/docs/AttributeReference.html#optnone) helped a lot.
=> test: crash in `projectile_test` caused by null tilecontext

src/crafting.cpp
Implements the suggestion in https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/3825
In crafting.cpp, set it so that `player::craft_skill_gain` also calls `practice` for any secondary skills in the recipe, at half the EXP rate as the primary skill. Also makes sure to exclude cases where, for some derp reason, the primary skill is also a subskill so that doing so won't make it gain 50% more EXP.
Trying to figure out the least clunky way to also let NPCs benefit from this.
2. Started crafting a heavy rail rifle via debug hammerspace and unlocking all skills.
3. Stopped it after a few seconds, observed that all the skills involved gained EXP, with primary skill of fabrication being ahead as expected.
4. Temporarily added a message that triggers when a …
=> feat: secondary crafting skills gain EXP too

src/debug.cpp, src/magic_enchantment.cpp, src/make_static.h, src/mapgen.cpp, src/vehicle.cpp
resolve https://clang.llvm.org/extra/clang-tidy/checks/modernize/type-traits.html warnings
use `_v` variants
None.
=> fix: apply clang-tidy `modernize-type-traits`

.github/workflows/matrix.yml
- fixes #3560 (again)
`true != 'true'` always evaluates to `true`. this causes tests to always skip.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/ce5c66744d1eea231629c43554ffd2e26d356520/.github/workflows/matrix.yml#L146-L148
matrix was comparing [`true` (boolean)](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7237118999/job/19717827424#step:1:154) to [`'true'` (string)](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7237118999/job/19717827424#step:1:156), always resulting in `true`.
- separate matrix into jobs per os for easier management
- host a server solely dedicated to run JSON tests built daily
- screm
should work (really)
while a bit verbose, https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging …
=> ci: fix always run flag not working

data/json/items/gun/9mm.json, tests/item_tname_test.cpp
It came to my attention that the model designation MP5A2 used in the game cannot be correct, since the A2 modification does not feature 3-round burst firing mode.
Rename the gun to MP5A4, which is the same thing but with 4-position trigger group.
Clobbering myself over the noggin until I forget this little bit of gun trivia so the discrepancy stops bugging me.
Made sure the new name is reflected in the game.
=> fix: correct the model name for MP5 SMG

data/json/mutations/mutations.json, src/suffer.cpp
makes swimming in debug mode less annoying.
skips oxygen check while `Debug Infinite Stamina` is enabled.
screm
swam a few kilometers in #3938, no drowning warning was made.
=> feat: infinite swimming with infinite stamina

data/json/scenarios.json
Some tweaks to the scenario recently ported from DDA.
1. Cleaned up the grammar a bit for the CVN scenario's description a bit. In particular drops the "unknown location" bit, since it seemed a bit clunky (plus opens us up to the question of whether to script "bewildered soldier learns from an NPC they're back home" into dialogue).
2. Added all the military professions allowed in Overrun to the profession list (i.e. all `PROF_MILITARY` professions except National Guard and Military Holdout, as one's for a profession caught still in their PT uniform while the other's a post-apoc profession).
1. Adding the civilian professions from CVN scenario to Overrun or vice-versa to make them have the same profession allowances.
2. Merging CVN scenario into Overrun as a generic "trapped in a military …
=> feat(balance): add military professions to CVN scenario, description tweak

src/iuse.cpp
- Fixes #3946
It seems the code responsible for assigning source reference to blood got lost somehow, so all samples that are not acid would always turn out to be clean "human blood" instead of "%monster_name% blood". This leads to the Refugee Center quest "Analyze Zombie Blood" being impossible to complete.
- Modify `iuse::blood_draw` to store source body `mtype` and assign it to produced sample.
- Additionally, when using blood draw kit on a tile with multiple bodies, break the loop and prevent subsequent prompts after picking a corpse to draw from.
Hoping someone else fixes this eventually.
Spawned and killed a bunch of zombies, including an acidic one, a monster, a feral human, and an NPC.
Tried using blood draw kit on each corpse, on myself, on none, with bodies piled up and …
=> fix: blood sample origin being lost

data/json/furniture_and_terrain/terrain-liquids.json, data/json/items/comestibles/seed.json, doc/src/content/docs/en/mod/json/reference/json_info.md, src/activity_handlers.cpp, src/activity_item_handling.cpp, src/iexamine.cpp, src/item_factory.cpp, src/itype.h
Ports https://github.com/CleverRaven/Cataclysm-DDA/pull/68664 which will set cattails as growing in shallow water and It also makes it so that different plants can have different terrain requirements for farming.
To quote the original PR: 
"seed_data" has a new optional field, "required_terrain_flag". This is set to "PLANTABLE" by default. In order to plant a seed somewhere, the terrain or furniture there needs to have the given flag.
If this flag is set to anything other than "PLANTABLE", the terrain will not turn into dirt after the seed is planted. This is to prevent the water to turn into dirt when you plant stuff in it.
Places that previously checked for the "PLANTABLE" tag now instead checks for the tag specified by the "seed_data".
Cattail seeds are set to have …
=> feat(content,port): JSONize terrain flag requirement for plants.

data/json/items/tool/traps.json, data/json/obsoletion/uncategorized.json, data/json/recipes/other/traps.json, data/json/traps.json, src/trap.cpp, src/trap.h, src/trapfunc.cpp
The continues the work started with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3939 to improve trap-related code and add some more eventually. WIP for now.
C++ changes:
1. In trap.cpp and trap.h, defined support for `trigger_items` JSON in `trap::load`. Uses the same format as `drops`, instead being items that spawn when the trap is triggered (as opposed to disarmed like `drops`).
2. Also in trap.cpp and trap.h, defined function `trap::trigger_aftermath`. This is used to provide final cleanup for traps, in particular dropping any items on trigger defined in the trap JSON's `trigger_items` section.
3. In trapfunc.cpp, converted all trap functions that return `true` to use `trigger_aftermath` in them, and removed most hardcoded instances of spawning items or calling `remove_trap` …
=> feat: JSONize some trap features

src/bionics.cpp
- fix #3914
made the sentence generic enough
actually taking acoount of map and vehicle roof, but api for that isn't straightforward
should work since it's only string changes
=> fix: make autodoc message generic

src/json.cpp, src/json.h, src/mapgen.cpp
- closes #3927
port non-lethal errors commit of https://github.com/CleverRaven/Cataclysm-DDA/pull/46337 by @Qrox 
- also migrate to typescript, but dependencies order resolution was a bit more involved and existing script works.
- also fix related JSON errors, but the amount of reported errors are massive
should work in CI.
=> test(port): non-lethal JSON errors for missing mapgen key

src/iuse_actor.cpp
- fix #3547
use `add_item_or_charges` in the loop
make everything stackable so we don't suffer
local tests pass
ripped off from #3489 because after month i wasn't able to figure out the reason of drastic changes in vehicle distance test
=> fix: account for charges on salvage

data/json/items/gunmod/grip.json
Fixes oversight missed in original weapon category commit in #2541 . Manually checkd rest of the entries, only gunmod that got missed for shotguns.
=> fix(content): Update ergonomic grips to work for shotguns

data/json/items/comestibles/med.json, data/json/items/generic.json, data/json/items/generic/string.json, data/json/items/resources/misc.json, data/json/items/resources/plastic.json, data/json/items/resources/wood.json, data/json/items/tool/toiletries.json, scripts/to_stackable.ts, src/activity_item_handling.cpp, src/item.cpp, src/iuse_actor.cpp
- resolve #3487
1. wrote a script to migrate items to ~~AMMO~~ stackable
2. converted items i could think of
3. ~~rags are heavily buffed, weighs only 10g/20ml~~ (should be a separate balance PR)
4. `TOOL`s are now `GENERIC` 
5. parts that were also used as vehicle parts had to be removed as they where the culprit for breaking vehicle tests. i suspect vehicle drag and efficiency calculate does not take account of count-by-charges
make everything stackable?
haven't tested disassembly and crafting, so weird stuff might happen.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/8fd48737-2589-44d2-9e68-b1c922dfb08e
interestingly, `use_action` works as before.
context: https://discord.com/channels/830879262763909202/830916329053487124/1166006575664738307
=> perf: make more items stackable

src/game.cpp, src/item.cpp
This implements yet more adjustments and improvements related to harvesting bionics.
1. In game.cpp, set `add_corpses` so that the butchery menu's list of monster corpses visually marks corpses that have CBMs detected in them, showing them with the same `(bionic detected)` text on the end like their item form does. This makes it easier to remember which ones out of a pile of bodies have had a CBM detected.
2. In item.cpp, changed `item::tname` so that scanned corpses gain a either `(scanned)` or `(bionic detected)` depending on if they have a bionic in then. This helps the player actually tell that the scanner is working by marking corpses that've been scanned but have no CBMs in them.
Screaming.
2. Spawned in and debug-killed a bunch of shocker zombies.
3. …
=> fix(UI): more improvements to visibility of bionic scanning

data/json/mapgen/ws_fire_lookout_tower.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_military.json
Add two more levels to the tower to make it a more interesting observation point.
Increase its height by 2 levels.
Do nothing.
"ws_fire_lookout_tower_f1":
"ws_fire_lookout_tower_f2":
=> feat(content): make fire lookout tower higher

.github/workflows/release.yml
- resolves #3895
- tag format: `cbn-experimental-YYYY-MM-DD-HHmm` -> `YYYY-MM-DD`
- release format: `Cataclysm-BN experimental build YYYY-MM-DD-HHmm` -> `Experimental YYYY-MM-DD`
tag name aligns with date range of commits. for example, release with commits from `2023-12-26T00:00:00Z/2023-12-26T23:59:59Z` will be named
- before: `cbn-experimental-2023-12-27-0036` (36 seconds is due to CI delay)
- after: `2023-12-26`
- keeping it as-is, but this has disadvantages of not being able to locate daily release without using github API, such as: `https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/2023-12-17`
- alternative tag prefix? `v2023-12-17`, `cbn-2023-12-17`
- use yesterday as release name? currently release `2023-12-18` contains commits from `2023-12-17`. …
=> ci: simplify tag and release name

src/iuse_actor.cpp
This adds a bit of sanity-checking for a problem found out while testing the implementation of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3967
In iuse_actor.cpp, updated `sew_advanced_actor::use` so that the if/else statements that check whether you can proceed with installing or removing a `clothing_mod` also check whether the mod would result in the item becoming unwearable, and if so preventing you from doing so if you're also currently wearing the offending item.
Also had to move the definition of `t_lower` a bit so that the destroy part of the if/else block can also use it.
Adding support for resizing for smol characters too. I think I'd want to wait on that one and add it along with some more properties and fixes, like support for making a gunmod not need materials to …
=> fix: don't un-XL clothes you're wearing if you're Huge

data/json/itemgroups/Clothing_Gear/clothing.json, data/json/itemgroups/Locations_MapExtras/locations_commercial.json, data/json/itemgroups/Locations_MapExtras/locations_mapextras.json, data/json/items/armor/holster.json, data/json/monsterdrops/zombie_cop.json, data/json/recipes/armor/storage.json
Adds the ability to create and find shoulder holsters like a cool 90s cop and/or super spy.
You can make a holster that sits under your arm. Copied mostly from the existing holster item with some caveats:
- I tried to make it so that we make use of existing items in the game - you can craft a shoulder holster from a normal holster, some standard sewing filament (10), and a shoulder strap. 
- Volume, weight and cost are all increased to account for the inclusion of the shoulder strap.
- Moved to the strapped layer instead of waist, compact and oversize are preserved so mutants can make these and it doesn't interfere with other strapped arm armor.
- Added to the accessory_weaponcarry so every zombie has a chance to have this (less chances than a normal holster), also added to the pawnshop …
=> feat(content): shoulder holsters

data/json/regional_map_settings.json
Replace "s_jewelry" with "s_jewelry_shop".
JSON changes.
none
1. Go into town.
2. The jewelry store and its roof appear without problem.
=> fix: id used for jewelry in regional_map_settings

.github/workflows/autofix.yml
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/7340681630/job/19987088515?pr=3992#step:10:282
prevent network failure halting the whole CI pipeline
use [actions/cache](https://github.com/actions/cache) to [cache deno dependencies](https://docs.deno.com/runtime/manual/advanced/continuous_integration#caching-dependencies).
screm
found while investigating CI failure on #3992
=> ci: cache deno dependencies

.github/workflows/autofix.yml
provide better explanation for comments made by those interesting looking tree bot.
be more specific
- not use the bot
- manually format stuff
- pain
should work, since it's only markdown changes.
=> ci: improve autofix comment

data/json/itemgroups/Monsters_Animals_Lairs/monster_drops_advtech.json
Some adjustments to the lowered spawn rates of bionics per experience with playtesting. General thing I found was that the new lower-tier harvest entries were much rarer than intended because of how both regular CBMs and power storage are merged into a single harvest roll, whereas the traditional cyborg zeds tend to have a separate roll for power storage.
1. Elevated the total chance of getting anything out of `cyborg_harvest_uncommon` from 10% to 40%, as all its potential yield is merged into a single roll. Additionally weighted the CBM portion more towards bionics over power storage. This makes the total chance of getting a CBM from lab mutants and armored zombies 20%, compare two shots at 50% chance each for lab cyborgs and bio-operators.
2. Likewise bumped the following groups from a …
=> feat(balance): adjust effective CBM chance of lower-tier profession zeds

data/json/mapgen/jewel_store.json
Remove unnecessary lines.
Use "t_region_groundcover_urban" for outside.
"t_pavement" under outdoor dumpsters.
JSON changes.
Do nothing.
=> fix: jewelry store mapgen

src/activity_item_handling.cpp
- fix #4005 
due to `item::charges_per_volume` returning 0 when no charges fit in given volume, `std::clamp(10, 1, 0)` will return 0, which will always move entire stack of items.
previous expression, `std::max(1, std::min(10, 0))` will return 1 and work correctly here
_cri_
was able to use plank to light up oven.
urgent fix for 0.5.1
=> revert: "refactor: use `std::clamp`"

src/npctrade.cpp
- fixes #4006 
only set ownership for splitted item if item is counted using charges.
_cri more_
traded with 1 of 100 hub gold coins. ownership for 99 coins was intact.
we should really make everything stackable and remove this unholy mess.
=> fix: prevent full ownership transfer when trading with partial charges of item

src/item.cpp
- fix #4009 
check for emptiness first
rewrite liquid logic to something sane
followed steps in #4009. no debugmsg occured.
_pain_
=> fix: prevent debugmsg while refilling liquid container with another one

src/vehicle_part.cpp
- fixes #3933
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/37586353b31a28ec0f4a7ad71e7ad844e52ad0ec/src/savegame_json.cpp#L2499-L2503
running debugger for an hour has shown that despite `carry_names` properly being loaded in `vehicle_part::deserialize`,
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/37586353b31a28ec0f4a7ad71e7ad844e52ad0ec/src/vehicle.cpp#L2150
it was always empty on `vehicle::remove_carried_vehicle`.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/37586353b31a28ec0f4a7ad71e7ad844e52ad0ec/src/vehicle_part.cpp#L77
found out `vehicle_part::copy_static_from` was the culprit. it wasn't copying `carry_names`.
rewrite vehicle logic from scratch
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/5a2e78da-9627-4e23-8044-e827edf5cfa4
1. mount bike …
=> fix: bike rack merging vehicle merging after loading from save

data/json/monsterdrops/feral_humans.json, data/json/monsterdrops/zombie_military_pilot.json
As part of #3090 this requires all weapon groups to be taken out of holsters as this could spawn guns AND ammo, which doesn't make sense in a holster that can normally only hold 1 item. Fixes #3982 .
Copied zombie soldier military death drop pistol chances to both feral militia and zombie military pilot death drops, which are the only two monsters to have the pistol group in their holsters creating multiple items. Copied from normal military soldier zombies so 30% probability to spawn. 
None, this was outlined in #3090 - all weapon groups must be outside their holsters otherwise things get weird.
Yup, dropped this into my test world and.... now I have an empty holster as well as the problem holster with multiple items in it. What. This doesn't make sense. @chaosvolt pls
=> fix(content): Fix holsters holding multiple items

data/json/furniture_and_terrain/terrain-liquids.json
I was more focused on getting JSONized plant terrain data out the door than worrying if cattails could grow on flowing water and murky water. Now they can.
Added the flag to flowing water and murky water. All shallow waters besides nasty chlorinated pool water can grow cattails now.
None
Same flag as the other terrains
=> fix: adds  "SHALLOW_WATER" flag where appropriate

data/json/mapgen/miniature_railway/miniature_railway.json
Replace sidewalks under counters with wooden floors.
JSON changes.
none
Before:
After:
=> fix: floor under counters in Luna park

data/json/mapgen/pawn_shop.json
Use "t_region_groundcover_urban" for outside.
Also remove outdoor wooden floor on "pawn_1".
JSON changes.
none
Before:
"pawn_1":
After:
"pawn_1":
=> fix: pawn shop outdoor terrain

data/json/mapgen/cs_internet_cafe.json
Use "t_region_groundcover_urban" for outside.
Place a flat roof under the cooling units on the roof.
JSON changes.
none
Before:
After:
=> fix: internet cafe outdoor and roof

data/json/mapgen/mi-go/mi-go_nested.json, data/json/mapgen/mi-go/mi-go_scout_tower.json
Fix a flying terrain tile in the "mi-go_scout_tower_3" mapgen.
JSON changes:
Create a copy of the nested mapgen "mi-go_encampment1_room14", adapted to level 2 of the tower.
none
Before:
After:
=> fix: mi-go scout tower

src/monexamine.cpp
- fix #4031 
use [`item::split`](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/578117ae7b3051bb2be8dd8a9c127eab1ecddbbe/src/item.h#L368) instead of [`game_object::detach`](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/578117ae7b3051bb2be8dd8a9c127eab1ecddbbe/src/game_object.h#L51)
~~unify charges for the 100th time~~
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/4e208d79-8e84-4d6a-9c56-c36deeb9abec
_end of 2023 with fixing bugs lol_
=> fix: leashing animal using entire stack of rope

.github/workflows/manual-release.yml
- resolves #4017
- changed input from `version` to `major`, `minor`, `patch` to use semantic versioning
- stables are now versioned from `cbn-0.5.1` to `v0.5.1`
- keep it as-is? (sorry i change versioning scheme every so often)
- merge experimental and stable into one? currently there's kind of no distinction between them
https://github.com/scarf005/Cataclysm-BN/releases/tag/v0.5.1
it works.
=> ci: semantic stable release

data/json/mapgen/roadstop.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_transportation.json
Connect roadstop, public washroom, roadside foodcart to the road and remove their "SIDEWALK" flag.
Modify roadside foodcart parking.
Change the placement of some objects, use "t_region_groundcover_urban" for the outside terrain, and remove useless crates.
JSON changes.
Do nothing.
Before:
After:
"roadstop":
"roadstop_a":
"roadstop_b":
=> fix: roadstop, public washroom, roadside foodcart

data/json/mapgen/s_candy.json
I redo #4042.
Fix "candy_shop_roof" because a line forgotten during #3779 places a flat roof line that shouldn't be there.
Delete line 138 because "A": "f_air_conditioner" is in the "roof_palette".
JSON changes.
none
Before:
After:
=> fix: "candy_shop_roof" mapgen

data/json/mapgen/city_blocks/city_block_2.json
Replace stairs with ladders on the roof of the city block, because ladders are more appropriate here.
JSON change:
Replace "t_stairs_down" with "t_ladder_down".
Do nothing.
Before:
After:
=> fix: replace stairs with ladders on city block roof

data/json/overmap/overmap_terrain/overmap_terrain_ranch_camp.json
silo with `|` or `#` as symbol doesn't fit.
Change some of the ranch symbols in overmap_terrain_ranch_camp.json to make the ranch look good on the map and be consistent.
Do nothing.
Before:
After:
=> fix: change `ranch_camp` overmap symbols

data/json/mapgen/airliner.json
The metal floor "t_metal_floor" used for the roof of the crashed airliner must be replaced by something else, because the metal floor places a flat roof on the upper level, level 2.
JSON change.
Use "t_metal_flat_roof" instead of "t_metal_floor" for "airliner_2a_1", "airliner_2b_1", "airliner_2c_1".
none
Before:
After:
=> fix: crashed airliner

data/mods/rural_biome/rural_regional_map_settings.json
Partially fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3993
Rural biome mod was horribly out of date and missing bog iron, some plants and trees such as cacao and coca trees, and had burdock which doesn't appear in vanilla.
Copied everything from the start of the vanilla file until map extra generation and replaced all of those fields in rural biome.
Possibly migrating away from a map settings overwrite, which may not be possible to blacklist urban locations that way.
it worked.
pain
=> fix: map settings on rural biome updated with new additions

src/animation.cpp, src/armor_layers.cpp, src/cata_tiles.cpp, src/cata_tiles.h, src/character.cpp, src/computer_session.cpp, src/creature.cpp, src/creature.h, src/editmap.cpp, src/enums.h, src/game.cpp, src/game.h, src/handle_action.cpp, src/iexamine.cpp, src/magic.cpp, src/magic_spell_effect.cpp, src/mattack_actors.cpp, src/monattack.cpp, src/monmove.cpp, src/monster.cpp, src/npc.cpp, src/npcmove.cpp, src/ranged.cpp, src/safemode_ui.cpp, src/safemode_ui.h, src/sounds.cpp
Decouple creature attitude from creature so as to reduce the inclusion of `creature.h`.
Changed Attitude from being an internal enum of Creature to simply being an enum, now defined in `enums.h`. Fixed code after this refactor by bash scripts: `for FILE in $(find ./ -name '*.cpp' -or -name '*.h'); do sed -i -E 's@(Creature::)*(Attitude::)*(A_HOSTILE|A_NEUTRAL|A_FRIENDLY|A_ANY)@Attitude::\3@g' $FILE; done
`, `for FILE in $(find ./ -name '*.cpp' -or -name '*.h'); do sed -i -E 's@Creature::Attitude@Attitude@g' $FILE; done` and `for FILE in $(find ./ -name '*.cpp' -or -name '*.h'); do sed -i -E 's@MFAttitude::@MF@g' $FILE; done`.
None.
Tested if the code compiles by `make LUA=0 TILES=1 SOUND=1 RELEASE=1`.
=> refactor: Decouple attitude from creature

data/json/mapgen/sugar_house.json
Replace the outdoor sugar house terrain with something better.
Remove "weight".
Use "t_region_groundcover" and delete unnecessary "set" lines.
Do nothing.
1. Changes didn't crash my game.
Before:
After:
=> fix: sugar house outdoor terrain

data/json/monsters/turrets.json
Shard pointed out in DMs recently that he found out that riot turrets aren't despawned by card readers, having ran into a lab that inexplicably used those instead of the normal light turrets.
Turns out that's in vanilla, in the office labs. Easy fix. :3
Set riot turrets to have the `ID_CARD_DESPAWN` and `CONSOLE_DESPAWN` flag, same as all other armed turrets.
Setting office labs to use 9mm turrets to guard the entrance like a normal sci-fi megacorp.
=> fix: allow card readers to despawn riot turrets too

data/json/npcs/items_generic.json, data/json/skills.json, src/npc.cpp, src/skill.cpp, src/skill.h
This aims to fix up some flaws with the hardcoded way in which NPCs generate their default starting weapons, clearing the way for better NPC gear variety in the future.
C++ changes:
1. In npc.cpp, updated `npc::best_skill` to only check for what counts as weapon skills, to prevent weird shit like an NPC how has high marksmanship skill than their pistol skill or whatever generating unarmed because by the code's logic their best skill isn't a weapon skill. Uses a neat bool as outlined below.
2. Also in npc.cpp, updated the logic `npc::starting_weapon` a bit. Now it probably checks for all the skills in-repo that might reasonably qualify as a weapon skill, and fixed the fallback behavior to actually properly kick in as a default result and not being skippable if the NPC's top skill was an …
=> fix: better define how NPCs generate starting weapon

src/monster.cpp
This sets it so monsters will ignore mechs that aren't currently being ridden.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4030
In monster.cpp, changed `monster::attitude_to` so that, when checking the attitude towards a fellow monster, monsters with the `RIDEABLE_MECH` flag are treated as neutral if they currently also lack the `ridden` effect.
This allows them to still figure out the mech is moving around and acting sus when being ridden if the player is somehow undetectable at the moment (or more amusing and actually-applicable-to-normal-gameplay example, allowing zombies to assume the furniture has abruptly decided to stand up and kidnap their friendly neighborhood player feral).
screm
2. Made myself undetectable in debug and spawned in a …
=> fix: monsters ignore mechs that aren't being piloted

data/mods/DinoMod/recipes/food_egg.json
Fixes an issue occurring regarding Dinomod overwriting the egg-based food recipes to only use dinomod eggs.
Adds an appropriate id_suffix to the relevant recipes.
Also removes the random extra powdered egg recipes that just had a slight time difference and the ability to use surface_heat, just for the sake of making sure they aren't overwriting anything (though those might have been the intended proper recipes)
- Leaving those tasty bird and other egg types unable to be cooked
- Instead removing the other pair of powdered egg recipes, and keeping the ones with surface_heat
I just have no clue what the purpose of the ones with surface_heat was, and thus I chose to keep the ones consistent with vanilla.
Loaded in, confirmed that everything was working
Down with the dino-egg monopoly on egg …
=> fix(mods/DinoMod): Fix Dinomod overwriting various egg-based food recipes

data/json/items/armor/boots.json, data/json/recipes/armor/feet.json
Normal socks are not very warm, but wool socks can be annoying to acquire. Thicker cotton socks makes perfect sense.
Added in new item, thick socks, and corresponding recipe. They're half as warm as wool socks.
=> feat(content): Thick socks

data/json/mapgen/s_clothing.json
Fix because shopping carts in "s_clothes" are placed outside on the grass and appear "like new" constantly.
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/51178
Set "status" to 1 for shopping carts.
Do nothing.
Before:
After:
=> fix(port): shopping carts in `s_clothes` mapgen

data/json/mapgen/sai.json
Change the terrain around the serving area interface with something better.
Use "t_region_groundcover".
Do nothing.
Before:
After:
=> fix: serving area interface terrain

src/npcmove.cpp
This fixes NPCs being able to see and react to explosives they have no way of knowing are present on the other side of a wall, which negates a lot of the !!FUN!! of dynamic entry.
In npcmove.cpp, set `npc::find_dangerous_explosives` so that the NPC in question continues on and dismisses positions that they aren't able to actually see.
Adding an extra layer to this by figuring out how to check whether the NPC is in range to hear the tick sound being given off, and if so allow them to still flee.
2. Spawned in a refugee center.
3. Deployed some C-4 on the other side of a wall from an NPC who couldn't see it.
4. The poor sod obvliously gets toasted.
5. Dropped C-4 where the NPC can see it.
6. They still correctly call it out and flee.
7. Checked affected file for …
=> fix: NPCs no longer magically aware of explosives they can't see

data/json/mapgen/map_extras/wilderness.json
Lil rebalance per feedback from RoyalFox on the discord, as it turns out the balance of abandoned sheds can get a bit wacky, especially so when you bump item spawn rate up (though that) due to how common full stacks of nails can be in it.
1. Per feedback, axed the system of having items spawn per tile since the basic floor calls so damn many of them.
2. Instead, placed a few area spawns in a random space within the room. Uses `stash_wood` and `recycle_iron` instead of `wood_workshop` since the latter has more interesting spawns plus is one of the few itemgroups that doesn't spawn entire stacks of nails when it shows up, also replaces the potential calls to `mischw` with one potential call to `tools_carpentry`.
Defining a custom group for shed contents.
1. Checked affected file for syntax …
=> feat(balance): adjust spawns in collapsed sheds

data/json/furniture_and_terrain/furniture-terrains.json, data/json/furniture_and_terrain/terrain-flora.json, data/json/furniture_and_terrain/terrain-walls.json
This consistency-checks and tweaks some bash and related yields from certain terrain innawoods to make some aspects a bit less annoying. In particular this also makes it a bit more reliable getting the basic trickle of limestone needed to start mining without already having access to mining (or using Mining Mod).
1. Set young trees and related (coca) to yield 1-4 long sticks instead of 0-5, allowing you to always get long sticks out of a tree in exchange for a lower max possible yield (in my experience you seem to encounter the annoyance of trees dropping no sticks way more often).
2. Removed the 50% chance of getting nothing out of bashing underbrush and all related terrain that bash into withered plants outright. Cutting/digging grass for straw is already noticeably better as a way to …
=> feat(balance): more consistent bash results for plants and stone

data/json/furniture_and_terrain/terrain-flora.json, data/json/regional_map_settings.json, data/mods/rural_biome/rural_regional_map_settings.json
Another lil innawoods balance adjustment while I'm failing at going to bed. Aim is to sanity-check the frequency of bog iron, cacao trees, and coca plants.
1. Doubled the weights used in `t_region_groundcover_swamp` while keeping bog iron at its original weight, with the aim of making it half as common as before.
2. Reduced weights of cacao and coca trees in `t_region_tree` to 1 instead of 2.
3. Reduced weight of cacao trees in `t_region_tree_shade` to 1 and removed coca plants from it, as that wouldn't exactly count as a shade tree.
4. Reduced weight of cacao tree in `t_region_tree_fruit` to 1 since the total weights here are also vastly lower.
5. Updated description of coca plant to allude to the likely medical research origin of it being modified to show up here, with the implication …
=> feat(balance): sanity-check rarity of bog iron, cacao, coca

data/json/furniture_and_terrain/terrain-doors.json
This fixes examining interior pickable metal doors not automatically lockpicking like they're supposed to. They worked just fine on manually activating a lockpick, but not on examine.
Turns out the problem is `examine_action` doesn't inherit right. Also found out that it needs to inherit `lockpick_message` too.
Adds `lockpick_message` and `examine_action` to pickable interior doors.
Finding the inheritance code responsible for this and figuring out how to add proper inheritance for those things? Not sure where to look for that and this is faster so.
2. Ported JSON change to playthrough build.
3. Can now pick open the military outpost doors I was previously unable to, and correct message prints.
=> fix: interior pickable metal doors can now pick on examine

src/npcmove.cpp, src/sounds.cpp
This fixes another couple of cases of NPC messages printing in cases where they shouldn't.
1. In npcmove.cpp, set `npc::move_to` so the second case of having NPCs shout "lemme move ree" (the one that applies when the person blocking the way is a fellow NPC) doesn't trigger if the person committing Door Stuck is currently following the player. In this case it can be reasonably assumed they get the picture and will move out of the way on their own when the player does, and more importantly this fixes the constant "move plz" spam that happens when you've got more than one NPC follower tailing you.
2. In sounds.cpp, set `sounds::process_sound_markers` so you're only reminded about noise waking you up if the person being woke up is the player, not an NPC.
Making the sound message use a …
=> fix: two cases of NPCs printing messages in odd contexts

src/item.cpp
Fixes #4068.
Moves magazine reloading to the new safer stack splitting system and moves the old charges==0 check to the one branch that still uses the old stuff. 
Cleaning it up further, moving that last branch to the newer stuff and sorting out whatever's going on with speedloaders is probably a good idea at some point. 
The reported bug (i.e. reloading liquids), reloading magazines, reloading singles and reloading with a speedloader.
=> fix: Prevents reloading from deleting containers

data/json/deconstruction.json
Someone used count for nails instead of charges when deconstructing linoleum. I noticed this because I'm the proud owner of about 6000 nails from partially renovating an evac shelter.
I replaced count with charges.
Creating a typhoon of nails.
Backported to my game so I could actually renovate my evac shelter.
Before
After
=> fix: stops linoleum from granting 1500 nails per tile

data/json/furniture_and_terrain/terrain-windows.json
After discussing it, it's reasonable to have closed glass windows block scent from traveling outside. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4112
Enables players to hide in buildings by having all closed glass windows block scent. IRL windows aren't 100% airtight but they should also feasibly be airtight enough that the smell will barely travel through it. In addition, I expect this to not dramatically alter balance because it only allows you to hide, not to fight or run away. If you shouldn't be in an area you'll still die.
The flag "NO_SCENT" was added to all relevant entries, replacing "REDUCE_SCENT" where applicable
suffering
Doors don't block scent at all either. That's a concern for another day. Also this file hilariously uses almost no copy-froms and …
=> feat(balance): closed glass windows block scent

doc/src/content/docs/en/mod/json/reference/creatures/effects_json.md, doc/src/content/docs/en/mod/json/reference/json_info.md
There was poor documentation for adding effects via mutation, I added documentation for doing this with mutation enchantments.
In json_info.md The field for enchantments is added.
in effects_json.md I gave an in-repo example of a mutation that grants an enchantment, and an example of an enchantment that grants a permanent effect.
Keeping it a mystery because that's funnier. Bugging others.
It's docs.
Pain
=> docs: add info for mutation enchantments

data/json/itemgroups/Agriculture_Forage_Excavation/forage.json, data/json/itemgroups/Food/food.json, data/json/items/comestibles/alcohol.json, data/json/items/comestibles/brewing.json, data/json/items/comestibles/drink.json, data/json/items/comestibles/raw_veggy.json, data/json/items/comestibles/seed.json, data/json/recipes/food/brew.json, data/json/recipes/food/drinks.json, data/json/recipes/food/other.json
Rice is currently unfarmable, so I decided to make it farmable as well as add in related rice products such as rice bran, sake, and by Scarf's request, sikhe.
Rice now is farmable in shallow water, and produces more of its own seeds (as well as straw) as a product. Rice seeds can be processed into dried rice with rice bran as a byproduct, and rice can now be used to make sake and sikhye, two new items. Rice bran is used to make vegetable oil.
I've also noticed that fruit wine only has a fun value of 2, so I've edited that to be 20.
The json checks out, it loads fine.
=> feat(content): rice farming, rice bran, sake, sikhye

data/json/mapgen/house/2storymodern04.json
Just like the bungalow02 garage, the "t_concrete" terrain used in the garage doesn't have the INDOORS flag and must be replaced because it's weird to be able to see the sky in the garage or to be glared by the sun inside.
Replace "t_concrete" with "t_thconc_floor".
Creates "t_concrete" with an INDOORS flag.
Do nothing.
1. Check the JSON for errors.
2. No errors when starting a new character.
Before:
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/146018959/40c89db5-508f-42b5-9b7c-c2ea6c25ec6a
After:
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/146018959/4bfdd1bb-1895-4520-bb69-30ae57b1de4d
=> fix: `2storymodern04` garage

src/activity_handlers.cpp
So, a lot of feedback has come in suggesting that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3719 undervalued the impact of skills on butchery and dissection yields. A lot of this is ultimately because dissection isn't as granular as it could probably afford to be, so going so far as to break up, for example, the electronics skill being divided by 4 means it takes several levels for it to kick in and actually bump up your success result by any amount at all.
1. In activity_handlers.cpp, changed `activity_handlers::butcher_finish` so that the baseline definition of `skill_level` is back to using survival skill directly instead of cutting it in half (so result is a clean 0-10 instead of randomized 0-7).
2. Furthermore, made both skills being checked for when dissecting grant 1 …
=> feat(balance): dial back nerf to skill impact on butchery a bit

src/ranged.cpp
This sets it so mounds of dirt, open windows, and other terrain can support bipods and heavy weapons again.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4126
In ranged.cpp, updated the definition of `is_mountable` to check for passable tiles OR climb difficulty when screening out closed-off vehicle tiles from the check.
It seems that stuff that doesn't bother with any climb flags due to being a plain passable terrain, like mounds of dirt for example, are most likely keeping the inherited default climbing difficulty of `INT_MAX`, hence why the check borks because that value is definitely gonna be greater than 5.
Pestering @scarf005 to fix it instead.
2. Confirmed I can once more fire an M2 Browning while on or adjacent to open windows and mounds …
=> fix: mountable terrain usable for firing heavy weapons agian

src/character_functions.cpp
- fixes #4137 
return `std::nullopt` instead of default initialized value
RIIR
worked in my machine
prerequisite for patches i'm making in #4125
=> fix: `pick_safe_adjacent_tile` returning invalid position

data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_commercial.json
Connect the rural gas station to the road.
Modify overmap_terrain_commercial.json to remove the sidewalk of the rural gas station.
none
Before:
After:
=> fix: road connection for rural gas station

src/game.cpp
Lines of text within the look-around panel were being drawn on top of one another. Fixes #4140, Fixes #3945.
Slightly reworked inconsistent line number accumulation/usage that was leading to overlap. In the whole call tree of the game::print_all_tile_info function, only game::print_terrain_info and game::print_visibility_info appeared to be problematic.
Started a new character and looked around at lighted tiles, dark tiles, tiles with stuff on them, with an NPC, etc. Seemed okay.
=> fix: Fix overlapping text in look-around.

data/json/bionics.json
A lil fix for something I forgot, namely NPC usage is required at both the item level and the bionic entry level.
Adds `BIONIC_NPC_USABLE` to the bionic entry for infolink, since the item form was set to copy from the NPC-usable template and idea was you can shove a radio in your friend's head. :3
screm
Load-tested JSON change in test release to confirm that yes, shoving a radio in your friend's head is 100% doable with this added and it works right in the `#` menu once done so.
Thanks to @EkarusRyndren for making me realize I only tested if the PC has this bionic, as trying to install it on an NPC to make sure both sides of it work as intended led me to discover I forgot this.
=> fix: add `BIONIC_NPC_USABLE` flag to infolink bionic

data/json/mapgen/s_grocery.json
Fix `s_grocery_1` outdoor terrain.
Use "t_region_groundcover_urban" and connect the grocery store to the sidewalk.
Do nothing.
Before:
After:
=> fix: `s_grocery_1` outdoor terrain

msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-test-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-vcpkg-static.vcxproj, msvc-full-features/JsonFormatter-vcpkg-static.vcxproj
So it turns out https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4154 also came with a bonus changing of default vcpkg settings such that VS2019 users can't compile anymore.
Reverted the file changes specifically in the `msvc-full-features` folder.
Saying "fuck you" to people who still use VS2019 (like myself) instead of expecting VS2022 users to figure out however you set it to use v143 build tools for compile-tests without changing the setting in the repo itself.
Compiled and load-tested after the revert.
=> fix: switch build tool back to v142 to fix vs2019

src/npc.cpp
Fixes #3980
Merchant NPCs are pulling all faction owned items within PICKUP_RANGE when restocking. If there are faction owned items in display cases they will disappear and not be replaced. Since merchants drop excess inventory at their feet we should only be picking up that inventory when restocking.
Reduce range from `PICKUP_RANGE` to `0`
Make a "merchant hammerspace" alternative inventory so that merchant carried sales inventories can go into there without bringing back perf issues from being overburdened while carrying items in the personal inventories. Sorta like the inventory chests that NPCs access in Oblivion / Skyrim.
=> fix: reduce merchant item restock range

src/safe_reference.h
Fixes #4108.
Counts the references correctly. It was missing the increment on redirect resolution and wasn't counting the redirected entries themselves. 
Works on the save in the linked issue, tried 3 times without a crash when the crash rate was 100% before.
=> fix: uaf in safe references

data/json/mapgen/orchard_apple.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_agricultural.json
Put a roof over `orchard_processing`, `orchard_stall` mapgen.
Create roofs.
Terrain can place roofs over them with "roof" in their JSON, but this is not a good solution.
Before:
After:
=> fix: orchard processing, stall roof

src/iexamine.cpp
Fixes #4101.
It was handling the container rather than the contents. Note that the check that the contents exists is done before enabling that menu option.
=> fix: tapping maple trees

data/json/items/resources/wood.json, data/json/recipes/other/other.json
Added in fuel briquette, a puck of dried plant matter that's used as firewood.
Straw and dried plants have very few uses beyond cordage and some innawoods constructions. I decided to give them another.
Added in fuel briquette, a lump of dried plant matter that burns.
=> feat(content): fuel briquette

src/melee.cpp
Every so often @Coolthulhu mentioned in the BN discord wanting to bring back some form of bonus damage to unarmed attacks scaling with skill, ideally in a form that would encourage the player to try fighting bare-handed at high unarmed skill as a viable alternative to unarmed weapons.
In melee.cpp, set `Character::roll_bash_damage` so that the `weap_dam` value gains a bonus equal to double that of `skill`, IF the user is fighting truly unarmed with no wielded weapon. This sets weapon damage to 20 at 10 unarmed skill, matching the performance of the katar and only outclassed (in-repo) by the bionic unarmed weapons.
While this does get the same "you get double your unarmed skill in this value" effect of the old code, there are a couple main differences compared to the old bonus:
* Does not …
=> feat(balance): unarmed skill affects empty-handed damage again

data/json/vehicles/bikes.json
Fix because the front frame/wheel of the motorcycle chassis and the right front frame/wheel of the quad bike chassis are missing.
Add missing parts.
If the missing parts are intentional, do nothing, but it seems odd to me.
Before:
Motorcycle Chassis/Quad Bike Chassis
After:
=> fix: motorcycle, quad bike chassis missing part

data/json/furniture_and_terrain/furniture-appliances.json, data/json/vehicleparts/vehicle_parts.json, tests/vehicle_power_test.cpp
Made regular solar panels generate 80 power instead of 50 and advanced solar panels generate 160 instead of 100.
Solar panels are rather weak ingame currently, and struggle to properly recharge vehicles and power grids.
The power generation of all solar panels will be increased by roughly 60%.
Reimplementing quantum solar panels.
=> feat(balance): Solar power bump

data/json/mapgen/nested/house_nested.json
Fix because "t_dirtfloor" used under the planters of these two nested mapgen should not be used outdoors.
Use "t_dirtfloor_no_roof".
none
Before:
`garden_3x3_3` used around the cathedral.
After:
=> fix: `garden_3x3_2`, `garden_3x3_3` nested mapgen

doc/src/content/docs/en/mod/json/reference/creatures/magic.md
I noticed that the magic flags still weren't in the docs evidently, so I put them in here myself. Thought they'd be helpful to be in the docs, rather than making people look through the magic.h file.
Copies the list of valid spell flags from magic.h to the documentation with appropriate formatting
Continue to be mildly annoyed at the lack of spell flags in the documentation.
Attempted to match the formatting of the rest of the file as best I can. It's docs, so it at least won't break the game even if I did somehow screw up that royally.
^-^
=> docs: Include Spell Flags in Magic Documentation

data/json/itemgroups/Clothing_Gear/clothing.json, data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json, data/json/itemgroups/military.json
So recently I spotted a weird lil error: when a gun spawn (like zombie soldier drops) generates the grenadier variant, it also spawns M203s attached to the spare magazines that spawn, leading to this oddity when you try to unload them:
Along the way I spotted another smol mistake that I figured is minor enough to bundle in this.
1. Redefined contents of `military_standard_grenadier` to define grenadier-specific versions of the sub-itemgroups in `military_standard_assault_rifles` instead of using the itemgroup wholesale, so it won't also apply the gunmod to the spare mags derp.
2. Defined the above-mentioned variants of the relevant everyday-carry itemgroups, which spawn the relevant gun with `military_accessories_grenadier` added to them, then the relevant spare mags.
3. Misc: Fixed …
=> fix: don't spawn grenade launchers installed on magazines

data/json/items/generic.json
After being smoked, the hides and felts get a correct number.
Put the field `"stackable":true`
Then it looks fixed at all.
screm
=> fix: hides after being smoked get merged into one

src/character_functions.cpp, src/item_factory.cpp
This helps make it a bit more visible when your wielded weapon is currently set to fire an attached gunmod, because it's easy to look at the wield query after flipping past full-auto, forgetting that the next fire mode is an M203 and not returning to semi-auto, and oops I exploded again.
1. In character_functions.cpp, set `fmt_wielded_weapon` so that the ammo counter for the currently wielded weapon actually matches the ammo count of the current fire mode used, meaning the number of shots shown will properly change when you switch from a gun's normal firing modes to any attached gunmods.
2. In item_factory.cpp, set `defmode_name` so that gunmods will generate a default fire mode name telling you at a glance that the selected fire mode has you switched to a gunmod. This can of course be …
=> fix: wielded weapon show correct ammocount when selecting gunmod, default firemode name for gunmods

.github/workflows/msvc-full-features-cmake.yml
- fix #4199
tests for windows aren't running in PRs because 
1. I disabled MSVC+vcpkg workflow
2. believing MSVC+cmake workflow would run instead
3. turns out it lacked a trigger for PRs (probably because it's WIP by the time (and still is) olanti added them)
copy and paste the same trigger used by MSVC
turn back on MSVC+vcpkg action
help me, CIIIIIII!
didn't enable MSYS2 + cmake one as it didn't seem very popular
=> ci: test msvc on PRs

src/overmap.cpp
In my laptop save I spotted a trapped tendril just chilling in the middle of a lake, having drifted from the nearby office tower due to horde mode behavior.
In overmap.cpp, changed `overmap::move_hordes` so that the OR function that filters out monsters who should not join hordes also checks for stuff with the `IMMOBILE` monster flag. It already excludes monsters with a speed of 30 or less, so monsters that can't move at all are fitting to exclude too.
Not playing with wander spawns on and/or not trying to raid aircraft carriers just offshore from collapsed office towers.
Currently out and about, can compile test when I get back home but don't see any sane way to actually test this other than setting half the monsters in the game to have the `IMMOBILE` flag then agitating the zeds to see …
=> fix: don't allow `IMMOBILE` monsters to join hordes

data/json/furniture_and_terrain/terrain-floors-outdoors.json, data/json/mapgen_palettes/acidia_commercial_destroyed_palette.json
Redo #3891.
Change description and id of `t_thconc_floor_nofloor`.
Remove `t_thconc_floor_nofloor` from acidia_commercial_destroyed_palette.json
Create `t_thconc_floor_no_roof` with `t_thconc_floor_nofloor` as "alias" in terrain-floors-outdoors.json
Change only the description.
1. Took a save file made before these changes.
2. Load the save file in another game, which contains these changes in the JSON.
3. No errors.
none
=> fix: description and id of `t_thconc_floor_nofloor`

data/json/furniture_and_terrain/terrain-doors.json
This fixes not being able to pry open the interior version of pickable metal doors with a halligan bar like you can the regular version.
And then it turns out regular locked doors can't even be pried open despite having pry data so fixing that while I'm at it, derp.
1. Copied and pasted pry data from `t_door_metal_pickable` to `t_door_metal_interior_locked`, which didn't have it due to actually copying from `t_door_metal_locked` (the garage/lab shutter doors).
2. Changed the iexamine for both to `locked_object` like regular doors that are both pryable and pickable have.
screm
2. Copied file change to test build, confirmed I can now pry open the doors in aircraft carriers.
3. Spawned in a locksmith set to confirm I can still pick them …
=> fix: prying data for pickable metal doors now actually works

data/json/itemgroups/Weapons_Mods_Ammo/guns.json, data/json/items/ranged/slings.json, data/json/recipes/weapon/ranged.json, data/json/vehicleparts/turret.json
This adds a weapon geared towards a higher-power upgrade step beyond slings and staff slings, with the added bonus of a design that can reasonably justify being a launcher-skill, in turn making it possible to break into entry-level launcher skill without spending valuable 40mm rounds on practice.
Also, as can probably be guessed, inspired by the over-the-top creations devised by Joerg Sprave (https://www.youtube.com/@Slingshotchannel).
1. Adds item definition for a slingshot cannon. Geared towards being a signifigant step up in raw damage over the staff sling, a more modest step up in range, and accuracy comparable to baseline slingshots, using the launcher skill. Notably bulkier, high reload rate instead of being a reload-and-shoot weapon, `STR_RELOAD` can help with it.
2. Added recipe …
=> feat(content): adds an entry-level launcher weapon

data/json/recipes/food/other.json
To craft coffee powder, you require a plastic bag to contain the coffee powder which gives you a plastic bag full of coffee powder. You then have to manually Unload the coffee powder to get your plastic bag back. This stops the tedium.
Removed the contained field, as well as the plastic bag component.
I am fine with requiring a plastic bag as a tool, but currently this is the ONLY recipe in the game I'm aware of that requires this, starch doesn't but starch still requires a hammer.
WTF WHY?
=> fix: stop requiring plastic bags for coffee powder crafting

data/json/furniture_and_terrain/furniture-appliances.json, data/json/furniture_and_terrain/furniture-barriers.json, data/json/furniture_and_terrain/furniture-decorative.json, data/json/furniture_and_terrain/furniture-fireplaces.json, data/json/furniture_and_terrain/furniture-graves.json, data/json/furniture_and_terrain/furniture-industrial.json, data/json/furniture_and_terrain/furniture-medical.json, data/json/furniture_and_terrain/furniture-migo.json, data/json/furniture_and_terrain/furniture-plumbing.json, data/json/furniture_and_terrain/furniture-recreation.json, data/json/furniture_and_terrain/furniture-roof.json, data/json/furniture_and_terrain/furniture-seats.json, data/json/furniture_and_terrain/furniture-signs.json, data/json/furniture_and_terrain/furniture-sleep.json, data/json/furniture_and_terrain/furniture-storage.json, data/json/furniture_and_terrain/furniture-surfaces.json, data/json/furniture_and_terrain/furniture-terrains.json, data/json/furniture_and_terrain/furniture-tools.json, data/json/furniture_and_terrain/terrain-doors.json, data/json/furniture_and_terrain/terrain-manufactured.json, data/json/furniture_and_terrain/terrain-mechanisms.json, data/json/furniture_and_terrain/terrain-walls.json, data/json/furniture_and_terrain/terrain-windows.json
This does a bit of standardizing and cleanup for ballistic resistance of furniture and terrain before I work on applying the feature to more stuff.
1. In general, all standard terrain and furniture with `ranged` bash data already specified now have their reduction properly set to an amount ranging from half their `str_min` (rounded up if needed) to `str_min`. Before I used arbitrary ranges that kinda sorta peaked at close to `bash_min`, but often I was using 5-10 values for basically anything with less than 15 bash_min, 10-20 for stuff in the 10-25 range, etc. This made very fragile terrain a bit tankier as ballistic protection than probably desirable, made a few substantially solid obstacles no better than some that could reasonably be considered more fragile, not to mention looked more …
=> feat(balance): further standardize and increase use of ranged bash info

data/json/items/melee/spears_and_polearms.json, data/mods/Magiclysm/items/alchemy_items.json, data/mods/Magiclysm/items/enchanted_melee.json, data/mods/Magiclysm/items/ethereal_items.json, data/mods/Magiclysm/items/weapons.json, data/mods/TEST_DATA/items.json
So, https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4214 was implemented by a script that accidentally converted some polearms from cutting damage to piercing damage.
In addition, mods folder wasn't touched by that PR.
1. Fixed makeshift glaive, glaive, naginata, naginata replica, and ji accidentally being converted into piercing weapons. Kept `SPEAR` flag on them for now.
2. Added `SPEAR` flag to naginata fake because the other variants have it. How the fuck the automation script missed that when the item is basically identical to the other two flag-wise is beyond me.
3. Updated items in mods that I had already set up to fix in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4212. Swapped `SPEAR` for `STAB` for stirge proboscis, demon spider fang, barbed javelin, TEST sonic …
=> fix: don't assign piercing damage to weapons that were previously cutting

src/game.cpp
Allow throw while peeking  downstair/upstairs. Port of [#49014](https://github.com/CleverRaven/Cataclysm-DDA/pull/49014) from DDA
Remove ```look_around()``` handling in ```game::peek()``` when there is a z-lvl move, and let ```game::peek( const tripoint &p )``` handle this.
Merging ```game::peek()``` and ```game::peek( const tripoint &p )```
Source PR: throw while peeking up/down stairs, by @zeropol: https://github.com/CleverRaven/Cataclysm-DDA/pull/49014
=> fix(port): allow blind throw while peeking upstairs/downstairs

data/json/uncraft/generic.json
Realizing that I can't salvage gallon jugs has once again abruptly led me down a weird rabbit hole of screaming at salvage-by-weight.
Since we've since decided to fudge the numbers for small underwear items and just let them be uncrafted into full rags, I added uncrafts for all plastic containers to convert them into a given number of plastic chunks (or scrap in the case of small bottles).
1. Going the full suffering route and bumping the weights for all plastic bottles to heavier values that will translate into a reasonable number of scraps.
2. Making it so plastic material salvages into plastic scrap instead and using that in recipes more.
3. Making plastic chunks smol.
4. Reverting https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2142 because jfc why does it constantly cause me so …
=> fix: uncrafts for lightweight plastic containers

data/mods/Magiclysm/modinfo.json
I'm not actually maintaining or updating Magiclysm anymore.
Removes myself from the list of maintainers in the modinfo file, replaces it with "none"
- PR'ing moving Magical Nights in-repo
Not _**yet**_. But later, perhaps ;3
N/A
I'd strongly suggest people interested in updated content that's actually getting maintained check out Magical Nights instead.
=> chore(mods/magiclysm): Remove myself as Magiclysm Maintainer

src/npc.h, src/npcmove.cpp
One of the PR ported for #3073.
Source PR: Performance: Cache NPC goal, by @dseguin: https://github.com/CleverRaven/Cataclysm-DDA/pull/54312
=> perf(port): cache NPC goal

data/json/furniture_and_terrain/furniture-domestic_plants.json
As pointed out by a member of the Discord, it's a *little* confusing how "Mature" plants aren't actually ready to harvest yet. Thus, this change is for clarity and to make it perfectly clear that it's not yet harvestable
Changed "Mature" to "Maturing" in the JSON file containing the single furniture id that every plant secretly points to when in the mature stage (and also changed the one for plants in planters too of course)
- Flowering
Considering how this name change would affect **every** plant, not sensible. Would work decently well if we ever rework the plants system for some reason though.
Checked to make sure the game didn't yell at me, and that it indeed does what it should. Should be auto-linted since I moved to VSCode where I can use the plugin.
Change suggested by Cürt in the …
=> fix: Changed 'Mature Plant' to 'Maturing Plant'

data/json/requirements/uncraft.json
So I could've sworn I nerfed MREs to not yield half a dozen purification tablets due to how much more effective they are. Turns out, in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3297 I edited the `mre_accessory` uncraft...which was long ago obsoleted, MREs actually produce their accessories via the `mre_accessory_list` CRAFTING REQUIREMENT instead. Auuuugh.
Toned down number of tablets given by `mre_accessory_list` from 6 to 1, like I tried and failed to do already, derp. It still goes from "meant to make 1.5 liters of water" to 2 liters worth, 6 liters from a single MRE meanwhile is not intended yield. :3
screm
2. Ported JSON change to playthrough build, confirmed taking apart an MRE ACTUALLY only yields a single tablet now. …
=> fix: mre actually gives 1 pur tablet this time

src/activity_handlers.cpp, src/cata_tiles.cpp, src/handle_action.cpp, src/item.cpp, src/map.cpp
This change aims to make it so you can pulp dead feral humans to keep them from reviving like you would with regular zombies, instead of the only option being to butcher them (or wait for them to revive, kill their zombie form, them pulp that).
WIP because I'm out and about on laptop currently, will test then mark as ready when I get home.
1. In activity_handlers.cpp, set it so `activity_handlers::pulp_do_turn` treats coprses with `zombify_into` as valid to pulp.
2. In cata_tiles.cpp, set `cata_tiles::draw_zombie_revival_indicators` to also check for unpulped monsters with `zombify_into` set for the sake of displaying the "stuff that should be pulped" indicator. Nested in a check for is_corpse to avoid potential access violation shenanigans I encountered during initial testing.
3. In …
=> feat(balance): allow pulping `zombify_into` corpses

src/iuse_actor.cpp, src/monster.cpp
Just as a deployable monster's damage condition is saved in its item form and vice versa, a fun lil idea I had was for deployable bots to have their nicknames saved via the item label for their inactive form.
1. In iuse_actor.cpp, changed `place_monster_iuse::use` so that it checks whether the item in question was labeled, and if so assigns it as the deployed monster's nickname.
2. Conversely, in monster.cpp set `monster::to_item` so that it checks whether the monster has a unique_name, and if so assigns it to the item being created as a label.
Adding the monster nickname to `monster::init_from_item` would also work, but it would enable nicknaming zombies by carving their name on the corpse. Dunno if that'd be considered desirable or not.
2. Spawned in and …
=> feat: item label can save deployable robot nicknames

data/json/furniture_and_terrain/terrain-walls.json
This is in parallel with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4219, while that finishes up adding ranged bash info to doors and other stuff that had ranged bash info partially implemented, this sets aside the addition of ranged data to solid walls.
1. Added ranged info to all non-transparent items in terrain-walls.json. Transparent stuff (i.e. half-built and damaged walls) meanwhile are covered by the above PR.
2. Also bumped up `str_max` of finished columns to match that of half-built ones, so the destroy thresh of its ranged info won't be higher than its max bash resist.
3. Likewise bumped `str_max` of concrete supports to match that of simple concrete walls, in between little and large concrete columns, for the same reason.
screm
1. First, tested firing a composite …
=> feat(balance): ranged bash info for solid walls

data/json/furniture_and_terrain/furniture-plumbing.json, data/json/furniture_and_terrain/furniture-triffid.json, data/json/furniture_and_terrain/terrain-doors.json, data/json/furniture_and_terrain/terrain-walls.json, data/json/furniture_and_terrain/terrain-windows.json
This finally applies ranged bash info to the remaining doors and windows that already had `ranged` data partially in use.
1. Belatedly added ranged data to triffid furniture that was added while the original implementation of furniture ranged bash info was being worked on.
2. Finally gave all the variations on closed doors ranged bash info instead of only the basic ones having it, derp.
3. Fixed one case of mistakening giving an open door ranged data.
4. Gave ranged bashed info to all other transparent walls that lacked this, the rest will come next PR.
5. Misc: gave half-built columns a coverage value.
6. Updated windows with some missing ranged data.
7. Important: I learned that for some reason bash info isn't fully overriden when specified. Windows seem to be deliberately using this to …
=> feat(balance): finish extending ranged bash info to windows, doors, and other half-implemented terrain; some window fixes

src/map.cpp
Fix a case of nullpointer fuckery causing random crashes. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4236
In map.cpp, set `map::smash_items` so the part of the check that looks for `zombify_into` is properly nested behind an `is_corpse` check, to avoid the risk that `get_mtype` will implode over something that won't have it.
Screaming.
2. Spawned in a bunch of steel targets and shot the fuck out of them with a barret, no crashes so far.
3. Spawned in a road roller and rammed it at highway speed into a lone of hay bales, no crashes.
4. Ran over some NPCs, ran over generated human corpses, and shot a target spot with a corpse on it with both a barret and an mk19, no crashes so far.
5. Dropped C-4 and a mininuke on a NPCs and their bodies, also …
=> fix: quickfix for bash-related crashes

data/json/itemgroups/Locations_MapExtras/locations.json, data/json/mapgen/ws_survivor_bunker.json, data/json/monstergroups/zombies.json
Remove the root walls from the survivor's bunker, because this terrain should logically only be found in the Triffid grove.
Remove root walls from `ws_survivor_bunker_f-1`.
Also moved "monstergroup" and "item_group" in ws_survivor_bunker.json to the appropriate JSON file.
none
Before:
After:
=> fix: remove root wall from survivor bunker

data/json/recipes/armor/head.json, data/json/requirements/materials.json
Add makeshift bandage types to blindfold recipe via a requirement group as no reason they cannot be used for a blindfold.
- Create requirement group bandages_all which has bandages, makeshift bandages, boiled makeshift bandages and bleached makeshift bandages in
- Add requirement group to blindfold recipe
Leaving blindfold recipe alone.
Loaded into base game and tested.
=> feat(content): Add all bandage types to blindfold recipe

data/json/mapgen/ws_survivor_bunker.json
Fix because it's the trap that's used, not the terrain.
Use "t_pit_spiked" terrain instead of "tr_spike_pit" trap.
none
Before:
After:
=> fix: spiked pit on surface of survivor's bunker

src/activity_item_handling.cpp
Fix segfault introduced in ba60edc05225 when attempting to make a farmplot zone of "No Seed" and then trying to farm said plot using automatic actions via "O"->"m".
- fix #4243 
Check for valid seed object before referencing it.
Repro'd the crash based on instructions in bug ticket #4243   on top of 0b5331a03 by following ticket repro steps. Tested fix by following same steps and seeing that character can now plow the farm field just fine.
=> fix: check for valid seed before reference in `can_do_activity_there()`

data/json/recipes/chem/chemicals.json, data/json/recipes/chem/other.json, data/json/recipes/other/materials.json
This implements some tweaks to how match head powder is make to make it less clunky to use, along with some related changes to some other mortar and pestle recipes once I noticed that a few of the recipes to use mortar and pestle lack batch time savings when most have it.
1. Set match head powder recipe to make 1 charge at a time, per 1 matchbook charge consumed. This makes it more granular, though more efficient as a side effect. Given match head powder isn't used for much besides primers (and are used en masse in that case) I feel it's not too wacky balance-wise. Time taken also reduced from 8 minutes to 1 minute, and to compensate for this increase in time per unit made it now uses the same batch time factor most other mortar and pestle recipes use.
2. Misc: Gave the ammonium nitrate …
=> feat(balance): make matchhead powder recipe more granular, related fixes for mortar and pestle recipes

data/json/effects.json, data/json/monsters/nether.json, src/monmove.cpp
This finally implements some sanity-checking of shoggoth item absorption and splitting behavior so they won't be as much of a menace to society.
C++ changes:
1. In monmove.cpp, changed `monster::move` so `ABSORBS_SPLITS` behavior gets a bit of sanity-checking. It now only does the split if it lacks a new status effect that's doled out to both monsters on a successful split, effectively implementing a cooldown on absorbing items. Splitting now also takes a bit out of both monsters, meaning some potential future items absorbed go into recovering from this loss of HP (until regen kicks back in, see below). They'll still absorb items to stockpile HP up to a point however, if they're still recovering from splitting they'll stop absorbing items once they're at 3 times max HP.
JSON changes:
1. …
=> fix: add limits and side effects to `ABSORBS_SPLITS` behavior

data/json/items/gunmod/rail.json, doc/src/content/docs/en/mod/json/reference/json_info.md, src/item.cpp, src/item_factory.cpp, src/iteminfo_query.h, src/itype.h
- Expansion of #2541 
Allow further fine-tuning of what guns can and cannot be installed with specific gunmods, both for further development and specificity of vanilla gunmods and for the use of mod authors.
Adds `mod_exclusions` and `mod_exclusion_category` as optional fields in gunmods. This allows contributors to add specific blacklists (say you want to make a gun mod installable on all rifles _except_ the Rivtech battlerifle for instance), and blacklist categories (all rifles unless they are energy weapons).
Blacklists take priority over target categories _but not target ids_. Priority for inclusion/exclusion goes `mod_targets` > `mod_exclusions` > `mod_exclusion_category` > `mod_target_category`
Note that it _will_ scream at you if you try to include and exclude the same id or the …
=> feat: Add exclusions and exclusion categories to gunmods

src/ranged.cpp
This PR addresses the issue of not being able to switch firing mode when using birdshot with double barreled shotgun.
With this change, when in TargetMode::Shape and actually using a gun, the firing UI will:
- show the current firing mode
- provide hotkey for switching firing modes
Fixes #4071 
Players can now switch firing modes from the shooting/firing menu when using a gun that fires in a 'shape' / area of effect.
Made character with double barreled shotgun. Tries this change with both birdshot and buckshot to see that double firing mode can be changed in the shooting ui and that it actually shoots both barrels. Buckshot shooting seems to work the same.
=> fix: enable display and switch of firing mode for shape targetmode

data/json/mapgen/house/bungalow28.json, data/json/mapgen/nested/residential_lawn_nested.json
Add nested chunks for residential front lawn features. This will make for more dynamic,  more interesting house spawns.
Create nest container for residential front lawns. Currently there are only 2 variants, to make it easier to review. More will be coming in the future. Using this nest container will make it easy to add more variants down the road without updating individual house files, and also control global spawn rates of variants.
Not adding these and letting houses be more stagnant.
linted file and spawned both variants in-game.
These two chunk variants aren't overly exciting on their own, but with more variants added, I think this could be more interesting overall than having set map features for specific houses.
=> feat: residential front lawn nested chunks

data/json/mapgen/house/bungalow27.json, data/json/mapgen/nested/residential_lawn_nested.json
Add residential backyard chunks to add dynamic lawn features to domestic backyards
Added Nest Container for residential backyards, which is what should be called by each individual house spawn. In the future additional chunk variants can be added to this nest container easily, which should be reflected in each house that calls this nested chunk without having to update each house individually.
----
linted and spawned each chunk variant in game.
There are only 2 variants at the moment, more to be added later. 
NOTE: my previous PR for adding front lawn chunks has already been merged, but that isn't reflected in this PR as it has not been published in a public build as of yet. That's why it looks like the residential lawn chunks file has both the front lawn and the backyard chunks. …
=> feat: residential backyard chunks

src/creature_tracker.cpp, src/creature_tracker.h, src/iuse.cpp, src/monster.cpp, src/monster.h
The reason for this PR is me hitting the following error message in the debug build as explained in the respective task when trying to tame a pet: "ERROR: the chicken tried to find faction player which wasn't loaded in game::monmove"
Fixes #4284 
Digging into it, it seems that once the animal gets tamed with food, it's never moved to the 'player' faction set of `Creature_tracker::monster_faction_map_` and then we hit the error in `monster::plan()` in `monmove.cpp`.
What this change does is move the existing code that 'makes the animal a pet' into a new method, `monster::make_pet()`, akin to similar functions in that class. It also introduces a helper function in creature_tracker layer that allows us to notify that layer that there has been a change in the faction that this monster belongs …
=> fix: move tamed pet to proper faction set in creature_tracker layer

data/json/mapgen/house/house_dogs.json
Make the victim clothes damaged, because logically if this person has been killed by dogs his clothes shouldn't be undamaged.
"damage": [ 1, 4 ] for all clothing and "damage": 3 for the body in `dogfight` `item_group`.
none
Before:
After:
=> fix: damage the clothes of the `house_dogs` dog fight victim

tests/ranged_balance_test.cpp
the tests are very flaky, and [fails unrelated PRs without much benefits](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/8125019849/job/22207142965?pr=4286#step:14:1917).
for the time being, it'd make more sense to ignore its failure.
https://github.com/catchorg/Catch2/blob/devel/docs/test-cases-and-sections.md#special-tags
mark `unskilled_shooter_accuracy` as `[!mayfail]`.
- mark all other ranged balance tests as flaky
should work as it effectively removes tests
=> test: ignore flaky ranged balance test

src/monster.cpp
Players usually tame wildlife that can be considered 'farm-animals'. It's tedious to require the player to keep taming offspring of the animals they have already tamed in the first place so this change addresses that. Mostly meant as QoL change for farm players.
This change is meant as a simple QoL improvement, mostly aimed at farm players. It makes is so that wildlife mammals that have been tamed and are friendly to the player produce equally friendly offspring that doesn't need to also be tamed with food as that's tedious.
This change works well alongside generic culling process that already exists for pets: 8c4263185e419725de24aba24b8100a6086717a4
Fix is really easy for mammals. Just check if parent monster is wildlife creature + friendly to player and then make offspring inherit their …
=> feat: friendly wildlife mammals spawn friendly offspring

Makefile, src/catalua_luna_doc.h
This attempts to fix the mingw windows builds. It's 2 different fixes for 32 and 64 bit and I'm not sure either will work. Note it's the mingw builds I'm looking at here rather than the translation problems affecting the msvc build.
The 32 bit fix gets rid of size_t from the lua doc because it's internally the same type as unsigned int and so conflicted. The 64 bit fix adds "-Wa,-mbig-obj" to the build flags so it won't complain that the output is too big.
None, I don't have a windows machine. I'm hoping to test it in the pipeline.
=> fix: mingw builds

data/json/flags.json, src/flag.cpp, src/flag.h, src/map.cpp, src/monster.cpp
It's tedious to require the player to keep taming offspring of the animals they have already tamed in the first place so this change addresses that, especially for chickens who multiply aggressively! Mostly meant as QoL change for farm players.
This change is meant as a simple QoL improvement, mostly aimed at farm players. It's a continuation of the work in 729b2b55e5e7b1721970bbe11606cf2cee1491f7 and addresses the tamed wildlife that reproduces by laying eggs.
This change works well alongside generic culling process that already exists for pets: https://github.com/cataclysmbnteam/Cataclysm-BN/commit/8c4263185e419725de24aba24b8100a6086717a4
Solution works by introducing a new flag that gets attached to the egg on the condition that the parent is friendly to the player + is wildlife …
=> feat: eggs from friendly wildlife critters spawn friendly offspring

src/avatar_action.cpp
Without this fix having an empty underbarrel mod/gun like the grenade launcher prevents the player from activating the firing ui via 'f'. This is especially troublesome as most players, including myself, only know how to change firing modes via this UI. This effectively prevents players from switching firing mode to the main weapon.
This change allows the player to activate firing mode UI via 'f' in the case where the underslung gun/mod is out of ammo but the main gun still has ammo. This is especially confusing for most players as they are used to changing firing modes from this UI only.
Fixes #3966 
Solution simply checks if any of the gun modes of the current weapon ca be fired at the moment, not just the 'currently selected one'.
Spawn character with m4 carbine and m320 grenade …
=> fix: empty underslung gun doesnt prevent going into firing mode UI

src/item.cpp
- fix #4275
Truthiness of a std::optional will always evaluate to true if the optional is not null. Need to check if DT_ACID/DT_HEAT exist in the optional instead.
Feet melting off, idk
Changed ANBC armor json to have some funny numbers and some normal ones, loaded game:
Spot checked armors that weren't overridden, they looked fine.
ow my feat
=> fix: heat and acid armor work

Makefile
followup of #4290
rename `OTHER` variable to `OTHERS`
cry
will test in `main` CI
https://digitalkarabela.com/mingw-w64-how-to-fix-file-too-big-too-many-sections/
=> fix: `OTHERS` typo in mingw build

.github/workflows/release.yml
- fix #4276 
ported https://github.com/CleverRaven/Cataclysm-DDA/pull/72031/commits by @akrieger.
- migrate MSVC distribution fully to cmake
- also install python3
https://github.com/scarf005/Cataclysm-BN/actions/runs/8141808018/job/22249927779
run succeeded in fork.
@SurFlurer helped finding fixes in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4276#issuecomment-1976245174.
=> ci: fix lang file compilation in windows msvc

src/item.cpp
fix #4302 
Items that are categorized as armor but don't have defined resistances will crash the game upon view. 
This was previously crash safe because we were using a null check, but the behavior was wrong. Added the null check back.
letting chaos scream and cry
Loaded up game, scrolled through entire debug spawner for items, no crash. Item resistance values look fine.
Not a fix for INT_MIN physical resistance on some smaller items; I can't reproduce that issue on windows.
=> fix: crashing when viewing armor item with undefined resitances

data/json/mapgen/refugee_center/refugee_center.json, data/json/monstergroups/zombies.json
currently, the monsters which spawn in in the refugee center are from the group `GROUP_MALL`. this is not normally a problem, until multiple mod interactions cause unintended and extra monsters to spawn for this quest.
creates a new monster group, `GROUP_REFUGEE_CENTER_BACK_ROOM` which controls which monsters will spawn
👍
=> fix: Refugee center back room monster group

.github/workflows/autofix.yml
prevent me from ping DDOSd by bot
- simplify autofix message
- remove '@scarf005' which pings me
cry
=> ci: simplify autofix message

data/json/recipes/food/other.json, data/json/requirements/materials.json, data/json/requirements/tailoring.json, data/json/vehicleparts/alternator.json, data/json/vehicleparts/battery.json, data/json/vehicleparts/boards.json, data/json/vehicleparts/cargo.json, data/json/vehicleparts/combustion.json, data/json/vehicleparts/doors.json, data/json/vehicleparts/engineering.json, data/json/vehicleparts/frames.json, data/json/vehicleparts/lights.json, data/json/vehicleparts/manual.json, data/json/vehicleparts/mirrors.json, data/json/vehicleparts/motor.json, data/json/vehicleparts/rams.json, data/json/vehicleparts/rotor.json, data/json/vehicleparts/seats.json, data/json/vehicleparts/tanks.json, data/json/vehicleparts/utilities.json, data/json/vehicleparts/vehicle_parts.json, data/json/vehicleparts/wheel.json, data/json/vehicleparts/windshields.json, tests/vehicle_interact_test.cpp
This finally implements a lil something I had on the backburner for a while: making more vehicle repairs have a material cost associated with them. Reasoning being:
1. It's already consistent with the item forms of items needing materials to repair.
2. Several vehicleparts like solar panels, tires, and the like already have a material cost to repair.
3. Game-balance wise, once you have a welding rig and enough solar panels repairing your vehicle is 90% completely free. It's not much since so far all the material costs I had in mind are easy enough to get, but it will at least mean deathmobile mains have to actually leave their vehicle every so often if they're doing repairs a lot.
1. Defined a crafting requirements: `vehicle_repair_electronics`, for general material cost of generic …
=> feat(balance): more vehicle repairs besides tires and solar panels require materials now

data/json/mapgen/house/house_fence09.json, data/json/mapgen/nested/roof_nested.json
Making roofs of residences a tiny bit more dynamic by introducing residential roof chunks. These nested chunks will be any sort of scenes/items you might find on a residential roof. I'd like there to be just a little higher chance of finding a surprise on a rooftop, and to hint at life in the game outside of whatever the player is up to.
Create the Nested Chunk container for residential roof chunks. I've only added 2 variants at the moment (one spawns a frisbee and baseball, the other a couple of crows perching on the roof) for the moment to make this easier to review. In the future I'd like to add more variants, maybe including some enemy spawns that would make sense (any flying or leaping creatures) as well as some loot (if the player is climbing rooftops to escape monsters, other …
=> feat(content): add residential roof chunks and one new residential roof solar variant

data/json/mapgen/shelter.json, doc/src/content/docs/en/mod/json/reference/items/item_spawn.md, src/item_factory.cpp, src/item_group.cpp, src/item_group.h, src/map.cpp, src/mapgen.cpp
- wanted to prevent header modification in #4266 as it triggered ~300 file rebuilds.
cherry-picked solutions from #4073 and #4266:
- for individual items: inlined `map::spawn_item` in `src/mapgen.cpp` and replaced with `map::spawn_an_item` as it allows passing item ptr (so we can activate it first)
- ~~for item groups: sent `ACTIVATE_ON_PLACE` flag to `Item_modifier.custom_flags` in `src/item_factory.cpp` and checked its presence in `src/item_group.cpp`.~~
- added `postprocess_fns: vector<detached_ptr -> detached_ptr>` field in `Item_modifier` class that lets you postprocess spawned item in [Command pattern](https://gameprogrammingpatterns.com/command.html).
- unify item and item groups spawning by spawning single items via item groups
- spawned grenades on top of shelter, one via …
=> feat: spawn active items on mapgen

src/character.cpp
riding horse should be fast.
- <https://gall.dcinside.com/board/view/?id=rlike&no=456342>
use mounted animal's speed instead when mounted.
also take overburden or other stuff into account but was lazy.
1. spawn `horse`, `cattle fodder`, `horse tack`
2. ride on horse
3. speed is now 300
4. dismount from horse
5. speed is now 100
=> feat: use mount's speed when mounted

src/editmap.cpp, src/map.cpp, src/map.h, src/mapgen.cpp, src/monster.cpp, src/monster.h, src/savegame_json.cpp, src/submap.h
So far map::add_spawn() and the underlying spawn_point struct have been operating on the binary notion that a spawn can be friendly or not. This PR extends those APIs to also support generating monsters that are pets of the player, while also honoring backwards compatibility with parts of the codebase that still want to operate on the binary friendly notion, such as the save/load system for submaps.
This is a followup to previous PRs (#4287, #4289) that made it possible for friendly wildlife creatures to spawn friendly offspring, mostly as a QoL improvement for farm players. As chaosvolt point out, this ended up creating friendly offspring, not pets. Hence several functions such as slaughter, milk, etc were still not allowed for friendly offspring - the player has to manually tame the …
=> feat: extend `add_spawn()` to handle creating pets

src/debug_menu.cpp, src/monster.cpp, src/monster.h
Extends the map submenu of the debug menu with an option to force monsters in a rectangular area to reproduce.
cow goes moo, sheep goes bah
Purpose is to ease debugging of hard-to-reproduce corner-cases such as what happens when a monster reproduces and spawns offspring.
Solution works by extending map sub menu of debug menu with an option to force all monsters in an area to reproduce. This can actually be triggered multiple times in the row in order to quickly create a huge flock of creatures out of a specific parent. The forcing of reproduction works by splitting try_reproduce into 2 parts, try() and actual reproduce()
Note that the solution does not cause eggs to hatch as that is based on the rot-timer functionality which is in a different part of the codebase altogether. TODO for …
=> feat: add reproduce area options in debug-map menu

src/debug_menu.cpp
make it easier to erase large number of items, e.g for perf reasons.
choose rectangular area, iterate through points and erase items.
make item merging easier.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/366fad32-fd06-4ba6-8180-75805c2a0e20
1. select `debug/map/erase items in area`.
2. select grid.
3. items are erased.
=> feat: erase items in area

src/monster.cpp
This is a fix for the corner-case where a monster that lays eggs is forced to reproduce via the debug menu. In such a case, the age of the spawned egg would be negative as the birth-timer points to a point in time in the future for the next valid reprouce check of the monster.
In this corner-case, we just use the current-turn timestamp for the newly spawned egg.
Fix negative egg item age bug introduced when using debug menu to force egg-laying animal (e.g. chicken) top reproduce.
Only use birth timer if it points to now or the past, otherwise use current timestamp.
spawn chicken
force chicken to lay egg - check its age
go far away and come back so submap gets reloaded
force previous chicken to lay egg - check its age
=> fix: dont spawn eggs with negative age values

src/game.cpp
Porting fix from cdda, original PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/47717
Issue is when player tries to move into a spot where a pet is and displace it but the originating position is not a position that the pet can move to. e.g. if you move from chicken fence to tile in the coop containing a pet chicken.
check result of critter.move_to() before actually moving player and making them disappear under the same tile as chicken. In that case we return the original position of player back so they dont move.
character climbs chicken fence. tries to move to tile with friendly chicken. with this patch, that should fail and you get proper error message. without the patch, character disappears under chicken which can then lead to crashes if there's another chicken in the next tile …
=> fix(port): Do not move into monsters that we cannot displace

build-scripts/mod_test_blacklist
1. the mod overrides many things such as palettes.
2. due to this, it causes countless test failures (like in #4312)
3. we lack staff to maintain it.
ignore `no_hope` from testing for the time being.
extract the mod into third-party mod (`cataclysmbn/no_hope`)?
=> test: add `no_hope` to mod test blocklist

data/json/vehicleparts/armor.json, data/json/vehicleparts/vp_flags.json, src/vehicle.cpp
Add the SHOCK_ABSORBER flag to shock absorbers, and change vehicle::damage_all() so that parts on the same tile as a shock absorber take substantially less damage from transmitted shock damage in collisions.
Ports CleverRaven/Cataclysm-DDA#43013
Vehicles generally take a lot of damage internally from collisions, this modifies the shock absorber part to provide a buffer on individual tiles.
Port change.
Reducing collision damage across the board?
Spawned a solar car, welded a shock absorber onto one of the solar panel tiles, smashed the car into a radio tower repeatedly. Most of the panel in the back of the car were badly damaged or destroyed, the tile with the shock absorber was fine. 
This implementation is somewhat limited, only a tile with a shock absorber installed receives any …
=> fix(port): make shock absorbers actually absorb shock damage

src/cached_item_options.cpp, src/cached_item_options.h, src/item.cpp, src/options.cpp, tests/item_test.cpp
- improve QOL by allowing 10h and 11h old pancakes to stack
- improve performance a tiny bit by not having 123 kinds of slightly different food around
- Added option group to configure comestible merging.
- the new stacking strategy is enabled by default.
- you can rollback to previous strategy via setting it `legacy`
- ~~by default, only comestibles that's up to 75% fresh can be merged (tweakable)~~
- by default, comestibles that has up to 25% similar freshness can be merged (tweakable)
- On item merging, the rot is set to weighted average of their rotness and charges
- mixing small fresh food with huge amount of near rotten food won't make it much fresher and vice versa
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2e755378-e5b7-46ed-81f9-cb0f95a6a0e6 …
=> feat: stack comestibles regardless of rot

src/monmove.cpp
THe root-cause for pets always following player regardless of MF_PET_WONT_FOLLOW flag was found in move_scent() which caused non fleeing creatures to gravitate towards the scent of the player, ignoring the wont-follow flag.
Fixes #4331
This is a fix for the bug where pets with WONT_FOLLOW flag actually end up following the player anyway.
The rootcause lied in move_scent() which makes non fleeing pets follow the scent of the player, thus ignoring the WONT_FOLLOW flag. The fix works by making monsters ignore the player's scent if the monsters:
- are not fleeing
- are pets
- have the PET_WONT_FOLLOW flag
Other than that specific corner-case, smell-based mechanics remain unaffected for monsters.
I don't think this is fixed in cdda as far as I cant tell so no fix to copy from there. I …
=> fix: pets with `MF_PET_WONT_FOLLOW` flag don't follow player

data/json/flags.json, src/item.cpp
This implements a lil streamlining of some item UI stuff.
C++ changes:
1. In item.cpp, removed the special bit in `item::basic_info` that places a description for the `MAGIC_FOCUS` flag directly above the item's description, as this is almost never actually important enough to be given such prominant placement.
2. Meanwhile, moved the check for notes inscribed on items out of `item::final_info` and into `item::basic_info` immediately below the item's basic description. This places it where you'd expect flavor text of this sort to be instead of being way down in its own dedicated section, separated by horizontal rules.
JSON changes:
1. Gave the `MAGIC_FOCUS` flag its orignal hardcoded text as its flag description.
Keeping item incriptions isolated by separators but still move them to …
=> feat(UI): move item notes to be with description, move `MAGIC_FOCUS` flag description to flag section

src/activity_handlers.h, src/activity_item_handling.cpp
Warn players if it's too cold to plant seeds via farming zone activity.
- Fixes #3963
Return unique error code if it's too cold to plant a seed and display meaningful error message in this corner-case.
Does not seem to be fixed in cdda after casually perusing their codebase so nothing to port.
in spring.
* character has seeds and shovel.
* create farming zone.
* try to farm via zone activity.
* character churns the earth.
* character fails to plant seeds.
* appropriate error message is displayed.
=> fix(UI): farming zone activity warns if it is too cold

.github/workflows/android.yml, .github/workflows/autofix.yml, .github/workflows/clang-tidy.yml, .github/workflows/documentation.yml, .github/workflows/i18n-extraction.yml, .github/workflows/i18n-printf-format.yml, .github/workflows/manual-release.yml, .github/workflows/matrix.yml, .github/workflows/msvc-full-features-cmake.yml, .github/workflows/msvc-full-features.yml, .github/workflows/msys2-cmake.yml, .github/workflows/msys2.yml, .github/workflows/pull-translations.yml, .github/workflows/push-translation-template.yml, .github/workflows/release.yml
bump outdated actions. fixes:
- node16 deprecation warning
- set-output deprecation warning
- https://github.com/actions/create-release -> https://github.com/softprops/action-gh-release (deprecated)
- https://github.com/actions/upload-release-asset -> https://github.com/shogo82148/actions-upload-release-asset (deprecated)
- everything else: bumped to latest version
get spammed with deprecation warning
[works in fork.](https://github.com/scarf005/Cataclysm-BN/actions/runs/8266883425) (androids fail due to missing gnupg keyring)
https://github.com/scarf005/Cataclysm-BN/releases/tag/2024-03-12
=> ci: bump outdated actions

data/json/items/tool/cooking.json
A review from the future after I'd already merged https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4348 pointed out a good idea.
And then I spotted some obvious mistakes in the old jar of yeast items so this turned into some general fixes.
1. Defined weight and volume for jar version. Went with weight matching volume since the flash version does that.
2. Set the wild yeast item to copy from the jar version instead since it yields a jar when activated.
3. Updated names to indicate size.
4. Moved the 3-liter version up to where the others are and converted it to use copy-from.
5. Updated the time requirements for larger batches. The jars take twice as long as the flask while the 3-liter jar takes the same amount of time the wild yeast uses (which is 6 times that of a flask). Also have …
=> fix: use `copy-from` for large yeast jars, general fixes to yeast cultures

src/armor_layers.cpp
- fixes #2743
- fixes #4353
Fix crash when equipping armor to npc with no clothing.
Crash due to accessing index 0 of empty std::vector. Skip accessing that vector in that corner-case. 
Relevant backtrace
```
#0  operator() (__closure=0x7fffffffc4a0, index=0) at /home/gpf/gamedev/Cataclysm-BN/src/armor_layers.cpp:498
#1  0x00005555557180c9 in show_armor_layers_ui (who=...) at /home/gpf/gamedev/Cataclysm-BN/src/armor_layers.cpp:889
#2  0x000055555661c1b7 in game::npc_menu (this=this@entry=0x555558b3c190, who=...) at /home/gpf/gamedev/Cataclysm-BN/src/game.cpp:5383
#3  0x000055555661cded in game::examine (this=this@entry=0x555558b3c190, examp=...) at /home/gpf/gamedev/Cataclysm-BN/src/game.cpp:5534
#4  0x000055555661e0f3 in game::examine (this=this@entry=0x555558b3c190) at …
```
=> fix: dont crash when equipping npc with no existing clothing

.github/workflows/release.yml
fix experimental releases having 'no changelog' despite having commits
explicitly give tag range
https://github.com/scarf005/Cataclysm-BN/actions/runs/8308252005/job/22738302800#step:5:41
worked in fork.
=> ci: use explicit tag range on changelog generation

data/json/items/vehicle/wheel.json, data/json/vehicleparts/wheel.json, tests/vehicle_efficiency_test.cpp
The 32' armored wheel looks like so: 
It is off-road.
It's also the best wheel the base game has to offer for your typical mobile base. It's difficult to find, difficult to take off and difficult to install. 
Changing the type from normal to off-road.
A mod. I have a mod doing it, but it makes sense for this to be in the base game.
Drive a vehicle with 32' armored wheels on rough terrain and compare the max speed/acceleration.
=> feat(content): the armored wheel is now off-road

src/game_inventory.cpp
- fix #4146
on max skill, print output in brown.
none.
=> fix(UI): do not hide skills from books on max skill

data/json/items/classes/gun.json
The energy gatling weapon class now specifies its weapon mods, removing the brass catcher weapon mod carried over as part of the copy-from for the base gatling weapon class.
The rebuilt CMS gatling laser had a brass catcher weapon mod slot, a nonsensical option for an energy weapon that might cause problems if used. Looking down the line of 'copy-from's, it turned out that the energy gatling weapon class copies most of its data, including weapon mods, from the regular gatling weapon class, which included a brass catcher weapon mod slot.
The energy gatling weapon class now specifies its own weapon mods, containing every weapon mod slot the ballistic gatling weapon class had save for the brass catcher.
I tested the edit ingame, the effected weapons no longer have brass catchers, nor did I …
=> fix: energy gatling weapon class weapon mod slot fix

src/vehicle_part.cpp
- fixes #4012 
make count-by-charges vehicleparts invincible.
make a proper damage system for CBC items, but this hack works...
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/d524074c-d100-4e6b-8876-cfb356987e97
1. spawn a car.
2. uninstall seatbelt.
3. the seatbelt item is correctly dropped.
- wanted to also write a test for it but can't figure out which API to use.
- with this fix maybe we could continue #3489?
- we also need a recipe for seatbelt.
=> fix: make count-by-charges vehiclepart installable

src/game.cpp
- fix #4022
on loading player character, reset its `cached_dead_state`.
1. kill yourself.
2. load another character in other world.
3. check that the character is alive.
=> fix: dead state persisting between worlds

data/json/items/chemicals_and_resources.json, data/json/items/comestibles/other.json, tests/comestible_test.cpp, tests/test_statistics.h
- automate calories testing more
- prevent #4317 from happening again
- make it easier to see why the test failed
- fix item stats accordingly
- `data/json/items/chemicals_and_resources.json`, `data/json/items/comestibles/other.json`: overriden item stats to pass the test.
- `tests/test_statistics.h`: applied clang-tidy suggestions.
- `tests/comestible_test.cpp`:
- improved error output to show ingredients and result item on error.
- made it not skip calories check when there's only one recipe.
- forbidden non-drink comestibles to have zero calories (always has to be overriden).
also output min and max kcal for each components, but it gets more complicated. might worth a followup PR.
example test output:
```
FAILED:
CHECK( mystats.calories.min() > 0 )
with expansion:
-333 > 0
with …
```
=> test: check negative calories

.github/workflows/manual-release.yml
fix manual release having no MSVC releases (like in [`v0.6.0`](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/v0.6.0))
same as #4298.
unify experimental and manual release together.
should work in CI.
https://github.com/scarf005/Cataclysm-BN/actions/runs/8370243414
=> ci: fix lang file compilation in manual release

data/json/items/melee/bludgeons.json
Tactical Tonfa (off) did not have the BELT_CLIP flag like other tonfas and its own (on) version. 
Added the missing flag and then reformatted the (on) version so it would just add its new flags to the base when turned on instead of overwriting them. Also changed a difference in the description of the two modes so they match.
Tactical Tonfa (off) could have the intended flags by just inheriting the flags of the copyfrom and adding NONCONDUCTIVE using the "extend" command.
Tactical Tonfa (on)'s formatting could have been left unchanged and it would still have the correct flags, the actual belt clip flag bug only concerned Tactical Tonfa (off).
Tested by downloading the modified bludgeons.json and running it.
=> fix: Tactical Tonfa (off) didn't clip to belts

src/item.cpp
make it easier to debug flags.
also show itype's flags.
just unify all flags into one?
1. turn on debug mode (F12)
2. examine an item.
3. itype's flag is also displayed.
=> feat(UI): display flags in debug mode

src/character_effects.cpp
Focus was always a very game slowing affair, gaining focus was too slow, loosing focus was always a big problem. A fast paced game like BN should not have such penalties on focus.
1. No more focus-loss while reading books.
2. boosted focus gain after crafting/fighting loss
Remove Focus all together (that would be a huge change, so this is a step in between).
Remove Focus loss on combat (would also make sense, but Apex would loose a huge advantage in combat skill gain.
5 Minute of wait on Focus:
only 1 point gained in 5 minutes.
already gain of 10 focus points in 5 minutes.
=> feat(balance): increase focus gain by 10x, remove read focus penalty

data/json/recipes/other/traps.json, data/json/uncraft/weapon/explosive.json
fix #4381
To fix land mine component inconsistencies in regard to real life land mines and other explosives within the game. For more issue see #4381. To fully address the issue land mines still need to be divided into real world or fictional models, but this requires the land mine trap effect to be moved from an hardcoded effect to something that can be modified by JSON. 
Introduces my changes to the crafting and uncrafting recipes for land mines mentioned in #4381. For crafting I added bone glue, changed the fragmentation element to be the same as the scrap loaded 00 shot recipe just 10x to be in line with what it was before, got rid of all that random nonsense that were useable as explosive and instead used the same lists as other explosives used equivalent in amount to 600 composition …
=> fix(balance): Recipe changes to address land mine component inconsistencies

data/json/ammo_effects.json, data/json/ammo_effects_simple.json, data/json/flags.json, data/json/items/ranged/throwing.json, src/creature.cpp, src/flag.cpp, src/flag.h, src/ranged.cpp
As the title implies, nets should not be dealing damage to the monsters they envelop. No matter how hard you throw a net, you are just throwing a net, it shouldn't kill a chicken in 2 throws.
Introduce NO_DAMAGE flag to deal with projectiles that should apply effects but not actually deal damage using typical logic.
Currently throwing a net to envelop a creature actually deals damage using regular damage formula, albeit with the NOGIB flag preventing overkill. However just 1 throw can severely injure a small creature (e.g. chicken) and I have managed to kill chickens in a couple of throws just by throwing nets.
In several video-games nets are typically just effect-applying items, not damage dealing items. Also throwing a net so hard you kill something is silly and unfun - ask me how I …
=> fix: nets should not deal damage

src/clzones.cpp
- fixes #4397
use `std::remove_if` to remove unsafe pointer arithmatic
see: 
- https://en.cppreference.com/w/cpp/algorithm/remove
- https://www.codeproject.com/Articles/1227392/Erase-remove-Idiom-Revisited
pointers pointers everywhere
1. load save containing legacy zone type (CAMP_FOOD)
[Superior.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/14772278/Superior.1.zip)
2. it does not segfault.
- introduced by #4369
- i _love_ C++ where a trivial operation of filtering elements causes segfault
=> fix: prevent segfault when loading invalid zone type

data/json/recipes/other/materials.json
Bog Iron ore to lump of steel was a necessary recipe, the problem is, for anyone playing without books, knows, at lvl 4 survival, there is except for spores from mushrooms, no other recipe training to lvl 5, which was needed for that recipe. furthermore, fabrication 5 nearly demands to have metallurgy already running, which isn't the case.
1. lower recipe autolearn to its real valures
2. add the recipe to more books.
=> fix(balance): reduce autolearn level of bog iron recipe and add it in more books

src/options.cpp, src/sdltiles.cpp
(the section with red arrow indicates time taken to render spinner UI)
- kind of solves #251
[for more than 7 years](https://github.com/cataclysmbnteam/Cataclysm-BN/commit/46887880be4df657fb55681858fe50364568f6cf) SDL was initalized with [`SDL_RENDERER_PRESENTVSYNC`](https://wiki.libsdl.org/SDL2/SDL_RendererFlags). With vsync, the game must synchronize with monitor's refresh rate (60hz ~= 16.7ms), causing slowdown. Disabling VSync may improve performance.
added disabled-by-default option `Use Vsync` (`VSYNC`) to control vsync behavior on GPU rendering.
keep using vsync
| with vsync | without vsync |
| :-: | :-: |
| ![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/421989c8-607b-4774-86dd-7db3224e30a0) | ![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/ …
=> perf: disable vsync by default

data/json/items/comestibles/carnivore.json, data/json/items/comestibles/offal_dishes.json
Fix getting parasites from having raw fish in your auto-eat zone:
Along the way I decided to just also add the relevant flag to all raw items that can grant parasites. While the low fun value may stop auto-eat due to the code checking the fun level, it doesn't stop you from hitting the wrong key and instantly getting parasites from that.
1. Set the `flesh` abstract to have `UNSAFE_CONSUME` on it.
2. Converted raw fish, and  to add `SMOKABLE` to its flag list via `extend` instead of fully overriding the flags.
3. Set pickled and canned offal, jerky, salted fish, various cooked offal items to delete `UNSAFE_CONSUME` from flags.
4. Added `RAW` and `UNSAFE_CONSUME` to raw fat like tainted fat has.
5. Misc: Fixed cooked meat scraps lacking `EATEN_HOT`.
screm
Checked affected files for syntax …
=> fix: add `UNSAFE_CONSUME` to all raw meat items

data/json/mapgen/necropolis/necropolis.json, data/json/mapgen_palettes/necropolis/necropolis_a.json
Continue to fix the Necropolis.
Use pavement instead of wood floor under the road barricades.
Use sidewalk instead of wood floor under the racks outside the gardening store.
none
Before:
After:
=> fix: more fix for level 0 of the Necropolis 2

src/options.cpp
- may fix #4423
- resolves #4431 
turn vsync on by default.
force enable vsync by default on windows?
@Lamandus confirmed that with VSync on the issue is solved.
=> fix: enable vsync by default

data/json/professions.json
Adds two professions, one for Electrical Engineering and one for Mechanical Engineering. They are mostly based on the Medical Resident profession and their own Mechanic/Electrician counterparts and are more focused on skill than gear.
This is my first Github PR ever, so perhaps expect a gigantic messup.
=> feat(content): Adds Mechanical and Electrical engineering professions

data/json/mapgen/pump_station.json
Fix a misaligned ladder in the pump station.
Align the ladder with the manhole cover above in the mapgen `pump_station_5`.
none
none
=> fix: misaligned ladder in pump station

src/newcharacter.cpp, src/options.cpp
Because I always create my avatar as female and it's tedious to change gender every time.
added `DEF_CHAR_GENDER` which sets gender on avatar creation.
make character creation UI remember more options?
Q: Who's maribel hearn and why do they always have to be a she?
A: _touhou hijack lol_
=> feat(UI): allow setting default gender

data/json/itemgroups/Locations_MapExtras/locations.json, data/json/itemgroups/Locations_MapExtras/locations_commercial.json, data/json/itemgroups/Locations_MapExtras/locations_mapextras.json, data/json/items/tool/cooking.json, data/json/items/tool/workshop.json, data/json/mapgen/ws_fire_lookout_tower.json, data/json/recipes/ammo/other.json, data/json/recipes/armor/arms.json, data/json/recipes/armor/feet.json, data/json/recipes/armor/hands.json, data/json/recipes/armor/head.json, data/json/recipes/armor/legs.json, data/json/recipes/armor/suit.json, data/json/recipes/armor/torso.json, data/json/recipes/other/materials.json, data/json/recipes/other/other.json, data/json/recipes/other/tools.json, data/json/recipes/other/vehicles.json, data/json/recipes/weapon/explosive.json, data/json/recipes/weapon/mods.json, data/json/recipes/weapon/ranged.json, data/json/requirements/toolsets.json, tests/iteminfo_test.cpp
This is a big one, it was a string of changes that went from creating A, to creating B etc.. All in all, this PR was created to make a concentrated alcohol fueled soldering iron. As in, you got a burner, and you hold a metal over it to heat it up and use for soldering, instead of using electricity.
Not to the list of changes, because one lead to another. (Sorry Co-Devs)
1. Creating a new item: alcohol fueled soldering iron.
a. Adding recipe
b. Adding spawn locations
c. Adding it to tool-lists for crafting.
2. Sane-checking the use of the soldering iron
3. remove the welder in some clothes recipes, because it wouldn't need glare protection.
4. remove the welder in some recipe for weapon mods where the repair-kits would be enough (also removing the requirement of glare protection.
5. …
=> feat: Adding alcohol-fueled soldering iron, and a lot of recipe optimations/changes

data/json/techniques.json
Per Pr0man's feedback on the discord, one issue with Eskrima is that the puno strike technique takes a lot of the utility out of using it with knives, as it frequently triggers with crits to completely negate the majority of damage for those weapons.
Set puno strikes to have `weapon_damage_requirements` of 8 bashing damage, same as a cudgel. Idea here is to exclude knives from the technique and mainly limit it to weapons that have enough base bashing damage to justify using the technique.
Realistically you could do haft strikes with knives just fine and they can certainly break bones if used right, but it doesn't bear out very well under current gameplay mechanics so it'd be better to reserve them for weapons that work well with it.
1. Coding in support for restricting tecs to specific …
=> feat(balance): restrict eskrima haft strikes to more damaging bash weapons

data/json/items/armor/bandolier.json
The stone pouch was inferior in nearly any way to drop leg pouches. The maximum they could hold was 750 ml (per leg) so 1500 ml for 2 pouches, with a encumbrance of 4. Drop leg pouches have a capacity of 4000 ml and also an encumbrance of 4.
Doubling the amount makes 2 stone pouches hold 2.500 ml of stones, while still lower than the drop leg, it takes less time to reload, and is easier to craft. Having more than 40 stones (for 2 pouches) is rarely needed.
Lowering encumbrance to 3 or even 2.
=> feat(balance): double stone pouch capacity.

data/json/construction.json, data/json/flags.json, data/json/furniture_and_terrain/terrain-roofs.json
This adds the possibility to construct wind turbines on roofs. It require (imaginary) bolts and metal frames for securing it up there.
=> feat: add construction of wind turbines on roofs

src/construction.cpp, src/descriptions.cpp, src/map.cpp
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/596091331acc4bb55a32fae53e8f1d479464995a/doc/src/content/docs/en/mod/json/reference/json_info.md#L863-L864
make it easier to check whether a terrain satisfies `pre_flags`.
added section to display terrain flags in construction and extended description
also make more detailed error message on why a construction cannot be constructed
idea from #4463
=> feat(UI): show terrain flags

data/json/recipes/animals/medium_quadruped_armor.json, data/json/recipes/animals/small_quadruped_armor.json, data/json/recipes/armor/arms.json, data/json/recipes/armor/feet.json, data/json/recipes/armor/hands.json, data/json/recipes/armor/head.json, data/json/recipes/armor/legs.json, data/json/recipes/armor/storage.json, data/json/recipes/armor/suit.json, data/json/recipes/armor/torso.json, data/json/recipes/other/containers.json, data/json/recipes/other/materials.json, data/json/recipes/other/medical.json, data/json/recipes/other/other.json, data/json/recipes/other/tools.json, data/json/recipes/weapon/bashing.json, data/json/recipes/weapon/ranged.json
Change some recipes to use the "sewing_standard" tag instead of filament and sewing quality
Change Waterskins recipes to not use fur as a component
changed the tags to use sewing_standard instead
removed components for fur in waterskins
=> fix: Fixing recipes with sewing quality, tweaking of recipes

data/json/items/armor/ammo_pouch.json
In a PR some days ago, I added the flag "COMPACT" (it makes the item wearable with others on the same layer) to many items, I missed the ammo satchel. Now it is added in. So it won't conflict with a leather belt for example.
Also I missed some encumbrance values not being set for some items. I defined "base" encumbrance which will lead to its max.
1. Give ammo satchel the tag "Compact"
2. give it a max encumbrance of 3 (was rigid 5 before)
3. added (max_)encumbrance to items missing it (or I deleted them and forgot to add them back)
=> fix(balance): add "COMPACT" to ammo satchel, fixing old errors of mine in encumbrance.

data/json/recipes/armor/other.json, data/mods/pride_flags/recipes.json
I realized that there was no recipe for the American flag, and considering I already made a flag recipe for the pride flags mod I figured it would be a good fit here too. However, I also realized that cutting up a flag gives 40 rags, so a recipe only taking 35 would be a rag duplication.
- Adds a recipe to craft an American flag
- Also changes the recipes in the pride flags mod (alongside the new American flag recipe) to use 40 rags 
Leave the flag uncraftable
Recipe does indeed load correctly.
=> feat(content, balance): Add American Flag Recipe, balance Pride Flag mod recipes

data/json/items/comestibles/brewing.json
Must and wort were being consumed by the player when set in auto-eat zones. Since they should be seen as ingredients they should not be auto-consumed. They can be used manually in a pitch. All brewing recipes are autolearn, so good alcohol should be made out of it.
=> feat(balance): add trader_avoid and unsafe consume to wort and must

doc/src/content/docs/en/mod/json/reference/json_flags.md
BIOPROOF doesn't appear to be listed in the JSON Flags documentation, so I thought I'd add it
Adds BIOPROOF to the JSON Flags documentation
Just leave it out and let it be obscure
My computer didn't explode upon saving the file, and that's really the most I can do.
Smol PR gang
=> docs: Add BIOPROOF to JSON Flags Documentation

data/json/items/comestibles/sandwich.json
Fixes the fact that sauce sandwiches made out of entirely okay ingredients would suddenly trigger lactose intolerance (and presumably meat intolerance / allergy too) for no reason.
Explicitly defines materials to prevent it inheriting the deluxe sandwhich's materials
- Leave the dairy matter because technically butter is a valid ingredient, and brioche and biscuits are made with milk
- The vast majority of the ingredients are non-dairy. As such, ingredient democracy has dairy removal winning.
Are there other oddities in the sandwiches file? Maybe, but it'd be good PR fodder for new contributors if they notice something. I just thought this one was particularly egregious, and I saw it being talked about firsthand.
=> fix: Fix sauce sandwich containing dairy and meat

src/requirements.cpp
- Fixes #3004 and fixes #2002
Check was bugged, if an item requires charges for tool use but is not `count_by_charges()` only unloaded tools are considered valid components, but the game looks for the extra item that is used in the tools because it cannot discern that it doesn't need to.
An extra check was added so that if the tool uses charges but is not `count_by_charges()` it goes to standard checks. It would technically also work vice-versa but I don't think that use case can even happen under normal circumstances.
- A healthy, happy life spent not staring at archaic code.
- Spawn 2 soldering irons and all the other requirements for installing a soldering iron.
- Give a plank hammering 2.
I don't really think I can fix the display without a lot of code diving into parts I'd rather …
=> fix: Construction Recipe check for components same as tool fixed.

data/json/items/tool_armor.json, data/json/recipes/armor/head.json
Sometimes you want to use ballistic goggles and a gas mask, or maybe you have all the eye protection CBMs and don't want to encumber your vision. Use a half gas mask!
The filter mask was the only half-mask in the game, and it only protects against smoke and not poison. There are times ingame where you won't want to have your eyes impeded by a gas mask, maybe because you have the CBMs so you don't need goggles, or maybe you have superior goggles to the gas mask you have available.
A new gas mask that only covers the mouth has been added.
=> feat(content): Half survivor mask

data/json/regional_map_settings.json, data/json/weather_type.json, src/item.cpp, src/weather.cpp, src/weather_type.cpp, src/weather_type.h
So a recurring complaint has been that it seems like it rains far less often than desirable. After a while of eyeballing the code, the weather JSON, and some testing in a test save, I eventually figured out a potential solution that should be a bit more effective than simply cranking base humidity up by a ton.
C++ changes:
1. In item.cpp, added an extinguish case for `precip_class::medium` to `item::process_extinguish`, defining a chance to affect fires in between the chance used by light and heavy.
2. In weather.cpp, updated `proc_weather_sum` to have a handling case for `precip_class::medium` with an `amount` value in between light and heavy.
3. Also in weather.cpp, changed `precip_mm_per_hour` so light rainfall has a value of 1 instead of 1.5, and added handling for medium rainfall at …
=> feat(balance): lower humidity threshold for drizzle, slight increase to base humidity

data/json/traps.json, data/json/vehicleparts/vehicle_parts.json
This adds the option to use tarp raincatchers on vehicles, the only other vanilla funnel option besides gutters (which aren't exactly portable) to not have a vehiclepart option.
1. Added a vehiclepart version of tarp raincatcher. Since collection power is all in liters, used 90 instead of the jank-ass volume value the trap version used.
2. But for consistency, bumped the value the trap version can handle from 85.5 liters to 90 liters.
Mainlining leather tarp raincatchers from MST Extra too.
2. Load-tested and set up two raincatchers over 60-liter tanks, one in trap form and the other a vehiclepart over an installed tank.
3. Waited...motherfucking FOREVER to finally get weather that's fucking rainy.
4. Gave up and loaded back in after …
=> feat(content): add vehiclepart raincatcher

data/json/itemgroups/art_antiques_crafts.json, data/json/items/tool/fishing.json, data/json/recipes/other/tools.json
Innawoods don't have a good way to break the fishing law. This PR allows to catch fish inhumanly. The way it is supposed to be!
1. Add a new item: clay fish trap. Heavier as the plastic one.
2. Added a recipe using 5 clay canisters. Autolearn at lvl 3 survival.
3. Added it to one item group.
Only using one jug or using a specific jug just for it. But to be honest, this gives old stuff more uses.
Spawned it in my game. It works... As bad as it usually works.
=> feat(content): clay fish traps

src/activity_item_handling.cpp
This adds a suggested followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4417 and fixes another oddball problem that was dropped in my lap.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4521
In activity_item_handling.cpp, updated `find_auto_consume` so that it now ignores items that will provide the player with zero calories when in an auto-eat zone, and additionally the check for `UNSAFE_CONSUME` also makes sure to catch items with parasites even if they lack the relevant flag.
1. Spamming the everloving fuck out of the `UNSAFE_CONSUME` on any item that has zero calories. 
2. Pestering Viss to do it instead.
2. Dropped several barley seeds and sausage casings into an auto-eat zone.
3. Debugged myself to be hungry and waited, …
=> fix: auto-eat ignores zero-calorie items, anything with parasites

data/json/items/armor/bandolier.json, data/json/recipes/armor/storage.json
The following is a copy of @Tefnut PR #4539 on grenade bandoliers created due to issues with their branch. Co-authorship maintained, and description of PR maintained. For any inquiries in the PR and suggestions ask Tefnut.
Shotguns, pistols, and rifles have an over-the-shoulder bandolier. While the impact of adding an option for grenade launchers is minimal, it helps legitimize them as an option. They technically had a grenade pouch prior, but a bandolier option is something a post-cataclysm survivor would certainly think of.
I added them and a recipe, copy-pasted from rifle bandoliers with their name, description, and accepted ammo replaced. They have half the capacity due to using bulkier ammo, but I'd say that they'd be fairly balanced still.
Not have grenade bandoliers
Buff grenade …
=> feat(content): grenade bandolier

data/json/items/classes/gun.json, data/json/items/gun/nail.json, gfx/MSX++UnDeadPeopleEdition/tile_config.json
The coilgun previously could not autofire like the nail rifle, nor did it look like a rifle. Its native sprite made it look like a small pistol when wielded and some sci-fi space gun when on the ground. Furthermore, the nail rifle counted as both a pistol and a rifle thanks to an extend line.
The coilgun now can autofire like the nail rifle, it has the sprite of the H&K G80 railgun now, and the nail rifle now counts as a rifle instead of a pistol.
=> fix(content): Coilgun fixes

data/json/mapgen/bank.json
Fix misaligned ladder on the roof and use `roof_palette`.
JSON change.
none
Before:
After:
=> fix: misaligned ladder, use `roof_palette` on `bank_roof`

data/json/items/armor/legs_armor.json
Evidently, adding steel to a leather skirt actually makes the skirt lighter! Who knew, we must now inform scientists everywhere that steel has a negative mass when it is added to things.
In all seriousness, this seems like a silly little mistake regarding which weight value to adjust from.
Adds the weight value of the scrap metal used in the recipe to the weight of the precursor armored leather skirt to get the proper value for the plated leather skirt.
- Leave in the harmless bug
It loads.
Armored Leather Skirt:
Previous Plated Skirt:
New Plated Skirt:
=> fix(balance): Fix Plated Leather Skirt's Weight Value

data/json/mapgen/bugs/wasp_tower.json, data/json/mapgen/radio_tower.json, data/json/mapgen_palettes/wasp_palette.json
Replace the stair at the base and top of the radio tower and wasp radio tower with ladder.
Also fix `radio_tower_roof_1`, `wasp_tower_roof_1`.
`t_ladder_up` instead of `t_stairs_up`
`t_ladder_down` instead of `t_stairs_down`
none
`radio_tower_roof_1`:
`wasp_tower_roof_1`:
=> fix: replace radio tower stairs with ladders

data/json/items/gun/22.json, data/json/items/gun/762.json, data/json/items/gun/shot.json
A long time ago someone on the discord noted that several guns have the wrong categories applied, I checked and agreed, and changed the copy-from so that they now point at the right category.
Change `copy-from` for the following guns.
- Mossberg Brownie: `pistol_base` -> `pistol_1shot` 
- SKS: `rifle_manual` -> `rifle_semi`
- Pipe Shotgun: `shotgun_base` -> `shotgun_1shot`
- M1897 Trench Gun: `shotgun_base` -> `shotgun_pump`
Leaving it alone until someone points it out again.
Load up the game, check that:
- Mossberg Brownie is now in One Shot category
- SKS is now in Autoloading category
- Pipe Shotgun is now in One Shot category.
- M1897 Trench Gun is now in Manual Action category
I made derringers count as 1 shot guns due to their barrel arrangement, we could probably make them into …
=> fix: Specific guns now have correct `copy-from` to fix their weapon categories.

data/json/mutations/mutations.json
This tackles chimera mutants waffling weirdly between fur and scales by making the patchwork skin mutation actually evolve from either of the relevant mutations.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4567
1. Set both `LIGHTFUR` and `SCALES` mutations to have `PATCHSKIN1` as a valid `changes_to`, so either mutation can evolve into it if given the chance.
2. Changed `PATCHSKIN1` to have `LIGHTFUR` and `SCALES` for `prereqs` instead of `SKIN_ROUGH`, which should create a one-way relationship for the mutations.
1. Setting `valid` to false for Patchwork Skin so that generic mutagen can't risk triggering a potential one-way relationship. This would mean that aspiring chimeras chugging generic mutagen would still witness the eternal fur-vs-scale dance.
2. Simply removing …
=> fix: patchwork skin correctly develops from fur or scales

src/map.cpp
Per request, it was suggested that glass walls and the like should still print messages for when they intercept bullets, for the sake of clarity so the player can tell that the feature actually works with them.
In map.cpp, changed `map::shoot` so that the check for printing the message on terrain and furniture intercepting bullets now only cares about if you can see the tile taking the bullet, and no longer checks for whether it had an intercept chance defined.
screm
2. Shot up some ballistic glass, it now prints the message when shooting through it.
=> feat(UI): ranged bash message prints for all intercepts

src/monster.cpp
I discovered that acidproof monsters seem to still be able to suffer from the corroding status effect.
In monster.cpp, changed `monster::is_immune_effect` to add a check for the corroding effect, setting them to be immune if the monster is otherwise immune to acid damage. Same general deal with monsters being immune to being lit on fire if they're immune to heat damage, and characters having a similar check for the corroding status if they're immune to acid or are a slime mutant.
screm
2. Spawned in a dark wyrm and let it vibe for bit in acid, it no longer shows itself as corroding after standing in its own acid.
3. Let it wait around a bit, confirmed it also stayed uninjured.
4. Checked affected file for astyle.
=> fix: `ACIDPROOF` monsters are now correctly immune to corrosion

data/json/items/ammo/40x46mm.json, data/json/items/ammo/40x53mm.json, data/json/items/ammo/shotpaper.json
part 1: #4611
This time I looked over the ammo. 40x ammo was missing a look alike, so they got one for retrodays
=> feat(content): look like for retrodays part2, 40mm ammo

data/json/npcs/cabin_chemist/chemist_missions.json, data/json/npcs/homeless/group_camp_missions.json, data/json/npcs/scrap_trader/scrap_trader_missions.json
This fixes the new missions added by Zlor's NPC ports recently inexplicably showing up on starter NPCs.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4583
1. Set the homeless camp NPC missions from `ORIGIN_OPENER_NPC` to `ORIGIN_SECONDARY`.
2. Set the chemist NPC missions from `ORIGIN_OPENER_NPC` to `ORIGIN_SECONDARY`.
3. Set the scrap trader NPC missions from `ORIGIN_OPENER_NPC` to `ORIGIN_SECONDARY`.
screm
Used my eyes.
=> fix: don't give holdout npc missions to starter npcs

data/json/harvest.json
As the title indicates. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4610
Removed a copy of the `mammal_fur` @Zlorthishen added for some reason that does nothing except replace normal organs with mutant offal, which was being loaded due to being lower in the file.
Remembering to actually double-check PRs that mess with harvest.json instead of rubber-stamping them.
Used my eyes to confirm I deleted the correct one.
Caused by me merging https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4474 without giving it a more thorough look-through.
=> fix: remove redundant copy of `mammal_fur`

src/avatar_action.cpp
This fixes the weird logic where eating food not in your inventory would always print a message saying you leave the empty container behind, even when it's still got some in it.
In avatar_action.cpp, updated the message logic in `avatar_action::eat` so the message triggers if the item targeted is neither a food container nor edible as-is. This ensures that it only triggers a message when it sees the item is now a container that's no longer got food in it (because immediately before this check you just ate the last bite).
Just removing the message and its check entirely since it doesn't really tell you anything important, we all forget to clean the empty cans out of our shopping cart until there's a giant pile of them anyway. :D
2. Spawned in some assorted food …
=> fix: don't spam incorrect messages about eating out of half-empty containers

src/newcharacter.cpp
Add a dot at the end of certain sentences in the description of Multiple pools and Freeform
"Scenarios and professions affect skill point pool." instead of "Scenarios and professions affect skill point pool"
"No point limits are enforced." instead of "No point limits are enforced"
none
Before:
After:
=> fix: add a dot at the end of Multiple pools and Freeform sentences

data/json/mapgen/shooting_range.json
Having all those casings littered all over the ground is very silly, and does not look good. Plus, it's pretty unrealistic that they wouldn't have some sort of receptacle for them.
- Adds two trashcans to the shooting range that now hold most of the casing spawns
- Removed most of the loose casing spawns
- Completely remove loose casing spawns
Nah, it's foreseeable that *some* small number of casings would be on the ground around the benches.
It loads
Presumably breaks No-Hope a little more, but what doesn't these days
=> feat: Condense casing spawns at shooting ranges

data/json/items/ammo.json, data/json/items/comestibles/med.json, data/json/items/generic.json, data/json/items/resources/wood.json, data/json/items/tool/fire.json
Some adjustments to firestarting tools and related items. In particular making ember carriers a bit less bothersome to work with, while making the tinder mechanic used on a couple more tools in exchange for allowing more items to be used for that.
1. Added the `REQUIRES_TINDER` flag to fire drills and camp fire drills. These are even more work to light a fire with than a flint and steel, which was the only item to have this flag.
2. Added `SLEEP_IGNORE` to light ember carriers. As oddball of an item as they are, I've found them to be really useful for extreme innawoods runs where keeping a slow-burning fire on hand is a lot less trouble than fiddling with flint and steel and helps skip some potential issues when in the dark, but the main drawback with it is it expects you to keep it …
=> feat(balance): updates to firestarting tools

data/json/overmap/overmap_terrain/overmap_terrain_industrial.json
Remove the sidewalk around the lumbermill.
Cut unnecessary lines in overmap_terrain_industrial.json for the lumbermill and use `generic_city_building_no_sidewalk`
None.
No sidewalk.
=> fix: remove lumbermill sidewalk

data/json/recipes/ammo/shot.json, data/json/requirements/materials.json, data/json/uncraft/ammo/shot.json
Lead is essentially illegal to actually use in birdshot irl in the USA. Plus, it helps to give birdshot a more unique identity, in a sense.
Changes uncraft to BBs for birdshot, allows for use of BBs in creating it yourself
- Use scrap
As pointed out by Chaos, undesirable
- Remove lead from crafting
Tempting, but unfortunately survivors care little about silly things like EPA regulations or safety other than keeping the zombies off their lawn.
Loads, is able to be crafted
[Section on wikipedia explaining lead-free shot](https://en.wikipedia.org/wiki/Shotgun_shell#Lead_free)
=> feat: Remove lead from birdshot

data/json/items/generic/bathroom_house.json, data/json/recipes/other/tools.json, data/json/uncraft/tools.json
This adds a bit of actual utility to shaving razors besides just flavor, and makes them a bit less hassle to craft.
I'd planned at first to also give this improvement to shaving kits too, but cutting quality injects use actions that would consume soap for no good reason.
1. Added cutting and fine cutting quality of 1 to shaving razors. Since the recipe uses just 1 razor blade, this basically assumes you're making an improvised straight razor when you stick it on a handle.
2. Updated the recipe to allow using a splinter wood, bone, or human bone for the handle instead of just a plastic chunk, since no heating or plastic mold is involved you're presumably just mounting it in a primitive handle to have a way to use it without cutting your fingers open.
3. Added an uncraft for regular shaving …
=> feat(balance): added tool quality to shaving razors, improve recipe for razor, allow uncrafting shaving kits

data/json/items/tool/woodworking.json, data/json/items/tool/workshop.json, data/json/items/tool_armor.json
This aims to make wood saws more worth using as tree cutting tools than plain stone axes, while currently still keeping proper wood axes superior since they're bulkier and have less other tool utility.
1. Bumped `AXE` quality of wood saw from 1 to 2.
2. Accordingly bumped up the axe quality of all related items: toolbox, survivor utility belt, misc repair kit, and workshop toolbox.
1. Bumping wood saws up to 3 so they're equal to wood saws. Since the only makeshift axe to really match a wood saw is the copper one, which takes more effort to make than plaine stone, it's probably okay at its current level.
2. Baking in some hardcoded shenanigans to make the `chop_moves` function either pick best of wood-cutting vs sawing quality for the tool being used automatically.
3. At some point I …
=> feat(balance): wood saw cuts trees better than a stone axe

data/json/bionics.json, data/json/items/bionics.json, data/json/items/fake.json, src/character_display.cpp, src/melee.cpp
This grab the ideas yay/phoenix brought up in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4556 plus the required hardcode changes. Idea is adding more utility to a bionic described as install 4 cm each of high-tech razor blades into your fingers, which logically should be more on par with some claw mutations while being better for cutting.
Currently WIP because I also intend to update the bonus unarmed damage but that's C++ stuff, and currently out and about on wifi. Also part of intended functioning seems to need a hardcode touching up too, see testing below.
C++ changes:
1. In character_display.cpp, updated the `per_hand` value in `character_display::display_empty_handed_base_damage` from 4 to 9, to match the total damage being added per yay's intended implementation.
2. In …
=> feat(balance): buff fingertip razor bionic, take 2

src/item.cpp, src/iteminfo_query.h, tests/iteminfo_test.cpp
I'd been meaning to rig it so that a bit more iteminfo stuff gets trimmed when it's not nessecary, and also found out in testing that there was a case of an iteminfo property not displaying at all when it probably should, so that finally gave me motivation to mess with this a bit more.
1. In item.cpp, moved some values in `item::ammo_info` higher up since they get used a bit earlier than normal. Rigged it so that now, damage and armor values are not displayed for ammo unless they're actually defined. The reason for the values being moved up is to fix a newline issue, where if an ammo has damage and range but not arpen, it'd fail to move range+dispersion to the next line down since normally the needed newline is called for by armor-pierce info. Now damage info either calls for a newline or …
=> feat(UI): trim some more iteminfo when not required, show range mod for gunmods

data/json/mapgen/refugee_center/refugee_center.json, data/json/npcs/refugee_center/surface_staff/NPC_free_merchant_shopkeep.json
This change will make the back bay zombies not spawn until the mission is requested, this will prevent zombies from breaking out before the player has a chance to accept the mission
removes the zombie spawn from the map
moves them to the NPC mission
continuing to allow the evolved zombies to kill all NPCs before I can speak to any of them
before requesting mission:
after requesting mission:
=> feat(balance): Alter "Clear Back Bay" mission so zombies don't spawn until mission is given

data/json/items/resources/metal.json, data/json/recipes/other/materials.json, data/json/uncraft/generic.json
This adds a few more ways to break down basic items into scrap, and along the way I found some weird inconsistencies to fix up.
1. Increased the amount of scrap used to make wire from 1 to 3. Scrap weighs 50 grams and wire weighs 151 grams, so now it's only magically gaining 1 gram of weight.
2. Likewise, increased the yield of uncrafting wires from 1 scrap to 3.
3. Set it so that the recipe for unbending barbed wire into wire yields 3 scrap as a byproduct. Barbed wire weighs 302 grams, so ideally this should be returning 3 scrap metal. This would incorrectly return 6 instead, if not for...
4. Lowered `count` of scrap metal from 2 to 1. **Why were they being paired up like that?** To my knowledge every single spawn of scrap metal in the game assumes that a single `count` of stack is gonna …
=> fix: don't spawn scrap metal in pairs, uncrafting consistency updates, add some more uncrafts

src/activity_item_handling.cpp, src/options.cpp
ports dda change
- https://github.com/CleverRaven/Cataclysm-DDA/pull/62299
adds a new auto-note option that marks the location of a favorite item drop
forgetting the item that you forgot you need, again.
- spawn random NPC in default scenario, get Cowboy, Yeeee-Haw!
- mark whiskey as favorite item
- run out of evac center
- drop whiskey
- run some more
- check map and see new note
note that the note on the initial commit has the wrong dda port
=> feat(port): Mark overmap location if player drops favorited item

data/json/monsterdrops/feral_humans.json, data/json/monsters/feral_humans.json
This makes the weapon selection dropped by feral humans vary a lil more, and a couple other tweaks.
1. Set it so that crowbar ferals can drop makeshift crowbars or claw bars instead of always full-on crowbars.
2. Set it so axe ferals pick between a fire axe and a wood axe at random, favoring a fire axe more often.
3. Speaking of, fixed it so that it's the axe feral that sometimes drops firefighter clothes, not crowbar ferals.
4. Gave hammer ferals a wider variety of handheld hammers they can drop instead of always proper hammers.
5. Gave feral scientists a chance to drop an x-acto knife instead of a scalpel.
6. Gave pistol-toting security ferals the full selection of 9mm pistols in `carried_guns_cop`, instead of just M9s.
7. Updated the fire message for feral-sec accordingly to not …
=> feat(balance): increase variety of weapons dropped by feral humans

data/json/mapgen/bugs/ants.json, data/json/obsoletion/migration_oter_ids.json, data/json/overmap/overmap_mutable/anthill.json, data/json/overmap/overmap_terrain/overmap_terrain_ants.json
This fixes mutable special generation having rendered the more dangerous acid anthills indistinguishable from regular ones at a distance.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4670
1. Defined a copy of the anthill `om_terrain` for acid variant. Currently same layout but that seems to be common for acid anthill `om_terrain`s.
2. Defined overmap terrain entry for sulfurous anthills once more.
3. Updated mutable special entry for acid anthills to use the new anthill for it.
4. Updated old migration file accordingly.
screm
1. Checked affected files
3. Debug revealed map, searched around for anthills and confirmed I could spot both normal and acid ones.
=> fix: acid anthills are distinct on the map again

data/json/mapgen/occupied_lumber_mill.json, data/json/npcs/lumberyard/lumbermill_missions.json, data/json/overmap/overmap_special/specials.json
More fix for the occupied lumbermill.
Fix the ownership because a corner of the lumbermill doesn't belong to the loggers.
Use the same road connection as the unoccupied lumbermill.
Add a roof to the sleeping quarter placed by the mission `MISSION_LUMBERMILL_GET_6_BLANKETS` because it has no roof.
none
Sleeping quarters roof.
=> fix: fix for the occupied lumbermill

data/mods/Magiclysm/items/ethereal_items.json, data/mods/Magiclysm/materials.json
Adds a new material `contentrated_mana`.
Adds a material field on `magic_light` entry containing `concentrated_mana`.
Fixes #2518.
Done by adding a new material `concentrated_light` which `magic_light` can use. The values were adapted from DDA's `concentrated_mana` material entry.
None.
1. Cast spell `Magical Light.
2. Move to see if the error pops up.
=> fix: `magic_light` throwing `wind_resist` error

data/json/uncraft/generic.json
Allows recovery of material from clay items, "clay pellet" should be the only one without an uncraft if I didn't miss any.
Added uncraft for: clay bowl, clay canister, clay jug, clay teapot, clay flower pot, clay pot, clay crucible, clay hydria, clay quern, large clay pot, brick and firebrick.
Made the last two require tools with hammering (1 for brick and 2 for firebrick since it's harder to break irl and players who want to get rid of a firebrick are likely to have some tools for metalworking) and chiselling 1. Looked up online how to break bricks and using a chisel came up in all examples seen.
1. Made a backup of data/json/uncraft/generic.json.
2. Replaced old file with modified version.
3. Loaded into a world and opened the debug menu to spawn items.
4. Verified that the uncrafts …
=> feat: add clay uncrafts

data/mods/DinoMod/scenarios.json, data/mods/DinoMod/startlocations.json
Content parity with DDA
Ports most scenarios content from DDA. Includes material from https://github.com/CleverRaven/Cataclysm-DDA/pull/56451 and https://github.com/CleverRaven/Cataclysm-DDA/pull/50513 and https://github.com/CleverRaven/Cataclysm-DDA/pull/49968
N/A
Passes checks. I can't get the latest build to run on my Mac but that shouldn't be related.
Permitted by #4665
N/A, this adds JSON content
=> feat(mods/DinoMod): scenarios

data/json/items/generic.json, data/json/recipes/armor/feet.json, data/json/recipes/armor/head.json, data/json/recipes/armor/other.json, data/json/recipes/armor/storage.json, data/json/recipes/armor/suit.json, data/json/recipes/chem/chemicals.json, data/json/recipes/chem/other.json, data/json/recipes/electronic/components.json, data/json/recipes/electronic/lighting.json, data/json/recipes/electronic/other.json, data/json/recipes/electronic/parts.json, data/json/recipes/electronic/tools.json, data/json/recipes/other/containers.json, data/json/recipes/other/materials.json, data/json/recipes/other/other.json, data/json/recipes/other/parts.json, data/json/recipes/other/tools.json, data/json/recipes/other/traps.json, data/json/recipes/other/vehicles.json, data/json/recipes/weapon/bashing.json, data/json/recipes/weapon/explosive.json, data/json/recipes/weapon/mods.json, data/json/recipes/weapon/piercing.json, data/json/recipes/weapon/ranged.json, data/json/requirements/materials.json
Nails can be hard to come by innawoods. This let the player use glue as an alternative. While "not as effective" as nails would be, innawoods can now rely on making glue to get boats without the need of metallurgy. Sure, nails are still superior, but that would be a nail free alternative.
Using a new requirement list "nail_glue" to replace nails as an solo items where it makes sense.
Nailing...
=> feat(content): use glue as nail alternative

data/json/mapgen/lab/lab_floorplans_finale1level.json, data/mods/DinoMod/mapgen/DinoLabFinale.json
It turns out when lab finales were reworked a while back, the failsafe feature of them always spawning a science ID card somewhere was lost in the process. As I noted in the relevant issue, it's really more of a last resort if a player manages to completely master a lab they spawn in but somehow fail to find any reasonable escape method.
Ideally if the player can survive crawling their way down into the finale, grab the card, make it back to the entrance and get past the turret to swipe the card reader, then they're badass enough they should already have free rein to scour the rest of the lab for way easier escape methods, but it's a good bit of idiotproofing in case the RNG was feeling weird enough that day.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4598
1. Placed a …
=> fix: lab finales have science ID cards again

data/json/species.json, data/mods/No_Reviving/modinfo.json, data/mods/No_Zombify/modinfo.json, doc/src/content/docs/en/mod/json/tutorial/modding.md, src/monstergenerator.cpp, src/mtype.cpp
Some players have expressed concerns over `zombify_into` leading to revivication like behaviour. Added a mod to disable it without overwriting all the monsters. Also the modding docs for monster adjustment was unsatisfactory, as it only recorded the REVIVE flag removal instead of noting all possible options you have with it.
Adds a special to `monster_adjustment` that empties `zombify_into` for selected species. Add an ALL species for filters.
Add a mod that disables `zombify_into` called No Zombification.
- Make a more robust `monster_adjustment` system that can work with more variables.
- Would be nice but a pain in the ass to code.
=> feat: Monster Adjustment additions, documentation and new mod to disable `zombify_into`

data/json/harvest.json, data/json/itemgroups/Monsters_Animals_Lairs/monster_drops_lairs.json, data/json/items/generic.json, data/json/obsoletion/migration.json, data/json/snippets/mutant_anatomy.json
A while back I ran into an error with endochitin complaining about not being able to have charges, and haven't seen it trigger any since then, presumably due to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4707 making them stackable.
Now there's still one more non-stacking tissue item obtained by harvesting, so I'm thinking this should fix the associated bug but can't 100% confirm since I can't find a reliable way to force the bug to trigger in the first place.
Relevant issue: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4730
Along the way, in the BN server I was encouraged to obsolete endochitin as it really does nothing for us except flavor.
1. Added `stackable` to hydrogen sacs.
2. Migrated out endochitin into regular chitin pieces, since it's basically just chitin …
=> fix: hydrogen sacs can stack, obsolete endochitin

data/json/furniture_and_terrain/furniture-migo.json, data/json/furniture_and_terrain/terrain-fences-gates.json, data/json/furniture_and_terrain/terrain-flora.json, data/json/furniture_and_terrain/terrain-fungal.json, data/json/furniture_and_terrain/terrain-migo.json, data/json/furniture_and_terrain/terrain-triffid.json
This adds ranged bash info to a few more relevant terrain items I forgot.
1. Added the standard `ranged` info to all regular trees, at 100% hit rate since all of them block view.
2. Added to tree trunks and stumps, with intercept chances of 50% and 25% respectively.
3. Bumped coverage value of trunks from from 45 to 50 a bit for consistency.
4. Added ranged bash info to triffid terrain. which was missed since the PR for it was done while I was in the middle of adding these en masse last time so I forgot about the new terrain.
5. Added to relevant terrain in fence and gate file, evidently I forgot about those too.
6. Added a coverage values of 35 to picket fences, 60 to split rail fence, for consistency. The latter also fits with closed split rail gates having that value.
7. Lowered …
=> feat(balance): add ranged bash info to more terrain and furniture

src/map_functions.cpp
A thing I noticed is that unleashing the special bonus surprise in mi-go locations tends to get the player stunlocked and killed, due to giving the critter it spawns several free hits on you.
In map_functions.cpp, set `migo_nerve_cage_removal` so that the mi-go takes a penalty to moves when spawned, equal to the moves that `iexamine::migo_nerve_cluster` takes plus 1 turn.
Simply having it not mod your moves on iexamine at all. Most iexamine interactions take a bit of time so it'd be inconsistent, and burning 2 seconds is normally inconsequential given monsters that haven't been spawned out of thin air in that exact instant have normally spent the time you're activating it spending their moves like normal creatures, it just plays weirdly with spawning a monster at the same time.
1. …
=> feat(balance): don't give mi-gos spawned by nerve clusters free turns

src/game.cpp
To fix the bug which leads to possibility to get into deep water instead of proper destination during going upstairs
- fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4087
Added additional excluding checks for tiles with "DEEP_WATER" tag during search for stairs.
None
Solution has been successfully tested in previously affected place
=> fix: prevent stairs leading to deep water

data/json/items/gun/shot.json
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4179 obsoleted mount slots for guns, but one gun still had mount slots pre-installed on them, which in practice gave them 2 sight and underbarrel slots since the game happily ignored the fact that the mods no longer have a slot they fit on and instead just applied the effects of those mount mods without a second though.
Removed the mount slot `default_mods` from the mossberg 590A1.
screm
Used my eyes to confirm the line I deleted no longer exists.
=> fix: mossberg 590A1 no longer has obsoleted gunmods installed on it

data/json/harvest.json
Turns out at some point chitin harvests were set to count as bone, which is sorta logical at first glance since it's the exoskeleton, but also not actually correct code-wise because `bone` means it won't be stripped off by skinning, and the EXO in exoskeleton is important there.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4741
Set all spawns of chitin and acidchitin in harvest.json to use type `skin` instead of `bone`.
Making Zlor do it since it was likely one of the portover PRs that first changed it.
3. Summoned a giant wasp guard as in the issue, confirmed I can indeed skin it to get chitin pieces.
4. Butchered the skinned corpse afterward, confirmed it doesn't drop any …
=> fix: chitin goes on the outside, not the inside

data/json/items/armor/storage.json, data/json/items/tool/pets.json, data/json/items/vehicle/cargo.json, data/mods/Aftershock/items/vehicle_items.json
Turns out https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4713 also changed a properly in the JSON for pet carrier iuse for some wacky reason.
Updated pet carrier items to use `creature_size_capacity` instead of `monster_size_capacity`, in both vanilla items and in mods (one result in Aftershock was found).
Changing the string back to `monster_size_capacity` because I have no goddamn idea why someone would ever make such a pointlessly minor change that does nothing but require the JSON to be updated, let alone why it got included in an accessibility port.
3. Scooped up a dog in a pet carrier, it works as expected.
=> fix: update JSON of pet carrier items with correct property

src/vehicle.cpp, tests/vehicle_power_test.cpp
It's a famous Cata meme, on Zero Day every tire in the world magically explodes. While all the other mechanisms for spawning a vehicle disabled in the game's code are more subtle and natural-looking, the "wreck the tires" code always looks jarring with how it vehicles only ever generate with intact wheels or with all wheels busted. It not only looks odd, but means the player rarely gets to contend with the "unbalanced" and "no steering" conditions.
Along the way, in looking at the code I found myself rapidly being tempted to tinker with the code a bit more to flesh out the variation in spawn conditions further.
In vehicle.cpp, set the `destroyTires` behavior in `vehicle::init_state` to pick wheels to destroy a number of tries equal to the number of wheels it has, instead of intentionally …
=> feat(balance): increase variety of potential damage states for spawned vehicles

.github/workflows/manual-release.yml, .github/workflows/release.yml, tools/copy_mac_libs.py
Add Apple silicon builds. 
Apple silicon Macs are over 70% in May 2024, according to steam's stats.
Added macOS 14 (M1) runner in CI.
Some modifications have been made to copy_mac_libs.py to fix the error that prevented the building on macOS14.
N/A
I ran the CI in my fork; no errors in the macOS related parts.
N/A
N/A
=> ci: add Apple silicon build

data/json/harvest.json, doc/src/content/docs/en/mod/json/reference/creatures/monsters.md
This separates out the JSON and documentation changes that crept into https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4751, which I initially did because they were relevant to implementing and documenting the decay feature. Now that the intended implementation is able to use a monster's harvest entries directly, but also it's left in draft because the implementation has some flaws in it, I figured I'd yoink the now-unrelated updates as a separate PR so they won't be held up by technical issues.
JSON changes: 
1. Fixed several cases of mutant human harvest entries having regular bones instead of human bones.
2. Set most arthopods to have more consistent use of sinew, and more consistent ratios of chitin. Left non-armored centipedes at a lower than standard (but no longer pathetically …
=> feat(balance): consistency updates to harvest entries

src/crafting_gui.cpp
So recently, crafting GUI coloration changed to make recipes that you can attempt to craft despite lacking subskills to show with brown text. This is a Bad Idea, because "item will be rotten due to rotten ingredients" already uses brown texts, and we shouldn't have this ambiguity.
In crafting_gui.cpp, set it so the text color for "could craft if known" is light grey instead of yellow, while using yellow for the "can craft but missing some skills" condition.
Reason is, I found in testing that the "could craft if known" condition also affects the UI of basically the entrire tools and components block. I was wondering why it changed to yellow for stuff you can't craft, and thought it looked utterly hiddeous. I was gonna go with red, but that made it look ugly too.
I decided it'd be less …
=> feat(UI): fix odd coloration of tools/components UI, recipes showing same color as ones using rotten components

data/json/requirements/materials.json
As RoyalFox correctly pointed out in the Discord, having nomex as an option in so many recipes where it would get transmutated into cotton is a big noob trap due to how valuable nomex is. In the event that we had material inheritance, nomex being in fabric_standard would be fine (though still a little bit odd). However, since we don't, I feel it's a good idea to prevent anyone from falling into that trap and wasting their rare and valuable nomex.
Removes nomex from fabric_standard, thereby making it so that a majority of recipes will not have the potential to be a trap for wasting your nomex.
- Continue to allow nomex to be wasted
- Bundle this with the cottonification of the ammo pouches, where it was discovered / talked about
I felt that this was a very different balance discussion, and …
=> feat(balance): Remove Nomex from fabric_standard

src/crafting_gui.cpp
Fix #4750
Passes `show_unavailable` from above. It was most likely set to `false` during porting of DDA changes because it refers to a BN-specific feature. Then possibly forgotten (good idea to `// TODO:` things like this).
1. Open craft menu
2. Press `u` to show unavailable
3. Look at a recipe that you don't know and have no books covering it (but a book exists)
4. Check that it has at least one book
Not fixed here, but related: #4767
=> fix: Re-add missing show_unavailable in recipes

data/json/mapgen/church.json
Consistency.
Replace `t_flat_roof` with `t_rock_floor_no_roof` in `church_3rdfloor_1`.
none
Before:
After:
=> fix: consistency problem with one of the roofs of the gothic church

src/crafting_gui.cpp
- fixes #4767 
- #4713 had a contained PR that affected the crafting GUI keybind prompts, which removed the show unavailable prompt option.
Adds the prompt back to the keybind list.
- Name the keybind "unavailable" rather than "show unavailable".
- I don't actually know which one we had prior to the PR.
=> fix: Add keybind prompt for "Show unavailable"

data/json/recipes/other/materials.json, data/json/uncraft/generic.json
After further research I found out bricks are cut using a metal chisel.
Also noticed the clay pallet material requirement was water OR sheet OR ceramic shards AND light wooden frame.
Bump disassembly requirements of (fire) bricks to Hammering 3 and Chiseling 3.
Made material used to craft clay pallet water AND sheet AND ceramic shards AND light wooden frame.
Downloaded the modified json files.
Overwrote the two relevant game files.
Loaded a character and checked both bricks disassembly reqs and crafting mats for clay pallet.
=> fix: disassembling bricks now require metal tools and clay pallet recipe update

data/json/itemgroups/Weapons_Mods_Ammo/ammo.json, data/json/itemgroups/vending_machines.json
ammo spawned always with their maximum charge, so you always got 80 .22 from a zombie.
now you get a randomized amount between 1-100. So it defaults to 50 (mathematically).
different counts for different ammo types. Shotguns getting 1-50, pistols 1-200. But maybe it gets a tweak in the future.
old
new
=> feat(content): ammo drops in different amounts

src/item.cpp
Fixes #4300
Checked the code against CDDA to see if they handle calculations differently or how they handle this particular issue. They do not have this calculation and it appears to be a BN specific calc only.
Compared the builds in MSYS and Visual Studio to confirm the issue is related to divide by zero and not some other factor.
Tested in MSYS, by running a game, spawning a watch via debug and not seeing negative numbers.
Not needed, reviewing the code should be enough to verify that divide by zero should now be properly handled.
N/A
=> fix: negative values in armor calculations

src/iuse_actor.cpp
So I've been wracking my brain trying to figure out how to fix the annoying as fuck issue where turning a transforming item on or off would unset any assigned inventory letter. Well, after fucking with this all night with no real idea which invlet-related feature was the one I needed to use to fix it, I finally found it.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3818
In iuse_actor.cpp, updated `iuse_transform::use` to call `inv_update_cache_with_item` after it updates the item, which it turns out seems to be the correct function for properly telling an item to update its invlet without doing any weird janky shit. In particular, I found that adding a call to `inv_update_invlet` did NOT work, and tested various over character commands that route an item to an inventory …
=> fix: transforming items no longer forget their assigned hotkey

src/character.cpp, src/monexamine.cpp
This fixes a few more oddities and oversights found with mount behavior.
1. Set it so that mounting a mountable creature that's been tied down is marked with the action "untie and mount", and have it commit the untie action when needed. This fixes a weird bug that happens when you mount a tied-down animal where it puts a duplicate rope in your inventory but then afterward still has the animal leashes when you dismount.
2. Additionally, set it so that the "AI is waiting" effect is no longer a prerequsite for mounting a horse, and set it so that mounting clears that effect. This fixes the issue where you can't re-mount a horse until you've waited a few turns after dismounting, which tends to be annoying if you ever need to dismount to go through a door, pick up an item, etc.
Not touching …
=> fix: fix mounting tied-up creatures, re-mounting recently-dismounted creatures

data/json/mapgen/nested/residential_lawn_nested.json, data/json/snippets/residential_signs.json
Fleshing out residential lawn nested chunk spawn variety, in order to make house spawns more dynamic and try to add a little life and dimension.
Add variant nested chunks that can spawn in backyards, frontyards or both. Also, adding other nested chunks to spawn list that already exist in the game (a few of my roof nested chunks and 3X3 garden plots). Some of these chunks are decorative (gardens), some have tools or vehicles (kayaks, bikes, shovels, etc.), others just have incidental little bits or ambient storytelling (animal spawns, abandoned suitcase, etc.). 
Also added a snippets file for the yard sign spawn.
Linted and spawned in game. Screenshots below.
Currently the front and backyard nested chunks only spawn in house_fence09, bungalow27 and bungalow28. I aim to add these to all of …
=> feat(content): `add residential lawn nested chunk variants'

src/crafting_gui.cpp
I was asked to go ahead and fix the issue where you can't scroll item info in the recipe menu. I was initially going to port https://github.com/CleverRaven/Cataclysm-DDA/pull/44100 as Kenan linked me to that, but it turns out our problem is a lil bit different here. Only one tiny bit of that PR made it into the commit as a result.
1. In crafting_gui.cpp, removed the unused, unbound bindings for `SCROLL_ITEM_INFO_UP` and `SCROLL_ITEM_INFO_DOWN`. Our root problem here is these keybinds were never ACTUALLY used later on in the `select_crafting_recipe` function, hence why they didn't do anything when bound. But, there's a less silly solution we can use here...
2. Set it so that the part of `select_crafting_recipe` that calls `recipe_info_scroll` when you hit the recipe info scrolling keys …
=> fix: recipe scroll command scrolls both component and item info, fix support for page up/down

data/json/monsters/nether.json
Yuggs were giving full animal meat, given that they have a 'gene sting' attack I think it's safe to consider them mutants. This fixes the harvest list to use the mutant_meatslug harvest group instead of the meatslug list. Fixes #4675.
=> fix: Correctly set yugg harvest to mutant_meatslug instead of meatslug.

src/activity_handlers.cpp
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4777 fixed some cases where bleeding or skinning a corpse would still print a "you fail to harvest X" message later on when butchering the corpse, but I forgot that if you skip straight to butchering a corpse without bleeding it you'll still get the message.
1. In activity_handlers.cpp, changed the definition of `already_harvested` inside `butchery_drops_harvest` to also exclude blood if the current butcher action is anything other than bleeding.
2. Because this should accordingly automatically exclude blood from yields of all other butchery actions in the part that handles `already_harvested`, removed the separate if function that processes zeroing out blood yields.
screm
Will test when I get home unless someone else looks at it, doing …
=> fix: don't print message about failing to harvest blood when not bleeding corpse

src/options.cpp, src/vehicle.cpp
This adds a new world option to modify vehicle damage. The purpose is to have a global value to alter initial vehicle health. Vehicles may be more broken than usual with a value > 1  so players may need to scrounge up vehicle parts to get a working one. In comparison the No Hope mod modifies most mapgen JSON files to create wrecks instead of vehicles to achieve a similar effect.
No Hope does it by setting values for "number" such as [ 3, 4 ] inside vehicle_spawn.json. This spawns multiple vehicles on top of each other to create a wreckage. The problem of this solution is that whenever a new map is created that uses "place_vehicles" it would need to be modified. This is hard to maintain and changes to the maps need to be backported.
The multiplication inside this commit is only a very …
=> feat: Basic Implementation for vehicle damage world option

src/character_functions.cpp
This fixes the issue in which you can load a gun with a magazine containing ammo it can't use, such as a stanag full of .300 blackout into an unmodded AR-15, leaving players to get confused when the game lets you do it but then says you're not allowed to shoot afterward.
In character_functions.cpp, updated `find_ammo_helper` so that the section concerning magazines tracks what ammotype the gun uses, as the preceding section for guns with internal mags does, then passes this info to the item visitor. In the statement specifically for magazines, it then asks if that magazine is already loaded, and if so skips over it if the ammotype of the ammo loaded in it doesn't match what the item about to be loaded can use.
Also stripping out the lil bit that tells you you're not allowed to fire the …
=> fix: disallow loading mags with incompatible ammo

data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_ammo.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_magazines.json
jfc why did we bring back the giant blocks of uncommented-out checklists that have zero impact on 90% of PRs again auuuugh, one of these in the required section isn't even relevant to many PRs since not all of them will have a linked issue.
This follows up on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4805 and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4806, implementing a way for guns and magazines to pick at random what ammo is loaded in them, and modernizes how the gun charges are specified. Also comes with a consistency update to speedloader spawns per @Lamandus' request, and a fuckton of related fixes for weird issues found while implementing stuff.
1. Set nested gun spawns to make use of the previously-unused `ammo-group` feature. This, it turns out, has the …
=> feat(balance): nested gun/mag spawns vary in ammo loaded, several fixes

data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json, data/json/monsterdrops/zombie_default.json
CrystalNole over on the BN discord discovered that basic zombies were always dropping fully-loaded magazines when they drop ammo, when the guns an obviously-failed survivor spawned with logically should have some chance of being depleted. Along the way, I decided to also tweak it so the variety of guns that can spawn has a bit wider variety.
1. Removed the default 100 ammo rate for carried guns, needed to allow the following to work.
2. Added `charges-min` of zero to all mag spawns in carried itemgroups. Found this works fine to make magazine spawns, even for magazine groups, vary in ammo spawned even when the same group is used by a stored gun spawn to spawn a full mag.
3. As a bonus, reworked the guns that basic zeds can spawn with. Instead of only ever spawning with pistol or shotgun …
=> fix: magazines dropped by zombies vary in ammocount, expand variety of guns

data/json/items/tool/woodworking.json, data/json/professions.json
Easy PR, fixes spelling for Competitive Fencer and Primitive Axe.
=> docs(content): correct spelling on fencer / primitive axe

data/json/itemgroups/Locations_MapExtras/locations.json, data/json/itemgroups/Locations_MapExtras/locations_mapextras.json, data/json/itemgroups/Weapons_Mods_Ammo/gunmod.json, data/json/itemgroups/Weapons_Mods_Ammo/guns.json, data/json/itemgroups/collections_domestic.json, data/json/mapgen/farm_dairy.json, data/json/mapgen/house/2Story01.json, data/json/mapgen/house/bungalow16.json, data/json/mapgen/isherwood_farms/dairy_farm_isherwood.json, data/json/mapgen/nested/house_nested.json, data/json/mapgen_palettes/house_general_palette.json, data/json/mapgen_palettes/house_w_palette.json
Promised followups to  and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4831, this allows certain previously underused gunmods to finally spawn, and expands on gun safe spawns in houses to re-add mundane safes back in but with actually decent odds of spawning useful shit.
1. Defined itemgroup `house_safe_misc`, a distribution for the sort of random non-gun fluff one might see in a fire safe.
2. Defined itemgroup `guns_safe_pistols`, which bundles all the pistols previously in `guns_safe_guns` so that it can be spawned elsewhere.
3. Replaced separate pistol spawns in `guns_safe_guns` with an equal weight of `guns_safe_pistols`, and created an itemgroup called `house_safe` for smaller fire safes that has a chance to spawn up to two instances of `guns_safe_pistols` specifically, …
=> feat(balance): spawn updates to gunmods and gun safes

data/json/mapgen/house/3Story01.json, data/json/mapgen/house/bungalow02.json, data/json/mapgen/house/bungalow03.json
add dynamic elements to house spawns and file cleanup: 3story01, bungalow02, bungalow03
add house nested chunk spawns, replace redundant furniture entries with palette symbols, generally tidy up each house file.
3story01
- get rid of clothesline in backyard
- replace furniture entry with table_foyer palette symbol
- add res_personal item entry
Bunaglow02
- replaced symbol for back deck fence, eliminating flower spawn error
-  removed clothesline in backyard, added backyard chunk
- removed redundant nightstand entry
- add res_personal item entry
- moved garage back wall one space back to allow more room in garage
- tidied up back wall of garage to allow more room, trimmed down deck to create a better layout
- added res_personal_items symbol
BEFORE
AFTER …
=> feat(content): house chunks and cleanup: 3story01, bungalow 02, 03

src/bionics.cpp, src/character.cpp, src/character_turn.cpp, src/item.cpp, src/ranged.cpp, src/visitable.cpp
This fixes a flaw I found with the advanced UPS not gaining any benefit when used with light power armor like it does for other items, and along the way I ended up deciding to make the efficiency multiplier used elsewhere by advanced UPS a little neater.
On further testing it was found that this mainly applies to power draw values that demand an odd number of charges, which is why light power armor was most strongly affected by this. @KheirFerrum provided a proper fix for that that compensates for odd-number charge consumption when using advanced UPS.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3765
1. In bionics.cpp. converted use of advanced UPS in `Character::consume_remote_fuel` to consume 0.5x charges when using advanced UPS, instead of a janky 0.6x.
2. In …
=> fix: power armor actually benefits from advanced UPS efficiency, adjust efficiency ratio

data/json/itemgroups/Monsters_Animals_Lairs/monster_drops_lairs.json, data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json, data/json/itemgroups/Weapons_Mods_Ammo/guns.json, data/json/itemgroups/Weapons_Mods_Ammo/magazines.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_magazines.json, data/json/items/gun/40.json, data/json/items/magazine/40.json, data/json/uncraft/magazine/45.json, data/mods/Generic_Guns/firearms/gg_firearms_migration.json, data/mods/Generic_Guns/magazines/gg_magazines_migration.json
Addition of another niche weapon. .40 SMG. This time the KRISS Vector. Yes, it is the TDI Vector with new name and other round, but this way we can have the TDI Vector and the KRISS Vector.
1. Add new gun KRISS Vector
2. Add new magazine KRISS Vector magazine
3. Add both in itemlists
4. Add both in spawnlists
5. Add both in merge lists
6. Add magazine in deconstruct recipe.
=> feat(content): new gun KRISS Vector .40

data/json/uncraft/magazine/40.json, data/json/uncraft/magazine/45.json
I missed to add the 2 drums for the glock to uncraft lists. This fixes it.
=> fix: add uncraft recipe for new glock drums

data/json/mapgen/house/bungalow13.json, data/json/mapgen/house/bungalow14.json, data/json/mapgen/house/bungalow15.json
make house spawns more dynamic, also clean up file for: bungalow 13, bungalow 14, bungalow 15
add house nested chunks for backyard, front yard, roof. swap out furniture entries for palette symbols, otherwise remove redundant entries, clean up the file
bungalow 13
- added roof chunks, removed roof furniture
- swapped out table_foyer for palette symbol
- added res_personal_items palette symbol
- removed side kitchen door, added dishwasher
- added swivel chair to office
- randomized carpet pattern for hideous entryway carpet
bungalow 14
- added front yard chunk
- added roof chunk, tweaked roof furniture placement
- replaced table with table fo
- swapped out table_foyer for palette symbol
- added res_personal_items palette symbol
bungalow 15
- changed shed walls to …
=> feat(content): House Nested Chunk Addition, Cleanup: bunaglows 13,14,15

src/map.cpp
I overlooked that blood could still drop as an item from decaying corpses.
In map.cpp, set `map::handle_decayed_corpse` to also exclude the `blood` harvest entry type, as it already does with bionic generation entries.
I actually first tested just giving blood a `drop_action` to convert to a field, but it doesn't seem to trigger for blood you find already on the ground.
Did this while out and about on wifi so haven't been able to test yet, but it's a very basic code tweak.
=> fix: don't drop blood as an item from decaying corpses

data/json/recipes/ammo/rifle.json, data/json/recipes/ammo/shot.json, data/json/uncraft/ammo/5x50.json
This fixes 5x50mm uncrafts generating a mountain of plastic chunks, presumably as a long-forgotten standin for the 5mm plastic casings they've had for a while. Along the way this led to sanity-checking the other Rivtech recipes a bit.
1. Set 5x50 recipes to be made 1 charge at a time and no longer require plastic chunks, as we don't require heaps of plastic to put plastic shotshells back together. Adjusted components accordingly, time was cut in half, kept the plastic mold requirement though. Also made the materials actually match the uncraft a bit better, with the heavy varient needing more lead.
2. Modernized the 8x40 caseless recipes to make 1 charge at a time and use proper crafting requirements, with material costs accordingly divided up. Phased out the use of plastic chunks, and …
=> fix: modernize recipes for Rivtech ammo

.github/workflows/autofix.yml
prevents autofix inconsistencies issues found in PRs such as #3981.
see: https://github.com/autofix-ci/action/releases/tag/v1.3
=> ci: bump autofix to v1.3

data/json/mapgen_palettes/house_w_palette.json
Put dirt floor under the planters in the nested mapgen `greenhouse_6x6_vegetable`.
Modify `house_w_nest_garden_palette`.
none
Before:
After:
=> fix: put dirt floor under the planters in the nested mapgen `greenhouse_6x6_vegetable`

data/json/items/armor/suits_protection.json
Another couple of flags I belatedly realized might logically apply to the military and industrial exos.
1. Added `ALLOWS_NATURAL_ATTACKS` to the military and industiral exos, since these are strapped-layer items that shouldn't be doing stuff like getting in the way of hooves.
2. Added `OVERSIZE` to them. This one I'm a bit less keen on. Logically they should not fall off your body just because you grow a tail, as opposed to the survivor power armor where it's a full-body suit. But right now we don't have stuff like the ALLOW_TAIL and the like item flags DDA has, so for a full-body object like this there's no real way to disallow huge mutants from wearing these while still allowing exo-suit catgirls.
3. @EkarusRyndren pointed out while sharing recent updates with them that waterproof is …
=> feat(balance): add `ALLOWS_NATURAL_ATTACKS` and `OVERSIZE` to relevant exos, remove `WATERPROOF`

data/json/emit.json, data/json/items/comestibles/carnivore.json, src/game.cpp, src/map.cpp
Lil fixes that came about during discussion in the BN server, on discovering that you can still bleed corpses that lack blood, plus some other problems that came to mind during playtesting.
C++ changes:
1. In game.cpp, `butcher_submenu` now properly checks for if a corpse has any blood to take before letting you bleed it, and if not disallowing it just as it does with skinning or field dressing.
2. In map.cpp, changed `map::handle_decayed_corpse` so that rotten harvest yields are excluded automatically. The corpse is already rotting away and hacks around it spawning weird unsightly piles of individual rotten fats.
JSON changes:
1. Went ahead and gave all blood items a `drop_action` coverting them into fields when dumped on the floor. In this case not for decay function hackery, but for …
=> fix: don't try to bleed corpses that lack blood, remove rotten decay results, blood dumped on the ground becomes a field

data/raw/keybindings/keybindings.json, src/overmap.cpp, src/overmap.h, src/overmap_ui.cpp, src/overmapbuffer.cpp, src/overmapbuffer.h, src/savegame.cpp
I was getting pissed off in my desktop playthrough with fast travel always trying to slam me face-first into the back fence of the Isherwood's place instead of going around like a sane person, while also having debug-overmap'd a shortcut I cut through the forest to count as a dirt road so autodrive would go through it, when an idea finally struck for a way to just designate saner paths at will.
Ideal for cases where you really don't want autodrive or the like to go through town instead of taking the field around, too.
C++ changes:
1. In overmap.cpp and overmap.h, defined functions `overmap::path` and `overmap::is_path`, both basically copies of `explored`-related functions.
2. In overmap_ui.cpp, set `draw_ascii` to mark an area that's been designated as a travel path the same way it …
=> feat: map command for marking autodrive/fast-travel shortcuts

src/avatar_action.cpp, src/character.cpp, src/character_functions.cpp, src/item.cpp
This is essentially a followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2881, allowing you to stash items in holsters, sheathes, mag pouches etc using the reload key.
1. In avatar_action.cpp, removed an old "try to reload item in holster" if statement from `avatar_action::reload` that does not actually work anyway. Instead, holsters are now checked in this function for whether they have slots available. If so, prompt to holster an item as the use action does, but skip giving the player the option to draw any other items stashed in it since the entire point of this is a method that lets you skip an extra keypress (and potential extra faffing about with items if you mistype) if all you want is to stash an item immediately.
2. In character.cpp, `Character::can_reload` now …
=> feat: allow stashing items in holsters/sheathes in `r`eload menu

data/json/flags.json, src/activity_item_handling.cpp
This helps deal with the annoyance of needing to manually drop tinder every time you want to start a fire using a fire drill or flint, by rigging firewood sources to check whether they need tinder and prioritize it if so.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4818
C++ changes:
1. In activity_item_handling.cpp, changed `try_fuel_fire` to check if it's starting a fire for the first time in that spot or not. If it is, it then polls whether the tool being used for that task requires tinder, and if so it forces the sorting for loop to completely ignore any firewood source contents that won't satisfy it, instead immediately grabbing the first tinder item in the source it finds, and only taking a single charge of it since that's the most it will need for this.
In addition, …
=> fix: firewood sources now automatically prioritize tinder when using tools that require it
