src/game.cpp
src/player.cpp
src/player.h
src/player_activity.cpp
src/player_activity.h

I've been wanting to merge this PR, but I also agree with the comments in it, so I want ahead and applied them.

Applied some suggestiond from the PR.

---

data/json/recipes/food/dry.json

Those recipes were used to dry frozen food. Since food freezing mechanic is gone they are useless.

Remove useless recipes

---

README.md

Initial Brights Nights readme
Go here to preview it:
https://github.com/Firestorm01X2/Cataclysm-BN/tree/bn-readme
Initial Brights Nights readme
BN needs its own readme.
Inital version of BN readme.

Initial Brights Nights readme

---

README.md

Fix discord link in readme. I've put temporary links by mistake.
Fix discord link in readme. I've put temporary links by mistake.
Fix discord link in readme. I've put temporary links by mistake.
New links provided.

Fix discord links in readme

---

src/sdl_wrappers.h

Fix Visual Studio build via vcpkg
Fix:
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/44
Fix:
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/44
Remove lines:
Cataclysm-BN/src/sdl_wrappers.h
Remove lines:
#include "SDL.h" 
#include "SDL_image.h" 
#include "SDL_ttf.h" 
That was added by mistake.
This includes already present in this file as conditional includes.
Tested via Visual studio 2019 on vcpkj.

Fix Visual Studio build via vcpkg

---

data/mods/No_Acid_Zombies/modinfo.json
data/mods/No_Explosive_Zombies/modinfo.json
data/mods/novitamins/modinfo.json

Deobsolating mods
* No Acid Zombies
* No Explosive Zombies
* No Vitamins 
SUMMARY: [Content] "Deobsolate few mods"
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/66#issuecomment-695787924
1) Enable mods in world creation
2) Game loads correctly
For now No filthy Clothes require additional testing. So it is better to be done in separate PR.

Deobsolate few mods

---

data/mods/No_Filthy_Clothes/modinfo.json

Deobsolate mod No Filthy Clothing
SUMMARY: [Category] "[Briefly describe the change in these quotation marks]"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/59
Deobsolate mod No Filthy Clothing
1) Create world with No Filthy Clothing mod enabled
2) Kill few zombies
3) Observe their clothes. It should not be filthy.

Deobsolate mod No Filthy Clothing

---

src/character.cpp
src/player.cpp
src/player_display.cpp

Set Thirsty limit to 60 and Very Thirsty  to 120
SUMMARY: Balance "Increase overdrinking limit "
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/70
Set Thirsty limit to 60 and Very Thirsty  to 120
1) Observe changing Thirst status

Increase overdrinking limit 

---

data/json/items/book/lockpick.json
data/json/skills.json

Remove lockpick skill leftovers.
Removed skill fron json, Lockpick Book reporpused to mechanincs
SUMMARY: Content "Remove lockpick skill leftovers"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/78
Remove lockpick skill leftovers.
Removed skill fron json, Lockpick Book reporpused to mechanincs
1) Create new character
2) No lockpick skill listed anywhere
1) Load old character
2) No lockpick skill listed anywhere

Remove lockpick skill leftovers

---

doc/MONSTERS.md

Add info about no_crits to DocAdded info about no_crits to documentation
SUMMARY: Documentantion "Add info about no_crits to DocAdded info about no_crits to documentation"
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/65
Add info about no_crits to documentation
Add info about no_crits to documentation
Just usual spellcheck

Add info about no_crits to documentation

---

README.md

SUMMARY: None
Make it easy to see what's different from CDDA.

Link to the wiki page with new changes from the top of the README

---

data/json/items/ammo/40x46mm.json
data/json/items/ammo/40x53mm.json
src/item_factory.cpp

Extending ammo effects
SUMMARY: Bugfixes "Extending ammo effects"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/82
Adding support for "extend" and "delete" for ammo effects.
Used https://github.com/CleverRaven/Cataclysm-DDA/pull/37804 as example
Waiting for https://github.com/CleverRaven/Cataclysm-DDA/issues/36851 to resolve. But it may take months/years.
1) Spawn Milkor MGL / Mark 19
2) Shot with greande launcher
3) Grenade must explode.

Extend ammo effects and Fix Grenade launcher rounds don't explode

---

data/json/npcs/TALK_TEST.json
doc/NPCs.md
src/dialogue.h
src/npctalk.cpp
tests/npc_talk_test.cpp

Hacked in `"npc_first_topic"` from CleverRaven/Cataclysm-DDA#42160
No other features from that PR, though. It depends on other stuff.

npc_first_topic hack

---

data/json/monsters/mammal.json
src/item.cpp
src/monstergenerator.cpp
src/mtype.cpp
src/mtype.h

As in title. Mostly for mods.
Implementation may differ from DDA's. It's rather minimal.

Implement zombify_into

---

src/avatar.cpp
src/character.cpp
src/creature.cpp
src/creature.h
src/effect.cpp
src/effect.h
src/monster.cpp
src/monster.h
src/player.cpp
src/player.h
src/player_display.cpp
src/savegame_json.cpp

Fixes #119
Also makes it possible to remove effects during effect processing.

Centralize effect removal

---

src/character.cpp
src/veh_interact.cpp

Allow using lifting and jacking through walls

---

data/json/items/armor/boots.json

Buff combat boots
SUMMARY: Rebalance "Buff combat boots"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/132
Increase stats of combat boots a bit.
Nerfing regualr boots.
Combare stats of combat boots and regular boots. Combat boots must be better.

Buff combat boots

---

src/newcharacter.cpp

SUMMARY: None
Some small changes/fixes for 'Description' tab of character creation screen:
* Change 'name' field to not look like it's ready to accept keyboard input
* Fix age and height popups require Enter to be pressed twice
Cherry pick relevant commits from CleverRaven#42062
Leaving new players to encounter bugs before even starting their first game
Used the age/height popup, used the text input field

Fixes for the last tab of character creation screen

---

data/json/snippets/health_msgs.json
src/character.cpp

Weight loss is no longer a mechanic.
Also, the messages happened too early.

Adjust hunger messages a bit

---

data/json/effects.json

SUMMARY: Bugfixes "Update linting for effects.json"
This should fix what JSON Validation and Travis are complaining about.
Ran contents of effects.json through online linter. Very simple and easy one.
Complain at Travis instead of letting it do all the complaining.
Online linter not complaining about a syntax error when fed effects,json's contents, game loads as usual.

Run effects.json through online linter

---

data/json/overmap/overmap_terrain/overmap_terrain_river.json

SUMMARY: Bugfixes "Fixed river banks generation"
Fix #138 introduced in 9ffc92ef463aa304df8f4f187810f22f3adb1e64
Use proper mapgen function (cherry-picked from CleverRaven#40217)
Teleported to a river bank before and after the fix. Before it was broken, now it's fixed

Fix river banks

---

src/newcharacter.cpp

SUMMARY: None
Pull some more bugfixes from the mainline
CleverRaven#40996
Opened the 'Traits' tab, played a bit with cursor positions & window sizes

Fix bugs in 'Traits' tab of character creation screen

---

data/mods/Aftershock/items/gun/grenade.json
data/mods/Aftershock/items/weapons.json

Fixes some incompatibilities with specific grenade ammo type
To fix errors and incompatibilities related to vanilla magazine incompatible ammo_type
Change the ammo_type to support vanilla grenade magazines and add extra used ammo to avoid possible incompatibilities
Do nothing
Changing the ammo_type and adding extra ammo for the weapon makes both work properly causing no errors
None

Fix for vanilla incompatible grenade ammo type

---

data/json/items/tool/explosives.json
src/activity_actor.cpp
src/activity_actor.h
src/addiction.cpp
src/bionics.cpp
src/game.cpp
src/iexamine.cpp
src/iuse.cpp
src/magic.cpp
src/map.cpp
src/map_field.cpp
src/mapsharing.cpp
src/vehicle_use.cpp

SUMMARY: None
Removing bugs from the game
CleverRaven#41447
CleverRaven#41743
CleverRaven#42751
CleverRaven#42951
CleverRaven#42933 (squashed with CleverRaven#43003)
CleverRaven#42645
CleverRaven#44102
CleverRaven#44146
CleverRaven#42149
CleverRaven#41631
Seeking dichlorvos
Underwent surgery by the nurse bot - dropped bionic is the correct one.
Drove through a tear in reality in a car - no errors, no teleportations, car is fine.
Tried hacking while Illiterate or when lacking charges for electrohack/bionic - failed, with no time spent; hacking with bionic/electrohack does not crash the game, can still fail or succeed and draws correct amount of charges/power.
Tried starting faulty engine via engine configuration menu - failed, as intended.
Made towing cable snap - message is fixed.
Threw …

Misc bugfixes from DDA 3

---

src/action.cpp
src/action.h
src/character.cpp
src/character.h
src/debug_menu.cpp
src/game.cpp
src/game.h
src/handle_action.cpp
src/item.cpp
src/iuse_actor.cpp
src/magic_enchantment.h
src/map_field.cpp
src/monmove.cpp
src/monstergenerator.h
src/mutation.cpp
src/player.cpp
src/savegame_json.cpp

SUMMARY: Performance "Port minor NPC performance optimizations from DDA"
Port some easy optimizations for an immediate, if small, win in performance.
CleverRaven#44962
CleverRaven#43082
CleverRaven#44083
CleverRaven#44967
CleverRaven#44241
CleverRaven#44242
Waiting in the refugee center went down from 67s/hour to 52s/hour

Port some minor performance improvements

---

src/npctrade.cpp

SUMMARY: None
Fix android build failure on the main branch:
https://travis-ci.org/github/cataclysmbnteam/Cataclysm-BN/jobs/742110859

Fix android build

---

data/raw/keybindings.json
src/character.cpp
src/character.h
src/clzones.cpp
src/debug_menu.cpp
src/debug_menu.h
src/game.cpp
src/item.cpp
src/messages.cpp
src/options.cpp
src/player_activity.cpp
src/player_display.cpp
src/savegame_json.cpp
src/ui.cpp
src/ui.h

SUMMARY: None
Port miscellaneous UI bugfixes and usability changes from DDA.
CleverRaven#40549
CleverRaven#42771
CleverRaven#40447
CleverRaven#43022
CleverRaven#40527
CleverRaven#41559
CleverRaven#44875
CleverRaven#43112
CleverRaven#43472
CleverRaven#43396
Went through every change in-game to make sure it works

Misc UI changes/fixes from DDA 3

---

src/field.cpp
src/map.cpp
src/map_field.cpp

Port DDA's #44013
In my profiled games, I usually see field finding as the biggest cycle hog, so this should be useful here.

Port DDA field performance

---

data/json/items/armor/coats.json

Add collar to emergency jacket
SUMMARY: Balance "Add collar to emergency jacket"
Emergency jacket is defualt item that can be found in default starts. It is definitely helpful for new players and with combination with emergency blanket should help player to be keep warm. There was only one downside it has no collar. And due to game mechanics limitation keeping your mouth warm is not that straightforward. Especially for begginers.
Adding collar to emergency jacket should help with survive at the begining.
Also, logically speaking there is no reason why emergency jacket should not have collar.
Add collar to emergency jacket via json.
None
1) Spawn emergency jacket
2) Check if now it has the collar.
None.

Add collar to emergency jacket

---

src/map.cpp
src/translations.cpp
src/translations.h
src/value_ptr.h
tests/translations_test.cpp
tools/clang-tidy-plugin/TranslatorCommentsCheck.cpp

Closes #173 
This is a port of DDA's #45217. I had to change some bits in `deserialize`, but from what I can tell, it shouldn't ruin the caching.
I didn't profile the performance at the time of writing.

Port of DDA translation caching

---

data/json/mutations/mutations.json
data/json/obsoletion/mutations.json
data/json/professions.json
src/handle_action.cpp
src/map.cpp

Helicopters are boring (among other things) because no one can use them.
Now that everyone can use them, they are a tiny bit less boring.

Let everyone use helicopters

---

build-scripts/build.sh

Don't try to sign Android builds for PRs

---

src/newcharacter.cpp

SUMMARY: Interface "Reduce lag when scrolling in 'Traits' tab of character creation UI"
Lessen the pain
Cache results of `u.has_trait()`, `u.has_conflicting_trait()` and `scenario::is_forbidden_trait()` checks.
Tried various scenarios that forbid traits and combinations of conflicting traits - everything is highlighted properly.

Reduce lag when scrolling in 'Traits' tab of character creation UI

---

data/mods/DinoMod/monstergroups/wilderness.json
data/mods/DinoMod/monsters/dinosaur.json
data/mods/DinoMod/monsters/hatchling.json
data/mods/DinoMod/monsters/juvenile.json

SUMMARY: Mods "difficulty fixes, bleeding, sauropod slumber"
Bugfix, realism improvements, better spawn balance 
Removes DIFF from juveniles and hatchlings, adds BLEEDS to predators, adult sauropods only spawn in forests at NIGHT
Larger content update with newest dinos and locations, pending cleanup in DDA
Simple JSON edits
Thanks to Chaosvolt for catching this bug

[DinoMod] difficulty fixes, let it bleed, sauropod slumber

---

src/main.cpp

SUMMARY: None
Fix compilation for real
It compiles on linux under clang10

Fix compilation

---

data/json/item_actions.json
data/json/items/resources/wood.json
data/json/recipes/recipe_deconstruction.json
src/item_factory.cpp
src/iuse.cpp
src/iuse.h

Move stick-breaking to a deconstruction recipe

---

data/json/monsters/mammal.json
src/creature.cpp
src/map_field.cpp
src/player.cpp

Port miscellaneous balance tweaks that could be good for BN too
Cherry-picked:
CleverRaven#39425
CleverRaven#40647
CleverRaven#41331
CleverRaven#41737
Went through each change and checked that they work

Port misc balance tweaks from DDA

---

src/character.cpp
src/clzones.cpp
src/construction.cpp
src/effect.cpp
src/game.cpp
src/iexamine.cpp
src/item.cpp
src/map.cpp
src/melee.cpp
src/mondefense.cpp
src/monstergenerator.cpp
src/mutation.cpp
src/npc_class.cpp
src/npcmove.cpp
src/overmap.cpp
src/player.cpp
src/player_activity.cpp
src/savegame_json.cpp
src/string_id.h
tests/explosion_balance_test.cpp
tests/overmap_test.cpp

Code maintenance.
The biggest thing is migrating remaining string ids to string_id and forbidding comparisons between strings to string_ids.
See commits.
Let the bit rot prevail
Game compiles. Unless there's a typo somewhere, that should be enough.

Misc code cleanup

---

data/json/professions.json

Fix Bikers should start with motorcycles
SUMMARY: Content "Bikers should start with motorcycles"
Fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/319
Cherry-pick from DDA:
https://github.com/CleverRaven/Cataclysm-DDA/pull/40782
None
1) Start biker profession
2) See if it spawns with bike and multitool now
Also profession description were changed similar to DDA. It looks fancier now.
"Time to ride or die"

Fix Bikers should start with motorcycles

---

src/wish.cpp

1. It now drops them on the floor if there's no space in inventory
2. Added a little message that appears when in 'E'verything mode
3. Fixed prompt for # of items to spawn when spawning everything
4. Fix canceling with 'E'verything mode enabled

Some changes/fixes for debug wish item menu

---

src/activity_handlers.cpp
src/bionics.cpp
src/character.h
src/game_inventory.cpp
src/iexamine.cpp

CBM installation rebalance take 3
SUMMARY: Balance "CBM installation rebalance"
Making  early CBM installation viable option, but with possible consequences.
Working towards:
https://github.com/cataclysmbnteam/Cataclysm-BN/projects/3
1) CBM instllation is now guranteed, but after that failure effects still may appear. So even failed operation gives bionic to player in workable condition. No more wasted bionic, but you still need skills if you want to install bionics without injures or failed bionics in addition.
2) CBM uninstallation works as usual- it can fail completely.
3) Autodoc now can't kill player during operation due damaging body parts. Instead of finally killing player it just add infection on body or head. It still can break limbs, however.
4) Autodoc damage to player body …

CBM installation rebalance take 3

---

data/json/field_type.json

Fix CleverRaven#44042
Ported CleverRaven#44079 + marked a few other fields as invisible

Make hot air invisible

---

doc/COMPILING/COMPILING-CMAKE.md
doc/COMPILING/COMPILING-CYGWIN.md
doc/COMPILING/COMPILING-FLATPAK.md
doc/COMPILING/COMPILING-MSYS.md
doc/COMPILING/COMPILING-VS-VCPKG.md
doc/COMPILING/COMPILING.md

Renaming project name in compiling guides
SUMMARY: Build "Renaming project name in compiling guides"
There are path to CDDA github all over the place. Also project name referenced as Cataclysm-DDA.
Change project name from Cataclysm-DDA to Cataclysm-BN.
Change path from CDDA repo to BN repo.
Other misc changes.
None.
Observe the documentation
doc/COMPILING/COMPILING-FLATPAK.md is not working. Added text about it.
I've intentonally pass few things, that I've not sure. For example directory paths - it is should be examined separately.

Renaming project name in compiling guides

---

src/activity_handlers.cpp
src/activity_item_handling.cpp

Fixes #407
Cherry-picked CleverRaven#44841 and CleverRaven#46020
Provided save file stopped crashing

Port DDA's fixes for mining activity

---

src/veh_interact.cpp

`map::update_vehicle_cache( veh, veh->sm_pos.z )` was called on a deallocated vehicle pointer. The function not only removes the vehicle, but also re-adds it to the cache.
For some reason, it didn't crash before. Then some change uncovered the crash.
This should fix it.

Fix dangling pointer deference on vehicle deconstruction

---

data/json/construction.json
data/json/furniture_and_terrain/furniture-appliances.json

Add a battery charger
Add a charger, which for some reason is not there
Add a recipe
Testing
Build a charging station through construction
Additional context
Made by @4nonch

Add a battery charger

---

data/json/furniture_and_terrain/furniture-tools.json
data/json/items/tool/misc.json
data/json/recipes/recipe_others.json
src/iexamine.cpp

Port grappling hook from dda
Hook activity
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/40834
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/42018
Testing
Activate the hook under the building and climb like a pipe
Have a hook in your inventory and get off the roof

Port grappling hook from dda

---

README.md

Add BN discord to readme
SUMMARY: Documentation "Add BN discord to readme"
Now BN has its own discord server.
Add permanent link to BN discord server: https://discord.gg/XW7XhXuZ89
Readme looks correctly
Rearanged discord servers.

Add BN discord to readme

---

src/player_display.cpp

Summary [Bugfixes]
Delete weight in player UI
Fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/107
Change code
Testing
Start playing and open the character menu

Delete weight in player UI

---

.travis.yml

Apply o3 optimisation to win64 builds and remove separate O3 build
SUMMARY: Build "Apply o3 optimisation to win64 builds and remove separate O3 build"
O3 version reported to be stable and even faster than default win64 version. So it is time make it default win64.
Also it should help to avoid players confusion on what version to choose.
Edit travis.yml
Check if pipleline is correct.
Should I also add OPTLEVEL="-O3" for win32 build?

Apply O3 optimisation to win64 builds and remove separate O3 build

---

data/mods/alt_map_key/overmap_terrain.json

Fix access shaft in alt_map_key mod

---

data/json/vehicleparts/rotor.json

Made helicopter rotors installable.
SUMMARY: [Bugfix] "Helicopter rotors now require mechanics 6, 7 and 8 to repair, uninstall and install, respectively"
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/484
Helicopters are currently completely off-limits due to an artificial skill limitation despite the feature being fully-working. This change alters the skill requirements to make the feature gerally available.
The repair, uninstall and install difficulties were changed from (all three) mechanics 30 to mechanics 6, 7 and 8 respectively.
I have considered making an additional requirement for specialized tools only found in high-risk locations like military bunkers and missile silos, if it proves to be necessary.
1. Spawn damaged helicopter with atleast one working rotor unit, …

Made helicopter rotors installable.

---

src/magic.cpp

Prevent learning invalid spells, forget them on load

---

data/json/furniture_and_terrain/furniture-plumbing.json
src/inventory.cpp

Fix bathtubs not working for crafting

---

src/character.cpp
src/npc.cpp

See commits. Didn't test, but the relevant code is identical, so "should work".

Port a couple bugfixes for bodyparts

---

src/init.cpp
src/map.cpp
src/mapgen.cpp
src/mapgen.h

Port of the C++ part of CleverRaven/Cataclysm-DDA#45184
Needed for #515

Chance to spawn seedling

---

Makefile
build-scripts/build.sh
src/creature.cpp
src/language.cpp
src/language.h
src/stats_tracker.cpp
src/stats_tracker.h
tests/translations_test.cpp
tests/vehicle_efficiency_test.cpp

Includes CleverRaven#40815 to fix GLIBCXX_DEBUG build and CleverRaven#47058 to make UBSan usable.

Fix consistently failing tests

---

data/json/recipes/armor/head.json

This reverts commit 5dcae08f0d3483bc3a20a4520f0a8817749ccd37.
Revert "removed recipes for ir and nv goggs"
SUMMARY: Content "Restore recipes for ir and nv goggles"
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/570
By reverting https://github.com/CleverRaven/Cataclysm-DDA/pull/31372
Ir and nv goggles wer removed, because of realism ( Looks like it was main reason "These are not reasonable things to be able to craft".) and because of fixing some kind of bugs related to some kind of tool mod.
Both reason looks very strange. Espeically considering it is possible to create such googles IRL (Mentioned PR contain links to examples). Even considering possible bugs- removing recepis to solve bugs is not solving any bugs, just hides it.
Receipes itself quite demanding so balance …

Restore recipes for ir and nv goggles

---

src/activity_handlers.cpp
src/iuse.cpp
src/mutation_ui.cpp
src/player.h

Fixes #569 and a couple issues related to Burrowing mutation found during testing.
Couldn't get the noise prompt to show up though.

Fix some issues with jackhammer and Burrowing mutation

---

data/json/furniture_and_terrain/furniture-terrains.json
doc/JSON_FLAGS.md
src/map.cpp
src/map.h
src/mapdata.cpp
src/mapdata.h
src/veh_type.cpp
src/veh_type.h
src/vehicle.cpp

Fix sunlight in vehicles and tents after #581
Fully enclosed vehicles and tents are dark inside, as they used to be.

Port fixes for sunlight fixes

---

src/worldfactory.cpp
src/worldfactory.h

Confirm quit when backtabbing from worldgen menu

---

data/mods/dda/modinfo.json

Update base mod name and description
SUMMARY: Interface "Update base mod name and description"
BN is not DDA.
Avoid player confusion.
Change base mod name and description. Id remain the same for now.
None.
1) Start new game
2) Observe base mod name in world creation menu and loading screen
None.

Update base mod name and description

---

tests/comestible_test.cpp

Port of Kevin's cleverraven/cataclysm-dda#50140 but without the changes regarding test parallelism, which is not available in BN.

Port fix for ASan out of memory problem

---

data/json/mutations/mutations.json
data/json/npcs/starting_traits.json
data/json/obsoletion/mutations.json

Bugfixes: "obsolete Good Memory trait"
Fixes #704 by removing / obsoleting the Good Memory trait as the inverse Forgetful trait was already removed in #89 and no longer serves any real purposes except as a point sink.
Removed from mutations, npc starting traits, added to obsoletion file.
Changing the entire function of the Good Memory trait to something that *is* useful occurred to me, but that feels out of scope here and I don't know what would be appropriate in it's place.
Compiled release build, created new world and character, confirmed trait is removed. Spawned & interacted with NPCs to ensure no apparent unwanted behaviour.
This all assumes the project is moving away from skill rust, or at least as a standard experience. If I got that wrong please let me know!

obsolete Good Memory trait

---

src/start_location.cpp

Bugfixes: "Helicopter crash now correctly skips head & torso damage"
Fixes #684
I found the cause of the error by looking into past PRs on the file in the other branch, and ported in the [fix done in this PR](https://github.com/CleverRaven/Cataclysm-DDA/commit/654bdaa2884a9070eb68f924e46bc11161a52d23). It looks like it was missing the return value for the get_all_body_parts check.
Compiled release build, spawned in ~10 hapless helicopter crash victims, damage is as expected.
Sorry for the flurry of PRs.. fixing the things that bug me as I come across them mostly, and it's kind of fun...

Fix body part check in helicopter crash

---

data/json/flags.json
data/json/items/gun/308.json
data/json/items/gun/50.json

Adds info for MOUNTED_GUN tag and edits desc of guns that use it
Currently MOUNTED_GUN lacks `"info"` and only few guns that has the tag say in description that they require to be mounted before use, this PR adds info about requiring to be mounted and edits the descs of those weapons to avoid thautology.
I've edited flags.json and added `"info"` to `"MOUNTED_GUN"` as well as edited the descs of the weapons that stated that they needed to be mounted before use
Editing description of each weapon that needs to be mounted before use
The screenshot is a bit outdated so the text is different
None

Add info for MOUNTED_GUN tag

---

data/json/itemgroups/Locations_MapExtras/locations_commercial.json
data/json/itemgroups/SUS/domestic.json
data/json/itemgroups/collections_domestic.json
data/json/itemgroups/food_service.json
data/json/items/comestibles/egg.json
data/json/npcs/missiondef.json
data/json/requirements/cooking_components.json
data/mods/DinoMod/DESIGN.md
data/mods/DinoMod/cooking_components.json
data/mods/Magiclysm/cooking_components.json
data/mods/Magiclysm/recipes/recipe_potions.json
src/debug.cpp
src/mission.cpp
src/options.cpp
src/pickup.cpp
src/veh_interact.cpp
src/veh_interact.h

PRs being ported:
https://github.com/CleverRaven/Cataclysm-DDA/pull/40189
https://github.com/CleverRaven/Cataclysm-DDA/pull/49491
https://github.com/CleverRaven/Cataclysm-DDA/pull/49565 (+added "BN" string to display)
https://github.com/CleverRaven/Cataclysm-DDA/pull/49931
https://github.com/CleverRaven/Cataclysm-DDA/pull/40896
https://github.com/CleverRaven/Cataclysm-DDA/pull/43120 + https://github.com/CleverRaven/Cataclysm-DDA/pull/43121

Port a couple tweaks and some fixes, notably for find inhaler & the last delivery missions

---

src/map_field.cpp

Fix fires not falling

---

src/mutation.cpp
src/player_hardcoded_effects.cpp

Fix mass mutation spam in OLD_MUTS mod

---

src/pickup.cpp

I changed meaning of `count`, from "0 is a magic number meaning all" to "0 means 0, empty optional means all", but for some reason set the default to 0 instead of empty optional.
So autopickup did match things, just that it picked up 0 of them.
Fixes #761

Fix autopickup

---

data/mods/No_Reviving/modinfo.json

Blacklist necromancer in no zombie rez mod

---

src/recipe.cpp

Fixes #721
It's a hard error because all other recipe problems throw errors. Meaning that it breaks compatibility with mods that have the problem.

Throw error when recipe has diff>0 but no skill set

---

data/json/recipes/armor/suit.json

SUMMARY: Bugfixes "Fix assembly of plate armor from components"
While working on something for Cataclysm++ involving the survivor plate armor item, I noticed that assembling plate armor didn't actually have autolearn. As a result, it would only ever be learned if the player spawned with 3 or more fabrication.
Gave autolearn to the assembly recipe for plate armor, in which the relevant components are brought together.
1. Continue to procrastinate.
2. Ping whoever finally fixed it in DDA.
Poked it to make sure it didn't scream at me about lint or syntax issues.
They fixed it in DDA at some point, unsure what PR that was in.

Fix assembly of plate armor only learning via chargen

---

data/json/effects.json
data/json/obsoletion/effects.json
src/bionics.cpp
src/game.cpp
src/iuse.cpp
src/player_hardcoded_effects.cpp
src/trapfunc.cpp

Tetanus is the single biggest source of "do I have parasites?" questions and even some bug reports.
Its sources are stupidly specific to terrain and some traps. You can never get it from scratches by zombies, but you can get it from thorns on a rose.
As an with vastly disproportionate penalty on unspoiled players (compared to spoiled ones) and only vague hints, it's badly designed.

Obsolete tetanus effect

---

data/json/loot_zones.json
src/activity_item_handling.cpp

SUMMARY: Features "Add ignore favorite zone"
That way we can keep favorite items on a stack somewhere. Cherry pick from https://github.com/CleverRaven/Cataclysm-DDA/pull/44982
His solution is good.
not adding it.

Add "ignore favorites" zone

---

src/clzones.cpp
src/game.cpp

SUMMARY: Interface "Zones are now sorted by name"
Cherry picked https://github.com/CleverRaven/Cataclysm-DDA/pull/46054 . QoL is always a good addition!
Copy pasting code.
not copy pasting code
someone has to do it for me... chaos pretty pleaaaase

Zones are sorted by name

---

data/raw/keybindings.json
src/bionics.cpp
src/bionics_ui.cpp
src/character.h
src/creature.h
src/enums.h
src/savegame_json.cpp
src/uistate.h

PRs being ported:
https://github.com/CleverRaven/Cataclysm-DDA/pull/41625
https://github.com/CleverRaven/Cataclysm-DDA/pull/42296

Port fix for connectors in bionics UI + ability to sort bionics list

---

data/json/itemgroups/books.json

Porting over https://github.com/CleverRaven/Cataclysm-DDA/pull/41205/commits
SUMMARY: Bugfixes "Several recipe books never spawn, making recipes impossible to perform."
Fixes #850
~The `"sweets_book"` doesn't spawn here or in DDA either so I just left it alone for now.~ I added the sweets cookbook to the relevant book groups. (And reported it to DDA's github)

Adding missing cookbooks

---

data/json/items/comestibles/drink.json
data/json/items/comestibles/other.json
data/json/recipes/food/brewing.json
data/json/recipes/recipe_food.json
data/json/requirements/cooking_components.json
tests/iteminfo_test.cpp

SUMMARY: Content "Bring sweetened tea and coffee to BN"
It was my first pull request in DDA, so why the heck not should it also be a part of BN. Adds sweetened coffee and tea variants to the game, which have a bit higher enjoyability than their non sugar counterparts.
drink tea without sugar
works fine
Squashed rebase, since it won't let me "normal squash"

Adding sweetened tea and coffee

---

data/json/items/comestibles/carnivore.json

SUMMARY: Bugfixes "Fix jerky counting as raw, unlike smoked fish and related items"
Noticed that jerky was showing as having the raw flag, and realized that was why it had reduced calories. Looked at how salted fish is set to delete the raw flag and also found that it's been fixed in DDA, so might as well.
Set it so jerky doesn't count as delicious raw meat.
Looking at the code, adding `EATEN_HOT` might also technically fix it, but this is how salted fish is set up so this works too.
Checked for syntax and lint errors, ported changes to my test build to confirm my stash of jerky was considered edible now.
DDA PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/48867

Fix jerky counting as raw

---

data/core/basic.json
data/json/flags.json
data/json/items/chemicals_and_resources.json
data/json/items/comestibles/alcohol.json
data/json/items/comestibles/brewing.json
data/json/items/comestibles/drink.json
src/activity_item_handling.cpp

SUMMARY: Features "Water and chemical continuations (soapy water) etc. won't be autoconsumed, add flag unsafe_consume"
Water in auto consume areas were considered trinkable. Now it will just sit there and won't ask you 10000+ times until you drink it.
Add Flag unsafe_consume add it to water and some other things. Can be expanded to others as well.
drink murky water
Should work.

Water, alcohol and other unsafe to consume stuff won't be autoconsumed, add flag unsafe_consume // Anti-Slav Patch extended

---

data/json/vehicleparts/boards.json
data/json/vehicleparts/cargo.json
data/json/vehicleparts/frames.json
data/json/vehicleparts/lights.json
data/json/vehicleparts/mirrors.json
data/json/vehicleparts/motor.json
data/json/vehicleparts/seats.json
data/json/vehicleparts/tanks.json
data/json/vehicleparts/vehicle_parts.json
data/json/vehicleparts/wheel.json

SUMMARY: Balance "Change required skills for a lot of vehicle instalation and removal, to better kickstart mechanics"
It was always a chore to get mechanics to 1 or 2. Some things didn't make sense outright, like you needed mechanics of 2 to remove hand paddles from a boat. Also changed, that removal is as difficult or easier than installation, so you don't softlock yourself out of your built vehicle when installing something.
Changing a lot of skill requirements to make it a bit more sense and smoother.
leaving as is.
I tested it a bit, and it looks fine. I would like to have some feedback if any of these skills are either too hard now or too easy.

Revamp of mechanics skill (vehicle parts)

---

data/json/construction.json
data/json/recipes/basecamps/recipe_modular_canteen/recipe_modular_canteen_common.json
data/json/recipes/basecamps/recipe_modular_firestation1.json

SUMMARY: Balance "Remove shoveling lvl1 from construction of smoking rack"
A smoking rack can also be constructed indoors, while not very safe, it is possible. So a shovel is something not needed to create a rack. 
Removing shovel from requirements.

Remove shoveling requirement in construction of smoking rack

---

data/json/recipes/recipe_others.json
data/json/recipes/recipe_weapon.json

Bugfix "remove duplicate tongs from 2 recipes"
Two recipes had blacksmith standard (which have tongs included) and tongs as extra tool needed, creating an duplicate entry in the crafting menu.

remove duplicate tongs from 2 recipes

---

src/item.cpp
src/requirements.cpp
src/requirements.h
tests/iteminfo_test.cpp

Port of https://github.com/CleverRaven/Cataclysm-DDA/pull/41355

Show tool requirements in 'Disassembly' section of item info

---

src/veh_interact.cpp

Show cursor coords in vehicle UI when in debug mode.

Show cursor coords in vehicle UI when in debug mode

---

.github/workflows/astyle.yml
.github/workflows/clang-tidy.yml
.github/workflows/json.yml
.github/workflows/matrix.yml

Cherry-picked from the following PRs:
https://github.com/CleverRaven/Cataclysm-DDA/pull/46361
https://github.com/CleverRaven/Cataclysm-DDA/pull/46272
https://github.com/CleverRaven/Cataclysm-DDA/pull/49924
https://github.com/CleverRaven/Cataclysm-DDA/pull/49933
https://github.com/CleverRaven/Cataclysm-DDA/pull/49964
https://github.com/CleverRaven/Cataclysm-DDA/pull/49923
https://github.com/CleverRaven/Cataclysm-DDA/pull/50042
https://github.com/CleverRaven/Cataclysm-DDA/pull/50076
https://github.com/CleverRaven/Cataclysm-DDA/pull/50109
https://github.com/CleverRaven/Cataclysm-DDA/pull/50129
https://github.com/CleverRaven/Cataclysm-DDA/pull/50147
Played a bit with the final result on https://github.com/olanti-p/Cataclysm-BN/pull/4, didn't notice anything weird (except GA spamming my mail …

[DDA Port] Cancel outdated workflows, run json/astyle/tidy workflows only when relevant files change, reduce fetch depth when possible

---

data/json/items/tool/cooking.json
data/json/items/tool/deployable.json
data/json/items/tool/electronics.json
data/json/items/tool/entry_tools.json
data/json/items/tool/fire.json
data/json/items/tool/firefighting.json
data/json/items/tool/fishing.json
data/json/items/tool/handloading.json
data/json/items/tool/knives.json
data/json/items/tool/landscaping.json
data/json/items/tool/lighting.json
data/json/items/tool/masonry.json
data/json/items/tool/med.json
data/json/items/tool/metalworking.json
data/json/items/tool/misc.json
data/json/items/tool/pets.json
data/json/items/tool/radio_tools.json
data/json/items/tool/raincatchers.json
data/json/items/tool/science.json
data/json/items/tool/shelters.json
data/json/items/tool/smoking.json
data/json/items/tool/stationary.json
data/json/items/tool/tailoring.json
data/json/items/tool/toileteries.json
data/json/items/tool/traps.json
data/json/items/tool/woodworking.json
data/json/items/tool/workshop.json

SUMMARY: Infrastructure "category for every tool and change of type depending on charges"
System of type and category was all over the place.
Everything that doesn't have ammo or needs charges is nor Generic type. Everything else is TOOL. Everything also got a category, so if the type should change, the category stays the same. Also standartize the position of where the category and type is.
Game loads up fine after getting rid of some errors here and there.
I hope people who add new stuff will remember this. Keep it clean!

category for every tool and change of type depending on charges

---

data/json/items/vehicle/wheel.json

SUMMARY: Bugfix "car wheels are now rubber+steel"
wheels were rubber+plastic before, now they contain rubber

car wheels are now rubber+steel

---

data/json/uncraft/vehicle/wheels.json

SUMMARY: Features "wheels can be uncrafted to scrap metal and rubber chunks"
Wheels couldn't be uncrafted. This will add the recipe for doing so. Metal saw needed.

wheels can be uncrafted to scrap metal and rubber chunks

---

data/json/items/armor/ammo_pouch.json

SUMMARY: Balance "Give Javelin bag better encumbrance rates"
Javelin bags were niece from the start, since they also use the backpack layer. But the values were way off for what they actually provide. This should fix it.

Give Javelin bag better encumbrance rates

---

data/json/construction.json
data/json/furniture_and_terrain/furniture-appliances.json

SUMMARY: Content "Make upgraded solar panels installable to grid"
This will make solar panels installable to the grid. It will provide more energy than regular ones.

Make upgraded solar panels installable to grid

---

data/json/construction.json
data/json/furniture_and_terrain/furniture-appliances.json
data/json/items/fake.json

SUMMARY: Content "Add possibility to connect soldering iron to grid"
This will make it possible to connect a soldering iron to the electric grid. You can move over the tile the soldering iron is placed upon.
soldering irons can be placed and used for crafting.

Add soldering iron to grid

---

data/json/construction.json
data/json/furniture_and_terrain/furniture-appliances.json

SUMMARY: Content "make vehicle welding rigs placable in grids"
This makes vehicle welding rigs also placable in grids. Since we can't use makeshift arc welders in grids, this should do the trick. The extra hoops will provide at least some work to make makeshift arc welders grid ready.

Make vehicle welding rigs placable in grids

---

data/json/recipes/chem/drugs.json
data/json/recipes/chem/other.json
data/json/recipes/other/materials.json
data/json/recipes/other/medical.json
data/json/recipes/weapon/explosive.json

SUMMARY: Content "Add phenol into recipes."
Phenol right now has no uses. It is clutter. Removing it is also not an option, since (at least) one mod is using it.
Phenol is used to make aspirin. Recipes we have used aspirin because of the qualities of phenol. So that's why I add Phenol to aspirin recipes. I checked multiple homepages. Most uses of phenol is used there. Now the description is actually correct!
I use 10 phenol = 1 asperin. So 10 ml of phenol is like one ASS. To be honest, that is just a balancing guess. Labs spawn 750 ml bottles of it here and there. So that is 75 aspirin per bottle. I am open to tweaks.
No errors.

Give phenol uses in Mainline

---

data/json/furniture_and_terrain/terrain-railroads.json

SUMMARY: Balance "Make railroad tracks passable for vehicles."
Due to move_cost 3 railroad tracks can't be crossed with vehicles. This changes it, so it is passible.
Why? We don't have any pedesterian walk curbs. And we can go on and off them just fine. So why not tracks as well?
Bonus: Derailed vehicles can be now set back on the tracks, which wasn't possible before

Make railroad tracks passable for vehicles

---

data/json/itemgroups/supplies.json
data/json/items/chemicals_and_resources.json
data/json/obsoletion/items.json

SUMMARY: Content "Obsolete Acrylamide"
It has no use in our game. Sure, it is carcinogenic, but does it really has a place in the game?... It is used to make water solvent plastics. Nothing of use for us.

Obsolete Acrylamide

---

data/json/recipes/other/materials.json

SUMMARY: Bugfixes "remove manure from crafting"
Part 1 would be Aluminium Sulfate replacing manure in liquid fertilizer. This will remove it from adobe bricks as well.

Remove Manure from Crafting (Part 2)

---

data/json/vehicleparts/cargo.json

SUMMARY: [Category] "[Briefly describe the change in these quotation marks]"
Revert of https://github.com/CleverRaven/Cataclysm-DDA/pull/22791 . Shopping cart were always a fun way to come around. Now add an engine and with some luck, you are able to breeze through the town, no problem
Make shopping basket boardable again, the same like wooden boxes are already and always have been.

Make shopping baskets boardable again.

---

data/json/flags.json
data/json/items/resources/plastic.json
data/json/items/tool/deployable.json
data/json/items/vehicle/tables.json
data/json/recipes/other/tools.json
data/json/vehicleparts/vp_flags.json
src/activity_handlers.cpp
src/activity_item_handling.cpp

SUMMARY: Features "QoL changes for butchering and lowering requirements for metal rack crafting"
Butchering something was always a hassle. When something was too big, you needed a lot of preperations to get stuff running.
1. Butchering racks don't need to be deployed, they can be near (ground/vehicle cargo) or in your inventory.
2. Tarps, tourist tables, tables don't need to be deployed, they can be near (ground/vehicle cargo) or in your inventory.
3. Saws are not necessary anymore
4. Crafting a metal butchering rack now requires FAB 3 (was 4), no Anvil, no Screwdriver, but takes double the time (30->60 min), hammer quality 3->2
5. (Long) Ropes don't need to be in inventory to be used for hanging something (butchering)
Tested all possible combinations. It worked out as intended.

Butcher changes (QoL and some)

---

data/mods/Aftershock/mod_tileset.json

Fixes #1080.
Also checked other mods, but thankfully none of them have this issue.

Fix Aftershock's mod_tileset compatibility list

---

data/json/recipes/other/materials.json

SUMMARY: Bugfixes "Fix knitting felt patches using thread instead of yarn"
Quick and easy fix for a mistake that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1065 helped me notice.
Changed the recipe for knitting felt patches to use `tailoring_wool_knitting` instead of `tailoring_cotton_knitting`, duh. That was a copypasta fuckup on my end.
Continuing to procrastinate on an easy fix, and/or letting someone else try to obsolete the recipe again.
PR where I made said mistake would be: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/859

Fix felt patch knitting using thread instead of yarn

---

data/json/items/tool_armor.json

SUMMARY: Bugfix "Fix "Unloading" and "Reloading" of batterypower of the smart watch"

Fix Smart watch

---

data/json/mapgen/regional_airport.json

Hotfix to wrong spawn group name related to helicopters
SUMMARY: Hotfix "Hotfix to wrong spawn group name related to helicopters"
I've renamed helicopter group part and forgot to do it in one place.
Fix group name.
1) Check group name it should be `civilian_helicopter_parts` but not `supplies_civilian_helicopter`
I've surprised that there was no warnings.

Hotfix to wrong spawn group name related to helicopters

---

.github/workflows/check-translation.yml
.github/workflows/matrix.yml
.github/workflows/push-translation-template.yml
.gitignore
build-scripts/requirements.sh
lang/CMakeLists.txt
lang/compile_mo.sh
tools/check_po_printf_format.py

Ports of:
* cleverraven/cataclysm-dda#48530
* cleverraven/cataclysm-dda#50605
* cleverraven/cataclysm-dda#50808
Should make translation source more up to date.

Port translation automation

---

data/json/professions.json
data/mods/Aftershock/player/professions.json
lang/extract_json_strings.py
src/profession.cpp
src/translations.cpp
src/translations.h
tests/translations_test.cpp

Should help with cases such as in #1142

Allow specifying translation context for profession names

---

data/json/items/armor/arms_armor.json
data/json/items/armor/boots.json
data/json/items/armor/gloves.json
data/json/items/armor/helmets.json
data/json/items/armor/suits_protection.json
data/json/recipes/armor/arms.json
data/json/recipes/armor/feet.json
data/json/recipes/armor/hands.json
data/json/recipes/armor/head.json
data/json/recipes/armor/suit.json

SUMMARY:  Balance "standardise chitin armor crafting levels, adding leather."
Chitin armor is quite good. It has only the caveat of being 95% coverage, which makes it a bit worse than a survivor suit. So it shouldn't be harder to craft than it counterpart.
The armor made of acid ants also got a little faster to craft.
All parts of the armor is now unlocked in the same time. So all chitin parts are available at lvl 6 instead of being spread between different levels.

standardise chitin armor crafting levels, adding leather.

---

data/json/items/comestibles/med.json

SUMMARY: Bugfixes "Fix snorting cocaine requiring ability to smoke crack"
Quickfix for a copypasta error introduced by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/773 causing regular cocaine to require smoking it like crack.
Removed the need for fire and an apparatus from the use action for cocaine, and no longer creates crack smoke.
Blowing off an easy fix for blow.
Checked file for syntax and load errors.
https://cdn.discordapp.com/attachments/348598573220495361/924217390751944734/Snaptik_7040379441335471407_o.mp4

Fix snorting cocaine

---

data/json/recipes/other/materials.json

SUMMARY: Bugfixes "Fix old leather recipe being overridden by new one"
Simple fix for something caused by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1164, as a recipe for leather patches without an ID suffix already existed.
Changed the "turn fur patch into leather patch via shaving" to have an ID suffix, so it goes back to existing instead of automatically being eaten by the new "tan hides directly into leather" recipe.
Putting off an easy fix until someone else spots it.

Fix "leather from fur" recipe lacking id suffix

---

data/json/recipes/food/bread.json

SUMMARY: Bugfixes "Fix brioche to have craft time"
Brioche didn't require any batch time to craft. This will fix it, now having 30 min.
Adding batch time 30 minute to brioche recipe
Maybe the time can be changed. Since I'm not good at baking, so got the time from here https://www.bbcgoodfood.com/recipes/brioche
Not yet.

Fix brioche to have craft time

---

data/json/vehicleparts/vehicle_parts.json

SUMMARY: Balance "Update vehicle heater install location for usability, consistency with coolers"
On watching a recent video by Critsybear I noticed an oddity with vehicle heaters, observed when he had trouble figuring out where it was supposed to be installed. It turns out this was due to it occupying the center slot, which was odd given it doesn't block movement. The item size is also much smaller than most utilities that occupy that slot, being crafted from a "large" heater that is nonetheless still portable. The vehicle-mounted cooler in contrast is the same item size, but goes on the roof.
Changed the slot used by vehicle-mounted heaters from `center` to `on_ceiling`, under the reasoning that this allows it to be mounted in a better variety of locations. Coolers use `on_roof` since …

Set vehicle heater to be less hassle to mount

---

.tx/config

Routine i18n updates on 25 December 2021

---

src/character.cpp
src/character.h
src/creature.cpp
src/creature.h
src/item.cpp
src/item.h
src/weather.cpp
tests/player_test.cpp
tests/weather_test.cpp

Fixes #1167
Now, fixing it was 10 minutes, but then I noticed that they don't protect from windchill, making it harder to calculate things. This took me more time.
But then, I noticed that windchill calculations are broken really hard around 50F - when going from 49F to 50F, body temperature actually drops considerably. After much testing, I found that the formula itself has an `if(temperature < 50F) {formula_1();} else {formula_2();}` block and they give completely different results, with formula for 50F consistently giving -7.2F windchill for 0 windspeed, but formula for 49F giving exactly zero.
The windchill formula was broken pretty hard and this may have resulted in some of the "why am I freezing in spring" posts. New one is sanity-checked with a test to ensure it doesn't have any …

Fix hoods, collars, pockets and windchill

---

data/json/recipes/other/materials.json

SUMMARY: Bugfixes "Fix bronze recipe allowing sealed cans instead of open ones"
That's a fuckup on my end from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1077 where I ported over allowing aluminum for bronze, but forgot that `can_drink_unsealed` is no longer a thing in DDA due to nested container stuff.
Fixed bronze recipe using sealed cans instead of unsealed ones.
Screaming.
Checked affected file for syntax and load errors.

Fix bronze recipe using wrong type of can

---

data/json/items/tool/med.json
data/json/vehicleparts/vehicle_parts.json

SUMMARY: Balance "Adjust autoclave power draw to sane levels, give it magazines that actually provide enough power"
After a brief misadventure with a bug that seems to no longer be present, I decided since I was already on the subject of autoclaves due to it I might as well tackle them.
1. Lowered power draw of autoclaves from 1500 watts to 1000. This makes it so it will eat up 5400-5500 power, an amount that medium storage batteries can cover it. Looking into it, I can find examples of steam autoclaves with as low as 900 watts and this is clearly a smaller model, but 1000 is a reasonably even number.
2. Changed what magazines it uses to storage batteries, medium storage batteries, and large storage batteries. Even at this reduced power draw it would still be far too much for every heavy …

Fix autoclave power draw, change magazines used

---

data/json/items/tool/lighting.json

SUMMARY: Bugfixes Fix lit candles have same name as regular ones"
Easy fix, no idea why it was ever like this in the first place.
Set it so a lit candle has an actually different item name from unlit ones.
Grumbling about it affecting the few mods that use candles for recipes without actually doing anything about it.
The usual check for syntax and lint errors.

Fix lit candles have same name as regular ones

---

data/json/obsoletion/recipes.json
data/json/recipes/armor/feet.json
data/json/recipes/armor/head.json
data/json/recipes/armor/storage.json
data/json/recipes/recipe_deconstruction.json

SUMMARY: Bugfixes "Fix it so straw items can't transform birchbark into straw"
An easy fix I remembered while poking through old issues. This fixes some cases of transmutating birchbark into straw via recipes that had uncrafts set for no discernible reason.
1. Changed recipes for straw basket, straw fedora, straw hat, and straw sandals to simply be reversible.
2. Obsoleted uncrafts for the above items.
Going to bed because it's like 3:30 AM as of this PR's OP.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1132

Fix straw items allowing transmutating birchbark

---

data/json/recipes/other/tools.json

SUMMARY: Bugfixes "Fix hobo stove recipe using sealed cans"
Another whoops caused by forgetting cans in DDA work differently.
Set it to use opened medium cans, not sealed ones.
Screaming.
Hobo stove actually craftable.

Fix hobo stove using wrong can type

---

README.md
data/motd/de.motd
data/motd/en.motd
data/motd/ru.motd
data/motd/zh_CN.motd

Update links for Readme and motd
SUMMARY: Documentation "Update links for Readme and motd"
Updating links and removing old ones.
Some motd missing bn discord links.
Currently we don't have presence on new DDA  discord but some links in motd still pointing on DDA discord.
Also there are some other links that point on pure DDA resources.
It should be corrected.
Correct the links.
None
1) Double check links.
None.

Update links for Readme and motd

---

data/json/recipes/weapon/ranged.json

Fix crafting requires sunglasses instead of welding goggles
SUMMARY: Bugfixes "Fix crafting requires sunglasses instead of welding goggles"
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1269
Fix the recepie. Pipe combination gun should requre glare protection 2, because it is require welding
None.
1) Check if pipe combination gun now requre glare protection 2 instead of 1.
None.

Fix crafting pipe combination gun requires sunglasses instead of welding goggles

---

.github/workflows/release.yml
Makefile
tools/copy_mac_libs.py

SUMMARY: Bugfixes "Merge possible osx fixes"
Try to fix:  
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/524
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1297
Manually merge:
> Possible fix: CleverRaven/Cataclysm-DDA#50234
> May be relevant: CleverRaven/Cataclysm-DDA#49595
> Might also need CleverRaven/Cataclysm-DDA#50560 going off of its description.
1) Check build?
2) Suppose that it is tested in DDA?
Suppose that it is tested in DDA?

Merge possible osx fixes

---

data/json/scenarios.json
data/json/start_locations.json

Content "Add Town Hall to Surrounded Start"
I like the town hall building and thought it would be nice to be able to spawn there. 
Add a town hall start location.
Add it to the Surrounded Scenario.
Making a new town hall scenario that limits your professions to those that have a decent reason to be at a town hall normally?
Put it in a start location mod? Or ask one of the existing start location mods if I could add this to it.
I ran the CDDA Linter on both changed files. I couldn't find an CBN specific one? Although if there is one I would be fine running that.
I also playtested that it ran on the newest experimental without error and that I was able to escape town from a town hall start.

Add Town Hall to Surrounded Start

---

data/json/furniture_and_terrain/furniture-zztesting.json

SUMMARY: Balance "Reduce enegery consumption of the floor lamp"
Right now the floor lamp uses up to 50 watt. This reduces it to around 10 watt.

Reduce energy consumption of the floor lamp

---

doc/COMPILING/COMPILING-VS-VCPKG.md

A few people already stumbled into the trap known as "new shiny Visual Studio 2022", add workaround to the docs to prevent confusion in the future.
Once vcpkg fully supports VS2022 and its freetype library receives an update that fixes font problems for us, this workaround could probably be removed.

Add compilation instructions for Visual Studio 2022

---

data/json/bionics.json
data/json/items/bionics.json

SUMMARY: Balance "Change Telescopic Eyes CBM to focus on vision problem traits only"
Was finally talked into tackling this basic change to the infamously-annoying eyeball CBM.
1. Set it so the telescopic eye CBM only removes vision mutations relevant to its function as a set of implanted corrective lenses. Most vision mutations would involve changes to cone/rod cells, the retina, the development of tapetum lucidum, etc. Basically the majority of useful mutations would involve the back of the eye, in contrast to Near-Sighted and Far-Sighted which are issues mainly with the lenses (i.e. the front of the eyes).
2. Updated name and description of Telescopic Eyes to fit the idea of it being more like Telescopic Lenses instead. Item description also notes that it can't be removed once instead. …

Telescopic Eyes no longer affect night vision

---

src/mutation_type.cpp

Port https://github.com/CleverRaven/Cataclysm-DDA/pull/48094 : Don't copy mutation branches unecessarily
Adds `const ... &` in mutation iteration.
Makes chargen UI a bit faster.
Compiles.

Port "Don't copy mutation branches unecessarily"

---

src/map.cpp

Another attempt at fixing win64 build failing with impossible/invalid warning:
```C++
src/map.cpp: In member function 'bash_results map::bash_ter_furn(const tripoint&, const bash_params&)':
src/map.cpp:3438:58: error: 'sound_fail_vol' may be used uninitialized in this function [-Werror=maybe-uninitialized]
"smash_fail", soundfxvariant );
```

Another win64 fix attempt

---

data/json/vehicles/farm.json

SUMMARY: Balance "Give horse wagons reins and tackle instead of unnecessary vehicle controls"
Simple change to make use of rein and tackle for its intended purpose after confirming it actually works to control animal-powered vehicles.
Replaced the fancy modern vehicle controls on covered wagons with appropriate rein and tackle part.
1. Continuing to wonder why an old wagon with no electronics on it has automatic transmission or whatever vehicle controls presumably add.
2. Going in the opposite direction and giving wagons a security system for the lulz.
2. Faffed about in a wagon with the controls swapped to confirm it can be operated this way.
One thing I'm once again bugged by: the wagon lets you exceed 16 MPH, and claims its safe …

Give wagons reins instead of controls

---

src/character.cpp

SUMMARY: Bugfixes "Fix typo for bear trap in character.cpp"
Fix #1360

Fix typo for bear trap in character.cpp

---

data/json/flags.json
data/json/items/gunmod/underbarrel.json
src/item.cpp
src/item_factory.cpp
src/itype.cpp
src/itype.h
src/ranged.cpp

SUMMARY: Bugfixes "Fix bayonets breaking gun mode selection and pistol bayonet not working"
Rewrote the gun mode selection to avoid the ugly offset math thing.
Added a flag for bayonets so that they don't need a reach attack mode to work.
* Spawn gun+bayonet+rail xbow and attach mods to gun
* Change firing modes from aim menu to see if all can be picked
* Test modes to see if they work
* Spawn a pistol bayonet and attach it to a pistol
* Look at the statblock to see that it has pierce damage listed

Fix bayonets breaking gun mode selection and pistol bayonet not working

---

.github/workflows/release.yml

SUMMARY: Build "Fix GH mingw release build"
Fix windows mingw build
Update apt cache before installing dependencies
Works on my fork https://github.com/olanti-p/Cataclysm-BN/releases/tag/cbn-experimental-2022-04-03-1647

Fix windows mingw release

---

src/activity_actor.cpp
src/game.cpp
src/game.h
src/item_location.cpp
src/item_location.h
src/player.cpp
tests/reload_on_location_test.cpp

SUMMARY: Bugfixes "Fix crash when trying to reload item on vehicle"
Fix #1472
Stricter (possibly slower) checks on favorite ammo. Should not be slow enough to matter.
Hacky.
Tried reloading UPS with batteries on my save and earlier save provided by user who had the first UPS crash happen.

Fix UPS reload crash again

---

src/mondeath.cpp

SUMMARY: Bugfixes "Fix debugmsg when overkilling half-worms"
Fix #1459
Splatter death function had type mixup and a missing check.
Disable all the null field messages and go back to unclear responsibilities and silently tolerating bugs.
Shoot a bunch of half-worms with a .50 cal rifle.

Fix worm null blood debugmsg again

---

data/motd/ko.motd

SUMMARY: I18N "Update outdated korean MOTD"
MOTD for korean is very outdated (0.C Cooper)
Translated everything again using current english MOTD as reference
None
All links copy-pasted from english MOTD
how the changes look like:

Update outdated korean MOTD

---

data/json/obsoletion/mutations.json

SUMMARY: Bugfixes "Remove mutation categories from obsoleted mutations"
Easy fix, makes sure you can't get Pain Recovery and the like from medical mutagen.
Removed mutation categories from all mutations in obsolete folder.

Remove category from obsolete mutations

---

data/json/furniture_and_terrain/furniture-medical.json

SUMMARY: Bugfixes "Allow actually getting an autoclave via deconstruction"
This simply splits off a misc. JSON fix from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1550 since this is a useful fix, whereas the other PR will be held up by some more C++ changes plus other potential feedback.
Set it so you actually get an autoclave when deconstructing the furniture variant, removing most of the scrap components based off what all looked like it was probably meant to be part of the autoclave itself. Leaves parts that seem fitting for water intake.
Not putting off more C++ changes.
I'll have to fix a merge conflict in the other PR once this is merged but it'll be simple enough.

Fix deconstructing autoclaves

---

doc/JSON_FLAGS.md

SUMMARY: Content "Belatedly remember to add CROSSBOW flag to JSON_FLAGS documentation"
Tiny thing I forgot with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1526.
Added the crossbow flag to the documentation.
1. Forgetting about it for another five years.
2. More serious answer, Coolthuhlu has mentioned that the whole "gunmods are filtered by both gun type and slot type" is a bit clunky and might be worth overhauling, but for now should at least document how it works currently. An overhaul is gonna be a lot more work.
...how does one even test documentation other than reading it, anyway.

Belatedly add documentation for crossbow flag

---

data/json/items/tool/workshop.json
data/json/tool_qualities.json
src/veh_interact.cpp

SUMMARY: Bugfixes "Port over PR fixing it so you can siphon with a leather hose"
This is another PR I could've sworn I was going to port over but evidently forgot about, fixing leather hoses actually being useless due to the siphon behavior not being updated.
1. Ported over change to rubber and leather hoses swapping in hose quality.
2. Ported over change adding hose quality to tool quality file.
3. Ported over change to veh_interact.cpp so it checks for hose quality instead of a fixed item.
Putting it off until I forget about it again.
1. Compiled and load tested.
2. Spawned in a leather hose and a jerrycan.
3. Went out and found a vehicle.
4. Examined it and confirmed you can siphon fuel from it.
5. Made sure you can't do any weird stuff like siphon from car batteries or minireactors. …

Port over fix for siphoning with leather hoses

---

data/json/recipes/chem/chemicals.json

SUMMARY: Bugfixes "Lintfix for recipes/chem/chemical.json file"
Quick and easy fix for an error that showed up in build checker suddenly.
Run the relevant file through online linter.
Wait for Coolthulhu to notice and fix it, wouldn't be surprised if I'm racing him to fix this as I type this.
Source was: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1529

Lintfix chemical recipe JSON

---

data/json/body_parts.json
data/json/mapgen/helipad.json
data/json/mapgen/military/mil_base/mil_base_z0.json

SUMMARY: [Content] "Changed military helicopters spawns"
I noticed in game that a lot of the military helicopters in game don't actually have spawn points. So I changed that. 
I added military helicopter spawns to the military base, and the military helipads respectively.  
Would have to wait to add more spawns, but other than debug spawning there were no spawns. 
Tested in game by spawning a large number of military helipads and a Blackhawk spawned! 
May have to adjust the X, and Y depending on how other helicopters spawn as they are quite big.

Military heli spawns

---

src/simple_pathfinding.cpp
src/skill.h
src/vehicle_autodrive.cpp

SUMMARY: None "Fixed firing asserts"
To be able run tests on MSVC in debug mode.
Run tests in debug mode.
Also removed one unused comparator.

Fix firing asserts from invalid comparisons

---

data/json/items/bionics.json

SUMMARY: [Category] "Fix outdated description of Probability Travel's item form"
A fuckup I forgot in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1506 where the item form still had the same description from before I reworked it into a point-and-phase CBM.
Updated description of Probability Travel's item form to be consistent with the CBM description.
Screaming.

Fix Probability Travel item description

---

src/overmap.cpp

SUMMARY: Bugfixes "Fix hovering 1-tile-long elevated bridges"
Elevated bridges are supposed to be at least 2 tiles long (ramp up and ramp down). If they're only 1 tile long, the single tile gets elevated all by itself and looks like a modern art installation:
It bridge is only 1 tile long, flatten it instead and turn into a regular road.
Separate overmap terrain for 1-tile-long bridges?
Teleported around the world, saw no hovering chunks. 
There's also a separate issue with bridges generating at wrong angle as endpoints of overmap special connections and resulting in a slightly different mess (see screenshot below), but that'll be covered in another PR.

Fix hovering 1-tile-long elevated bridges

---

data/json/items/comestibles/carnivore.json
data/json/items/comestibles/nuts.json
data/json/items/comestibles/raw_veggy.json
data/json/items/comestibles/veggy_dishes.json

SUMMARY: Content "Allows a few more things to be processed in the mill"
Not enough milling.
More milling, including:
- Corn to cornmeal
- tainted bone to tainted bone meal
- starch, rice, and acorn meal to flour (like in the player recipe)
Less milling?
I just edited the JSON files on github, no testing. They're simple single line JSON edits, should be fine?

More milling

---

data/json/mapgen/basecamps/modular_firestation1.json
data/json/recipes/basecamps/recipe_modular_firestation1.json

SUMMARY: Feature "Add option to build grid forge to firestation camp"
No grid forge
Add grid forge
Fundamentally alter the way basecamps function from the ground up.
Dropped the JSONs in, they worked

Firestation camp grid forge

---

src/map.cpp
src/panels.cpp
src/pixel_minimap.cpp
src/sounds.cpp
src/visitable.cpp
tests/vehicle_power_test.cpp
tests/vehicle_test.cpp

SUMMARY: None
This one is from https://github.com/CleverRaven/Cataclysm-DDA/pull/41664

[DDA Port] Map reference migration part 8

---

src/item_location.cpp
src/live_view.cpp
src/magic.cpp
src/map_field.cpp
src/mapbuffer.cpp
src/mattack_actors.cpp
src/mission_companion.cpp
src/npctalk_funcs.cpp
src/projectile.cpp
src/sdltiles.cpp
src/teleport.cpp
src/vehicle_part.cpp
tests/behavior_test.cpp
tests/creature_in_field_test.cpp
tests/explosion_balance_test.cpp
tests/map_test.cpp
tests/monster_test.cpp
tests/npc_talk_test.cpp
tests/vehicle_drag_test.cpp
tests/vehicle_efficiency_test.cpp
tests/vehicle_turrets_test.cpp

SUMMARY: None
This one is from https://github.com/CleverRaven/Cataclysm-DDA/pull/41661

[DDA Port] Map reference migration part 7

---

src/handle_liquid.cpp
src/iexamine.cpp

SUMMARY: None
This one is from https://github.com/CleverRaven/Cataclysm-DDA/pull/41375

[DDA Port] Map reference migration part 6

---

src/explosion.cpp
src/faction_camp.cpp
src/fungal_effects.cpp
src/game.cpp
src/gamemode_defense.cpp
src/gamemode_tutorial.cpp
src/gates.cpp
src/handle_action.cpp

SUMMARY: None
This one is from https://github.com/CleverRaven/Cataclysm-DDA/pull/41368

[DDA Port] Map reference migration part 5

---

src/character.cpp
src/clzones.cpp
src/computer_session.cpp

SUMMARY: None
This one is from https://github.com/CleverRaven/Cataclysm-DDA/pull/41364

[DDA Port] Map reference migration part 3

---

src/advanced_inv.cpp
src/advanced_inv_area.cpp
src/avatar.cpp
src/avatar_action.cpp
src/ballistics.cpp
src/basecamp.cpp
src/bionics.cpp
src/cata_tiles.cpp

SUMMARY: None
This one is from https://github.com/CleverRaven/Cataclysm-DDA/pull/41362

[DDA Port] Map reference migration part 2

---

src/condition.cpp
src/construction.cpp
src/crafting.cpp
src/creature.cpp
src/debug_menu.cpp
src/editmap.cpp

SUMMARY: None
This one is from https://github.com/CleverRaven/Cataclysm-DDA/pull/41367

[DDA Port] Map reference migration part 4

---

src/activity_item_handling.cpp

SUMMARY: [Bugfixes] "Fixes vehicle zones"
No more debugmsg and interrupted tasks.
Add the z level to it.
Not messing it up the first time.
I should add some to the suite at some point.
Whoops.

Vehicle zones fix

---

data/json/recipes/recipe_deconstruction.json

SUMMARY: Content "Make the silver watch uncraft recipe give the right amount of silver and clockworks"
Copy from https://github.com/CleverRaven/Cataclysm-DDA/pull/60035 made by me.
Doing it.
Not doing it.
Deconstructed a silver watch, returned right amount of silver and clockworks.

Make silver watch uncraft equal to the other clockwork watches

---

src/wish.cpp

SUMMARY: Interface "Show mutation id in mutation debug menu"
Copy of https://github.com/CleverRaven/Cataclysm-DDA/pull/59992 made by myself.
Do it.
Not doing it.
Kinda. Still have to fix BN build errors in my system.

Show mutation id in mutation debug menu

---

src/action.cpp
src/activity_handlers.cpp
src/activity_item_handling.cpp
src/avatar.cpp
src/character.cpp
src/character.h
src/character_functions.cpp
src/character_functions.h
src/construction.cpp
src/crafting.cpp
src/crafting.h
src/crafting_gui.cpp
src/game.cpp
src/iexamine.cpp
src/iuse.cpp
src/iuse_actor.cpp
src/npc.cpp
src/panels.cpp
src/player.cpp
src/player.h
src/player_activity.cpp
src/savegame_json.cpp
src/veh_interact.cpp
tests/crafting_test.cpp
tests/reading_test.cpp

SUMMARY: Infrastructure "Reorganized some Character-related code"
Moving stuff out of `player`.
1. Move multiple methods related to craft recipes from `player` to `Character`
2. Move a couple methods related to crafting speed from `player` to `crafting.h`/`.cpp`
3. Move `fine_detail_vision_mod` out of `player`
* Make it a namespaced function in `character_functions.h`/`.cpp` module
* Update documentation
* Add a wrapper for commonly used comparison of returned value with 4
4. Replace some `g->u` usages with `get_avatar()`
Game compiles. No behavior changes intended.

Character code reorganization 24-aug-2022

---

data/json/items/comestibles/protein.json

SUMMARY: Bugfix "Fix Protein rations use oversized wrappers "
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1800
1.  Bump ration volume to 0.25 litres instead of the currently used oddly specific 0.223.
2. Use a zipper bag, as container for Protein rations. It contains exactly 250ml. It is even realistic https://www.alibaba.com/product-detail/Custom-printed-Snack-Protein-Bar-Popcorn_1600432062697.html?&wgu=274265_16644_16617986128924_3c31fb199d&wgexpiry=1693334612&tp1=274265_16644_16617986128924_3c31fb199d&tp2=274265&tp3=1046855
Adding new container specifically for Protein rations. But it was not necessary.
1. Make a new character in a stocked evac_shelter
2. Open any cupboard
3. See protein ration (zipper bag) (1/1)
None

Fix Protein rations use oversized wrappers 

---

src/newcharacter.cpp

SUMMARY: Infrastructure "Comment ugly code used for character skill sorting in new_character.cpp"
In #1784 it was asked that I comment on the somewhat ugly code I used while fixing the scrollbar.
I comment the code.
Ignore, wait until someone comes across it and screams.
It compiles. ~It's a comment what do you want from me????~

Add comments to ugly code

---

data/json/npcs/robofac/NPC_ROBOFAC_MERC_1.json

Fixes the bug where if you had multiple missions from robofac_merc_1 you would be prevented from completing the initial mission until you completed the second.
Add an s so the condition can not use the default chat topic.

Fixed a tiny bug for robofac_merc_1.json

---

data/core/tips.json

Adding tip about recipies autolearning
Suggested in #1868

Update tips with info about learning recipies 

---

data/json/items/book/survival.json

That book had fun of 4. A very high number for a book that just shows some plants. 1 is more appropiate. It also serves as a skillbook.

Natural Remedies of New England is not that fun

---

CODE_OF_CONDUCT.md

Fixes #662
Kevin doesn't have a big saying in our project. And since Chulu probably has enough on his hands already, I voluntarily add myself as ombudsman for problems in our community.

Adding me as point of critique

---

.github/workflows/matrix.yml
.github/workflows/release.yml

SUMMARY: Infrastructure "Change mac OS version from 10.15 to 11 in Github Workflows"
Fix #1897
Bump the version, see if it's enough.
1. Workflows pass
2. Release build is created
3. Release build can be executed on Mac (will need help with this one...)
I left Mac OS versions as 10.15 in the Makefile.

Change mac OS version from 10.15 to 11 in Github Workflows

---

.github/workflows/manual-release.yml
android/app/build.gradle
msvc-full-features/prebuild.cmd

SUMMARY: Infrastructure "Add manual release workflow"
Being able to release named versions, rather than just timestamped ones with generated build numbers.
CTRL+C+V'd the experimental release workflow and edited it a bit to allow overriding version strings with it.
Changed msvc version generating script not to generate version string if one is provided already.
Modified the android build config so that we're in "cataclysmbnteam" rather than in "cleverraven".
Creating named releases by generating unnamed ones and then manually renaming them.
I'll do that in a moment...

Manual release workflow + Makefile (+friends) respecting VERSION

---

.github/workflows/manual-release.yml

SUMMARY: Infrastructure "Fix manual release"
Make manual release not have syntax errors.

Fix manual release

---

src/consumption.cpp

fixes #135
Fixing bug in which food which shouldnt be allowed for carnivore was
implementing fix proposed in #135 
Compiled, spawned garlic blulbs and cloves, checked if behaves properly when carnivore and not carnivore
none

Fix garlic clove/bulb carnivore bug

---

data/json/items/containers.json

Make cigs packs normal size
Fixes #1970 
Adjust cigarettes' packs size
Have cigarettes packs have normal amount 
Adjusted volume of cigarettes'packs
Keep them as is and adjust amount of cigarettes spawning in them

Fix Cigarette packs size

---

src/cata_tiles.cpp

SUMMARY: Bugfixes "Fix rendering level -10"
Fixes rendering level -10.
Off by one error.

Fix rendering level -10

---

doc/JSON_INFO.md

SUMMARY: Bugfixes "fix typo on modinfo.json schema"
conflics -> conflicts

fix typo on modinfo.json schema

---

src/color.cpp
src/overmap_ui.cpp
src/panels.cpp
src/panels_utility.cpp
src/panels_utility.h

SUMMARY: Infrastructure "Refactor Panels"
There's lots of duplicate codes, i mean *a lot*
extract functions
port refactored code from DDA?
- it's still a fraction of what needs to be refactored
- might need C++17 and C++20 features to make it more sane

Refactor panels

---

doxygen_doc/Doxyfile
src/cata_tiles.h

SUMMARY: Infrastructure "Add documentation for tile related functions"
Some rendering functions lack docs and variants are hard to see.
Add some documentation for arcane rendering functions.
I'm not completely sure if the documentations I've added is corect.
I did search for some things such as what does the return type does, but help is appreciated.

Add documentation for tile related functions

---

src/monattack.cpp
src/monmove.cpp

Fix #1997 
SUMMARY: Bugfixes "Fix dog ignoring leash when they see enemies"
1) Creatures would ignore leashes when they want to attack (or possibly flee from) a target.
2) A dog has a probability to bark at a monster, which remove a whooping 100 move points. This means that given enough monsters, a dog would "bark itself to death", being unable to follow the player even leashed because it used all its move points to bark every turn.
1)
- If the leashed animal is already close to the player and a hostile creature is adjacent to the player, try to attack it to defend the player. I also increased the leash range a bit to allow dogs to do their hit and run attacks (long leashes do exist)
- Otherwise stay close to the player
2)
- Reduce the barking cost from 100 to 10. Having your dog unable …

Fix dogs ignoring leash when they see enemies

---

tools/gfx_tools/compose.py

SUMMARY: Infrastructure "[DDA Port] port compose.py"
- BN one does not work
- co-author everyone since there were too many commits
- get all commits related to the file and cherry-pick them instead

[DDA Port] port compose.py

---

data/json/items/armor/boots.json

SUMMARY: Balance "Make sneakers less warm"
- fixes #2100
sneakers now has warmth of 10

Make sneakers less warm

---

src/iuse.cpp

SUMMARY: Interface "Add better pet food message"
Fixes #2018
"Place the cattle fodder where" -> weird
This also changes the message for the other pet foods.
Try to activate the following food:
- cattle fodder 
- dog food
- bird food
- cat food
The message is changed

Add better pet food message

---

data/json/mapgen/ws_biker_dump.json

SUMMARY: {Content} "Add bandits and thugs to regional dump, dda port #40415"
Adds bandit and thug NPCs to biker_dump
implement dda #40415

add NPCs to biker_dump

---

src/options.cpp
src/sdltiles.cpp

SUMMARY: Interface "Add option for minimizing on focus loss"
- resolves #2102 
- made minimizing a separate option

Add option for minimizing on focus loss

---

data/json/construction.json

Fix Regular / Reinforced Plastic Window Cost

---

src/avatar.cpp
src/character.cpp

SUMMARY: Bugfixes "[Port] Fix stats through kills missing max hp modification"
Increasing the strength stats through stats through kills didn't increase the maximum HP of the player as it should.
Original PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/45223
Port the DDA fix for it.
- using a new character
- increase the strength stats with stats through skills does increase his maximum HP

[Port] Fix stats through kills missing max hp modification

---

doc/MODDING.md

SUMMARY: None "Suggest modders to use JSON validator"
Just to make new modders life easier by letting them know about existing tools.

Suggest to use json validator for modders.

---

data/mods/Dark-Skies-Above/modinfo.json

[Content] - Obsolete Dark Skies Above
adds obsolete tag to an obsolete mod
implements dda pr cleverraven/cataclysm-dda#62504

Obsolete Dark Skies Above

---

data/json/itemgroups/Locations_MapExtras/locations.json
data/json/items/melee/bludgeons.json
data/json/martialarts.json
data/json/obsoletion/items.json
data/json/obsoletion/recipes.json
data/json/recipes/weapon/piercing.json

This item was boggus. It was weak, extremly weak. Needed grinding (!) to even be produced and had really no reason to be in the game other than fluff. That's why I got rid of it.
Fight me if you disagree.
Bring your own sharp toothbrush tho.

obsolete the conductive sharp_toothbrush

---

data/mods/Generic_Guns/modinfo.json

After a somewhat heated argument, I came to the realization that my time is not worth the extra stress I already had upon. I consider, since I made a lot of changes (for better or for worse) to generic guns, myself as a author of it. I won't maintain it anymore, so everyone is free to take up the role and make it better, as they like it to have.

removing myself as Maintainer of Generic Guns.

---

data/mods/Generic_Guns/ammo/casings.json
data/mods/Generic_Guns/ammo/shot.json
data/mods/Generic_Guns/recipes/recipes_firearms_repeater.json
data/mods/Generic_Guns/recipes/recipes_firearms_single.json

Found some errors in the recipe (using already obsoleted ammo), and did name correction in the casings.

Some error and naming corrections in GG

---

data/json/items/containers.json
data/json/recipes/other/containers.json

The wooden barrel needed an anvil to be construced, that removes the necessity, hammering should be enough. Also the steel keg was using more resources as the 100 l drum without offering any advantages. This will balance it out.

Remove Anvil Requirement for wood barrel, make steel keg more like steel drum

---

src/vehicle_move.cpp

SUMMARY: Features "Better helicopter ascent blocking: allow INDOORS tiles, forbid thin floors, print cause"
When going up with a helicopter, the messages were unhelpful. This makes them more useful.
* Removed the requirement for all tiles to be outside for the vehicle to ascent
* Made floors (any terrain without `NO_FLOOR` flag) above block ascent
* Added a message describing what is blocking ascent and direction to it
* Supported blockers: ceiling, a solid block of terrain (wall, rock), unwalkable furniture, monster, vehicle
Decided to go for the simplest solution that works.
* Printing more/all blockers, not just the first one
* Better ordering of blockers, so that the first one is more "representative"
* Printing coords instead of direction of the name
* Spawn a helicopter
* Test …

Better helicopter ascent blocking: allow `INDOORS` tiles, forbid thin floors, print cause

---

.github/CONTRIBUTING.md
src/debug_menu.cpp

SUMMARY: [Interface] "More welcoming debug help menu"
- fixes #2357 
before:
```
Debug Functions - Using these will cheat not only the game, but yourself.
You won't grow.  You won't improve.
Taking this shortcut will gain you nothing.  Your victory will be hollow.
Nothing will be risked and nothing will be gained."
```
after:
```
Debug Functions - Manipulate the fabric of reality!
You can use them to fix a bug or test something.
most importantly, have FUN!
```
I didn't take much time thinking up new help text so it may have some more room for improvement.
text changes only.

More welcoming debug help menu

---

src/options.cpp

SUMMARY: Interface "Update description for new explosion option"
improve option description from #1348  [for end user](https://www.reddit.com/r/cataclysmbn/comments/10u3dty/new_explosions/)

Update description for new explosion option

---

README.md

Fix path to latest release page
SUMMARY: Infrastructure "Fix path to latest release page in readme"
Link to "latest" release shows latest stable 0.2 but not latest experimental.
Change link in readme
1) Go to https://github.com/Firestorm01X2/Cataclysm-BN/tree/feature/latest-release-fix
2) Click latest.
3) You must see experimental version but not stable.
None

Fix path to latest release page in readme

---

data/mods/No_Hope/Mapgen/lab_rooms.json

SUMMARY: Lab kennel gate rubble removal for No Hope mod
Forgot that No Hope needed to be edited too. See my previous edit #2423 for more info.

Lab kennel gate rubble removal for No Hope mod

---

.github/workflows/clang-tidy.yml
tools/clang-tidy-plugin/test/lit.cfg

SUMMARY: None
Follow-up for https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2237#discussion_r1062976658
Update to c++17
Will wait for CI

Update lit.cfg for C++17

---

data/json/items/comestibles/drink_other.json

SUMMARY: Balance "Vinegar is less fun but has some calories"
Vinegar was too "fun" to drink and added nothing, now it has some calories at least.
Add the Unsafe tag to vinegar, but since unfermented vinegar has -15 fun, it makes sense to make it a bit "more" fun.

Vinegar is less fun but has some calories

---

tools/clang-tidy-plugin/test/simplify-point-constructors.cpp

SUMMARY: None
Fix tidy after #2437
Cherry-pick the fix from https://github.com/CleverRaven/Cataclysm-DDA/pull/64152
Tidy tests pass locally, will wait for CI

[DDA Port] Fix tidy

---

data/json/items/comestibles/raw_veggy.json

SUMMARY: Balance "Eating black tea leaves isn't fun"
Eating tea leaves was around -1 fun per consume, which is a bit too forgiving. -6 would be more fitting. Eating those leaves doesn't taste good at all.
lowering the fun to -6 or so should be more like it.
leaving as is, since it isn't a big change to be honest. But I guess it makes sense to do so to dried tea leaves.

Making eating black tea leaves less fun

---

data/json/items/generic.json

adds the item `fema_data` to fix the refugee merchant mission "Unknown Recipient"
Summary: [Bugfix] Fix missing item definition for 'Unknown Recipient' mission
Refugee merchant gives a mission 'Unknown Recipient' which will spawn a Hub01 location. However, there is a missing item definition which causing it to be uncompleted.
Adds the item definition in.

Fix 'Unknown Recipient' mission

---

src/pickup.cpp

SUMMARY: Bugfixes "Fixed some bugs with picking up of count-by-charges items"
Fix #2329 (note: to trigger the bug, you must be standing on the tile you're picking up from)
Fix #2417
Rearrange code to deduct charges at appropriate moments.
The code is prime spaghetti.
I checked that the original bugs are gone, and that pickup still works, but I won't be surprised if this breaks something else.

Fix some bugs with picking up of count-by-charges items

---

data/json/recipes/armor/other.json

you could produce free rags with sleeping bags, this is the fix for it.

sleeping bag now require 60 rags

---

.github/workflows/astyle.yml
.github/workflows/clang-tidy.yml
.github/workflows/json.yml
.github/workflows/lint.yml
.github/workflows/matrix.yml

SUMMARY: Infrastructure "add automated PR style review"
|     c++     |      json      |
| :---------: | :------------: |
| ![c++][c++] | ![json][json]  |
| (files tab) | (comments tab) |
[c++]: https://user-images.githubusercontent.com/54838975/227416503-421b7b2c-e00c-48d4-b83b-336243db6840.png
[json]: https://user-images.githubusercontent.com/54838975/227418359-4993f703-019d-4c31-9ca3-c7df843240c0.png
Help contributors find and fix style issues more easily in their PRs.
1. port DDA PR
- https://github.com/CleverRaven/Cataclysm-DDA/pull/62165
- https://github.com/CleverRaven/Cataclysm-DDA/pull/62629
- https://github.com/CleverRaven/Cataclysm-DDA/pull/62660
- https://github.com/CleverRaven/Cataclysm-DDA/pull/62736
- https://github.com/CleverRaven/Cataclysm-DDA/pull/62824
- …

automated PR style review

---

data/json/itemgroups/Clothing_Gear/gear_civilian.json
data/json/itemgroups/Locations_MapExtras/locations.json
data/json/itemgroups/Locations_MapExtras/locations_commercial.json
data/json/itemgroups/Locations_MapExtras/mall_item_groups.json
data/json/itemgroups/Locations_MapExtras/mansion.json
data/json/itemgroups/SUS/domestic.json
data/json/itemgroups/collections_domestic.json
data/json/itemgroups/supplies.json
data/json/items/generic/bathroom_house.json
data/json/obsoletion/items.json
data/json/uncraft/generic.json

SUMMARY: Content "Removal of bathroom clutter that served no purpose"
There were still items lying around that didn't have any reason to be there. in vain of the kitchen clutter removal, it was time to get rid of the clutter inside the bathrooms, that either never spawned, or rarely (only mansions spawned toothbrushes, those snobs!) and don't have a reasonable uncraft recipe. 
Toilett paper is gone now...
Removal of said clutter.
Give the clutter a reason to exist, but I couldn't find any good use for it, to be honest.
toilett paper is gone.

Obsoletion and removal of useless bathroom fluff

---

README.ko.md
README.md

SUMMARY: I18N "add korean README.md"
There is a community of Korean roguelike players, and providing language support for development resources could be an effective way to encourage their participation in BN.

korean `README.md`

---

data/json/item_actions.json
data/json/items/tool/science.json
data/json/requirements/electronics.json
src/item_factory.cpp
src/iuse.cpp
src/iuse.h
src/overmapbuffer.cpp
src/overmapbuffer.h

SUMMARY: Features "Add new MODIFY_GRID_CONNECTIONS to voltmeter"
Being able to extend grids.
Voltmeter gets a new function that lets it connect grids. It's very clunky, but usable.
To connect grids:
* Activate voltmeter
* Pick the use function
* Pick the direction you want to connect current map square to
* Pay the cost multiplied by the number of map squares in the resulting grid, or 0 if it does not extend current grid
The function is a "toggle" and will say if you are going to connect or disconnect the square.
Disconnecting is free.
Cost is a requirement, not a recipe.
Functionality that didn't make it into this PR:
* Requirements for the grid, like "it has at least one wall tile" - you can create a free-floating grid by connecting tiles while on a helicopter, if you manage to keep it …

Add new MODIFY_GRID_CONNECTIONS to voltmeter

---

data/json/items/armor/suits_protection.json

SUMMARY: I18N "Fix missing spaces in suits_protection.json"
Fix missing spaces i've overlooked in #2458.
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/4543981103/jobs/8009403116
Adds a space.

Fix missing spaces

---

.github/workflows/manual-release.yml
.github/workflows/msvc-full-features.yml
.github/workflows/release.yml
msvc-full-features/vcpkg.json

Fix VCPKG build
SUMMARY: Infrastructure "Fix VCPKG build"
Fix VCPKG build 
Bump up vcpkg version to
https://github.com/microsoft/vcpkg/releases/tag/2023.02.24
https://github.com/microsoft/vcpkg/commit/a7b6122f6b6504d16d96117336a0562693579933
Previously it worked as well:
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2091
1) Compiles via CI.
2) Compiles locally on VS. Game starts successfully.
People with existing VS+vcpkg build setups will need to manually update their vcpkg.
Assuming the setup matches one described in the doc, this can be done in 2 steps:
Open your vcpkg folder (usually C:\dev\vcpkg) in cmd and run:
git pull --ff origin master
Open the solution in Visual Studio and do a "Clean Solution" + "Build Solution"

Fix VCPKG build

---

.github/workflows/release.yml

SUMMARY: Infrastructure "Fix msvc"
Fix msvc
Set the environment variable that it's complaining about.
Bit weird this one, not sure why it suddenly broke.
None cos workflow, don't even know if it will work at all.

Force vcpkg binary caching to default in workflows

---

.github/workflows/release.yml

SUMMARY: Infrastructure "Fix linux builds"
Linux builds decided now was a good time to break.
Bumps the ubuntu image version.
Reusing the same branch here seems to be causing problems. Hopefully this works right.

Linux build fix

---

.github/workflows/json.yml
.github/workflows/lint.yml
Makefile
build-scripts/build.sh

SUMMARY: Performance "Parallelize json style check"
- port https://github.com/CleverRaven/Cataclysm-DDA/pull/54363
- port https://github.com/CleverRaven/Cataclysm-DDA/pull/54375

perf: parallelize json style check

---

.github/workflows/android.yml
.github/workflows/check-translation.yml
.github/workflows/manual-release.yml
.github/workflows/msvc-full-features.yml
.github/workflows/msys2.yml
.github/workflows/pull-translations.yml
.github/workflows/push-translation-template.yml
.github/workflows/release.yml

SUMMARY: Build "bump build pipeline to use actions/checkout@v3"

ci: bump to actions/checkout@v3

---

src/game.cpp
src/savegame_json.cpp

SUMMARY: Bugfixes "Hotfix for missing map and autopickup rules"
Hotfix for regressions after #2519
Fix save id and character name
Local testing

Hotfix for missing map and autopickup rules

---

src/diary.cpp

Same as #2586, but for character diary

Hotfix diary

---

src/animation.cpp
src/animation.h

SUMMARY: Bugfixes "fix yet another regression from #2594"
bumping runner version probably caused some issues with mac build

fix: macos build failure hotfix, take 2

---

src/lightmap.cpp

SUMMARY: Bugfixes "Bring 3d shadowcasting more in line with 2d and handle floors geometrically"
Fixes the pillar bug and generally makes 3d results more in line with 2d. Also does geometric handling of floors, so they act like opaque edges. Nothing else and nothing too fancy here, this is more fixes to the old algorithm rather than a new one.
The main difference here is a different division scheme when we encounter a split. We split into 3 sections. The area below the split is fully processed and can be cast a level deeper. The area after the split is untouched and will be handled by a same level recursive call. The area before the split where a single row has been processed we keep going with in the same call.
This is a very natural scheme, but like a lot of schemes, it will infinitely …

3d shadowcasting

---

src/npcmove.cpp

SUMMARY: Bugfixes "Make NPC guards complain at player stealing items"
port https://github.com/CleverRaven/Cataclysm-DDA/pull/64822 by @Surflurer

feat: make NPC guards complain at player stealing items

---

src/map.cpp
src/map.h
src/mattack_actors.cpp

SUMMARY: Bugfixes "Fix turrets aiming through walls"
Fixes #2578 fixes #2431
Bit of an overhaul to their targeting to make it a little better at selecting the closest target and a bit clearer. 
Just adding the missing vision check.
I had a drive around some turrets and they're firing correctly now.

Fix turrets aiming through walls

---

data/json/monsters/power_leech.json

Summary: [Bugfix] "Signal Tree is harvested as a human"
to fix this bug found by Redbonky#3447 on BN Discord
adds "harvest" tag to signal tree
[insert meme statement here]
spawned one and it works

A Signal Tree shouldn't have human skin

---

src/main_menu.cpp

SUMMARY: Bugfixes "Fixed scenario message printing on each load"
Fix #2609
Distinguish between new game and loading existing game.
Works as expected on local setup.

Fix scenario message printing on each load

---

data/json/construction.json
data/json/construction_sequence.json
data/json/furniture_and_terrain/terrain-walls.json
data/json/recipes/basecamps/recipe_modular_canteen/recipe_modular_canteen_metal.json

SUMMARY: Balance "Remove the requirement for shallow pit for junk metal walls"
To allow players to construct their dream slum.
The requirement for shallow pits means junk metal walls can only be built on dirt tiles this substantially limits their use. There is no makeshift wall that can be used on floor tiles and the junk metal walls are an excellent fill for this roll. 
1. constructed, deconstructed & smashed the wall
2. tested building in different spots to make sure there wasn't any unwanted behavior

Remove the requirement for shallow pit for junk metal walls

---

.github/workflows/pull-translations.yml

SUMMARY: I18N "fix date not showing on automated pulls"
- fix regression caused by #2689 
changed `formattedTime` -> `time`
[followed docs](https://github.com/nanzm/get-time-action#outputs)

ci(i18n): fix date not showing on automated pulls

---

data/json/recipes/armor/head.json
data/json/recipes/food/meat.json
data/json/recipes/food/other.json
data/json/recipes/food/snack.json
data/json/recipes/food/veggi.json
data/json/recipes/other/tools.json
data/json/recipes/weapon/piercing.json
data/json/recipes/weapon/ranged.json
data/json/requirements/cooking_components.json

SUMMARY: Balance "Make more use of new bread_sandwich, condiment, and bone_sturdy crafting requirements"
Follow-up to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2369, implementing some uses of the crafting requirements added to vanilla.
1. Made use of `condiment` crafting requirement, mainly for sandwiches/burgers calling for a wide variety of options for sauce. Left a few specialized recipes like oddball uses for mustard, some hot dog recipes, salads and the like untouched for now.
2. Updated `bread_sandwich` crafting requirement to include garlic bread. Also added cornbread to it since I don't think we have any existing specialized wheat-free sandwich recipes in vanilla at present, so `bread_sandwich_wheat_free` might not see much use right now.
3. Made use of `bread_sandwich` …

Follow-up usage of bread and condiment crafting quality

---

src/map.cpp
src/map.h
src/npc.h
src/npcmove.cpp
src/npctalk.cpp

Summary Features "Ported NPC chat command that orders NPC to move to location player-chosen location"
port https://github.com/CleverRaven/Cataclysm-DDA/pull/51313 by @eltank
port https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/71 by @Night-Pryanik 
command single NPC
https://user-images.githubusercontent.com/54838975/235950190-3e467ad9-318e-4bb9-9e52-8e9c4af46af6.mp4
command multiple NPC, one by one, then all at once
https://user-images.githubusercontent.com/54838975/235950202-22ff343c-d064-49cb-b89e-c18e83b60f65.mp4

feat: npc command to move them to given location

---

data/json/mapgen/abandoned_barn.json
data/json/mapgen/helipad.json
data/json/professions.json
data/json/scenarios.json
data/json/vehicle_groups.json
data/json/vehicles/helicopters.json

SUMMARY: Content "Gyrocopter vehicle and pilot profession addition, related followups"
Implementing some ideas that came up in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2811 that I didn't finish before going to bed for a bit.
1. Implemented a gyrocopter vehicle to make use of the part. As discussed in that PR and on the BN discord, I started off leaning more towards mimicking the appearance of the real-world Bensen B-8 (example: https://upload.wikimedia.org/wikipedia/commons/a/a2/Bensen_B-8M.jpg) a bit more closely instead of the unknown model of two-seater used in Thog's mod since we never heard back from him. On finding the three external wheel pattern didn't really look good when facing side, I ended up simplifying it down to a 3x1 vehicle more in the vein of a bike. Kept …

Add gyrocopter vehicle and profession

---

.github/workflows/lint.yml

prevent this kind of spam #2776 - it does not completely fix it as you can still trigger the spam; it is just way harder to do so
port my:
https://github.com/CleverRaven/Cataclysm-DDA/pull/65039
https://github.com/CleverRaven/Cataclysm-DDA/pull/65096

prevent spawm from linter bot

---

data/json/furniture_and_terrain/furniture-appliances.json

SUMMARY: Bugfixes "Set largest grid battery to look like a battery, not a locker."
Random find I stumbled into that I could've fucking sworn I fixed, but evidently not.
Changed `looks_like` of large storage battery furniture to use the same standard battery as its target, not lockers.
Going insane because I could've sworn I fixed this twice, and I can confirm visually what the exact problem is, so I dunno how I could've failed to fix it twice.
2. Spawned in and confirmed big battery now looked like the other batteries.

Fix large grid battery using wrong looks_like

---

data/json/monsters/feral_humans.json
data/json/speech.json

SUMMARY: Content "Add parrot lines to some feral types, fix typos, missing death functions, and update armor values"
Some misc updates and fixes to feral humans. Notably fixes missing death functions on some ferals.
1. Updated armor values of labsec ferals to be consistent with labsec zombies, increasing ballistic armor from 4 to 10.
2. Updated armored ferals to match light plate armor instead of gothic plate armor, to represent a more middle-ground value given how their death drops can vary quite a bit. Bash and cut resist goes from 20 to 16, stab resist goes from 15 to 13 (as stab resist for armor is 80% of cut resist, rounded up from 12.8), ballistic resist goes from 12 to 14.
3. Updated armor values of feral militia, based off half the armor values of kevlar vest as that's the only …

Further improvements/fixes to ferals

---

data/mods/DinoMod/DESIGN.md
data/mods/DinoMod/recipes/containers.json
data/mods/DinoMod/recipes/head.json
data/mods/DinoMod/recipes/offal_dishes.json
data/mods/DinoMod/recipes/parts_construction.json
data/mods/DinoMod/recipes/pets_bear.json
data/mods/DinoMod/recipes/pets_elephant.json
data/mods/DinoMod/recipes/pets_ostrich.json
data/mods/DinoMod/recipes/recipe_food.json

SUMMARY: Mods "[DinoMod] cutting fixes for recipes"
Bugfix
Changes all recipes requiring cutting 2 to just need cutting 1, documents this
N/A
Simple JSON edit
Thanks to Phoenix of the Chorus on Discord for reporting this

[DinoMod] cutting fixes for recipes

---

.github/pull_request_template.md

SUMMARY: Infrastructure "Mention in the PR template to check style for JSON and c++"
to help contributors get familiar with code style.
added links to code style guide to PR template.

chore: mention code style on PR template

---

data/json/monsters/feral_humans.json
data/json/speech.json

SUMMARY: Content "Add some Psychosis callouts as parrot lines for other feral humans"
A small idea that came to mind while working on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2892
1. Added `PARROT_AT_DANGER` to the other feral humans.
2. Added speech lines based off some of the Psychosis shouts, mainly used by the variants that don't already have lines of their own.
I wanted to just use `<schizo_self_shout>` so I could do this with way less copypaste but that doesn't work:
I guess coding support for that would be an option too but blargh.
2. Load-tested in a release for testing.
3. Spawned in a feral human and let it scream at me.

Add more parrot lines to ferals

---

data/json/monsters/mammal.json

SUMMARY: Bugfixes "Fix incorrect unit given for volume of cows, making them weigh a megagram while only occupying 1 liter of volume"
Lil thing I abruptly noticed while doing to preliminary testing in preparation for a PR I was tempted to work on, turns out to be a problem in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2588 that I only just now caught.
Set cows to have a volume of 1000 liters, not 1000 milliliters.
Pesterting Scarf to do it.
2. Loaded up compiled test build and spawned a cow, confirmed it says on examine that it's actually huge.
3. Killed it in debug, confirmed a corpse at the tile volume limit doesn't immediately shit itself in any weird ways when created (one would hope not given how many dinos in Dinomod are …

Fix cows being only a liter in volume

---

data/json/items/comestibles/egg.json
data/json/items/comestibles/meat_dishes.json
data/json/items/comestibles/mushroom.json
data/json/items/comestibles/seed.json
data/json/items/comestibles/veggy_dishes.json

SUMMARY: Bugfixes "Set several cooked items that inherit from raw items to delete the raw flag"
I noticed that cooked mushrooms were still showing as raw, figured I'd fix that and check for any other raw foods along the way.
1. Set cooked mushrooms to delete the `RAW` flag.
2. Also set boiled egg to delete the `RAW` flag.
3. Set roasted coffee beans to delete the `RAW` flag.
4. Set dehydrated vegetable to delete the `RAW` flag, which in turn fixes dehydrated alien fungus chunk.
5. Set dehydrated tainted meat to delete the `RAW` flag.
1. Removing `RAW` from flour and oatmeal because cornmeal doesn't have it. Doesn't really matter but so long as it doesn't fuck up calorie inheritance I guess.
2. Removing `RAW` from uncooked pasta because you do kinda sorta cook it in the process of making …

Fix cooked items counting as raw

---

data/json/flags.json

SUMMARY: Bugfixes "Add missing JSON flag to flags.json"
Fix error on load:
```
DEBUG    : item of type 'toastem2' was loaded with undefined flag 'VERY_COLD'.
FUNCTION : operator ()
FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\savegame_json.cpp
LINE     : 2296
VERSION  : BN b476232
```
Added JSON definition for `VERY_COLD` flag.
Screaming.
1. Added JSON change to release for testing.
2. Loaded save that had some very cold items present.
3. No error.

Fix load error from undefined VERY_COLD flag

---

data/mods/CRT_EXPANSION/modinfo.json
data/mods/CRT_EXPANSION/scenarios/crt_classes.json

SUMMARY: [Bugfix] "What exactly does C.R.I.T. stand for?"
More than a few people have asked what exactly C.R.I.T. stands for. And until now the only place this was referanced was a single line in the description for the C.R.I.T. Lone Wolf profession. The acroynm stands for Catastrophe Response and Investigation Team, by the way.
changes a few files to include 'Catastrophe Response and Investigation Team '
:-/
:-}

docs: state what exactly does C.R.I.T. stand for

---

src/scenario.cpp
src/scenario.h
tests/find_auto_consume_test.cpp

SUMMARY: Bugfixes "Fix the failing test suite"
Stop the test suite crashing.
Two things, bit incorrect putting them in one pr but I want to get the tests passing. First is an upgrade to scenario black/whitelists so you can now have multiple without it crashing. It will start from the sum of all whitelists (or just all scenarios if there are none) and then apply the black lists.
Also, a fix in the test suite to pass some lambda parameters by value rather than reference. I'm not sure what catch is doing that by reference gives a use after return there but it seems to.
Hopefully much better now.
We need to be more careful merging things that don't pass tests. It tends to compound on itself where when it's broken you can't tell what's causing more problems. In future if something breaks the …

Fix the tests

---

data/json/scenarios.json

Removing some locations which logically don't make sense for scenarios involved and in some cases don't fulfill the requirements even.
SUMMARY: [Balance] "[Removing some locations from scenarios that don't make sense]"
Fixing things mentioned in #3021 
Some starting locations weren't thought out well or just plain don't work for the scenario under current game conditions.
Removed locations from scenario.json
In case of golf courses perhaps make them spawn inside of the city but that would be tougher nut to crack.
Or perhaps make a new golf club location which would only appear inside of a city.
Started the game and checked if it loads correctly, then went over starting locations in scenarios.

Scenario locations balancing

---

README.md

SUMMARY: Infrastructure Fix stable badge link
Fix stable badge link
0.2 -> 0.3
There doesn't seem to be a way to link to latest non-pre release
Should work as is

Fix stable badge link

---

README.ko.md

Update stable release link for Korean readme
SUMMARY: Infrastructure "Update stable release link for Korean readme"
Korean readme contained link to 0.2
Set proper link in Korean readme
None
Check link in https://github.com/Firestorm01X2/Cataclysm-BN/tree/feature/kor03
Make sure that Korean readme is correct
None

Update stable release link for Korean readme

---

data/json/bionics.json
data/json/items/bionics.json

Increase the energy output so that you can go to the plus even when you turn on all possible bionics
There used to be a mutation for infinite energy, but now I cant find it
I fixed a few values in json
cope
That's works

Debug cbm generator is too weak

---

data/json/uncraft/generic.json

Glass jars, flasks and bottles have weird convoluted ways of re-forging - 9 glass jars into a sheet, which can then be broken into shards, for example. This makes these common glass objects 'disassemblable' directly into glass shards. By breaking against the ground or something. 30s per uncraft, in line with the rest of the glass objects (though I'd change all to 6s, if others agree, you literally smash a bottle, it doesn't take half a minute).
Added recipes to uncraft - generic .json.
Smashing my large in-game collection of bottles into nothing.
Ingame tested, B works as expected.

Glass object (jar, 3l jar, flask, bottle) disassembly; Update generic.json

---

src/active_item_cache.cpp
src/character.cpp
src/character.h
src/creature.cpp
src/faction.cpp
src/faction.h
src/item.cpp
src/line.cpp
src/map.cpp
src/map.h
src/monmove.cpp
src/npc.cpp
src/npcmove.cpp

SUMMARY: Performance "Ported performance PRs by Aivean from DDA"
- resolves #3074
- resolves #3075
- resolves #3076
- resolves #3078
- resolves #3079
resolves the easy part of #3073 .

perf(port): performance PRs by @Aivean

---

doc/SOUNDPACKS.md
src/sdlsound.cpp

SUMMARY: Infrastructure "Allow preloading all variants of sfx"
- fixes #114
O(n^2), use at your own risk
maybe it won't be necessary if the root cause of #114 was missing sfx path, in that case #3059 will handle this issue better
[link to original dicussion at BN discord](https://discord.com/channels/830879262763909202/830916451517857894/1140806895200911493)

feat: option to preload all sfx variants

---

README.ko.md
README.md

Update experimental link in readme
SUMMARY: Infrastructure "Update experimental link in readme"
Currently experimental link shows stable on top. It should be fixed.
Show only prereleases for experimental link
Look for experimental link in:
https://github.com/Firestorm01X2/Cataclysm-BN/blob/feature/readme-link-upd/README.md
https://github.com/Firestorm01X2/Cataclysm-BN/blob/feature/readme-link-upd/README.ko.md
None

Update experimental link in readme

---

data/json/vehicleparts/vehicle_parts.json

Fixing the issue #1922 where security cameras will overlap vehicle doors and make it impossible to see if doors are opened or closed.
I have removed "location": "on_roof" from the vehicle_parts.json and thus security cameras will no longer show on cars.
This isn't ideal solution but i don't know of anything else to make it work.
Anything that will show security cameras on car but not when on the same tile with doors.
Please let me know if you have a better solution to this problem.
I made the change and loaded the game. Cameras aren't visible anymore on cars and thus don't overlap doors.
Tested if cameras are working with closed curtains and they are.

Security camera doesn't overlap vehicle doors anymore

---

tests/vehicle_drag_test.cpp
tests/vehicle_efficiency_test.cpp

Update vehicle tests
SUMMARY: Infrastructure "Update vehicle tests"
Vehicle tests needs updating after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1925
```
Cataclysm-test-vcpkg-static-Release-x64.exe  vehicle_drag_calc_baseline
Cataclysm-test-vcpkg-static-Release-x64.exe  make_vehicle_efficiency_case
```
And replace data for broken tests
None
Wait for CI to finish
None

Update vehicle tests

---

lang/concat_pot_files.py
lang/extract_json_strings.py
lang/unicode_check.py
tools/check_po_printf_format.py
tools/copy_from.py
tools/copy_mac_libs.py
tools/dialogue_validator.py
tools/fix-compilation-database.py
tools/gfx_tools/decompose.py
tools/gfx_tools/png_update.py
tools/json_tools/cddatags.py
tools/json_tools/keys.py
tools/json_tools/util.py
tools/json_tools/values.py
tools/merge_maps.py
tools/palettize.py
tools/update_blueprint_needs.py
utilities/building-utility/deconstruct.py

SUMMARY: Infrastructure "Used f-strings for python scripts for readability"
[f-strings](https://realpython.com/python-f-strings/) are cool, let's use them everywhere.
~~it's totally not like i can't stand using % and .format~~
ran [flynt](https://github.com/ikamensh/flynt).
rewrite it in typescript, but it requires many more steps to reach there. this is the first step.

refactor: convert to f-strings

---

data/json/effects.json
data/json/mutations/mutations.json
data/json/obsoletion/effects.json
src/bionics.cpp
src/character.cpp
src/character.h
src/creature.cpp
src/iexamine.cpp
src/iuse_actor.cpp
src/mutation.h
src/mutation_data.cpp
src/npc.cpp
src/panels.cpp
src/player_hardcoded_effects.cpp
src/suffer.cpp
tests/player_helpers.cpp

SUMMARY: Balance "Simplify broken limb mending"
Make broken limb not take you out of combat for [insert way too long duration here].
Broken limbs can now be healed in every way a healthy limb can, they just heal at 25% speed, unless splinted or you have REGEN_LIZ.
Limbs stay broken until they reach full hp.
* Reworking limb breaking to be purely hp based, so that limb is broken when below x% hp
* Keeping the long wait until we have proper limb removal
* Set hp of limbs to, respectively: 0, 0, 0, 50%
* Set one of the 0 hp limbs to 50% hp
* Splint one of the 0 hp limbs
* The splinted limb should now be "blue" on the hp bar, two broken ones should be red
* Sleep until the splinted limb visibly regens about 25%
* Splinted limb should regen as much as the non-broken limb
* The non-splinted …

Simplify broken limb mending

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md

SUMMARY: Infrastructure "issue and pr template improvments"
- allow empty issue (useful for tasklist)
- reduce heading levels for PR template
- add images to bug report guide

chore(github): issue and pr template improvments

---

src/overmap.cpp

SUMMARY: Bugfixes "Fixed some issues with bridge\road generation on overmap edge"
Fixes #1495.
1) Pathfinder doesn't return direction of last node. For linear connection that case was covered, but not for nonlinear. In result such nodes wasn't placed at all, leaving gap on the end of connections. Now they will be placed reusing old direction. Linear things already does almost same.
2) Connections doesn't know what direction they should be pointing at the end of their route. So bridges could approach connection points from the side. This is fundamental issue, as connections points are shuffled, and pathfinder just don't know how its path supposed to be used. Imagine bridge one map longer than on screen linked in above issue, that's how it'd look with only first fix. 
Solution is kinda …

Fixed some issues with bridge/road generation on overmap edge

---

src/mapgen_functions.cpp

Addendum  to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3275
As was mentioned in previous PR i didn't fully resolved how multiple coast lines should be drawn on one shore map, and it could connect them in wrong order. But after some pondering i finally found a good way to resolve it.
// Each shore have up to 8 connection points where coast line can be attached. Let's say
// we have river_north at the west, it will be attached to slot 2.  Another shore at the
// north, with one mutual lake at NE, it will be attached to slot 1. One more shore at east
// with two mutual lakes at SE and NE, that'll make it attach to both 6 and 7 slots. That's
// what we need to get in the end:
//  -1----0-
// |....    |      Overmap:
// 2........7        FSL
// | .......|        R@S
// 3  ......6 …

Better shore line at 3 and 4 way junctions

---

data/json/furniture_and_terrain/furniture-appliances.json

SUMMARY: Interface "Set small battery furniture to not look like lockers"
This accounts for the small battery furniture added recently not properly getting its `looks_like` from basic furniture batteries and defaulting to lockers instead. I opted to make them more distinct since they are less bulky and easier to make.
Set the smaller battery furniture to have `looks_like` resembling plain storage battery items, in the vein of other basic placed tools.
Drawing up a custom sprite for smaller furniture batteries.
2. Ported file change to test build and checked that small storage batteries, car batteries, and bike batteries looked like the item sprite when placed.

Update looks like for small battery furniture

---

src/character_functions.cpp

SUMMARY: Bugfixes "Removed unused itype from character_functions.cpp"
Fix tiny error noticed by the tests for https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3359 for some weird reason.
In character_functions.cpp, removed an obsolete reference to the item ID for To Serve Man now that it's handled by item flags instead.
Screaming.
Double-checked that the `itype_id` is indeed unused anywhere in the file.
My fucky-wucky in: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2910

Fix unused reference to To Serve Man

---

data/mods/TEST_DATA/items.json
src/assign.h
src/item_factory.cpp
tests/item_test.cpp

SUMMARY: Mods "Implement 'extend' for magazines"
Make it possible to add new magazines without having to re-declare the entire magazine block, which prevents mod compatibility if two mods want to modify the same gun.
* Implement `assign` for `std::map<string, std::set<string>>`
* Add an ugly hack for `magazine_default` field
* Throw an error if `"delete"` is used on `"magazine"` field - the problem is un-setting the `magazine_default` field
Changing the `magazines` field to map of vectors (instead of sets), so that `magazine_default` can be set in `finalize`.
Paste the following in any file in main mod (plus missing comma, if needed):
```JSON
{
"id": "test_glock_19_conversion",
"type": "GUNMOD",
"name": { "str": "TEST Glock 19 SHOT conversion" },
"description": "Conversion kit that makes …
```

Implement "extend" for magazines

---

data/json/items/comestibles/raw_veggy.json

SUMMARY: Balance "This PR changes the weight of tea leaves to be more inline with reality" 
This changes the weight for a single tea leaf to make it more correct with the weight of a single tea bag. Considering that each tea leaf is a single serving to make 1 cup of tea. 
Changed the weight from 14 g to 2 g
Searching online shows that generally 1 tea bag is only 2g at most.  When you start getting lots of tea leaves the weight can get a bit absurd. 
None
Tested in my own fork.

Changed weight of raw tea from 14 g to 2g

---

src/activity_item_handling.cpp

SUMMARY: Bugfixes "Fix blueprint construction zone functionality"
Fixes #2904
Current implementation of `find_base_construction` is very easy to break, as demonstrated in the linked issue. If the designated construction is not possible it will search through all possible constructions and pick the first one that can be executed. In the linked issue if you have the skills and components necessary to build a chain fence it will do so if unable to remove grass.
Another example displays an infinite loop:
- Start new game with Fabrication Skill at 3
- Designate a `Build Brick Wall from Adobe` blueprint construction zone through `Y` menu on a `Grass` terrain tile
- Does not matter if you have components necessary to build the wall
- Start building `O` menu
- Will infinitely loop between …

fix: make find_base_construction not broken

---

src/handle_liquid.cpp

Ported & merged over fix https://github.com/CleverRaven/Cataclysm-DDA/commit/7445cfe0db80d4f5d43d5f099c4ef5cd19cf99d0 to BN
To add the ability to transfer liquids from one vehicle tank to the other in the same vehicle, since this change was added in DDA but not BN And a good QoL change
Add the ability to fill an available tank, where applicable, in a vehicle
Not having the change?
Testing ingame shows no errors or game breaking bugs, everything seems to work

- Ported commit siphon vehicle fix from DDA repo to BN

---

src/overmap.cpp

SUMMARY: None
Get rid of the common annoyance in CI
Silence these errors
A proper fix. If only labgen was not so convoluted...
Should not show this error anymore

Silence lab type errors

---

src/vehicle_selector.cpp
src/vehicle_selector.h
src/visitable.cpp

Bugfixes "Allow using jacking tools from vehicle cargo"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2942
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/48640
Removed wheel using jack stored in same vehicle

fix(port): allow using jacking tools from vehicle cargo

---

src/overmap.cpp

SUMMARY: None
Continuation of #3449 
Should work (tm)

Silence more lab type warnings

---

src/bionics.cpp
src/iuse.cpp

Content "More things to please pyromaniacs"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3442
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/57330
Making binic lighter use `firestarter_actor`, but during looking whether DDA already did it or not i noticed above PR, which can be just cherry picked right away, without any extra hussle. So be it.
Lighted fire with bionic, threw a molotov and inc grenade. It just works.

fix(port): add missing pyromaniac morale boost for bionics and explosives

---

data/json/recipes/chem/chemicals.json

Fix ammonium nitrate recipes to have distinct IDs so both show up in game.
SUMMARY: Bugfixes "Fix ammonium nitrate recipe"
Ammonium nitrate had 2 crafting recipies, however only one is available in-game, as they both have the same id.
Add missing id_suffix to one of the recipes.

Fix ammonium nitrate recipe

---

data/json/recipes/weapon/piercing.json

SUMMARY: Bugfixes "Fix bronze dagger recipe overriding steel dagger"
Copypaste screwup I made in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3425
Fixed the result ID of bronze dagger recipe to actually make a bronze dagger, not a medieval dagger.
Screaming.
Used my eyes for once.
aaaaaa

fix: bronze dagger recipe using wrong ID

---

data/json/items/generic.json

SUMMARY: Bugfixes "add . at the end of tanbark description"

fix: tanbark description

---

.github/pull_request_template.md

SUMMARY: Infrastructure "Added checklist to the PR template"
It's very common for PRs to change some functionality, but do it only partially or miss some step like updating the documentation.
Add a checklist to the PR description as an experiment. I've copied it to this PR's description to show how it looks "live".
Move this to dedicated docs, but then you wouldn't be able to tick items off the list.
Maybe also request JSON format changes to attempt at backwards compatibility?
This PR is the test in itself.

chore: checklist in PR template

---

src/creature.cpp

SUMMARY: Bugfixes "Fixed zero monster speed on spawn"
Fixes #3548
A typo in Creature constructor caused wrong value to be copied to the `speed` variable
Fix typo
Freshly-spawned turrets now fire properly

fix: zero monster speed on spawn

---

src/activity_item_handling.cpp

SUMMARY: Bugfixes "Fix moving firewood onto a fire"
Fixes #3549. 
Rejig so it's not deleting during the loop.

fix: moving firewood onto a fire

---

src/handle_liquid.cpp
src/item.cpp

SUMMARY: Bugfixes "Fix crafting deleting stuff"
Fixes #3563. Fixes #3557. Also fixes a bug with drinking.
I missed some assignments and messed up one of the patches yesterday.

fix: crafting deleting stuff

---

data/mods/No_Hope/regional_map_settings.json

SUMMARY: Mods "No Hope doesn't make the world freezing"
After many complaints about summer being extremely cold in No Hope, I asked Night Pryanik if it was intentional design. I was told the weather should be vanilla, so I'm changing it to vanilla.
Since regional map settings requires weather to be defined, I copied and pasted vanilla's current weather settings. This will work until we change it. After asking @chaosvolt  I'm pretty sure I can't stop No Hope from overwriting the weather as it overwrites mapgen to spawn houses and map extras in a different way, and I'm not sure if transplanting all of that to a region overlay would correctly overwrite vanilla's mapgen.
We need to code a better way to modify the regional map settings without having to overwrite each part of it, but I can't …

feat(mods/no hope): No Hope doesn't make the world freezing

---

src/locations.cpp

SUMMARY: Bugfixes "Fix holster/bandolier draw speed"
Fixes #3576.
Readd some code that was in the old item_location to the new location stuff.

fix: holster/bandolier speed

---

src/npcmove.cpp

SUMMARY: Bugfixes "NPCs will keep their splints on."
Some people in the Discord have brought up that NPCs are removing their splints, so I looked into it. Found another bug in the process that jove will need to look at.
The issue here is that the code for NPCs checks if limb hp is less than or equal to 0 to determine if the splint should be left on. As #3054 has changed broken limbs are defined, this returned an erroneous result.
Use `is_limb_broken()` function as the gods intended.
- Check for disabled effect on limb.
- Awesome idea if we like to break things every time someone touches how limbs are broken. Truly an immersive experience.
- Remove the `adjust_worn()` function entirely.
- It's not doing it's purpose right, see additional context.
- Spawn NPC, mind control them.
- Set any …

fix: NPCs keep their splints on

---

data/json/monsters/mammal.json

SUMMARY: Balance "Set moose to yield pelts instead of hides when butchered"
Something spotted by Zeni over on the BN discord.
Set moose to use `mammal_large_fur` instead of `mammal_large_leather`, as moose pelts are typically going to be shaggy enough to justify it.
Adding it to cows and deer. Those are probably closer to leather than fur so eh.
Checked affect file for syntax and lint errors.
DDA seems to have fixed this at some point too, so.

feat(balance): Give moose pelts instead of hides

---

src/npc.cpp

SUMMARY: Bugfixes "Fix error message on npc takeoff"
Fixes #3609.
Clear the iterator before takeoff.

fix: error message on npc clothing takeoff

---

data/json/furniture_and_terrain/terrain-flora.json

SUMMARY: Bugfixes "Adding lacked description to harvestable coca tree"
#3626 added cacao tree and coca tree in game, but coca tree didn't have any 'This tree has some harvestable thing' sentence. This PR will fix it with adding a simple sentence.
Adding _If you examined the trunk of the tree, you could probably find some mature coca leaves._ to the description of harvestable coca tree.
Leaving it in current state.
Didnt tested yet, but simple json change won't break anything... right?

fix: Add harvestable coca tree description

---

data/json/mapgen/house/2Story02.json
data/json/overmap/multitile_city_buildings.json
data/json/overmap/overmap_terrain/overmap_terrain_residential.json
data/json/regional_map_settings.json

more houses
linted and spawned in game.
2 variants each for basement, ground floor and second floor.

feat(content): 2Story02

---

.github/pull_request_template.md

Iterating on PR template
Changes per feedback after #3519
Compress PR title instructions introduced by #3536 into a paragraph 
None
None needed
Won't show up for every PR now

chore: adjusted PR template per feedback, stylistic changes

---

src/submap.cpp

Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3689
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3635
Added swap of cosmetics to submap::swap, it must been overlooked during items identity refactoring. 
None.
Spawned rotated mortuary, and vandalized shelter. Signs working, graffiti on their places.

fix: rotation of signs & graffity

---

data/json/vehicleparts/vehicle_parts.json

The travois was larger than the wood box, and thus had more cargo space, despite the travois being made of sticks and rope and the wood box being made of proper nails and lumber.
The sizes of the two have been swapped around, so the travois is now 150 and the wood box is 300.

feat(content): swap travois and wood box size

---

src/iuse.cpp
src/location_vector.cpp

Fixes #3714. Also fixes an inaccurate error message.
More awkward iterator stuff.

fix: bad iterator message in chopping logs

---

src/iexamine.cpp

Fixes #3712.
More iterators, more false positives though.

fix: bad pump iterator

---

src/map.cpp

Fixes #3738.
Use the new interfaces. That said, I'm not sure why this was crashing before and I want to look into it. This is a quick fix until I find the real cause.

fix: mopping floors

---

.github/workflows/manual-release.yml
.github/workflows/msvc-full-features-cmake.yml
.github/workflows/msvc-full-features.yml
.github/workflows/release.yml

- fixes #3740
port https://github.com/CleverRaven/Cataclysm-DDA/pull/69592 by @akrieger

ci: bump vcpkg version to fix MSVC build

---

data/json/snippets/epilogue_npc.json

I decided that since I am not well-versed in the deeper code of the game, I may as well contribute where I can: in JSON. Similar to last time when I added more snippets for Schizophrenia, this one is aimed at adding more endings for NPCs.
Added several new epilogues for both male and female NPCs.
Leaving it be.
Seems to be working fine. Just some simple new lines in JSON.
Hope everyone's doing great. 😄

feat(content): New Epilogues for NPCs

---

data/json/mapgen/cs_public_art_piece.json

Some changes to remove the flying roofs above.
JSON changes.

fix: cs_public_art_piece mapgen

---

data/json/snippets/graffiti.json
data/json/snippets/grave_labels.json
data/json/snippets/survivor_notes.json

Following up on my previous PR, this time I'll be adding more grave_labels, graffiti, and survivor_notes.
Adding more snippets.
Leaving it be.
JSON only.
Hope everyone lives a wonderful life. :D

feat(content): More Snippets

---

data/json/snippets/graffiti.json

Gosh darn it I left some numbers in the previous order before my final edit.
Real quick fix!
Nope.
Quick fix in JSON!
RAAAH

fix: misalignment in snippet id numbering

---

data/json/items/armor/ammo_pouch.json

Fixes some assorted things I overlooked when approving https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3777
1. Removes redundant, misspelled plural form of the renamed ammo satchel.
2. Renamed ammo pouches/satchels to refer to magazines instead. Turns out someone (someones, both @yay855 who PR'd it and me who approved it) forgot that "ammo satchel" was already in use for the name of the makeshift waist mag carrier, so might as well just standardize that now.
1. Reverting the ammo pouch name change in above PR.
2. Screaming.
2. Used my eyes for once.

fix: fix naming conventions for mag pouches, remove redundant plural

---

CMakeLists.txt

fix occasional build failure in local and CI caused by https://github.com/llvm/llvm-project/issues/53950 
add `C` languages in [`project`](https://cmake.org/cmake/help/latest/command/project.html).
newer LLVM should fix it
worked on my machine. let's see if it works on CI too.

build: fix cmake build

---

src/location_vector.cpp
src/location_vector.h

Fixes #3790 and probably a host of other similar problems
Get rid of them.

fix: Remove active iterator messages

---

src/cata_variant.h
src/character.cpp
src/character.h
src/consumption.cpp
src/iuse.cpp
src/iuse_actor.cpp
src/iuse_actor.h
src/magic_spell_effect.cpp
src/map_field.cpp
src/mapgen.cpp
src/memorial_logger.cpp
src/mutation.cpp
src/mutation.h
src/mutation_data.cpp
src/mutation_data.h
src/npc_class.cpp
src/npc_class.h
src/player_hardcoded_effects.cpp
src/type_id.h
src/wish.cpp
tests/memorial_test.cpp
tests/modify_morale_test.cpp
tests/mutation_test.cpp

Type safety, resolving tech debt introduced with parametric mapgen, maybe some performance improvements - string_id supposed to be faster than regular string.
Ported https://github.com/CleverRaven/Cataclysm-DDA/pull/43421, and also removed hacky check which i added to mapgen.
None
Game builds, runs, consuming mutagens respect categories, dream picked correctly, unit tests are passing.

refactor(port): Make mutation_category ids be string_ids

---

src/overmap.cpp

Fix overmap editor.
Ported:
* https://github.com/CleverRaven/Cataclysm-DDA/pull/52762
None.
Spawned evac center, no more failed asserts.

fix(port): failed assert when placing special in overmap editor

---

data/json/furniture_and_terrain/terrain-flora.json

Make ferns easily passable by vehicle
Ferns in game can easily stop APC at low speed. It is hardly expected behavior for players since ferns are usually not strudy or big.
Set VEH_TREAT_AS_BASH_BELOW to ferns.
None.
1) Spawn t_fern and t_fern_harvested
2) Spawn APC
3) Drive ore ferns at 12 km/h
4) You should easily pass fern. APC must not collide or stop.
Save for testing attached:
[AT bush.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13624867/AT.bush.zip)

feat: Make ferns easily passable by vehicle

---

data/json/furniture_and_terrain/terrain-fences-gates.json
data/json/player_activities.json
data/mods/TEST_DATA/furniture.json
data/mods/TEST_DATA/items.json
data/mods/TEST_DATA/terrain.json
doc/src/content/docs/en/mod/json/reference/json_info.md
lang/extract_json_strings.py
src/activity_actor.cpp
src/activity_actor_definitions.h
src/iuse.cpp
src/mapdata.cpp
src/mapdata.h
tests/player_activities_test.cpp

Unhardcode bolt cutters. And it introduces basic infrastructure(activity_data_common) for more unhardcoding later on.
Ported: 
* https://github.com/CleverRaven/Cataclysm-DDA/pull/50057
* https://github.com/CleverRaven/Cataclysm-DDA/pull/50365
* https://github.com/CleverRaven/Cataclysm-DDA/pull/51160
None.
It have very detailed unit tests. All passed. And it also works in game.

refactor(port): bolt cutting migrated to activity and jsonified

---

data/json/recipes/ammo/rifle.json
data/json/recipes/ammo/shot.json

Noticed a few inconsistencies with the Rivtech caseless ammo crafting recipes:
- 20x66 shotgun ammo recipes produce different number of shells from identical amounts of basic resources (variant differences notwithstanding)
- 20x66 shotgun ammo doesn't take primers, while other caseless ammunition does
- 20x66 flechette recipe allows use of regular nails, unlike other caliber ammo of this type
- 8x40 ammo takes 1 primer per batch instead of per round crafted
- 8x40 HVP takes an increased amount of gold/platinum/silver/tin/solder, neither of which is a suitable material for a _High Velocity Penetrator_
- changed the 20x66 flechette recipe to produce 20 shells instead of 10 to match the other two recipes. It's not **that** much better than 12ga to justify the cost at only 10 made per batch. …

feat(balance): improve consistency of handmade caseless ammo recipes

---

data/json/items/ammo/atgm.json

This was a follow-up I noted we oughta do in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2381 that I completely forgot about. Rationale: TOW missiles are still set to do massively lower direct impact damage than over rockets or grenade launcher rounds.
Increased ATGM damage from 30 to 200, making its total damage equal to that of 40x53mm HEDP. 40x53mm has 250 direct damage and 50 damage from ammo effect, vs. ATGM having 200 direct damage and 100 explosion damage.
Screaming at relative balance of Big Dicc explosive weapons yet again and struggling to overhaul them once more.

feat(balance): belatedly rebalance ATGMs relative to other ammo

---

data/json/ammo_effects.json
data/json/items/tool/explosives.json
doc/src/content/docs/en/mod/json/reference/json_info.md

A while back I mentioned that a mininuke, as awkward as it is to use, probably oughta be one of the few things with hulk-tier damage, given actually dropping it at something's feet, catching them in the blast, and surviving is an impressive challenge. But with how eager explosion damage is to ruin floors, more blast damage alone doesn't seem like the ideal solution...
1. Added a fragment definition to the mininuke explosion `use_action`, using damage type `heat` with an amount equal to its explosion value.
2. Updated the `MININUKE_MOD` ammo effect accordingly. Last I checked any items using it have been mod-shifted anyway.
3. Updated documentation on explosion stuff a bit per Scarf's request.
1. Buffing direct explosion damage to even more absurd degrees instead.
2. Just using normal …

feat(balance): add heat-type damage to mininukes

---

src/vehicle.cpp

Fixes #3867 
Removes the parts from the destroyed vehicle more gracefully.

fix: mounting vehicles to racks

---

data/json/recipes/armor/arms.json

Fixes a mistake I noticed.
Fixed steel arm guard recipe being borked to not use forging.
Screaming.

fix: fixes steel arm guard recipe

---

data/mods/Craft_Gunpowder/modinfo.json

Minor thing that was pointed out to me a while ago, the Craftable Gun Pack still talked about craftable gunpowder when we now have a vanilla recipe.
Edited description in modinfo along with a note about why the mod folder (visible in world creation screen) still refers to gunpowder.
Renaming the mod's folder should remove the need to add a note about it, but I worry that might break old saves and/or updates. I worry launcher users especially will likely either run into problems or create them themselves depending on how the simple launcher and catapult works vs whether anyone tries to dump folders on top of old folders without proper cleanup.

fix: update description of Craftable Gun Pack mod

---

data/json/mapgen/nested/basement_nested.json

Fix a misplaced vehicle.
Change vehicle position.
none
Before:
After:

fix: room_8x8_junk_W nested mapgen

---

data/json/vehicleparts/turret.json

Smol and easy lil addition.
Added a vehiclepart definition for the craftable laser rifle.
screm
2. Ported file change to test build and load-tested.
3. Confirmed it looks like a regular mounted laser rifle when installed.

feat(content): add vehicle-mounted shoddy laser rifle

---

data/json/item_actions.json

A smol update on my todo list, the item action name for `GUN_CLEAN` was too easily confused with the item action name for `GUN_REPAIR`
Changed wording from `"Repair/mend a gun"` to `"Clean/mend a gun"`, to avoid easy confusion with the similar wording of the nearby action on gun repair kits, `"Repair a gun"`.
Figuring out how to write up a menu that makes the "pick a gun to mend" menu filter out non-guns.
Used my eyes.

fix: make item action name of gun cleaning a bit more distinct

---

src/vehicle.cpp

Fixes #4032.
Setup the locations correctly when unfolding them.

fix: foldable vehicle locations

---

data/json/overmap/overmap_mutable/lab.json

Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4029
It currently places cores cores instead of stairs at z-2, must be copy-paste error. Changed OMT to correct one.
None.

fix: central labs will generate stairs at z-2

---

data/json/professions.json

It is copied from student profession, but with a small trait and AWESOME RANDOM BOOK BOX.
Add the profession with some of random items.
I hope this PR will help you create professions that lead to randomized situations.
Copy student profession, and add another item with contents-group like below.
```json
"entries":[ 
{"contents-group":["manuals_school", "textbooks_school","light_reading"], "item":"box_small" } 
]
```
If multiple items exist within a container, the Profession window does not display their contents. Therefore, player cannot check what books are in there.
Only when you start the game will you see the contents of the box.
Trying to change profession code to get randomized option.
That way would be long and painful.

feat(content): profession with random books

---

data/json/mapgen/ranch_camp.json

I want to make some changes in the ranch camp but first tidy up the json.
JSON changes:
Move "type", "om_terrain", "weight" to the right place like on other mapgen.
Do nothing.
1. Check JSON file and no visible error.
2. No error message when starting a new character.
3. Debug the ranch and no errors found.
none

style: tidy up `ranch_camp.json`

---

data/json/mapgen/hospital.json

This belatedly makes the hospital roof a bit less empty, like I'd promised to do a while back.
Set it to place infrastructure/utility chunks at a decent rate in each of the roof tiles not next to the helipad, idea being keep the extra utility stuff spaced away from it.
Additionally, set the space near the helipad to have a modest chance of spawning signs of former survivors having camped out on the roof, including a decent chance of the "help" chunk appearing.
Screm
2. Ported JSON file to test build, load-tested, spawned in a hospital to look at the roof.

feat(content): add roof chunks to hospital roof

---

data/json/items/ammo.json

Don't allow cutting apart a pile of yarn into felt patches, doi.
Added `NO_SALVAGE` to yarn, just as thread has.
Sinew and plant fiber don't seem to be made of materials that can be salvaged into anything, but keep in mind for if that ever changes.

fix: don't salvage wool thread into wool patches

---

doc/src/content/docs/en/index.mdx

Fix link that gave 404.
No testing done.

docs: Fix link in documentation frontpage.

---

data/json/items/comestibles/carnivore.json

continuation of #4185 due to accidental branch deletion.
Make a smoking rack to cure hides or furs.
Simply add a `smoking_result` field and `SMOKABLE` flag on the skins.
Those code would make them what I expected.
~~Gently weeps.~~ Trying it after smoking rack or some iexamine JSONized.

feat: smoking rack can cure skins

---

data/json/items/ranged/archery.json

Tweaks a mistake of #2862, for composite longbow.
It doesn't follow the DMG/req_STR ratio for composite bows.
The ratio for the composite is 4.
So I put the number of required STR to 9 instead of 11.
Gently weep.

feat: tweaks for composite longbow

---

data/json/items/comestibles/meat_dishes.json

Fixes #3768 
```Dry_meat``` was missing a ```"delete": { "flags": [ "NUTRIENT_OVERRIDE" ] }``` line in ```meat_dishes.json```
Dehydrating mutant meat, now gives as a result "dehydrated meat, mutant", with correct toxin value.

fix: Mutagenic toxins missing from dehydrated meat 

---

data/json/construction.json

Fix #4197 's bug that the construction `Gather Clay From Dirt` gives you **just one clay**.
`charges` --> `count`. EZ
Cry and feel a shame

fix: give me more clay, ooze bog

---

doc/src/content/docs/en/mod/json/reference/json_info.md

- #2541 is not properly documented in docs
Add documentation
Laughing evilly as someone reinvents the wheel.
Nothing. I can't really preview my changes.

docs: Add documentation for mod_target_category

---

data/json/recipes/food/other.json

@Lamandus spotted that hard cheese recipe is in the meat subcategory despite the recipe JSON being in the file for other.
Changed hard cheese's subcategory from `CSC_FOOD_MEAT` to `CSC_FOOD_OTHER` like soft cheese and like the other items in the file.
screm
Used my fucking eyes for once.

fix: correct sub-category for hard cheese recipe

---

data/mods/No_Wasps/modinfo.json

monster exclude for all wasp and dermatik monsters and monster_groups
do not merge this until after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4265 has been merged

feat(content): `No_wasps` mod

---

data/json/npcs/refugee_center/surface_refugees/NPC_Boris_Borichenko.json

the mission description for Boris's second mission is ambiguous
changes the mission name so to mention a `circular saw`
👍

feat(content):Update Boris mission text

---

data/json/requirements/cooking_components.json

doratheexplorer1230 on discord informed me that insect eggs couldn't be used for cooking
added the list `eggs_insects` to cooking components group `"eggs_small"`

feat(content): Cooking with insect eggs

---

data/json/monsters/insect_spider.json

adds the flag `"HIT_AND_RUN"` to wasps & dermetiks
terrifyingly effective

feat(content): Sting and Run

---

data/json/npcs/refugee_center/surface_staff/NPC_free_merchant_shopkeep.json

reduce the number of `glass jars` from 100 to 25. 
👍

feat(balance): reduce jar requirement in `In a Pickle` mission

---

data/json/furniture_and_terrain/furniture-appliances.json

Back when I was updating battery power density figures, turns out I'd updated grid storage batteries but forgot about grid vehicle batteries, for which some values changed, hecc.
1. Updated capacity of mounted car battery from 2500 to 3000, matching its item form.
2. Updated capacity of mounted motorbike battery from 500 to 600, matching its item form.
3. Updated capacity of mounted small motorbike battery from 150 to 300, matching its item form.
Forgetting about it again.
2. Used my eyes.
Capacity was changed back in: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3877

fix: increase capacity of lead-acid grid batteries

---

src/iuse.cpp

mp3 music log spam is super annoying
Fixes: #4190
Describe music once every hour instead of every 5 minutes. It's actually nice when it's a lot less frequent.
spawn mp3 player + watch. put on mp3 player and turn it on. wait X hours. only see X music messages.
A good fix today is better than a perfect fix next year.

feat: limit music log spam

---

data/json/items/comestibles/drink.json
data/json/items/comestibles/raw_veggy.json

Coca tea and Coca leaves were being eaten when auto-eat and auto-drink zones were created. That can lead to a cocaine withdrawal.
use the unsafe consume tag so it won't be used automatically. Same as alcohol.

fix: Coca is not safe to eat

---

data/json/recipes/other/other.json
data/json/recipes/weapon/explosive.json

Dynamite Bomb and the mechanical pump used the soldering iron as possible tools to fuse metal together. I removed them, since glare protection was needed anyway to make the craft, which doesn't make sense using a soldering iron.

fix(balance): remove soldering iron as possible tool for 2 recipes

---

data/json/npcs/cabin_chemist/cabin_chemist.json

Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4351
Search-and-replace'd all hits of `bottle_plastic_pill_prescription` in NPC folder with `bottle_plastic_small`.
screm
2. Also checked the rest of the `container` entries in that file, far as I can tell everything else uses containers already in the game.

fix: cabin chemist gives you bottles that actually exist

---

data/json/items/comestibles/egg.json

SUMMARY: Fixed typo in "wild veggetable omelet" item name
I noticed a minor typo in the name of an item, the "wild veggetable omelette," and I figured it would be quick and easy to make a PR that fixes it.
Typo fix in JSON, no code change.
No other solutions applicable
Searching the repository for "veggetable" yielded no other results than this item name, and the item ID itself is not misspelled nor modified, so it is unlikely that changing the name would break any references to this item.

fix: minor typo in "wild veggetable omelette"

---

data/json/items/comestibles/veggy_dishes.json

Dry rice had negative calories due to a missing flag. Added flag. 1 AM here, too tired to explain it all. Result speaks for itself
fixes: #4317

fix: negative calories when creating dry rice

---

src/consumption.cpp

First step into morale changes. This will change the timer from 2 hours until the morale completely depletes from food to 12 hours.
This also includes negative modifiers. So chugging oil is not that valid anymore and cooking high morale food is now a great boon.
See above. This is not the end tho, @MrLostman is also working on morale timer buffs for other things, so this is just a first step, it may change in the future.

feat(balance): increase morale gain (and loss) from food to 12 hours

---

src/character_effects.cpp

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4391 missed a smol thing and it makes the buildbot complain about an activity being defined but not used.
Remove the now-unused definitely for `ACT_READ` from character_effect.cpp.
screm
Compiled and load-tested, the real test is making sure clang-tidy finds nothing else to complain about.

fix: remove unused variable to make clang-tidy stop complaining

---

src/clzones.cpp

Fix #4402
Fix inverted condition in `remove_if` causing zones to be removed only if they are valid
None

fix: zones being erased on loading save

---

data/json/recipes/ammo/other.json
data/json/recipes/other/containers.json
data/json/recipes/other/other.json
data/json/recipes/other/tools.json

Right now, crafting stuff from clay have 2 different set of recipes. "Old" ones and "new" ones. The old ones always needed cordage, leather/skin and glazing. The new one neither of those 3. Now the recipes don't use skin or cordage, but always need glazing. Also the time amount to craft and the amount of heat was standartized too.

fix(balance): clay crafting standartization

---

data/json/recipes/food/meat.json

This effectively mainlines jerked offal from MST Extra, though a bit simplified. Idea being this allows a way to preserve organs as well, rough lookup indicates this is a thing that's done (though more commonly for dog treat jerky since organs aren't used as much commercially, but vet offices already have jerky spawning there).
Added `offal_raw` as a component option to the recipe for jerky.
Mainlining jerked offal as a separate item. I'd have to change the recipe a bit, maybe make it a level in difficulty higher, anything because the MST Extra version is functionally identicaly to the regular jerky recipe so no actual value in it being a separate recipe.
2. Built and ran tests, no weird comestible test failures from what I could see.

feat: allow making jerky with offal

---

data/json/construction.json

The pine tree lean-to only was able to use "non harvested" trees. Now it also can use the harvested variant.

fix: pine tree lean-tos can also use harvested pine trees

---

data/json/construction.json
data/json/construction_group.json
data/json/furniture_and_terrain/terrain-doors.json

There was only one way to produce a door frame, it was inside the standard door construction path. You can use glue and nails, too, now.
Make own construction for the frame (since there are multiple doors. 2 more ways to produce (with glue) or with higher skill logging onto place with no adhesive.

feat: add different constructions for door frames

---

data/json/items/generic.json

Pine boughs are useful for a lot of crafts (for example superglue or tea), but are sorted for fire wood and will be burned alongside planks and logs. This removes the tag so it will be sorted in the regular "S. Parts" zone instead of the firewood zone. They are still burnable and usable as firewood if desired.

fix(balance): pine bough is not considered firewood automatically.

---

data/json/items/comestibles/junkfood.json
data/json/recipes/food/dry.json
data/json/recipes/food/meat.json
data/json/recipes/food/other.json
data/json/recipes/other/other.json
data/json/requirements/cooking_components.json
data/mods/DinoMod/recipes/food_egg.json
data/mods/DinoMod/recipes/recipe_food.json

Meat and wood soups were good, but they lacked some consistency, for example, already cooked meat products can be used, but not all. For example raw offal was possible, but cooked variants weren't. Also I added some groups to make better list and add missing meals.
1. Add a cooked offal group
2. Add a raw and cooked meat+sausage group
3. Add those groups to different soups
4. Add cooked offal to many recipes that only took raw offal (sausage)
5. added large craft versions for sausages (for large stomach)
6. moved bologna and jerky out of raw meat, added them to their groups respectively
7. tinker the amount of ingredients used for different soups
8. 
No errors.
smoked meat is now found in a lot more recipes, same with canned meat and fried offal.

feat(balance): allow more ingredients in different meat based recipes, add of new meat groups

---

data/json/recipes/food/meat.json

Pemmican was using a very narrow amount of ingredients. For something being very versatile and having a lot of different ways to make, it was very very limited. This recipe is now using a whole lot more ingredients.
Add lists for the different ingredients instead of counting up the different ingredients manually.

feat(balance): make pemmican out of a lot more ingredients

---

data/json/items/comestibles/carnivore.json
data/json/recipes/food/meat.json
data/json/requirements/cooking_components.json

Offals were always used seperatly. Which means, a lot of crafts didn't take advantage of the batching (canned offal, fried offal). To make it a bit more smooth, there is now a "raw offal" recipe, that mixes all offal together. It is in the same category as the mix weak and strong alcohol. Funnily enough, "raw offal" wasn't dropped per butchering anymore, but was a drop at some places. So this change now makes raw offal craftable.

fix(balance): offal mix recipe and requirement group corrections

---

data/json/requirements/cooking_components.json

dehydrated vegetable was not user friendly. It has to be rehydrated to be used for recipes, so it was easier to just eat it. This makes the use of dehydrated vegetable more versatile by just adding it to one requirement group. For example broth can be now made with dehydrated vegetables (what you do at home as well).

feat(balance): add dehydrated vegs to a lot of recipes.

---

data/json/recipes/food/other.json

Sugar was not craftable without books. You had one sugar recipes calling for chem making 2. But that provides a problem. Chem making 2 is not obtainable. You need either a book to craft a basic chem set, or you need to find one. There was one recipe that only calls for chem making 1 and sugar beet, but it was not autolearn (for whatever reason).
1. make sugar beet variant of recipe autolearn
2. make sugar recipe out of sweets and fruits use the same tolls as the sugar beet variant.

feat(balance): standartize sugar production and make sugar obtainable innawoods

---

data/json/items/tool/cooking.json
data/json/recipes/food/other.json

Yeast is not craftable in the wild. It needs a glass jar. Glass jars can't be crafted via autolearn. So a innawoods variant is needed. Clay bowl (which only has one other recipe use in butter) is now a bit more useful.

feat: make wild yeast with clay bowls

---

data/json/items/tool/cooking.json
data/json/recipes/food/other.json

As the wild yeast version, this adds a clay bowl version for the regular yeast production.

feat: Add yeast clay bowl recipe

---

src/debug_menu.cpp
src/main_menu.cpp

Within the Info debug menu, adds a discord invitation to Bright Nights Discord.

feat(content): Discord invite from debug

---

data/json/requirements/cooking_components.json

There were some "plant matters" missing in the wood soup recipe. This adds them in.

feat: Update Wood soup recipe

---

data/json/recipes/electronic/parts.json

The recipe for wind turbines called for bicycle and motorcycle alternators. This let also use car alternators being used for the craft, since they are very common.

feat(balance): wind turbine also accepts car alternators

---

data/json/items/armor/ammo_pouch.json
data/json/recipes/armor/storage.json

Magazine pouches were not balanced correctly. New flag (compact) wasn't added, so a chest magazine pouch would conflict with a backpack. The recipes were also not updated properly.
1. corrected description
2. changed encumbrance of multiple pouches
3. recipe corrections and updates

feat(balance): magazine pouch audit

---

data/json/recipes/chem/chemicals.json

Acid is needed for few crafting recipes, but it needs chemical making 3, which is unobtainable innawood playthroughs
Changed the requirement from chemistry 3 to distilling 1. With this way, old chemistry kits still(hehe) able to cook acid, while distill is now an alternative way to make it.

feat(balance): Readjust tool requirements of acid water, make innawoods acid crafting possible

---

data/json/obsoletion/items.json
data/json/obsoletion/recipes.json

some recipes weren't officially obsoleted or moved to the right file. this corrects it.

fix: obsolete recipe corrections

---

data/json/deconstruction.json
data/json/furniture_and_terrain/furniture-industrial.json
data/json/furniture_and_terrain/furniture-roof.json
data/json/furniture_and_terrain/terrain-zlevel-transitions.json
data/json/mapgen/wind_turbine.json
data/json/overmap/overmap_special/specials.json
data/json/overmap/overmap_terrain/overmap_terrain.json

- https://github.com/CleverRaven/Cataclysm-DDA/pull/51516 by [wapcaplet](https://github.com/wapcaplet)
- https://github.com/CleverRaven/Cataclysm-DDA/pull/51476 by [jbytheway](https://github.com/jbytheway)
- https://github.com/CleverRaven/Cataclysm-DDA/pull/63534 by ghost 👻 
adds Wind Turbines as a wilderness map location, and adds `t_ladder_up_down`
ground level
power nacelle at z-level 8
Average distribution in a test mapgen
a subsequent pull request will implement the `t_ladder_up_down` in other maps

feat(port,content): Wind-Turbine plus `t_ladder_up_down`

---

data/json/items/armor/sheath.json

This changes the amount of encumbrance of sling based items (axe ring, spear strap, etc.). Now those items give more encumbrance when an item is actually added to it. If left empty, they are either 0 or 1 encumbrance. For the spear strap, the bigger the spear is, the more encumbrance it will give.

fix(balance): remove encumbrance for empty sling based weapon holders

---

data/json/items/armor/sheath.json

Back scabbard got a lower encumbrance than the regular one. This fixes it.

feat(balance): corrected back scabbard encumbrance

---

README.md

Fixes a typo in the README
Fixing a typo
There was a typo that needed to be fixed
None
None
N/A

fix: typo in `README.md`

---

data/json/recipes/armor/legs.json

I hope it works, since I did it all from my phone, let me tell you, it is finiky. Shorten recipe time of making pants shorter. Same with cargo shorts.

feat(balance): shorten trousers shortening recipe.

---

data/json/recipes/food/meat.json

Found it weird that you could make sausage casing with dirty water but not clean, included clean water as an alternative.
Although the more I think about it the more I'm thinking food-grade stuff should be made with clean water anyways.

fix: sausage casing recipe to use clean water as well as normal dirty water.

---

data/json/martialarts.json
data/json/techniques.json

Rapid strike and similar techniques have been rebalanced to no longer reduce damage dealt, and their movecost reduction is changed from 50% to 75%. Eskrima also had three techniques that served that same purpose, which was mild bloat given that techniques are chosen semi-randomly.
Rapid strike and similar techniques punished already-weak weapons (knives, mostly), reducing their already-low damage in favor of greater attack speed- but this game's armor calculations make damage far more important than speed, making such a technique horrible.
Rapid strike and similar techniques have had their damage reduction removed and their movecost reduction lessened, with most techniques of that type now simply being a 75% move speed boost for that attack.

feat(balance): Rapid strike rebalance

---

data/json/items/melee/spears_and_polearms.json
data/json/recipes/other/tools.json
data/json/recipes/weapon/bashing.json

This makes it possible to disassemble various primitive tools and weapons, as well as buffs the pipe spear to have the same to-hit bonus as the wooden spear; every single item that is now uncraftable has a very simple assembly method, while the pipe spear is basically the same as a wooden spear but made of metal.
Numerous tools (especially stone ones) weren't uncraftable despite being rocks (or in one case, a hunk of metal) literally tied to a stick. Furthermore, the pipe spear (and by extension, the sharpened rebar) had a -1 to hit despite being functionally just a wooden spear made of metal.
The stone hammer, makeshift hammer, stone shovel, stone knife, stone axe, stone adze, crude lockpick, cestus, quarterstaff, and peasant flail can now all be disassembled. The pipe spear now has a +1 …

feat(balance): primitive tool/weapon diassembly, pipe spear buff

---

data/json/recipes/armor/torso.json

Fixes #4526
1. Lower skill level but leaves auto learn at same level, so it isn't the go to grind recipe to get tailoring up
2. Raise the amount of rags needed quite a lot.

fix: fix wedding dress craft requirements

---

src/vehicle_autodrive.cpp

Made autodrive's maximum speed average out at around 40 MPH or 65 KPH, something that's not too fast to suddenly stop in most cases but that's far faster than before.
Autodrive in BN was horrible, it had a maximum speed of 12 MPH.
Autodrive now has a maximum speed of roughly 40 MPH or 65 KPH, a simple tweak in the vehicle_autodrive.cpp file. It's fast enough to be a reasonable rate of travel without being so fast that it breaks the autosteering.
The speed is fairly good _on roads and water,_ but for whatever reason it immediately slows down to a crawl on dirt or in the air no matter what wheels you're using, constantly jumping in speed between the max and the min. I would _welcome_ help on how to fix that, since this is my first foray into C++, but for now the change is fairly good for …

feat(balance): Autodrive faster

---

data/json/items/armor/undergarment.json

The camisole was, despite being a frilly and fancy garment IRL, not considered fancy.
The camisole item now counts as fancy.

feat(balance): Made camisole fancy

---

data/json/itemgroups/Locations_MapExtras/locations.json
data/json/itemgroups/Locations_MapExtras/locations_commercial.json
data/json/items/tool/musical_instruments.json
data/json/recipes/other/tools.json

Added a wooden equivalent of the bone flute, since wood flutes... you know, are a thing.
The bone flute was a good earlygame musical instrument, but _bone_ flutes are _not_ the most common type- wooden ones are.
Added in a wooden flute, crafting recipes, and appropriate spawns.

feat(content): Added wooden flute

---

data/json/weather_type.json

Building on top of @chaosvolt PR #4515 .
Weather got better but was not quite right, it stayed cloudless a lot of times, so I digged the file and used the "either" rule for baro and hydro not "and". The weather now is a lot more likely to change to cloudy, and so changing to rainy. Same with sunny, it was rare, so it also got the "either" treatment.
Light drizzle is a rain type, so instead of light drizzle, it will flurry.
1. Sunny and cloudy get "either" not "and" for baro and hydro.
2. Values got changed, so it is not always cloudy or sunny.
3. Renamed "Clear" to "Fair"
Works fine. It will probably need some more fine tuning in the future. (Less cloudy or less rainy, or even the opposite)

feat(content): more clouds, changes to weather behavior

---

data/json/recipes/weapon/ranged.json

My PR to reimplement pneumatic weapons missed the coilgun's recipe somehow.
When I PR'ed pneumatic weapons back into the basegame, I somehow missed the recipe for the coilgun.
Added the recipe for the coilgun.

feat(content): Added in coilgun recipe

---

data/json/items/magazine/nail.json
data/json/recipes/ammo/other.json

The nail rifle magazine wasn't actually a magazine thanks to a screwup on my part. Flechettes also took 3 hours to craft 100, way too long compared to the 1 hour for the same amount of nalis.
The nail rifle magazine is now restored to its original glory. Flechettes now are as quick to craft as nails.

fix(content): Nailrifle mag fix, flechette crafting time balance

---

data/json/requirements/cooking_tools.json
data/mods/Aftershock/recipes/requirements.json

For some reason the list of tools required to boil something is different from the list of tools required to cook something, but they both use an open flame, so the thermoblade fits there too.
When I added the thermoblade a few weeks ago, I added it to the cooking requirements, but I didn't realize that boiling requirements were a thing too and didn't add it to that.
If fire can be used to boil something, so can a thermoblade. Now the thermoblade is added to the "water_boiling_heat" requirement list.

fix: Thermoblade can boil water

---

src/weather.cpp

Solar panel CBMs are a lot less useful now that the weather is more cloudy and rainy. This change makes it so that cloudy weather will still let you charge solar.
Chaosvolt's recent change to make cloudy weather more common has rendered the solar panel CBM far less useful, as it can't currently recharge in cloudy weather.
The C++ field "is_in_sunlight" seems to be defined separately for mutations and solar panels, so I edited the latter to require only light sunlight instead of normal to allow solar panel CBMs to work in cloudy weather, but not storms or darkness.

feat(balance): Lowered sun intensity for is_in_sunlight

---

data/json/weather_type.json

This is a tweaking PR to make cloudy a bit less frequent. Rain isn't affected. Fair weather should happen bit more often.

fix(balance): make it a bit less cloudy

---

data/json/recipes/other/vehicles.json

The recipe was in the electric parts recipe category for some reason. #2811 introduced this item.

fix: homemade gyrocopter recipe correction

---

data/json/uncraft/generic.json

Smart watch now gives an ultra-light battery when uncrafted.
The regular wristwatch gives an ultra-light battery when uncrafted, but the smartwatch, which has 120 UPS power capacity, gives zero.
The smart watch now gives two ultra-light batteries when uncrafted.

feat(balance): Smart watch now gives 2 ultra-light batteries on uncraft

---

data/json/recipes/armor/feet.json
data/json/recipes/armor/hands.json
data/json/recipes/armor/head.json
data/json/recipes/armor/suit.json

Thermal gear took a long, long time to make, especially for the relatively simple parts like gloves and socks, and this made the uncraft time also unbearably long. So now they take a lot less time to make.
Thermal gear took a very long time to produce (and thus to uncraft), making its usefulness limited compared to other, less costly warm clothing such as wool socks, or even just a union suit.
The crafting time of most pieces of thermal clothing have been reduced.

feat(balance): Thermal gear crafting time buff

---

data/json/weather_type.json

Another weather tweak.
1. Light drizzle is less common 
2. Drizzle is more common 
3. Rain is a lot more common 
4. Clouds are less common 
5. Sunshine is more common 
6. Snowstorms are more common 
7. New weather: heavy rain: more common than thunderstorms, same heavy precipitation

fix(content): less light drizzle, more regular rain, added heavy rain

---

data/json/regional_map_settings.json
data/json/weather_type.json

Heavy rain didn't spawn do to an oversight. Now it does, so does the new weather "light snowfall".
Add heavy rain and light snowfall into the "spawn list".
Add light snowfall, the snowy counterpart of light drizzle.
Both are lacking tiles on the overlap weather report, so it looks "not nice". I am not able to make those tiles. (Lack of PC and lack of knowledge). So if anyone can do it, please do.

feat(content): heavy rain fix and light snowfall addition

---

data/json/items/comestibles/drink_other.json

Mayo, ketchup and mustard were auto eaten without any big impact on morale. I don't know who loves to drink pure mustard, but the majority probably doesn't.
Lower fun to -6 - -8
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167661460/b02e5e63-fa77-4c7b-b53d-3fe15821d450

feat(balance): mayonnaise, ketchup and mustard are less fun to drink

---

data/json/items/comestibles/egg.json
data/json/items/comestibles/meat_dishes.json
data/json/recipes/food/meat.json
data/json/recipes/food/other.json
data/json/requirements/cooking_components.json

Condiments were underutilized. I added 2 recipes that uses them. For cooked sausage and boiled eggs. Also corrections in the food requirements. Boiled eggs got a small correction.
1. New condiment requirement 
2. Sausage amounts for recipes are now around 0,25 l.
3. Condiment recipes for boiled eggs and sausages 
4. Boiled eggs now spoil after 10 days instead of 2 days.
5. New recipes have different names depending on what condiment you use.

feat(content): add 2 recipes using condiments and tweaks

---

data/json/weather_type.json

This should be one of the final tweaks from me for the weather. It looks very good now.
1. A bit more cloudy
2. A bit more sunny
3. A bit more light drizzle 
4. Sunny requires clear (fair) weather

feat(balance): more weather tweaks

---

data/json/furniture_and_terrain/furniture-appliances.json
data/json/furniture_and_terrain/furniture-sleep.json

First look like for retrodays users. Mattress look like and ground lamp look like.

fix(content): look_like for retrodays part1

---

data/json/recipes/other/tools.json

The wooden dog whistle is a typical grind recipe. It takes no effort to make it and requires fab 4 to make.
1. Reduce fabrication to 2 to fit to other recipes in its category 
2. Instead of fine cutting, drilling is needed

feat(balance): make dog whistle easier to craft

---

data/json/items/armor/suits_protection.json
data/json/recipes/armor/suit.json

The light survivor suit is decent for what it is, but a superalloy variant would make sense, given there's one of the heavy version.
Added lightweight superalloy survivor suit, an electrically conductive but more protective version of the lightweight survivor suit.

feat(content): lightweight superalloy survivor suit

---

data/json/recipes/other/materials.json

For small metal sheets a hacksaw or similar was needed to make small metal sheets to scrap metal. Since it has the perfect size of being as big as one chunk of metal, a recipe to make those chunks using a simple hammer.
Creating a ineffective recipe. Using the hacksaw is a lot more effective.

feat(content): new ineffective recipe to make chunks of steel using a hammer

---

data/json/items/comestibles/other.json
data/json/items/comestibles/spice.json

Thyme wild herbs, and wax were auto-eaten despite having a penalty to fun and having little nutrition.
Thyme, wild herbs, and wax now have a -15 to fun, stopping them from being auto-eaten.

feat(balance): Thyme, Wild Herbs, Wax Now -15 Fun

---

data/json/furniture_and_terrain/furniture-appliances.json

Instead of the stationary look of the windmill, I changed it to the rotating version.
Done on my galaxy 21 FE. And it is much more stupid than with my galaxy 9, due to restrictions on android data file changes...
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/2efce74b-b9b2-424b-acb1-8014288e1c4b

feat(content): wind turbine rotate in undead tileset now

---

data/json/items/comestibles/carnivore.json

Easy typo fixes, fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4622
Updated the descriptions of cooked and seasoned scraps of meat to not refer to mutant meat, since they're made of normal meat.
screm
Checked that I did in fact update the descriptions for `meat_scrap_cooked` and `meat_scrap_cooked_seasoned`.

fix: correct descriptions for cooked scraps of meat

---

data/json/overmap/overmap_terrain/overmap_terrain.json

Radio towers that contains wasps can only be seen on tile maps. Those who use the old maps can't determine if it is a wasp tower or not. Also I give it its own name, for those with color problems.

fix(content): give wasp radio towers unique name and symbol on maps

---

data/json/items/comestibles/other.json
data/json/recipes/food/other.json

Dog and Catfood used an very old recipe, with a super limited amount of ingredients. Now you can make them with a whole lot more. Yes, too much sodium is not good for your pets either!

feat(content): dog and cat food can be made out of a lot more ingredients

---

src/iuse.cpp

Change from rarer used m/s for metric wind speeds to more used km/h. Also code got a bit more compact, so did the text.

feat(content): km/h for Windmeter (metric) and more compact text.

---

data/json/mutations/mutations.json

Fixes #3667: Non-threshold mutation Genetic Chaos being unpurifiable. 
Genetic Chaos has two pre-requisites: Metallassomaiphile (post-threshold) and Genetically Unstable (pre-threshold) and allows acquiring Genetic Chaos without having both at the same time. Genetic Chaos itself isn't a post-threshold mutation but has the unpurifiable flag.
Removed _purifiable: false_ from Genetically Chaos in Mutations.json.
Making it a post-threshold mutation or making both its pre-requisites post-threshold.
1.Generated a character.
2.Granted Genetically Chaos via DEBUG.
3.Used a Purifier Smart Shot. Was able to target and purify Genetically Chaos.

fix: non-threshold mutation Genetically Unstable purifiable

---

data/json/itemgroups/Locations_MapExtras/locations.json
data/json/mapgen/hospital.json

Increased chance of finding common bionics in hospitals.
Hospitals were previously extremely risky places to go, with many glass doors and walls and many zombies but not much in the way of good loot.
This PR makes hospitals now have a good chance to have civilian-grade cybernetics, making them much more worthwhile to raid.

feat(balance): Hospital Bionics Chances

---

src/panels.cpp

- resolve BN issue https://github.com/cataclysmbnteam/Cataclysm-BN/issues/448
- port dda pr https://github.com/CleverRaven/Cataclysm-DDA/pull/45407

feat(UI,port): Bigger minimap

---

data/json/regional_map_settings.json
data/json/weather_type.json

Another small weather tweak. Summer gets a bit more humid. Not as much as before, but you can get your occasional light drizzle or drizzle.

feat(balance): more sun, less clouds, bit more humidity in summer

---

src/vehicle_autodrive.cpp

#4535 while good intent lead to bad driving behavior, mostly a lot of slow downs.
After a few tests, I got the optimal settings for non crash, best speed and fuel economy, even with driving 0 characters and a big vehicle.
```
static constexpr int MIN_SPEED_TPS = 2;
static constexpr int MAX_SPEED_TPS = 5;
```
raising the minimum speed to 2 (12 km/h instead of 6), but halving the top speed.
I used a armored vehicle.
For this path, to and back
1 - 10
2 - 5

fix(content): auto drive speed fix

---

data/json/requirements/cooking_components.json

while cattail stalks themselves could be used in a lot recipes, the cooked version cannot. This adds the cooked version into the requirement-group of cooked veggies.

fix(content): cooked cattail stalks usable in more recipes

---

src/vehicle_autodrive.cpp

After some testing, I found a solution to the auto-drive hiccups, it seems it tries to lower its speed back to min-speed after reaching a node "too fast". By removing the "needs minimum speed at new node" it will keep constant speeds.
Reverts #4677 .
Removing the part of the code bugging it.
Old settings
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/a7d79b3e-63bd-40d2-9cd0-74069b36652c
New settings
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/78231776-f2eb-4e98-abc0-0b3d16cb9c32

fix: auto-drive speed hiccups

---

src/options.cpp
src/vehicle_autodrive.cpp

Adds the option to change the minimum and maximum speed for auto-drive in the options. Slower speeds are good for fuel economy, faster ones for speedy changes in position.
Add a option in the option menu.

feat(content): minumum and maximum auto-drive speed option

---

src/vehicle_autodrive.cpp

This change will make auto-drive a bit safer. It lowers the speed which are needed to turn the steering wheel leading to better reaction to different obstacles.
Lowering the move cost to 0. raise the "space needed on the sides" for either braking or canceling auto-drive.
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/089b5b97-17ad-419b-93f5-1617540cdae7

fix: less crashing while auto-driving, smoother driving style

---

data/json/uncraft/generic.json

Allows recovery of material from some glass items which couldn't be disassembled.
Stuck to items which couldn't be used in recipes.
Modified data/json/uncraft/generic.json to add beaker, crack pipe, graduated cylinder, small glass tube and wine glass.
Two items weren't included.
The "glass prism" which is obtained only by disassembling a spectrophotometer, because I'm not certain if it should be made disassemble-able or replaced by a more generic item.
And "sheet of tempered glass" since I can't seem to find the file with the others sheets of glass
disassembly.
1. Made a backup of data/json/uncraft/generic.json.
2. Replaced old file with modified version.
3. Loaded into a world and opened the debug menu to spawn items.
4. Verified that the uncrafts were added.

feat: add some glass uncrafts

---

data/json/weather_type.json

small weather tweak. Sun should occur more frequently, clouds just a bit less. More of "fair" weather will be sunny.

fix(content): bit less clouds, more sun

---

data/json/items/vehicle/wheel.json
data/json/recipes/other/vehicles.json
data/json/vehicleparts/wheel.json

Wooden bicycles were some of the first bicycles ever made, and yet we have no wooden wheel mount equivalent.
Added light wooden wheel mount, a wood variation of the light wheel mount.

feat(content): light wooden wheel mount

---

data/json/items/tool/workshop.json
data/json/recipes/other/tools.json

Made the misc repair kit able to be made with any number of civilian-grade knives with fine cutting.
The misc repair kit wasn't craftable innawoods, nor was it too easily craftable otherwise; it needed an xacto knife, which are relatively uncommon.
The misc repair kit can now be crafted using any tool knife with fine cutting, not including scalpels.

feat(balance): Misc Repair Kit Knives

---

data/json/items/ranged/crossbows.json

Adds straps to crossbows
adds the `[ "sling", 1 ]` line to the following items
- `"crossbow"`
- `"compcrossbow"`
- `"huge_crossbow"`
- `"rep_crossbow"`
adding the line to `"xbow_base"`, but this might affect smaller hand-held crossbows
👍 
suggested from /rlg/

feat(content): add straps to crossbows

---

data/json/items/generic.json
data/json/items/tool/misc.json

Kevlar plates weren't like rags or leather patches. They were buried in a different file than all clothing related materials and also wasn't stackable.
i

fix: kevlar plate

---

data/json/items/comestibles/drink.json
data/json/items/comestibles/med.json
src/iuse.cpp

SLEEP use_action had a hardcoded amount of fatigue. That is not necessary, since it is fully jsonized. I gave different tiredness levels for chamomile tea, Zolpidem and poppy sleeping powder.
1. remove the fixed fatigue modification from the use_action sleep
2. remove the positive stem and fatigue mod of chamomile tea and give it the lowest amount of fatigue.
3. the message says it makes you sleepy, not "very sleepy"
Remove the use_action all together, since it only posts a message now.
got sleepy.

fix: use_action "SLEEP" and chamomile tea.

---

data/json/recipes/food/dry.json
data/json/requirements/cooking_components.json
tests/iteminfo_test.cpp

Powdered milk could only be made out of regular milk, UHD milk, evaporated, condensed milk couldn't be used.
Also evaporated milk wasn't use in ANY recipe. This gives it more reasons to use.

feat(content): more ways to use evaporated milk and more powdered milk components

---

data/json/items/generic.json
data/json/items/resources/metal.json
data/json/items/resources/wood.json

Sticks, pipes and straw can be carried easily on your arms/hands. This represents the possibility to wield a larger amount of those. Same way planks are stackable.

feat(content): make sticks, straw and pipes stackable

---

data/json/items/melee/bludgeons.json
data/json/recipes/weapon/bashing.json

Chaosvolt mentioned the idea of an extendable quarterstaff and it seemed like a fun idea to design.
Added the extendable quarterstaff, a lighter and more portable but less sturdy version of the ironshod quarterstaff.

feat(content): extendable quarterstaff

---

data/json/items/tool/workshop.json
data/json/recipes/other/materials.json
data/json/uncraft/generic.json

Recently made more ceramic items disassemble-able however there weren't many crafting recipes which use ceramic shards. This PR adds the ability to turn ceramic shards into lumps of clay, increasing its usefulness.
Added a recipe mostly based on the video https://www.youtube.com/watch?v=sHStLmaJADM albeit simplified to make it doable with Innawood setting. Used the items "pallet of wet adobe bricks" and "pallet of dry adobe bricks" as models since the drying time seemed appropriate for  recycling ceramic shards.
Make ceramic shard a component of more recipes. Except all recipes which uses sharp rock already accepts ceramic shard.
Replaced game files with the modified versions.
Loaded into a world and spawned all concerned items.
Noticed the recipe doesn't show up in the two books it was …

feat(content): recycle ceramic shards by turning it into lumps of clay

---

data/json/mapgen/house/2storymodern02.json

Fix the roof of 2storyModern02.
Fix the roof.
none
Before:
After:

fix: an error on the roof of 2storyModern02

---

data/json/recipes/food/veggi.json

Jam by itself is a very simple recipe. It has no right to be (in its original form) not autolearn. It has no special "abilities" that would make it imbalanced. So that's why it should be autolearn by default, I set it to lvl 3 for the lvl 2 recipe.

feat(balance): make jam autolearn

---

data/json/itemgroups/Food/food.json

Tin canned stuff wasn't spanwing as it should be, there were some things (like bone broth or permeni) only spawning in private resorts, homeless camps and aircraft carriers... This makes it spawn also in other places that makes sense.
Field tested and seems to be alright.

feat(content): make some tin canned stuff actually spawn more often

---

data/json/itemgroups/Food/food.json
data/json/itemgroups/collections_domestic.json

Peptone broth can be used for making broth. While spawning, but rarely at home, a lot of people use it to actually make broth. This makes the spawn much more common.

feat(content): make peptone broth spawn much more in houses.

---

src/activity_handlers.cpp

This is a set of follow-up fixes and additions to butchery, following from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4727
1. In activity_handlers.cpp, reworked how `butchery_drops_harvest` zeroes out the yields from field-dressed, skinned, and bled corpses via defining a bool that tracks all three potential instances. Replaces the separate "zero out yield of X if Y flag" checks with a single check for the new bool.
2. Setting the above function to properly zero out offal yields for any field dressed corpse also in turn fixes an exploit where you could duplicate stomachs by field dressing then dissecting a corpse.
3. Also added a check that makes 100% certain that only bleeding a corpse will actually produce blood as an item.
4. Set the "you failed to harvest X" message to not …

fix: follow-up fixes to butchery yields and messages

---

data/json/itemgroups/Clothing_Gear/clothing.json
data/json/itemgroups/Weapons_Mods_Ammo/magazines.json
data/json/itemgroups/collections_domestic.json

Spawns guns, magazines and ammo in regular houses. Until now, only a very very slim chance of a gun spawn was available in a night stand. But in that night stand you could find AK74s, elephant guns, and Saigas (not anymore).
1. Add spawns of guns (pistols>smg=shotguns>rifles) to living rooms and bedrooms.
2. Add spawns of ammo (pistols>smg=shotguns>rifles) to kitchens, living rooms and bedrooms.
3. Add spawns of magazines (pistols>smg=shotguns>rifles) to living rooms and bedrooms.
4. nightstands spawn pistols their ammo or their magazines.
5. drawers spawn pistols their ammo or their magazines.
It may need some tweaking in the future, but for now it should fit.
in 100 spawns one gun was spawned, 2 magazines and one batch of ammo.

feat(content): spawn guns, magazines and ammo rarely in houses

---

.github/pull_request_template.md

Adding a section about checking your emails to the PR template, also adding a new checklist as per suggestions from Scarf.
It's a few new lines in the PR template file, truly arcane knowledge. Check the changed lines.
Letting someone else do it.
Unnecessary in this instance.
N/A

docs: update PR template with useful information

---

data/json/recipes/weapon/ranged.json

This fixes a copypaste blunder I made in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2829 that I completely failed to notice for basically over a year until someone on the subreddit pointed it out.
Corrected the other mech laser recipe to use the recon mech's laser instead of using the gatling laser a second time.
screm
2. Load-tested and checked all recipes, it's there now.
Reddit thread: https://www.reddit.com/r/cataclysmbn/comments/1dexlm3/rebuilt_rmes_laser/

fix: rebuilt recon laser recipe no longer overrides gatling laser recipe

---

data/json/recipes/other/other.json

Allow more ingredients to bait fish. Or rather to make fish bait.

feat(content): allow more ingredients for fish bait

---

data/json/mapgen/house/bungalow28.json
data/json/mapgen_palettes/house_general_palette.json
data/mods/No_Hope/palettes.json

expanding standard house palette. there are multiple houses that use the table_foyer item group, and this will save on lines of code.
added table spawn with "table_foyer" item group to house palette, also to no hope because that was a problem last time. Also changed bungalow 28 to reflect this change.
leaving it as is
changed bungalow 28, and it spawns as it should

feat(content): house palette addition

---

data/json/mapgen/house/2Story01.json

Adding residential spawn chunks for yard, roof, personal items to increase variety. General tidying of file, fixing errors.
Added the nested chunks for ground and roof, added residential items on 2nd floor.
linted and spawned all variants in game.
Ground variant 1
- replaced foyer table entry with palette symbol
- removed hardcoded symbos, added frontyard nested chunk
Ground variant 2
- replaced foyer table with palette symbol
2nd floor - variant 1, 2 and 3
- added res_personal_item palette symbol to closet
- fixed bad terrain flooring for closet rack from null to waxed floor. No longer spawns with linoleum flooring in closet
Roof
-removed hardcoded solar panels, added roof solar chunk
-added residential roof spawn chunk

feat(content): House Nested Chunk Addition, Cleanup:  2Story01

---

data/json/mapgen/house/2Story02.json

add residential nested chunk spawns for variety, cleanup house entry.
Added front yard, roof and personal item nested chunks, replaced some item spawn entries for palette symbols.
linted and spawned all variants in game.
Basement - variant 1
-replaced table foyer with palette symbol
Basement - variant 2
-removed guitar and amp in spare room, added res_personal item palette symbol
Ground - variant 1
-replaced table foyer with palette symbol
-removed trees and birdbath from front lawn added front yard nested chunk
Ground - variant 2
-replaced table foyer with palette symbol
Second - variant 1
-replaced table foyer with palette symbol
-removed clothes rack and added res_personal item palette symbol to one of the bedrooms
Second - variant 2
-replaced table foyer with palette symbol
-replaced …

feat(content): House Nested Chunk Addition, Cleanup: 2Story02

---

data/raw/keybindings/keybindings.json
src/inventory_ui.cpp

There would be times when I would first want to see the description on things I would drop before dropping them. There are also times when I want to quickly look at the description of an item from some of the inventory UI. This adds that.
- Add a keybinding for `EXAMINE` under the `INVENTORY` category.
- Add a handler to the keybinding where it would create a window showing the item data highlighted.

feat(content): Add an examine button on the inventory UI

---

data/json/itemgroups/Weapons_Mods_Ammo/guns.json

Mac 10 and Mac 11 were in the rare category, together with the HK5SD and the TDI, they spawn now more regular, but even rarer than a tommygun

feat(content): mac10 and mac 11 are not as rare as a TDI

---

data/json/itemgroups/Locations_MapExtras/mansion.json
data/json/itemgroups/Weapons_Mods_Ammo/guns.json
data/json/mapgen/basement/basement_guns.json
data/json/mapgen/farm_dairy.json
data/json/mapgen/house/2Story01.json
data/json/mapgen/house/bungalow16.json
data/json/mapgen/isherwood_farms/dairy_farm_isherwood.json
data/json/mapgen/police_station.json
data/json/mapgen/shooting_range.json
data/json/mapgen_palettes/house_general_palette.json
data/json/mapgen_palettes/house_w_palette.json
data/json/mapgen_palettes/mall_palette.json

gun safes were in a very sorry state, thanks to the help of Discord user CrystalNole, I got notified of the problem.
Until now, a lot of gun safes were empty, spawned junk (like a map and only a map) and rarely a common pistol.
make a spawn itemgroup for the safes and their guns (we are now working a lot with those itemgroups, aren't we @chaosvolt)
what can be expected:
100% one gun is spawned.
39.5% two guns are spawned.
5.25% three guns are spawned.
When a gun is spawned chances are:
19,6% for a common pistol
3,9% for a rare pistol
2% for a obscure pistol
7,8% for a common SMG
0,8% for a rare SMG
0,4% for a obscure SMG
29,4% for a common shotgun
3,9% for a rare shotgun
0,4% for a obscure shotgun
29,4% for a common rifle
2% for a rare rifle
0,4% for a obscure rifle
Also: 
50% a common …

feat(content): let gun safes spawn actual gun loot

---

data/json/recipes/food/drinks.json
data/json/recipes/food/other.json
data/json/requirements/cooking_components.json
tests/iteminfo_test.cpp

Until now only regular cow milk could be used, now, also soy and almond milk are possible substitutes.

feat(content): allow almond and soy milk to be used for coffee/tea milk and milkshake

---

data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json
data/json/itemgroups/Weapons_Mods_Ammo/guns.json
data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json
data/json/itemgroups/Weapons_Mods_Ammo/nested_magazines.json
data/json/items/gun/10mm.json
data/json/items/magazine/10mm.json
data/mods/Generic_Guns/firearms/gg_firearms_migration.json

Adds the Glock 20 into the game. This is the first dedicated 10 mm gun, while we have a SW revolver that can use 10 mm, we don't have a 10 mm pistol.
Port just a few info from DDA, most work is done by me. I checked for the creator of the Glock 20, but I couldn't find it anywhere.
1. Add gun with some info from DDA to BN.
2. Add 3 types of magazines possible to be bought (15, 30, 100)
3. Spawn the gun in nested groups, together with magazines.
4. placed it in the common group, since it is not too rare, to be rare.
make 10 mm a common ammo, since it is in the rare category, finding 10 mm will not be that easy.

feat(content): add glock 20

---

data/json/furniture_and_terrain/terrain-railroads.json

Easy smol thing I could've sworn was allowed.
1. Set gravel to have a deconstruct entry, returning exactly the amount of pebbles needed to construct it.
2. Also set both bash and deconstruct to return as dirt.
1. Making the construction entry for gravel require diggable terrain, to prevent exploits that could turn underground rock into dirt.
2. Adding an underground version that reverts to rock floor when deconstructed.
2. Ported JSON change to playthrough build, confirmed that deconstructing it works and yields 100 pebbles.

feat: allow deconstructing gravel

---

data/json/mapgen/house/bungalow04.json
data/json/mapgen/house/bungalow05.json
data/json/mapgen/house/bungalow06.json

make house spawns more dynamic and other wise cleaning up files: 
bungalow 04, bungalow 05, bungalow 06
added house nested chunks incl roof, front and backyard, added furniture palette symbols, cleaned up
bungalow 04
- removed furniture items from backyard, added front and back yard nested chunks
- used tree palette symbol
- replaced indoor plants with diff symbol to avoid using palette symbol for flowers
- used palette symbol for flower spawns
- revamped kitchen layout
- replaced bedside furniture with nightstand palette symbol
- add res_personal_items
- added roof nested chunks
bungalow 05
- removed hardcoded lawn furniture, added back and front yard chunks
-  added roof chunks
- added table foyer palette symbol
- add res_personal_items
bungalow 06
- added …

feat(content): add house nested chunks and cleanup: bungalows 04, 05, 06

---

data/json/recipes/other/materials.json

Fixes a copypaste error in the recipe for razor blades.
Remove needing an absolute whole-ass entire broadsword from razor blade recipe.
We really should make the recipe for normal blades less silly and find a proper makeshift option for blades.
AAAAAAAAAAA

fix: razor blades aren't made out of entire broadswords

---

data/json/mapgen/house/bungalow10.json
data/json/mapgen/house/bungalow11.json
data/json/mapgen/house/bungalow12.json

Making house spawns more dynamic and cleaning up files: bungalow 10, bungalow 11, bungalow 12
add house nested chunks for roofs, front yard; replace furniture entries with palette symbols, otherwise clean up files.
linted and tested in game
Bungalow 10
- add front yard nested chunks
- add roof nested chunks
- added res_personal items palette symbol
Bungalow 11
- removed window from behind fridge in kitchen
-  removed bushes from front yard left, added fy chunk
- add roof nested chunks
- added table foyer symbol
Bungalow 12
- added roof chunks
- added res_personal items palette symbol

feat(content): House Nested Chunk Addition, Cleanup:  bungalow 10, 11, 12

---

data/json/mapgen/house/bungalow16.json
data/json/mapgen/house/bungalow17.json
data/json/mapgen/house/bungalow18.json

make house spawns more dynamic, cleanup files by removing redundant entries and using palette symbols: bungalow 16, bungalow 17, bungalow 18
add house nested chunks for backyard, front yard, roof; replace furniture entries with palette symbols; otherwise clean up redundant entries and make sure file is looking good
bungalow 16
- add backyard, frontyard chunks
- add roof chunks
- add res_personal item palette symbol
- removed furniture entries, add table_foyer palette symbol
bungalow 17
- moved front yard furniture, added front yard chunk
- moved ladder spawn to back of house
- added roof chunks
- add res_personal item palette symbol
bungalow 18
- add frontyard chunks
- add roof chunks
- add res_personal item palette symbol

feat(content): House Nested Chunk Addition, Cleanup: bungalows 16, 17, 18

---

data/json/mapgen/house/bungalow19.json
data/json/mapgen/house/bungalow20.json
data/json/mapgen/house/bungalow21.json

make house spawns more dynamic, clean up file for : bungalow 19, bungalow 20, bungalow 21
Adding nested chunk spawns for houses, including front yard, backyard, roof solar, roof item; remove furniture entries and replace with palette symbols where appropriate; clean up house spawn errors, and generally clean up the file
bungalow 19
- add backyard chunk
-  add roof solar and item chunks
- replace furniture entry with table_foyer palette symbol
- add res_personal_item spawn in bedroom
bungalow 20
- add backyard chunk
-  add roof solar and item chunks
- replace furniture entry with table_foyer palette symbol
- add res_personal_item spawn in bedroom
backyard 21
- removed furniture on side of house, replaced with backyard and front yard chunks
- added roof solar and …

feat(content): House Nested Chunk Addition, Cleanup:  bungalows 19, 20, 21

---

data/json/items/armor/suits_protection.json

Some smol easy followup thoughts that came to mind for https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4868
1. Added `ONLY_ONE` flag to all three exos.
2. Added `POWERARMOR_COMPATABLE` flag to specifically the industrial and military version.
Remembering it earlier.

feat(balance): add `ONLY_ONE` to exo-suits, `POWERARMOR_COMPATABLE` to military and industrial versions

---

data/json/items/toolmod.json

Minor thing that came to mind when I remembered https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3877
Set it so that the battery compartment toolmod can accept medium storage batteries, which are at present the same volume as the already-permitted car battery. Also tweaks item description a bit to better explain that the size of a car battery (i.e. 10 liters) is the cutoff point for it, hence not allowing bigger storage batteries.
screm

feat(balance): allow medium storage batteries with battery compartment toolmod

---

data/json/uncraft/cbm/cbm.json

During gameplay I noticed that the uncraft components for the shock absorber CBM was visibly that of the EMP armgun.
Gave the shock absorber the correct items on uncraft.
screm

fix: kinetic shock absorber uses correct uncraft

---

data/json/mapgen/nested/residential_personal_items.json

expand the available chunks to spawn in the res_personal_items nested chunk spawn called in houses. add a bit more character to the houses in the form of personal items that might be found in a person's bedroom or closet.
add more chunk variants and add to nested container that typically spawns in some houses. 6 new entries
acoustic guitar
ergometer
photo albums and other sentimental items
comic collection
bowhunter - compound bow, assorted hunting items
bodypillows

feat(content): add new entries for res_personal_items nested chunk

---

data/json/techniques.json

Most speed-boosting techniques were corrected to not reduce damage a while back, but the kickboxing jab technique was apparently passed over.
The kickboxing jab technique now does not reduce damage dealt in exchange for nerfed movecost.

feat(balance): Kickboxing Jab Correction

---

data/json/items/gunmod/laser_gunmods.json

Most laser weapon mods are extremely terrible, with penalties that outweigh the benefits.
Rebalanced the beam scatterer to reduce range by 10 instead of 20; the electrolaser conversion to work on any laser weapon, reduce damage by 5 instead of 8, and reduce range by 20 instead of 25 in exchange for multiplying power draw by 1.4 instead of 1.2; and the high density emitter's power drain boost has been reduced from 2x to 1.5x.

feat(balance): Laser mod buff

---

data/json/mapgen/cathedral.json
data/json/mapgen/radio_tower.json

Snipers were too commonly spawned on top of radio towers, it didn't give a good reason for having those there. So regular non hostile towers now spawn snipers less, but have variation.
Lower spawn chance for snipers and map spawns. Use groups for weapons spawns

feat(balance): lower sniper spawn on regular radio towers slightly, spawn more different guns

---

data/json/items/armor/suits_protection.json

The new exo-suits were missing a line of json marking which ammo type they used, making them unable to charge from anything but a UPS.
The exo-suits and survivor power armor now have the battery ammo type, letting them charge from recharging stations and battery chargers.

fix: Add ammo type to exo-suits

---

data/json/items/armor/holster.json

Bow slings were good at saving encumbrance for all bows except the composite greatbow, because 6L of a bow was too much bow for the sling to store (max 5L), so my char had to suffer wearing the composite greatbow for an additional 30(!!!) encumbrance on the torso. 
Doubles the effective max storage volume of the bow sling to match the back holster for guns at 10L, so there's room if you want to add all your mods to the bows.
Smaller bows? No, it must the slings who are wrong.

feat(content): Increased bow sling storage size

---

data/json/mapgen/nested/residential_personal_items.json

increasing variety in personal item nested chunks that spawn in house bedrooms and closets
add 12 more res_personal_items nested chunk variants, bringing the total up to 32 different variants.
bugout box
hat collection
saxophone
tinkerer - box of electronics parts
work gear - construction
box of random donations
camping gear
golf clubs
Desk - Stoner's stash
football gear
baseball gear
rollerskates and protective gear

feat(content): yet more res_personal_items Nested Chunks

---

data/json/harvest.json

I noticed I got a faulty yet sterile bionic from a feral human, and realized we were using the wrong fault for them.
Replaced all cases of the obsoleted "reset to factory specs" fault in harvest.json with the non-sterile fault it's supposed to use, likely introduced when feral scientists were ported over.
screm
Learned to read, confirmed `fault_bionic_salvaged` was not present in the file. :V

fix: bionics from feral humans use correct fault

---

data/json/requirements/electronics.json

@Lamandus pointed out a thing they forgot to add.
Added ethanol soldering iron as an option in `add_grid_connection`
Converting it to internally use `soldering_standard`, which would've made this never be a problem in the first place in exchange for grid hookups also requiring solder.

fix: alcohol soldering iron can now be used for expanding grids

---

src/npcmove.cpp

This fixes cases where NPCs will waste shots on targets their gun literally lacks the range to hit.
Set `npc::method_of_attack` so that target distance being within their gun's max range is required before they commit to firing, so they won't repeatedly waste shots on targets they've dialed in on that their gun lacks the oomph to actually touch. Set here instead of `npc::confident_gun_mode_range` like I first considered doing, this way NPCs can still dial in and aim at targets outside their max range if they have the stats to try.
screm
2. Handed NPC a flintlock pistol loaded with paper shot cartridges, maxed their shooting stats.
3. Spawned in a zombie a decent distance away and turned on debug mode.
4. NPC no longer fires prematurely.

fix: NPCs hold fire if their target is out of max range

---

data/json/mapgen/nested/residential_lawn_nested.json

add variants to residential front and backyard nested containers
created 13 new variants and added to both front and backyard entries
native plant garden
lilac bushes
stray pet dog
discarded stepladder
deckchair and beer cans
abandoned shopping cart and supplies
bench w flowers
corpse
pile of lawn trimmings
Boulder
NPC
dirtpatch
fertilizer and bucket

feat(content): add new entries to residential lawn nested containers

---

data/json/items/generic/bathroom_house.json
data/json/items/generic/dining_kitchen.json
data/json/items/tool/woodworking.json

Some prices were off by an order of magnitude on some tools.
Changes here:
- Price down the shaving razor from $5 to $1.50. Razor blade ($1) was used to make shaving razor ($5), which was used to make makeshift shaving kit ($2.40). Pricing it to $1.50 puts it in between, keeping into account the other items you can make from the razor blade are around the same price (with the exception of scourge which is $52).
- Stone chisel post apocalyptic price brought to $0 as it is easy to make and was using the pre-apoc price ($16).
- Canning pot was $200, brought down to $20 which matched other tools that were able to preserve food like the vacuum sealer and can sealer.
Fixes #4936.
Spawned in items and tried to sell to shopkeeper
- Chisel no longer for sale when speaking to shopkeepers
- Canning …

feat(balance): decrease prices for stone chisel, canning pot, and shaving razor

---

data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json
data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json
data/json/itemgroups/Weapons_Mods_Ammo/nested_magazines.json
data/json/items/gun/9mm.json
data/json/monsterdrops/zombie_default.json

To raise the amount of variables in gun drops by zombies, I did some changes to spice stuff up.
Also some fixes for the new carbon rifle/pistol while I was at it.
If a zombie would drop a carried gun:
1. 10% chance of no magazine dropping (was 0%)
2. 25% chance of spare ammo dropping. Between 10 and 40 shots, up to 2 different ammo types. (Shotguns 10-30 shots, up to 3 different ammo types)
3. zombies won't drop ammo without any gun.
4. lowered drop rate to keep amount of dropped guns the same
5. fixes for the carbon pistol and rifle.
works as intended.

feat(balance): changes in carried gun, magazine and ammo drops

---

data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json

Forgot to add another small fix for the itemgroup of carbon guns. Added on hand ammo for the nested variant of both.

fix: add ammogroup to nested carbon guns

---

.github/workflows/documentation.yml

try fix docs action, part 2 of #4959 
[use proper args](https://github.com/withastro/action/tree/v2/)
test it locally but i need to get outside in 20 minutes
haven't

ci: fix docs deployment, attempt 2

---

.github/workflows/documentation.yml

attempt 3 of #4959, #4963
title

ci: bump  `actions/deploy-pages` to v4

---

data/json/furniture_and_terrain/furniture-appliances.json

The grid 3D printer did not have a use-action. It turned out to be missing the necessary line in the code to allow it to function like its fake item.
Added the proper line in the json to allow the grid 3D printer to be used for repairing.

fix(content): Grid 3D Printer Use Action

---

src/activity_handlers.cpp

Simple thing I looked into to fix mining boulders carving holes in the earth itself.
In activity_handlers.cpp, set `activity_handlers::pickaxe_finish` and `activity_handlers::jackhammer_finish` to check if the target position has bashable furniture on it first, and call `destroy_furn` instead if so, only calling `destroy` if no such thing is found.
screm
2. Spawned in a boulder and a pickaxe.
3. Mined it via activating, no more holes in the floor.
4. Went over and mined a pavement, it turns into a hole in the floor. This seems like some jank that may warrant a separate fix in the future.
5. Jackhammered a boulder, also correctly doesn't explode the floor.
6. Warped along and vaporized a rock wall with both, both behave as expected.

fix: mining a boulder no longer destroys the floor under it too

---

.github/workflows/matrix.yml

force run macos build on #4970
add `workflow_dispatch`

ci: add manual trigger to build matrix

---

data/json/itemgroups/Locations_MapExtras/locations.json
data/json/itemgroups/art_antiques_crafts.json
data/json/items/tool/cooking.json
data/json/recipes/other/tools.json

This aims to make distilling quality actually reasonably accessible innawoods, so that denatured alcohol isn't as much of a roadblock.
1. Added items for clay and copper retorts. Basically as simple and portable as the concept of an alembic or retort can reasonably get. 1 lower distillation quality than a still, but same boiling and containing qualities.
2. Added recipes for both items.
3. Added both to `antique` and `museum_misc`. Added clay version specifically to `pottery`, and copper version specifically to `moonshine_brew`.
1. Adding a bulky makeshift still using earthenware that condenses directly above the collector, like this sorta setup: https://www.youtube.com/watch?v=bNJl2_OgHmE
2. Adding glass alembics too, possibly most accessible by messing with an existing bottle instead of …

feat(content): add clay and copper retorts for craftable `DISTILL` quality 1

---

data/json/items/tool/workshop.json

Smol fix Kyara spotted in the BN discord.
Bronze hammer is now bronze/wood instead of steel/wood.
Screaming.
Used my eyes.

fix: bronze hammer actually made of bronze

---

data/mods/Aftershock/items/inactiverobot.json

The Executive started with two Sentinel 1-xs that were designated as pets. As such they could be renamed, carry bags, wear armor, and be leashed. When the player makes them inactive and re-activates them, the inactive object did not have the is_pet flag, so they lost the above functionalities, and you could only push or deactivate them.
Add the is_pet flag to the inactive robot object for Sentinels
Most robots do not have this, should consider implemented on a wider scale.
Changed json, relaunched in world, able to restore pet functionality after reactivation.

fix(mods/aftershock): make Sentinel Knight bots pets when re-activating

---

data/json/furniture_and_terrain/terrain-manufactured.json
data/json/mapgen/wind_turbine.json

This adds an actual reason besides common spare parts to visit wind turbines.
1. Defined a terrain entry for a wind turbine rotor, which can be deconstructed for a large wind turbine and assorted extra parts.
2. Reworked the layout of wind turbine nacelle to contain the new furniture.
Figuring out a good sprite to mock up for the external tileset.
3. Visited a wind turbine.

feat(content): add terrain that can be salvaged for an XL wind turbine to the wind turbine location

---

data/json/items/resources/misc.json

A minor thing that came up while poking through files.
Set wool mattress to gain a `use_action` override, since it inherits from down matress, to deploy as the correct furniture.
Updating constructions to make it so building a bed no longer transmutates wool and down-filled mattresses into normal ones.
What I actually wanted to do here was add `ALLOWS_REMOTE_USE` to all `deploy_furn` items, mattresses especially since they're bulky as fuck, but trying it causes this error:
I dunno how to actually fix that, I poked through the files but none of the chain of functions involved here really stood out as giving an obvious way to fix that. Best I can tell is `item::where` is not getting a valid item location when you remotely use an item with …

fix: wool mattress deploys as correct furniture

---

data/json/mapgen/shooting_range.json

Guns and ammo may spawn somewhere on the shooting range, but we have a weapon safe and a ammo dispenser doing the job.
Remove random played gun spawns, tidy up.

fix: don't spawn military guns or ammo on shooting range

---

data/mods/No_Hope/Mapgen/basement_nested.json

Fix for the guns_shotgun_rare_static -> guns_shotgun_rare

fix: fix for no hope shotgun spawn

---

data/json/scenarios.json

Remove mention of flu from Really Bad Day scenario
Flu no longer exist in game, but it was still mentions in Really Bad Day scenario.
Remove mention of flu from Really Bad Day scenario text description.
Start new game and observe Really Bad Day scenario description. It must not contain mention of flu.
None

fix: Remove mention of flu from Really Bad Day scenario

---

data/json/recipes/other/tools.json

Hand pumps weren't autolearn, a key component of the pneumatic guns (which were autolearn), balancing wise it still needs glare protection 2, so welding glasses/PDA masks are still mandatory.

feat(balance): autolearn hand pump

---

data/json/itemgroups/Weapons_Mods_Ammo/guns.json
data/json/monsterdrops/zombie_default.json

A valid point was made in Reddit. Survivor zombies should have quite high chances to have archery stuff, in comparison to regular zombies. Chances for archery drops in regular zombies were dropped by 75%, but now survivor zombies have a chance of 35% of having archery stuff. Before they had none.
Thanks to Ardashasaur for pointing it out.
See above. Changing the drop rates accordingly.
I gave survival zombies more weapons to choose from, for the drop.
Not tested! But if it compiles, it should work.

feat(balance): lower chance of archery drop rate.

---

src/cata_arena.h
src/safe_reference.h

related: project-chip/connectedhomeip#33493
~- [ ] need to actually apply fix for GCC 14 + fedora~
fix some of build errors when using gcc14
related: #4978
check each commits
was able to build on fedora 40 docker:
```
sudo dnf install git cmake ninja-build mold clang17 ccache \
SDL2-devel SDL2_image-devel SDL2_ttf-devel SDL2_mixer-devel \
freetype glibc bzip2 zlib-ng libvorbis ncurses gettext flac-devel
mkdir -p build
cmake \
-B build \
-G Ninja \
-DCATA_CCACHE=ON \
-DCMAKE_C_COMPILER=clang-17 \
-DCMAKE_CXX_COMPILER=clang++-17 \
-DCMAKE_INSTALL_PREFIX=$HOME/.local/share \
-DJSON_FORMAT=ON \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCURSES=OFF \
-DTILES=ON \
-DSOUND=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DCATA_CLANG_TIDY_PLUGIN=OFF \
-DLUA=ON \
-DBACKTRACE=ON \
-DLINKER=mold \ …
```

build: fix some build errors on fedora

---

src/item_factory.cpp

100 item-group tests were not enough nowadays, a lot of tests are in the percentile instead of percent.
Raise tests spawns form 100 -> 1000

feat: raise amount of itemgroup tests from 100 -> 1000

---

src/newcharacter.cpp

Small layout change. Window were too close to the border. Now it shifted a bit to right.
Shifted the window.
It works.
Before:
After:

fix(UI): character preview window minor layout change

---

data/json/itemgroups/books.json

As a follow up to #5036 , this adds missing manuals to the rare spawn group, raised chances a little for the rare spawns and let the books spawn outside of dojos. (Mansion) and "manual" Itemgroup (which includes stuff like rifle manual, etc.)
1. add more books to the rare matrial arts book group
2. Let Dojo manuals spawn in more itemgroups

feat(content): let martial books spawn elsewhere (rarely), add 6 missing manuals to the spawnlist

---

src/newcharacter.cpp
src/newcharacter.h

Fixing problems noted here: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5031#issuecomment-2244194732
- Character window were too big
- fixes #5044
- Got rid of WINDOW reference, so curses should build probably fine.
- Position of window now specified with orientation (top_left; top_right...) + margins
- Window autohides if width is not enough
- Tile automatically set's it's size depending desired ncols/nlines on current screen for window
- Border construction now tied to tile dimensions
None?
It works locally.
Current version:
[![asd](https://files.catbox.moe/hyfmbj.png)](https://files.catbox.moe/20n49m.mp4)

fix(UI): character preview window redesign

---

src/character.cpp
src/character.h
src/mutation.cpp
src/newcharacter.cpp
src/newcharacter.h

Segmentation fault being raising upon mutation taking off clothes. Now it should be fixed.
- Added check for mutation toggle. If we're currently not in game - do not try to place items on map.
- Recalculating clothes on mutation removal so they don't disappear
- Added support for bionic display
None.
Works locally.
None.

fix(UI): segmentation fault fix on mutation taking off clothes

---

data/json/furniture_and_terrain/furniture-storage.json
data/json/furniture_and_terrain/furniture-terrains.json

Some minor fixes from noticing that cardboard boxes turned into paper on being bashed.
1. Set cardboard boxes to yield cardboard instead of paper when bashed down, since they uncraft into cardboard.
2. Likewise updates cardboard forts and related furniture a bit for consistency.
Screaming.

fix: cardboard box furniture yields cardboard when bashed instead of paper

---

src/newcharacter.cpp

- fixes #5057
#include "cata_tiles.h" wrapped with #if defined(TILES).
Moving 'tilecontext' interactions to somewhere else to get rid of that include. But will leave it for now.
Can't test locally.
None.

fix(UI): curses build fix

---

data/json/itemgroups/Agriculture_Forage_Excavation/forage.json

Belated fix now that mushrooms use cultures instead of spores, and have a default stack instead of spawning 1 at a time.
Updated foraging itemgroups for mushrooms to yield mushroom culture instead of spores, and converted the shroom spawns from `count` to `charges`.
Screaming.

fix: foraging mushrooms yields sane amount, no longer yields obsolete spores

---

data/json/items/resources/plastic.json
data/json/recipes/armor/head.json
data/json/recipes/other/containers.json
data/json/recipes/other/materials.json
data/json/recipes/other/tools.json
data/json/recipes/other/vehicles.json
data/json/recipes/weapon/bashing.json

This adds 3d printing recipes for most other items made solely from plastic, whose standard recipes use plastic molds.
1. Added 3d printing recipes for hard hats, small plastic bottles, 2-liter plastic bottles, trash cans, funnels, plastic boat hulls, and tonfas.
2. Added a recipe for standard plastic sheets, since they're useful as groundcloths and in some constructions.
3. Added 3D printing recipes for both standard and rigid plastic sheets.
- Misc: Sanity-checked weight of rigid plastic sheet to not be 300 plastic chunks worth of weight, and in turn toned down its plastic requirements to fit the item weight better. Also updated the recipe to make a bit more sense since it involves working with plastic, not glass.
- Misc: sanity-checked material demand of plastic boat hull recipe, made …

feat(content): add more 3d printing recipes, related balance adjustments

---

data/json/itemgroups/Agriculture_Forage_Excavation/forage.json

I was in a hurry and fucked up with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5058 because was out and about on laptop.
Correct `charge` to `charges`
Screaming.
Used my fucking eyes for once.
:<

fix: typofix `charge` to `charges`

---

src/character_preview.cpp
src/character_preview.h
src/newcharacter.cpp
src/newcharacter.h
src/output.cpp
src/output.h

Curses build fix.
Wrapped character_preview_window methods with #if defined(TILES).
None.
Can't test locally.
None.

fix(UI): another attempt to fix curses build

---

.github/workflows/lint-workflow

lint github actions before they cause issues
adopt https://github.com/marketplace/actions/actionlint
original workflow from: https://github.com/mimmi20/browser-detector/blob/30ba8d300b8a95c3cbe4425b144c8e8d7a1144cf/.github/workflows/lint-workflow-files.yml#L30
scream

ci: add `actionlint`

---

src/ui.cpp
src/ui.h
src/wish.cpp

Imagine you haven't played the game for a while. When you're back you installed some mods, maybe the one that got update. You suddenly want to check changes in mutation branches. You'll have to scroll like 20 minutes to check if mutations in some branch (slime, arachnid, chimera, etc..) are changed/added/removed. Or to find out which categories and mutations were added by some mod.
I'm offer solution to pick a mutation category and filter all traits by that category. It should make life easier.
- ui.cpp: new method 'void uilist::filterpredicate' to filter entries by their id
- wish_mutate_callback in wish.cpp: new input option on wish mutation menu (will open menu with list of all mutation category to choose from) and logic for it
None.
It works locally.
Video showcase below: …

feat(UI): filter by category for mutation debug menu

---

src/wish.cpp
tests/Makefile

- fix #5081
- fix target name
- remove `Werror` so warnings aren't treated as errors
will check using CI
gaaahhhh

build: fix build (again!)

---

data/json/items/melee/bludgeons.json
data/json/recipes/weapon/bashing.json

Added spiked club item, a wooden club with bands of iron and spikes crafted onto it. Spiked clubs were a common medieval weapon among peasants. Also changed the morningstar and warhammer to have +1 to hit, instead of -1 and 0 respectively, since morningstars are literally just heavily spiked maces and warhammers are just hammers meant to be used as a weapon.
Although there are crude medieval weapon equivalents for swords and daggers, there is no such equivalent for maces, despite an IRL weapon- the spiked club- serving that purpose. Furthermore, the morningstar and warhammer had relatively low to-hit chances despite being fairly simple weapons to use.
Added in the spiked club, a bludgeoning/piercing weapon made out of wood and iron and able to be crafted relatively early on using wood, …

feat(content): Spiked club, minor weapon tweaks

---

.github/workflows/matrix.yml

use cmake more because it's pain having to manage both makefile and cmake
turn `cmake: 1` for all CI when testing PRs (matrix.yml)

ci: use cmake for all matrix

---

data/json/items/comestibles/med.json

as a proud smoking hater that line sounds very... _hipster_
simplified the description similar to other cigarette items
become savage

feat: simplify cigar description

---

.github/workflows/autofix.yml

Reverts cataclysmbnteam/Cataclysm-BN#5104
fixes #5110

revert: "ci: run typescript test before autofix"

---

data/json/items/generic/casing.json
data/json/recipes/ammo/components.json

.22 was in an odd place. already sub par, it wasn't a very well used ammo to begin with, having it "not able to handload" it doesn't help the case. There are videos of people reloading .22 with oxy or match head powder, so this is possible to do.
Create Recipe to create a usable .22 casing with primer.
Change a name and description of .22 casings to match.

feat(content): reuse of .22 casings

---

data/json/uncraft/generic.json

This makes it so that lighters don't increase in total mass when taken apart.
Changed the uncraft for lighters to yield a plastic scrap instead of a plastic chunk. Instead of going from 14 grams to 55 grams when disassembled, it now goes down to 10 grams.
Fiddling with refillable lighters which also increase from 20 grams to 55 grams (5 from pilot light, 50 from scrap metal) when taken apart. We don't really have a generic item for tiny amounts of steel like we do with plastic so eh.
2. Load-tested and confirmed lighters yield plastic scrap when taken apart.

feat(balance): lighters yield plastic scrap instead of plastic chunk when taken apart

---

src/crafting.cpp

Learning something from disassembly was a very frustrating affair. With only a chance of 25% it was a extremly unreliable way in learning a recipe from something. You need 8 tries to have a 90% chance in learning something. That is not good at all (imagine how many engines you have to disassemble to learn anything. 
Now it is depending on Int and skill. If your skill is +4 of the skill needed, you get a 100% chance.
If your skills are too low, you still won't learn the recipe, so be careful with that as well.
Now it is more depending on Int and skill.
leaving as is, but it is less than optimal.
works, loads, all fine.

feat(balance): disassembly learning now depends on skill and Int more.

---

data/json/mapgen/house/2Story03.json
data/json/overmap/multitile_city_buildings.json
data/json/overmap/overmap_terrain/overmap_terrain_residential.json
data/json/regional_map_settings.json

more house spawn variety
added 2story03

feat(content): add 2story03

---

data/json/monsterdrops/zombie_default.json

This allows guns dropped off basic zeds to spawn with damage and fouling, consistent with weapon drops from other zombies and ferals.
Set the call to `default_zombie_carried_guns` in `default_zombie_items` to spawn with the same damage (0-2) and dirt (0-1500) ranges as sidearms dropped in `mon_zombie_soldier_death_drops`.
screm
3. Spawned in and killed a big group of basic zombies
4. Confirmed the guns and magazines have the expected range of damage.

feat(balance): guns dropped by basic zombies can now spawn damaged and/or dirty, like with other zombie gun drops

---

data/json/monsterdrops/zombie.json

I encountered an armored zombie and got 1800 copper wire off its corpse, oops.
Set the copper wire spawn in `mon_zombie_armored_death_drops` to use `charges` instead of `count` when it picks salvaged power armor instead of an intact suit, making it drop 1-12 wire consistent with all power armor giving 12 wire when salvaged.
Screaming.
Used my eyes.
I guess I should cast this boon into lava in my laptop save as punishment for my having set it wrong back when I reworked armored zed drops...

fix: armored zombie no longer drops entire stacks of wire

---

data/json/construction.json
data/json/construction_group.json
data/json/furniture_and_terrain/furniture-migo.json
data/json/furniture_and_terrain/furniture-terrains.json

Mi-go locations are painful due to how hard it it is to destroy gas emitters. Scarred lumps for example were up to 600 bash damage and min of 250. This allows you an easier time smashing them, as well as for weak characters they can now pour concrete over the two worst offenders. 
I first made it easier to smash the worst offenders. That will solve it for decent strength players wielding heavy sledges. I also set most of these terrains to mineable, which solves it for players with mining tools. I also added a way to concrete over the scarred lump and seeping scar. You can't drag concrete lumps and they act as medium boulders, but you can still smash them. They are an obstacle until you get rid of them. Now you should be able to live in mi-go places if you put in a lot of effort, or make …

feat(balance): Easier ways to remove mi-go gas emitters

---

data/json/recipes/food/brew.json
data/json/recipes/food/other.json

This fixes some brewing recipes I spotted that had a mismatch between how much material they use and how much stuff they produced.
1. Toned down the `result_mult` of unfermented vinegar from 10 to 3, and bumped the amount of water required from 2 to 3. So now it makes the same amount of product (750 ml) as most of the other brewing recipes, instead of turning half a liter of water into 2.5 liters of vinegar-to-be.
2. Increased unfermented gin's water usage from 2 to 3, matching how it produces 750 ml of end result.
3. Misc: the "vinegar from acetic acid" recipe now requires 19 water and produces 320 charges (the 20th is presumably the volume of acetic acid), matching how it requires 5 liters worth of vinegar to make.
1. Keeping vinegar at 10x output and just making it use a lot more …

fix: adjust material usage for vinegar and gin recipes

---

data/json/mapgen/lab/lab_floorplans.json
data/json/mapgen/lab/lab_floorplans_1side.json
data/json/mapgen/lab/lab_rooms.json

This makes labs a bit more viable as an alternative to hospitals for blood analysis missions. Before, only one of the several room variants that spawned centrifuges provided a working console for one.
1. Reworked the room variants that tuck a centrifuge in a corner room to spawn an actually usable centrifuge with a viable console next to it, except for the flooded variant which keeps a broken console.
2. Reworked the fume hood room to spawn a smaller number of centrifuges paired with consoles. Some broken like the two-centrifuge medical room, one working.
3. Adjusted the nested chunk associated with the above room to edit the correct tiles to swap two of the centrifuges with cloning vats, also correctly clearing out furniture since centrifuges aren't terrain.
4. Updated the 9x9 nested …

feat(balance): make more lab centrifuge rooms usable for blood analysis

---

data/json/itemgroups/Weapons_Mods_Ammo/ammo.json

Update ammo.json
Update ammo.json
Same with the magazines and the weapons, the distribution of ammo didn't follow any rules. This will change it.
1. distribute common ammo according the guns spawning in the common group. For example, if 9mm guns are 220 combined tickets, 9mm ammo also will.
2. rare ammo will have the better versions of ammo (+P+ for example).
3. Obscure gets the obscure gun ammo, if the obscure gun uses ammo that is common in other groups, it will not be in obscure.
4. If a pistol is using rifle ammo, the rifle ammo has a slim chance to spawn in the pistol category.
5. Due to the massive amount of 9mm and other pistol ammo already, rifle won't spawn pistol ammo, except .22, or classic bolt action rifles (magnum for example).
doing something better for 5 hours on a sunday. …

feat(content): revamp of ammo spawns

---

data/mods/innawoods/specials.json

Adds some specials, which make sense to appear in deep wilderness.
Also tweaked number of wasps nests spawning in overworld.
Wasp nests spawns lowered to 1/10 of what it was. 
Made some water specials (ponds, basins and bogs) possible to actually spawn now. 
Added few dumpsites for chance to get metal.
Also added very rare desolate barns and derelict properties.
Let someone else do it. 
Just check if map loads and go a bit in any direction, find some new map specials and not be surrounded by 30+ wasps.

feat(mods/innawoods): Tweak spawn chances for map specials in innawood mod.

---

data/json/monsters/insect_spider.json

This sanity-checks more recently-added and/or changed mutant insects a bit.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4544
1. Fixed giant bees envenoming you via bites instead of a sting attack, and fixed its venom being the only case where it's applied to specific BP.
2. Toned down armored centipede's bite to only have as much arpen as its normal attack, which is already plenty. Also lil spelling tweak in description.
3. Nerf dragonfly naiads to have worse overall melee stats than adult dragongflies, swapped the stretchy limb attack for a bite attack like adult ones have but less powerful. Updated description accordingly, fixing a typo too.
screm

fix(balance): sanity-checking for giant bees, armored centipedes, and dragonfly naiads

---

src/suffer.cpp

The advanced microreactor is described as being safer than the regular microreactor, and while this is technically true, it's just 2/3rds less radioactive; it's still plenty dangerous to anyone without a radiation scrubber CBM. And given how rare both it and its prerequisite is, and how difficult it can be to get them AND a radiation scrubber CBM, I don't think it's unreasonable to just make the advanced microreactor not irradiate you.
A single number in the C++ was changed, effectively eliminating the radiation output from the advanced microreactor.

feat(balance): Advanced Microreactor No Longer Irradiates You

---

data/json/items/comestibles/med.json
data/json/recipes/other/medical.json

@proxihunter pointed out 2 errors in antiseptic soaked rag and cotton balls. This is the fix for it.
crafting antiseptic cotton balls will now create 8 balls instead of 4 (it used 8). Rags now provide 2 rags back after using, also crafting the desinfected rag will use 4 rags and creates 4.

fix: antiseptic rag and cotton balls

---

data/json/items/comestibles/med.json
data/json/uncraft/generic.json

First aid kits were a bit lack luster in what they had. Adding a scissor, medical gloves and a mask would make sense in that case, even just for flavour
See above.

feat(content): add more stuff to first aid kit.

---

data/json/items/gunmod/barrel.json
data/json/recipes/other/containers.json
data/json/recipes/weapon/mods.json

There aren't very many early to midgame UPS weapon uses that aren't just lasers or the coilgun.
Added a makeshift railgun attachment for firearms that boosts the damage and range of a weapon but worsens its accuracy and drains some UPS with each shot.

feat(content): makeshift railgun accelerator attachment

---

data/json/items/armor/power_armor.json
data/json/recipes/armor/suit.json

The survivor armored exo-suit is a bit strong for how easily it's made. This PR seeks to fix that.
The following changes have been made: the survivor armored exo-suit's thickness was reduced to 6, its speed boost was removed, it was changed to the 'outer' slot instead of belted, it no longer works with power armor CBMs, it has a higher skill requirement for crafting, and many of the ingredients required to make it have been increased to reflect their purpose.

feat(balance): survivor armored exo-suit rebalance

---

data/json/furniture_and_terrain/terrain-windows.json
data/json/itemgroups/Drugs_Tobacco_Alcohol/drugs.json
data/json/itemgroups/vending_machines.json
data/json/mapgen/Pottery_Sewing_Shops.json
data/json/mapgen/gunsmith.json
data/json/mapgen/s_gas.json
data/json/mapgen/s_grocery.json
data/json/mapgen/s_gun.json
data/json/mapgen_palettes/road.json

As wished, addition of medical vending machines into groceries and gas stations. Some fixes
1. Addition of medical supply vending machines into groceries and gas stations
2. removal of unnecessary furniture entry in gun shops
3. fix one typo because I made the same typo while searching files.
4. removal of the empty reinforced vending machines at craft shops and add drink and food ones instead.
not doing it

feat(content): medical supply vending machines in shops and fuel stations

---

data/json/furniture_and_terrain/terrain-windows.json

This fixes two cases of windows being deconstructable that very obviously should not be. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5324
1. Converted basic boarded up windows to not inherit from `t_window`, soit can't be trivially deconstructed and since the other boarded windows don't let you take them apart without first prying the boards off.
2. Likewise, converted the alarmed variant of metal bar windows to not inherit from basic windows, because once again that let you take them apart with ease (and get a mere sheet of glass for your trouble).
Defining abstract terrain for windows we don't want deconstructable to all inherit from. Only two relevant windows inherited from a different style of window in the first place so ech, not really vital.
1. Checked affected …

fix: remove flaws `copy-from` that allowed deconstructing a single variant each of boarded-up and barred windows

---

data/json/items/comestibles/seed.json
data/json/recipes/food/seeds.json
data/mods/No_Fungi/recipes.json

This makes it feasible for Mycus players to farm, by adding a seed for planting mycus fruit.
1. Added mycus fruit seedpods. Stacks up like regular seeds, but requires planting on mushroom-friendly places like mushroom cultures do. Has roughly 5% the calories of the fruit used to make it per seed, and same use action as mycus fruit and marloss wine.
2. Added recipe for mycus fruit seedpods, basic cutting like a normal seed recipe but at a survival skill requirement in between that of basic seeds and mushroom cultures. Also notes in a comment to in the future add support for mutations unlocking recipes.
3. Set No Fungal Monsters mod to obsolete the recipe.
Tackling the idea of locking marloss wine and mycus fruit seedpods behind the Mycus mutation now instead of later.
Checked affected …

feat(content): add seedpods for planting mycus fruit

---

src/character.h
src/item.cpp
src/item.h
src/item_factory.cpp
src/melee.cpp

As in title: show all attacks.
Iterate over all attacks, show each separately. Default to old behavior if there's exactly one attack.
Also fixed a bug where DEFAULT attack is added to all weapons, even those that have explicit non-DEFAULT attacks.

feat(UI): Show attack statblocks for all attacks on an item

---

data/json/items/armor/masks.json

Tiny lil fix to follow up on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5346, I forgot a description update.
Updated description of bandana to mention you can transform it to switch bodypart covered, since the head version mentions that.
Leaving it an eldritch mystery for the player to discover.
1. Used my eyes.
2. Also loaded up compiled test build to confirm transform does indeed work for non-`TOOL_ARMOR` wearables like I saw on a few items, and that it correctly changes BP even when worn.

fix: bandana description references ability to transform

---

data/json/materials.json

Fixes a fucky-wucky I made in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5348.
Added the missing `repaired_with` entry to budget steel.
Screm

fix: repairing budget steel doesn't ask for a `none`

---

src/ranged.h

According to the comment, handle_gun_damage() is supposed to return `true` if the gun misfires or has other problems, and return `false` otherwise. However, reading the function, it's clear that it does the exact opposite.
Just change the comment.
Did not consider alternatives.
Did not test.

docs: Correct a comment for handle_gun_damage() to reflect actual code behaviour

---

data/json/recipes/food/drinks.json

This allows making generic weak mixed alcohol by watering down strong alcohol, letting you basically make grog without actually bothering to write up a separate comestible just for it.
Added an alternative recipe for weak mixed alcohol combining 7 units of relevant strong alcohol (250 ml) to 4 clean water (1 L), producing 5 units (1.25 L) of weak mixed alcohol.
Compare the recipes for ethanol and denatured alcohol asking for 14 units of strong mixed alcohol or 10 units of weak mixed alcohol.
1. Adding grog anyway for the funny.
2. ["Kerosene, propylene glycol, artificial sweeteners, sulphuric acid, rum, acetone, red dye no. 2, scumm, alxe grease, battery acid, and/or pepperoni."](https://www.youtube.com/watch?v=OgPsGdKToEU)
2. Ported …

feat(balance): allow making weak mixed alcohol by watering down strong mixed alcohol

---

data/json/items/armor/shields.json
data/json/recipes/armor/other.json

A collection of assorted shield-related tweaks.
1. Added a recipe for riot shields, made from a rigid plastic shield with some level of welding and sawing for the handle and related framework. Also adds a 3d printing version of the recipe.
2. Added manhole covers as an alternative component for welded shields.
3. Added `repairs_like` to ballistic shields, set to be about on par with mid-late tier shields.
Screm

feat(balance): allow crafting riot shields, alternative component for welded shield, add `repairs_like` to ballistic shield

---

data/mods/CheesyInnaWoodsFixes/recipes/existing_recipe_changes/tool_recipe_bn.json

Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5378
Set the recipe override in cheese's innawoods recipe mod to use normal glass jars and not sealed ones.
Screaming.
Confirmed that's the item ID of normal jars you scrounge up from forest trash.

fix: don't use sealed jars for chemistry set recipe override

---

data/json/vehicleparts/vehicle_parts.json
data/json/vehicleparts/wheel.json

Simple sanity-checking of wooden vehicleparts after testing in current playthrough. Makes a few wooden vehicleparts easier to install than their normal counterparts.
1. Changed wooden tables to `vehicle_nail_install` and `vehicle_nail_removal` instead of `vehicle_bolt`, using same amount of nails/adhesive as wooden seats.
2. Changed wooden wheel mounts and cart wheels to use level 1 wrench quality instead of level 1, and now the wheels use wood sawing 1 quality to remove just as the wheel mounts do.
screm

feat(balance): wooden tables, wheel mounts, and wheels easier to install than metal counterparts

---

data/json/recipes/armor/other.json

I said in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5375 I added a recipe but I forgot actually aaaa
Adds recipe for pirate flag, currently basic copy of the US one.
screm
In the future the flag recipes will need some sanity-checking but that can wait.

fix: add pirate flag recipe I forgot to add to the Jolly Roger PR

---

.github/workflows/i18n-extraction.yml
.github/workflows/i18n-printf-format.yml
.github/workflows/push-translation-template.yml

missed `pip3` in #5384 because i only applied fixes by searching for `pip install`
add `--break-system-packages`

ci: fix pip installation in i18n

---

data/json/items/armor/masks.json

I discovered (namely in the form of absentmindedly almost fucking destroying my bandana) that the head bandana copying from the face version does not gain the repair difficulty of its base version, so it would jump up in repair difficulty massively.
Gave head bandana `repairs_like` pointing to the face version.
Screaming at code and trying to make it look at repair difficulty of inheritance.

fix: assign `repairs_like` to head bandana

---

data/json/items/armor/sheath.json
data/json/items/melee/spears_and_polearms.json

A couple more tweaks to allow stashing things in other things.
1. Defined `min_volume` of 1 liter for axe ring holster as its automated method gave it a minimum volume that was a few ml too high to stash a hatchet.
2. Gave pointy sticks the `JAVELIN` flag, as their volume is just enough to fit in a javelin bag. Long pointy sticks remove this flag accordingly now since they inherit from pointy sticks.
screm
2. Ported file changes over to laptop build and load-tested.
3. Checked item info of hatchet now says it fits in an axe holster, and pointy sticks say they fit in a javelin bag.

feat(balance): adjust `min_volume` of axe holster, allow stashing pointy sticks in javelin bag

---

data/json/construction.json
data/json/construction_group.json
data/json/furniture_and_terrain/furniture-appliances.json

We can place minifreezers as grid furniture, but not minifridges. This solves that, and does a few related consistency tweaks.
1. Added abstract and furniture definitions for minifridges placed as grid furniture. Power draw across 10 minutes set to be consistent with vehicle minifridge's current powerdraw.
2. Added construction entry and construct group for the above.
3. Misc: Edited grid minifreezer's power draw to be consistent with vehicle version.

feat(content): allow placing minifridges as grid furniture

---

data/json/items/gun/cannon.json
data/json/recipes/ammo/launcher.json

A couple of misc fixes for cannons and associated ammo.
1. Fixed reload time of blackpowder cannons being 10 times higher than intended, and also added `STR_RELOAD`. Split off from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5407 so the need to review code changes doesn't hold up JSON fixes.
2. Fixed recipe for cannon scrap shot calling for lead in addition to the actual scrap.
screm
Used my eyes for once, did basic fucking math to confirm that 3000 moves is in fact 30 times 100.

fix: fix reload time of cannons being 10x higher than intended, fixed scrap shot also demanding lead

---

src/mapdata.h

Another thing I borked in an earlier PR.
Set mapdata.h to use the itemgroup ID `digging_soil_loam_200L` as the default `digging_result` for terrain that doesn't have an override specified. I could've sworn I updated that in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5409 but nope.
screm
1. Used my fucking eyes.
2. Compiled and load-tested.
3. Dug a deep pit, depositing the yield of each step in a different tile.
4. It actually produces dirt, about 200 liters from a shallow pit and about 400 for a deep pit, as expected.

fix: use correct itemgroup ID for default `digging result` of soil

---

data/json/external_tileset/External_Tileset_DP_Normal.json

I got so used to how I set sail and pirate flag vehiclepart sprites to not rotate since they should alwaws appear to be standing straight up that I forgot that the makeshift cannon's vehiclepart sprite needs to be rotatable.
Added `"rotates": true` to UDP external tileset sprite assignment for `vp_mounted_makeshift_cannon`.
Screaming.

fix: makeshift cannon external UDP sprite now rotates

---

src/creature.cpp
src/creature.h
src/explosion.cpp
src/fungal_effects.cpp
src/map_field.cpp
src/monattack.cpp
src/mondeath.cpp
src/trapfunc.cpp
src/weather.cpp
tests/reading_test.cpp

Slowly crawl towards bodypart enum removal by removing `Creature::add_env_effect` overload that uses it.
Just replace it with `body_part_str_id` overload.
Things should work as they did before. Tests pass.

refactor: Remove `Creature::add_env_effect` using bp enum

---

data/json/bionics.json
data/json/items/ammo.json
data/json/items/melee/spears_and_polearms.json
src/character.cpp
src/ranged.cpp
tests/throwing_test.cpp

(throwing rocks for 30 damage, and javelins for 70 damage @ STR 16, throwing 10)
- fix #2571
made extra throwing damage proportional to strength and skill level. the formula for damage is:
```math
speed = \log_2\left(\max(1, \text{throwing skill level})\right) + \log_2\left(\max(1, strength)\right)
```
```math
damage = 0.5 \times \frac{\text{weight}}{1\ \text{kilogram}} \times speed ^2
```
graph: https://www.desmos.com/calculator/eej5a9mzo2
extra throwing damage bonus for javelins at 1kg @ throwing 10 (x: strength)
| throwing 0 | throwing 5 | throwing 10 |
| :-: | :-: | :-: |
|![image](https://github.com/user-attachments/assets/c6c1a14c-d20b-4f56-b849-f3019d505e49) |![image](https://github.com/user-attachments/assets/340ce153-d66f-4b97-aea7-1f34eed5cb4c) …

feat(balance): revamp throwing damage

---

src/bionics.cpp
src/catalua_bindings_creature.cpp
src/character.cpp
src/character_turn.cpp
src/creature.cpp
src/creature.h
src/iexamine.cpp
src/iuse_actor.cpp
src/mattack_actors.cpp
src/monattack.cpp
src/monster.cpp
src/npcmove.cpp
src/npctalk.cpp
src/player_hardcoded_effects.cpp
src/wisheffect.cpp
tests/creature_test.cpp

Slow crawl towards alterable anatomies by removal of hardcoded body part enum use.
As in title - replace uses of enum with `bodypart_str_id` ones. Relatively simple, boring refactor.
Things compile and tests don't break
Follow up after #5421

refactor: Remove remaining uses of body_part enum from creature.h

---

src/character.cpp

fixes #5443
According to the linked issue, the led tattoo bionic is too bright. It should be difficult to read by their light, as the description implies.
The solution was just to set the lumination value to the same as that of the glowing led effect.
It's also possible to just embrace the brightness and remove the part of the description which implies that the light is supposed to be dim.
1.) Give a character some power bionics and the LED Tattoo bionic
2.) Put them underground
3.) Turn LED Tattoo on
4.) Read book
(For best results, make sure the character isn't illiterate first)

feat(balance): make LED tattoo bionic less bright

---

data/json/furniture_and_terrain/furniture-flora.json

fix: cattails are correctly named

---

data/json/recipes/electronic/components.json
data/mods/CheesyInnaWoodsFixes/recipes/existing_recipe_changes/alternativeCopperWire.json

This sanity-checks the recipe for copper wire to be in line with recent changes to solder recipe, and to add more alternative options for the insulation as initially added to Cheesy's innawoods recipe mod.
1. Updated copper wire recipe's tool usage to match that of solder, removing the more wasteful option of using a forge as an alternative to `surface_heat` and making the required forging tools more basic since working with a reasonably soft metal. Also gained batch_time_scaling.
2. Defined a much broader accepted range of components to take the place of insulation. This adds medical tape as an alternative to duct tape, along with allowing paper insulation, as well as thread and pitch as based on the ideas had in Cheesy's mod. The latter is a bit less permissive since we're not making …

feat(balance): consistency-check copper wire recipe, add alternative insulation options from Cheesy's Innawood mod

---

data/json/recipes/other/tools.json

Derg brain smol.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5486
Actually ported the fucking recipe for beehives from MST Extra now that the item is in vanilla.
Screaming.
No thoughts, head empty, too occupied monchin' the forbidden corndog:

fix: beehives actually craftable

---

data/json/obsoletion/npc.json
data/mods/Aftershock/npcs/cyborg_npcs/npc_classes_cyborg.json
data/mods/more_classes_scenarios/cs_classes.json

sanity check of professions and NPCs after merging https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5484
makes sure all NPC's and professions do not have the `Hydraulic Muscles CBM` without also having `Skeletal Bracing CBM`

feat(content): Check bionic professions

---

data/json/items/gunmod/muzzle.json

Lil followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5470, another of my PRs added a craftable shotgun suppressor so it didn't get its loudness value tweaked like all the others.
Bumped up homemade shotgun suppressor's modifier to match that of the other makeshift suppressor, just as the shotgun suppressor's modifier matches that of the standard one.
screm
Used my eyes.

feat(balance): update loudness modifier of newly-added suppressor

---

data/json/harvest.json
data/json/monsters/reptile_amphibian.json

I thought I caused this but no it was in the original PR, oops.
1. Changed name of `mutant_mammal_large_scute` to `mutant_animal_large_scute` for giant rattlesnakes to use.
2. Defined harvest entry `animal_toothy_large_scute` for non-mammal, large but non-mutant critters like sewer gators. Gives scutes and pointy teeth, but normal bones since not currently considered a mutant.
Making sewer gators count as mutants too and using `mutant_animal_large_scute`.
1. Used my fucking eyes to confirm the harvest IDs matched this time.
2. Also searched-in-folder to confirm that nothing in JSON nor in mod folder was using `mutant_mammal_large_scute`.
AAAAAAAAA

fix: giant rattlesnakes and gators harvest entries now exist

---

src/character_preview.cpp

Lil change to something that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5479 evidently tweaked unintentionally.
Rigged it so character outfit shows by default in character preview. Very minor unimportant thing in the end unless you're playing Cata at work I guess.
Make it something you can set in options if you want extra nudity without ever having to press C once, I dunno.
2. Saw character preview shows equipment as default.
3. Hit C a few times, it correctly toggles clothes on and off.
Reverse stripetease.

feat(UI): default character preview to show equipment again

---

data/json/construction.json

I noticed the niter bed recipe was asking for soil twice in the construction.
Removed redundant component from construction entry.
screm
Used my eyes.

fix: don't ask for soil twice in niter bed recipe

---

data/json/flags.json
doc/src/content/docs/en/mod/json/reference/json_flags.md
src/flag.cpp
src/flag.h
src/melee.cpp

We have `SHOCKING`, we have `FLAMING`, but we did not have an acid equivalent. Also, I really needed an acid equivalent for some modded content.
Also, we apparently did not document the former flags either, so I made sure to correct that mistake as well
Adds `ACIDIC`, a new flag that does the same thing as `SHOCKING` and `FLAMING` but for acid damage.
Adds documentation for the mentioned flags
- JSONize the damage amount
Above my paygrade, sorry. ***Definitely*** the preferred solution for the future, though.
- Weh endlessly
That's Chaos' job ^-^
It builds and works on my machine
Is it just me or are the damage values for the flags kinda... low? 1 to 8 points of damage isn't terribly much imo. I'd definitely consider raising them up to a more meaningful range
Acid damage could definitely …

feat(content): Add ACIDIC flag for melee damage

---

src/scores_ui.cpp

The item kill list added in #5394 wasn't scrollable, even after it accumulated enough entries that they didn't fit in the window. 
Stop resetting the window text after every key input.
Did not consider alternatives.
Loaded save with a weapon with more kills than fit on the screen. Looked at kill list. List can be scrolled.

fix: make item kill list scrollable

---

data/json/itemgroups/misc.json

Fixes an oops causing alluvial deposits to give fuckloads more gold or silver than intended.
Set the gold and silver results in `digging_alluvial_extras` to use `charges` instead of `count`, like the rest of them do. I can only assume that since I was gonna initially use 1dX number of full stacks, decided to use charges to make the results even more randomized thinking it'd look nicer, presumably when I did that I forgot to update all of them...
screm

fix: don't spawn 400-1600 entire stacks of gold or silver from alluvial deposits

---

build-scripts/build-clang-tidy-plugin.sh

Let's see if this makes clang-tidy shut up!
clang-tidy CI keeps failing because it can't find lua.h, so going to see if adding LUA to its cmake configuration makes it shut up.
`-DLUA=ON`
Threw together a test PR on my own fork using Scarf's PR #5538 which has been failing clang-tidy build. It didn't work nicely until I told it to just process all cpp / header files in /src then it gave me some new and exciting, but most importantly DIFFERENT, errors. It seemed to be able to find the lua headers just fine

ci: add `-DLUA` to clang-tidy cmake config

---

gfx/MSX++UnDeadPeopleEdition/tile_config.json

Fix fallback sprite showing for the auto travel path on the overmap. This was because of missing definitions in the UDP tile_config.
Also assigned a semitransparent sprite for when the path is on a different z-level than currently viewed. (id's: "overmap_path_above" and "overmap_path_below")

fix(UI): Added missing sprite definitions for overmap auto travel path

---

data/json/itemgroups/Weapons_Mods_Ammo/everydaycarry_guns.json
data/json/itemgroups/Weapons_Mods_Ammo/nested_ammo.json
data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json
data/json/items/gun/454.json
data/json/items/magazine/454.json
src/url_utility.cpp

@ZChris13 pointed out that .45 colt is shorter than .454 Casull, and #5593 removed too many ammo types. 
Put .45 Colt back into the allowed list.
Have not considered alternatives.
Loaded game, loaded gun. Works as expected.

fix: Add ammo types to Taurus Raging Bull revolver

---

src/panels.cpp

Fix #5591
In calculation of most extreme temperature, use `BODYTEMP_NORM` as the "zero", instead of actual zero.
* UI shows actual character temperature instead of "Freezing"

fix: UI always showing "Freezing" temperature

---

.github/workflows/clang-tidy.yml
build-scripts/build-clang-tidy-plugin.sh

Make clang tidy work again.
As suggested by Scarf, based on link:
https://stackoverflow.com/questions/71213753/switch-to-llvm-13-as-default-instead-of-llvm-10-in-ubuntu-20-04-how
* Wait for clang-tidy to (hopefully) not-fail this time

fix: Configure clang-tidy to use llvm-18

---

src/iuse.cpp

Smart shot purifiers let you pick to remove one mutation but also remove up to two extra random mutations.
A rare one use consumable that gives the impression that it gives you control shouldn't also be unreliable. It being unreliable doesn't create any interesting situations for the player.
To make it only remove the selected mutation.
Drank a mutagen removed every mutation with multiple smart shots

feat(balance): reliable smart purifier

---

data/json/items/armor/helmets.json

This sanity-checks carbon fiber helms to not be massively more protective than other carbon fiber armor.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5627
Set carbon fiber helm to inherit from the barbute instead of heavy survivor helm. Side effect of this is it gains eye protection as well.
Explicitly setting it to still only protect the head, or flavoring it as more like the riot helms with a visor you can flip up and down?
2. Load-tested in compiled test build and confirmed armor values are down to a more consistent amount.

fix: carbon fiber helmet no longer much stronger than other armor pieces

---

data/json/itemgroups/Clothing_Gear/clothing.json
data/json/itemgroups/Locations_MapExtras/locations.json
data/json/items/tool_armor.json
data/json/recipes/armor/suit.json

Added thermal electric survival outfit, a temperature-regulating piece of clothing, plus recipe.
Survival in summer is not difficult but _tedious_ due to most clothing not having temperature regulation for high temperatures, and armors having relatively high thermal insulation. It means survivors can't really fight during the summer.
Added thermal electric survival outfit, a piece of clothing that regulates the wearer's temperature when turned on. Also added crafting recipe.
Overhauling the way clothing insulation works to have a maximum and minimum insulation.
It still needs testing and possibly loot table additions, but the basic item and recipe are completed for now.

feat(content): thermal electric survival outfit

---

data/mods/No_Hope/item_groups.json

None applicable
Fixes #5654 
To account for #5635 , moved to `guns_pistol_common`, as the items being injected are pistols.
Just replaced injection to `drugdealer` with `guns_pistol_common`.
I thought about changing or removing the `magazine` and `ammo` fields, but I'm not really confident I know what those really do.
Just loaded a world with No Hope in it. Might have missed a step.

fix(mods/no_hope): Inject to `guns_pistol_common` instead of `drugdealer`

---

data/json/furniture_and_terrain/terrain-floors-indoor.json

I noticed that the private resort upper floor had visible snowfall in the hallways. This turned out to be because the `t_floor_red` used in those hallways doesn't have the `INDOORS` flag. Neither do `t_floor_green` and `t_floor_blue` defined in the same file. Since all three are only used in interior locations (the private resort, small office, irradiation plant and various lab rooms), this is probably a mistake.
Added the `INDOORS` flag to those three floors.
Making private resort upper floor use `t_carpet_red` instead. Not sure if it's supposed to be that, there's carpet elsewhere in the resort, but editing the terrain itself also means it won't rain inside the irradiator plant.
Load save from a private resort during a snowstorm. No snowfall graphics inside, only outside.

fix: add INDOORS flag to red, green and blue floors

---

src/map_extras.cpp

RoyalFox mentioned wanting to tweak item spawns in some of the map extras and some initial confusion ensued about whether the old hardcoded map extra functions need to be touched too since they've been JSONized. I noted that basically the only reason to bother leaving them in is if some obscure mod out there pulls a No Hope and contains full overrides of the map extra definitions in their JSON for some insane reason, so it should be safe to remove the now-unused map extra functions outright.
In map_extras.cpp, removed the functions `mx_military`, `mx_science`, `mx_collegekids`, and `mx_drugdeal` (along with their inclusions in `FunctionMap builtin_functions`), as all of those are now handled by mapgen update JSON.
JSONizing a couple more of them while I'm at it.
Compiled and load-tested, …

refactor: clean out map extra functions that've since been JSONized

---

doc/src/content/docs/en/dev/guides/building/cmake.md

For building the game with MSYS, I followed guidelines in the docs but some errors occurred and the game didn't build.
After searching, I found the problem; `base-devel` package was needed.
So I installed it, and the build started running.
I add this in docs to prevent others from repeating my mistakes.
`Install base-devel.`
Seeing.

docs: Add `base-devel` to the .md

---

data/json/items/armor/boots.json
data/json/items/armor/helmets.json

Fixes a mistake I made in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5645
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5675
Correctly manually specifies encumbrance overrides for plated leather boots and helm. Was a copypaste error on my part it seems.
Screaming.

fix: don't make plated leather boots and helm massively more thick than intended

---

data/json/items/tool_armor.json
data/json/recipes/armor/head.json
data/json/recipes/armor/suit.json

As per - fixes #5678 details, the liquid cooling suit cannot be used with mutated anatomy thanks to its hand and foot coverage. However, hand and foot coverage is still important for wintertime, especially for mutants who struggle to wear most forms of gloves and shoes.
I added in a suit (no hands, feet, or head) and a mask version of the thermal cooling outfit, plus recipes for them.

feat(balance): Mutant-friendly cooling outfit

---

data/json/items/gun/metal_rail.json
data/json/items/gunmod/barrel.json
data/json/recipes/weapon/mods.json

The makeshift railgun attachment and weapons had some minor issues- the attachment was a bit overpowered, while the heavy rail rifle and military rail rifle both had the RELOAD_ONE flag despite having an ammo capacity of 20. The military rail rifle also felt a little unrealistic as a semi-automatic weapon used in the military.
The makeshift railgun has been split into the makeshift rifle accelerator and the makeshift pistol accelerator. Both have had their handling further reduced as well. The heavy rail rifle and ferromagnetic rail rifle have had their RELOAD_ONE flag removed, description modified slightly to express this, and the ferromagnetic rail rifle has had its damage increased to 30 as an amount between the makeshift and heavy. Finally, all three ferromagnetic rail weapons have …

feat(balance): Railgun rebalance

---

data/json/items/melee/bludgeons.json
data/json/items/melee/swords_and_blades.json

Bone maces and clubs are both set into a wooden haft in their recipe and description, and being only made of heavy bone makes them notably more awkward to repair than the other monster hunter weapons.
Added wood to the materials list for bone club and bone cleaver.
1. Making heavy bone items require normal bones to repair instead of heavy ones.
2. Coding support for making repair items an array so that bones, human bones, heavy bones, and teeth can be used to repair bone and teeth items in general?
Ported file changes over to playthrough build and load-tested.

fix: add wood material to bone club and cleaver

---

data/json/furniture_and_terrain/furniture-appliances.json

I fucked up when creating the ceiling lamps.
Fixed the id according to convention.
Hopefully since the PR of the ceiling lamps is pretty new not much people have used the bad one. In case some people have they can turn them off and the game loads fine.

fix: Change the id of the ceiling lamp when it has no power according to convention.

---

data/json/recipes/weapon/bashing.json

Bone clubs were flavored as having a wooden haft, recipe didn't reflect that.
Added `wood_structural_small` to recipe components.
Screm.

fix: bone club recipe requires wood for the haft

---

data/json/items/containers.json
data/json/professions.json
data/json/recipes/armor/feet.json
data/json/recipes/armor/hands.json
data/json/recipes/other/materials.json
data/json/recipes/other/tools.json

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5722 made rubber gloves actually useful for something, so went ahead and added recipes for some basic rubber items since sometime before that I added a recipe for rubber chunks.
1. Added a recipe for rubber hose, at 1 level of fabrication higher than leather hoses but no subskills.
2. Added recipes for rubber boots and rubber gloves, went with a level lower than the above recipe.
3. Misc: Set balloons to be twice the weight of condoms (generally larger) and added them to recipe for rubber chunks.
4. Misc: Added rubber gloves to electrician profession.
1. Adding tailoring skill as a sub-requirement for rubber boots and gloves?
2. Adding work gloves or fire gauntlets to electrical uninstall crafting requirement?
3. Added electronics …

feat(balance): add recipes for rubber gloves, boots, and hoses

---

data/json/items/armor/misc.json

Funny idea that came about because messing with rubber salvaging and because @EkarusRyndren keeps talking about SS13 in my DMs and I need to torment them with clown memes. Right as I started to copypaste the use action for bicycle horns I thought to check DDA and found they did this already earlier this year.
Converted clown nose from `ARMOR` to `TOOL_ARMOR`, added noise action to clown noses. Ended up copying the description change from the DDA implementation but the use action is mostly a straight copy of the bicycle horn with lower volume (and had already picked out 10 volume for it even before I saw DDA's implementation picked that volume too).
1. Copying the DDA PR wholesale. I figured to play it safe and convert to `TOOL_ARMOR` just in case keeping it as armor might break something. …

feat: add noise use action to clown noses

---

src/bodypart.cpp
src/cata_variant.cpp
src/cata_variant.h
src/character.cpp
src/character.h
src/creature.h
src/iexamine.cpp
src/iuse_actor.h
src/magic.cpp
src/map_field.cpp
src/npc.cpp
src/panels.cpp
src/pldata.h
src/savegame_json.cpp

Creep towards limb addition/removal by removing hardcoded limb counts.
`hp_part` is an enum for parts that have hp. We have something better: JSON-ized parts that have "main part" set to themselves. I replaced last uses of `hp_part` enum with said main parts.
Also removed unused `healed_24h` field.
* Sleep regen works
* Bandaging/disinfecting works
* Bandaging/disinfecting applies limb, head and torso bonuses correctly
* Bit hard to test, you need to fiddle with first aid skill and high healing items until head has lower bonus than torso/limbs and torso has higher bonus than head/limbs
* Autodoc applies splints correctly
* Player HP is displayed correctly on sidebar

refactor: Remove `hp_part` enum

---

data/json/items/gun/shot.json

Smol easy fix pointed out in the discord.
Converted gatling shotgun to use the fire mode JSON all other select-fire guns use instead of the old-as-fuck `burst` property.
Removing it from the code entirely and making modders cry.

fix: don't use ancient legacy `burst` property with gatling shotgun

---

data/json/items/ammo.json

So it turns out welding gas is actually set to count as a liquid for a reason.
Set hyrdogen to count as a liquid, fixing issues where crafting it would skip liquid handling behavior and dump it loose in your inventory, rendering it unusable.
Delving into the code to fix why gases aren't triggering liquid handling but weh.
Used my eyes.

fix: set hydrogen to gas like other craftable gases

---

data/json/items/armor/belts.json
data/json/recipes/armor/other.json

This fixes some goofs with the survivor belt item and recipe.
1. Removed the redundant extra tool belt from the recipe. The ability to use a toolbelt as an alternative to the other pouch items was kept in though.
2. Updated description to account for how it now holds multiple tools and not just a single knife.
Also allowing it to holster pistols for the lulz?

fix: remove extra tool belt from survivor belt recipe, update description

---

data/json/recipes/food/other.json

Corn oil is a common option for biodiesel, with vegetable cooking oil obviously being the most logical role it'd fit into.
Added corn to vegetable cooking oil recipe, at a rate of 3 units of corn per 1 unit of oil. Roughly 3.3% yield by mass. Fumbling with google-fu gave me values ranging from 0.5 all the way up to 1.9 pounds of corn oil per bushel of corn (56 pounds, even as an American I don't fuckin' get it either man), which is a fucking wacky range of 0.8% to 3.3%, so I figured let the player have a yield on the high end since if you're using cooking oil for anything en mass you're going to be making a fuckload of it, 64 oil and thus 192 corn just for a single liter of biodiesel for example (not counting the much smaller amount of corn going into the vodka making 100 units of …

feat(balance): allow making vegetable cooking oil from corn

---

data/json/professions.json
data/json/scenarios.json

This adds a profession that serves to showcase some of the newer utility bionics in the game related to bionic and grid mechanics, as well as building on how zombie scientists can potentially have bionics on them.
1. Added Bionic Lab-Tech profession, which builds on the generic lab technician and adds high-level skills to fit a cyborg-focused role, together with a suite of CBMs fitting for medical and electrical work (notably including surgical scalpels and electrosense), and getting the augmentation associate's autodoc trait. Double the point cost of augmentation associate.
2. Added new profession to lab patient/staff scenarios, mine scenario, and overrun scenario. Basically all scenarios that explicitly add the regular lab-tech. Also added to High Tech, Low Life since that allows most …

feat(content): bionic lab-tech profession

---

src/magic_spell_effect.cpp
src/npcmove.cpp

Fix #5648
* Give NPC an A7 laser rifle and full UPS
* Spawn a zombie
* Wait a turn so that NPC shoots the zombie
Bundled a `const` in non-relevant part of code, to fix a warning. Will remove if it causes trouble.

fix: Fix NPCs causing a crash when using a laser gun

---

data/json/recipes/other/other.json

Added in book learn for the oven
Book learn was missing from the oven recipe. Bug report requested it be learnable by books. Bug report here. 
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5770
Adds in recipe from books instead of learned by disassembly only. 
None
Json edit and launch to confirm it does not error out.

fix: Update other.json to add in recipe for oven. 

---

data/json/recipes/food/meat.json

Added glass jar and 3 liter glass jar to appropriate recipes for blood soup.
Before, jarred blood soup produced a free jar, since its recipes did not require one.
Jarred blood soup now requires the appropriate jar to craft.

fix(content): Blood Soup No Longer Produces Free Jars

---

data/json/harvest.json

This fixes yet more harvest entries that were missing blood.
1. Added animal blood to all the fish harvest entries, and mutant blood to `mutant_fish` and `mutant_fish_large`. Shellfish and lobster were left untouched since we don't have an item for wacky hemolyph-type stuff yet.
2. Added mutant blood to a bunch of mutant human harvest entries that were lacking them.
3. `mammal_large_chitin` was also missing mutie blood, fixed that.
4. Since we went ahead and already added blood to super-tiny mammals and now fish, added it to `bird_tiny` too, and also fixed `bird_large` lacking mutant blood.
5. `inucubator_mammal` given blood since it isn't dead yet, but I gave it a special exception to the normal ratio and let it have half the amount that's normal.
Skeletal harvest entries were left alone …

fix: more harvest entries have blood

---

data/json/vehicleparts/turret.json

It seems that with the rebalance of crossbows, the repeating crossbow turret wasn't changed from SMGs to rifles. As currently the repeating crossbow uses rifle skill.
Changed SMG skill to rifle skill.

fix(balance): make Repeating crossbow turret use `rifle` skill

---

data/mods/CRT_EXPANSION/items/crt_gunmods.json

chore: Smol grammar fixes  for CRIT mod

---

src/monattack.cpp

was kicked by a prototype robot, but damage message shows "zombie kicks".

fix: Specified the kicker name

---

data/json/construction.json
data/json/furniture_and_terrain/furniture-surfaces.json
data/json/items/vehicle/tables.json
data/json/recipes/other/vehicles.json
data/json/vehicleparts/vehicle_parts.json

Robotic crafting bench for vehicle, furniture, as a construction, it's recipe and item itself
Faster crafting bench, high tech thing locked behind a decent skill check. 
Tested offline and it worked
Playtest just in case and add a proper lookss like field since this one doesn't seem to work

feat(content): Robotic crafting bench 

---

data/json/recipes/chem/chemicals.json
data/json/recipes/weapon/explosive.json

Filling in PR template for the OP since they didn't do any of it.
PR adds alternative recipe for hydrogen peroxide, and a recipe for C4 explosives.
1. Alternative hydrogen peroxide added, primarily using zinc or copper plus sulfuric acid.
2. Recipe for C4 requiring RDX and motor oil, plus some electronic scrap.
None provided by PR OP, will provide in a comment review below.
Tests don't explode.
Post scriptum : I hate github. 
This PR info provided by Chaosvolt due to info not being provided but requested by Scarf.

feat: Craftable c4 and hydrogen peroxide

---

doc/src/content/docs/en/dev/guides/building/makefile.md

Updates docs with instructions on how to get nightly android builds working on a fork.

docs: Add documentation for building an APK in a fork

---

android/app/src/main/res/values/colors.xml

d9fde31542acc606f27cdb547663cc29b7404e2c introduced Release build errors by introducing a reference to
the color 'background_black', which is set in experimental builds but not release builds.

fix: Android release builds broken due to missing color

---

doc/src/content/docs/en/mod/json/reference/creatures/magic.md

fix wrong entry in docs added by #5915
write how it actually works

docs: fix documentation for `ABOVEGROUND` enchantment condition

---

data/json/mapgen/lumbermill.json

nerf gas pump
nerfs the amount of gas found at the lumberyards
see https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5921#issuecomment-2585591139
👍

feat(balance): Reduce gas found at lumberyard

---

data/json/overmap/overmap_special/specials.json

Adds "GLOBALLY_UNIQUE" to Hub01

feat(balance): add `GLOBALLY_UNIQUE` to Hub01

---

data/json/recipes/other/other.json
data/json/recipes/other/tools.json

I don't see why you shouldn't craft this stuff
Craftable ceramic dishes, scrub brushes, kettles, drinking glasses
Load the game
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/207
Well I guess we're doing an extra flavor items mod later, since most of them got axed.

feat(content): Craft kitchen stuff

---

data/json/recipes/other/vehicles.json

Plastic and carbon fiber vehicle frames now take 30 plastic chunks and 200 carbon fiber filaments to make respectively, and plastic frames now have a batch time factor of 60%. This should hopefully make them once again a cheap, lightweight option instead of steel frames.
Plastic and carbon fiber frames are relatively expensive and not worth using most of the time compared to steel frames due to the long crafting time.
Plastic vehicle frames and carbon fiber frames now both require less material to craft and have a bulk crafting bonus of 60%, with the former being 30 chunks of plastic for plastic frames and 200 pieces of carbon fiber filament for carbon fiber frames.
The changes are made entirely in json and so shouldn't cause any errors. That said, balance testing and suggestions are more …

feat(balance): Plastic, Carbon Fiber Vehicle Frame Buff

---

data/json/flags.json

chore: fix typo in `FIREWOOD` flag

---

.github/pull_request_template.md

More disagreement has ensued over "purpose of change" being potentially too vague vs "Why should this PR be merged?" being potentially too confrontational. Figured instead of risking it being fixed one PR at a time I can just set aside a draft PR.
Added proposed summaries to `Purpose of change` and `Describe the solution` that add a bit more context for what their purpose is (to avoid encouraging the default assumption they're near-identical sections that just translate to "The What" and "The What But In More Words") without making things any more long-winded than nessecary.
Opened this PR and technically failed the test immediately, as it seems changes to the template don't apply to the same they're being made in. I can only assume any changes we decide upon won't take effect until the …

docs: additional clarification for PR template

---

data/json/items/tool/deployable.json

fix #5985 
Add missing flags
Un//fold specified things

fix: prevent folded vehicle item duplication on unfold

---

data/json/items/resources/plastic.json

it's pretty self-explanatory
This little JSON change should not break anything

fix: change plastic sheet category to plastic scrap

---

src/panels.cpp

Same with the compass, the Armor display was quite informative, especially how good your armor still works, but it was too "big" for tablet users.
Creating a new way to show armor. It will just show the health of the armor at the part of the body.
small screen:

feat(UI): compact armor display

---

data/json/recipes/food/other.json

Was pointed out in BN discord that salt water having to be boiled down in batches of 10 each is absolutely goofy and makes it hard to make salt in small batches.
Reduced salt-from-salt-water recipe to make 10 salt at a time instead of 100. Components reduced from 10 salt water/50 saline to 1 salt water or 5 saline. Time reduced from 90 minutes to 10 minutes (batch time savings will help make up for this, plus compare clean water being 5 minutes), also upped the amount of boiling charges required from 3 to 5 since clean water only demanded 3 too.
Scremaing.
2. Load-tested in compiled test build, confirmed it says it makes 10 salt at a time.
For comparison, making 10 batches of salt takes 56 minutes now instead of 90 even with the bump …

feat(balance): make salt from salt water in small batches

---

data/json/items/fake.json

Add siphon ability to `Integrated Toolset`
Adds the line `[ "HOSE", 1 ],` to the fake item `toolset`.
I considered adding this to the `Extended Toolset`, however considering how many other abilities are already on the `Integrated Toolset` adding a siphon isn't out of place.
Added this line to local copy of game, and verified that the character is now able to siphon liquids
Go Go Gadget Siphon!

feat: Add siphon ability to `Integrated Toolset`

---

data/json/itemgroups/Weapons_Mods_Ammo/gunmod.json
data/json/items/gun/shot.json
data/json/items/gunmod/accessories.json
data/json/items/gunmod/barrel.json
data/json/items/gunmod/grip.json
data/json/items/gunmod/mechanism.json
data/json/items/gunmod/muzzle.json
data/json/items/gunmod/rail.json
data/json/items/gunmod/stock.json
data/mods/CRT_EXPANSION/items/crt_gunmods.json
data/mods/Magical_Nights/items/enchanted/enchanted_gunmods.json
tests/ranged_burst_balance_test.cpp

This adjusts values of various gunmods to improve performance of some underwhelming stat modifiers.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6071 hopefully
1. Rounded a lot of small handling modifiers up to nearest multiple of 5 to make them have a more noticable impact on recoil.
2. Loudness penalties for gunmods like shortened barrel, muzzle brake, etc given a sanity-checking and beefed up to ber consistent with how much more volume guns tend to deal in.
3. Range modifier for the MP5 suppressor made enough to actually notice by rounding up to 5.
4. Dispersion modifiers have been greatly beefed up, as many of the values simply were not balanced with the sort of high dispersion that most weapons have these days.
5. Reworked the breacher grip to make a bit more sense, …

feat(balance): additional rebalancing for gunmods

---

data/json/items/generic/currency.json

Another lil category fix.
Moved faction currency from "other" to "valuables"
Screm
Ported change over to playthrough build and load-tested.

fix: faction currency goes in `valuables` item category

---

src/magic_enchantment.cpp

- I _really_ don't like those warnings in #6111 , and if the compiler actually does optimize it away it will break a lot of shit.
- Checks that the reference is positive rather than negative.
- Shouldn't crash in the same circumstances as #6111.

refactor: `process_relic` logic refactor

---

src/character.cpp
src/game_inventory.cpp

[may cause performance penalty due to raw string construction on comparison; recommended to use STATIC or static const declaration](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6125#issuecomment-2679966197)

refactor: UPS checks use static strings

---

src/player_activity.cpp

Fixes: #6144
Check if target actually exists
Check every piece of code that may put nullptr inside `targets` vector
Compile, start, try to reproduce the bug

fix: invalid safe reference

---

data/json/recipes/food/meat.json

Needing specifically plastic funnels for sausage casings seemed a tad restrictive, especially innawoods.
Set the sausage casing recipe to permit using all standard funnels as alternative tools to plastic funnels.
Implementing this by marking the relevant funnels with `sub`, would require changing affected funnels from type `GENERIC` to `TOOL`.

feat(balance): allow using other funnels for sausage casing recipe

---

data/json/player_activities.json
src/activity_actor.cpp
src/activity_actor.h
src/activity_actor_definitions.h
src/activity_handlers.cpp
src/activity_handlers.h
src/activity_item_handling.cpp
src/construction.cpp
src/construction.h
src/iexamine.cpp
src/player_activity.cpp

- Actors are neat, handlers are not;
- #3271.
- Compile;
- Run;
- Construct smth;
- Deconstruct smth.
- Migrated to actor with slight adjustments to fit in actor system;
- Changed target to be an abs tripoint explicitly;
- Still uses ugly "reduce total time to simulate assistance" thing, but that's a topic for other PR.

refactor: migrate construction to actors

---

data/json/construction.json
data/json/construction_group.json
data/json/furniture_and_terrain/furniture-appliances.json
data/json/items/fake.json
data/json/items/vehicle/tables.json
data/json/recipes/other/other.json

Cool station to buff ur butchery and etc, even if u didn't find autonomous scalpels yet
Build, start, install, check it works.

feat(balance): advanced butchering station

---

data/json/furniture_and_terrain/terrain-floors-indoor.json
data/json/furniture_and_terrain/terrain-floors-outdoors.json

Eelvator is a part of several buildings, especially multi-Z level parking lot, yet for some reason it's not considered as a road, while all other tiles are.
Give elevator a "ROAD" flag, so it's not considered offroad
Create a variant of elevator that is considered "ROAD" and place it to specific lcoations
- Compile
- Start
- Check vehicles that are ok with road but too heavy for offroad to work

feat(balance): elevator is a road

---

data/json/itemgroups/Locations_MapExtras/locations.json

swap icon spawn for money_bundle
resolves #4748
I opened the above issue after finding an icon and reading its description. I assumed the currency being in game meant the faction could also spawn.
Since I lack the skill and knowledge on how to make map special spawn and anything related to npcs I opted to swap the icon currency in the church loot table for money bundle. Probability wasn't changed.
Replace icon with merch since both are post apocalypse currencies. 
Modified location.json, follow steps 1 and 2 found in how to reproduce in #4748. Teleported to church and checked if there was any money bundle (which wasn't in the item spawn group prior to modifying locations.json).

fix: swap currency of unused faction for money bundle

---

data/json/recipes/other/other.json

Sarcophagus access code requires hackpro and laptop/control laptop(CL) as a tool, which makes sense, BUT CL presumingly(based on recipe) already contains hackpro.
Let it requier either hackpro or CL
- Compile
- Start
- Check recipe

feat(balance): make sarcophagus access code optainable via control laptop

---

data/json/items/tool/deployable.json
data/json/items/tool/shelters.json

fix #6191
Add missing flags
- Compile
- Start
- Check affected items

fix: item duplication on furniture deploy

---

src/iuse.cpp

- Cable is unable to process connection if u somehow disconnect 1st end and manage to keep second end connected and then coonect first end;
- Remove code duplication
Process connections after any of those is done
- Testing all possible connection variants;
- Testing all possible disconnection variants:
- Manual disconnection(Activation);
- Over-extension;
- Moving vehicles;
- Deconstructing cable connector;
- Dropping and/or dragging;

fix: cable unable to handle connections made in certain sequence

---

data/json/bionics.json
data/json/itemgroups/bionics.json
data/json/items/bionics.json
src/active_tile_data_def.h
src/bionics.cpp
src/bionics.h
src/character.h

A better, more rare and uncraftable version of cable charger, for late-game charging
Add json and some code adjustments
- Compile;
- Start;
- Check power draw from source is correct and power add to char is correct;
- Check cable charger 2 is correctly upgrading cable charger 1;

feat: Cable Charger mk II CBM

---

data/json/furniture_and_terrain/furniture-appliances.json

Turned off industrial freezer autostarts if there is enough energy, due to copy-from base IF
Override `active` json field
- Start
- Disable IF
- Check it didn't restart for no reason

fix: remove industrial freezer(off) autostart

---

data/json/items/ammo/40x46mm.json
data/json/items/ammo/40x53mm.json

I noticed that 40mm grenades were remarkably bulky, and some very basic googling confirmed that the stack size being set to only 1 seems to be an error. IRL they're about 100 mm long, and the volume of a cylinder that length with 40mm diameter would be just close enough to 125m...
1. Set volume of of 40x46mm abstract to 125 ml, being close to above value.
2. Set volume of 40x53mm abstract to 150 ml, also not far from a raw cylinder value matching the dimensions of 40x53mm.
Using `stack_size` fuckery instead, which would make the math harder to follow.
1. Checked affected syntax and lint errors.
2. Did math :<
Weights seem to be accurate based on info I could find.
40x46mm sauce: https://www.inetres.com/gp/military/infantry/grenade/40mm_ammo.html
40x53mm sauce: …

feat(balance): sanity-check volume of 40mm ammo

---

data/json/items/tool/workshop.json
data/json/recipes/other/tools.json

I keep raiding gun stores and can't find a gunsmith kit for the life of me.
Adds a crafting recipe for gunsmith kit. Also adjusts its volume and weight based on components used.
Playing a melee build.
I meant to add a hand press to the kit but that tool does not depend on a quality, instead it's manually inserted into every single ammo crafting recipe there is. That broke things.

feat: Add crafting recipe for gunsmith kit

---

data/json/uncraft/armor.json
data/json/uncraft/generic.json

Allows recovery of basic materials from items which couldn't be disassembled or cut up.
Add entries for relevant items to data/json/uncraft/.
Make matchbook work in a way similar to cigarette pack by adding a match item separate from the matchbook ensuring players can't loose out on charges. Except matchbooks are normally used to light matches so might require to either allow matches to be used even without anything to light them or new flag/tool quality shenanigans.
Loaded into a world with a default survivor. Spawned relevant items and tried to disassemble them.
Will remove matchbook's uncraft if wasting matchbooks charges by disassembling them becomes an issue.

feat: add ability to disassemble a few paper/carboard items

---

data/json/recipes/chem/drugs.json

I forgot to add autolearn to it. You can't obtain it from books.
at #6357
fixes le bug xD
putting down the cup

fix: add missing `autolearn` in sizzurp lean recipe

---

data/json/items/comestibles/junkfood.json

fix: Fixes non-fatal error caused by redefining default charge amount on cheese spread

---

src/activity_speed.cpp

fixes #6370
Clear stats vector before putting new vals
Use provided savefile

fix: activity speed stat overflow

---

doc/src/content/docs/en/mod/json/reference/items/item_creation.md

PR created on behalf of @Patternseeker to split #6362 
cherry picked from commit f9e870521b787a94eab4aebd9e947dd526030546 in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6362

docs: document gun `handling` stat

---

data/json/items/tool/toiletries.json

"cutting": 1
Fixes the tool quality on razor blade.

feat(balance): add fine cutting tool quality to razor blade

---

doc/src/content/docs/en/mod/lua/reference/lua.md

forgor to run docs command in #6439 
run deno task doc
automate it

docs: add traps lua API

---

data/json/items/gun/223.json

How do you fit this
Into this
For context the 100 round beta c-mag drum does fit in an M249

feat(balance): make M249 unable to load snail mags and 150 round mags

---

doc/src/content/docs/en/mod/lua/reference/lua.md

docs: update lua API for FILTHY

---

doc/src/content/docs/en/dev/guides/building/makefile.md

Small things I ran into while installing
* Update mxe target with `sqlite` dependency
* "cross-compiling"->"cross-compile" for consistency
* Add documentation for `BACKTRACE` make flag
`PCH=0` is still used in the cross-compile for windows command, but I couldn't find what that does.
<!--
please remove sections irrelevant to this PR.

docs: update MXE targets for windows cross-compile

---

doc/src/content/docs/en/dev/guides/building/cmake.md

I recently did a fresh install on WSL, figured I'd document it.
* Add section for using WSL. 
A bunch of misc. fixes:
* Fix ubuntu package names
* bunch of `freetype` -> `libfreetype-dev`
* Remove `glibc`, comes installed
* Add `gettext`
* Remove shell prompt characters for easier copy-pasting
* Use `cmake` everywhere instead of `make`
* Standardize to NOT `cd` into `build` directory. Having a mix of both was unclear which commands would work when.
Fresh ubuntu 24 install, fresh cataclysm build via cmake.
<!--
please remove sections irrelevant to this PR.

docs: Add WSL section for cmake

---

doc/src/content/docs/en/mod/json/reference/items/item_creation.md

No documentation makes me angry
Fixes the problem
Escalation of violence
Tests

docs: add cast_spell documentation

---

doc/src/content/docs/en/mod/json/reference/items/json_inheritance.md

Clarify copy-from behavior for replacing items
I had a question about this that wasn't explicitly in the docs.
Update docs.

docs: Update json_inheritance.md

---

.github/labeler.yml

make them stand out in PRs since we'll focus on Lua more

ci: label Lua PRs

---

.github/semantic.yml
.github/workflows/autofix.yml
doc/src/assets/semantic.json

fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6531
- autofix lua files
- do not stage changes in `.github`
- update semantic.yml

ci: autofix cleanups

---

data/json/recipes/food/other.json

Processing wild rice into dried rice took a long time and could only be done using smaller-scale tools.
Added in a new recipe to make dried rice, using the food processor.

feat(balance): dry rice food processor crafting recipe

---

data/json/items/comestibles/offal_dishes.json

I'm livid over this liver's listless use of my lexicon!

fix: typo in foie gras description

---

data/json/effects.json
tests/char_healing_test.cpp

One minor thing I only just recently noticed is the head is set to heal much more slowly than the torso, which may by somewhat magnified by the recent tweak to healing rates in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6663
Increased the head healing rate of bandaged and disinfected effects from 50 to 75, matching what torso healing rate was set to.
Screm.
2. Ported JSON change to playthrough build and slept.
3. Result was less fuckly than before I changed things.
Head was still coming out noticably lower in my tests in my actual playthrough, but in a fresh save test with all HP values set to 1 every part seemed to be healing up about the same.
I might need to fix the healing test too, weh...

feat(balance): set head healing from bandages/disinfectant to match torso

---

data/json/uncraft/generic.json

They didn't have any
Tested couple dozen different ones I had at hand, via mod

feat: add uncraft recipes for tiaras, cufflinks, pendant necklaces

---

data/mods/No_Reviving/modinfo.json

Feature parity for zombie necros and skeleton necros.
Adds `mon_skeleton_necro` to the blacklist
Removing the base zombie necromancer from the blacklist. I see this mod as a QOL and not a flat "remove EVERY revival mechanic" mod, as I feel that removes a challenging enemy from the game I'd enjoy playing against, but I would not enjoy pulping every body. This isn't my mod or the likely intention of the mod however, so not gonna do that in this PR unless others feel the same.
Changed the blacklist, load tested in a world. Spawned and fought a skeleton necromancer. Admittedly I didn't wait around long other than skipping time and checking streets for them, but I figure since I've never seen a normal zombie necromancer in my playthroughs with this mod it is functioning as expected now.

feat(mods/no_reviving_zombies): add `skeleton_necro`

---

data/json/items/comestibles/alcohol.json
data/json/recipes/food/drinks.json

It's the modern age, why shouldn't we be able to make irish coffee using the latest coffee brewing technology?
Introduce a more stimulating type of irish coffee which, instead of normal coffee, is made with atomic coffee.
The values of atomic irish coffee were determined by the differences between irish coffee and sweet coffee milk. Then, that logic was applied to sweet atomic coffee milk to get atomic irish coffee. The price was guessed to probably be a dollar or two more than the original irish coffee (was it even legal to serve atomic coffee in resturants and bars?). The postapoc price was determined using the same math of "(irish coffee - sweet coffee milk) + sweet atomic coffee milk= atomic irish coffee".
Start going back to AA
- Both can be crafted, with the atomic one instead …

feat: atomic irish coffee

---

data/json/items/comestibles/alcohol.json

fix: typo - atomic irish coffe

---

src/map.cpp

So, I was gonna reduce the amount of redundant code used by cover mechanics so it no longer has two separate if statements that do the exact same thing except for furniture vs terrain, but then I realized this does have a single use: if you slap cover-providing furniture on top of cover-providing terrain, the previous behavior of always prioritizing furniture over terrain can cause some wacky behavior.
For example, if you somehow get furniture with a cover save chance below 100% embedded in a wall, you can fire through a wall that normally intercepts your shots completely. Sadly, the only elegant fix I could think of for this is ultimately to use the "check furniture and terrain separately" but make it two separate if statements instead of if/else shenanigans.
In map.cpp, tweaked …

feat(balance): check cover for furniture and terrain independently if both are on the same tile

---

data/raw/generate_types.lua
lua_annotations.lua

no more those random diffs with sorting order slightly changed!

feat: more specific lua annotation sorting

---

.github/copilot-instructions.md

attempt to make copilot make review better. if used well it could work out as filter for obvious mistakes.
added `copilot-instructions.md`
use other reviewing service
refer to https://copilot-instructions.md/

chore: copilot-instructions.md

---

.github/workflows/matrix.yml
data/mods/Test_for_Lua_hooks/main.lua
data/mods/Test_for_Lua_hooks/modinfo.json
data/mods/Test_for_Lua_hooks/preload.lua
data/raw/generate_types.lua
docs/en/dev/reference/cli_options.md
docs/en/mod/lua/reference/lua.md
lua_annotations.lua
src/catalua_bindings.cpp
src/catalua_hooks.cpp
src/monster.cpp

Thanks for #6921 , we can make lua hooks much easier.
`on_mon_death` hook will let you make lua mod more comfortable.
It tracks killed monster and the killer(almost it's you, but just in case), and allows the mod to spawn another monster, to hurt you, even to revive the killed monster ~~(or to trick you into believing it revived)~~!
1. Add `catalua_hooks.h` in `monster.cpp`.
2. `on_mon_death` hook in `monster::die` function.
3. Add `"on_mon_death"` string in `hook_names`.
4. Run `deno task docs:gen`
Punching chickens
Run test lua mod and Be bountied.

feat(mods): `on_mon_death` lua hook

---

.gitignore
.vscode/extensions.json

they're frequently used when developing on vscode.

chore: recommend vscode extensions

---

data/json/recipes/electronic/parts.json

This adds some more options for making solder.
Added silver as an alternative to tin for solder. Also added zinc and bismuth as alternatives to lead in the solder recipe too. Material ratios have been tweaked a bit to account for the different weights to add up to ~100 grams of metal (50 units of solder, 2 grams each, kinda ignoring the weight of the pitch).
Realistically solder tends to be 37-40% lead instead of 50/50, and silver solder is usually like under 5% silver and either the rest is tin or there's some copper added in, but eh.

feat(balance): add alternative materials to solder recipe

---

data/json/items/comestibles/offal_dishes.json

Artificial sausage casings contain meat allergens despite supposedly being made from plastic, because they copy the allergens of regular sausage casings
Explicitly set artificial sausage casings to contain no meat allergens
Letting meat intolerant characters continue to suffer whenever they take a bite out of a veggie sausage?
Checked that artificial sausage casings and veggie sausages made using them do not cause allergic reactions for players with the meat intolerance trait

fix: remove meat allergen from artificial sausage casing

---

data/raw/keybindings/keybindings.json
src/character_display.cpp
src/game_inventory.cpp
src/item_action.cpp

The player can already change their profession name, so I figure allowing the player to change their name isn't too far fetched.
Adds a keybind in the @ menu to change your name.
Adds a message in the log to indicate that you've changed your profession or your name.
Fixes some grammar issues in the '%' and 'T' menu.
Compiled, loaded in, spawned a new player. Opened the @ menu, (had to bind the key myself) bound the key, and then successfully changed my name.

feat(UI): allow player to change their name/nickname
