cataclysmbnteam/Cataclysm-BN

src/construction.cpp, src/construction.h, src/item_factory.cpp
Your changes fix #17449 whereas combined with these also fixes #17443
=> Additional fix

tools/format/format.conf
You need to update the lint rules as although `tools.json` is not in canonical format (`format.pl -qc`) it has no invalid fields (`format.pl -q`)
=> Update lint rules

src/character.cpp, src/map.cpp, src/monattack.cpp, src/monstergenerator.cpp, src/npc.cpp, src/npcmove.cpp, src/pathfinding.cpp, src/pathfinding.h
Fixes #16
Currently only NPCs because climbing code is hardcoded in ugly way. Didn't fix the ugly here, only the issue.
=> Make NPCs pathfind over (and not just around) fences

data/json/recipes/recipe_ammo.json
I presume that the fire source is intended as a means of shaping the various metal parts into ball form, as Wikipedia claims that not doing this would damage the bore. This is consistent with what I understand is the intention behind shaping the bullet in virtually all other types of ammunition.
What is not consistent however is that, unlike cartridge ammo, the recipes don't let you use a hotplate for this purpose.
=> Allow hotplates in blunderbuss shot/slug/flechette crafting

src/item.cpp
Fix https://github.com/CleverRaven/Cataclysm-DDA/issues/38409
Example rings stat effect double, looks like separate bug. Rings effects change when transformed.
=> update relic on item convert

doc/COMPILING/COMPILING-CMAKE.md, doc/COMPILING/COMPILING.md
I've misunderstood part of `COMPLINIG.md` related to languages, .mo's and localization.
So I've edited this doc a bit to help other people understand localization flags.
Also I've changed `OMPILING-CMAKE.md ` just to make it more fancy.
=> Make localization part of doc COMPILING.md clealier

data/json/monsters/turrets.json
Reducing ammo for turrets.
Basically it is fixing that:
https://github.com/CleverRaven/Cataclysm-DDA/issues/38638
https://github.com/CleverRaven/Cataclysm-DDA/pull/33436#issuecomment-527393955
Reduce aturrets ammo to sane ammounts.
Previous version of turrets has around 100 ammo. But for realistic reason ammo count was changed to insane numbers. This PR going to fix that. 
Turrets still going to have around 100 ammo as it was before change. It should be enough to mantain fire and at the same time prevents turret to drop lifetime ammo pile for player.
M2HB autonomous CROWS II .50 BMG ammo: 400 ->90
M240 autonomous CROWS II  7.62 ammo: 1000 -> 120
M249 autonomous CROWS II  5.56 ammo: 1600 ->120
It is exaclly 30 bursts before running out of ammo. I have to compensate turret fire rate with …
=> Reduce ammo for turrets

src/options.cpp
Set UNDEAD_PEOPLE as default tileset
Set Undead People tileset as default since it  has outstanding quality and provides better presentation of BN.
Privide better presentation. Also Inform players that BN has that tileset built in.
Just set default tileset in options.
1) Delete options file (options.json)
2) Start the game
3) UNDEAD_PEOPLE tileset must be selected.
=> Set UNDEAD_PEOPLE as default tileset

src/avatar_action.cpp, src/game.cpp, src/game.h, src/iuse.cpp, src/player.cpp, src/player.h, src/vehicle_use.cpp, tests/reloading_test.cpp
Fix for Unloaded ammo belt doesn't disappear
Bugfixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/49
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/49
Bug happens only if player Unloads ammo belt by using U command (not from inventory). But belt removal was used only for avatar action. Solution is move belt removal to player::unload.
Partially implementing this: https://github.com/CleverRaven/Cataclysm-DDA/pull/40541
Transofrm 
`bool player::unload( item &it)`
to
`bool player::unload( item_location loc )`
Do essesary modfications to all references
Add "MAG_DESTROY" item removal to magazine handling in
`bool player::unload( item_location loc )`
Remove "MAG_DESTROY" removal from
`avatar_action::unload( avatar &you )`
1) Spawn 5.56x45mm ammo belt
2) Unload it from …
=> Fix for Unloaded ammo belt doesn't disappear

src/trapfunc.cpp
Fix (workaround) for Landmine does almost no damage
Bugfixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/60
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/60
Connected issue:
https://github.com/CleverRaven/Cataclysm-DDA/issues/37724
>I believe you should check function trapfunc::landmine() at src/trapfunc.cpp:L605
It clearly uses same explosion() function but uses preset values so I think that landmine probably does not use JSON set values at all.
Confirmed. Landmine triggers:
```
bool trapfunc::landmine( const tripoint &p, Creature *c, item * )
{
// tiny animals are too light to trigger land mines
if( c != nullptr && c->get_size() == MS_TINY ) {
return false;
}
if( c != nullptr ) {
c->add_msg_player_or_npc( m_bad, _( "You trigger a land mine!" ),
_( "<npcname> …
```
=> Fix (workaround) for Landmine does almost no damage

data/json/vehicle_groups.json
Restore atomic car and bubble car.
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/59#issuecomment-694273374
Restore atomic car and bubble car.
SUMMARY: [Content] "[Restore atomic car and bubble car]"
Restoring removed content. Bubble car was restored as well, since it is bacically on the same level of  atomic car.
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/59#issuecomment-694273374
Atomic cars and buble cars were still in game jsons and was not obsoleted. I've just needed to add this cars back to spawn.
Reactors appears operational. Reloading via plutonium cells working.
Game loads correctly
=> Restore atomic car and bubble car

src/item.cpp
Fix Mess kit cannot be used for boiling when loaded with batteries
SUMMARY: Bugfix "[Fix Mess kit cannot be used for boiling when loaded with batteries]"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/75
Before
```
if( id == quality_id( "BOIL" ) && !( contents.empty() ||
( is_tool() && !has_item_with( boil_filter ) ) ) ) {
return INT_MIN;
}
```
After
```
if( id == quality_id( "BOIL" ) && ( !contents.empty() ||
( is_tool() && !has_item_with( boil_filter ) ) ) ) {
return INT_MIN;
}
```
Proper logic is 
```
if (Can Boil  AND ( It is not empty OR (It is tool AND  It contains something else rather then its ammo) ) )
then
Do not Boil
```
Maybe it was just a typo with "!"
Looks like
`has_item_with( boil_filter )`
was ok
This case could be potentially dropped for QOL measures. We …
=> Fix Mess kit cannot be used for boiling when loaded with batteries

data/json/professions.json, src/activity_handlers.cpp, src/iexamine.cpp, src/iuse_actor.cpp
Lockpick skill removed. Will cause debugmsgs if mods use it.
Numbers are not tested and need tweaking. More precisely, an idea of how hard should lockpicking be.
=> Remove lockpicking skill

data/json/monster_attacks.json, data/json/monstergroups/zombies.json, data/json/monsters/zed_medical.json
A new tree of zombie evolution:
* Nurse - walks fast, but attacks (injects) once per ~1.9 turn, causing low armor-piercing damage, light bleeding and poison. Can't bash, no armor except vs acid. Can't smell (nurse is too "mechanical" mentally, surgeon has no face).
* Surgeon - as nurse, but better. Injects once per turn, then (once per 20 turns) scratches for high damage and some bleed but armor is doubled against this attack.
* Vivisector - Surgeon but with stats and attacks boosted, zero movecost leap added, inject having stronger poison, and light stab armor.
Overall they are closer to support than main damage dealing force.
Bad armor and no dodge means even a mediocre combatant may be able to kill one in melee (8/8/8/8+3 skills+knife spear+hoodie/jeans was able to kill a Vivisector), …
=> [CR]Medical zombies

src/options.cpp
This is mostly for balancing purposes. As in, "this is how fast the game should go".
At 91 day season and 400% evolution time (default), you can easily get through the goal-filled phase of the game to the "mindless exploring out of curiosity" phase before seeing the season change or the zombies evolve to the final stage.
=> [CR]Reduce start day and season length

src/item.cpp
SUMMARY: Interface "Display contained items like 'water (plastic bottle)' instead of 'plastic bottle of water'"
The way item names are displayed currently puts the container of an item before the contained item. When the display is relatively narrow (e.g., you have low vision like me, so you use huge fonts), this leaves relatively few characters for the contained item in contexts where item names are truncated. Generally, the content is more important than the container.
The container now comes after the content in item names. For plurals, this works out as "2 clean water (plastic bottles)".
It might be nice to use this form for lists (like the inventory or the `X` command) and the old, more prose-like form for running text (like the message log). But I don't know if Cata already has any …
=> Display contained items like "water (plastic bottle)" instead of "plastic bottle of water"

data/json/items/armor/coats.json
(Copy of https://github.com/CleverRaven/Cataclysm-DDA/pull/44553)
SUMMARY: Balance "Rename 'housecoat' to 'bathrobe' and add some description."
"Bathrobe" is the much more common term, judging by Google Ngrams and Google Trends.
=> Rename "housecoat" to "bathrobe" and add some description.

src/npctrade.cpp
Fix Item duping via NPC trading
SUMMARY: Bugfix "Fix Item duping via NPC trading"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/95
Added filter to check that we are removing thing from same stack.
1.  Find an NPC that you can trade items with
2.   Acquire at least two similar containers with different contents (e.g. an empty and full gun magazine, or two plastic bottles with different liquids inside)
3.   In the NPC trading window, select any container except the first that appears in the list, and give it to the NPC
4.   You will lose the correct container in the list.
**Save provied:**
[Уорн.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5356752/default.zip)
=> Fix Item duping via NPC trading

src/item_factory.cpp
Refactor Extending ammo effects
Using solution from DDA.: https://github.com/CleverRaven/Cataclysm-DDA/pull/44750
It is much shorter.
Assign is working!
SUMMARY: Bugfixes "Extending ammo effects"
Refactor https://github.com/cataclysmbnteam/Cataclysm-BN/pull/87
Adding support for "extend" and "delete" for ammo effects.
Now uisng assign.
Used https://github.com/CleverRaven/Cataclysm-DDA/pull/44750 as example
Waiting for https://github.com/CleverRaven/Cataclysm-DDA/issues/36851 to resolve. But it may take months/years.
1) Spawn Milkor MGL / Mark 19
2) Shot with greande launcher
3) Grenade must explode.
=> Refactor Extend ammo effects

src/bodypart.h, src/character.cpp, src/effect.h
Effect map is an unordered map (of unordered maps), meaning that adding new effect can invalidate iterators to existing ones.
This can cause crashes when adding an effect during effect processing, as effect processing iterates over all effects and some effects add new effects.
The simplest fix is to simply change both maps to ordered ones, which may be slower (could use a test).
According to https://stackoverflow.com/questions/6438086/iterator-invalidation-rules references to `unordered_map` elements should not be invalidated by inserting new elements, which hints at a possible different solution.
=> Workaround for effect-related crash

data/json/mapgen/bus_station.json, data/json/mapgen/campground.json, data/json/mapgen/campground_npc.json, data/json/mapgen/construction_site.json, data/json/mapgen/daycare.json, data/json/mapgen/farm_dairy.json, data/json/mapgen/jewel_store.json, data/json/mapgen/lot_empty_commercial.json, data/json/mapgen/park_skate.json, data/json/mapgen/pizza_parlor.json, data/json/mapgen/post_office.json, data/json/mapgen/public_works.json, data/json/mapgen/school_1.json, data/json/mapgen/ws_biker_dump.json
SUMMARY: Balance "Make vehicles outside of garages and showrooms slightly damaged"
There were a few places with completely intact vehicles where it didn't make any sense lore- or gameplay-wise. The worst offender was brand new Luxury RV in a campground surrounded by many half-broken cars and vans.
Make all previously intact vehicles that aren't protected from elements (i.e. not in showrooms or otherwise enclosed buildings) slightly damaged.
There are two locations that I wasn't sure what to do with:
* Parking garage - is it enclosed enough to warrant intact vehicles? It's easy to get into and there are rarely many zombies around, making it a very easy way to get mostly unscathed vehicle once you smash through security system.
* `lab/lab_surface/lab_surface_big_*` locations - I don't think …
=> Make vehicles outside of garages and showrooms slightly damaged

data/json/effects.json, data/json/items/comestibles/med.json, src/activity_handlers.cpp, src/addiction.cpp, src/avatar.cpp, src/character.cpp, src/character.h, src/handle_action.cpp, src/iuse.cpp, src/magic.cpp, src/mutation.cpp, src/npcmove.cpp, src/npctalk.cpp, src/player.cpp, src/player_hardcoded_effects.cpp, src/sdltiles.cpp, src/suffer.cpp, tests/fatigue_test.cpp, tests/npc_talk_test.cpp
* Sleep no longer conserves kcal/water - used to drain at 50% speed. Average character now needs 125 more kcal per day.
* Being just tired no longer drains focus. Other levels drain less: dead tired caps at 75, exhausted 50, massive exhaustion 25
* Made sleep deprivation more stable. Sleeping without a bed will be enough to keep it at bay, sleeping in bed doesn't triple healing time, just 150%.
* Sleep deprivation has lower max cap. 6 days of sleep deprivation results in collapsing.
* Meth lasts 12 hours, stacks up to 24 hours, gives small bonus, negates tiredness. 5 speed, 1 perception. Unhealthy, but not devastating.
* Meth halves sleep deprivation penalties and negates its effects (except collapse).
* Using meth significantly lowers thirst and hunger.
* Nerfed meth addiction. Won't …
=> Sleep, sleep deprivation and meth changes 

data/json/items/gunmod/rail.json
Rail crossbow mod buff
SUMMARY: Rebalance "Rail crossbow mod buff"
Rail crossbow using pre-rebalance values.  Found thanks to **Displeased man**
Looks like it was missed during:
BALANCE Fiddle with archery and crossbow numbers: https://github.com/cataclysmbnteam/Cataclysm-BN/commits/upload?after=dbd818236acb45b6ee6d3c75f98f3e33eceece62+209&branch=upload
Currently it has very low damage but assault rifle accuracy. It has to be changed due to balance concerns.
- Increase damage for rail crossbow. Set it between hand crossbow and usual crossbow
- Increase dispersion. Dispersion for Rail crossbow was very low. Set dispersion between hand crossbow and usual crossbow
None.
1) Spawn and install Rail crossbow weapon mod
2) Observe the stats.
None.
=> Rail crossbow mod buff

data/json/items/melee/swords_and_blades.json
Remove the trench knife's unarmed weapon status
SUMMARY: Rebalance "Remove the trench knife's unarmed weapon status"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/137
Remove UNARMED_WEAPON flag from trench knife. Now it trains melee and piercing weapons.
>Fire-and-Glory 
> Currently the trench knife is an unarmed weapon, meaning:
> A. You can use it in unarmed martial arts, like boxing, karate, etc.
> 
> B. It trains solely the unarmed combat skill.
> 
> Apparently this was an intentional addition to CDDA some years back under the premise that since half of the weapon is a knuckle-duster, you should be able to use it in martial arts like other fist weapons.
> While in real life this makes a certain amount of sense, in game it is nonsensical since if you're punching zombies, …
=> Remove the trench knife's unarmed weapon status

data/raw/keybindings.json, src/animation.cpp, src/game.cpp, src/game.h, src/ranged.cpp
SUMMARY: Interface "Draw lines of fire when aiming vehicle turrets"
1. Fix exploit with automove on CURSES (cherry-picked CleverRaven#40194; required for the next change)
2. Draw approx. lines of fire when aiming vehicle turrets to avoid confusion (CleverRaven#40198 adapted for BN)
3. Prevent aiming cursor on TILES from disappearing when aiming at a tile out of sight (just an annoying visual bug, fixed in mainline as part of CleverRaven#39785)
Cherry-pick and/or adapt code from the mainline
Cherry-picking CleverRaven#39785 for the bugfixes first, but it had accumulated a billion merge conflicts/its own changes by now. I could try to port all of that to BN and make a big PR (3k-4k lines of C++) - if you're willing to have these changes / review them?
(On CURSES) Clicked on tiles at the …
=> Draw lines of fire when aiming vehicle turrets

src/descriptions.cpp
Changes extended look (`x->e` by default) now lists possible item types for results.
Ideally it would list exact item quantities, but that would require flattening a bunch of nested probabilities, which can be non-trivial (how to display "30% chance for 1-3 planks + 50% chance of 1-2 planks"?).
It looks like this:
```
By deconstructing this, you can get:
planks
nails
jackhammer (off)
```
This is good enough to tell at a glance if this item is worth deconstructing for rare ingredients.
=> List deconstruction result types in extended look

data/json/effects.json, src/avatar.cpp, src/bionics.cpp, src/character.cpp, src/character.h, src/character_oracle.cpp, src/consumption.cpp, src/enum_int_operators.h, src/iexamine.cpp, src/mutation.cpp, src/mutation_ui.cpp, src/npc.cpp, src/npcmove.cpp, src/npctalk.cpp, src/player.cpp, src/player_activity.cpp, src/player_display.cpp, src/player_hardcoded_effects.cpp, src/sdltiles.cpp, src/suffer.cpp
Thirst display is a bit weird, with "you're full! are you sure you want to get bloated?" happening with nothing on display.
Also, thirst penalties happened too soon after drinking, which is just tedium, considering the ease of finding water. While the proper solution may be to get rid of thirst altogether, it would be a big change, so a minor fix for now.
Level | Starts at | Was
--- | --- | ---
turgid | -inf | -inf
hydrated | 0 | -60
slaked | gone | -20
no display | 60 | 0
thirsty | 120 | 60
very thirsty | 240 | 120
dehydrated | 480 | 240
parched | 600 | 520
dead | 1200 | 1200
This is more comparable to the old version, where you can drink yourself into -60 thirst.
The meaning of "Hydrated" is now "you probably won't be able to drink more water".
=> Tweak thirst numbers

data/json/enchantments.json, doc/MAGIC.md, src/character.cpp, src/magic_enchantment.cpp, src/magic_enchantment.h, src/mutation.cpp
SUMMARY: Features "Port over ACTIVE enchantment condition" 
First part of my work to port over any post-nested CDDA features that will be useful once I start updating third-party mods to have versions compatible with Bright Nights.
1. Updated magic_enchantment.cpp with changes to enchantment condition checking.
2. Updated magic_enchantment.cpp with changes to enchantment condition enum and is_active definition.
3. Updated character.cpp with changes to the checks for whether an enchanted mutation or bionic is active, updated according to the difference in how BN's code checks for if a CBM is toggled.
4. Updated MAGIC.md with the provided mention of active enchantment condition.
5. Updated ENCH_INVISIBILITY in enchantments.json to use ACTIVE condition.
Since artifact effects still exist in …
=> Port over active enchantment condition

src/character.cpp
SUMMARY: Bugfixes "Fix relic stat changes applying twice"
Second part of the "fix/update magic stuff for later use" series, this time going with a very easy one to port over.
1. Removed redundant line in character.cpp that causes stat changes from relics to double.
Changing the JSON for every relic in the game so their stat changes take into account being applied twice.
1. Compiled and load-tested game.
2. Re-introduced our dear friend the Cube of Shame from the preceding magic-related PR:
```
{
"id": "debug_active_relic_test",
"type": "TOOL",
"name": { "str": "Cube of Shame", "str_pl": "Cubes of Shame" },
"description": "This is a debug-only item for testing relic activation, powered by batteries.  Turn it on to lose intelligence and perception.",
"material": [ "steel" ],
"symbol": ";", …
```
=> Fix relic stat changes applying twice

data/json/effects.json, data/json/flags.json, data/json/items/tool/misc.json, doc/MAGIC.md, src/character.cpp, src/character.h, src/item.cpp, src/item.h, src/magic_enchantment.cpp, src/magic_enchantment.h, src/mutation.cpp, src/newcharacter.cpp
SUMMARY: Features "Port over changes allowing enchantments to grant mutations, more flexible implementation of relic-based clairvoyance."
Adds the code changes from the PRs that allow for enchantments to grant the effects of mutations. This includes the clairvoyance update that was added at the same time as the first PR, and the code changes in the followup PR so that it wasn't pretty much only applying mutation flag effects.
However, instead of tying clairvoyance to a mutation flag, I implemented it via effect flag instead. This is more versatile, not only can any source of enchantments thus provide clairvoyance via granting an effect, but likewise any source of effects (not just enchantments) can do so.
This will likely go well with future plans to JSONize more hardcoded checks to allow …
=> Port over mutations granting effects (and fix)

data/mods/alt_map_key/overmap_terrain.json, data/raw/keybindings.json, src/character.cpp, src/character.h, src/debug_menu.cpp, src/faction.cpp, src/item.cpp, src/map.cpp, src/options.cpp, src/panels.cpp, src/player.cpp, src/player.h, src/player_display.cpp, src/veh_interact.cpp
SUMMARY: Interface "Port various UI improvements from DDA"
Small stuff for UI usability/consistency/correctness
CleverRaven#44720
CleverRaven#40087 (made sure it works with 'no lift requirements' mod)
CleverRaven#40276
CleverRaven#40539
CleverRaven#40784
CleverRaven#40561 (ported only useful stuff)
CleverRaven#41102 (doesn't show up if player has low melee skill)
CleverRaven#41195
CleverRaven#41290
CleverRaven#41407 (weapon name erroneously extends onto next line in BN, so this fix still applies)
Tested each of them briefly to make sure the game doesn't crash and the change actually works.
=> Misc UI changes/fixes from mainline

src/npcmove.cpp
SUMMARY: Bugfixes "Port some NPC AI fixes from DDA"
Port some NPC AI fixes from DDA
Port CleverRaven#42304 and patch an edge case in that PR:
NPCs with 'stick close to me, no matter what' rule do not defend themselves when assigned to guard a position if player moves too far away (threat assessment ignores threats in favor of catching up with the player, but NPC doesn't need to catch up with the player, and that makes them stay in place and ignore enemies).
Repeated tests from the linked PR
Left an NPC with 'stay close, no matter what' rule to guard a position - they fight back when zombies try to eat them.
NPCs do not defend themselves if issued a temporary order (via `C` menu) to forbid engagement and then assigned to guard a position. Not sure what to do about this.
If NPC has a reach …
=> Npc ai fixes

data/json/items/comestibles/med.json, data/json/npcs/TALK_COMMON_OTHER.json, data/json/npcs/talk_tags.json, src/debug_menu.cpp, src/game.cpp, src/handle_action.cpp, src/npc.h, src/npcmove.cpp, src/ui.h, src/wish.cpp, src/worldfactory.cpp
SUMMARY: None
Port usability/flavor changes for UI from DDA
CleverRaven#41017 (squashed with CleverRaven#43124)
CleverRaven#42154
CleverRaven#42510
CleverRaven#42424 (squashed with CleverRaven#44531; tweaked to prompt only once if there are many acidic corpses in the pile)
CleverRaven#40464
CleverRaven#40624 (squashed with CleverRaven#40702)
CleverRaven#40632
CleverRaven#41781
CleverRaven#43381
Created a new world, obsoleted/removed some mods, queried for list of mods - obsoleted/removed ones have their own category.
Asked NPC to travel with me - 'Nevermind' shows up and works.
Tried pulping a pile of corpses with acidic ones in them - the game warns about acid.
Used 'look around' menu while wearing IR goggles - flavor text shows up.
'Wish for item' menu auto-enables container for …
=> Misc UI changes from DDA 2

src/npctrade.h
Add a hint in trading menu on how to turn a page
SUMMARY: Interface "Add a hint in trading menu on how to turn a page"
Fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/163
Just change text hint to include info about changing pages.
None.
1) Open trading menu
2)  Observe TAB key to switch lists, letters to pick items, **< or > to switch page**, ...
Despite user report, I've could not find that tip in DDA source code. Still it is usefull to have it.
=> Add a hint in trading menu on how to turn a page

src/avatar.cpp, src/avatar_action.cpp, src/ranged.cpp, tests/throwing_test.cpp
Fixes #182
QoL: You can now throw items without wielding them first if you have enough free hands.
You need enough hands to wield current weapon and the thrown weapon. If you do have enough, you don't need to unwield and rewield current weapon every throw.
Rebalanced throwing accuracy at low levels. Level 1 throwing is comparable to old level 3 throwing. Level 10 is a tiny bit less accurate than old level 10.
This should prevent those situations where a character can't throw a grenade through a window without it hitting a wall on the side of it.
=> Throwing update

data/json/items/gun/ups.json, data/json/monsters/turrets.json, data/json/recipes/recipe_deconstruction.json, data/json/recipes/recipe_electronics.json
Fix Disassembling a laser turret drops a handheld laser cannon instead of a TX-5LR laser cannon
SUMMARY: Bugfixes "Fix Disassembling a laser turret drops a handheld laser cannon instead of a TX-5LR laser cannon"
Fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/143
It is make sense that laser turret should drop TX-5LR Laser Cannon but not handled version. Handрудв version can be created from cerberus laser cannon via craft.
Recipes (inlcuding deconstruction) were changed accordingly.
Additonally created fake for laser_cannon to disguise it as TX-5LR Laser Cannon in message log.
None.
1) Spawn laser turret.
2) Check if it shoots from "TX-5LR Laser Cannon" but not "handheld laser cannon".
3) Destroy turret. Check deconstruction. It must contain "TX-5LR Laser Cannon" but not …
=> Fix Disassembling a laser turret drops a handheld laser cannon instead of a TX-5LR laser cannon

src/advanced_inv.cpp, src/advanced_inv.h, src/cata_variant.h, src/crafting_gui.cpp, src/dump.cpp, src/filesystem.cpp, src/flat_set.h, src/item.cpp, src/main_menu.cpp, src/martialarts.cpp, src/newcharacter.cpp, src/output.cpp, src/requirements.cpp, src/scores_ui.cpp, src/translations.cpp, src/translations.h, src/wish.cpp, tests/catacharset_test.cpp, tools/clang-tidy-plugin/UseLocalizedSortingCheck.cpp, tools/clang-tidy-plugin/UsePointArithmeticCheck.cpp, tools/clang-tidy-plugin/test/use-localized-sorting.cpp
SUMMARY: I18N "Switch lists in some menus to use localized sorting; improve the sorting on Windows and MacOS (ported from DDA)"
Port from DDA PRs that switch various menus to use localized sorting (instead of sorting by id, or by blindly comparing strings).
Also port PRs that fix localized sorting on Windows and MacOS.
Cherry-picked without changes (the single merge conflict was due to different header inclusions, wow) the following PRs from DDA:
CleverRaven#40100
CleverRaven#40131
CleverRaven#44288
CleverRaven#40062
CleverRaven#40041
CleverRaven#40291
CleverRaven#44078
CleverRaven#41104
Looking for a cross-platform library that can:
1. Convert utf-8 string <-> ascii string <-> wstring
2. Compare 2 utf-8 strings alphabetically
3. Format numbers & dates
4. Do all of the aforementioned …
=> Port changes to sorting & localized sorting

data/json/flags.json, data/json/monster_special_attacks/spells.json, src/magic.cpp, src/magic.h, tests/memorial_test.cpp
SUMMARY: Features "Port over NO_FAIL spell flag"
Focusing on just the part from the source PR I needed, due to technical difficulties noted in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/208 that are a bit beyond my reach at present.
1. Added NO_FAIL flag to flags.json.
2. Added changes to magic.cpp and magic.h for NO_FAIL flag.
3. Added NO_FAIL flag to debug-only "Pain" and "Tired" spell for testing, renamed them to differentiate them from the mi-go beam side effect spells of the same names.
As noted in previous PR, it's mostly just real damn useful for casting EXP balance but isn't vital for mod porting.
2. Debug-learned all spells in a vanilla world.
3. Opened spellcasting menu to check failure rate of Debug Pain, vs. other spells on the list.
4. …
=> Port over just the NO_FAIL feature

data/json/regional_map_settings.json, data/json/test_regions.json, data/mods/desert_region/desert_regional_map_settings.json, data/mods/rural_biome/rural_regional_map_settings.json, doc/REGION_SETTINGS.md, src/cata_utility.cpp, src/cata_utility.h, src/weather_gen.cpp, src/weather_gen.h
Weather rebalance
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/156
There was attemp already: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/129
But it demonstrated limited ability to tweak weather. Previously it was quite hard to tweak temperature by seasons.
It is better to add ability to set temperaure for exact season.
Remove `base_temperature` setting from JSON
Add ability to set exact temperature for all seasons in 
`\data\json\regional_map_settings.json`
Add new JSON fields:
```
"spring_temp": 8,
"summer_temp": 16,
"autumn_temp": 7,
"winter_temp": -14
```
This JSON fileds set temperarature for middle of certain season.
Intermeidate temperature caluclucates automatically due linear interpolation.
Humidity, pressure, etc unchanged. Only temperature calculation …
=> Weather rebalance and new weather settings

src/action.cpp, src/animation.cpp, src/bionics.cpp, src/bionics_ui.cpp, src/cata_utility.h, src/construction.cpp, src/debug_menu.cpp, src/game.cpp, src/game.h, src/handle_action.cpp, src/options.cpp, src/output.cpp, src/output.h, src/overmap_ui.cpp, src/panels.cpp, src/sdltiles.cpp, src/sdltiles.h, src/ui.cpp, src/ui.h, src/ui_manager.cpp, src/ui_manager.h, src/veh_interact.cpp, src/veh_interact.h
SUMMARY: None
Finish migrating UIs to ui_adaptor
Commit CleverRaven@6892e81d751d9f908bebc838bddc251790a555c3 and PR CleverRaven#40985
Vehicle interaction menu. There were a bunch of merge conflicts, mainly because DDA uses some convoluted logic when it comes to how helicopters can be modified and whether they would fly after that (BN allows helicopter modifications with no penalties or restrictions, I believe).
PR CleverRaven#41050
Various small changes, including actions menu [`Return`] and main menu (not to be confused with title screen) [`Esc`].
PR CleverRaven#41069
5 miscellaneous menus
The last commit is me renaming a function since confusion around its purpose led to a bug in DDA.
Vehicle menu:
* Opened various sub-menus (part selection for …
=> Finish ui_adaptor migration (part 3)

src/weather_gen.cpp
Fix  build. Remove unused variable seasonality_magnitude_K after Weather rebalance
I've left usued variable in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/224
=> Fix  build. Remove unused variable seasonality_magnitude_K after Weather rebalance

src/advanced_inv.cpp
It's a bit of a hack, but it works, is just 3 lines, and even if there are cases when it wouldn't work, the game would crash at that point anyway.
Fixes #229
=> Fix AIM crash when moving all

src/avatar.cpp
SUMMARY: Bugfixes "Fix segfaults from attempting to read non-book items in inventory examine screen"
Simple bugfix using code change proposal posted in relevant issue, thanks to @ anothersimulacrum for posting it.
Added the suggested fix from the issue to avatar.cpp, to prevent the player from attempting to read non-books from the inventory menu.
N/A
2. Started up a game.
3. Examined various items from inventory screen to confirm that trying to read them failed without a crash.
4. Examined items from AIM to likewise ensure that wouldn't crash on attempting to read.
5. Spawned in a book to skim and read it, to confirm books still work. Reading an unread book skims it, brings up skillbook menu if valid skill book, brings up martial art learning options if a …
=> Fix attempting to read non-books from inventory screen causing segfault

data/json/recipes/armor/feet.json, data/json/recipes/armor/hands.json, data/json/recipes/armor/legs.json, data/json/recipes/armor/torso.json, data/json/recipes/other/medical.json, data/json/recipes/recipe_food.json, data/json/recipes/recipe_others.json
SUMMARY: Balance "Port over QoL recipe changes from MST Extra and three DDA PRs, makeshift bandages change"
While preparing a Bright Nights compatible version of my MST Extra mod, I took note of some recipe overrides made for QoL purposes, and decided to port them over. Additionally, reviewing the JSON for those versions reminded me of three PRs made to DDA that would be desirable to port over to here.
Finally, discussion in modder discord convinced me that changing the craft skill for makeshift bandages (also affected by one minor PR being ported over) would be an improvement.
1. Ported over recipe overrides from MST Extra, allowing cured hides/pelts to be used in leather wraps and loincloths, due to these being crude reversible items. Also made leather loincloth consistent with fur …
=> Port over minor QoL changes from MST Extra, 3 PRs

src/crafting_gui.cpp, src/debug_menu.cpp, src/handle_action.cpp, src/iuse_actor.cpp, src/martialarts.cpp, src/overmap_ui.cpp, src/start_location.cpp, src/veh_interact.cpp, src/vehicle.h, src/vehicle_use.cpp
SUMMARY: None
Port QoL changes and fixes to various UIs from DDA.
Cherry-picked:
CleverRaven#44593
CleverRaven#42962
CleverRaven#44413
CleverRaven#44435 (excluding blood type, since BN doesn't have it)
CleverRaven#44599 (squashed with CleverRaven#44898)
CleverRaven#44741 (this should really get its own key in keybindings menu instead of being alternative function of `s`mash)
CleverRaven#44842
CleverRaven#42607
Tried each change in-game. Didn't test failing location report & "use item" menu performance, but these are trivial.
Apparently, hitting `Return` after losing input focus makes github immediately open the PR...
=> Misc UI changes/fixes from DDA 4

src/avatar_action.cpp
Fixes #235
The bug was caused by not overwriting the location after wielding.
=> Fix throwing crash on unwield

src/action.cpp, src/animation.cpp, src/avatar.cpp, src/avatar.h, src/cata_tiles.cpp, src/construction.cpp, src/coordinate_conversions.cpp, src/coordinate_conversions.h, src/debug.cpp, src/debug.h, src/editmap.cpp, src/game.cpp, src/game.h, src/game_constants.h, src/lru_cache.cpp, src/map.cpp, src/map.h, src/map_memory.cpp, src/map_memory.h, src/options.cpp, src/point.h, src/ranged.cpp, src/savegame_json.cpp, tests/map_memory_test.cpp, tests/point_test.cpp
SUMMARY: Features "Unlimited map memory"
Remove limit on map memory capacity.
Follows #97.
Right now, map memory is implemented via `lru_cache`, with absolute map square coordinates as keys. This makes it impossible to remove limit on map memory size, since sooner or later players' computers would run out of memory trying to cram all memorized tiles into RAM.
This PR splits map memory into chunks (named `memorized_submap`, with size equal to an ordinary `submap`), and loads these chunks from the disk (or allocates new empty ones) as necessary.
The `memorized_submap`s are stored in a new folder, `<save-name>/<player-name>.mm1/`, in individual files with names equal to their coordinates. While simplistic, this solution produces a _ton_ of small (<4kb) files, which could tank performance on …
=> Refactor map memory, remove map memory limit.

src/map_memory.cpp
SUMMARY:  None
Fix tile memory showing wrong tiles at z == 0 after a quicksave if the player had tile memory loaded for submaps with z != 0.
Don't discard z
Getting tile memory to work properly on the first try would've been nice.
Teleported to a house roof, saved the game, loaded it, quicksaved, then scrolled the view down to z = 0.
I'm not sure how it compiled in the first place given `point` does not implement `operator+(const tripoint&)`
=> Fix tile memory behavior after quicksave

src/debug_menu.cpp, src/debug_menu.h
SUMMARY: Infrastructure "Added separate benchmark for 'Draws per second' as opposed to existing 'Frames per second'"
This came up in #251.
After migration to `ui_adaptor`, "Draw benchmark (X seconds)" went from measuring number of redraws (`g->draw()`) per second to number of redraws + window refreshes (`g->draw()` + `refresh_window()`) per second. Window refresh is a blocking operation, with block time depending on the OS, and therefore may skew with the benchmark results.
This PR reverts the behavior of the "Draw benchmark" back to how it worked before the migration, and adds "FPS benchmark" that retains the current behavior.
Changed the code to call `refresh_window()` only when measuring FPS.
Also, moved popup creation out of measuring code (!!!), and made the game actually display it …
=> Fix Draw benchmark behavior, add FPS benchmark

src/ui.cpp, src/ui.h, src/wish.cpp
SUMMARY: None
Fix highlight in "Player->Mutate" debug menu (see screenshots)
Allow `uilist_entry` to override highlight color specified for `uilist`.
Opened debug mutate ui, played a bit with mutations.
Before: it's unclear whether avatar has "Deaf"
After: "Deaf" switches between `h_white` and `h_light_green`
=> Fix highlight in "wish mutation" menu

src/main.cpp, src/main.h, src/sdltiles.cpp, src/wincurse.cpp
SUMMARY: Bugfixes "Fixed segfault when closing game window via Alt+F4"
1. Fix segfault (see 'Additional context') when closing game window via Alt+F4.
2. Untangle signal handling code, make TILES version terminate immediately on SIGINT
1. Use `exit_handler` that destroys the `game` instance before calling `exit()` instead of calling `exit()` and trusting compiler to run destructors in correct order. As a bonus, it now properly closes debug log.
2. Show "Really quit?" query only on CURSES.
Tried windows tiles, linux tiles and linux curses. Segfault is gone, Ctrl+C terminates the game on tiles and queries for exit on curses.
```
Thread 1 "cataclysm-tiles" received signal SIGSEGV, Segmentation fault.
ui_adaptor::invalidate (rect=..., reenable_uis_below=<optimized out>) at …
```
=> Proper cleanup when closing game window

src/filesystem.cpp, src/filesystem.h, src/main.cpp
SUMMARY: Interface "The game now warns if user directory is not writable on startup."
Solves #254
Also, fixes debug log file not being created for the first game session.
This PR adds a check to determine whether directory is writable, and makes the game run this check for `user` and `config` dirs on startup.
If the check fails, the code produces a "fatal error" that is displayed in a user friendly way:
On curses: writes to `stderr`
On tiles: shows SDL's cross-platform message box
1. Bump required C++ version to C++17 and implement the check via [Filesystem library](https://en.cppreference.com/w/cpp/filesystem), but this solution works too and does not require dropping support for older compilers.
2. Add error codes in these messages. The game can't use translations at that stage, but …
=> Warn at startup if user directory is not writable

tests/reading_test.cpp
SUMMARY: None
Fix failing test:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cata_test is a Catch v2.12.0 host application.
Run with -? for options                                                                                                                                                                                                                                                        
Randomness seeded to: 1607345790                                                                                                                                                                                                                                               
-------------------------------------------------------------------------------
Losing book …
```
=> Fix the 'losing book during reading - book in car' test

tests/Makefile, tests/creature_test.cpp, tests/explosion_balance_test.cpp, tests/iuse_actor_test.cpp, tests/line_test.cpp, tests/player_helpers.cpp, tests/stats_tracker_test.cpp, tests/stomach_contents_test.cpp, tests/test_main.cpp, tests/throwing_test.cpp, tools/clang-tidy-plugin/DeterminismCheck.cpp
SUMMARY: None
Misc changes for tests aimed at QoL / speed / correctness.
Might fix some of these order-dependent failures.
CleverRaven#44910
CleverRaven#44636
CleverRaven#44281
CleverRaven#44286
CleverRaven#40359
CleverRaven#43255
CleverRaven#43290
CleverRaven#40674
Let's see what travis thinks about it
=> Misc tweaks for tests

src/main.cpp, src/main.h, src/runtime_handlers.cpp, src/runtime_handlers.h, src/sdltiles.cpp, src/wincurse.cpp
SUMMARY: None
Fix compilation for _real_ real
Make sure `exit_handler(int)` is included into `cataclysm.a` when linking `cata_test`
Move it into an existing `.cpp` file instead? None of them looked suitable
The tiles version compiles on linux under `clang10`, and all the tests compile too.
=> Fix compilation (for real this time)

src/runtime_handlers.cpp
SUMMARY: None
Fix compilation. Hopefully, for the last time.
Add missing include to satisfy gcc and mingw
Giving up programming
gcc gives no errors when it compiles `runtime_handlers.cpp`
Sorry for the mess -_-
=> Fix compilation for gcc and mingw

src/overmap.cpp
This mostly happened during tests, causing builds to time out.
Caused by missing advancement of an iterator, discovered by @olanti-p.
=> Attempt to fix infinite loop in some mapgens

src/debug.cpp, src/debug.h, src/main.cpp
SUMMARY: None
Fix crash when DebugLog is called before logging is initialized.
Example case is crash on startup if there are multiple tilesets with the same id https://github.com/DoctorGoat/BN_Update/issues/7
Port CleverRaven#44498
=> Port DDA's fix for crash when DebugLog is called before logging is initialized

src/overmap.cpp
Fix infinite loops in worldgen
Port CleverRaven#44968
Port CleverRaven#45798
It should be easy to rewrite this road placement code to use a simpler randomization mechanism (e.g. world seed + hashed overmap coords = list of road points). This could be used to check if overmaps don't connect with roads without generating these overmaps, which in turn could be used to speed up pathfinding through multiple overmaps.
The game compiles. Generated overmaps look fine in game.
=> Port DDA's fixes for infinite loops in worldgen

data/json/items/ammo/22.json, data/json/items/ammo/32.json, data/json/items/ammo/380.json, doc/GAME_BALANCE.md
SUMMARY: Balance "Establish documentation of rebalancing plans, apply to two more calibers."
Part two in my rebalancing of low-tier ammunition, applying the balancing scheme to two more ammo types: .32 ACP and .380 ACP. Moreover, I've also established a rough outline of how the plan is expected to work, and what goals it seeks to accompish, in GAME_BALANCE.md.
This explicitly takes the "use real-world numbers for determining how much damage to deal" concept already defined in the documentation, and uses it as a starting point. Then it outlines under what contexts to adjust those numbers, a recommendation for how much, and additionally outlines the how armor penetration should be utilized to make the different variations of ammunition better for different situations.
1. Applied the …
=> Ammunition Rebalance Part 2: .32 and .380 ACP

src/martialarts.cpp, tests/player_helpers.cpp
Fix a bug and order-dependent dps test failure.
See commits
Add a test for complete effect removal?
DPS tests are fixed by either commit, as expected.
=> Fix martial arts providing bonuses from effects markes as 'removed'

src/player.cpp
Fix #166
Add explicit cast to float
Add Visual Studio builds to CI?
Github Actions and AppVeyor have Visual Studio and vcpkg preinstalled (BN [still has](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/.appveyor.yml) DDA's AppVeyor config), Travis [would need some work](https://travis-ci.community/t/how-to-set-up-vcpkg/10656), but also doable.
Just compiling with tiles and sound, without necessarily running tests, should be enough.
Game compiles without warnings
=> Fix msvc warnings

doc/JSON_INFO.md, src/character.cpp, src/character.h, src/newcharacter.cpp, src/player_display.cpp, tests/vision_test.cpp
As in title. Closes #184
UI now whows that perception grants 1/3 of a tile of night vision per point and that eye encumbrance takes 0.1 tile per point of encumbrance.
I'm not satisfied with how the math currently rounds things up, but subtracts 1 internally.
This moves breakpoints: you gain the extra vision tile at 7, 10, 13. Should be at 3, 6, 9, 12.
Due to how the vision math works, there are no gains outside the breakpoints (except cancelling out eye encumbrance), not even in circular distance mode. There is no way to get a "more filled out LOS circle" or a half-visible tile.
It will probably require a hard `floor` to get it where I want it.
=> Display effects of perception and eye encumbrance on night vision in menus

src/activity_handlers.cpp, src/activity_item_handling.cpp, src/crafting.cpp, src/game.cpp, src/iuse.cpp, src/iuse.h, src/player.cpp, src/player.h, src/veh_interact.cpp, src/veh_type.cpp
1. Fixes assisting NPCs not actually providing speed bonuses (CleverRaven#35610)
2. Print names of _all_ NPCs that assist with activity
3. Don't print names of NPCs that don't assist with activity
1. Fix integer math
2. Fix loops
3. Fix more loops
Rewriting the whole thing to be incorporated into activity code, so that multiple characters can work on a single task, leave/join at any time and provide bonuses proportional to their abilities instead of the current magical -10%/-20%/-30% reduction to activity time from 1/2/3 NPCs for simply being nearby when activity is started.
Or just moving half of affected activities into construction/crafting recipies.
Tried digging a pit with 4 NPCs nearby, 3 of them are recognized as 'helpers' and provide move reduction for the activity (120'000 -> …
=> Fix multiple issues with NPC assistance

src/armor_layers.cpp
Fix #281
Update bounds before clamping index to these bounds
Fixed the crash for me
=> Fix crash when removing last item worn by NPC

src/computer_session.cpp, src/mission_start.cpp, src/mission_util.cpp, src/overmapbuffer.cpp, src/overmapbuffer.h, src/popup.cpp, src/popup.h, src/simple_pathfinding.h, src/ui_manager.h
Starting shelter console gives a player their first mission - to reach a refugee center.
To do this, the game first must find (or generate) that center, and then find a path to it. The whole process normally takes a second or five, but depending on worldgen can take up to a minute.
A whole minute of being unresponsive is perhaps not the best first impression the game should leave on new players.
This PR adds a small animated 'Please wait' popup that acts as a [throbber](https://en.wikipedia.org/wiki/Throbber) - indicates that the game is busy generating terrain / finding path. 
Implement a new popup called `throbber_popup` and show it while searching for/generating mission target and finding path to it.
To minimize the overhead, the popup employs some tricks:
* It freezes all underlying …
=> Show an animated 'Please wait' popup while looking for mission target

data/json/bionics.json, data/json/items/fake.json
Closes #168 
Will leave wielded scalpels if you have a save with them pulled out. It's a minor bug, so I'll let it slide.
Making them not-toggled makes them work at all times.
=> Make bio scalpel not activated

src/crafting.cpp, src/recipe.cpp
Closes #160
I only had to move the fitting from `complete_craft` to `create_result`.
=> Display craft results as FIT by default

src/game.cpp
Closes #288
It does the hack I described: a NPC that fails to path on overmap will unset own destination.
It's OK because the player who would try to tell a NPC to path into unpathable location will get "no path" message, so this only affects NPCs who acquire the pathing mission from non-player sources.
=> Make NPCs who fail to overmap path not try again

android/app/src/main/AndroidManifest.xml, src/sdltiles.cpp
Apparently there were some users who experienced the joystick issue in BN (inherited form DDA, CleverRaven#33936).
This PR ports DDA's fix for it and another fix for game restarting when usb keyboard is plugged in.
Cherry-picked CleverRaven#42982 and CleverRaven#45506
None, since I can't build it myself (and don't own usb keyboard).
I can't find any bugreports in DDA repo related to these changes, and there were no conflicts, so I'm pretty sure everything will work as is.
=> (Android) Port DDA's fixes for stuck joystick and game restarting when plugging in usb keyboard

src/activity_item_handling.cpp, src/inventory_ui.cpp, src/inventory_ui.h, src/iuse.cpp
Closes #147
Fixes washing for count-by-charges items (CleverRaven#41884)
In the same order as commits:
1. Change `inventory_iuse_selector` to correctly handle items not on character. Since it is a copy-pasted version of `inventory_drop_selector`, it assumed all items are on character, and so did some questionable casting between `item_location` and `item*`, producing invalid `item_location`s as a result.
2. Stopped activity handler for item washing from trying to reorder received items. It is a) unnecessary here b) breaks with items the character doesn't have.
3. Added items within `PICKUP_RANGE` (like when crafting) to the list of items to wash - that's pretty much CleverRaven#45348
4. Fixed handling of partial stacks of count-by-charges items: split off some charges into a separate item …
=> Changes & fixes for item washing

src/game_inventory.cpp, src/game_inventory.h, src/item.cpp, src/item_factory.cpp, src/itype.cpp, src/itype.h, src/player.cpp
Closes #303
Guns that can't be loaded will not have a "this weapon can't be loaded in current state" line instead of causing a crash.
Additionally:
* If a gunmod can be applied to specific gun types, but will make them unable to be loaded, debugmsg on game load. This might be undesirable if a mod has separate ammo and magazine mods, though.
* Gunmod installation always asks you exactly once if you want to do it, using the same menu query, instead of possibly asking you twice if the mod is unremovable, or zero times if it's guaranteed. If installation is guaranteed, it just doesn't offer to use tools.
* If a gunmod would cause a gun to become un-loadable, warn about it. This isn't covered in the on-load debugmsg, because you can specify whole classes of guns.
* The gunmod installation …
=> Prevent crashes for guns that can't be loaded

data/json/items/comestibles/seed.json
SUMMARY: "Adjusted plant growth time proportionally for default 14 day seasons"
Fixes #308
Adjusted the growth times from 91 days to 14 days and the rest to the same ratio, rounding to the nearest whole number.
Make the seed's growth time automatically scale to the set season length, but I have no clue how to do that.
Loaded an existing save and found that the seeds had grown as I would have expected based on season length.
=> Adjusted plant growth time

data/json/items/tool/electronics.json, data/json/items/tool_armor.json, data/json/mutations/mutations.json, src/activity_handlers.cpp, src/activity_item_handling.cpp, src/avatar.cpp, src/bionics.cpp, src/clzones.cpp, src/harvest.cpp, src/harvest.h, src/item.cpp, src/iuse.cpp, src/mutation.h, src/mutation_data.cpp, src/newcharacter.cpp, src/string_id.h, src/translations.h, src/vehicle_move.cpp, tools/clang-tidy-plugin/TranslatorCommentsCheck.cpp, tools/clang-tidy-plugin/test/translator-comments.cpp
Deporting bugs by porting fixes
CleverRaven#45165
CleverRaven#44938 (squashed with CleverRaven#46442)
CleverRaven#45234 (not a bugfix, but a must-have nonetheless)
CleverRaven#45250 (also removed a check for Jittery so that behavior completely matches description)
CleverRaven#45250 (in case clang-tidy will be part of CI some day)
CleverRaven#45281
CleverRaven#45451
CleverRaven#45609
CleverRaven#45685
CleverRaven#45963
CleverRaven#45626
Couldn't reproduce that vehicle SIGFPE crash and didn't check clang-tidy, but the rest of the fixes work.
=> Misc bugfixes from DDA 4

src/map_memory.cpp, src/map_memory.h, src/savegame_json.cpp
Lowers RAM usage for 2 cases:
1. When there are no graphical tiles memorized, only symbols
2. When zooming out or scrolling up/down in 'Look around' window
Rewrite `mm_submap` in such way that it allocates buffer for memorized tiles/symbols only on first write operation (as opposed to always allocating on init).
Loaded existing save, walked around a bit. Didn't notice any problems.
Loaded a save where avatar is in a clear field, noted RAM usage. Zoomed out (with tiles only), pressed `x` and moved the cursor up/down 3 z levels, noted RAM usage again.
Tiles:
Memory usage | base, MB | increased to, MB | delta, MB
-|-|-|-
without patch | 326 | 367 | +41
with patch | 322 | 327 | +5
ASCII (SDL build with tiles disabled):
Memory usage | base, MB | increased to, MB | delta, MB
-|-|-|-
without …
=> Some RAM optimizations for tile memory

src/item.cpp
Fix mess kit again
SUMMARY: Bugfixes "Fix mess kit again"
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/292
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/292#issuecomment-751388918
> 
> 
> Now that I'm reading the new logic, it also seems wrong:
> If the item is loaded, it has contents. Meaning the second part of the check (the one for tools) only triggers for UNloaded items.
> 
> I must have tested it wrong. I probably spawned a container with boiling quality, like a glass bottle.
> 
> The correct logic would probably be
> 
> ```
> if( id == quality_id( "BOIL" ) && !contents.empty() &&
>     ( !is_tool() || has_item_with( boil_filter ) ) ) {
> ```
> 
> Except for one caveat (at the bottom of my post).
> This way: if it's empty, it's good to go. If it's not empty …
=> Fix mess kit again

data/json/vehicleparts/rams.json, src/advanced_inv_pane.cpp, src/bionics.cpp, src/character.cpp, src/item.cpp, src/mapgen.cpp, src/mission_companion.cpp, src/monattack.cpp, src/sdlsound.cpp, src/sounds.cpp, src/veh_interact.cpp
Preemptive bugfixing
CleverRaven#45399 (squashed with #45904; there were some more problems, so I've squashed my own fixes on top of it)
CleverRaven#45773
CleverRaven#45750
CleverRaven#45835
CleverRaven#45914
CleverRaven#46021 (Latest version of BN freezes when trying to move all items from `A`ll area with `Open default AIM layout` option enabled. This change fixes that, but I suspect there's another bug hiding in the code.)
CleverRaven#46010
CleverRaven#46104
CleverRaven#46137
CleverRaven#45413
Let the bugs strike first?
Didn't test the food stealing fix (it looks fine), but the rest worked.
The AIM resets panels when moving items from `A`ll area one-by-one with `Open default AIM layout` option enabled, but that's not critical.
=> Misc bugfixes from DDA 5

src/debug.cpp
Fix the black screen issue reported on discord.
Example case is when there are 2+ mods with same mod ids.
Delay showing `debugmsg`s a bit more
Copypasted one of the in-repo mods, run the game.
Before: black screen on startup.
After: the game shows "there's already a mod with ident x" debugmsg
=> Fix black screen on startup (when trying to show debugmsg)

src/cata_tiles.cpp, src/cata_tiles.h
Fixes #245
Replace `assert` with `throw`
Triggered (via debugger) failure when:
1. loading save - game gives `debugmsg` and returns the player to the title screen
2. switching tileset while playing - game shows error popup and falls back to using text mode
=> Don't crash if failed to create texture

src/character.cpp, src/computer_session.cpp, src/game.cpp, src/game.h, src/gates.cpp, src/magic_spell_effect.cpp, src/monattack.cpp, src/output.cpp, src/overmapbuffer.cpp, src/savegame_json.cpp, src/turret.cpp, src/vehicle.h, src/vehicle_use.cpp, tests/string_test.cpp
Digital disinsection
CleverRaven#46266
CleverRaven#46345
CleverRaven#46242
CleverRaven#42549
CleverRaven#46407
CleverRaven#40995
CleverRaven#46433
CleverRaven#46465
CleverRaven#46453 (the bug persists if z-levels are disabled)
CleverRaven#46521
CleverRaven#46536
Calling Ghostbusters?
Didn't test fixes for profession / regen message, but those are trivial.
The rest either have tests from original PRs or were tested manually.
Turret's friendly fire check is really weird: the turret sometimes refused to shoot until I moved 10 tiles away from the line of fire, and sometimes it fired right over my shoulder (through my tile).
=> Misc bugfixes from DDA 6

data/json/items/tool/misc.json, src/character.cpp, src/item.cpp, src/player.cpp, src/suffer.cpp
SUMMARY: Bugfixes "Port over fix for applying effects from passive enchantments"
An important fix to enchantment code that I forgot about. Needed for effects-from-enchantments to function again, especially if from mutations.
1. Ported over changes to item.cpp and suffer.cpp, for less broken processing of passive relic/enchantment effects. This had to be done as `enchantment_cache.activate_passive` instead of `enchantment_cache->activate_passive` but this causes a problem, see below.
2. Altered the stat adjustment of the cube of shame to test an issue that came up while working on initial commit.
Continue to slowly go insane.
2. Spawned in and activated the cube of shame.
3. Tested the Cloaking System CBM to confirm invisibility effect appears on activation.
4. …
=> Port over fix to effects-from-enchantments

src/cata_utility.h, src/ui.cpp, src/ui.h
It's doesn't show any results when I try to use the filter with Russian interface.
Get rid of `tolower()` call. On Linux it apparently skips UTF-8 chars, but on Windows it mangles them. Must be something with locales... The `lcmatch()` function that performs case-insensitive comparison already converts input to lower case, and does it right, so the problematic `tolower()` is unnecessary here.
Also, renamed a few variables for readability and fixed docs for `lcmatch()`.
Switched to Russian, entered `я` in debug wish item uilist filter.
Before the fix: no entries found.
After: many entries found, all of the contain either `я` or `Я`.
Works on both Win and Linux.
=> Fix uilist filtering with non-ascii chars on Windows

src/handle_action.cpp
=> Fix 'Wait for...' query when player doesn't have a watch.

src/cached_options.cpp, src/cached_options.h, src/creature.h, src/debug.cpp, src/debug.h, src/game.cpp, src/game.h, src/game_constants.h, src/game_ui.cpp, src/json.cpp, src/line.cpp, src/line.h, src/loading_ui.cpp, src/messages.cpp, src/messages.h, src/options.cpp, src/options.h, src/output.cpp, src/panels.cpp, src/popup.cpp, src/recipe.cpp, src/sdlsound.cpp, src/sdltiles.cpp, src/translations.cpp
1. Move cached options to a separate lightweight header. This might allow to get rid of some heavier #includes on the next IWYU run, and overall is a bit cleaner than spreading them over the codebase.
2. Make PICKUP_RANGE configurable through debug options tab. The purpose of that is to make it possible to craft with items that are e.g. in a different room of the player's base. Might also come in useful for actual debugging.
See commits. Partially uses code from https://github.com/CleverRaven/Cataclysm-DDA/pull/43983/commits/ebfe558c2a96bf9f5edb036e92f8c4f7e12625cd and https://github.com/CleverRaven/Cataclysm-DDA/commit/bf604e5625860758773c66bcdd19be0fc585b023 (the crash and black screen issues referenced in that commit should have been fixed in #321).
While looking into history of …
=> Move cached options to separate file, make PICKUP_RANGE configurable

data/json/items/ammo/357mag.json, data/json/items/ammo/357sig.json, data/json/items/ammo/38.json, data/json/items/ammo/38super.json
SUMMARY: Balance "Ammo Rebalance Part 3"
After a bit of a delay, got back to working on the ammo rebalance project. This time will be tackling the .38 and .357 calibers.
* Balance increase of ~22% applied to .38 Special FMJ, increase of armor penetration to 9 to make it close to 25% more effective against 16 armor armor compared to JHP variant, as per GAME_BALANCE.md.
* Hollowpoint damage bonus of 25% applied to .38 Special JHP.
* Moved `38_super` and variants to 38_super.json, and set it to copy-from `38super_fmj` to make all .38 Super rounds actually count as .38 Super ammo. Recoil and disperson increases also removed since it's no longer being tweaked relative to .38 Special
* Balance increase applied to .38 Super FMJ, armor penetration of 14 added to make it 25% more effective against …
=> Ammo Rebalance Project: Part 3

data/raw/keybindings.json, src/action.cpp, src/action.h, src/cata_tiles.cpp, src/debug_menu.cpp, src/game.cpp, src/game.h, src/handle_action.cpp
A few times I've had the need to easily check layout of submaps / overmap tiles in relation to the avatar, and this PR implements debug overlay for that.
It uses single lines to indicate submap boundaries, double lines for omt boundaries.
Submaps are also color coded:
green - part of `g->m`
cyan - loaded in the `MAPBUFFER`
blue - neither
Also includes commit https://github.com/CleverRaven/Cataclysm-DDA/commit/23ce399f37c1c00335a3c4c7949296779569c23b from DDA to minimize number of future conflicts.
=> Add debug overlay for submap & overmap tile boundaries

src/cata_utility.cpp, src/cata_utility.h, src/catacharset.cpp, src/catacharset.h, src/filesystem.cpp, src/filesystem.h, src/font_loader.h, src/game.cpp, src/ime.cpp, src/init.cpp, src/main_menu.cpp, src/mapsharing.cpp, src/newcharacter.cpp, src/options.cpp, src/output.cpp, src/output.h, src/sdl_font.cpp, src/wdirent.h, src/worldfactory.cpp, tests/filesystem_test.cpp
Fixes miscellaneous issues with filesystem access, most notable is reading/writing non-English paths on Windows.
1. Add tests for filesystem operations, with both ASCII and UTF-8 paths
2. Fix misc bugs detected by the tests
3. Rewrite all filesystem functions to accept paths as UTF-8 encoded strings, and:
* on Linux, use these UTF-8 encoded paths for system calls;
* on Windows, convert them to `wstring` and pass them to wide Windows API (as per https://utf8everywhere.org/#windows ).
Newer Windows 10 builds have optional support for UTF-8, but I'm not sure if it's mature enough to warrant full switch.
4. As part of №3, remove the optional Chinese/Japanese/Korean path encoding conversion hack. Because it
* is enabled by default, and breaks file paths when working with some other non-English …
=> Fancy fixes for filesystem functions

src/sdlsound.cpp
May fix issue #101
I went to check SDL_mixer source code, and noticed that `Unsupported audio channels` error is used only in a few functions, one of them `Mix_SetPosition()`. This function is used in the game code to position some sound effects, namely pitch-shifted walking sound, and the error was introduced in SDL_mixer 2.0.2 (MXE had 2.0.4 before the recent update; not sure which version DDA uses, but most likely some older one since 2.0.2 is from October 2017).
Pitch-shifted sounds are done in such way that they dynamically allocate & pitch-shift a chunk on each `play_variant_sound` call, and then dynamically de-allocate it when playback finishes. In case of any error in `play_variant_sound`, the de-allocation happens instantly.
What I believe happens is:
1. The pitch-shifted chunk …
=> Don't deallocate playing chunk if failed to set sound position

data/json/items/ammo/22.json, data/json/items/ammo/32.json, data/json/items/ammo/357mag.json, data/json/items/ammo/357sig.json, data/json/items/ammo/38.json, data/json/items/ammo/380.json, data/json/items/ammo/38super.json, data/json/items/ammo/46.json, data/json/items/ammo/57.json, data/json/items/ammo/762x25.json, data/json/items/ammo/9mm.json, data/json/items/ammo/9x18.json, doc/GAME_BALANCE.md
SUMMARY: Balance "Ammo Rebalance Project, part 4"
Part four of the ammo rebalance project, implementing ideas as outlined in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/359 This covers pistol-caliber ammunition up to 9mm caliber.
1. Increased 5.7mm's damage by one-third.
2. Increased 4.6mm damage by two-nineths.
3. Reflavored the standard 7.62x25mm ammo as FMJ, allowing me to make balancing a bit easier. Otherwise I'd have to tack on the hollowpoint bonus and make it 37 damage, instead of 29.
4. Overhauled how arpen bonuses are being tacked on as per musings in the tracking issue. Instead of fumbling with comparing FMJ ammo against arbitrary armor values, instead desired arpen is determined by whether damage plus arpen is at least 25% higher than the hollowpoint variant's …
=> Ammo Rebalance Project: Part 4

data/json/construction.json, data/json/furniture_and_terrain/furniture-appliances.json, data/json/items/fake.json
The electric grid system recently added can be used already with numerous tools like arc welders so I feel like it should be a feature to be added.
I will add more electrical tools like the soldering iron but I feel like it could be further refined, for example: Tilesets, I don't know if a tileset for a vehicle could work on a furniture. Besides this is my first ever pull request and I have barely any knowledge of programming, I know how to code items, furnitures, recipes through json files but that is about it.
Also, I need to add that I selected the jumper cable item in the recipe because there is no equivalent in C:DDA and C:BN for household commercial cable.
=> Add the option to place (construct) arc welders and connect them on a electrical grid

data/raw/languages.json, src/debug.cpp, src/explosion.cpp, src/language.cpp, src/language.h, src/main.cpp, src/options.cpp, src/options.h, src/path_info.cpp, src/path_info.h, src/text_snippets.cpp, src/translations.cpp, src/translations.h, tests/test_main.cpp, tests/translations_test.cpp
SUMMARY: Infrastructure "Cleaned up game language/locale handling"
Problems with current game language handling code:
1. It's scattered across multiple files.
2. Everything is hardcoded.
3. It's nondeterministic. Starting the game with one language and switching to some other leads to different gettext/locale settings  when comparing to starting the game with that other language already selected.
4. It has a number of minor bugs.
See commits. The biggest changes are:
1. Moving all language handling code into a separate `.h`/`.cpp` file.
2. Encapsulating language definitions.
3. Loading these definitions from JSON.
4. Rewriting gettext/locale code to re-set the state from scratch each time language is set (once on startup, then each time it's changed in settings).
1. Get rid of 'System …
=> Clean up game language/locale handling

src/character.cpp, src/character.h, src/player.cpp
Most of move effects, like breaking grabs and standing up from downing.
Rewritten a bit to use static functions instead of methods. No need to have everything be a method when it only uses public methods of `Character`.
Requested by Cyan on Discord and was easy to port.
=> Port Codebandit's "Escape grabs and some traps while waiting (#41187)"

doc/JSON_FLAGS.md, src/veh_type.cpp, src/vehicle.cpp, src/vehicle.h, src/vehicle_use.cpp
Remove electric power consumption for vehicle parts with EMITTER flag.
Reasons:
1. The code assumes `epower` to be in kilowatts, while everything else treats `epower` as watts;
2. It also bypasses regular power calculations, meaning e.g. consumption rate does not show up in vehicle menu;
3. Emitters consume power only while active, and we have `ENABLED_DRAINS_EPOWER` flag for that.
Remove power consumption code, move emitters code into a separate method.
Also, updated docs on vpart flags (some flags are likely still not documented), and added a couple checks for flag usage.
Used "essense surge generator" from Arcana https://github.com/chaosvolt/cdda-arcana-mod/blob/dcda20db402dc654b81bbaaaadd573f3cd977cd4/Arcana_BN/vehicleparts.json#L96-L138
The part still emits fields while active, but …
=> Remove epower consumption for vparts with EMITTER flag

data/mods/Aftershock/recipes/recipe_overrides.json, data/mods/Aftershock/recipes/recipes.json
Summary 
Category "Bugfixes"
Fix craft atomic headlamp
All atomic items are made from plutonium, except for the headlamp, which is made from betavoltaic. And he is nowhere to be found
Inserted craft from BN with replacement for plutonium
Testing
OK
=> Aftershock craft fix

data/json/items/vehicle/cargo.json, data/json/recipes/recipe_others.json, data/json/vehicleparts/vehicle_parts.json
Continuation of the previous topic https://github.com/cataclysmbnteam/Cataclysm-BN/pull/377
I changed your recommendation from 3 to 2 heavy frames, since 3 heavy frames weigh 300kg and the cargo holder will weigh 200kg, it is not logical.
=> Update cargo capacity (continuation)

src/cata_tiles.cpp, src/cata_utility.h, src/character.cpp, src/units.h, src/weather.cpp, src/weather_gen.cpp, tests/player_test.cpp, tests/vision_test.cpp
Fixes #383
To actually figure out if I fixed it, I re-did the tests and added temperature units (currently only used in tests).
For air temperature tests, there are 4 sets of clothing:
* Nude
* Light ("hat_ball", "bandana", tshirt", "gloves_fingerless", "jeans", "socks", "sneakers") 
* Heavy ("hat_knit", "tshirt", "vest", "trenchcoat", "gloves_wool", "long_underpants", "pants_army", "socks_wool", "boots")
* Arctic ("balclava", "goggles_ski", "hat_hunting", "under_armor", "vest", "coat_winter", "gloves_liner", "gloves_winter", "long_underpants", "pants_fur", "socks_wool", "boots_winter")
There are 7 body temperature thresholds:
* BODYTEMP_FREEZING
* BODYTEMP_VERY_COLD
* BODYTEMP_COLD
* BODYTEMP_NORM
* BODYTEMP_HOT
* BODYTEMP_VERY_HOT
* BODYTEMP_SCORCHING
The body temperature values are …
=> [CR]Fix body temperatures being too low

data/json/itemgroups/military.json, data/json/monsterdrops/zombie_cop.json, data/json/monsterdrops/zombie_soldier.json
Reduce chance of dropping weapons and ammo from zombie soldiers and cops.
SUMMARY: Balance "Reduce chance of dropping weapons and ammo from zombie soldiers and cops"
Currently player has 100% chance of getting weapons from zombie soldiers. With 70% it will be assault rifle. With 10% it will be LMG with good amount of ammo.
This gives player solid way of farming wepons from zombies and ammo instead of actually looting it from locations.
Additionally it unbalances game with providing solid way of getting gun and ammo early.
1) Reduce chance of dropping wepons from soldiers from 100% to 10%, but add separate 30% chance of dropping pistol.
2) Big guns dropped from zombie soldiers will be damaged as guns dropped from cops. Pistols going to be clean.
3) Reduced max possible dropped ammo for …
=> Reduce chance of dropping weapons for zombie soldiers

src/string_formatter.cpp, tests/line_test.cpp, tests/map_memory_test.cpp, tests/npc_talk_test.cpp
~May help with the weird test output?~
Well, that didn't work.
It also didn't break anything, so I guess it can still go in as it makes `cata_printf` behave more like vanilla `printf`. 
Switch from C++ stream to C printf
Compiles, Travis is unaffected
=> Switch cata_printf to use printf

src/ballistics.cpp
Fixes #371
When dropping item contents, don't count item itself as part of contents.
Threw a glass bottle of acid at a wall.
=> Fix thrown glass item not shattering

src/debug_menu.cpp, src/distribution_grid.cpp, src/distribution_grid.h, src/overmap_ui.cpp, src/overmap_ui.h
Add debug overmap display for distribution grids.
Shows 2 things:
1. Overmap tiles connected into big grids (with >= 2 overmap tiles)
2. Active grids (the ones in the grid tracker)
Refugee shelter with active 3-level grid (solar panel, battery, item charger)
Blinking light-blue-on-dirty-yellow
City buildings with multi-z-level grids
Blinking light-blue-on-black
Since the code uses overmapbuffer's standard methods, there's a side effect of game generating new overmaps while scrolling the map in this mode. This was not intentional, but also seems harmless enough.
=> Add debug overmap display for distribution grids

src/armor_layers.cpp, src/character.cpp, src/character.h, src/game_inventory.cpp, src/inventory.cpp, src/pickup.cpp, src/player.cpp, src/player.h
Fixes #84.
There may be items in containers that also have letters assigned to them (in case of attached save it was a hunting knife in a sheath sharing same keybing with makeshift bandages, and usp_45 in a holster with same key as wielded shotgun), and that breaks inventory restack code that expects all items with letters to be top-level.
Revert commit d1c43aa9ca5e5a4a179207692e4fc30ecfca574f.
Using indices is kinda meh, but at least the code works. Ideally I'd fix this properly, but I also have no idea on how the potential "linked items" feature would work.
Loaded the save, repeatedly opened inventory.
=> Fix inventory letters getting re-assigned on inventory restack

src/explosion.cpp
Fixes #395.
Also fixes that monsters with MF_ELECTRIC_FIELD flag are vulnerable to the blast only if player sees them being blasted.
Stop the code from discarding z component; move 'g->u.sees()' condition into a proper place.
The first part is based on https://github.com/CleverRaven/Cataclysm-DDA/commit/b7f8e2375c2a56f1228ffe49f40d35361ef432bd, though due to merge conflicts it was easier to re-implement from scratch.
Blowing up EMP grenade on the same z level as player drains bionic power; dropping it from from a ledge makes the player immune to the blast.
The blast animation looks the same in both cases - something to look into later.
=> Fixes for EMP blast

data/json/mapgen/shelter.json
Fixes #398
Cherry-picked CleverRaven#41095
Repeatedly started new game with non-vandalized shelter as starting location. After the change, the shelter is always in pristine condition.
=> Port DDA's "Move used shelter into the vandalized category"

data/json/monsters/turrets.json
SUMMARY: Bugfixes "Allows ID cards to despawn light turrets, laser turrets"
I noticed that light turrets, currently used in lab bunkers, lacked the monster flag that allows card readers to despawn them. On discussion with @Firestorm01X2 in the modder's discord, it was suggested I add that plus the flag that allows consoles to despawn them, for consistency.
And the suggestion came up to add them to laser turrets too. Right now they only show up as inactive versions the player can deploy, but this came up as a suggestion so they'll be usable in locations in the future.
1. Gave `ID_CARD_DESPAWN` and `CONSOLE_DESPAWN` monster flags to `mon_turret_light`
2. Gave `ID_CARD_DESPAWN` and `CONSOLE_DESPAWN` monster flags to `mon_laserturret`.
1. Adding this to all turrets, not just the others likely …
=> Allow despawning light turrets and laser turrets

data/json/items/ammo/10mm.json, data/json/items/ammo/36paper.json, data/json/items/ammo/40.json, data/json/items/ammo/44.json, data/json/items/ammo/44paper.json, data/json/items/ammo/45.json, data/json/items/ammo/45colt.json
SUMMARY: Balance "Ammunition Rebalance Project Part 5"
Fifth part of the ammo rebalance project, as noted on https://github.com/cataclysmbnteam/Cataclysm-BN/issues/359. This should now cover all of the pistol-caliber ammunition that would be subject to a damage increase, possibly all the bullets that'd get a base damage buff at all.
This leaves damage and arpen adjustments for FMJ, hollowpoint, and other variants of other ammo that would not be subject to a direct buff to their FMJ variant's damage. This also leaves the question of "do we scale arpen of heavy-but-slow bullets to the same amount" for another day.
1. Applied the one-nineths tier of balance increase to 10mm FMJ, raising its damage from 31 to 34. Increased its armor penetration to 19.
2. Applied two-nineths tier of balance …
=> Ammo Rebalance Part 5: Almost All Pistol Rounds

src/inventory_ui.cpp, src/main_menu.cpp, src/worldfactory.cpp, src/worldfactory.h
Closes #333
1st commit adds filtering for mod list in the world creation menu (originally written for DDA back in June https://github.com/CleverRaven/Cataclysm-DDA/commit/1253929540a101b103a12bbb2ddddb6fb6850555).
2nd commit adds new UI (basically an alternative mode for "select mods" world creation tab) that allows editing mod list and mod load order. It's accessible from the title screen (World->WorldName->Edit World Mods) and has a big fat warning on it to discourage people from recklessly breaking their saves.
Created new world, loaded into it, then went back to title screen and edited mod list, then loaded into the world again.
Everything seems to be working fine.
=> UI for editing world mod list

src/item.cpp
Fixes #344
If item is a magazine, `item::ammo_default()` now returns `default_ammo` for that magazine.
Defined an ammo belt that specifies default_ammo different from ammotype's default ammo, debug spawned it.
=> Respect magazine's default ammo override in item::ammo_default()

src/worldfactory.cpp
I merged #434 and #426, but then noticed they are in conflict.
This should fix it.
=> Missing string_utils header after header prune

src/ballistics.cpp, src/ballistics.h, src/cata_utility.cpp, src/cata_utility.h, tests/throwing_test.cpp
New expected values for throwing tests are now within `epsilon / 2` of calculated ones.
The throwing tests are still a brute force black box thing.
Maybe the nondeterministic, statistical tests should set their own RNG seed.
=> Fix throwing tests being too fragile

data/json/furniture_and_terrain/furniture-surfaces.json
Port "Makes the tourist table and workbench grabbable/movable" from dda
Grab and move a workbench or even a tourist table
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/46597
Testing
Grab and move tourist table and workbench
=> Makes the tourist table and workbench grabbable/movable

data/json/uncraft/armor.json
Port "added disassembly options for some basic undergarments and socks" from dda
Added disassembly recipes to uncraft for many trivial things such as socks, panties, briefs, etc. All recipes produce thread, and are balanced around the existing uncraft recipe for socks_ankle. Thread amounts are all well below the amount of thread it would take to craft the item, and should pose no balance issues
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/47742
Detete: xlboxer_shorts, xlsocks, xlboxer_briefs, xlboy_shorts - becouse BN dont have this items
Testing
Spawn socks and disassembled them
=> Added disassembly options for some basic undergarments and socks

src/item.cpp
Port "fix disassembly component display" from dda
The disassembly ui didn't stack components used in the fabrication of items (only looted items had their components stacked due to that being the way they are formated in the recipe)
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/47869
Testing
- Spawn in cargo pants
- Spawn in the components needed to make cargo pants ( use short string due to them being item stacks not charges)
- Craft the cargo pants
- Enter disassembly view and compare
- Previously: the strings would show up as 3 stacks of 2
- Now: they are a single stack
=> Fix disassembly component display

data/json/items/armor/legs_clothes.json
Port "Fix Army Winter Pants repair difficulty" from dda
Added the ability to strengthen winter army pants (what was previously not possible)
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/47691
Testing
Spawn army winter pants and strengthen them
=> Fix Army Winter Pants repair difficulty

src/avatar.cpp
Port "Show remaining XP to next level in Stats Through Kills" from dda
Show remaining XP points needed to next level instead
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/46452
Testing
Kill zombi and try to activate the skill with mod "Stats Through Kills"
=> Show remaining XP to next level in Stats Through Kills

src/animation.cpp, src/animation.h, src/cata_tiles.cpp, src/cata_tiles.h, src/game.cpp, src/handle_action.cpp, src/pixel_minimap.cpp, src/pixel_minimap.h
Reduce CPU usage when there are no animations on screen
Don't redraw if there is nothing to animate (no weather, SCT or beacons on the pixel minimap)
Walked around / waited with/without animations enabled. The program properly redraws game window.
=> Don't redraw if animations are enabled, but there is nothing to animate

src/character.cpp
SUMMARY: Infrastructure "Simplify Character::mod_power_level"
Function is overly complex for how simple the transform really is. The work done to prevent integer overflow can be reasoned about further and no conversion to `int64_t` is necessary. The `if-conditional` is also unnecessary. The operation being done is equivalent to calling `std::min`
`power = power_level + npower` can overflow. The overflow is why there is a cast to `int64`. This makes sense. What doesn't make sense is not using our available domain knowledge to remove the need to cast.
There is a set range we are going to clamp to which is `[0, max_power_level]` and we need to satisfy the condition `max_power_level >= power_level + npower`. Rearranging terms `max_power - power_level >= npower`
We can use this rearrangement …
=> Remove unnecessary casting and branch from Character::mod_power_level

src/sdltiles.cpp
Stop the game from receiving 'Tab' key when Alt+Tabbing out of the window
Treat any key press while Alt is down as "handled", but in reality simply discard them.
Alt+Tabbing while in settings UI no longer changes the tab. Text input using Alt codes still works.
=> Ignore non-numeric keys pressed while Alt modifier is active

src/activity_item_handling.cpp
Fixes #445
As in the title
Make yourself hungry, get a vehicle and designate autoconsume zone. Fill it with food, then drive the vehicle a few tiles forward.
Before: waiting for an hour leaves the avatar hungry.
After: as soon as waiting starts, the avatar goes from hungry to sated and a message pops up in the sidebar reporting consumed food.
=> Refresh vehicle zone cache before looking for autoconsume zones

src/iexamine.cpp, src/item_factory.cpp, src/iuse.cpp, src/iuse.h, src/monexamine.cpp
SUMMARY: Infrastructure "Make iuse a namespace instead of class"
`iuse` is a stateless class, just a collection of functions. Because of this it is not necessary to use a class, and does in some cases force instancing of the `iuse` class.
Change `class iuse` to `namespace iuse`, remove `static` keyword from functions within the namespace, and clean up appearances of `iuse` instances that are no longer necessary.
The function `iuse::wash_items` is only ever called within `iuse.cpp` so its definition can be removed from `iuse.h` and made into a static function.
=> make iuse a namespace instead of class

data/raw/languages.json, doc/TRANSLATING.md, tests/translations_test.cpp
I'm not sure if I'm doing it right. I'll merge it in few hours if no one tells me how to do it better.
Changes:
* Updated docs with BN links. Removed link to discord because discords are mentioned in other files and BN doesn't have a translation channel at the moment.
* Regenerated the .pot file, which, as far as I know, contains all the strings to be translated.
* Renamed the Russian language file from `ru.po` to `ru_RU.po`, because `ru.po` causes Transifex to treat it as a different language, without translators. From what I can tell, those two should still be treated as `ru_RU` internally, with only Transifex really caring about the difference.
=> Language file (.pot) + docs update

src/vehicle.cpp
Port "vehicles: towed vehicles don't set their parking brakes" from dda
Disengage parking brake when towing, this will increase the towing speed and eliminate the dropping of the cable
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/46508
Port from https://github.com/CleverRaven/Cataclysm-DDA/pull/46539
Testing
- Spawn 2 cars and a tow cable
- Connect them
- Try towing one car with another
Additional context
As the author said: "Developer isn't responsible for towing vehicles that stop suddenly and are rammed by their towed vehicles"
=> Disengage parking brake when towing

src/sdltiles.cpp
Closes #457
Partly reverts #455 by hardcoding it to only work on tab key.
We should properly support key modifiers some day, at the moment they scramble the codes, with weird results like CTRL+A being backspace and the like.
=> Allow alt keys except for tab

data/json/flags.json
Closes #472
It was just a wrong description of a correct flag.
Also hid the `"MELTS"` flag for now, it's not supported at the moment.
=> Fix wrong description for ammo belt

src/character.cpp, src/character.h, src/game.cpp, src/iuse_actor.cpp, src/weather.cpp, src/weather.h, tests/behavior_test.cpp, tests/player_test.cpp
Closes #473
Body part immersion check didn't check `in_vehicle`, now it does.
Temperature code is really ugly with its dependence on global state. I refactored some barely related bits here, even though the actual fix itself is 2 lines.
=> Fix vehicles not preventing water temp effects

data/raw/keybindings.json, src/crafting.cpp, src/crafting.h, src/crafting_gui.cpp, src/player.cpp, src/player.h, src/recipe_dictionary.cpp, src/recipe_dictionary.h, tests/crafting_test.cpp
Closes #272
Option to display all recipes, even those the character doesn't know about.
=> Display all (unknown) recipes option in crafting GUI

src/creature.cpp, src/string_utils.cpp
Fix #491
The substring replacement utility function was changed from modify-string-in-place to return-modified-string, but the call site remained unchanged. Rectify that, and fix another similar case.
Spawned zombie, spawned Nodosaur, let them fight. The "zombie bites..." message is now correct.
=> Fix <npcname> not replaced in monster attack messages

data/json/items/resources/wood.json
Increased log volume/weight to preserve conseration conservation of mass and volume and make using charcoal kiln easier since you need to cut less trees to produce more charcoal and give less routine for player.
1) Merge Fix: https://github.com/CleverRaven/Cataclysm-DDA/issues/45607
2) As side effect - it should make using charcoal kiln easier since you need to cut less trees to produce more charcoal. So less tree cutting routine for player.
Manually merge https://github.com/CleverRaven/Cataclysm-DDA/pull/45636
Change log volume/weight from 6/10 to 30/50. 
None.
1) Observe wood log stats
2) Try to fill charcoal kiln with logs. Now it should fit 2 logs instead of 12. So it should make charcoal burning easier. So less routine for player.
Despite being realistic this change also making …
=> Increased log volume/weight to preserve conseration conservation of mass and volume

src/distribution_grid.cpp
Now that's embarrassing: I tried to optimize empty grids by not caching them, reasoning that most grids will be empty.
Every "gridded" submap tile needs some minuscule amount of time to be updated every turn.
But the result was that large empty grids were rebuilt for every single overmap tile of the grid.
Here I remove the premature optimization that caused the problem.
=> Fix very slow empty grids

data/mods/Magiclysm/npc/TALK_HEALER_GREY.json, data/mods/Magiclysm/npc/TALK_OLD_MAGUS.json, data/mods/Magiclysm/npc/TALK_TECHNO_KID.json
Bugfixes, Mods "Giving NPCs necessary dialogues related to missions"
According to [mission docs](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/doc/MISSIONS_JSON.md)
> Any NPC that has missions needs to have a dialogue option that leads to TALK_MISSION_LIST
NPC in Magiclysm mod were assigned TALK_MISSION_OFFER instead of TALK_MISSION_LIST, and while it works for accepting their jobs, it doesn't provide necessary function for them to say that they don't have any more jobs for the player, resulting in 
`src/npctalk_funcs.cpp:102 [void talk_function::assign_mission(npc&)] assign_mission: mission_selected == nullptr`
Except for old magus, who has necessary checks, but I've changed them too in case of future updates with more quests added and to be in line with documentation.
=> Magiclysm NPC mission dialogue fix

src/character.cpp, src/creature.cpp, src/creature.h, src/melee.cpp, src/monattack.cpp, src/monster.cpp, src/player_hardcoded_effects.cpp, src/savegame_json.cpp
Zombie grabs get a minor buff:
* On miss, they only cost 40 moves (down from 80)
* On success, they don't cost anything and instantly follow up with a regular attack and set bite cooldown to 1
Infection no longer kills a player who is currently on antibiotics.
Also removed bugged `throw_resist` and `grab_resist` stats. They were checked, but never set.
As a result, player can now use grab breaking techniques.
=> Buff zombie grabs, nerf infection death

src/game.cpp
Fix #492
Cherry-pick CleverRaven#47473
Dragging a safe over items now swaps safe and items (with safe's contents remaining inside).
=> Port DDA's fix for dragged safe's contents spilling if there is an item in the way

src/map.cpp
Fix #504
Port CleverRaven#45515
Pushed a welding cart off a ledge. With the fix, new carts fall as expected, and old ones cease all bouncing activity.
=> Port DDA's fix for bouncing vehicles

src/animation.cpp, src/animation.h, src/cata_tiles.cpp, src/cata_tiles.h, src/handle_action.cpp, src/item.cpp, src/item_factory.cpp
Implement idle animations.
Turns out UDP already has a bunch of them (e.g. for spore clouds), but they went unused as BN lacks relevant code.
Cherry-picked CleverRaven#40342, then heavily modified it:
1. Made the code request redraws if there are idle animations on screen (required due to changes from #451).
2. If animations are disabled, fall back to showing the first frame of the animation (instead of random frame).
3. Added random stagger to trap/item animations to make them look nicer.
Tested with UDP on:
1. spore clouds and 'Spore dusted' status effect
2. lit torches, both wielded and dropped
3. dissectors
CPU usage stays at ≤1% when none of those are visible, and at ≈8% otherwise.
When animations are disabled, all monsters/items use same tile (and CPU remains at ≤1%).
=> Implement idle animations

src/map.cpp
Fixes #415
The issue was caused by `map::restock_fruits` being only called on load, but relying just on `calendar::turn` and `submap::last_touched`. `submap::last_touched` is updated both on load and on save.
The result was that `map::restock_fruits` couldn't update underbrushes, fruit trees etc. that were in the bubble when the season changed.
The fix is very specific to this particular bug.
`produce_sap` and `rad_scorch` could also fit here, but those two should be called on every save and I decided to gate the update behind season change check, since it's somewhat expensive (requires iterating over all saved tiles).
For now `produce_sap` and `rad_scorch` will stay buggy in that plants in the bubble are not affected by them.
=> Call `map::restock_fruits` on save to respect transform_into for in-bubble plants

src/cata_tiles.cpp, src/cata_tiles.h, src/string_utils.h, tests/cata_utility_test.cpp
Increase FPS
Expand on tileset correctness checks
Port CleverRaven#44917.
That PR changed handling of tiles with same ids (while they used to be completely overwritten by the last such tile, after the change they somehow cause CleverRaven#48819). I don't quite get what's happening there, so as a workaround implemented a check for duplicate ids within a tileset (it seems to have fixed the issue).
Visually checked (with UDP and ChestHole16) tiles for:
* monsters
* corpses
* vehicle parts & their looks_like
* terrain (including trees in all 4 seasons)
* furniture
* items
* clothing overlays
FPS improvement - UDP, in a city, zoomed out:
Same place, RetroDays, zoomed out:
=> Port DDA's optimizations to cata_tiles::find_tile_looks_like + Skip and report duplicate tiles in tileset

src/cata_tiles.cpp, src/cata_tiles.h
Fix sprite replacement mods after #516
Revert 1e0f7b9d89434a83966170db2b27351c379abdcf, overwrite tiles same way as it was before optimizations.
Running around with UDP and changing seasons.
Also tested with sprite replacement mod from CleverRaven#45563
=> Revert "Skip and report duplicate tiles in tileset", fix sprite replacement mods

doc/TRANSLATING_MODS.md, lang/extract_json_strings.py, lang/extract_mod_strings.bat, lang/extract_mod_strings.sh
Implements https://github.com/cataclysmbnteam/Cataclysm-BN/pull/505#issuecomment-835891760:
1. Made string extraction script use mod id as project name if project name is not specified
2. Added `.bat`/`.sh` scripts to automate the other 2 python scripts
3. Updated docs
Tested on Windows and Kubuntu.
=> Simplify mod string extraction

data/json/recipes/recipe_weapon.json
SUMMARY: Bugfixes "Recipe for long poles is now autolearnable and requires heavy wooden beam instead of log matching dda."
The recipe for long pole isn't autolearnable and can be only found in the book textbook_weapeast. 
It is autolearnable in dda and can also be crafted at a lower fabrication level with the book. 
It also requires a wood_beam in dda instead of a single log. This tiny change should match dda and make pikes easier to craft but slightly more expensive.
For comparison:  https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/recipes/other/parts_construction.json
=> Fix recipe for long_pole to match dda

data/mods/DinoMod/NPC/Mr_Lapin.json, data/mods/DinoMod/NPC/NC_Yoshimi.json, data/mods/DinoMod/NPC/NPC_Alonso_Lautrec.json, data/mods/DinoMod/NPC/NPC_Brigitte_LaCroix.json, data/mods/DinoMod/NPC/TALK_NC_FARMER.json, data/mods/DinoMod/NPC/TALK_SURVIVOR_CHEF.json, data/mods/DinoMod/hints.json, data/mods/DinoMod/lab_notes.json, data/mods/DinoMod/mapgen/nested/shack_nested.json, data/mods/DinoMod/mapgen/swamp_shack.json
SUMMARY: [Mods] "More DinoMod NPC content"
Make DinoMod feel more like a part of the world, build out more of the DinoMod plotline and connect with content, more player hints
New dialogue for many existing NPCs. New rope hint. New lab notes. New DinoLab NPC who knows a lot about dinos but won't say much. New location variant to spawn that new NPC.
Extensive references to Dinosaurs Attack!, Land of the Lost, Land Before Time, Dinosaurs, the Dinobots, Dino Riders, Denver the Last Dinosaur, Cadillacs and Dinosaurs, Dinosaur Jr.
Game loads no errors, Yoshimi spawns, looks right, dialogue works. The location isn't where expected and they seem to be moving around in odd ways but it's not game breaking
"What can you tell me about the dinosaurs?" -The player
=> [DinoMod] More NPCs know about dinos

data/json/professions.json
The 'computer hacker' profession came with a laptop but no battery so I have changed it to include a laptop with a battery pre-installed
(after all, who goes out with a laptop and no battery!)
=> Add laptop battery to Computer Hacker profession

data/json/monsters/zed_soldiers.json
SUMMARY: Bugfixes "Fixes black-ops and hunter-killer zombies lacking night cloaking like their description implies."
I was looking at the JSON for black-ops and hunter-killer zombies to double-check whether I had a drop override for them in one of my mods, when I realized they were lacking the `NIGHT_INVISIBILITY` flag, despite their descriptions overtyl stating they're invisible in the dark. From what I could find, there's no sign of this being a deliberate change, it seems to just be a mistake.
1. Gave `mon_zombie_soldier_blackops_1` the `NIGHT_INVISIBILITY` flag, thus also allowing `mon_zombie_soldier_blackops_2` to inherit the flag via its copy-from.
1. Changing the description to not allude to what seems to be literally the primary gimmick of these monsters.
1. Tested for correct …
=> Fix allegedly night-invis monsters lacking the relevant flag

src/ascii_art.cpp, src/ascii_art.h, src/clzones.cpp, src/clzones.h, src/creature.cpp, src/creature.h, src/disease.cpp, src/disease.h, src/init.cpp, src/item.h, src/item_action.cpp, src/item_action.h, src/magic_enchantment.cpp, src/magic_enchantment.h, src/map_extras.cpp, src/map_extras.h, src/mapgen.cpp, src/mapgen.h, src/monfaction.cpp, src/monfaction.h, src/mutation.h, src/mutation_type.cpp, src/overmap.h, src/savegame.cpp, src/savegame_json.cpp, src/skill.cpp, src/skill.h
Map extras are not cleared on data unload, leading to erroneous debug messages when loading world with different mod set (to reproduce, load a world with Dinomod, then a world without Dinomod).
This PR fixes that, and adds clearing code to a bunch more types as a preventive measure.
Also renamed a few things here and there.
=> Clear more types on data unload

src/active_tile_data.cpp, src/item.cpp, src/item.h, src/map.cpp
As in title.
Removed 15% inefficiency from charging stations. It was just small enough not to matter.
Also renamed `item::set_energy` to `item::mod_energy`, because that's what it does.
=> Prevent disabled recharging stations from working

data/json/item_actions.json, data/json/itemgroups/Locations_MapExtras/locations.json, data/json/itemgroups/Locations_MapExtras/locations_commercial.json, data/json/itemgroups/science_and_tech.json, data/json/itemgroups/tools.json, data/json/items/tool/electronics.json, data/json/recipes/recipe_electronics.json, src/activity_handlers.cpp, src/character.cpp, src/consumption.cpp, src/game.cpp, src/game_inventory.cpp, src/harvest.cpp, src/item.cpp, src/item_factory.cpp, src/itype.cpp, src/itype.h, src/iuse.cpp, src/iuse.h, src/mondeath.cpp, src/monster.h, src/savegame_json.cpp
Mass-dissecting corpses when hunting for That One CBM is boring. Now bionics will be pre-generated on monster's death and surgery will only extract them - possibly wrecking them in the process.
The player will be able to notice what bionics are there in the corpse, to see if it's worth the effort. Gamey, let's handwave it as "autodoc tattoos some medical info on implantation, that's how you know what's in the corpse". `// TODO: Put that in lore`
Increased dissection time with bad tools to compensate. 5 times slower with X-acto knife, 1.25 times slower with bionic scalpel.
=> Generate bionics on death, damage them on surgery

src/mongroup.cpp
It is currently visited only if monstergroup with such id already exists, so depending on mod loading order may cause "unvisited member" warning.
=> Always visit 'override' field in monstergroup definitions

src/mattack_actors.cpp, src/mattack_actors.h, src/mondefense.cpp
Return fire rework.
The monster defense function for return fire has a bunch of things done wrong. It copies a large block of the gun actor instead of using it.
- Doesn't error when gun function is not found (ideally, it would be checked in MonsterGenerator::check_monster_definitions())
- Doesn't initialize the NPC in the same way (stats, skills)
- Won't work for weapons that require UPS
- Is a copypaste instead of proper function reuse
There's also the issue of return fire intentionally not working against throwing, which makes it easy to cheese it. The sound check could be changed to just an extra accuracy penalty if the source can't be heard.
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/81
Result:
1. Now return fire will work for shooting throwing, melee. Obvious expoits …
=> Return fire rework

data/json/npcs/refugee_center/surface_refugees/NPC_Guneet_Singh.json
SUMMARY: Bugfixes "Fix buggy weapon duplication caused by NPC spawning with wielding a contained weapon"
This updates Guneet Signh's weapon spawn to be consistent with how Maldeep and Mangalpreet's weapons are spawned, having them all start wearing the weapon in its sheath/scabbard, instead of wielding the whole thing, scabbard and all.
This prevents the issues that cropped up due to https://github.com/cataclysmbnteam/Cataclysm-BN/issues/559, but does not fix whatever weirdness may be the underlying cause. Since NPCs probably should be set to spawn either wearing a contained weapon, or wielding their weapon while wearing its intended container separately, this is probably a low-priority bug. Spawning holding a sword in its scabbard is a fairly weird state of readiness to be in.
1. Changed …
=> Fix Guneet being able to duplicate his sword

data/json/effects.json, src/monster.cpp
* Fix #571 by removing "permanent" from `earphones` effect.
* Fix musical instruments by removing "permanent" from `music` effect.
* Add "max_duration" to both to fix affected saves.
* Add "permanent" to `sleep_deprivation` effect to match other fake effects.
mp3, violin.
=> Fix permanence for some effects

src/activity_handlers.cpp, src/iuse.cpp
Closes #567
Two fixes:
* Bionic detector now ignores not-bionic items more consistently
* Surgery messages are more specific, saying "You ruined this bionic/organ" rather than "You found a ruined bionic/organ"
=> Display fixes for new bionic butchering

data/json/construction.json, data/json/furniture_and_terrain/furniture-appliances.json, data/json/items/fake.json
SUMMARY: Content "Adds grid-powered options for kilns and a few electric cooking tools"
I finally started looking into the grid-based applicances to see how that worked, and decided it'd be fairly easy to add a few extra options. Went with fairly simple stuff for the time being, basic things that are readily used in recipes.
1. Added a construction for plugging an electric brick kiln into the grid.
2. Three basic food-related grid options as well. Dehyrdators, food processors, and vaccuum sealers. Decided to keep it fairly simple as far as food-related tools go.
1. I was tempted to see how well a grid-installed FOODCO kitchen buddy would work, but I don't think an item can be set to substitute for mulitple tools, so it wouldn't have really been doable.
2. Makeshift vacuum sealers could …
=> Add a few more grid-powered constructions

src/map.cpp, src/vehicle.cpp
Vehicles leaking fuel while outside reality bubble cause spammy debugmsg on current build.
Prevent fuel leaks if vpart is outside reality bubble.
Allow leaks, but erase leaked fuel? I have no attachment to either solution.
Took a walk around a city.
=> Prevent fuel leaks if vpart is outside reality bubble

src/npcmove.cpp
Fix #559
Ignore holster contents if the holster is wielded.
The save stopped crashing.
Moreover, Guneet now puts on his scabbard and only then pulls out the scimitar. I'll chalk it up to him considering it a good armor.
=> Prevent NPCs from wielding from inside of wielded holster

src/character.cpp, src/item.cpp
This crutch should counteract all sources of thirst and hunger NPC may be affected by.
Fixes #579.
Includes a nice change ported from CleverRaven#47336 that adds item's `itype_id` to debug item info display.
In provided save, NPC now asks for water only if needs are enabled (`no-npc-food` mod is removed before load).
NPCs gain thirst/hunger without the mod, stay satiated with it.
Avatar thirst/hunger gains are unaffected.
Faction camps still require food for operation.
=> Keep NPCs satiated if NPC needs are disabled

src/generic_factory.h, src/material.cpp, tests/generic_factory_test.cpp
Optimize rotting corpses
Port CleverRaven#44544
In a test scenario (blind avatar waiting in a middle of a city) `materials::get_rotting()` went down from ≈12% to 0%.
The next expensive calls in item processing are `get_heat_radiation()` with total of ≈22%.
=> Port speedup for `materials::get_rotting()`

src/armor_layers.cpp, src/character.cpp, src/character.h, src/game_inventory.cpp, src/inventory.cpp, src/pickup.cpp, src/player.cpp, src/player.h
Fix #607.
Remove the debugmsg as the rest of the code seems ok with NPCs having invlets.
Clear all invlets in NPC's inventory instead (as they don't use them anyway), but that breaks invlets in "select item to steal" menu.
There's no more debugmsg when selecting a book for NPC to read.
=> Fix debugmsg on NPC inventory restack

src/magic_spell_effect.cpp
If `min_duration` is not specified in spells, it defaults to 0.
If duration of permanent effect is 0, it's removed during turn processing as expired.
However, requiring a permanent effect to have any kind of duration specified is somewhat counter-intuitive.
This change ensures permanent effects from spells get at least 1 second of duration when applied.
Alternatives: always use 1 second for permanent effects applied from spells? Enforce 1-second duration for all permanent effects? Don't remove permanent effects if their duration is 0? I imagine the latter may cause division-by-zero crashes, and the other 2 may restrict possible mechanics centered around effect duration (does it matter, if effects can have intensity anyway?)
=> Fix permanent effects from spells require min_duration

src/generic_factory.h, src/item_factory.cpp, src/missiondef.cpp, src/recipe_dictionary.cpp, src/veh_type.cpp
Fix #384.
Clear deferred JSON on data unload.
The actual change that fixes the issue is addition of `deferred.clear()` in `Item_factory::clear()`, the rest is added for the good measure.
Retraced reproduction steps, debug message no longer shows up.
=> Clear deferred JSON on data unload

src/action.cpp, src/action.h, src/avatar.cpp, src/cata_tiles.cpp, src/debug_menu.cpp, src/game.cpp, src/game.h, src/handle_action.cpp, src/lightmap.cpp, src/lightmap.h, src/map.cpp, src/map.h, src/map_field.cpp, src/mattack_actors.cpp, src/scent_map.cpp, src/submap.h, src/teleport.cpp, tests/ground_destroy_test.cpp, tests/npc_test.cpp, tests/shadowcasting_test.cpp, tests/vehicle_split_test.cpp, tests/vision_test.cpp
Fixing bugs, improving performance.
PRs being ported:
CleverRaven#41741
CleverRaven#44093
CleverRaven#44112
CleverRaven#44181
CleverRaven#44108
Also some changes from CleverRaven#41935 to minimize merge conflicts.
Removing cobwebs now properly updates vision.
Player sprite and neighboring tiles are now visible when in thick smoke.
In best-case test scenario (3D FoV on, avatar in clear field and a small enclosed room 2 submaps away with a smoke vent inside) waiting for 2 in-game hours went down from 33 seconds to 12 seconds.
That cache copy bug was as insane performance hog actually:
=> Port improvements & fixes for transparency and seen caches

src/game.cpp
SUMMARY: Bugfixes "Fix two bugs with vehicles spawned by scenarios and professions"
Per discussion in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/594 I tested two suggested code changes that turned out to be simple, and fixed both the main issues without any apparent problem.
And thanks to Olanti's advice, it can now spawn near the player if there is adequate space, so all three problems found in the issue are solved.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/594
1. Moved the vehicle-placement section in `game::start_game` to occur before the `build_map_cache` and `update_map` bits Fixes spawned vehicle taking several seconds to apparently magic its way in out of thin air, and (together with setting it to allow a minimum radius of zero) fixes the issue of it …
=> Fix bugs with vehicle-spawning scenarios/professions

data/json/items/armor/belts.json
SUMMARY: Balance "Adds a belt-clip use action to webbing belts"
On noticing this item on a military profession, I was curious what it could hold only to find it completely lacked any storage or even the ability to clip something on it, something even the generic leather belt has. I checked to see if maybe DDA had something implemented for it and nope, so put together a basic belt-clip storage action for it for consistency.
Added a `holster` use action to the webbing belt. Based primarily off the stats used by the standard leather belt, with weight and volume allowances in between leather belts and police duty belts, while retaining the leather belt's slightly high draw cost.
Making it have pouches to represent ALICE and MOLLE belts, but modern MOLLE equipment would most likely be already …
=> Add a use to military webbing belts

data/json/overmap/overmap_special/specials.json
SUMMARY: Bugfixes "Re-adds ELECTRIC_GRID flag accidentally removed from mansions and evac shelters, allow add grids to two more locations"
Quick and easy fix once it was noticed that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/515 accidentally removed the `ELECTRIC_GRID` flag from the overmap specials they were used in.
Discussion in the BN discord led to giving grid support to two more locations that would be an easy and obvious fit for them, LMOE shelters and the Tacoma Ranch.
1. Added the `ELECTRIC_GRID` back into all overmap specials that previously used them. That would be all variants of evac shelters, and all variants of mansions.
2. Added `ELECTRIC_GRID` to LMOE shelters and the ranch camp.
~~Could add electric grid support to a few other locations. The ranch camp and …
=> Re-add missing electric grids to shelters and mansions

data/mods/DinoMod/NPC/NC_Yoshimi.json, data/mods/DinoMod/mapgen/swamp_shack.json
SUMMARY: [Mods] "DinoLab mission chain"
Build DinoLab story, tie together new dino mutagen content, tee up eventual DinoLab project
First mission for Dr. Yoshimi to get a chemistry set, reveals a (generic for now) lab and spawns  a zombie dino there to fight. Second mission to get a recipe book at the existing field exhibit, spawns a zombie scientist and zombie dino to fight.
Just build the stupid lab already
Game loads no errors. Yoshimi spawn looks good now.
Conversational flow is fixed.
First quest works, map spawns, monster and item spawn. 
Item works to end the quest correctly. 
Second quest throws the right mission and the monsters looks good
“I've seen things you people wouldn't believe" -Bladerunner
=> [DinoMod] DinoLab missions

CMakeLists.txt, build-scripts/build.sh, lang/CMakeLists.txt, src/language.cpp
Closes #616.
Solution: get all files that match `lang/po/*.po` and build a list out of their names
Testing: Local tests with CMake confirm it generates a ninja build that compiles _all_ language files on `ninja translations_compile` invocation.
---
Closes #629.
* For `Make` builds, add `LANGUAGES="all"` (it was removed in https://github.com/CleverRaven/Cataclysm-DDA/pull/47077 for some reason, and that change slipped into BN during Travis->GA migration)
* For `CMake` builds, compile language files before running tests
Testing: Github Actions.
=> Fix translation tests in CI

data/json/effects.json, src/activity_handlers.cpp, src/character.cpp, src/game.cpp, src/monattack.cpp, src/mondeath.cpp, src/monexamine.cpp, src/monmove.cpp, src/npc.cpp
Fixes #633.
Fix dancer zombies not dancing.
Fix blobs freezing in place around brain blob.
Split `controlled` effect into 2:
`ai_controlled` for use in Thriller's and brain blob's special attacks (makes creature follow predefined plan)
`ai_waiting` for horses (makes them stay still until effect expires)
Making `controlled` not permanent, but then after some digging I realized the effect was broken in 596d44984dc6a072f67c8b031228dc1f790beaa4 and repurposed to make horses stay in place. This PR reverts these changes, and implements a more careful solution.
Zombies dance, blobs swarm, horses can be repeatedly mounted.
Broken horses from existing saves become unbroken (game shows a couple debug messages, but they can be safely skipped).
We should totally have dancers in vanilla.
=> Fix controlled monsters

data/raw/keybindings.json, src/color.cpp, src/color.h, src/mapdata.cpp, src/output.cpp, src/output.h, src/overmap.cpp, src/overmap.h, src/overmap_ui.cpp, src/overmapbuffer.cpp, src/overmapbuffer.h, src/sdltiles.cpp, src/string_input_popup.cpp, src/string_input_popup.h, src/string_utils.cpp, src/string_utils.h, src/ui.cpp, src/ui.h, tests/cata_utility_test.cpp
Fix a couple bugs, add a couple QoL features. Closes #482.
See commits.
New features:
* Show notes from all Z levels, show direction from `g->u`'s pos to that note
* Show note's danger radius in the list, or whether it is inside danger radius of some other note
* Allow sorting by name(default)/distance/symbol
* Retain sort order, filter and cursor position after editing / deleting a note
* Allow temporarily disabling 'Really delete note?' popup
Includes bugfixes ported from DDA:
https://github.com/CleverRaven/Cataclysm-DDA/pull/43220
https://github.com/CleverRaven/Cataclysm-DDA/pull/46768
https://github.com/CleverRaven/Cataclysm-DDA/pull/48190
Loading various worlds, adding/deleting notes with/without filter/specific sort order.
Along the way discovered that MIN_RANGE/MAX_RANGE marks that …
=> Improve om notes manager

src/cata_tiles.cpp
Fix false positive unvisited member warning if JSON file has mod_tileset entry and an entry of some other type.
If entry is not of `mod_tileset` type, allow unvisited members, as their detection is handled by whatever code is actually responsible for loading that type.
Modified version of Aftershock for testing: [aftershock_with_misplaced_fields.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/6797060/aftershock_with_misplaced_fields.zip)
Without fix: throws a dozen of 'unvisited member' warnings.
With fix: throws only 2 warnings, for genuinely misplaced fields `unvisited_1` and `unvisited_2`.
=> Fix false positive unvisited member warning if JSON file has mod_tileset entry and an entry of some other type

src/clzones.cpp, src/clzones.h, src/init.cpp
Fixes #635.
Fixes zones from one save appearing in different save if both have been loaded in single session and there was no zones file in the second save.
1. In mapgen, restrict zone rotation to z-level being generated.
2. Reset zone manager during finalization (after zone types have been loaded, but before actual zones are loaded). 
Also fixing non-player zones (see https://github.com/CleverRaven/Cataclysm-DDA/issues/49755), but the more I looked into them the more I realized they may need a complete refactor. There is no "worldwide" zone handling; zones are handled on per-character basis, to the point that they can only be saved via Zone Manager UI.
For now, non-player zones in BN are considered unimplemented.
Save for testing: …
=> Fix zone generation rotates zones on all z levels; clear zone manager on new game

src/avatar.h, src/character.h, src/creature.h, src/json.h, src/mission.h, src/npc.h, src/player.h
Make UBSan in CI happy
Add initialization to misc members in `Creature` family and couple other classes.
Not all of this is necessary, but UBSan was tight-lipped on what fields exactly it didn't like, so I went with _all_ of them for the good measure.
All tests pass on local copy built with asan+ubsan
=> Add initialization to misc class members

src/path_info.cpp
SUMMARY: Bugfixes "Fix the bug that looking wrong path for data directory"
When building with flag 'PREFIX', as you can see we install our data at "$(PREFIX)/share/cataclysm-bn/".
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/77f9aa72350084cd6dad139fb761bd0161d1daab/Makefile#L909
But if you look at here, 'datadir_value' is set to "share/cataclysm-dda/" when built with flag.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/77f9aa72350084cd6dad139fb761bd0161d1daab/src/path_info.cpp#L82-L84
Fix the path at 'src/path_info.cpp'.
I was able to lauch the game without problem.
=> Fix the path of data directory

data/json/items/classes/gun.json, data/json/items/fake.json, data/json/items/gun/bio.json, src/character.cpp, src/item_factory.cpp
Fix CTD when trying to ignite an item while having flamethrower in the inventory.
This is caused by `Character::has_fire` assuming that chargeless items with `FIRESTARTER` flag also have `firestarter` iuse func (flamethrowers do not), and dereferencing a null pointer.
Add a check that warns if `FIRESTARTER` item neither can have charges nor has the `firestarter` iuse.
Disallow using flamethrowers as lighters, but nothing else is good enough if one wants to have a smoke _with style_.
Game no longer crashes.
Since flamethrowers are neither tools nor count-by-charges, using them to light a cig does not deplete fuel. I don't think that's a big deal since by the time the player gets a flamethrower they're most likely already in possession of (near-)limitless firestarting capabilities.
=> Fix CTD when trying to ignite an item while having flamethrower in the inventory

src/game.cpp, src/game.h
Fixes #648, which occurs when character dies, but there is already a character with the same name in the graveyard.
This may happen when character duplicated due to a bug, or when player repeatedly tries and fails to survive in different worlds and gives their character same name on each attempt.
Create per-character folders inside graveyard. The folders follow the memorial's naming scheme of name + timestamp, thus mitigating possible filename conflicts.
Delete graveyard folder, load a world, die. Character gets moved to a newly created subfolder inside newly created `graveyard` folder.
=> Create individual folders for characters in graveyard

src/lightmap.cpp
Fix ascending with helicopters to z=10
Don't try to build lightmap for the non-existent z=11
There is no more crash
=> Fix CTD when ascending to z=10

src/vehicle_part.cpp
Fix #612.
Cause: when amount consumed equals amount in the tank, the item that represents fuel is left with 0 charges, but is not removed from the tank. In case of e.g. a Portable Generator, consumption rate is 1 unit of gasoline per turn, so any amount of fuel ends up leaving invalid item.
Fix condition
Repeated steps from the issue, observed absence of the bug.
=> Fix fuel tanks not depleted properly when engine is idling

.github/workflows/release.yml
Enable backtraces in release versions
Remove `BACKTRACE=0`. For win build, also install mxe version of `libbacktrace` same way Travis used to:
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/477b74802f798bb768df933f81e3a49061ec9216/build-scripts/requirements.sh#L66-L80
Ran the workflow in a fork, locally tested Win/Linux tiles releases produce `crash.log` when triggering crash via debug menu.
OSX release compiles, but I can't test further.
https://github.com/olanti-p/CataclysmExpBN/releases/tag/cbn-experimental-2021-07-12-1918
=> Enable backtraces in releases

src/item.cpp, tests/iteminfo_test.cpp
SUMMARY: Balance "Scale default encumbrance for non-rigid items at 2 per liter held, instead of 4 per liter"
Per discussion in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/669 it was suggested that I start with changing how the hardcode default affects the encumbrance of non-rigid items, at least when they lack a defined max_encumbrance. Turns out it's rather easier than I first thought to change the hardcode default scaling.
Changed `game::get_encumber_when_containing` to divide encumbrance penalty by 500 milliliters instead of 250 milliliters for non-gun items. Wearable guns has its own special-case modifier evidently designed to make bulky guns a bit less encumbering than even my planned modifier, so left it alone for now.
Setting explicit max_encumbrance for more non-rigid …
=> Update default for how encumbrance scales for non-rigid items

data/json/furniture_and_terrain/terrain-windows.json, src/map_field.cpp
SUMMARY: Bugfixes "gases can pass on/through open windows"
Allow gases or anything that uses `propagate_field()` to enter a window tile. From there it should pass onto other allowable tiles, so gases should now pass through windows.
Fixes #568
~Change the `if()` check to skip propagation from `not permeable` to `not window and not permeable` and `window and block_wind`~ **(Reverted)**
Added `PERMEABLE` to applicable window types.
~Need help writing tests. Not sure where to begin with writing a test (have reviewed other test files).~
In-game test shows smoke passing through `window frame with metal bars`.
=> fix open window tiles to be permeable

CMakeLists.txt, CMakeModules/AstyleFormatSource.cmake
SUMMARY: Build "Add astyle to CMake build process"
Make astyle prettification automatic as part of the build process.
Add a CMake module for astyle using the project's `.astylerc` and include it in CMakeLists.txt.
=> Add astyle to CMake build process

src/language.cpp, src/units.h, tests/stomach_contents_test.cpp
SUMMARY: Build "Fix errors preventing build"
Main branch failed to build on `linux64` using both `Make` and `CMake` due to several errors from the compiler.
These changes make it so that there are no build errors preventing the build process from completing without changing build options.
Fixes #665
Please see documented commits.
Considered changing `-W` flags, but only 2 errors needed to be fixed.
Build process completes with no errors.
=> Fix build on linux64

data/json/items/tool/handloading.json, data/json/recipes/ammo/40x46mm.json, data/json/recipes/ammo/40x53mm.json, data/json/recipes/ammo/shot.json, data/json/recipes/recipe_obsolete.json, data/json/requirements/toolsets.json
SUMMARY: Balance "Update shotshell handloading to be more consistent, make more use of makeshift press"
While reviewing the recipe for handloading shotshells, I noticed how wildly inconsistent and bizare the tool requirements were. Standout problems with it were:
1. Recipes split up into variants that were almost identical aside from a tiny difference in time, presence/absence of batch mlutiplier, and use of the makeshift dowel press instead of a regular press. Otherwise still involved bullet casting.
2. Water requirement for bullet casting allows you to infinitely reuse clean water, salt water, or sewage, but set it so you had to use larger and larger amounts if using regular water.
3. The tools required for casting bullets are defined in a way that's not mod-friendly, doesn't make it …
=> Update shotshell recipes to be more consistent

.github/workflows/release.yml, changelog.json
SUMMARY: Build "Add changelog to releases"
Allow users to see the release changes without digging through PRs.
Added a Github action to auto-create a changelog for releases. The downside is an additional 3 minutes to create a release due to having to fetch all refs from the repo. Could not get it to work without fetching all refs.
Simpler, faster alternatives are not feasible without using semantic version tagging.
Tested to be working properly on my fork.
Screenshot of it working:
https://i.imgur.com/1R5wBCO.png
=> Add changelog to releases

data/mods/DinoMod/mutations/mutations.json
SUMMARY: Bugfixes "Duplicate mutation entry caused CTD"
Fixes CTD
deletes duplicate entry. Thanks to Cuddlebaby for finding the effect and cause. Based on https://github.com/CleverRaven/Cataclysm-DDA/pull/49919
Wait for a later rollup but this is time sensitive
NA
Thanks to @Maleclypse for figuring this out
=> [DinoMod] Duplicate entry caused CTD

data/mods/DinoMod/monstergroups/wilderness.json
SUMMARY: Mods "DinoMod wilderness spawn counts and fixes"
Count wilderness spawns, measure against vanilla spawns, balance so that all dinos actually spawn as intended (they weren't) and don't overwhelm swamps in late game
Count all dino spawns in wilderness, document, balance against what is documented in vanilla, make sure new dinos like amargasaurus spawn
Move dinos to special locations and back off the wilderness lists entirely
Loads no errors, more dino types appear as expected
Ported from https://github.com/CleverRaven/Cataclysm-DDA/pull/50184
=> [DinoMod] wilderness spawn counts and fixes

tests/player_helpers.cpp
`avatar::consumption_history` was not cleared in `clear_character`. Normally, it only clears with passage of time.
ASan probably made it consume much more memory than it ordinarily would.
=> Attempt at fixing ASan memory problem

.github/workflows/matrix.yml, src/output.cpp, tests/effective_dps_test.cpp
* Disabled sounds on ASan/UBsan builds
* Prevented scrolling combat text from appearing in test builds
* Reset (in-game) sound list in dps test
=> Potential fixes for ASan out of memory issue

data/json/recipes/ammo/components.json
SUMMARY: Balance "Allow using match head powder as a source of impact-sensitive material for primer crafting"
A while back I recall there having been discussion of using match heads as an option for making primers. Rationale being, if you mix the main material from matchheads with that of the striker surface (or the entirity of the matchhead, in the case of strike-anywhere matches), you get an impact-sensitive material that people have successfully tested using for pistol primers.
First video example I was able to find, evidently a reupload of a video I'm going to guess was the source of this idea: https://www.youtube.com/watch?v=CQI2bvkE7ic
Added match head powder to primer recipes as an alternative to oxidizer powder, at equal amounts by weight.
1. Having the added amount equal oxidizer …
=> Allow match head powder for primer recipes

data/json/harvest.json, data/json/itemgroups/bionics.json, data/json/monsters/zed_electric.json
SUMMARY: Balance "Have zapper zombies yield CBMs instead of relying on blob magic"
I mentioned pondering the idea of giving basic bionic spawns to zapper zombies, consistent with how BN is avoiding the "no bionics from zeds, they run on blob magic" development DDA is leaning towards, which was the reason why the original proposal of having zapper zombies yield CBMs was vetoed back when they were first added.
Per said conversation on the modder's discord, a suggestion came up to focus on power storage/generation, similar to broke cyborgs, thus making their yield useful while still encouraging the player to favor shocker zombies. Should be interesting for early-game characters wanting to break into the basics of bionics, and helps reinforce BN's retention of manmade CBMs as a contrast to …
=> Add bionics to zapper zombie

src/iuse.cpp
SUMMARY: Bugfixes "Fix use of strong and weak antibiotics on tetanus"
Fixes #678
`antibiotics` has a 33% chance to cure tetanus. Based on this, made `strong_antibiotic` have a chance of 70% and `weak_antibiotic` a chance of 16%.
No testing done.
=> fix antibiotics on tetanus

data/json/items/comestibles/drink_other.json
SUMMARY: [Balance] "Make cooking oil unhealthy"
Cooking oil doesn't have unhealthy value, which most players would assume to be true. Make it so. Our survivors should probably try to find a more befitting food source than drinking gallons of oil months on end.
Also, today I learned that, while olive oil is particularly good for you, vegetable oil is not:
https://www.jeffnobbs.com/posts/death-by-vegetable-oil-what-the-studies-say
Make cooking oil unhealthy
N/A
Drink cooking oil in large batches and debug check our healthy stat
Copied from origin PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/49758
=> Port make cooking oil unhealthy

src/monster.cpp, src/monster.h
Features: "Ports change to add relative monster speed to look menu and adds extra debug info to extended monster descriptions"
Adds colour-coded monster speed relative to the player speed to the look menu, as well as advanced debug info to the extended description.
With very minor changes, this PR implements:
https://github.com/CleverRaven/Cataclysm-DDA/pull/47153 `Add speed to monster descriptions`
https://github.com/CleverRaven/Cataclysm-DDA/pull/47252 `Change monster description speed colors`
https://github.com/CleverRaven/Cataclysm-DDA/pull/48481 `Adjust formula for monster speed descriptions`
I also implemented the changes from auto to proper function calls and making `monster::can_upgrade()` const as that just made sense.
All tables in this PR have been updated with the correct …
=> Port relative monster speed to look menu

doc/COMPILING/COMPILING-CYGWIN.md, doc/COMPILING/COMPILING-MSYS.md, doc/COMPILING/COMPILING-VS-VCPKG.md, doc/COMPILING/COMPILING.md, msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-test-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-vcpkg-static.vcxproj, msvc-full-features/JsonFormatter.vcxproj, src/main.cpp
1. Fix #380
2. Fix sound not working in Visual Studio build
3. Update compilation instructions for Visual Studio, MSYS2, Cygwin and MXE
(based on https://github.com/CleverRaven/Cataclysm-DDA/pull/46830)
4. Add instructions on how to install MXE via APT (which is much faster than compiling it from source)
Existing Visual Studio environments shouldn't be affected in any way. To fix the sound, `sdl2_mixer` may need to be manually reinstalled.
For x64:
```
.\vcpkg --triplet x64-windows-static remove sdl2-mixer
.\vcpkg --triplet x64-windows-static install sdl2-mixer[libflac,mpg123,libmodplug,libvorbis]
```
Fox x32:
```
.\vcpkg --triplet x86-windows-static remove sdl2-mixer
.\vcpkg --triplet x86-windows-static install sdl2-mixer[libflac,mpg123,libmodplug,libvorbis]
```
MSYS2 builds are pretty …
=> Update Windows compilation docs, fix couple issues with Visual Studio and MSYS builds

src/character.h, src/martialarts.cpp, src/martialarts.h, src/melee.cpp
SUMMARY: Bugfixes "Port over fix to martial arts armor penetration"
The issue with martial arts arpen was fixed in DDA, figured I'd port it over when I got a chance to.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/637
1. Ported addition of a def for `mabuff_arpen_bonus` to character.h.
2. Ported `ma_buff::arpen_bonus` and `Character::mabuff_arpen_bonus` to martialarts.cpp.
3. Ported def for `arpen_bonus` to martialarts.h.
4. Ported changes to melee.cpp that make melee damage actually take arpen into account, converted to BN's older method of specifiying damage types.
Pestering someone else to do it.
2. Debugged in max skills and all martial arts.
3. Tested punching an armored zombie with brawling skill, and hitting them with an arming sword …
=> Port over fix to martial arts arpen

src/veh_interact.cpp
Closes #389
Pre-disable values, for reference:
| # of engines | mechanics lvl |
|-|-|
1 | 0
2 | 8
3 | 12
4 | 14
| >=5 | 15
Rebalance was done on the following conditions:
* Installation cost of additional engine should be higher than installation cost of most difficult installed engine
* Installing more engines should progressively require more skill
* We can't go over lvl 10 with requirements and nobody liked limited engines, so let's allow _all_ the engines at lvl 10.
And based off the following numbers:
* `Under the hood` (raises to lvl 3) is described as "advanced mechanics manual", which is enough to install low-power combustion engines, but IMO should be _far_ from "explains how to install 2 engines".
* Repairing low-powered and installing medium-powered engines and motors requires …
=> Reenable 3+ engines for vehicles and rebalance required mechanics skill

data/json/furniture_and_terrain/furniture-plumbing.json
Features:  "Add wax to toilets"
Toilets will yield 1 wax when smashed. This copies the DDA PR for the same purpose: https://github.com/CleverRaven/Cataclysm-DDA/pull/45472
The reasoning is that wax is very handy for making candles and a couple of other early game items, but is generally hard to find. FWIW real life toilets do generally contain wax rings at the base. 
Coped over changes from the original PR.
Amount of wax seems appropriate at 1 as this allows for 1 candle to be made.
Compiled release build, spawned in and smashed toilets to verify.
I don't care about the realism of wax in toilets so much as the relatively easy way to scrounge up a toilet candle when in need. Mostly this is just a feature I enjoyed in the other branch and would love to see here.
=> Port addition of wax to toilets when smashed

src/sounds.cpp
SUMMARY: Interface "Noise made by controlled vehicle added to sound indicator"
While driving a vehicle, noises made by it should be displayed, but these can come from far enough position not to count as heard sound.
Sets `player.volume` appropriately using `vehicle.vehicle_noise`, already calculated by `vehicle::noise_and_smoke`.
`veh_pointer_or_null `shouldn't return `nullptr`, since only called when `p->controlling_vehicle` is `true`.
Loaded test world, located vehicle, started engine, let go controls, walked to the back near muffler, from where the sound is coming.
Watched sound indicator rise, fall and rise again.
Copied from origin PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/46544
=> Add noise from driven vehicle to displayed sound

data/json/monsters/insect_spider.json, data/json/monsters/triffid.json, data/json/monsters/zed-classic.json, data/json/monsters/zed_children.json, data/json/monsters/zed_explosive.json, data/json/monsters/zed_misc.json, data/json/monsters/zed_soldiers.json, data/json/monsters/zed_survivor.json, doc/JSON_FLAGS.md, src/monster.cpp, src/monster.h, src/monstergenerator.cpp, src/mtype.h
Infrastructure: "Jsonize fungalize_into"
Fixes #462 by porting the Jsonize fungalize_into changes from DDA.
`fungalize_into` json property works similar to zombify_into
`MF_NO_FUNG_DMG` grants immunity to spore damage and fungalization
Copied the implementation from the DDA branch with some tweaks to more closely match the way 'zombify_into' was implemented in BN. 
Compiled release build. Individually spawned & tested each monster with fungalize_into or MF_NO_FUNG_DMG specified (using fungal blooms in an enclosed space), as well as some randoms to test against. Works as expected.
=> Jsonize fungalize_into

data/json/furniture_and_terrain/terrain-doors.json, data/json/gates.json
SUMMARY:bugfixes "Garage gate have now open variant to fix #747 issue."
Garage gates were transforming into wooden floor thus Mechanical winch when constructed next to a specific walls with wooden floor between those walls could spawn metal garage door out of thin ~~air~~ floor. 
I created opened variant for garage gates and swapped it with "t_floor" in the transformation code.
Works fine. If there are locations with "garage gate" that was open but possible for the player to operate trough Mechanical winch, it wont be there. Because they used floor as open variant for garage gates it will be just floor. At least there are barely any locations with "open" garage.
On the pros side is also that me or SDG can make some nice sprite for open gate.
Also, why does the `t_mdoor_frame` etc leave …
=> Mechanical winch spawnig gate between walls fix #747

data/json/items/ammo_types.json, data/json/items/resources/glass.json, data/json/items/tool/traps.json, data/json/recipes/recipe_others.json, data/json/recipes/weapon/explosive.json, data/json/requirements/materials.json, data/json/vehicleparts/wheel.json
SUMMARY:Bugfixes "Can bomb recipe use present materials, Wheels use rubber instead of plastic for repair, Glass shards are AMMO."
More realism 😂 for repairing vehicles. Being able to craft Can bomb. Glass shard wont lag game that much anymore.
Adjusted recipe for **Can bomb** (by PoshOctavia)
Created 2 new  requirement materials for repairing installed vehicle parts, `rubber_chunks` and `metal` that contain `metal chunk` and `small metal sheet` .
Replaced `plastic chunks` with `rubber chunks` in all wheels with rubber tires. Added `welding` and `metal` requirements to repairing **Armored wheel** and `metal` to **Drum wheel**
Created new ammo type for **Glass shards** and changed them to be the "AMMO" instead of "TOOL"
Repairing rubber wheels could use fire or heat source.
Tested, found …
=> Minor fixes for Can bomb, Tires and Glass shards

data/json/itemgroups/Locations_MapExtras/locations.json, data/json/items/ammo.json, data/json/items/ammo_types.json, data/json/items/obsolete.json, data/json/recipes/ammo/weldgas.json
SUMMARY: Balance "Make oxygen tanks usable for making oxy-ace, obsolete redundant oxygen item"
As noticed during discussion of the industrial center PR, the type of oxygen item used for the oxy-acetlyene recipe was basically unobtainable, and seemed to have been added as an afterthought that ignored there already being three different sources of compressed oxygen in the game.
1. Updated the oxy-ace recipe to use charges of oxygen packs, tanks, and cylinders as tools instead of using raw oxygen as a component. The ratio was based off use of oxygen in Cata++ for makeshift thermal lances, as can be seen here: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/blob/master/nocts_cata_mod_BN/Recipe/c_recipes.json#L1997
2. Amount of oxygen cylinder charges and acetylene used to make oxy-ace …
=> Update oxygen usage of acetylene recipe

data/json/vehicleparts/doors.json
Summary: Features "Created Left and right variants Hd_Doors and Hatches to make it possible to use new UDP sprites."
Created entries that already existed in UDP json because DDA use them.
Some vehicles might need slight fixes, like this humvee there using front/rear variant instead of left/right variants.
https://user-images.githubusercontent.com/37194372/128952923-b679705e-a659-46e9-9735-923bb0f60055.mp4
=> Left and right variants Hd_Doors and Hatches

src/avatar_action.cpp
The game would check all firing modes to determine if the gun can be aimed in current mode.
The result: a gun with bayonet or a gunmod that is a gun could aim if any of the modes is usable.
Fixes #743
Fixes #757
=> Check only current mode when firing a gun

data/json/flags.json, data/json/items/comestibles/other.json, src/consumption.cpp
Mycus characters can't easily balance kcal vs quench, so they should be able to eat when full.
I added a new flag - `NO_BLOAT` - which makes a food item exempt from usual bloat->vomit mechanics. It lets non-mycus characters overeat those, which is a tiny "flavor" bonus.
=> Make mycus food ignore bloating

data/json/items/ammo.json, src/item.cpp, src/veh_type.cpp, src/vehicle.cpp, src/vehicle_display.cpp, src/vehicle_move.cpp, tests/vehicle_efficiency_test.cpp
Fix fuel usage estimate in vehicle UI.
Fix turret damage estimate in vehicle UI.
Fix moving in reverse does not consume fuel for acceleration.
Fix emotors consider 1 battery charge as 2.5kJ worth of energy, not 1kJ as the rest of the code does.
For fuel estimate, fix calculations in `vehicle::consumption_per_hour()`. I'm not sure what it was calculating before (some legacy value?), but now it calculates fuel consumption in millilitres based on joules consumed this turn. Also, display code assumed that returned value was in charges, which broke display for non-1-millilitre-per-charge fuels -- added proper conversion for that.
For battery energy density, "energy" field of fuel islot is per-millilitre, so make 1 charge of battery be 1mL.
Other fixes were ported from DDA: …
=> Misc fixes for vehicle efficiency, fuel usage estimate and vehicle UI

src/crash.cpp, src/debug.cpp, src/loading_ui.cpp, src/main.cpp, src/player_hardcoded_effects.cpp, src/popup.cpp, src/sdl_wrappers.h
Closes #787
Clang 12 needs to be specifically informed not to use `-Wold-style-cast` when including `SDL.h`.
Changed all inclusions of `SDL.h` to inclusions of `sdl_wrappers.h`.
Unlike in DDA, which wraps inclusion of wrappers in `if defined(TILES)`, I decided to wrap the contents of the file instead, to cut down on boilerplate. I hope this won't cause problems.
I decided to port things manually because the file has a longer history in DDA.
Author of the fix itself is Kevin
=> Port DDA fix for Clang 12 complaint on Mac

.github/workflows/clang-tidy.yml
Ubuntu 16 will be discontinued on Github Actions soon.
=> Bump ubuntu version to 18 on clang-tidy

data/json/furniture_and_terrain/terrain-doors.json
Move_cost changed to 2 to allow vehicles passage and added flags to support roof.
I forgot to test the most important feature of gate last time.
=> Vehicles can't go trough open garage gate fix 

.gitignore, src/line.cpp, src/line.h, src/magic_spell_effect.cpp, src/point.h, src/tileray.cpp, tests/line_test.cpp
Includes some refactors cherry-picked from commits https://github.com/CleverRaven/Cataclysm-DDA/commit/6d444b891e9be260c8adb955cfe55595d74e8faa and https://github.com/CleverRaven/Cataclysm-DDA/commit/78cb7c199a7f6c30b76642d399dbf7c25de068e3 and a fix cherry-picked from https://github.com/CleverRaven/Cataclysm-DDA/pull/41470.
The missing cases added by me are just copies of the following snippet with axes switched, so I'm not sure whether they properly use `t` and `t2`.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/99ce588f21dc6d60cd3f7835e1f0d9eb0a0c6e7f/src/line.cpp#L127-L143
=> Fix 3D bresenham for `abs(dx) == abs(dz)` and `abs(dy) == abs(dz)` cases

src/activity_actor.cpp, src/avatar_action.cpp, src/bionics.cpp, src/character.cpp, src/character.h, src/condition.cpp, src/consumption.cpp, src/debug_menu.cpp, src/effect.cpp, src/faction_camp.cpp, src/game.cpp, src/gamemode_defense.cpp, src/handle_action.cpp, src/iexamine.cpp, src/iuse.cpp, src/iuse_actor.cpp, src/npc.cpp, src/npcmove.cpp, src/npctalk.cpp, src/player.cpp, src/player.h, src/player_hardcoded_effects.cpp, src/suffer.cpp, src/vehicle.cpp, tests/new_character_test.cpp, tests/npc_talk_test.cpp, tests/npc_test.cpp, tests/stomach_contents_test.cpp
Remove the `get/set/mod`+`_hunger` functions in `Character`.
They were just wrappers around kcal anyway.
I'm not sure if I didn't scramble any of the replacement values (signs, math), hence [CR].
For values where it doesn't matter, I used something from 5 to 10 (kcal per hunger).
For ones where it does, I used 10.
The actual value for closest conversion is ~8.6. This corresponds to 2500 kcal per day.
I'm not sure if I should change effects here or leave them with conversions for now.
=> [CR]Remove hunger in favor of just calories

data/json/items/armor/arms_armor.json, data/json/items/armor/legs_armor.json
SUMMARY: Bugfixes "Fix arm and leg guards that are part of an armor set having wildly different properties"
I noticed while fumbling to get leather armor produced that leather arm guards, intended to be worn with leather body armor, and being used together to craft the plated and boiled armor sets, didn't behave the same as leather body armor. It was on the strapped layer instead of normal, and wasn't variable in size.
1. Set leather arm guards to have VARSIZE, increased encumbrance to 20, and removed `STRAPPED` flag. Now consistent with leather body armor.
2. Removed `STRAPPED` flag from chitin and acidchitin arm guards, to be consistent with the body armor item.
3. Replaced `STRAPPED` with `OUTER` for plate arm and leg guards, to be consistent with cuirass and with assembled plate …
=> Make arm/leg components of armor sets consistent with rest of set

data/json/construction.json
SUMMARY: Features "Make removing gravel possible"
Since we can place gravel but can't remove it, this should do the trick. I wasn't sure if we should keep 100% of the ingredients when building gravel floors, but rather a bit lower (some may get destroyed or were washed away, etc.).
Reason for it is: you can't build fences etc. over gravel.
Add a construction method of removing gravel from groundtiles.
While I "remove gravel", some stone faced dude appeared and played the accordion next to me.
=> Remove Gravel

src/vehicle_move.cpp
Helicopter rotors collide only with huge creatures
SUMMARY: Features "Helicopter rotors collide only with huge creatures"
It is very easy to lose helicopter rotors to random zombie due collision with rotors. At the same time logically normal creature should not collide with helicopters blades since blades is placed  quite high.
Only huge creatres can collide with helicopter blades.
1) Spawn helicopter
2) Spawn zombies with variuos sizes.
3) Make sure that helicopter blades collides only with huge zombies, like hulks, but do not collide with normal or smaller zombies.
Maybe it is better simply to prevent collidng rotors with all creatures?
=> Helicopter rotors collide only with huge creatures

data/raw/keybindings.json, src/avatar.h, src/ranged.cpp, src/savegame_json.cpp
SUMMARY: Interface "Persist preferred aiming mode"
Cherry pick of https://github.com/CleverRaven/Cataclysm-DDA/pull/44775. A extremly handy way of aiming without changing modes all over again.
Copy and pasting
Chaos tried, and he got it to work!
It does throw this message on compiling tho...
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\xmemory(696,103): warning C4244: 'argument': conversion from '_Ty' to 'int', possible loss of data
1>        with
1>        [
1>            _Ty=__int64
1>        ] (compiling source file ..\src\ranged.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\vector(694): message : see reference to function template instantiation 'void …
=> Persist perfered aiming mode

data/json/bionics.json, data/json/emit.json, data/json/enchantments.json, data/json/field_type.json, doc/JSON_INFO.md, src/bionics.cpp, src/bionics.h, src/character.cpp, src/field.cpp, src/field.h, src/field_type.cpp, src/field_type.h, src/lightmap.cpp, tests/modify_morale_test.cpp
Fix Artificial Night Generator bionic makes enemies invisible to player character.
Original PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/40645
=> Port fix for Artificial Night Generator bionic

src/character.h, src/suffer.cpp
SUMMARY: Balance "Clothing coverage now mitigates sunburn damage."
Port of https://github.com/CleverRaven/Cataclysm-DDA/pull/43200
> The Solar Sensitivity mutation is too simplistic. No matter if you are naked or completely clothed, the sun burns all body parts at the same rate. In a bikini or a burka, being in full sun will burn you to death in 10-15 minutes. But not to worry - all you need to do is wield an umbrella, and you will be 100% safe. 
> Instead, this mutation should consider how exposed each body part is, and apply pain and injury effects in proportion to how much skin is exposed to the sun.
Created character, gave them the Solar Sensitivity mutation, and waited in the sun wearing different types of clothing, watching the limb damage to make sure it looked right. It did.
=> (Port from DDA) Clothing coverage now mitigates sunburn damage.

src/character.cpp, src/npc.cpp
Show gender on NPC
SUMMARY: Interface "Show gender on NPC"
NPC has genders ingame just like player. However there are no way to see it except using tileset. But some players may not use tilesets- for them it may be not possible to determine gender at all (probably by name, but name may be confusing or by clothes but it is not that easy notice).
At the same time showing gender can be usefull for roleplay reasons and for game world perception.
Also it may be usefull for modders.
Long time ago:
https://github.com/CleverRaven/Cataclysm-DDA/pull/31390
> shard in the Discord asked me to do this.
Restore and improve:
https://github.com/CleverRaven/Cataclysm-DDA/pull/31390
(It was reverted here: https://github.com/CleverRaven/Cataclysm-DDA/pull/31395 for some reason)
Now player can see NPC gender …
=> Show gender on NPC

.github/workflows/pull-translations.yml
As in title. BN currently has builds executed on `upload` branch, which is the de-facto master.
=> Fix branch in automatic translation pulling

src/map.cpp, src/pathfinding.cpp, src/vehicle_move.cpp
Fix UB when trying to ascend with a helicopter beyond map boundaries.
* Fixed boundary check in `veh_at`
* Added a separate flavor message when trying to ascend too high, as there should be no obstacles in the sky
---
Fix UB when NPC tries to path over stairs in a partially-loaded OMT.
This may happen when player character approaches a location that has both NPCs and monsters, and z levels are enabled, so NPC might try to investigate sound on different z level while OMT is only partially inside reality bubble.
[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7115993/npc-finds-stairs-ub.log)
Reproduction steps:
1. Add a check that x or y are outside array bounds, add it right before `if( pf_cache.special[x][y] & PF_UPDOWN )`
2. Start new game in shelter with an NPC
3. …
=> Fix a couple cases of UB

data/json/itemgroups/Weapons_Mods_Ammo/guns.json, data/json/items/gun/blunderbuss.json, data/json/recipes/recipe_weapon.json, data/json/recipes/weapon/ranged.json
SUMMARY: Content "Further update pipe gun craftings"
Followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/825 implementing some suggestions and ideas that came up in the process of updating pipe gun crafting.
1. Per suggestion in last PR, downgraded the need for fine screwdriving in pipe gun recipes (including blunderbuss) to regular screwdriving, as whatever is being screwed is probably something like a machine screw with a slotted head. Makeshift guns that still require fine sawing were left unchanged.
2. Defined barrel lengths for blunderbuss.
1. What next, blunderbuss in the style of a cap and ball revolver as advanced mechanics recipe, effectively a counterpart to the revolver shotgun?
2. Along the way I noticed that pipe guns, and for that matter a lot of guns, have …
=> Further updates to pipe guns and blunderbusses

data/json/vehicleparts/faults.json
SUMMARY: Interface "Rewrote the descriptions of engine faults to be more clear about their actual effects."
The strings used to describe engine faults have been, to my knowledge, pretty much unchanged since their introduction way back in the day. They have a few grammatical errors, and they don't actually describe what the fault does, meaning that for some of them, it's mostly up to memory as to what they actually do.
This PR does a few things:
* Engine fault descriptions now describe the actual effect they have on the car. For ones with duplicate functionalities, it also includes a small fluff message about why the problem is happening. The goal here is to make sure that one can see the actual problem right away, with the extraneous info/stuff that isn't as important left for later in …
=> rewrites the descriptions for engine faults

data/json/furniture_and_terrain/terrain-fences-gates.json, data/json/furniture_and_terrain/terrain-zlevel-transitions.json
SUMMARY: Bugfixes "Fix two terrains lacking expected flags"
Noticed that there was an open gate I couldn't see through, and quickly found it was missing the `TRANSPARENT` flag. Along the way @SzQ1 also mentioned apparently some behavior problems caused by wooden downstairs not having `INDOORS` like normal stairs, so good timing I guess.
1. Gave open split rail privacy fence gates `TRANSPARENT` like all other open gates have, including the other type of split rail gate. Doesn't give much privacy when it's open, after all.
2. Gave wooden downstairs `INDOORS` per SzQ's request as they're evidently busy and just recently did some stairs tweaks. Consistent with normal stairs, I'm not exactly sure what behavior it causes problems with and whether trying to build them outside might cause a …
=> Flag fixes for wooden stairs and privacy gates

src/iexamine.cpp
SUMMARY: Bugfixes "Mutants with the Proboscis or Hummingbird Beak mutations can correctly suck nectar out of flowers again."
Right now, the game throws a runtime every time the player tries to pick a mutated poppy. This is because it tries to fetch a certain type of item (`poppy_nectar`) whose definition doesn't actually exist, causing the error. This PR fixes that by making it fetch the normal nectar item instead.
There's also an issue in the math allowing certain mutants to actually drink the nectar the flower provides; it checks if the player's max stored calories minus their current calories is *less than* the nectar provided by the flower, which means they'll only actually be able to drink the nectar when they're nearly dead from starvation.
* Mutated poppies' `iexamine` function now …
=> fixes a runtime when picking mutated poppies and fixes some mutants being unable to eat nectar

src/sdlsound.cpp
Fixes "metallic" pitch-shifted sounds (e.g. walking) on some sound cards.
Fixes #410.
I had to deep dive SDL2 again, and in the process noticed that `Mix_OpenAudio()` by default allows SDL2 to choose any number of sound channels. For some sound devices, this number may be higher than 2 (e.g. 4 or 6).
When sound is to be played, it is first loaded via SDL2, which converts it into the mixer's format. If played sound must be pitch-shifted, it is then passed to Cata's `do_pitch_shift()` which assumes there are always 2 channels, and in case there are _not_ 2 channels - scrambles the sound and turns it "metallic".
You can reproduce "metallic" effect on system with any sound card by changing `int audio_channels` to 6 and then launching the game with `SDL_AUDIODRIVER=disk` environment variable. …
=> Force stereo when opening audio device

src/npctrade.cpp, src/npctrade.h
Add a hint in trading UI on how much it would take to settle the deal.
This should make trading UI a bit less awful, and free the player from mental gymnastics of dividing by 2.5
The `You'll need to offer X to settle the deal` hint may show amount higher than available amount, but this is intended.
=> Trade ui: add amount to trade hint

data/json/overmap/overmap_terrain/overmap_terrain_hardcoded.json
Increase chance of spawning swamp mosnters
SUMMARY: Balance "Increase chance of spawning swamp monsters"
Fix: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/861
Swamps traditionally was dangerous place. It gives it unique role in some way.
There was PR from DDA: https://github.com/CleverRaven/Cataclysm-DDA/pull/44997
- Raised the population and spawn probabilities to [2,6] and 50% respectiveley
I've decided not to rely fully on mentioned PR, since it requires merging 9 new monster critters. As far as aware BN strategy is not to throw monsters in to the mix just to add more monsters.
That is why I decide to go with easy solution, that was partially taken from mentioned PR- I've just increased group spawn chance.
Actually it was part of mentined PR - so there will be no new merge …
=> Increase chance of spawning swamp monsters

data/mods/TEST_DATA/items.json, src/basecamp.cpp, src/construction.cpp, src/craft_command.cpp, src/craft_command.h, src/crafting.cpp, src/crafting.h, src/crafting_gui.cpp, src/player.h, src/requirements.cpp, src/requirements.h, src/veh_utils.cpp, tests/crafting_test.cpp
Hammerspace no longer cancels crafting as soon as it is started.
When selecting tool components, the following changes are visible:
* Actual cost of use is shown, rather than one just for starting the craft (in case of crafting)
* Tools with magazines show charges properly
* Sorting prefers tools with enough charge over tools carried by player
Also code side changes:
* `requirements.h` no longer includes `crafting.h`
* `select_tool_components` is no longer a `player` method, but a regular function in `crafting` namespace
* Renamed `crafting_flags`, changed from flags (`AND`ed `bitset`-but-not-really) to just regular `enum class`, now handles whether the menu displays full costs, starting costs or continue costs
* Added basic tests for tool selection and hammerspace crafting
=> Fix debug hammerspace and weird charge display for tool component selection

data/json/recipes/recipe_deconstruction.json, data/json/recipes/recipe_others.json
SUMMARY: Bugfixes "Minor fix for missing uncraft and crafting fiber mats"
Late-night combination of two minor innawoods fixes for stuff I spotted.
1. Defined an uncraft for tanned pelts, as I noticed that tanned hides had one but tanned pelts didn't. Very minor since you can freely cut them apart, but it does have the benefit of ensuring you get the ideal 6 out of them instead of a random result.
2. Set recipe for fiber mat to allow any filament, not just plant fiber. Despite the name the straw is very clearly the meat of the object, so restricting it to fiber seems to be just whoever added it taking the name too literally.
1. Giving the uncrafts `BLIND_HARD` or `BLIND_EASY`.
2. Removing the uncraft for tanned hides and forcing the player to gamble with their precious leather if they're …
=> Two minor wilderness recipe fixes

android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
None
Possibly get rid of crashes on Android when USB device is plugged in.
Catch SecurityException in SDL getSerialNumber
=> No crash on Android when USB device is plugged in

data/json/items/comestibles/frozen.json
SUMMARY: [Balance] "Make candy ice cream less unhealthy"
Currently it's ridiculously easy to tank health using candy ice cream. With -3 health, it is equivalent to tainted fat and less healthy than fertilizer or sewage water (both -2), among other examples. As candy ice cream is far less bad for you then the above, this makes no sense from a balance perspective.
Change the health modifier of candy ice cream from -3 to -1.
If -2 is more appropriate than -1, I'm willing to change that.
Revamp the entire health system (as eating candy and ice cream separately will also have a modifier of -3). But I'm not good enough at coding for that. This PR is more of a band-aid fix than anything.
None needed
=> Make candy ice cream less unhealthy 

src/monster.cpp
Bugfixes: "Added a check to prevent monster upgrades from circumventing blacklists."
Previously, if a monster had a specific upgraded form defined (for example, SWAT zombies specifically upgrade into kevlar zombies), the game would allow the monster to evolve into its upgraded form even if the upgraded form was blacklisted. This issue did not affect monsters that upgrade using _groups_, such as the zombie soldier.
This could result in situations where monsters such as Kevlar Hulks would show up in worlds where they had been blacklisted.
I added an if statement to `monster::try_upgrade`, inside the branch that handles upgrading to a specifically defined monster. It now checks if the upgrade target is blacklisted, and if so, returns as it would if there were no upgrades available.
I thought …
=> Prevent monsters from upgrading into blacklisted forms.

data/json/items/fake.json, data/json/items/tool/workshop.json, data/json/uncraft/ammo/223.json, data/json/uncraft/ammo/270win.json, data/json/uncraft/ammo/30-06.json, data/json/uncraft/ammo/300.json, data/json/uncraft/ammo/300blk.json, data/json/uncraft/ammo/308.json, data/json/uncraft/ammo/357sig.json, data/json/uncraft/ammo/410shot.json, data/json/uncraft/ammo/4570.json, data/json/uncraft/ammo/50bmg.json, data/json/uncraft/ammo/545.json, data/json/uncraft/ammo/556.json, data/json/uncraft/ammo/700nx.json, data/json/uncraft/ammo/762x39.json, data/json/uncraft/ammo/762x51.json, data/json/uncraft/ammo/762x54.json, data/json/uncraft/ammo/shot.json, data/mods/Salvaged_Robots/items.json
SUMMARY: Balance "Allow easier uncrafting of pistol and shotgun rounds"
The idea came up recently that bullet pulling could use some tweaks to make it so that blunderbuss rounds and other basic "I need to scrap some ammo I don't intend to use" recipes can be more accessible, at a point before you'd have the gunsmithing setup needed to make said options functionally obsolete. On noticing that pullers had level 2 pulling quality, but nothing actually used that quality, this led to the ideas below.
Also has the side effect of making pliers actually useful for something that wrenches can't do, so that pliers aren't completely obsolete once you find a wrench.
1. Implemented level 2 pulling quality being needed for all rifle-caliber ammo. When asked whether I should go with the realistic "level …
=> Allow easier bullet pulling for simple ammo

src/overmap.cpp
Source PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/47144
Segfault can be reproduced in BN when running tests on version 31c2adc6d885f750f3cbc34f72b2e61bc44493be with seed 1631905804 (compiled as `make TILES=1` with `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`).
=> Cherry-pick DDA fix for segfault during subway generation

src/game.cpp, src/game.h
1. Redraw terrain view when querying to stop activity
2. Move interrupt checks from '.' key and from monster being too close to before activity is executed, so if the player confirms interrupt, they'll still have all their moves before it's the monsters' turn to act.
3. Fix text in auto-move interrupt confirmation prompt.
=> Misc fixes for activity interrupt prompt

src/activity_actor.cpp, src/activity_actor.h
Fixes regression after #885 (see https://github.com/cataclysmbnteam/Cataclysm-BN/pull/885#issuecomment-920298776 for context).
=> Fix drop & stash activities cannot be interrupted

data/json/npcs/TALK_COMMON_MISSION.json
SUMMARY: Bugfixes "Fix two lines of mission dialogue"
Couple bits of mission talk topic were a bit odd. In particular, the "I have another mission" line showing up even when it's your first mission from that NPC. Far as I can tell the only way to actually get it to track whether you'd done a mission in the past would be add_var stuff but that'd have to be inserted into every single missiondef.
The other one was the "I don't know what else to say" one sounding like a debug message. Which, it sorta is but also in the context it shows up there is basically no way to actually replace it with custom mission success lines. It's the one used for conditional goal missions.
1. Changed "another job" line to "a job" since this line also shows up on your first mission from them.
2. Removed the "I …
=> Fix two lines in mission dialogue to be a bit less odd

src/item.cpp, src/item_factory.cpp, src/item_factory.h, src/iuse_actor.cpp, src/player.cpp, src/player.h, src/recipe_dictionary.cpp, src/recipe_dictionary.h
I noticed that `d:` search in crafting UI takes enormous amount of time, particularly for characters that know all recipes.
In VS release build, it takes 27 seconds. Changes in this PR cut that number down to 4 seconds.
When profiling, I noticed that approximately 70% of time is spent on formatting `You could use it to craft` item info section. Out of those 70%, 50% is spent on creating new `recipe_subset` from list of known recipes, and remaining 20% is spent on destroying the subset.
I've managed to bring the time down to 5 seconds by filtering out recipes that don't have the item as component before adding them to the subset.
Additional 1 second was squeezed out by getting rid of vector allocation in `Item_factory::find`, and iterating over original vectors instead.
Out of remaining …
=> Speed up recipe search by item description

data/json/professions.json
SUMMARY: Balance "Port over minor DDA change giving the churl a baselard instead of makeshift knife"
Simple and easy change, reasoning as per the source PR:
> The Makeshift Knife is a chunk of recycled stainless steel scrap metal. The Churl, being a medieval peasant, starts with a Makeshift Knife- the implication is that it's all they could afford to build or borrow. Where did a 14th century English peasant get STEEL to recycle in the first place, and why don't they have a real knife instead of scrap metal with a rag tied to it?
In practice, the distinction between steel and iron is not a useful one as regards historical accuracy, but the idea of giving the churl something that's actually from the medieval period (admittedly late medieval) instead of a post-apoc scrap knife is sound and a …
=> Port over change giving churls a historical knife

data/json/clothing_mods.json
SUMMARY: Balance "Port over changes to armor padding"
This ports over changes from DDA to leather padding, kevlar padding, and steel. Per the source PR, it makes steel armor padding actually distinct from leather and makes it so coverage does not factor into the protection, which makes it more viable to try and apply this to low-coverage objects.
Also, I might be planning to make superalloy padding a thing since superalloy sheets are currently only used in the MBR vest variant, for which I'd want the existing armormods to have their balance up to date before I think with adding that idea.
1. Ported over change implementing higher cut and bash protection for steel padding.
2. Ported over change making all three padding types modify their protection based on thickness, no longer caring …
=> Port over changes to tailor mods

src/debug.cpp
SUMMARY: Bugfixes "Reduce debug.log file size by folding consecutive identical errors"
Should prevent log file from growing into gigabytes when the same message is repeatedly and rapidly logged.
See https://github.com/CleverRaven/Cataclysm-DDA/issues/50017 for example.
This is a port of my CDDA PR with minor changes for formatting: https://github.com/CleverRaven/Cataclysm-DDA/pull/51791
This PR does two things to mitigate the issue.
1. Folds identical errors as much as possible by tracking the unique information of an error (filename, line, function, error message ) and increments a counter if these are identical AND the newest error is within a 100ms window following the previous error. 100ms is a lot of time for a computer, so if the threshold is exceeded it is probably unique enough to …
=> Reduce debug.log file size by folding consecutive identical errors (Port of CDDA PR 51791)

src/vehicle.cpp, src/vehicle_move.cpp
Significantly lower fuel usage for helicopters
SUMMARY: Bugfixes "Significantly lower fuel usage for helicopters"
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/486
Fuel usage on helicopters is insanely high and even not realistic. Mostly due bug that in fact that engine use 100% and more power in flight.
This PR fix that by reducing engine power necessary to mantain flight.
Engine power usage on hover reduced from 100% to 10%.
Engine power on flight reduced from 120% ~ 150% (yep it was that bad!) to 15%
Engine power for changing height from 130% to 30%
Engine power from accelerating/decelerating from 100~200(!?)% to max around 110%
Removed tricky statistical based fuel consumption since it was based on velocity instead of acceleration.
Engine efficiency is not touched- only …
=> Significantly lower fuel usage for helicopters

src/editmap.cpp, src/map.cpp
Fix vehicle flickering while driving at night
Cherry-picked https://github.com/CleverRaven/Cataclysm-DDA/pull/44886
Driving APC at night no longer causes the vehicle to flicker
=> [DDA Port] Fix vehicle flickering while driving at night

src/item.cpp
Fixes liquids spilling from resealable containers (regression from #934).
Example cases: aluminum can with drink, tin can with meat soup.
=> Fix liquids spilling from some sealed containers

data/json/items/armor/belts.json
SUMMARY: Balance "Make tool belt a rigid item and set its encumbrance to lower level"
I made tool belt a rigid item with 6 encumbrance which i feel is more in line with other belt and tool items.
Tool belt assumes 22 max encumbrance which translates to roughly 11 encumbrance when 6 items are in the belt, which is simply too much for the benefit it provides. There are much better alternatives for storing tool and this slot (torso waist) has already  a very strong alternative which is survivor harness.
Survivor utility belt which contains all necessary tools has only 2 encumbrance and provides 0.5 L volume on top of it.
I think this change will make this item at least marginally useful, other than a crafting component for crafting other better items.
I was considering to leave it a …
=> Tool belt rigid and less encumbering

data/json/game_balance.json, src/vehicle_move.cpp
Disable helicopter rotor collision and add option to enable it back
SUMMARY: Features "Disable helicopter rotor collision"
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/819#issuecomment-907669620
>DrPariah 
> Do rotors still collide with map features? As an example, small boulders or young trees? If they do, it'd be nice to have no collision at all. It's super frustrating to finally find a working helicopter and lose it because the rotors disintegrated due to a twig being one space too close.
I've seen previously people complained about this exactly. Rotors are invisible for player and it is way too easy to lose it - and after that your flight is over.  It limits helicopter usablity a lot. Additionally warning about collision are not alway in place.
So I propose to disable …
=> Disable helicopter rotor collision

data/json/mutations/mutations.json
SUMMARY: Bugfixes "Fix Wings Stubs not having wing mutation type, causing problems with mods that use mutation types"
Upon seeing a character with both Wing Stubs and Scaly Wings, I quickly realized that Wing Stubs lacks the mutation type all other wing-type mutation has. Causes problems when interacting with any mutation mods that add wings, since successful mutual cancellation is most easily done via use of mutation types, instead of having to copy-from edit vanilla mutations to inject mutual cancellation.
Wing stubs get the wing mutation type.
Letting Dragonblood mutants continue to become even freakier than they already are by gaining a surplus pair of tiny flappy-flaps
Honestly part of the problem is just because I have Scaly Wings in Arcana develop from Scaly Patches instead of Wing …
=> Fix Wing Stubs not having mutation type

data/json/items/tool/deployable.json, data/json/items/tool/misc.json
#894 changed some items from `TOOL` type to `GENERIC`, which broke item consumption logic for `unfold_vehicle`, `UNFOLD_GENERIC` and `LADDER` use actions that relied on relevant item being tool without charges.
Revert type of all affected items as a quick fix.
=> Fix item not removed on vehicle unfold or stepladder placement

src/crafting_gui.cpp
SUMMARY: Infrastructure "Simplify logic for displaying crafting recipe list"
In my ongoing attempts to more fully understand how the crafting gui works I found an uncommented blob of code filled with mostly redundant drawing code. Figured out that this section is to draw the recipe list with a scrollbar if it cannot be fully contained within the drawable area. I knew this could be simplified.
There are 4 cases to consider, 3 require a scroll and 1 does not:
1. The list is shorter than the viewing window's line count.
We do not need a scroll, the minimum is at 0 and maximum is the list's length
2. The list window, centered on the current selection, extends before the start of the list
We push the list window forward so that it starts at the list start
3. The list window, centered on the …
=> Simplify logic for displaying crafting recipe list

data/json/mapgen/collapsed_tower.json
SUMMARY: Bugfixes "Fix the nanofab in collapsed office towers not having a console, prevent mapgen bash from hitting it"
So chatter in the BN discord revealed the nanofab in the collapsed office tower is spawned wrong and unusuable. Quick and basic look through the JSON revealed whoever made the map placed two nanofab bodies, having defined a terrain def for the control panel but not placed it.
Furthermore the bash stuff in the mapgen runs the risk of it spawning pre-busted anyway, completely out of the player's control. Given this is a pain in the ass location to clear and the nanofab is effectively the only real reward, this design's a bit anti-fun.
1. Fixed the nanofab room not actually having a console.
2. Moved the edge of the first bash effect to ensure it'll miss the …
=> Fix the mis-spawned nanofab in collapsed office tower

data/json/furniture_and_terrain/terrain-doors.json, src/iuse.cpp
SUMMARY: Balance "Fix elevated chance of breaking target while prying, implement risk of breaking doors"
Follow-up PR to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/837, per request I was asked to implement door breakage chance and make 
Along the way I discovered that the JSONization messed with the formula for breakage a bit, making it so that the base failure rate for a normal starting survivor (prying 2, 8 strength, 0 mechanics skill) was MUCH higher than intended, so the second half of the above requested feature fixes that too.
1. Changed prying break roll to multiply the outcome of a failed pry attempt by the available prying quality. This fixed the breakage chance on failure being much higher than I'd actually intended (setting the base failure rate with level 2 prying …
=> Fix prying breakage roll, implement busting doors

src/activity_handlers.cpp
SUMMARY: Balance "Make dissection take longer and give more experience"
Right now dissection bringes not a lot of skill gain. 1% or 2% are the maximum what we get. Sure it is used to give us implants and stuff, but a skill gain would also make sense.
Raising the amount of time needed to dissect a corpse, do to using fine tools and cutting very carefully. It was changed in time needed, but raises XP.
The amount of XP you get depends now on 3 factors: the size of the corpse, the time you need to cut it up and also how many bionics (burned or not) you get! That means a chicken gives very few XP (small critter, no bionics [hopefully]), a shocker brute would give a lot more.
Old:
At lvl 1 a dissection gives 4%
At lvl 2 a dissection gives 1%
At lvl 3 a dissection gives 1%
At lvl 4 a dissection …
=> Make dissection take longer and give more experience

src/iuse.cpp, src/map.cpp
SUMMARY: [Bugfixes] "Fix for being able to mop up liquids in sealed container terrain"
Fixes #1060. No more clipping your mop through walls.
While mopping: if the tile's terrain has the SEALED flag, the tile will not be searched for item-based liquids to mop (iuse.cpp), nor will these liquids be considered valid to mop up under any circumstance (map.cpp). This was already being done for the LIQUIDCONT flag.
Field- and vehicle-based liquids are not checked for SEALED terrain on the same tile, as I was unsure whether this was necessary -- does the former represent liquid on/around the container instead of inside it?
1. Built and launched the game on the latest bleeding-edge commit, bee8a49: VS2019 build --> run distribute.bat --> delete data/font/Terminus.ttf to force fallback font due to a …
=> Prevent mopping in sealed container terrain

src/cata_tiles.cpp, src/mapbuffer.h
I _expected_ linear search to be expensive, but with large mapbuffer, maximized game window, Retrodays and lowest zoom level it's bad enough to double, or even triple, rendering times.
=> Speed up debug submap grid rendering

src/debug_menu.cpp, src/overmap_ui.cpp, src/overmap_ui.h, src/panels.cpp, src/sdltiles.cpp, src/weather_type.h
Misc bugfixes and changes following #1101
1. Fix enabling weather overlay reveals all terrain tiles in graphical mode
2. Equalize 'look at sky' and 'toggle weather overlay' behavior between ascii and graphical overmap
3. Fix debug vision not working in graphical overmap
4. Fix weather names not translated (Port of https://github.com/CleverRaven/Cataclysm-DDA/pull/46537)
5. Fix enabling weather overlay hides name of underlying terrain (Port of https://github.com/CleverRaven/Cataclysm-DDA/pull/52547)
=> Misc fixes/changes for overmap weather display

src/editmap.cpp, src/lightmap.cpp
Port of https://github.com/CleverRaven/Cataclysm-DDA/pull/44847
In BN, this bug most commonly affects fire lookout towers: their entire bottom level is pitch black when viewed from outside, even at day, and completely conceals zombies there. With this fix, the bottom level is merely darker than the surroundings.
=> [DDA Port] Fix multiple issues with "ledge" rays

src/active_tile_data.cpp, src/active_tile_data.h, src/active_tile_data_def.h, src/construction.cpp, src/distribution_grid.cpp, src/distribution_grid.h, src/iexamine.cpp, src/inventory.cpp, src/iuse.cpp, src/map.cpp, src/mapbuffer.h, src/overmap_ui.cpp, src/savegame_json.cpp, src/submap.cpp, src/submap.h, src/vehicle.cpp, src/vehicle.h, tests/crafting_test.cpp, tests/electric_grid_test.cpp
And also extract active tile definitions from `active_tile_data.h` into a separate header.
This is pure refactor, with no changes to behavior intended.
=> Convert distribution grids and active tiles to use type safe coords

data/json/items/comestibles/med.json, data/json/items/comestibles/mre.json, data/json/items/generic.json, data/json/items/tool/metalworking.json, data/json/items/tool/radio_tools.json, data/json/items/tool/workshop.json, data/json/items/tool_armor.json
SUMMARY: Balance "Add NO_REPAIR and NO_SALVAGE to most packaged items with disassemble action, allow using that action on a few more items intended to be uncrafted"
Looks to be a simple fix for this, so far. Prevents you from cutting up any item with the disassemble or unpack use actions, thus preventing you from deleting contents with just a knife. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1104
Also makes things a bit more intuitive for a few more items that are supposed to be dismantled to get contents.
1. Added `NO_SALVAGE` to first aid kit.
2. Added `NO_REPAIR` and `NO_SALVAGE` to `mre_box` and `mre_smallbox`, for consistency with most of the affected items.
3. Added `DISASSEMBLE` action, `NO_REPAIR`, and `NO_SALVAGE` to rag, leather, and wool bundles.
4. Added …
=> Fix cutting up packaged items, expand use of disassemble action

src/iexamine.cpp
SUMMARY: Bugfixes "Fix utility lights and other transforming terrain printing the message used by their target terrain instead of the correct message"
Quick and easy fix for transforming terrain grabbing the wrong message. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1107
Updated `iexamine::transform` in iexamine.cpp, scooting the `if( !message.empty() )` bit to be inside the swap functions, before the actual transformation part of the other two if statements. This ensures that it grabs the transformation message for the ter/furn in its state before transforming, instead of after.
Just moving it to the beginning doesn't work since it groks the message text in the transformation if statements instead, hence absorbing the "can I play a message" part into both …
=> Fix transform iexamine printing wrong message

src/character.cpp, src/game.cpp
SUMMARY: [Bugfixes] "Prevent using inventory item menu to drop items with the NO_UNWIELD flag; correct related hint colors"
Fixes #1074. From the look of things, schizophrenia could also cause this issue; this should be fixed as well.
Also corrects the hint colors of relevant actions in the IIM (drop, wield, throw): previously, *all* items would hint as undroppable if the wielded item had NO_UNWIELD. Also, items with NO_UNWIELD would incorrectly hint as throwable and (un)wieldable; and items would hint as wieldable while a NO_UNWIELD item was wielded.
Intercepts dropping in `Character::drop(item_location loc, const tripoint & where)`, a method used only by `game::inventory_item_menu` (IIM), `player::takeoff` ('take off' action), and `Character::suffer_from_schizophrenia` (schizophrenia …
=> Fix items with NO_UNWIELD being droppable via inventory item menu

src/inventory.cpp, src/inventory_ui.cpp, src/inventory_ui.h
SUMMARY: Performance "Fixed potential seconds-long freeze while mass-applying auto inventory letters"
Fixes #1112.
`inventory::assign_empty_invlet`: now looks up action keybinds only once (as opposed to the previous once per key in `inv_chars`). This reduces freeze time in the situation described in #1112, but does not eliminate it.
`inventory::add_item`: now skips forcing other items out of their invlets if the target invlet is empty. This significantly reduces the number of calls to `assign_empty_invlet` during crafting inventory rebuilds, which occur frequently while picking up items. This is enough to completely resolve #1112.
This PR vastly increases the performance of crafting inventory rebuilds while auto inventory letters is on. However, it seems like picking up items *may* be …
=> Major performance improvements involving auto inventory letters

doc/COMPILING/COMPILING-VS-VCPKG.md
Update VS build instruction to avoid font problems
@olanti-p reported that latest version of vcpkg has problems win font.
Instruction updated to avoid that.
@olanti-p reported that latest version of vcpkg has problems win font.
Instruction updated to avoid that.
After
`cd vcpkg`
We must use
`git checkout 6bc4362fb49e53f1fff7f51e4e27e1946755ecc6` to grab vcpkg without font problems.
None
1. Check doc spelling: https://github.com/Firestorm01X2/Cataclysm-BN/blob/feature/vs-doc-update/doc/COMPILING/COMPILING-VS-VCPKG.md
None
=> Update VS build instruction to avoid font problems

data/json/item_actions.json, data/json/items/tool/science.json, src/item_factory.cpp, src/iuse.cpp, src/iuse.h, src/overmapbuffer.cpp, src/overmapbuffer.h
It is currently possible to see grid connections only via debug menu (#409), but even before that was implemented there were multiple requests for the ability to check grid connections in game.
Additionally, the only way to check grid charge level is by examining a battery, which is quite impractical when testing/debugging more complex grid stuff.
Add 2 new item use functions:
* `REPORT_GRID_CHARGE` - report grid charge level
* `REPORT_GRID_CONNECTIONS` - reports grid connections to neighboring overmap tiles
And add both of them to the voltmeter.
Also rebrand voltmeter as multimeter, or add multimeter as separate item and move new functions there.
=> Allow voltmeter to tell electric grid connections and amount of energy stored

data/json/furniture_and_terrain/terrain-doors.json
SUMMARY: Balance "Allow halligan bars to pry open pickable metal doors"
Per prior discussion on the prying overhaul, a misc idea that came up was the suggestion of allowing halligan bars to open metal doors, as an incentive to use them over normal crowbars.
Added prying entry to pickable metal doors, requiring prying 4 to open. Per feedback, went with difficulty of 4 (half that of of wooden doors, making them almost always open) and noise of 24 (double that of prying open a wooden door).
Adding option to pry open safes, with risk of breaking them?
Checked affected file for syntax and load errors.
Chance of successful prying at different strength values: https://anydice.com/program/2528b
Str | Success Rate
--- | ---
8 | 92.80%
12 | 98.54%
16 | 99.54%
20 | 99.81%
=> Allow halligan bars to pry pickable metal doors

data/json/furniture_and_terrain/furniture-zztesting.json, src/active_tile_data.cpp, src/active_tile_data_def.h, src/distribution_grid.cpp, src/distribution_grid.h, src/game.cpp, src/map.cpp, src/map.h, src/mapdata.cpp, tests/electric_grid_test.cpp, tests/stringmaker.h
This PR implements active furniture that constantly consumes electric charge, can be turned on and off, and can change into different furniture when it runs out of power. 
The rough outline of how this works, using floor lamp as example:
1. Default state for the lamp is `f_floor_lamp`, "turned on, but has no power". In this state, the lamp constantly checks for presence of electric charge in the grid, and once it detects required amount, turns into `f_floor_lamp_on`. It can also be manually turned off by transforming to `f_floor_lamp_off` on examine.
2. `f_floor_lamp_on` is "turned on and has power" lamp, aka lit. In this state, the lamp consumes specified amount of charge from the grid, and once the charge runs out, turns back into `f_floor_lamp`. It also can be examined and "turned off" …
=> Implement steady consumers for grids

data/json/itemgroups/supplies.json, data/json/mapgen/airport/s_airport_private.json, data/json/mapgen/airport/s_airport_runway_private.json, data/json/mapgen/regional_airport.json
Rebalance airports to increase helicopters accessibility
SUMMARY: Rebalance "Rebalance airports to increase helicopters accessibility"
Players still are not using helicopters. Probably because helicopters still very hard to access and build.
Also helicopter parts basically almost do not exist in game world apart from helicopters.
To increase chance that player will use helicopters re balances loot and helicopter spawn for airports
First of all game already split helicopters in 2 groups: Mostly civilian and military.
Civilian helicopters use light rotors and light gas-turbine engine (1350 hp gas turbine engine)
Military helicopters use heavy duty military rotor and medium(1900 hp gas turbine engine) or large gas turbine engine (6000 hp gas turbine engine)
1) Added group for civilian …
=> Rebalance airports to increase helicopters accessibility

data/json/mapgen/mine/mine_entrance.json, data/json/overmap/multitile_city_buildings.json, data/json/overmap/overmap_special/mine.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_industrial.json
SUMMARY: Bugfixes "Fix some buildings/specials having wrong rotation, fix mine entrance parking"
While playing recently, I noticed a few city buildings, overmap specials, and even in once case part of a larger special were twisted up and facing the wrong way. For that last one, it turned out to be a case of using old hardcoded parking lots in the middle of a map special where it wouldn't generate right.
1. Fixed churches facing backwards. Both variants were affected, and can be explained by them having their entrance on the south side, when it seems most city mapgens are north-facing instead.
2. Fixed road connection of the basic radio tower being on the wrong side, making it backward. This seems to be because the other radio tower variant is facing the opposite direction and thus has its …
=> Fix some minor city building and special issues

src/distribution_grid.cpp, src/distribution_grid.h, src/map.cpp, src/output.cpp, src/requirements.cpp, src/requirements.h, src/ui.cpp, tests/crafting_test.cpp
Fixes #1030
According to @olanti-p 's benchmark (which I can't find right now...), grids consume a significant % of CPU cycles when just waiting in one spot.
Here I introduced basic optimization to avoid going through all the `121*121*21` submaps each second. Now only ones with non-empty grids will be checked.
Additionally, the steady consumer code in #1128 showed another big performance issue (currently debug-item-only): `get_resource`, when executed by 10 lamps on a tiny sample grid of 1connector+1battery+2cars, would cause a massive lag.
I added a cache that saves sum of energy in batteries on `get_resource`, then updates it on `mod_resource`. The cache should stay consistent with actual data because adding/removing active furniture forces grid rebuild (and thus cache clear).
In my …
=> Grid fixes and optimization

data/mods/Graphical_Overmap/go_overmap_terrain_recreational.json
In Graphical_Overmap, icon for "hunting_blind" is a tower, which is misleading.
Not sure if it will be ported to BN, but I ported my fix here. 
It fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/53173
=> fix hunting_blind icon (graphical_overmap)

data/json/itemgroups/SUS/domestic.json, data/json/itemgroups/collections_domestic.json, data/json/itemgroups/tools.json
SUMMARY: Balance "Overhaul content of junk drawers to have more variety, less consistent loot"
Was nudged to work on this part of my misc to-do list. In a nutshell, the "specific use storage" itemgroups have been a known problem for a while. They consistent of large collections of largely static items, varying very little yet also averaging towards a very high amount of the exact same stuff.
Thus, one of my goals is to make some of the common problematic itemgroups using "SUS" have a more varied output, with a general trend toward not reliably giving you the exact same items in every single house. Decided to start with junk drawers first, as they're the shining, premier example of a highly static, bland output that generally always gives you the same basic items every time.
1. Added an …
=> Reworking Specific Use Storage, part 1

data/json/mutations/mutations.json, data/json/obsoletion/mutations.json, src/character.cpp
SUMMARY: Balance "Make Nomad trait series less punishing relative to point value, obsolete Antsy and Restless for now"
In a nutshell, the Nomad mutation chain is badly thought out. It STARTS at an aggressive rate of morale penalty buildup that is enough to force the player to not want to spend more than a night's rest at any given location, behavior that's better suited for what the top-tier trait Restless should be encouraging. So what's Restless do instead, if not that? Makes it so if a Chimera mutant needs to stop to craft or cook, they'll suddenly become too depressed to do anything in a whopping 2 hours.
As an alternative to simply removing the behavior outright, I opted to nudge their behavior to something closer to what would fit the niches it seems to expect players to fall into, …
=> Update Nomad traits to scale better, obsolete Antsy and Restless

data/mods/dda/modinfo.json, data/raw/keybindings.json, doc/JSON_INFO.md, doc/MODDING.md, src/dependency_tree.cpp, src/dependency_tree.h, src/mod_manager.cpp, src/mod_manager.h, src/mod_manager_ui.cpp, src/worldfactory.cpp, tests/dependency_tree_test.cpp
* Add a separate category for BN core data to distinguish it from major mods
* Add a toggle for showing obsolete mods on world creation
* Allow specifying mod incompatibilities (requested in #1148)
* Remove active mods from selection list on the left (also requested in #1148)
* Add docs for `MOD_INFO`
=> Misc additions to mod manager and its UI

data/json/obsoletion/mutations.json
Being in "obsolete.json" does nothing by itself, in case of traits, they must be `"valid": false`.
=> Un-valid NOMAD2+3

data/mods/default.json
Enable elevated bridges by default
SUMMARY: Features"Enable elevated bridges by default"
Survey (https://www.reddit.com/r/cataclysmbn/comments/qyz509/does_anyone_play_with_zlevels_off/) and observation indicates that
1) Most players plays with z-levels on
2) A lot of players like 3d bridges
So it is better to enable elevated bridges mod by default
1) It should fit most players base. Players, who don't want that feature still can disable the mod and z-levels.
2) It will provide better presentation for game itself.
Enable "elevated_bridges" as default mod for new worlds.
None.
1) Start creating new world
2) Observe default mod list
3) "elevated_bridges" must be enabled.
None
=> Enable elevated bridges by default

data/json/mapgen/field_baseball.json, data/json/mapgen/field_football.json, data/json/mapgen/hospital.json, data/json/mapgen/park.json, data/json/mapgen/pool.json, data/json/mapgen/school_1.json, data/json/mapgen/stadium_football.json, data/json/mapgen/trailer_park.json, data/json/monstergroups/zombies.json, doc/MAPGEN.md
SUMMARY: Bugfixes "Port spawn audits from DDA"
Over the last month I have been slowly [auditing the spawn tables of various overmaps](https://github.com/CleverRaven/Cataclysm-DDA/pulls?q=is%3Apr+is%3Aclosed+author%3AInglonias+spawn+audit) in DDA. Some, such as parks and hospitals, had an absurd number of zombies for their size and importance, and others had high spawn variance which made them either too easy or too hard, but rarely good gameplay (trailer parks, sports arenas and fields, pools).
Ported my spawn audits from DDA over to BN. I did this manually, rather than using a git cherry-pick, since I couldn't be bothered to learn how to do that across repositories. 
N/A
I ensured that the game starts with no JSON errors, and went around to the various overmap locations to ensure that …
=> [DDA Port] Spawn audits of various locations

src/consumption.cpp
SUMMARY: Bugfixes "Fix Mycus Feeder denying use of NO_INGEST items"
Per discussion on the discord, I was reminded that Mycus characters couldn't use bandages, which was pointed out as an annoyance. Turns out they can use such times, but only from the activate menu, not the consume menu.
Changed the check in consumption.cpp allowing items with NO_INGEST to be applied by characters with Mycus Feeder, for consistency with being able to use such items in the action menu.
1. Breaking use of comestibles in general, even through the activate menu. Bad idea because that basically full-stop halts any form of consumable tool.
2. Adding some sort of regen trait to Mycus category, possibly requiring activatable mutations to be ported over to have a fungal equivalent to DDA's version of Hyper …
=> Allow Mycus characters to use bandages in both menus

data/json/items/ammo/3006.json
M2 AP BP ammo was derived from normal 3006 BP, which made it worse than any item. Changed this to copy-from the normal M2 AP ammo before applying BP modifiers. Name also changed to reflect correct M2 AP naming.
Fixes #1213
=> Fix to .30-06 M2 AP (Black Powder) values and naming.

data/json/bionics.json, data/json/items/bionics.json, src/consumption.cpp
Buffed Expanded Digestive System to always prevent food poisoning, and also updated its descriptions to clarify this change, along with clarifying that it prevents Parasites.
It felt weird for Expanded Digestive System to have a small chance of not preventing food poisoning, it was an unnecessary gamble and in my opinion made it a rather boring choice for a bionic. Now it will always prevent food poisoning, just like Saprovore.
=> Small expanded digestive system buff

data/json/bionics.json, data/json/items/gun/bio.json, data/json/items/melee/fake.json
SUMMARY: Bugfixes "Fix bionic weapons not cleaning up on NPC death, prevent installing buggy ranged weapons on NPCs"
Some basic fixes to CBM stuff per recent discussion.
1. Added the `NO_DROP` to all psuedo-items used as bionic weapons and bionic guns, ensuring they're erased as expected if someone dies with them active.
2. Removed the `BIONIC_NPC_USABLE` flag from bionic ranged weapons, avoiding the related issue found during testing where an NPC will treat bionic guns like bionic melee weapons.
If anyone can confirm if ranged CBMs are working for NPCs in DDA, and can find a particular PR that fixes it, link me and I can see about doing that instead of point two.
Right now I can't even confirm if DDA NPCs can properly select bionic weapons at all, as I couldn't get them to even try …
=> Fixes for bionic weaponry

data/json/construction.json
SUMMARY: Content "Add floor lamp construction"
Floor lamp is a simple and good interior light source, but since it was unconstructible, it wasn't available in basement, second or higher floors you built.
This will add a simple construction recipe, which requires 2 cables, 4 amplifiers, 4 light bulbs, 1 steel lump, and 1 pipe, the maximum amount from the deconstruction recipe.
Adding a construction recipe that results in a floor lamp.
Test completed. It works well, and if in a house with working eletric grid, it automatically lights on like normal floor lamp, from #1128.
=> Add floor lamp construction

data/json/itemgroups/Weapons_Mods_Ammo/ammo.json
SUMMARY: Bugfixes "Quickfix for atomic battery itemgroups"
Fixes a mistake I made ages ago in Cataclysm++ that in turn got ported over when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1109 used the itemgroups from it as a base.
Updates itemgroups `ammo_atomic_batteries` and `ammo_atomic_batteries_full` to actually use item IDs for the atomic batteries.
Putting it off after having spotted it.
Checked affected file for syntax and load errors.
=> Fixed atomic battery itemgroups having wrong items

src/character.cpp
SUMMARY: Bugfixes "Fix CBMs harvested from NPCs not being in same state as ones from monsters"
Most of this turned out to be easy to fix, general issues where NPC bionics would be either still faulty and filthy, and power storage for some reason was coming out ready-to-install.
The former was utterly trivival to fix, the latter I was only able to figure out thanks to discussion with @acssimpson on the BN discord. One of my initial stabs at the solution had been pretty much right on the money, but I'd forgot to define the items being asked for at the beginning of the file.
1. Updated harvest of regular CBMs from NPCs to remove use of fault and filth, to be consistent with bionics from monsters.
2. Updated harvest of power storage CBMs to properly have non-sterile and non-packed, like the …
=> Fix harvested NPC bionics not being in intended state

data/json/mapgen/refugee_center/refugee_center.json, data/json/npcs/refugee_center/surface_visitors/NPC_arsonist.json
SUMMARY: Bugfixes "Set Makayla specifically to have feline ears, not every generic arsonist NPC"
Since the refugee center uses an NPC class that generic NPCs can also use, I was going to just add an ears mutation to this NPC via the mapgen entry.
Then I double-checked and realized that someone already had the idea of "the arsonist should actually have mutant ears since their dialogue implies it" but did it basically backwards, via injecting it into the NPC class. Since this class is still marked as one dynamic and static NPCs can use, it means all generic arsonists you meet will ALL have cat ears.
1. Set it so the refugee center mapgen calls `add_trait` to slap cat ears on the center's arsonist.
2. Removed Feline Ears from the trait selection of the arsonist NPC class.
1. Setting …
=> Don't give every generic arsonist cat ears

src/iuse_actor.cpp
SUMMARY: Bugfixes "Fixed CTD when attempting to modify shoulder strap"
Fixes #1230
If item is armor, that doesn't necessarily mean it has armor data (lmao).
As such, check for null pointer before dereferencing.
Game no longer crashes, and allows padding shoulder strap with leather and fur. Pretty sure it doesn't do anything useful, but that's an issue for another time.
=> Fix CTD when attempting to modify shoulder strap

src/activity_handlers.cpp, src/npctrade.cpp
SUMMARY: None
`xgettext` gets confused by thousands separators in code, and emits warnings during string extraction.
Normally that's not an issue, but these warnings show up on each and every PR, and that's getting annoying.
Get rid of problematic thousands separators. Looks like there's only 3 of them in the codebase, so their presense can be considered as going against code style anyway.
CI will tell.
=> Fix xgettext warnings

src/consumption.cpp
Taste Modifier is currently broken, it creates power equal to food's fun value instead of using power, this is because it subtracts the fun value, but the fun value is always negative. I fixed this by removing a single errant Minus sign from the equation.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1168
=> Make Taste Modifer use power properly.

src/npc.cpp
SUMMARY: Bugfixes "swapped the order in which NPCs receive items in order to prevent a freeze that occurred due to items dropped via mutation being dropped out of bounds"
Bugfix, don't think there is an open issue.
I shuffled the order that NPC are randomly generated, so now items are assigned items after they mutate. This means that they won't be given clothing, just to have it fall off when they gain spider arms or whatever.
I suppose you could intercept the drop item call and delete the item from existence instead of trying to drop it onto the 'ground', but I'm not entirely sure that would fix the problem.
Made a world with maximum npc multiplier, and passed 12 hours. This was literally impossible with bug, and now happens just fine.
=> Npc item spawning fix

data/json/overmap/overmap_special/specials.json
SUMMARY: Bugfixes "Make it a bit easier for evac shelters and necropolises to find a desirable place to spawn"
I've noticed that in certain city settings, the default evac shelter can get very prone to failing to spawn, especially when city placement is abnormally close or distant. Saw a similiar poroblem with necropolis, which is a potential issue for any future plans to nudge the player toward them (ideally after becoming the marshal).
1. Increased min and max city distance for evac shelters from 3/10 to 2/14, expanding their spawn ranges a modest bit.
2. Decreased minimum city distance for necropolis from 20 to 12.
These should overall be relatively minor tweaks to make the specials in question a bit more robust in terms of spawning range, especially in worlds with abnormal city …
=> Make evac shelters and necropolis spawning a bit more robust

data/json/overmap/overmap_special/specials.json
SUMMARY: Content "Add ELECTRIC_GRID flag to more overmap specials"
Simple enough, tackling the idea of adding grid connections to more specials, generally the ones that have more in the way of interconnected buildings without too many open fields or roads in them.
Added `ELECTRIC_GRID` flag to:
1. Motels
2. Sewage treatment plant.
3. Gas stations.
4. Cabins
5. Sugar house.
6. Military bunker.
7. Missile silo.
8. Radio towers.
9. Hazardous waste sarcophagus.
10. Refugee center. I'm leery of this one because it's fucking huge, which means if anything grid-related is liable to break when the grid gets big enough, this might run afoul of it. Plus it has tons of empty fields that end up with power connections due to this. I went with it because of how it was deemed acceptable to add it to the …
=> Grid-ify more overmap specials

data/json/items/chemicals_and_resources.json, data/json/recipes/ammo/components.json
SUMMARY: Balance "Make recipe for black gunpowder more consistent by weight, wasting less valuable ingredients, make in smaller batches"
Per some musings on the BN discord, some work to make production of blackpowder actually respect conservation of matter a bit better. Less so for realism reasons, and moreso because leaning more towards realistic in this case works out to using way less of the most annoying-to-get materials.
Changed material demand of the standard blackpowder recipe to be made in batches of 10 instead of 100, per Coolthulhu's suggestion. Time scaled down accordingly. Material usage scaled down and nudged more towards consistent ratios by weight. Comment explaining why it looks so wacky added to the recipe as well.
Also updated the generic recipe slightly to be as close …
=> Make black gunpowder recipes less absurdly wasteful

data/json/items/tool/workshop.json, data/json/materials.json
SUMMARY: Features "Allow to fix glass sheets and other glass items"
Before this PR, if we want to fix a glass sheet, we had to install it on a car, repair it, and remove it again. This will simplify it by allowing repair it directly.
Arc welder, makeshift arc welder, and extended toolset can repair glass-based thing. It will require glass shards as material.
Adding Iron material to every glass items, like reinforced glass sheet.
Test completed by editing json file. It worked well.
=> Allow to fix glass sheets and other glass items

data/json/items/comestibles/veggy_dishes.json
SUMMARY: Balance "Port over minor change to starch shelf life from DDA"
Simple port of a recent tweak in DDA. Per original PR, reasoning is combination of an example indicating cattail starch was allowed to sit out to dry in open conditions for a period longer than it'd take to rot in-game without issue, in tandem with its short spoilage time being a hindrance to crafting flour (exacerbated by all the "hours as meat = days as jerky" issues spoilage currently has).
Updated `spoils_in` of starch by the same amount proposed in the source PR, increasing from 1 day and 6 hours to 3 days and 12 hours.
1. Fixing the issues that make this a problem in the first place (and are why Nonperishable Overhaul mod exists) is on my todo list, but it'll take several steps.
2. One minor entry that's part of …
=> Port over minor extension to starch shelf life

data/json/construction.json
SUMMARY: Balance "Port over update making fire rings slightly easier to build from DDA"
Another easy JSON port of a recent DDA change.
Tweaked it so fire rings are built on dirt and require digging quality of 1 in the construction, instead of being built on shallow pits. Makes things a bit less hassle, as the source PR notes. Adding my own two cents as the one who added it back in ye olden days, back in my day digging a shallow pit was a construction and didn't wear you out, so it was definitely less hassle as originally added to More Survival Tools.
Honestly it's a minor one either way since you're literally halfway to building a fireplace in terms of both digging quality and rocks required, but the added exertion to something that should be something as simple as "make sure you're not …
=> Port over update making fire ring less hassle to build

data/json/vehicleparts/doors.json, data/json/vehicleparts/vehicle_parts.json
SUMMARY: [Balance] "Give internal and wooden vehicle doors the "AISLE" flag."
Internal doors are supposed to be nothing but simple dividers that allow you to pass from one room of a spacious vehicle into another, without hindering the persons movement when said door is open.
By giving internal doors the "AISLE" flag, they are considered a walkway without hampering movement inside of a vehicle. This change is meant to discourage the removal of internal doors in vehicles only to replace it with an aisle to not get a movespeed penalty when walking on and off the tile in question. As per Chaosvolts asking specifically, this flag was also added to wooden doors specifically. They are flimsy enough to be actual weakpoints, yet make for an interesting option when needing a quick escape. Given …
=> Give AISLE flag to internal doors

data/json/recipes/ammo/arrows.json
Removed reversible flag as most other arrow recipes are one way - this also allows us to keep batch count consistent with other non-reversible arrow recipes, which is the source of the problem. The alternative is turning down batch count to 1.
Partially addresses #621.
=> Fix Exploding Arrow Duplication Exploit

src/character.cpp, src/consumption.cpp
SUMMARY: [Bugfixes] "Fixed hyper metabolism mutation for chimera"
Hyper metabolism has been broken for a while. When trying to eat enough to heal, the character would instead become bloated and then vomit.
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/312
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1255
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1289
Instead of making the hypermetabolism check part of the mod_kcal, I moved the check to the consumption logic.
Reworking the entire food system to not be bunko, but this seemed faster.
=> Fixed hyper metabolism

src/ballistics.cpp
SUMMARY: Bugfixes "Fix rooftop shooting"
This is direct copy of https://github.com/CleverRaven/Cataclysm-DDA/pull/52386.
Whenever the bullet trajectory changes z-levels, check both tiles if there is a floor in between. This should still prevent the player
from shooting directly through the floor.
=> Allow shooting adjacent enemies across z-levels.

data/json/items/tool/handloading.json, data/json/recipes/other/tools.json
SUMMARY: Balance "Update recipe for hand press"
Hand presses have been purely a hand tool for quite some item, and DDA at some point altered their recipe accordingly (albeit in DDA's usual manner).
* Lowered the weight of hand press. I went with a target weight of 5 pounds, as the heaviest portable hand press I could find via quick google-fu was 4.75 pounds (most were under 2 pounds).
* Updated recipe to be made entirely from metal, with an amount of forge and metal use consistent with weight. This is similiar to DDA's current recipe, but without the massive artificial jump in difficulty and time.
* Did however increase time needed to 90 minutes, 30 minutes per steel lump used.
1. Adding a furniture press that does include a hot plate to fill the niche of a larger bench-style press.
2. …
=> Update recipe for hand press

.gitignore, doc/COMPILING/COMPILING-VS-VCPKG.md, doc/DEVELOPER_TOOLING.md, msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-test-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-vcpkg-static.sln, msvc-full-features/Cataclysm-vcpkg-static.vcxproj, msvc-full-features/JsonFormatter.vcxproj, msvc-full-features/vcpkg.json
As in the title.
Cherry-picked some DDA code:
https://github.com/CleverRaven/Cataclysm-DDA/pull/41908
https://github.com/CleverRaven/Cataclysm-DDA/pull/54170
https://github.com/CleverRaven/Cataclysm-DDA/pull/51616 (partially)
Also removed an obsolete workaround and my previous blind attempt at fixing docs for vs2022 (#1294).
Migrating BN to meson.
Installed from scratch vcpkg and Visual Studio 2022 Community, got it to compile BN without problems.
~There's still the issue of the astyle plugin not supporting vs2022 yet, but that's relatively minor and can be solved by setting up msys2 to run `make astyle`.~
Nevermind that, I managed to cobble together Astyle extension for vs2022, so that's not a problem anymore either.
=> [DDA Port] Streamline Visual Studio project setup process, clarify docs, another VS2022 fix

data/raw/keybindings.json, src/savegame_json.cpp, src/veh_interact.cpp, src/veh_interact.h, src/vehicle.h, src/vehicle_display.cpp
SUMMARY: Feature "The shape of a visible vehicle part can be changed instantly at no cost (CDDA's change shape equivalent)"
https://github.com/CleverRaven/Cataclysm-DDA/issues/27770
This PR essentially replicates https://github.com/CleverRaven/Cataclysm-DDA/pull/48477
However, it differs in how it works. Whereas CDDA's version is a "select part, change shape", in this PR the visible/displayed part is immediately selected. This also does make it context-sensitive since a player inside a vehicle sees different parts than a player outside of it. Other than that, no other difference other than the implementation.
Bardcore essentially added a new value to vehicle parts that is serialized/deserialized from JSON and stores the symbol. This is in contrast to CDDA's part variant system.
N/A
Tested …
=> Porting over CDDA's "change shape" feature

src/game.cpp, src/overmap_ui.cpp
SUMMARY: Bugfixes "Disable some graphics-related keys when their functionality is disabled"
Disable some keys related to graphical features when these features are absent (curses, SDL with tiles disabled).
Fixes #1313
Sprinkle in some conditions and `#ifdef`s
Disabled tiles in SDL build - zoom keys went absent.
=> Disable some graphics-related keys when their functionality is disabled

data/json/flags.json, src/item.cpp, src/iuse.cpp
SUMMARY: Interface "Flag corpses confirmed to have bionics to make them easier to sort"
Per some discussion on the BN discord, a thought that came up is that the bionic scanner changes the description of corpses that've been tested positive for CBMs, but it would be more useful for sorting out what corpses are worth dissecting if a positive scan was more visible.
1. Updated flags.json to add `CBM_SCANNED` flag.
2. Updated item.cpp so that items that have been scanned and have the flag will show relevant tagtext, per feedback.
3. Updated iuse.cpp so that the bionic scanner marks corpses with the flag when it confirms them to have CBMs.
1. Add a "CBMs were detected in this corpse, you may wish to dissect it instead" message to the summary for each butchery method in the butchery menu, if …
=> Make bionic corpse identification a bit more visible to the player

data/json/furniture_and_terrain/terrain-doors.json, data/json/furniture_and_terrain/terrain-floors_indoor.json, data/json/furniture_and_terrain/terrain-manufactured.json, data/json/furniture_and_terrain/terrain-walls.json, data/json/furniture_and_terrain/terrain-windows.json, src/assign.h, src/descriptions.cpp, src/field_type.cpp, src/handle_action.cpp, src/itype.h, src/map.cpp, src/map.h, src/mapdata.cpp, src/mapdata.h, src/mapgen.cpp, src/numeric_interval.h, src/omdata.h, src/output.h, src/overmapbuffer.cpp, src/rng.cpp, src/rng.h, src/units.h, src/units_probability.h, tests/npc_test.cpp, tests/overmap_test.cpp
Bash struct gets a new member: `ranged`, which is optional. This is used by `map::shoot`.
It's possible to set the following:
* Reduction of damage of a projectile passing through this terrain. It's an array with `min` and `max` and is rolled as `rng(min, max)`.
* As above, but special-cased for lasers.
* "Destruction threshold" which is amount of damage after reduction needed to destroy this thing. If laser reduction is set, lasers never destroy this terrain. Defaults to 0, meaning any hit ranged above reduction will wreck this terrain.
* Flammability, which makes incendiary ammo and heat damage create small fires when hitting this terrain.
* Chance to intercept a bullet passing through this tile but not aimed at this tile. Defaults to 100%.
If `ranged` is unset, the behavior is …
=> JSONize ranged bash (reinforced glass letting bullets through etc.)

data/json/flags.json, data/json/items/tool/explosives.json, data/json/items/tool/radio_tools.json, data/json/recipes/electronic/tools.json, doc/JSON_FLAGS.md, src/animation.h, src/bionics.cpp, src/creature.h, src/explosion.cpp, src/explosion.h, src/explosion_queue.h, src/game.cpp, src/handle_action.cpp, src/iuse.cpp, src/iuse_actor.cpp, src/magic_spell_effect.cpp, src/map.cpp, src/map.h, src/monster.cpp, src/monster.h, src/npc.h, src/player.cpp, src/player.h, src/visitable.cpp, tests/explosion_balance_test.cpp
1. Fix explosions within vehicles causing segfault (fixes #175)
2. Fix active explosives within monsters not exploding (e.g. when technician pulls an active grenade)
3. Fix radio activation mod having infinite uses 
4. Fix items with `RADIO_ACTIVATION` flag not actually being activated (fixes #1276)
5. Fix active mininuke timer getting reset to 0 on save/load
6. Fix resonance cascade doing nothing
7. Allow RC control to choose which rc car to control, instead of selecting semi-randomly
8. Allow RC control signal to activate items within vehicles or creatures' inventories
9. Allow RC control signal to activate items on all z-levels, remove max range of 30
10. Make radio activation mod easier to craft by allowing more battery variants as components
1. Defer explosions, to avoid modifying …
=> Misc fixes for explosions and radio activation

src/explosion.cpp
SUMMARY: Balance "Explosions bash terrain at full advertised force."
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1291
There is no clear reason why explosions bash terrain (and vehicle parts, actually) at 25% of the power. This PR removes this.
Because the damage does not change smoothly across the radius, this might require some additional balancing later on, however, at the moment explosives are completely useless against terrain and this has higher priority than making the damage distribution less messed up.
=> Explosions deal full damage to terrain, not 25% of it

android/app/src/main/java/com/cleverraven/cataclysmdda/SplashScreen.java, data/mods/default.json, src/mod_manager.cpp, src/mod_manager.h, src/mod_manager_ui.cpp, src/path_info.cpp, src/worldfactory.cpp
SUMMARY: Infrastructure "Allow user mods to override default preinstalled mods"
It is agonizing to debug saves that use many 3rd-party mods at once.
Not only they may be hard to track down or slow to install on Windows due to sheer amount of tiny files, the process of installation frequently amounts to "dump this into game `data/mods/` folder, overwrite when prompted", especially for BN mods updated out-of-repo, which messes with preexisting files and folders and the version control system overall.
Allow mods from `mods/` user folder to override mods in `data/mods/` folder.
New loading rules are as follows:
1. If 2 or more mods within `data/mods/` share same id, `debugmsg` with details is issued and none of them are loaded;
2. If 2 or more mods within user `mods/` folder share same id, …
=> Allow user mods to override default preinstalled mods

src/character.cpp, src/player.cpp
SUMMARY: [Bugfixes] Bugfix
Apparently getting into a mech with a broken arm deletes the mech's weapon.
Was fixed on DDA by adding additional checks to the 'get in mech' checks and the 'wield weapon' checks.
https://github.com/CleverRaven/Cataclysm-DDA/pull/47314/files
And if you ever see this- thanks original author!
=> Broken Arm Mech Fix ported from DDA.

src/mapdata.cpp, src/mapdata.h
Fix #1336
Also, try to fix Win64 build failure semi-blindly.
Removed a misplaced transparency removal.
Also added explicit values for some optionals that were associated with win64 not-builds.
Tested with all 3 sizes of boulders. Small and medium are transparent, large is not, so it seems to be OK.
=> Fix un-transparent furniture

src/options.cpp, src/overmap_ui.cpp
SUMMARY: Interface "An option to display absolute overmap coordinates instead of relative coordinates"
Overmap displays your current position like 3'59, 2'33 which is a strange unit that's pretty much useless: it's not very easy to remember, it's not clear how it works and, for the purposes of stuff like calculating distances manually, it's converted into absolute coordinates anyway. This PR alleviates this by adding an option (enabled by default) to display absolute coordinates instead.
The only two places where overmap coordinates are seemingly displayed is the bottom right corner of [m]ap screen and notes panel in the same screen. Depending on the option's value, it will display them differently.
N/A
N/A
=> Add an option to display absolute overmap coordinates

data/json/scenarios.json, data/json/start_locations.json
SUMMARY: Content "Port over ability to start on islands from DDA"
I keep getting pestered to add islands to BN's wilderness scenario, turns out this was added to DDA a while back.
1. Copy over edit to wilderness scenario adding deserted island to starting location options.
2. Copy over added starting location, fixed name from "desert island" to "deserted island" since only one of the allowed island variants is sandy.
1. Adding any other island overmap specials we can think of to scenarios.
2. Adding island start location to other innawoods scenarios.
3. Narrowing down what types of islands are valid so that you don't risk getting softlocked on the more useless variants.
1. Checked file changes for syntax and lint errors.
2. Ported file changes to a test build.
3. Load-tested and started …
=> Port over island starting location

src/item.cpp
SUMMARY: Balance "Fermenting no longer takes longer with longer season length"
Per discussion on an unrelated oddity found while looking into https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1331, it was advised that fermenting vat times should not scale with seasons.
Changed `item::brewing_time()` to not multiply the fermentation time of items by `calendar::season_ratio()`.
Continuing to be mystified by things taking over twice as long to brew up when season length is set to my usual preferred middle ground of 30 days.
1. Compiled and load tested.
2. Started up a world with 30-day seasons.
3. Checked item entry for unfermented vinegar.
4. Observed that the time it said it'd take to ferment when added is 7 hours, instead of 15 hours.
I haven't checked yet to see if it still scales …
=> Remove seasonal scaling for fermenting

data/json/mapgen/robofachq_static.json, data/json/mapgen_palettes/robofachq.json
SUMMARY: Bugfixes "Fix malformed furniture and terrain placement in Hub 01"
Couple things I spotted borked in Hub 01 thanks to Critsybear's BN playthrough.
1. Fixed furniture def for toilets using wrong character, causing electronic machinery to spawn with toilets on top of them.
2. Removed terrain def that was placing domestic windows, not something you expect to see in Hub 01, underneath server furniture. When they say they run windows, that's not what they meant.
3. Fixed a case of the server `:` being called for on the map but not having a furniture def.
4. Fixed a case of `&`s being called for without matching terrain def.
Making electronic toilets a feature instead of a bug.
1. Checked affected file for syntax and load errors.
2. Load-tested files in test build.
3. Warped on over to …
=> Some mapgen fixes for Hub 01

data/json/recipes/other/materials.json
SUMMARY: Balance "Make quicklime 10 at a time to not force the player to collect multiple limestone shards"
I noticed that you get 10 bits of limestone from uncrafting one limestone shard, but the recipe for quicklime takes 50. Easy enough to fix the recipe to be more granular, so you don't have to wait until you have 5 limestone shards.
Reduced components of quicklime recipe down from 50 limestone to 10, reduced time taken from 60 minutes to 12 minutes, reduced charges from 250 forge/50 oxy torch to 50/10, and added `charges` of 10 to the recipe.
1. Allowing it to use 1 limestone shard as an alternative component.
2. Making forge and oxy torch usage equal because uneven torch usage is mostly a holdover from ye olden days. Dunno which number we'd want to go for though.
Checked affected …
=> Make quicklime in smaller batches

src/projectile.h, src/ranged.cpp
SUMMARY: [Bugfixes] "Fix RECOVER_%i flags not working"
Make RECOVER_%i flags work again, so that arrows no longer mulch 100% of the time.
In recent PR, I named two fields the same way and forgot to copy the value from ammo to projectile.
Here I remove the one from `projectile`, since recovery is set on shot, not hit.
=> Fix RECOVER_%i not working

data/json/construction.json, data/json/recipes/basecamps/recipe_modular_field_rammed_earth.json, data/json/recipes/basecamps/recipe_modular_field_wad.json, data/json/recipes/basecamps/recipe_modular_saltworks/recipe_modular_saltworks_log.json, data/json/recipes/basecamps/recipe_modular_storehouse/recipe_modular_storehouse_rammed_earth.json, data/json/recipes/basecamps/recipe_modular_storehouse/recipe_modular_storehouse_wad.json
SUMMARY: Balance "Make thatched roof require saner amount of materials relative to sod roof"
Of the two notable ways to build a roof innawoods, the thatched roof option takes a noticeably higher toll in terms of resources. The log and sod roof takes 2 logs (which a single trunk can easily supply), 40 soil (generally less than a shallow pit yields), 12 birchbark or pine boughs (2-3 trees worth in either case), and 4 sticks or 8 planks (if going for sticks, likely a young tree or two at most). So that's roughly 5-7 tiles harvested per 1 tile of roof (not counting potentially needing to cut down a tree).
Thatched roofing meanwhile requires 60 piles of straw (60 long OR grass tiles dug up) or 60 withered plants (rough estimate of 40 underbrush smashed on average), 48 cordage pieces (so 48 …
=> Updates to sod and thatch roofing

data/json/furniture_and_terrain/terrain-doors.json, data/json/furniture_and_terrain/terrain-floors-outdoors.json, data/json/furniture_and_terrain/terrain-floors_indoor.json, data/json/furniture_and_terrain/terrain-highways.json, data/json/furniture_and_terrain/terrain-migo.json, data/json/furniture_and_terrain/terrain-roofs.json, data/json/furniture_and_terrain/terrain-traps.json, data/json/furniture_and_terrain/terrain-walls.json, data/json/furniture_and_terrain/terrain-windows.json, data/json/furniture_and_terrain/terrain-zlevel-transitions.json, data/mods/Aftershock/maps/terrain.json, src/character.cpp, src/character.h, src/construction.cpp, src/handle_action.cpp, src/map.cpp, src/map.h, src/mapdata.cpp, src/mapdata.h, src/monmove.cpp
SUMMARY:  [Bugfixes] "Fix missing roofs and partial roof destruction"
Roofs need pretty specific conditions to work correctly:
1. Have `"bash_below": true`
2. Don't have roofs themselves
3. Were spawned on mapgen or load
4. Z-levels are enabled
The first 3 are improved here:
1. A warning is produced when a tile is a roof, but has no `bash_below`. Some terrains had this problems, fixed now.
2. A warning is produced when a roof has a roof. Terrains with this issue fixed.
3. Constructions now create roofs over them if open air was there before.
Additionally, roof bashing is improved:
* Can bash down with `s->SHIFT+.`
* If a tile has its roof wrecked, it itself is wrecked
* If a `bash_below` tile is wrecked, but is not the roof of the tile above, the roof is placed and then bashed with the …
=> Roof buffs

src/game.cpp, src/game.h
SUMMARY: [Features] "Allow moving zone position"
Currently, the only way to change the position of a zone is to re-edit the zone, but in many cases it is more convenient to move the area directly than to re-edit. So it's a good idea to add a feature to move the zone directly.
Add a new option below the option "Edit position", now the window looks like this:
You can then use the keyboard  to move the zone:
or mouse:
If z-levels are enabled, moving zone across z-levels can also function, as shown in the gif above.
- Create a new zone, select it and move it around, the zone saves fine.
- Load an old save with existing zones, those zones can also be moved.
=> Allow moving zone position

data/json/vehicleparts/combustion.json, data/json/vehicleparts/motor.json, data/json/vehicleparts/rotor.json, data/json/vehicleparts/vehicle_parts.json
SUMMARY: Balance "Made more parts consistently use same skill level for installation and removal, more use of swapping parts being lower-skill than repair"
It was remarked that certain parts required immense mechanics skill to be able to install, notably gas turbine engines (and rotors to some extent). On looking further into this, I noticed that for gas engines this mostly seems to be a consequence of V12 engines having a skill jump between the gasoline and diesel version, then all variants of turbine engine having escalating skill demands (when different sizes of the same type of engine generally don't have skill jumps).
A second cause of some oddities mostly comes in the form of skill to install, remove, and repair being all over the place. For most items the trend seems to be having …
=> Some consistency updates for part installation

data/json/recipes/food/other.json
SUMMARY: [Feature] "Fix bone meal recipe to use human bone with food processor"
Human bone can be made to bone meal with quern / mortars and pestles, but not with food processor.
This will fix it.
Add bone meal's recipe to count human mone as valid material.
None.
Tested with current save.
It worked well.
=> Fix bone meal recipe to use human bone with food processor

data/json/furniture_and_terrain/terrain-doors.json, src/mapdata.cpp
SUMMARY: Bugfixes "Fix secret door opening into itself, preventing walking through"
In my recent change, I used `copy-from` on secret doors to deduplicate some data. But I didn't change the `"open"` value, so open secret door still opens into open secret door. I didn't expect the game to prefer opening to walking.
Here I fix the issue.
Set open secret door to open to null, meaning it doesn't open. Add a warning for all tiles that open or close into themselves.
Make walking preferable to opening. This would still leave the issue of being able to open a door into itself, so it doesn't fully resolve the problem.
1. Spawn open secret door
2. Walk through it
3. Try to open it
4. Get a message that it is already open
=> Fix secret door opening into itself, add warning on load

src/game.cpp
SUMMARY: Features "Ask for a retry if game fails to find a suitable starting location"
* Quality of life stuff for #36. It **doesn't** fix the issue.
Port of my own PRs [#55025](https://github.com/CleverRaven/Cataclysm-DDA/pull/55025) and [#55695](https://github.com/CleverRaven/Cataclysm-DDA/pull/55695).
None.
Reduced chance to spawn for one of locations so it has a fairly high chance of fail to find a suitable location, made several retries until game finally found a suitable location.
None.
=> Ask for a retry if game fails to find a suitable starting location

src/creature.cpp, src/mondeath.cpp
SUMMARY: Bugfixes "Fix debugmsgs about null fields on dying critters"
Forgot to add checks for null ids in certain places where they should exist.
Will merge out of "schedule" to test if Windows builds will unbreak.
=> Fix debugmsgs on dying critters

src/crafting.cpp, src/inventory.cpp, src/inventory.h, src/item.cpp, src/item.h, src/visitable.cpp
SUMMARY: [Performance] "Optimize craft menu performance when there are numerous items around"
After I happily looted a large shopping center with the help of my recently developed "moving zone" feature, I found that if I tried to open the craft menu with my loot in the craft range, the game would freeze some seconds before the menu finally opened. And it takes really a lot of time to browse the recipes. So I look into the code and try out a solution to increase the performance.
Firstly, when opening the craft menu, I notice that the game does a lot of iterations in `inventory::add_item` function to check whether the new item can be stacked with the existing item, so it takes a lot of time to run `item::stack_with`. One simple approach to improving that is to reduce unnecessary loops. So I …
=> Optimize craft menu performance when there are numerous items around

src/bionics.cpp
SUMMARY: Balance "Remove filthiness and fault from bionics obtained by uninstalling"
Should be one final consistency tweak to the proposal of harvested CBMs not being filthy and faulty.
Removed filthy and fault from bionics obtained via uninstallation.
I wanted to also tinker with the idea of making it so uninstalling a faulty bionic yields a burnt-out bionic instead of the bionic item, but I couldn't figure out how to correctly get both `Character::perform_uninstall` and `Character::uninstall_bionic` to check for a flag on the bionic when deciding what bionic item it'll drop.
Compiled and load tested.
=> No filth and fault on uninstalled bionics

src/game.cpp
SUMMARY: [Features] "QoL changes for moving zone (blinking, auto zoom and cursor as center)"
To make the operation of moving zone simpler and looks better.
1. Zone is blinking when moving it, and cursor in the center of the zone.
2. Auto zoom out for better observation when moving a large zone.
Moving zone around and it looks nice.
=> QoL changes for moving zone

src/editmap.cpp, src/map.cpp, src/map.h
SUMMARY: [Performance] "Improve game performance by adding suspension cache"
People have been complaining for a long time that CBN is running a lot slower than CDDA, so it's the time to look into the code and find out what is the problem.
It turn out that the function `add_susensions_to_cache` brought by #1234 is the culprit of the huge lag, as it keeps iterating over every map tile. Cache it, and the lag should be gone.
Waiting for 6h in game:
- Before this PR
- After
Also obtained mutation web bridge, use it and the suspension mechanic works.
I tested the game time in a basement.
=> Improve game performance by adding suspension cache

src/inventory.cpp, src/inventory.h, src/visitable.cpp
SUMMARY: [Bugfixes] "Revert invstack change and only use the cache when needed"
The invstack change to add an items type cache in #1386 seems buggy somehow.  Revert!
Revert  invstack change  and only use the cache when the `inventory::add_item` might be called frequently.
More cautious check to guarantee the cache to be right.
But, it doesn't appear to be worth the effort and it's difficult to do.
Open the craft menu with numerous items around, and the performance is fine.
Fix #1416
=> Revert invstack change and only use the cache when needed

src/activity_handlers.cpp
SUMMARY: [Performance] "Optimize butchery menu performance"
Currently opening the butchery menu is a slow thing to do, it shouldn't be that slow.
`inv.has_item_with` should only be ran once.
Open the the butchery with corresponding tool in inventory, works fine.
=> Optimize butchery menu performance

src/npcmove.cpp, src/simple_pathfinding.cpp
SUMMARY: [Bugfix] "Use bidirectional search to avoid game freeze in pathfinding"
As #1412 shows , the game will freeze when the map is big and npc or player tries to path to an unreachable location. This PR fix it.
If the destination is unreachable, the bidirectional search can find that earlier than the normal one.
And because bidirectional search may return different path result, only use it when search count is big enough.
- Use BFS to check if the destination is reachable before start pathfinding.
- Simply decrease the max search count.
- Reveal the map, path to an unreachable destination, no game freeze happen.
- Reveal the map, path to a reachable destination far away (more than 200 tiles), pathfinding works fine.
- Download the save file in #1412, waiting for several days, no game …
=> Use bidirectional search to avoid game freeze in pathfinding

data/json/recipes/ammo/arrows.json, data/json/recipes/ammo/components.json, data/json/recipes/ammo/other.json, src/item.cpp, src/item.h, src/recipe.cpp
SUMMARY: Balance "Implement support for ALLOW_FILTHY recipe flag, use for arrows and certain other ammo"
A suggestion came up in the BN subreddit of letting you use filthy components for items where filthy status should not actually matter, with arrows given as a prominent example. Turns out this would be trivial if not for filthy components being filtered out in an entirely different function, one used by a lot of other functions.
1. Define a separate function in item.h for finding crafting components for recipes to use, since just removing the check for filthy items would affect a ton of other functions.
2. Add an additional filter in `recipe::get_component_filter` to filter out filthy components by default, unless the recipe has the `ALLOW_FILTHY` flag.
3. Added the ALLOW_FILTHY flag …
=> Allow crafting certain ammo with filthy materials

data/mods/Aftershock/recipes/recipes.json
Fixed components in recipes of light battery and plutonium cell: "can_drink" to "can_drink_unsealed" and "can_food" to "can_food_unsealed"
=> Change obsolete componets to actual

src/inventory.cpp
SUMMARY: [Bugfixes] "Minor bugfix for items type cache"
To fix #1424
Uses  add_item_by_items_type_cache() instead of '+='
- Before this PR, spawn a food truck, examine it, the debug message pop up.
- After this PR,  spawn a food truck, examine it, no debug message pop up.
=> Minor bugfix for items type cache

src/messages.cpp
SUMMARY: Bugfixes "Fix static initialization order crash"
Attempt at fixing Windows build launch crash. Fix #1427, fix #1426 
From stacktrace and experimental fix provided by @SaintCirno9 in #1427, I assume #1423 caused it by changing `calendar::start_of_cataclysm` to a reference. The stacktrace suggests that the crash happens during static initialization and I'd expect it to be related to order of initialization.
I changed the referred variable to a `constexpr` one.
Don't try to make calendar testable.
Run MSVC build. If it works at all, fix is working.
=> Fix static initialization order crash

.github/workflows/msvc-full-features.yml, .github/workflows/release.yml, msvc-full-features/vcpkg.json
SUMMARY: Build "Fix GH msvc release build"
Fix msvc release build.
The build is failing because `vcpkg` tries to build sdl2 packages using exact version of some msys2 packages that seem to have been removed from https://repo.msys2.org/mingw/i686/ .
As such, update `vcpkg` to the latest version that passes all tests https://github.com/microsoft/vcpkg/commit/9d9a6f486cc7da7664117a75d01440db0088634a which also defines up-to-date msys2 packages (reference: https://github.com/microsoft/vcpkg/commit/897f02781f7724a44f15d26f708fd6a2832422c3).
Giving up on GitHub Actions and building releases locally.
Works on my fork: https://github.com/olanti-p/Cataclysm-BN/releases/tag/cbn-experimental-2022-04-03-1739
=> Fix windows msvc release

src/bionics.cpp
Blood Filter now removes Badly Poisoned status.
Didn't seem like there was a good reason to have Badly Poisoned not be affected at all by Blood Filter CBM. It is still a toxin in your bloodstream after all.
One of my considerations was that Badly Poisoned could be downgraded to just Poisoned before being removed on the 2nd "flush", this would throw in resource and turn management considerations into avoiding Badly Poisoned to begin with. However I lack the technical knowhow to make this work, so this is what you get.
Walked into Poison Gas, activated Blood Filter CBM, saw poison removed.
Blood Analysis CBM considers both Badly Poisoned and Poisoned to be separate conditions but simultaneously calls them poisoned. I'd hope that this could be changed later on.
=> Blood Filter CBM update to remove Badly Poisoned status

data/json/bionics.json, src/character.cpp, src/item.cpp
Added a toggleable version of Air Filtration System CBM that makes it provide protection equal to an activated gas mask.
Currently the Air Filtration System CBM is basically useless. With the breaking of chance based rolls for EP the only Environmental Protection that matters is reaching the threshold values. The only threshold that the base Air Filtration System CBM reaches is that for smoke of all intensities.
The base bionic is unchanged, granting 7 passive Environmental Protection. Changes were made to Character.cpp and Items.cpp to support a toggleable version of "env_protect" (Credit to Coolthulhu for the code and walking me through actually compiling the thing).
An additional active Bionic was created that is packaged into the Air Filtration CBM, this raises the EP by an additional …
=> Make Air Filtration CBM Useful

src/sdlsound.cpp
SUMMARY: Bugfixes "Fixed tracking of volume of currently playing music track when changing music volume in settings"
When updating music volume through settings, the game uses `current_music_track_volume` to change volume of currently playing music track. Yet instead of being updated each time new track starts playing, `current_music_track_volume` is updated only once, when the first track in the playlist starts playing.
Update `current_music_track_volume` after starting new music track.
Checked through debugger that `Mix_VolumeMusic` receives proper values based on `MUSIC_VOLUME` and volume of current track defined in json.
=> Fix tracking of volume of current music track when changing music volume in settings

data/json/bionics.json, src/bionics.cpp
[Bugfixes]: Fixed code so power armour cost is not subtracted when armour not active, made MkII power armour Interface CBM draw 500J every turn instead of 1kJ every 2 turns which felt kind of weird. Also formatted some of the act/react costs to follow new format.
Power Armour Interfaces drew power even when power armour was at rest, there was already code for this and looking into it showed that the problem lay with a typo.
MkII Interfaces currently draw power at a rate of 1 kJ every 2 turns, instead of 1 kJ every turn as the MkI, I figured this could be made uniform in the interest of more uniform power discharge rates.
Also while I was at it I changed some of the older act/react cost format to the new format in use since bionic power was expressed in J.
Fixed Typo in Bionics.cpp so the …
=> Power armour drain fix

data/json/recipes/electronic/other.json
Minor: Added Inactive Riot Control Turret Recipe
Allow disassembly of Inactive Riot Control Turrets to achieve parity as broken Riot Control Turrets can be disassembled. Activating a turret to break it so you can disassemble it is illogical.
Added recipe, mainly copied from Medium Turret list. Components pulled from broken version as almost all turrets use the same individual list between the two versions. Time was set to 1 hour as disassembly of Riot Control Turret is twice as long as a Medium Turret.
Remove ability to disassemble Riot Control Turret. (Would be very stupid, but would still achieve parity)
Have Riot Control Turret be learned from military/lab schematics. (It appears at military roadblocks, suggesting a military origin, but is crafted with police robot parts)
Debugged a …
=> Add reversible Riot Control Turret Recipe

src/game.cpp
SUMMARY: Bugfixes "Stricter favorite ammo check to fix item reload crash"
Fix #1448
The bug was caused by favorite ammo being saved as a location and then not checked for viability, allowing things like trying to reload with an item outside bubble or is contained in the reloaded item already.
I changed it from "get ammo under favorite ammo location" to "if there is ammo location like favorite one, use that without prompting". 
Disabling ammo favoriting for general case.
1. Load save in #1448
2. Reload UPS
3. Don't get a crash (unlike in latest release)
4. Spawn a bow + 2 stacks of arrows
5. Favorite one stack with "change gun mode"
6. Fire a couple of arrows
7. Don't get a prompt, because favorite ammo is set
8. Favorite second stack by opening inventory menu, selecting the bow, then …
=> Stricter checks on favorite ammo

src/distribution_grid.cpp, src/game.cpp, src/overmapbuffer.cpp
SUMMARY: [Performance] "Optimize electric grid"
To fix #1322 
The profiler result in #1322 is rather inaccurate because of the compile options we use, I guess. 
In fact, the major performance eater in `electric_grid_at` is the copy of the `tripoint_abs_omt`, which is weird.
Simply using a reference there solves the lag.
Load the save attached in #1322 , then walk around.
- Before this PR
- After this PR
I also made the `distribution_grid_tracker::on_saved()` only reload needed things, but the improvement is not as significant as the reference used in `electric_grid_at`.
=> Optimize electric grid

data/json/recipes/basecamps/recipe_modular_canteen/recipe_modular_canteen_common.json, data/json/recipes/basecamps/recipe_modular_field_common.json, data/json/recipes/basecamps/recipe_modular_firestation1.json
SUMMARY: Bugfixes "Fix construction blueprints not using rope and cordage crafting requirements consistently"
Minor blueprint fix for something that causes minor problems depending on mod selection.
Updated butchering rack blueprints to correctly use the same crafting requirements for its rope/cord component as the construction it's being told to look at. This ensures that anything that changes the `rope_natural_short` or `cordage` requirements won't cause a blueprint error on load. This could include a hypothetical future addition to the types of cord items in the game, or it could be the current known example of loading a mod like MST Extra that edits the cordage crafting requirement for the same reason.
Struggling to find and port over whatever DDA PR makes it not do this when testing …
=> Fix construction blueprint not using requirements

data/json/recipes/electronic/components.json, data/json/recipes/electronic/other.json
Added Turret Chassis as an individual component recipe, altered Light Turret recipe to bring balance.
The Light Turret takes 6 hours to craft over the Medium Turrets 30 minutes, owed likely to the section that crafts an entire turret interior chassis for it using springs, steel, pipes and metal sheets. This makes the Light Turret difficult to utilize and also annoying since if a Turret Interior Chassis is found it cannot be used for the Light Turret.
Furthermore, a broken Light Turret takes only 1 hour to deconstruct, and yields Turret Interior Chassis instead of springs, steel, pipes and metal sheets. This makes the recipe even more unintuitive, as if you have several broken Light Turrets, deconstructing them will never give you all the components required for a Light Turret, as Turret …
=>  Light Turret Recipe change, Turret Chassis recipe addition

data/json/effects.json, data/json/itemgroups/Locations_MapExtras/locations.json, data/json/itemgroups/collections_domestic.json, data/json/itemgroups/science_and_tech.json, data/json/items/comestibles/meat_dishes.json, data/json/items/comestibles/other.json, data/json/recipes/food/meat.json
SUMMARY: Balance "Makes royal jelly useful again, but also possess mutant toxins"
Per discussion on the BN discord, some ideas came up for how to bring back royal jelly as one possible vanilla option for poison and other statuses, with some rebalancing possible now that mutagenic toxins are a thing. Also ties in with my plan to eventually port over DDA's venom and antivenom rework, and a separate idea that'll involve triffid stuff.
1. Reworked royal jelly to imply it's specifically a post-cataclysm substance mainly made by mutated insects, as fits the majority of its standard spawns. This re-adds a narrower version of the cureall effect to it, plus a separate antitoxin effect. Per feedback from Coolthulhu, it was suggested that royal jelly would be better balanced if it provided a …
=> Revive and rebalance royal jelly's curing ability

data/core/tips.json
SUMMARY: Interface "Update main menu tips to account for changes in BN, new mechanics, etc"
A while back it was suggested to update the tips available in BN, as some of them concern mechanics specific to DDA, and of course some mechanics specific to BN lack a mention. Plus can add a few for advice concerning a few mechanics common to both that don't get much hinting.
1. Removed four tipd concerning frozen food.
2. Added a tip pertaining to the electric grid system, and changed the oven tip to allude to being able to restore power.
3. Added a tip concerning the different behavior of mutated meat.
4. Changed tip concerning vehicles to not refer to tanks, since those have never even been vanilla.
5. Added a tip concerning helicopters, and how they can be repaired.
6. Added a tip alluding to …
=> Update main menu tips for BN

src/consumption.cpp, src/savegame_json.cpp
SUMMARY: Fixes vitamin bug that prevents new chars from gaining/losing vitamins.
Fixes #1466 so that newly created characters will have vitamins change, particularly useful in our case for mutagenic toxins.
> Stop silently failing when attempting to modify a vitamin that is not already contained, and instead add it to the vitamin_levels map, and change the character loading function to avoid the behavior that hid this problem in the past - filling out the vitamin map completely even if there was nothing to load for it.
Created new custom character, add mutant lard and waited 30 minutes. Checked that mutagenic toxins rose. Saved and loaded char and ensured progression of mutagenic toxins continued.
=> Don't silently fail when attempting to modify vits

data/json/bionics.json, data/json/clothing_mods.json, data/json/mutations/mutations.json
SUMMARY: Balance "Add missing ballistic armor to clothing mods, mutations, bionics"
Some follow-up updates to the ballistic damage PR, incorporating some stuff that was added later on.
1. As promised, I said I'd update clothing mods to add bullet protection when the ballistic damage PR was ported over, so here we be. Notable divergences from DDA's version are that steel padding's bullet resist is closer to the difference the steel material actually has, presence of superalloy padding, 
2. Ported over updates to alloy armor CBMs. Description is closer to the original, and encumbrance not ported over for now (can if requested), but did grab the ballistic protection and the updates making the relevant CBMs cover subordinate bodyparts.
3. Ported over adding ballistic armor to shell mutations. …
=> Follow-up updates after ballistic damage PR

src/calendar.cpp, src/calendar.h, src/craft_command.h, src/crafting.cpp, src/faction.h, src/iexamine.cpp, src/overmap.cpp, src/pathfinding.h, src/ranged_aoe.cpp, src/vehicle_use.cpp, src/vpart_position.h, src/vpart_range.h, tests/monster_test.cpp
SUMMARY: Build "Fixed a compiler warnings (which are errors with -WError) of clang 13."
Most of had default copy constructor explicitly defined but not copy operartor, or vice versa.
There are some examples of variables, only used to assigning.
None.
Didn't test, but it compiles.
=> Fixed a compiler warnings (which are errors with -WError) of clang 13.

data/json/effects.json
SUMMARY: Balance "Add pain_max_val to parasites, like all other pain-causing permanent status effects"
While watching Critybear's latest playthrough he showed me a fun discovery involving effectively infinite pain caused by parasites, which can tank your stats to absurd levels and render your focus effectively zero. This was in his DDA playthrough, but a quick test confirmed that just one of the two pain-causing parasites is enough to cripple you in the same way in BN.
Since these are permanent-until-cured status effects that cause pain, by definition pain will automatically build up uncontrollably over time unless the pain chance is so low that natural pain recovery can outpace it, so the only other potential fix that came to mind was to make use of `pain_max_val`. All other permanent …
=> Add max_pain_val to pain-causing parasites

data/json/recipes/basecamps/recipe_modular_canteen/recipe_modular_canteen_common.json, data/json/recipes/basecamps/recipe_modular_firestation1.json, data/json/recipes/basecamps/recipe_modular_shelter/recipe_modular_shelter_common.json, data/json/recipes/basecamps/recipe_modular_shelter_1/recipe_modular_shelter_1_common.json, data/json/recipes/basecamps/recipe_modular_shelter_2/recipe_modular_shelter_2_common.json, data/json/recipes/basecamps/recipe_primitive_field.json
SUMMARY: Bugfixes "Removed references to obsoleted item Stone Pot."
While the stone pot is obsoleted, there are still places where it is referenced, misleading players into believing such a recipe exists. [Credit to silverwing235 on the discord for bringing this to my attention]
Removed all remaining references to the stone pot in construction recipes.
... Add it back?
Kind of telling that this hasn't been fixed in so long, we really need to look at the faction camp system at some point.
=> Removed rock_pot References

src/activity_item_handling.cpp
SUMMARY: [Bugfixes] "ACT_FETCH_REQUIRED is dark capable"
To fix #1500 
Found there is a similar issue in DDA https://github.com/CleverRaven/Cataclysm-DDA/issues/41220
And this is the fix https://github.com/CleverRaven/Cataclysm-DDA/pull/46243
Then cherry-pick! (though I already found the problem by my self)
No game freezes anymore after this PR.
=> DDA port #46243: Make ACT_FETCH_REQUIRED possible in the dark (fixes game freeze)

src/handle_action.cpp
SUMMARY: Performance "Do not go into animation loop if there is nothing to animate"
When using animations the game will check for user input more quickly so that any active animations can progress. With terminal builds animations are fairly rare. This burns CPU time to do little of importance. A user reported high CPU usage with animations enabled on curses build that disappeared when disabled, even when there was no weather, SCT, nor after-life to animate.
Check early to see if there is anything in need of animation. If there is something that requires we go into the faster animate loop do so. Otherwise treat it like animation is turned off to save some CPU time since new animations won't begin until at least after user input has been obtained.
In the case of TILES builds we will go …
=> Don't animate if there is nothing to animate

src/mutation_ui.cpp
SUMMARY: [Interface] "Add cursor navigation to the mutations UI"
To fix #1479
Cherry-picked from https://github.com/CleverRaven/Cataclysm-DDA/pull/53764
Seems working fine.
https://github.com/CleverRaven/Cataclysm-DDA/pull/54204 is also included.
=> DDA port #53764: Add cursor navigation to the mutations UI

src/item.cpp
SUMMARY: Interface "Change how books are highlighted to differentiate "Just for Fun" books."
Just for Fun books being highlighted the same as skill books can be somewhat irksome to players, requiring them to either remember the titles (especially in the case of books that might otherwise seem useful, the Merck manual comes to mind.) or just walk up and (R)ead them to remove the highlight.
Adjusted a commit from author Marloss (with a few changes) to make "Just for Fun" books appear on the inventory screen as Magenta when unread.
Remove the highlighting for "Just for Fun" books entirely.
- Would be a good update for utilitarian players, but arguably you could just remove all the flavour books entirely. Keeping the highlight but making it different from Skill/Recipe Books would allow …
=> Change highlighting for "Just for Fun" books.

data/json/flags.json, doc/JSON_FLAGS.md, src/ranged.cpp
SUMMARY: Features "Port over canceled DDA PR allowing big mutant characters to fire heavy weapons while dismounted, at penalty"
Revives an old idea that was requested I look into a while back, porting over an idea that was attempted in DDA but closed for realism reasons. Allows abnormally large mutant characters to fire heavy weapons like the M2 Browning without needing terrain, at penalties to dispersion and recoil.
Now that the game UI itself confirms that just getting Large turns a 6-foot character into 7'5" and a Huge character becomes 9'3" it's pretty clear that yes, they are expanding in all dimensions and not merely getting swole.
1. Changed the check for firing a mounted weapon in `ranged::gunmode_checks_weapon` to also allow it if the shooter is Large or Huge in size.
2. Changed …
=> Large and Huge characters and heavy weapons

data/json/items/armor/bandolier.json, data/json/professions.json
SUMMARY: Balance "Rebalance bandolier capacity for consistency relative to shotgun bandoliers, based off average volume of ammo used"
Bandoliers are in a bit of a weird niche, their intended main advantage is a reduction in reload time, but with it being 0.8 seconds faster on average that tends to be moot compared to being able to carry extra ammo. I personally feel that these two advantages aren't that great on their own, but are perfectly fine when combined, enough to make for a solid balance against their primary drawback of giving up a fairly valuable torso slot.
For shotgun bandoliers the numbers check out just about right I feel, but the problem is pistol and rifle bandoliers, which hold less of ammo that tends to be smaller than what the player will likely be filling shotgun …
=> Consistency updates for bandoliers

data/json/itemgroups/Clothing_Gear/clothing.json, data/json/itemgroups/SUS/domestic.json
SUMMARY: Balance "Update Specific Use Storage, dressers and wardrobes"
Part four of overhauling the Specific Use Storage itemgroups. Per discussion on the BN discord, I was reminded that the dresser spawns of the SUS itemgroups were also on the list to be fixed up. As usual it leaned towards massive spawns of relatively identical items, often disproportionately spawning some of the exact same few items, most famously hilarious amounts of kilts.
Part of it is because itemgroups for men-only and women-only items (kilts vs skirts for example) were called about as often as unisex clothing spawns, and since the former has way lower variety of items that meant they'd show up a lot more than expected.
1. Reworked the dresser itemgroups. Mainly, merge calls for unisex vs. gendered clothing into a …
=> Overhauling Specific Use Storage, part 4

src/inventory.cpp, src/visitable.cpp, tests/crafting_test.cpp
AKA Fix stone hammer being uncraftable with 2 rocks
SUMMARY: Bugfixes "Fix quality-same-as-component not recognizing 2 items of same type"
Fix #1408 (I hope)
Seems that rocks are being counted as charges now. The quality cache system didn't handle this edge case and instead counted them as 1, but it's a simple fix, once the reason for the bug is known.
I also added two test cases to ensure it doesn't break in the future:
* Crafting rock hammer with 2 rocks - this one should work
* Crafting rock hammer with 1 rock - this one should fail, because the same rock is "trying" to be both a tool and a component
Get rid of the requirement to have two items. It's a bit realismic and probably not worth the effort to maintain it.
* Run the new tests
* Spawn materials for a stone hammer: plank, …
=> Fix quality-same-as-component not recognizing 2 items of same type

data/json/recipes/other/vehicles.json, data/json/vehicleparts/vehicle_parts.json
SUMMARY: Balance "Allow makeshift ropes for reins and yokes, don't use 60 feet of rope for yokes"
Per discussion on the BN discord, it was pointed out by PoshOctavia that animal-powered wagons can be clunky to get set up in wilderness gameplay due to needing god-tier strings to make reins and yoke.
1. Set rein and tackle recipe to allow `cordage` instead of `cordage_superior`.
2. Set yoke and harness recipe to use 4 instances of `rope_natural_short` instead of 2 instances of `rope_superior`. Not only is it odd to restrict it to only allowing good-quality strings for something so basic, the recipe was demanding **60 feet** of rope for something that realistically will likely top out about 24 feet total (see additional information below).
3. Per further discussion in the BN discord, swapped …
=> Rebalance for rein and yoke recipes

data/json/furniture_and_terrain/furniture-surfaces.json
SUMMARY: Features "Allow workbenches simple-deconstruct into workbench item"
Fixes #1514
Added `EASY_DECONSTRUCT` flag to workbenches, making them able to be deconstructed into `workbench` item without tools
> We actually already have this mechanic for Oven implemented, so it just can be applied to other functional furniture that doesn't exist just for scrapping.
Make them not; however this comment from https://github.com/cataclysmbnteam/Cataclysm-BN/issues/1514#issuecomment-1120353082 seems reasonable.
no visible errors after modifying json
deconstructing workbench with bare hands yield 1 workbench item.
=> Allow workbenches simple-deconstruct into workbench item

src/bionics.cpp
SUMMARY: Bugfix "Repair Nanobots no longer has the ability to starve you to death in your sleep."
A follow up to my original change to the PR. Since it's now considered "Sleep Friendly" it needs to _actually_ be sleep friendly. Starving you to death in your sleep is the _exact opposite_ of that.
Granted this is an edge case where you go to sleep both hungry and heavily injured, but it should still be considered.
Adjusted the Repair Nanobots to automatically disable if you have less than 85% of your max calories.
Have the Repair Nanobots not heal when under 85% max calories, but don't disable.
- I kind of like this idea considering how the Repair Nanobots currently function, I have a draft implementation of this where it only runs the checks when calories are above 85%, printing a message …
=> Update Repair Nanobots

data/json/overmap/overmap_terrain/overmap_terrain.json, data/json/overmap/overmap_terrain/overmap_terrain_abstract.json, data/json/overmap/overmap_terrain/overmap_terrain_hardcoded.json, data/json/overmap/overmap_terrain/overmap_terrain_industrial.json
This small fix along with small tileset update will make internal parkings and roads like Industrial centre and mines show proper tiles. There are more such small things that will need similar fix.
Related tileset PR that will require this to work.
https://github.com/Theawesomeboophis/UndeadPeopleTileset/pull/32
Without it current PR doesn't break anything, we will have to just update ingame tileset from the Boophis one.
Industrial centre
mines
and few others probably too.
=> GO Fix parkings and roads

data/json/construction.json, data/json/furniture_and_terrain/furniture-appliances.json, data/json/furniture_and_terrain/terrain-railroads.json, data/json/mapgen/house/house_fortified.json
SUMMARY: Bugfixes "Small fixes for error-inducing funnel placement, looks_like for grid batteries, deconstruction of gravel"
A collection of misc fixes that came up that I felt were each too small to be worth a PR on their own. The first two are things I'd thought I'd fixed but never actually did, both cases of thinking about something and forgetting you hadn't done it, it seems.
1. Fixed an instance where a house would try to spawn a funnel on top of a gutter downspout.
2. Fixed looks_like of large and huge grid storage batteries to point to the regular battery variant that already has its own sprite in UDP, instead of also looking like lockers.
3. Removed deconstruct entry from gravel due to the existence of an explicit construction for turning gravel back into dirt, and moved its …
=> Misc fixes for funnel, grid batteries, gravel

src/handle_action.cpp
SUMMARY: Bugfixes "Helicopters now print a message on failing to ascend due to lack of engine power, instead of silent failure"
I'd been wanting to figure out how to fix the annoyance where helicopters would fail silently, with no message, if you tried to ascend but couldn't due to lack of power. It took a lot of rooting through a fairly complex chain of functions, giving up, then working through the opposite direction by figuring out what actually happens internally when you press `<`, before I finally found how to fix that.
Updated `game::handle_action` so that triggering the `ACTION_MOVE_UP` will check for if you're in the circumstance of a helicopter trying and failing to ascend, and if so print a message to hint at the problem.
Continue going in circles looking at how the vehicle …
=> Fix helicopters silently failing to ascend

src/iuse_actor.cpp
SUMMARY Bugfixes "Have tailor kit mod menu tell you an item can't receive a clothing mod earlier in the code"
In Thelonestander's stream it was discovered that the "lack of materials" failure message in the tailor's kit menu has priority over the "this item can't even accept this clothing mod" one, so you'd likely end up gathering or making steel armor plates only to find out an item is incompatible after all that effort.
Swapped the order of the if/else statement in iuse_actor.cpp so check for incompatability of clothing mod first.
Putting it off until he's at least done with the stream.
2. Spawn in a tailor's kit and a MOLLE pack.
3. Tried adding steel padding to MOLLE pack, observed that it says you can't do that.
4. Tested on a leather jacket, confirm it …
=> State inability to add a clothing mod up front

data/json/recipes/chem/chemicals.json
SUMMARY: Bugfixes "Fix 60x dupe bug between fertilizer and ammonium nitrate pellet"
- 1 charge of `Commercial Fertilzer` (aka fertilizer) can be crafted into 350 `ammonium nitrate pellets` (aka pellets)
- 350 `pellets` can be crafted into 1 `fertilizer`, but with **60 charges** (since its [default chages are 60](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/41ae57c46e67c48dffcb15628371162ea1b61483/data/json/items/chemicals_and_resources.json#L273-L296)), effectively yielding 60x fertilizers per iteration.
related links addressing the issue on korean roguelike forum:
- https://gall.dcinside.com/board/view/?id=rlike&no=408667
- https://gall.dcinside.com/board/view/?id=rlike&no=388068
change the resulting charge of commercial fertilizer to 1, making both recipies even.
None
JSON …
=> Fix 60x dupe bug between fertilizer and ammonium nitrate pellet

data/json/items/comestibles/carnivore.json, data/json/items/comestibles/offal_dishes.json, data/json/items/migration.json, data/json/obsoletion/recipes.json, data/json/recipes/food/meat.json
SUMMARY: Bugfixes "Fix cooked offal recipes not needing heat to cook, make fried offal actually flavored as such"
So I was gonna make this PR just a bundle of some misc easy fixes that barely warranted a separate PR each, but looking into the issue of cooked offal not using heat to cook actually turned out a lot more complicated than I expected, due to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1371 seeming to intend to reflavor generic cooked offal as fried offal, warranting more involved changes beyond just fixing the bugged recipe.
1. Reflavored cooked offal as fried offal. This seems to be what the change to recipe and mention of "you can fry them" in the PR OP was talking about, which makes sense because just plain campfire generic offal no longer has any reason to exist …
=> Fix oddities with generic cooked offal

data/json/uncraft/ammo/40x46mm.json
SUMMARY: [None] "[Fixed 40x46mm M1006 beanbag shells give the wrong casing on disassembly]"
Issue #1565 
Changed json in game build, and tested item's disassembly
=> 40x46mm M1006 beanbag shells give the wrong casing on disassembly #1565

data/json/items/gunmod/accessories.json, data/json/items/gunmod/grip.json, data/json/items/gunmod/mount.json, data/json/items/gunmod/sights.json, data/json/items/gunmod/underbarrel.json, data/mods/Magiclysm/items/enchanted_gunmods.json, src/item.cpp, src/item_factory.cpp
Also add warning in strict json mode
SUMMARY: Bugfixes "Fix 'bow' gunmod location not working"
Fix #1526
When a gun has skill type "archery", allow gunmods with "bow" as gun type as well.
Added a warning, currently only in strict mode, that "bow" is deprecated. All modders should have strict mode on for warnings like this.
Changed existing entries from "bow" to "archery".
Rewriting the hacky gunmod location thing to be properly verified and strongly typed.
While this would be a good idea, it would take extra work, then again even more to maintain compatibility with mods.
Dropping the "bow" location altogether and just printing warnings if neither skill nor item for the location exists.
Checking if there is at least one gun with given type which can receive this particular gunmod, warning …
=> Fix "bow" gunmod location not working

data/json/items/armor/ammo_pouch.json, data/json/items/armor/boots.json, data/json/items/battery.json, data/json/items/gun/40.json
SUMMARY: Balance "Allow storing speedloaders and batteries in relevant mag pouches, related changes"
This is a collection of updates pertaining to storage of items and compatiability between holsters, mag pouches, and the like.
1. `MAG_COMPACT` flag added to all light and medium class batteries, and `MAG_BULKY` added to heavy class batteries, allowing them to be stored in relevant mag pouches that will fit them. Ultralight batteries and mech batteries left untouched. Idea is mainly this allows a utility use for magazine storage beyond just firearm magazines, plus utility for mods that add battery-fueled weapons.
2. Allowed small enough mag pouches to also fit items with the `SPEEDLOADER` flag, as it'd make sense to store speedloaders there too, and nothing in-game could actually store …
=> Updates pertaining to mag pouches and speedloaders

data/json/recipes/armor/storage.json, data/json/recipes/chem/chemicals.json, data/json/recipes/food/other.json, data/json/recipes/other/materials.json, data/json/recipes/other/tools.json, data/json/recipes/other/vehicles.json, data/json/requirements/materials.json
SUMMARY: Balance "Allow sticks and/or long sticks for more recipes that previously only allowed planks, fix crafting softlock with wood saws"
PoshOctavia pointed out in the BN discord that wood saws don't allow using heavy sticks to make them, only allowing planks. Since planks need a decent sawing or woodcutting tool to make, this causes a crafting softlock. On looking further into it, I discovered a ton of recipes that could reasonably allow sticks as an option.
1. Recipes for scabbards, baldrics, and back scabbards updated to allow sticks as an alternative to planks, and fur as an alternative to leather.
2. Methanol recipe updated to allow sticks and long sticks.
3. Sugar from wood recipe updated to allow long sticks.
4. Filled charcoal kiln recipe updated to allow long sticks.
5. …
=> Allow sticks/long sticks in more recipes

src/animation.cpp, src/character.cpp, src/creature.cpp, src/inventory_ui.cpp, src/item.cpp, src/ranged.cpp, src/ranged_aoe.cpp, tests/dependency_tree_test.cpp
SUMMARY: Build "Fix Compilation error about range based for loops"
compilation was failing because say,
```c++
for( const std::pair<tripoint, double> &pv : to_bucket )
```
wasn't const enough to be referenced.
```c++
for( const std::pair<const tripoint, double> &pv : to_bucket )
```
added some of added missing const qualifier, or changed to auto if it wasn't able to.
=> Fix compilation error about range based for loops

data/json/mapgen/lab/lab_floorplans_finale1level.json
SUMMARY: Balance "Mechs in lab finales won't fail to spawn, fix one case of spawning in a wall"
During Thelonestander's BN stream today he finally ran into a mech lab finale, rare as those are, only to find that it had mech containment with no mech. Given these are fairly rare, burn up fairly rare power cells, and could use some improvements in the future anyway.
Turns out it was not only not a 100% spawn rate, but also that particular variant was set to spawn in a wall, most likely bugging it out.
1. Fixed broken spawn of recon mech in one lab finale variant.
2. Set spawn changes of mechs in lab finales to 100%, checked the rest will all spawn in actually available space.
1. The spawn rate could possibly stay low (or maybe elevated but not 100%) for the lifting mech variants, because …
=> Adjust rarity of mechs in finales, fix a spawn

src/vehicle_use.cpp
SUMMARY: Bugfixes "Fix engines being unable to be toggled except first"
Fixes #1552
missing `i++` at the end of loop 
turns out this line was accidently [removed on this commit](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1480/files#diff-078ef22e64ec25788b594c35675260cc1d008bfa08d2a902e5d0c929ff7fe753L392)
None
None
None
=> Fix engines being unable to be toggled except first

src/melee.cpp
SUMMARY: Bugfixes "Fix reach attack crash"
A missing null check caused a reliable nullptr deference in reach attack code. Added a check for null.
Check for null when getting a potentially-nonexistent monster's size.
=> Fix reach attack crash

src/ranged_aoe.cpp
SUMMARY: Bugfixes "Fix invalid comparator which triggerred debug assertions in STL"
Old implementation have such bad quality:
if a == b, then `a < b` and `b < a` would be both true which is invalid comparator implementation.
Because running tests in debug build is painful, didn't test lack of assertion firing.
Release build passes tests though.
Found that when trying running tests in debug build.
=> Fixed invalid `less` operator implementation for `tripoint_distance`

src/vehicle.cpp
SUMMARY: Bugfixes "Prevent discharging too much power from nearly empty batteries"
Consider the situation when charging from large storage battery (80 MJ) with 10 kJ remaining. It would have 0% power level (10*100 / 80_000) so our "prev_charge_level" would `-800` and we would lower `amount` by 810.
Essentially free energy when it shouldn't be so I ensure that we cannot charge more power than remaining.
Just ensure that we never try to lower our power amount more than we have.
Only run autotests because change is trivial.
=> Prevent discharging more power from battery with nearly 0% power

src/vehicle.cpp, tests/vehicle_efficiency_test.cpp
SUMMARY: Bugfixes "Make electric engines consume battery power evenly"
Earlier, when riding a car with electric engines and multiple batteries, batteries discharged one after one.
However, they should discharge by similar percent (this is how connected electric grids work).
To reproduce old behaviour, one can do this:
1. Put 2 charged batteries to car.
2. Put electric engine to car.
3. Make car use only electric batteries.
4. Ride the car a while.
5. Notice that one battery is significantly more discharged than another (can be even 0% vs 100%).
Made fuel consumption reuse existing code for utility discharges if fuel type is battery.
Ride a car with 1 battery charged to half and another charged fully.
Monitored power level of batteries, noticed that only most charged discharged.
When the …
=> Make electric engines consume battery power evenly

src/distribution_grid.h, src/vehicle.cpp, src/vehicle.h
SUMMARY: Infrastructure "Refactor power grid traverse code"
I was randomly reading code and found this function confusing. Refactored for readability.
* Split graph traversion and whatever caller wants to do with items.
* Added comments in places where I failed to understand fast.
* Removed `amount` updating from traversing and few hacks on call-sites caused by this.
* Removed redundant "only vehicles" traversion method.
* Removed raw pointers from public interface.
* Run auto tests.
* Loaded my save with power grid and vehicle with batteries, checked that power grid correctly shows power and charges/discharges.
=> Refactor power grid traverse code

src/crafting_gui.cpp, src/inventory.cpp, src/inventory.h, src/recipe.cpp, src/recipe.h
Co-Authored-By: Gordon Watt <15700895+Theundyingcode@users.noreply.github.com>
SUMMARY: Interface "Port over changes from DDA allowing crafting menu to show product stack size, amount of product already nearby"
Finally set aside time to port over a thing Lamandus had been asking me about, allowing the crafting UI to show you how many of an object you have nearby, and make it more clear how many items a recipe will make.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/449
1. Ported over changes to crafting_gui.cpp, including inventory.h and added if statements to `select_crafting_recipe`.
2. Ported over addition of `inventory::count_item` to inventory.cpp and inventory.h.
3. Ported over addition of `recipe::makes_amount` to recipe.cpp and recipe.h. Converted the function to …
=> Port over crafting UI improvements from DDA

data/json/monsters/mammal.json, data/json/monsters/misc.json, data/json/monsters/mutant_human.json, data/json/monsters/nether.json, data/json/monsters/slugs.json, data/json/monsters/zed_fusion.json, src/achievement.cpp, src/map_field.cpp, src/monster.cpp, src/monstergenerator.cpp, src/mtype.h
SUMMARY: Balance "Allow regeneration to be modified by effects."
Regenerating monsters currently don't push for smart approaches, preferring a more dakka approach that doesn't really encourage any kind of tactics.
Port over [#50439](https://github.com/CleverRaven/Cataclysm-DDA/pull/50439) from DDA which extends regeneration and allows effects like on fire, corroding and the like to modify the amount healed.
Change it to multiply regeneration by specific amount instead, instead of a flat addition/reduction, which should be more comfortable to use.
Disable regen entirely under specific effects.
- System as is will allow that, and has more nuance to boot.
Spawned Debug Monster, used molotovs/acid bombs to set them on fire/give them acid burns. Tested that amount of reduction was appropriate, …
=> Port over regen modifiers

.github/workflows/matrix.yml, .github/workflows/release.yml, Makefile, build-scripts/build.sh, src/simple_pathfinding.cpp, src/vehicle_autodrive.cpp
SUMMARY: Infrastructure "Fix CI builds"
Fixes #1627
Made Makefile look into COMPILER parameter
Just remove Makefile and use only cmake.
Not yet
Found out that we don't actually use compilers from matrix when trying to bump C++ version.
#1624
Also little changes in code and some documenting comments.
=> Updated Github matrix and Makefile to use COMPILER parameter

src/faction_camp.cpp, src/item.cpp, src/item.h, tests/basecamp_test.cpp
SUMMARY: Bugfixes "Fix container handling in basecamp distribute food mission"
The mission had 2 bugs:
* Canned food calories calculated like it would spoil:
1. Make a basecamp.
2. Get 2 slices of salted meat chunk.
3. Open them.
4. Distribute them using basecamp and note calories change.
5. Distribute same amount of slices in sealed bags of meat chunk.
6. See that you got same amount of calories despite the fact that food wasn't going to rot.
* Unwanted food and even not food was taken from containers
1. Put can of SPAM and gallon jug of bleach at food distribution zone.
2. Distribute food.
3. See that your SPAM is taken from can and now would rot soon :(
4. And even your precious bleach spilled to the floor and you cannot pick it up now.
Fixes:
1. Check if food in container which …
=> Fix container handling in basecamp distribute food mission

src/crafting_gui.cpp
SUMMARY: [Bugfixes] "Allow recipe category merge"
Some recipe categories added by mods may have same id with the vanilla one, this PR makes them merge together, fix duplicate recipe categories in the crafting gui.
Fix #1607 
Skip duplicate element in `craft_cat_list` and `craft_subcat_list`, `craft_subcat_list` won't clear before adding.
Simple and easy, but not the best solution.
I think the best solution is to implement this craft_cat in `generic_factory` way. But seems over complicated? Idk.
Create a new world with DinoMod loaded, no duplicate "Animals category" anymore.
=> Allow recipe category merge

src/vehicle.cpp
SUMMARY: [Bugfixes] "Projectiles that deal less than 20 damage can't go through cars"
Fixes #730
Shots that deal too little damage to do anything to a vehicle part now lose all their momentum when this happens.
=> Shots less than 20 damage don't go through cars

data/mods/Aftershock/vehicles/vehicle_parts.json
SUMMARY: Balance "Made the Aftershock foldable ultralight frame a more sane folded volume"
The afs foldable frame folded to 10 L which is far larger than any base foldable frame and is also significantly larger than the item it is installed from. In addition, the name of the part is inconsistent with the other foldable frames.
Frame folded volume is now 4 L down from 10. Part name string is now "foldable ultralight frame" to match all the other foldable [material] frames.
A different volume than 4 L.
- Created a new save with a folded ultralight vehicle
- saved & quit
- modified the JSON
- folded ultralight vehicle is same volume as before
- unfolded & refolded vehicle
- it's now the lower volume
So it loads just fine and doesn't seem to break anything, just needs to be recalculated.
=> Sane aft frame folded volume

src/savegame_json.cpp
SUMMARY: [Bugfixes] "Save stomach data so it won't lost during save/load"
Fix #1615 
Just save/load the stomach data.
Do the same thing as #1615 says. After this PR, the character is no more hungry again.
=> Stomach data should be saved

src/bionics.cpp, src/character.h, src/game_inventory.cpp, src/item.cpp, src/item.h
SUMMARY: Interface "Improve Read selection view (especially for NPC)"
I tried to make NPCs read books many times in last playthrough and found that color scheme and alphabet sorting instead of sorting by skill make choosing a book very inconvenient.
Grouping by skill and ordering by time to read should greatly simplify choosing of a book to read for players too.
Changes:
* Books with same skill training group together in reading menu. Skills sorted by localized name.
* Still not finished training books with same skill sorted by time required to read.
* When asking NPC to read, shows time to read a `chapter` like for player character.
* When asking NPC to read, shows colors for NPC skills, not for player. E.g. if player skill is 9 and NPCs is 7, book with level 8 would be blue.
* Now …
=> Improve Read selection view (especially for NPC)

src/activity_actor.cpp, src/activity_actor_definitions.h, src/activity_item_handling.cpp, src/item.cpp, src/npc.h, src/npcmove.cpp, src/npctalk_funcs.cpp
SUMMARY: [Bugfixes] "Fix some problems of thievery "
Fix #1572 
Fix #1581 
Action "Sort out my loot" does not move items that do not belong to the player faction (no theft).
For #1572, make the NPC talk about thievery immediately once they notice you steal something.
For #1581, move the code to right position (I believe they are placed wrong during the migration).
Add items owner check in move loot action.
Tested thievery in refugee center. Works as intended apparently.
=> Fix some problems of thievery 

src/map.cpp
SUMMARY: Bugfixes "Fixed crash in lightmap generation after debug long teleport"
Fixes #725
Add full vehicle list invalidation to `map::clear_vehicle_list`
Sticking it in `map::load` that's called on long teleport, but I'm paranoid.
1. Bind quicksave key
2. Move mouse cursor outside game window
3. Find (or spawn) a vehicle
4. Enter debug menu -> teleport -> long range -> any destination more than 2 overmap tiles away
5. Hit quicksave key
6. Before fix: CTD
After fix: game quicksaves with no issues
Somehow I've encountered this "rare" crash dozens of times, got fed up with it.
=> Fix crash in lightmap generation after debug long teleport

src/item.cpp
SUMMARY: Bugfixes "Include effects from gunmods when displaying gun damage in item info"
Fix #1566
Use damage from gun with all gunmods rather than raw gun damage. Range display already does this.
Repeated repro steps from the issue, item info screen now displays increasing gun damage.
Also works in "compare before/after installation of gunmod" screen.
=> Include effects from gunmods when displaying gun damage in item info

src/map.cpp
SUMMARY: Bugfixes "Fixed smash_fail sound not playing"
Fix #1579
`smash_fail` variant initialization seems to have been accidentally removed in #1307, added the code back in.
Before: smashing walls and furniture results in no sound unless they break.
After: smashing walls and furniture always produces sound.
=> Fix smash_fail sound not playing

data/json/npcs/refugee_center/surface_refugees/NPC_Fatima_Al_Jadir.json
SUMMARY: Bugfixes "Remove broken Fatima teaching dialogue option"
Fix #1543 
Remove broken dialogue options that refer to non-existing talk topic.
In DDA, Fatima later gained the ability to teach g->u the wielding proficiencies, but proficiencies are not in BN, so it's impossible to port. She could teach mechanics instead, of course, but NPC skill teaching is overall kinda broken and needs an overhaul first.
Went to refugee center, spoke to Fatima. She gives the backstory, but does not prompt to teach anything now.
=> Remove broken Fatima teaching dialogue option

data/core/basic.json, data/json/items/gunmod/bionicmods.json, data/json/items/ranged/launchers.json, data/json/not_really_obsolete.json, data/mods/Aftershock/items/bioparts.json, data/mods/No_Hope/Items/guns.json, src/item_factory.cpp
SUMMARY: Bugfixes "Fixed debugmsg when firing water cannons"
Fix #1638 
Move the flag from water cannon to water.
Validate gun (and gunmod) ammo effects on load.
Something more complex that allows gun(mods) to alter ammo recovery rates, but upon searching through BN repo and Kenan's modpack there seemed to be no cases of that actually being used in some meaningful way.
Loaded a random world, spawned fire engine, fired the water cannons.
Before fix: a debugmsg, no puddles.
After fix: a puddle, no debugmsgs.
=> Fix water cannons

.clang-tidy, tests/catch/catch.hpp
SUMMARY: Infrastructure "Upgrade Catch2 library to v2.13.8"
Older version was [problematic](https://github.com/catchorg/Catch2/issues/2272) during C++20 migration so I updated library version. Decided to make it different PR because C++20 migration appears to be not so easy as I thought so I decided to split away complete parts.
I just copied their file from [their release](https://github.com/catchorg/Catch2/releases/tag/v2.13.8) in github.
I edited one variable name in their code because it clashed with our translation define (changed it from `_` to `__`).
Also removed catch.h from clang-tidy checks.
Excluded `catch` from clang-tidy because it is third-party library.
=> Upgrade Catch2 library to v2.13.8

msvc-full-features/stdafx.h, pch/main-pch.hpp
SUMMARY: Build "Add colony.h to precompiled headers for a small build speedup"
`colony.h` is the largest extensively used header file in the project. It's essentially third-party code, and it makes its way into over 160 compilation units. A prime candidate for precompilation.
Add `colony.h` to the list of precompiled headers.
Implementing an opaque wrapper over `colony<item>` so that `colony.h` gets included only once, in wrapper's `.cpp` file, and the rest of the code uses the wrapper defined in a lightweight header, but testing showed there to be too little build time improvement over the current solution to justify spaghettification.
Compiled with `time make -j4 -k COMPILER=clang++-12 TILES=1`.
Before:
```
real    20m22,521s
user    75m19,058s
sys     1m47,387s
```
After:
```
real …
```
=> Add colony.h to precompiled headers

data/mods/Aftershock/maps/furniture.json, data/mods/Aftershock/recipes/deconstruction/deconstruction_overrides.json
SUMMARY: Bugfixes "fixes #1675"
Autodocs deconstruct into parts instead of autodoc item like in base game
Autodoc deconstructs to item, item disassembles to parts.
Loaded it up, worked great.
=> Aftershock doesn't interfere in base game autodoc uninstallation

.github/workflows/documentation.yml
SUMMARY: Infrastructure "Add workflow to deploy documentation on github page"
for some reason removed github action yml last commit in #1603, so it doesn't do much.
reverts the github workflow in question.
at least it works on my machi... fork
- [workflow run result](https://github.com/scarf005/Cataclysm-BN/actions/runs/2478209181)
- [deployed gh pages in fork](https://www.maribel.dev/Cataclysm-BN/)
this is a follow-up PR to #1603, please also check here
=> Add workflow to deploy documentation on github page

src/handle_liquid.cpp
[Bugfixes] Fix a crash when picking up liquids
This is the weirdest bug. The actual problem is simple, it's missing a null pointer check when looking for adjacent vehicles when you're picking up liquids from the ground. What I really don't understand about it is that the crash appears and disappears depending on your compile flags. With O3 or O2 it crashes, with Os it doesn't. It seems like it should just crash consistently.
Null pointer check.
Exorcising my compiler.
=> Fix crash picking up liquids

data/json/furniture_and_terrain/furniture-terrains.json
From here https://github.com/CleverRaven/Cataclysm-DDA/pull/52861
Co-Authored-By: StringhamEthan <69316833+StringhamEthan@users.noreply.github.com>
SUMMARY: Balance "Port increased boulder rock drops from DDA"
Boulders drop very few rocks, seems like a whole boulder should drop more.
Make them drop more by copying commit were somebody fixed the same problem in DDA.
Do basically the same thing but with different numbers.
=> Boulders drop more rocks port from DDA

data/mods/TEST_DATA/terrain.json, src/cached_options.h, src/debug.cpp, src/handle_action.cpp, src/main.cpp, src/map.cpp, src/map.h, src/mapdata.cpp, tests/map_test.cpp
SUMMARY: Bugfixes "Fix crash in some mods when burning roofs"
Should fix the crash in @thelonestander 's save, with the burning flesh building.
The problem can be formulated as follows:
* Tile with a roof `C` (for "ceiling") has a roof `A`
* Roof `A` is bashed down to another roof: `B`
* Someone bashes down roof `A` that is over tile `C`
* What happens now?
I see the following solutions:
* `A` will turn to `B`, `B` will then be destroyed to air, air will be "plugged" with roof of the tile below, so with `A` again - infinite loop, the thing that we see right now
* `A` is a roof tile of `C`, so we could wreck both `A` and `C` whenever one is over other - simple and "good enough", although it might get weird in some cases
* Track all the changes until a loop would happen (`A`->`B`->`A`), …
=> Fix crash when bashing/burning roofs in some mods

data/json/item_category.json, data/json/loot_zones.json, data/mods/Magiclysm/items/spell_scrolls.json, data/mods/Magiclysm/items/spellbooks.json
SUMMARY: Interface "Adds spellbook item category and loot zone"
Magiclysm spellbooks and scrolls are difficult to sort and search for because they are categorized as "other"
Adds a new item category "spellbooks" to spellbooks and scrolls and an associated loot zone so they can be easily prioritized and searched for.
Making them categorized as normal books. Also, putting a space between "spell" and "book"
Dropped the edited JSONs in a fresh copy of the game and everything worked as expected.
=> Adding magiclysm spellbook category for ease of sorting

data/json/monsters/mammal.json, data/json/monsters/misc.json, data/json/monsters/mutant_human.json, data/json/monsters/nether.json, data/json/monsters/slugs.json, data/json/monsters/zed_fusion.json, doc/MONSTERS.md, src/monster.cpp, src/monstergenerator.cpp, src/mtype.h
SUMMARY: Infrastructure "Change regeneration modifiers into a JsonObject instead of an array."
Suggested by @Coolthulhu to allow for easier read/write and to add scaling modifiers for effect intensities.
Regeneration modifier in json converted to object with items Effect, base_mod and optional scaling_mod.
Temporarily adds a print message proceeding regeneration in order to know how much is actually being regenerated. Once this has been tested properly it will be removed before merge.
- Just extend the array to contain 3 variables instead of 2.
Considered to not be particularly user friendly for reading/writing.
=> Regeneration Modifier Rework

src/basecamp.cpp, src/mapgen.cpp, src/omdata.h, src/overmap.cpp, src/overmap.h, src/string_utils.h
SUMMARY: Bugfixes "Fixed generation of adjacent elevated bridges"
As in the title. If 2 (or more) bridges generated next to each other, the code that elevates them would wrongly detect bridgeheads and make an untraversable mess.
Refine the check, and also clean oter_id rotation API a bit.
Watching people suffer
I wasn't lucky enough to get an overmap with 2 adjacent bridges show up, so I had to hardcode them in (not present in PR), and the new elevation code seemed to be discerning them properly. Also teleported to bridgeheads, they also seem fine.
=> Fix generation of adjacent elevated bridges

src/game_inventory.cpp, src/item_search.cpp
SUMMARY: Interface "Book selection menu: filter by name by default"
Book selection menu is searching by skill name, not item name, which is counter-intuitive as it does not adhere to behavior of other similar menus.
Closes #1191
Filter by item name instead, and add special `k:` prefix for searching by skill name.
Spawned a bunch of books, tried searching using different terms.
Also tested that search works with localized item and skill names.
=> Book selection menu: filter by name by default

data/raw/keybindings.json, src/action.cpp, src/action.h, src/game.cpp, src/handle_action.cpp, src/item.cpp, src/item.h, src/player.cpp, src/player.h, src/ranged.cpp, src/ranged.h
SUMMARY: Interface "Add separate keybind for selecting which gun ammo is used by default"
Fixes #1352
When pressing `F` to change gun mode if the gun has only 1 mode, and it's either `RELOAD_AND_SHOOT` (slings, bows) or `RELOAD_ONE` (shotguns, revolvers), the game will instead try to select default ammo to use.
There are a couple problems with this:
1. If none of the loading options are available (e.g. shotgun is loaded with regular shot, but you only have dragon breath left), the game will show a erroneous "You don't have any X to reload your Y" message.
2. If the shotgun has a second magazine (e.g. `Kel-Tec KSG`), it has a second firing mode, so the player loses ability to select default ammo.
1. Add a separate keybind for changing default gun ammo, and remove default ammo selection …
=> Add separate keybind for selecting which gun ammo is used by default

data/json/construction.json
SUMMARY: Bugfixes "Can't mine down through roofless rock floor"
Only `t_rock_floor` and not `t_rock_floor_no_roof` can be mined down through via the "mine downstair" construction.
Copy of original construction but with `t_rock_floor_no_roof` prerequisite.
Make rock walls mine into the roofed version, or use a terrain tag to allow mining down instead of a specific terrain match.
Dropped the change in, it worked.
(construction time sped up via options menu for testing purposes)
=> Make mine_downstair work on rock floors without roof

data/json/uncraft/armor/armored.json
SUMMARY: Content "Missing uncraft recipes for armored armor"
Resolves #1595 
and a little more.
Allows to cut armored jackets into leather and scrap. Also allows same thing for armored leather vests, fingerless gloves, armored boots and gauntlets. The latter requires something to saw the metal, too.
None.
Debug spawn above-mentioned armor, try to butcher or disassemble it. It just works.
Look out for more missing uncraft recipes, report them to the guards!
=> Missing uncraft recipes for armored armor

doc/JSON_INFO.md, src/vehicle.cpp
SUMMARY: Bugfixes "Cargo Weight Modifiers rounding to 0/100/200, etc"
`cargo_weight_modifier` currently works weirdly, with anything below 100 turning to 0 and anything above 100 incrementing to the nearest 100. This prevents it from working as intended.
Ports over [53811](https://github.com/CleverRaven/Cataclysm-DDA/pull/53812) from DDA. Also amends the documentation which had a duplicated entry for `cargo_weight_modifier`.
Made bicycle baskets have 10 `cargo_weight_modifier`, added items to the basket and observed weight increase from vehicle menu.
Since we don't want negative mass, we might want to sanity check the calculations so any `cargo_weight_modifiers` below 0 become 0.
Aside from that perhaps we might benefit from giving decimal places to vehicle weight displays, though this is …
=> Cargo weight modifier update

src/character.cpp, src/item.cpp
SUMMARY: None
Fix windows build
Get rid of shadowing when iterating, since the cross-compiler we use is based on some ancient `g++` (version 5 or something) that doesn't handle it well.
Making msvc build the only one
Compiles locally, but will wait for CI
=> Fix windows cross build

src/map.cpp
SUMMARY: Bugfixes "Prevent `map::destroy` from wrecking floors when it was aimed at a wall"
Fix #1711
If `map::destroy` is "aimed" at something impassable, stop bashing when the terrain becomes passable.
* Disallowing destroying floors without the flag set
* Changing pickaxe to use a different method
* Spawn pickaxe
* Teleport self underground
* Apply pickaxe at a solid rock
* Verify that it leaves a rock floor and not open air
=> Prevent `map::destroy` from wrecking floors when it was aimed at a wall

src/item.cpp
SUMMARY: Bugfixes "Magazine weight was not being added to items with a magazine."
Fixes #1677.
Item weight code lacked a check for whether an item had a magazine, and thus did not add the relevant weight to the gun.
Ignore for another 2 months
Spawn M4A1, 10 round STANAG magazine and SIG 552. Record all weights, unload both bullets and magazines from all 3. Checked both guns without magazine, with empty magazine, and with full 10 round STANAG magazine. Confirmed numbers are as expected.
=> Magazine Weight Fix

src/consumption.cpp
Linted
A follow up Pr for #1207. 
This allows non-food comestibles to also be usable by players with traits that limit food types in the same way the Made of Sugar trait does.
N/A
Compiled and tested, works great!
=> Allows the use of bandages for players with traits like Made of Sugar

data/json/items/comestibles/carnivore.json, data/json/items/comestibles/raw_veggy.json, data/json/items/comestibles/wheat.json, data/json/items/generic.json, doc/JSON_INFO.md, src/iexamine.cpp, src/item_factory.cpp, src/item_factory.h, src/itype.h
SUMMARY: Infrastructure "Ports over jsonized milling results"
Port over [41174](https://github.com/CleverRaven/Cataclysm-DDA/pull/41174) from DDA repo that allows one to define items as millable and define their results outside of hardcode.
Converted their implementation to use int values so as to prevent products being made out of thin air.
> Removes the (undocumented) flag "MILLABLE".
> 
> Adds an item slot that defines what an item can be milled into (e.g. for "wheat" that would be "flour").
> 
> Fixes mills to produces flour at the same conversion rate as manual crafting. Mills used to give 15 flour for 1 input item. But crafting it with a quern requires different amounts of input items to get the same 15 flour as result. For example it takes four oats to craft 15 flour. This has been …
=> Make milling results definable in JSON (#41174)

src/avatar.cpp, src/morale.cpp, src/morale.h, src/player.cpp, src/player.h
SUMMARY: Bugfixes "Fix Morale Calculations."
Originally this PR was to fix a display oddity, as fatigue would display on the morale screen as a penalty when in reality it capped the focus equilibrium display and increased/decreased fatigue penalties accordingly. Leading to unintuitive situations where the more you tried to increase your morale the higher the penalty became.
While converting it to display as a cap. It was found that morale calculations were broken. Fatigue itself did not affect the focus equilibrium, but rather applied extra per tick decrements directly to focus change calculations. Furthermore, the caps for each tier of fatigue were different from the player side display.  
Created new function `calc_fatigue_cap()` to unify the calculations, so that only one calculation …
=> Rework Morale Display

src/activity_handlers.cpp, src/editmap.cpp, src/game.cpp, src/grab.cpp, src/handle_action.cpp, src/map.cpp, src/map.h, src/mapgen.cpp, src/submap.cpp, src/veh_interact.cpp, src/vehicle.cpp, src/vehicle.h, src/vehicle_move.cpp, src/vehicle_use.cpp, tests/vehicle_ramp_test.cpp, tests/vehicle_test.cpp
SUMMARY: [Bugfixes] "Allow turning on ramps, interacting with vehicles across z-levels and prevent disappearing parts"
Fixes #1212 by reallowing turning on ramps. It also fixes two other problems mentioned in that issue. Attempting to interact with vehicle parts on a different z level to the player won't cause an error and vehicles on ramps will no longer half disappear when loading or shifting submaps.
Currently the code checks every part to see if it's on a ramp and move it up or down accordingly. Turning could cause parts to skip the ramp and collide with the floor or float and there was a lot of code accounting for the fact that the precalc z level wasn't correct until one of the last steps of movement. 
With this, we update the z levels at the same time as the rest of the movement, …
=> Fix turning, interacting with and shifting vehicles on ramps

src/action.cpp, src/activity_actor.cpp, src/activity_handlers.cpp, src/activity_item_handling.cpp
SUMMARY: Infrastructure "[DDA Port] Port code to use global getters instead of g->u and g->m"
Reducing dependency on `game.h` and `game` class.
This and following PRs are cherry-picks of corresponding DDA PRs.
This one is https://github.com/CleverRaven/Cataclysm-DDA/pull/41358
The idea is to use `get_map()`, `get_avatar()` and `get_player_character()` instead of including `game.h` just for `g->m` or `g->u`.
Cherry-picks are done somewhat loosely (parts of commits are dropped, parts are adapted for BN) since the divergence is quite noticeable at this point, so some usages of `g->u` or `g->m` may remain in the changed files.
Doing this manually, but that would produce even more merge conflicts down the line.
Compiles locally. No behavior changes intended.
These are bound to cause merge …
=> [DDA Port] Map reference migration part 1

src/map.cpp, tests/vehicle_test.cpp
SUMMARY: Bugfixes "Fixes crash during mapgen"
No more segfaults.
More null pointer checks on submaps.
I'm going to actually look at this and work out why they're null in the first place. I'm adding checks to the specific part that the ramp code triggers but those checks are missing everywhere because it's meant to be that they're initialized by that point. 
Not enough apparently. 
Also changes g->m to get_map in the tests because it wasn't compiling.
=> Mapgen crash fix

src/sdl_font.cpp
SUMMARY: None
In SDL_ttf 2.20.0 (released 21 days ago), `TTF_FontFaceStyleName` was changed to return `const char*` instead of `char*`. This broke our osx builds, which seem to have moved to version 2.20.0 first out of all our CI environments.
Change to `const char*`, also rewrite the surrounding code to be readable.
Waiting for CI to give green checks.
=> Fix compilation with SDL_ttf 2.20.0

src/requirements.cpp
SUMMARY: Bugfixes "Requirements: fix tool duplication when list already contains replacing type"
Fix tool duplication in requirements when list already contains replacing type (e.g. if list has `fake_welder` and `welder`, `fake_welder` would show up twice).
This is cherry-picked from #1729 for #1742
Check if the list already contains replacing type before adding it.
Done in #1729
=> Requirements: fix tool duplication when list already contains replacing type

src/activity_handlers.cpp, src/iuse.cpp, src/iuse_software.cpp, src/iuse_software.h, src/morale_types.cpp, src/morale_types.h
SUMMARY: Bugfix "Rebalance gaming machines and fix power consumption"
Fix #1751.
Also found out that morale bonus from `game_do_turn` is actually pointless as 99% of the morale boost is handled in `iuse::portable_game`.
In the same vein, `generic_game_do_turn` ultimately granted 8 morale only despite using an entire hour due to ~morale decay~ unintuitive code. It also did not have _any_ checks for consuming charges. Furthermore, routing through `generic_game_do_turn ` instead of `play_videogame` was unnecessary, as that function already has a check for if the game is a generic game.
First, changed the way `game_do_turn` processed such that it would use the item charges first, and only look for UPS if the charges were used up.
Then, ripped out the morale bonus in `game_do_turn` because it …
=> Gaming Device update

lang/extract_json_strings.py, src/mapdata.h
SUMMARY: I18N "Translate prying messages"
Fix #1721
Extract prying messages in `lang/extract_json_strings.py`.
Switch relevant message members in `map_data.h` to use `translation` class so that they're actually translated in-game.
Locally ran `lang/extract_json_strings.py`, saw the new messages in the POT.
Compiled a MO with translated prying messages, saw them appear in-game.
=> Translate prying messages

src/om_direction.h, src/overmap.cpp
SUMMARY: Bugfixes "Fixed automatic sprite rotation for non-linear overmap tiles"
If overmap terrain is rotatable, and the tileset has no explicitly defined rotations for the corresponding tile which is also marked as rotatable, then the game would try to automatically rotate that single tile to match rotation of the omt. Except the rotation direction is wrong (screenshot of `ws_regional_dump` found in latest unpacked UDP version):
This PR fixes this bug.
Turns out `rotations` for omts are clockwise rotations, and `rotations` for tileset sprites are counterclockwise rotations. This PR adds proper conversion from omt rotation to sprite rotation.
Rewriting the renderer.
Re-packed UDP with the aforementioned `ws_regional_dump` for testing: …
=> Fix automatic sprite rotation for non-linear overmap tiles

src/activity_item_handling.cpp, src/advanced_inv.cpp, src/character.cpp, src/character.h, src/game.cpp, src/game_inventory.cpp, src/player.cpp, src/player.h
SUMMARY: Bugfixes "Fixed CTD when trying to drop worn NO_TAKEOFF items, other related fixes"
Fix #1475, improve NO_TAKEOFF handling in some other cases
1. In dropping activity, show debugmsg and skip item if failed to drop it
2. Add message when failing to drop the item through item overview screen (`i`->select item->`Enter`)
3. Don't show worn NO_TAKEOFF items in multidrop menu
4. In item overview screen, fix colors of drop & wield options for worn NO_TAKEOFF items
5. In AIM, check whether can drop item before starting activity
Tried to drop active worn foodperson mask via multidrop screen, AIM and via item overview screen, all failed.
=> Fix CTD when trying to drop worn NO_TAKEOFF items, other related fixes

src/avatar.cpp, src/player.cpp, src/player.h
SUMMARY: Infrastructure "Refactor `calc_fatigue_cap()"
Was suggested in #1708 to convert `calc_fatigue_cap()` to use int instead of accepting the entire character class.
Converts `calc_fatigue_cap()` to use int argument instead of character argument. Adjusted code accordingly.
Started new character, applied fatigue, applied pain, tested that morale displayed and changed appropriately.
=> Refactor calc_fatigue_cap()

data/json/overmap/overmap_connections.json, data/json/overmap/overmap_special/mine.json, data/json/overmap/overmap_special/specials.json, data/mods/Aftershock/maps/overmap_specials.json, data/mods/DinoMod/overmap/overmap_specials.json, data/mods/Fuji_Structures/worldgen/overmap_specials.json, data/mods/More_Locations/bandit_tower/overmap_specials.json, data/mods/More_Locations/estate/overmap_specials.json, data/mods/More_Locations/factory/overmap_specials.json, data/mods/More_Locations/military_outpost/overmap_specials.json, data/mods/More_Locations/multistory_houses/overmap_specials.json, data/mods/More_Locations/refugee_tower/overmap_specials.json, data/mods/More_Locations/tri_tower/overmap_specials.json, data/mods/National_Guard_Camp/overmap_specials.json, data/mods/No_Rail_Stations/overmap_specials.json, data/mods/Salvaged_Robots/robot_additions/overmap_special.json, data/mods/desert_region/desert_overmap_connections.json, data/mods/mapspecials_demo/megastore/overmap_specials.json, data/mods/mapspecials_demo/missile_silo/overmap_specials.json, doc/JSON Mapping Guides/Guide for beginning mapgen.md, doc/OVERMAP.md, src/omdata.h, src/overmap.cpp, src/overmap.h, src/overmap_connection.cpp, src/overmap_connection.h, src/overmap_special.h, src/savegame.cpp
SUMMARY: Infrastructure "Modernized oms connections JSON, deprecate autoguessing from "terrain""
Railroad-related yak shaving.
Modernize overmap special connections JSON, deprecate "guess-connection-from-specified-terrain" hack.
No behavior changes intended.
1. Remove some dead code (old "roads_out" migration, unused declarations, unused field "flags")
2. Replace terrain ids in connection with explicit connection ids (e.g. `"terrain": "road"` -> `"connection": "local_road"`)
3. Add a deprecation warning for `"terrain"` field, implement hardcoded migration to relevant connection for out-of-repo mods.
4. Prevent connections from starting at a point occupied by some other oms terrain, fix existing cases.
5. Simplify blacklist for No_Rail_Stations mod
Created new world, teleported around to …
=> Modernize oms connections JSON, deprecate autoguessing from "terrain"

data/mods/CRT_EXPANSION/items/crt_gun.json
In the mod CRT Expansion there and an effect called "messy" this was invalid so I got rid of it. This throws an error upon loading and this will fix it. 
Just got rid of the [ "messy" ] effect for the gun. 
None
Tested in game. CRT loaded. Gun still works. Everything looks good. 
N/A
=> Remove messy flag within CRT expansion to get rid of load error. 

data/json/items/gun/faults_gun.json
SUMMARY: Balance "Port over improvements to gun cleaning"
Simple port over of a DDA JSON PR that makes gun cleaning allow a wider range of items to use in the mending, and in particular fixes gun cleaning using wacky amounts of materials like soapy water.
1. Ported over changes greatly expanding the list of available solvents, minus any not present in BN, and changing amounts used to not consume entire liters of low-stack-size stuff.
2. Ported over addition of cotton balls, faux fur, and wool patches to the options allowed for gun cleaning.
1. Adding gauze pads and/or lycra patches to the options too.
2. Adding some sort of dedicated "small patch of cloth" item with a basic recipe, because even as-is it's still kinda intensely wasteful to eat whole rags just to clean a gun once.
3. …
=> Port over expanded options for gun cleaning

src/advanced_inv.cpp
SUMMARY: Bugfixes "Fixed CTD when dropping stashed items in AIM"
Fix #1773
Split branches for cases when source pane is `WORN` or `INVENTORY` and remove worn-related checks and assertion from `INVENTORY` branch. Also get rid of superfluous manipulations around worn item index.
Dropped some worn items, then wore them back from ground.
Dropped some stashed items, then picked them back up.
Moved some items from worn to inventory and back.
`NO_TAKEOFF` items still can't be taken off.
=> Fix CTD when dropping stashed items in AIM

msvc-full-features/Cataclysm-vcpkg-static.vcxproj
SUMMARY: Bugfixes "Added executable icon to msvc build"
Fix #1717
Mingw build includes a resource file that describes the ico to use for the executable.
Add this file to msvc build as well.
Compiled the game in Visual Studio and with Github Actions, launched the game on Windows, saw that exe has the icon.
https://github.com/olanti-p/Cataclysm-BN/releases/tag/cbn-experimental-2022-08-10-2041
=> Add exe icon to msvc build

src/cata_tiles.cpp
SUMMARY: Bugfixes "[DDA Port] Fix black lines and misaligned rotated sprites on Windows"
Fix black lines and misaligned rotated sprites on Windows.
Example cases:
Cherry-pick https://github.com/CleverRaven/Cataclysm-DDA/pull/45524, which removes the offset.
From the discussion in original PR, that most likely was a workaround for some SDL bug which appears to have been fixed since (our mingw releases use SDL 2.0.14 at the moment and msvc - SDL 2.0.20).
Done on Windows 10.
Downloaded latest release, then compared with the fixed releases built by GA on my own fork:
https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-08-06-2156
Before: tiles are misaligned with direct3d11/software/opengl renderers in both msvc and mingw x64 releases.
After: tiles are drawn …
=> [DDA Port] Fix black lines and misaligned rotated sprites on Windows

data/json/overmap/overmap_special/specials.json, src/overmap.cpp
SUMMARY: Bugfixes "Audit occurrences and spawning of labs vs. microlabs, fix weird spawning of experiment cell mapgen"
A complaint I'd seen a few times has been that microlabs seem to be vastly more common than regular labs overall, which is presently a problem given the microlabs are currently effectively filler, at least until I can do some work on https://github.com/cataclysmbnteam/Cataclysm-BN/issues/971.
Per feedback, this in itself isn't a massive problem, though personally if I could make regular labs equally as common as microlabs I'd like to, but worldgen likes to bundle overmap specials into the same general patches of similarly-compatible city distances. However, the low occurrence rates of the unique lab variants does have a magifying effect on regular labs being …
=> Update placement of labs, fix lab cell start

msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-test-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-vcpkg-static.vcxproj, msvc-full-features/JsonFormatter-vcpkg-static.vcxproj
SUMMARY: Infrastructure "Enabled runtime assertions in msvc builds"
Fix #1779
Get rid of `NDEBUG` in defines
Keeping arcane differences between windows builds
Added an always-failing assertion, compiled release build with VS, launched it. Got an assertion failure.
=> Enable runtime assertions in msvc builds

data/json/itemgroups/Clothing_Gear/clothing.json, data/json/itemgroups/Locations_MapExtras/locations_commercial.json, data/json/itemgroups/Locations_MapExtras/mall_item_groups.json, data/json/itemgroups/Locations_MapExtras/mansion.json, data/json/itemgroups/activities_hobbies.json
Gets rid of the fitness band from game since it does nothing.
In game the fitness band currently doesn't do anything. Figured since its an item nobody can use it would be best to get rid of it. 
Scrubbed the fitness band from various locations it was meant to spawn in. 
Either fixing the fitness band to work (I left it in the obsoleting file just in case) 
Tested in game, the item does not show up! 
N/A
=> Removes Fitness band from relevant places

src/vehicle.cpp
SUMMARY: Bugfix "Make debug message for lift_thrust print properly"
Debug message for lift_thrust couldn't print because it was trying to taking an int for a float conversion.
Changes from float to int in the debug message.
Spawned atomic helicopter, turned on debug mode and started the vehicle, debug message displays properly.
I know that lift is now displayed correctly, but the math is still a bit of a headache for me.
=> Fix double to int for debug message

src/iuse.cpp
SUMMARY: Bugfixes "Make Bionic Scanners work with UPS Conversion Mods"
If a bionic scanner has the UPS conversion mod installed, it will simply fail the moment you get close to a bionic carrying monster, as the `note_bionics` iuse has no support for the `USE_UPS` flag.
Fixes #1133 
Adds a check to ensure that the bionic scanner is possessed by the character, and if there's not enough charge in the device (automatic since ups conversion mods remove the internal battery) it will draw from any UPS source you have instead.
- Make bionic scanners go by power_draw instead.
Rejected on basis of reward/resource consumption mismatch.
New game, spawned in bionic scanner. Installed ups conversion mod. Spawned bio-operator, killed bio-operator. Repeated while I checked several things.
=> Add UPS conversion support to Bionic Scanner

.github/CONTRIBUTING.md
SUMMARY: Build "Change CONTRIBUTING.md to point at the current BN repository"
The contributing document currently points to [a private or nonexistent repository](https://github.com/CleverRaven/Cataclysm-BN.git). This is a simple text change to point it at the current repository under cataclysmbnteam.
Simple documentation text change; no testing needed.
=> Point CONTRIBUTING.md to the right upstream repository

src/character.h, src/iuse.cpp, src/newcharacter.cpp, src/newcharacter.h, src/player.cpp, src/player.h, tests/iteminfo_test.cpp, tests/new_character_test.cpp, tests/player_helpers.cpp
SUMMARY: Infrastructure "Reorganized some Character-related code"
Continuing despaghettification.
1. Rename `Character::empty_skills` -> `Character::clear_skills`, as `empty` is usually used for functions that check for emptiness.
2. Move more character creation code out of `player` and `Character` classes. Some of it has absolutely no business being non-const methods of `Character` class when all it does is operate on globals...
3. Move some of the methods tailored specifically for character creation menu into `newcharacter.h`/`.cpp` as well
4. Replace some `g->u` usages with `get_avatar()`
5. Get rid of `player::purifiable()` method since it only checks for trait flag under the hood
Game compiles. No behavior changes intended.
=> Character code reorganization 22-aug-2022

src/map.cpp
SUMMARY: Bugfixes "Fix null field id error when butchering some corpses"
Fix #1753
`map::add_splatter_trail` has a check for null id, but `map::add_splatter` does not. Add it there as well.
Tracking down every place in the code where `add_splatter` could be fed null id?
Tried dismembering broken cyborgs.
Before: debugmsg
After: no debugmsg
=> Add check for null field id in map::add_splatter

src/player.cpp
SUMMARY: Bugfixes "Unload pet food instead of eating it when activating container"
Fixes #584
Activating unloaded pet food allows placing it, but when activating canned pet food, the character eats it.
That's almost always not the desired behavior.
When activating canned pet food, unload it instead.
Making pet food inedible.
`a`ctivated can of dog food, it was unloaded.
`a`ctivated unloaded dog food, was prompted to feed a dog.
Explicitly `E`ating still works on both canned and uncanned.
=> Unload pet food instead of eating it when activating container

data/json/mapgen/lumbermill.json, data/json/mapgen/military/mil_base/mil_base_z0.json, src/mapgen.cpp, src/mapgen.h
SUMMARY: Bugfixes "[DDA Port] Fixed multiple issues with gaspump placement"
Fix #1720 caused by integer overflow.
Fix gaspump placement in lumbermills and military bases.
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/46499 which enlarges jmapgen_int to int and prevents overflow.
Includes commit that fixes gaspump placement in lumbermills.
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/46529 which does same but for milbases.
Spawned problematic locations, went there before and after the fix, saw all fixes work as expected.
=> [DDA Port] Multiple fixes for gaspump placement

src/mission_companion.cpp
SUMMARY: Bugfixes "Fix NPCs on a camp mission could be selected for another camp mission"
Fix #780
Fix #1351
Fix #1491
Disallow selecting NPCs that have missions assigned to them, regardless of whether they're a camp worker or not.
Made a camp, assigned a couple NPCs to it, selected one for camp expansion mission. He was no longer available for foraging mission.
Basecamp/mission code is extremely convoluted, it wouldn't surprise me if this breaks something else.
=> Disallow selecting NPC for camp mission if they already have a mission

src/activity_handlers.cpp
SUMMARY: None
Fix regression after #1804 (reported on discord)
Fixes #1827 
Fix inverted condition.
Double checked the rest, should be fine.
None, this change is trivial
=> Fix inverted condition causing spell study to fail

src/cata_utility.cpp, src/newcharacter.cpp, src/output.h, src/skill.cpp
SUMMARY: Interface "Sort Character Creation skills in menus"
Skills in character creation are sorted alphabetically currently, which isn't necessarily easy to look over. During the game, when opening the character menu skills are already sorted by category, so sorting it as such shouldn't be an issue.
Ports over [53052](https://github.com/CleverRaven/Cataclysm-DDA/pull/53052).
Reworks the way the list is populated so that the categories themselves don't have to be added to the skill list, cutting down on excess code (stuff like checking if the item is actually valid or not) and making the solution much easier to add to other menus.
~~The profession menu is currently an issue, I can't get stable_sort to work on the vector of pairs.~~ Just me being an idiot and forgetting to remove `const`. …
=> Sort Character Creation skills in menus

data/mods/Magiclysm/items/enchanted_misc.json
SUMMARY: Bugfixes "Everburning torch can substitute for a regular torch"
The everburning torch can't be used as a torch/fire in crafting recipes right now, but it's a torch though so it should.
Make it a substitute
Ignore it I guess
didn't bother, it's one very simple line
=> everburning torch substitutes for torch

src/activity_actor.cpp, src/activity_actor_definitions.h, src/avatar_action.cpp, src/ranged.cpp
SUMMARY: Bugfixes "Fixed miscellaneous bugs related to bow loading"
Fix #1789
Should also fix #1560
Clear up some confusing UI moments.
While investigating save file from #1789 I found out that `u.ammo_location` points to some item on map.
Turns out, nothing prevented player from selecting an item on map as default ammo for bow, and walking away from it and leaving it outside the bubble would break the `item_location` it points to.
As the solution, forbid selecting items outside player possession as default bow ammo, and future proof the code by resetting `u.ammo_location` whenever valididty check fails.
To improve UI feedback and clear up general confusion around "reloading" of bows, print messages whenever selecting an ammo as default for the bow.
Also fix "your bow isn't loaded" …
=> Misc bow loading/ammo selection fixes

tests/food_fun_for_test.cpp
SUMMARY: Infrastructure "Make the bionic taste modifier test explicitly look for 0."
In #1769 @Coolthulhu made a comment about the tests. Fixing it.
Makes the check explicitly look for 0 instead of implying it via false.
Ignore?
The tests didn't fail when I ran it...
=> Update food fun for test code

data/json/recipes/ammo/shot.json
Fixes 2 minor things:
black powder 00 shots was missing the batch time
black powder junk shots were using 50% of black powder actually needed.
=> 2 Fixes of shotgun shell recipes

data/json/bionics.json, data/json/items/gun/bio.json
Buff bionic shotgun
SUMMARY: Balance "Buff bionic shotgun"
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1772#issuecomment-1204454800
> chaosvolt analysis:
>Making the bionic shotgun able to hold 2 shells may be a related nifty improvement, but outside the scope of this PR.
Bionic shotgun arm stats was compatible with handmade12 gauge pistol. It is weak for such high tech thing and not easy access weapon.
- Increase clip size: 1 => 4.
- Decreased dispersion: 855 =>500.
- Added 2 shot burst.
- Removed damage debuff.
- Edited description. Removed mention about "single shot" only.
Now Shotgun CBM will have somewhat unique role-  something like double barreled  sawed-off shotgun with ammo count for 2 double shots.
Good "surprise" weapons that always with you. Still it will not replace …
=> Buff bionic shotgun

data/mods/Aftershock/items/tools.json
SUMMARY: Bugfixes "Fix Aftershock UPS override creating UPSes loaded with a battery that can't be removed"
So one side benefit I made note of in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1760 is that I wasn't sure how Aftershock's weird overrides would interact with vanilla spawns, now that BN has spawns of the UPS item pre-loaded with a battery.
Turns out they do not fail gracefully, instead of an error on one spawning in you get stuck with a UPS that has a battery permanently stuck in it, that can't be removed and prevents the damn thing from recharging. Thanks to @EkarusRyndren for discovering this the hard way.
1. Removed changes to UPS in Aftershock that remove its magazine definition in favor of max charges.
2. Likewise removed any other unnecessary changes, and updated …
=> Fix Aftershock breaking vanilla UPS spawns

src/avatar.h, src/game.cpp
SUMMARY: Interface "[DDA Port] Show number of monsters in sidebar compass"
One of the popular port requests, show # of monsters in the compass above the minimap.
Cherry-pick https://github.com/CleverRaven/Cataclysm-DDA/pull/49737
Surprisingly, it had no conflicts.
=> [DDA Port] Show number of monsters in sidebar compass

data/mods/Aftershock/recipes/uncraft_bionic.json
SUMMARY: Bugfixes "Fixed desync of build recipes (aftershok mod) in uncraft recipes (base game) of some CBMs"
The base game overwrites the uncraft recipes of the following CBMs that have a craft/uncraft recipe in the Aftershok mod:
"bio_energy_storage",
"bio_power_storage_mkII",
"biobatteries"
"bio_oops"
"bio_evap"
bio_flashlight
"bio_water_extractor"
does not match
Separate uncraft recipes have been added to the Aftershok mod. copied from his craft recipes. only for problematic CBMs
The fix is tested in the game, all recipes work.
Note maybe the "decomp_learn" parameter is not required in uncraft recipes? (but, its presence does not interfere)
=> Craft and uncraft recipe CBM (mod Aftershok)

data/json/overmap/overmap_terrain/overmap_terrain_hardcoded.json, src/map.cpp, src/map.h, src/mapbuffer.cpp, src/mapgen.cpp, src/mapgen_functions.cpp, src/mapgen_functions.h, tests/test_main.cpp
SUMMARY: Infrastructure "Disables map generation and saving during the test suite"
This fixes two problems in the test suite, one that many tests would accidentally trigger mapgen and another that these maps would be saved and loaded between tests. However, the intent isn't really to fix the issues, it's to measure their impact. I have no idea how much this is actually going to fix. I know that mapgen can mess with but not break some vehicle tests and I know that disabling loading gets rid of an issue that only happens on the monster vision branch where ~50% of seeds will fail a bunch of the throwing balance tests but not when ran alone. Past that there could be no impact, but judging by how easy it is to trigger these behaviors, it could also be 99% of our problems. Either way, it helps …
=> Disables mapgen and saving during the test suite.

update-pch.sh
SUMMARY: Build "Fix shebang in update-pch.sh"
since [[ is bash specifix syntax, script fails unless running it explicitly with bash.
Changed shebang to use bash as default interpreter.
=> Fix shebang in `update-pch.sh`

data/json/mutations/mutations.json, data/json/obsoletion/mutations.json, src/character.cpp, src/character.h, src/mutation.h, src/mutation_data.cpp, src/suffer.cpp
SUMMARY: Features "Deobsoletes Pain Recovery mutations. Adds Pain Recovery mutation variable"
Pain recovery was removed because at the time it didn't work. This was due to [#35300](https://github.com/CleverRaven/Cataclysm-DDA/pull/35300) attempting to move `suffer()` and forgetting to replace the effects under `suffer_from_pain()`
`suffer_from_pain()` was removed in favour of applying the modifiers directly to pain recovery in `Character::regen`. A new variable was added to mutations. `pain_recovery` works much in the same way as `healing_awake` or `healing_asleep`. Being an additive modifier to the pain recovery multiplier.
After some discussion, pain recovery was made to give a 100% increase and made a chargen trait. The other versions will remain obsolete as Deadened is a 2 point …
=> Pain Recovery Deobsoletion

data/json/items/book/misc.json, data/json/mapgen/hazardous_waste_sarcophagus.json, data/json/recipes/other/other.json
Adds a book that spawns with the military ID in the Hazardous Waste Sarcophagi.
SUMMARY: Content "Adds a new book that spawns with the military id card in the Hazardous Waste Sarcophagi overmap locations"
1.) The main reason to change this is to give players the ability to go into the location and see what it may have downstairs. Im not spoiling anything, but its cool. 
2.) You can apparently access this location via a questline, however. I feel as though not everyone will find the quest giver (I don't even know who gives the quest) so I gave this as an extra option just in case players cant find it either. 
3.) Another good reason to have this as an option is to allow players to access what IS below and might be able to make use of it. Those of you who have been down to the basement know …
=> A new way to get into the Hazardous Waste Sarcophagus 

data/json/recipes/food/other.json
[BUGFIXES] Fix candied honey to forest honey duplication bug
Fix #1813 
In relation to the file "data/json/recipes/food/other.json", i changed the charges amount of "honey_bottled" from 14 to 7.
No tests have been carried out
=> [BUGFIXES] Fix candied honey to forest honey duplication bug

data/json/items/armor/power_armor.json, data/json/items/armor/sheath.json
As talked about in discord previously i'm bringing this rather simple PR.
Longsword and estoc fall in the strange category where they have to be carried around using a baldric or a back scabbard, which is essentially wrong from both real life and balance perspective (longsword and estocs were carried in scabbard suspended on belt like one handed swords historically, they were just worn at different angle than shorter swords cause of their length).
I will leave back scabbard out of this as it's probably fine for it to remain as the only option to carry great swords.
Baldric is essentially a scabbard which hangs from your shoulder which is a problem gamewise since you basically trade leg encumbrance for torso encumbrance (torso waist layer) and having low torso encumbrance is vital for …
=> Longsword and estoc to fit in scabbard

src/cached_options.cpp, src/cached_options.h, src/cata_tiles.cpp, src/cata_tiles.h, src/editmap.cpp, src/game.cpp, src/map.cpp, src/map_memory.cpp, src/map_memory.h, src/options.cpp, src/sdl_utils.cpp, src/sdl_utils.h, src/sdltiles.cpp, src/vehicle.h, src/vehicle_display.cpp, tests/map_memory_test.cpp
SUMMARY: Features "Draw in lower z levels."
Fixes #1728. Draws in the contents of lower z levels with a visual effect. 
When drawing tiles previously each row would be collected and then drawn in turn. Now the whole map is collected first. It's during this collection that the searching down to lower z levels happens and only the lowest tile is collected. Collected tiles are sorted by z level, then the terrain, furniture, graffiti and trap layers are drawn for each collected tile in turn. Then starting at the lowest z level and working up, the fields, items, vehicles and creatures are drawn for each collected tile and the tiles above them. Lastly the zone markers and revival indicators are drawn. 
Things being drawn on lower z levels have an effect applied to them. Similar to the greyscale …
=> Draw lower z levels

data/json/itemgroups/books.json, data/json/items/book/martial.json, data/json/items/melee/bludgeons.json, data/json/martialarts.json, data/json/mutations/mutations.json, data/json/techniques.json
SUMMARY: Content "Add new barbaran montante martial art from CDDA"
This martial art looks very intersting for high STR characters using heavy weapons. 
It's focusing on armor penetration. 
I thought it would be nice to have it in CBN.
Adding the martial art. I just copy pasted the first commit adding the martial art, the other related commit is about weapon category, and they are not implemented in CBN.
None
I created a character with this martial art, fought a bit with a compatible weapon, and verified that it was working.
Note that the "Impaling Estocada" technique only works with a weapon having at least 8 cut damage, if you're testing it yourself. And the other is a disarm.
This MA shines with the buffs.
Summary of the martial art: …
=> [FEATURE] add barbaran montante MA

src/cata_tiles.cpp, src/cata_tiles.h, src/game.cpp, src/options.cpp, src/sdltiles.cpp
SUMMARY: Bugfixes "Fix mod graphics sometimes not loaded when loading multiple worlds in single session"
Fix #1264
Remember list of mods the tileset was loaded with, and invalidate it if the list changes.
Also added a debug switch that completely disables tileset caching, for modding purposes.
1. Set UDP as current tileset
2. Make a world without mods, save and quit to menu
3. Make a world with Magiclysm, spawn a plastic golem, see it has no sprite
4. Apply fix
5. Repeat steps 2 and 3, plastic golem now has a sprite
=> Improve tileset invalidation between sessions

src/cata_tiles.cpp
SUMMARY: Bugfixes "The no sight property works correctly again"
Fixes #1858 
Only overrides visibility for higher tiles in a stack rather than all tiles.
=> Fixes a bug where no sight let you see items through walls

data/json/overmap/overmap_special/specials.json
Add power grid to farms
SUMMARY: Content "Add power grid to farms (except Isherwood farms)"
Continuation to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1244.
> Adding them to farms, despite the large amount of fields that would give powergen to. Since the ranch camp and industrial center have already been given the okay to have grids, and assuming it's deemed acceptable to do so with the refugee center, it may be fine to add it to farms too.
It seems players tends to try to use power grid on farms. It is logical, since farms - is good potential base location. But previously farms didn't have built in power grids. It time to change that.
Add ELECTRIC_GRID to all farms overmap special.
Obviously it will gridify soil as well due the way power grid works, but it should  doable …
=> Add power grid to farms (except Isherwood farms)

data/json/items/ranged/crossbows.json
Repeating crossbows should reload only one bolt at a time, since the time for reloading won't benefit of an all at once method.
The old system had the problem that if your reloading has to be canceled, you will loose all reloading progress. This change will circumvent it and it will act like shotguns.
=> make repeating crossbow reload one bolt at a time

data/json/recipes/electronic/tools.json
It is not possible to craft soldering iron without having duct tape. In order to get duct tape you either have to find it or learn the recipe from a book. You can't do any proper electronics work without having soldering iron and the problem of duct tape is a stopgap in this issue.
I added the possibility of using bone glue or super glue in the recipe of soldering iron. I see no reason why only duct tape should be able to put the parts together.
Changed the recipe, loaded the game.
=> Glues added to soldering iron recipe

src/effect.cpp, src/optional.h, src/wisheffect.cpp
SUMMARY: None
Fixes #1862
`maybe-uninitialized` quoted in the issue was a false positive.
There also were a couple `range-loop-construct`s.
For former, port https://github.com/CleverRaven/Cataclysm-DDA/pull/51898
For latter, fix type mismatch
Giving up on C++
Compiled the game, ran the test suite.
The rest will be done by GA.
=> Fix gcc 11.2.0 build

src/suffer.cpp
SUMMARY: Bugfixes "fix chemical imbalance modifying eyes temperature"
Fixes #1375
Reset eyes temperature to normal body temperature after a cold/hot effect from chemical imbalance happens
- made a character with the chemical imbalance
- waited until one of the temperature modifications triggered
- the eyes temperature didn't change
=> fix chemical imbalance modifying eyes temperature

data/json/items/fake.json
SUMMARY: Bugfixes "Add food heating when eating to grid RV kitchen and oven"
Fixes #1564
When eating close to a RV kitchen or oven, the food will be automatically heated like with their vehicles counterpart.
If a fire is lit, no power is used.
If there isn't, it will use 25 power (same as the vehicle version).
When no power is left, it doesn't heat the food.
I tested the different conditions described in the solution
=> [FIX] Add food heating to grid furnitures

src/avatar.cpp, src/avatar.h, src/map_memory.cpp, src/map_memory.h, src/vehicle_autodrive.cpp
SUMMARY: Bugfixes "Fixed a couple issues with autodrive and map memory"
1. Fix some rare occurences of `Called map_memory::get_submap() before initializing map memory region.`
2. Make autodrive work at night when not using tiles
1. Preparing memory map region is now not a hard requirement, but rather an optimization.
Where before the mm_submaps were searched/loaded/allocated only on preparation step, and `get_tile()`/`get_symbol()` would only return data from prepared region, now these heavy operations can potentially happen on every `get_*` call. This makes it harder to reason about performance, but less prone to breakages.
2. Map memory was never designed as part of game state. It's a graphical overlay, it's state is used by map drawing routines and the occasional "unmemorize vehicle …
=> Some fixes to autodrive and map memory behavior

src/ballistics.cpp
SUMMARY: Bugfixes "add explosion effect triggers after each explosive ammo is shot" 
Fixes #1904
Adding a "explosion_handler::get_explosion_queue().execute();" after a projectile is shot.
(Cf additional context of the issue for more details)
I repeated the steps in the issue, shotted 5 ammoes and got 5 nice explosions, precisely one after each shot,
None for now
I repeated the steps in the issue.
I also tried some grenades but they worked fine. And I think it's not even related.
I tried to do the same by giving a weapon to a NPC, and I think it works, but he one shotted himself with it. Is it me or they don't seem to be able to shoot at more than 3 meters even with the right commands?
About this part
"This may require some measure to prevent two executes being called on the same queue in …
=> fix "Explosion processing is delayed to end of turn for explode-on-impact ammo"

src/monmove.cpp
Fix #1691 
When a monster tries to reach the player, but has a bashable furniture that he can bash on his path, he'll try to bash it endlessly.
But the function used to bash the terrain/furniture has some bug that don't allow the monster to bash it.
More precisely, the function checks if the terrain is flat/is a road, then if it's bashable, and will stop the bashing attempt if it isn't. But it doesn't check if there is a bashable furniture on it.
This can be observed with a zombie soldier/zombie hulk and a large canvas door/animal skin wall/cardboard wall on a flat terrain
Fix the function so it checks if there's is a bashable furniture on the terrain before stoping the bashing attempt.
In the same situation than the bug report, fixing the function made the zombie bash the wall at will
=> fix bashable furnitures not bashable by monsters

data/json/recipes/other/materials.json
This will make duct tape autolearnable at level 6. It stays a level 3 craft with the same book learning options.
=> Make duct tape autolearn at Fab 6

data/json/recipes/armor/head.json
Ski masks were an odditiy, learnable at level 6 and with very few items craftable. This will make them craftable faster, but also autolearn it later, with an lower recipe level. On the plus side: it can be learned from books now.
=> Ski mask and balclava difficulty, craft time and book learning changes

src/handle_action.cpp
SUMMARY: Bugfixes "fix floor destroyed message prompt when bashing on stairs"
Fixes #1771 
To give more details, when something is bashed, the game checks if there is a "floor or support" below the player to know if it should prompt the "Floor destroyed" message.
To do that, it calls the has_floor_or_support function, that checks wether the player can go below or not. It doesn't make the difference between open air or stairs and similar terrains that allows you to go below.
Now, it also checks if the terrain has a "GOES_DOWN" flag, and won't prompt the message if it has.
I hesitated on editing has_floor_or_support, but since it's used several times in different context it could have side effects.
Create a stair, go up, spawn a furniture next to it, bash it, no more message.
=> fix floor destroyed message prompt when bashing on stairs

data/mods/Generic_Guns/ammo/replacefix.json, data/mods/Generic_Guns/firearms/pistol.json, data/mods/Generic_Guns/robots/gg_bots_migration.json
There was an error lingering, where light machine guns in cars would have sniper ammo instead of rifle ammo, this fixes the problem.
=> fixes for generic guns

src/npcmove.cpp
SUMMARY: Bugfixes "Make NPCs a bit better about remembering to aim, improve debug messages for aiming and firing a bit, add a visible warning when a player is being aimed at by an NPC"
I recently had the idea of rigging it so that hostile NPCs will print a message when aiming at you, to give the player some degree of fair warning that they're about to be shot. This is in line with turrets and robots generally audibly announcing their action beforehand.
This also should help make it easier to judge when an NPC is actually bothering to aim their shots and when they're making snapshots, which should in the future make it easier to figure out when they're actually playing by the same rules as the player. Having the player also see a non-debug message when the NPC's aiming at them will also …
=> Print a message when NPC takes aim at the player, some aim behavior/message tweaks

src/melee.cpp
NPCs (and the player) could block with broken limbs if they were wearing an item with the "BLOCK_WHILE_WORN" flag.
Fixes #1790
In the end, this fixes:
- Blocks from BLOCK_WHILE_WORN items still working when all the related limbs are broken (eg both arms for arm guards)
- Blocks not working with MA other than forced unarmed when not using a weapon
- Blocks from forced unarmed still working when both arms are broken
Details:
Some mods can add shields or unusual "BLOCK_WHILE_WORN" worn item, so I tried to take them all into account.
If a worn item covers the arms, it's either an arm guard or shield.
In that case the covered arm must be working (arm guards cover both arms, so one working arm is enough)
Otherwise If a worn item covers the legs, one of them needs to be working
Finally, if an …
=> fix NPC blocking with broken limbs

src/iexamine.cpp
SUMMARY: Bugfixes "[WIP] fix [E]xamine does not fallback to using lockpicks on locked doors when the player has no prying tool"
Fixes #282 
See title
For now the solution is to call the function used when examining a lockpickable only terrain (eg some doors).
Problem is, the part "The <thing> is locked." is repeated, so I don't find it very satisfying.
- Changing the wording enough so that the repetition wouldn't be so obvious
- Finding a clean way to pass extra information to locked_object_pickable
- None were good enough
Doors that are both pyrable and lockpickable work as intended.
Crates can't be lockpicked.
Any idea?
=> fix [E]xamine does not fallback to using lockpicks on locked doors when the player has no prying tool

src/character_display.cpp, src/newcharacter.cpp
SUMMARY: Bugfixes "Fix bonus displayed without +"
Some bonuses displayed didn't have a "+" in front of them, while some did.
Also during character creation night vision bonus had a "-". 
Every bonus gets a +
Removing the "+"
Create new character, looking at every bonus. Then same thing in the "@" menu in game.
Before
After
PS: the changing for crafting bonus, from 2d to d is intentional, to remove the space between the + and the number when there's only one number (just in case)
=> Fix bonuses displayed without +

data/changelog.txt
SUMMARY: Infrastructure "Update changelog.txt with 'Changes so far' wiki page content"
Update the text changelog for the stable release.
Copied https://github.com/cataclysmbnteam/Cataclysm-BN/wiki/Changes-so-far to the changelog. Minor reformatting.
Removing the changelog from repo and only having it online.
No need
=> Update changelog.txt with "Changes so far" wiki page content

data/mods/DinoMod/monster_factions.json
SUMMARY: Mods "[DinoMod] faction updates"
Feature parity with DDA, bugfix geese murdering massive sauropods with no counter
A ton of faction tweaks to prepare for new dinos and fix problems with monsters attacking with no counter by explicitly defining the interactions to be the same on both sides. Some tweaks to remove copy-from functionality (doesn't exist for factions in BN) and remove definitions for factions like gator that don't exist in BN.
N/A
Game loads no errors, debug spawned a goose and a brontosaurus next to each other and the goose didn't slowly murder the brontosaurus
More table setting to start moving development to BN during DDA content freeze
=> [DinoMod] faction updates

data/json/effects.json, src/monexamine.cpp, src/monexamine.h, src/monmove.cpp, src/monster.h
SUMMARY: Features "Port complete leash and lead system"
I love my cows. After the quadruped armors to protect them I needed a reliable system to move them.
Fixes #781
No but seriously I like this system and thought it would be a great addition in CBN.
Port the leash and lead system from DDA.
Now animals with the PET_WONT_FOLLOW flag won't follow you by default, but you can attach a leash to them and lead them to move them.
Go [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/50890) for the complete set of features, it's well explained.
Only difference, I increased the range at which you loose hold of the leash, which means you can safely have up to 6 animals on a leash, whereas with the DDA limitation I couldn't keep more than 2 at a time.
Also, as a side note, this avoids [this …
=> Port complete leash and lead system

data/json/monster_factions.json, data/json/monsters/nether.json
SUMMARY: Balance "Vortex monsters no longer harmless despite being aggressive, make vortices and mutants friendly"
This effectively ports over some changes to a vanilla monster from Arcana and Magic Items mod with some changes, to make one monster that is notably hostile but harmless (due to getting a special attack it used to use instead of normal attacks, long before my time it seems) actually do something.
1. Defined monster faction JSON for mutant and vortex faction, made mutually friendly as mine spirals are populate mainly by those two factions.
2. Set it so vortices actually have the ability to fight back. Gave them some basic melee damage (in line with some Arcana alterations to vanilla monsters I plan to rebalance and port over in the future), with a set amount of bonus electric …
=> Vortices can now fight back

src/magic_spell_effect.cpp
SUMMARY: Bugfixes "Trivial bugfix for bash spell effect not working against impassible terrain"
This fixes a long-running bug that @foulman reported in DDA ages ago: https://github.com/CleverRaven/Cataclysm-DDA/issues/38077 in which bash spells do absolutely nothing to solid terrain like doors, walls, or even windows.
Turns out, the code for it is immensely, hilariously easy to fix. As in, the sort of thing @KorGgenT could've fixed over 2 years ago with literally just the flip of a single boolean.
Literally just set the ignore_walls boolean in `area` defintion for `spell_effect::bash` to true.
Pestering someone else to do it.
1. Loaded in an existing release, debugged all spells plus 1000 INT, tested Artifact Pulse to confirm that windows only get yote when they're opened.
2. Compiled and …
=> Fix bash spells doing nothing to walls and windows

Makefile
SUMMARY: Build "Make Makefile build output less verbose"
it was really hard to see what is going on. now it prints object file only.
- when creating object file, only `filename.o` is shown.
- when linking, only target name is shown.
- use previous verbose output with `VERBOSE=1`
get flooded in text
|            before            |             after             |
| :--------------------------: | :---------------------------: |
| ![Cataclysm : fish_01][left] | ![Cataclysm : fish_02][right] |
[left]: https://user-images.githubusercontent.com/54838975/193814299-521e066b-c1dc-40bb-8df9-693875ba853d.png
[right]: https://user-images.githubusercontent.com/54838975/193814307-85edfd5d-f8c0-4c2e-af14-6dddece9444f.png
=> make `Makefile` less verbose

src/cata_tiles.cpp, src/cata_tiles.h
SUMMARY: Performance "Fixed some frequent reallocations when drawing map with tiles"
Improve rendering performance on slow machines by avoiding repeated reallocations
1. Persist `draw_points` vector. From testing, when zoomed out with Retrodays tileset it may grow in capacity to 16384 elements (458752 bytes on linux) and reallocate 11 times in the process over the course of single `cata_tiles::draw` call.
2. In `apply_vision_effects`, don't allocate a string each time when deciding on vision effect to apply. On default zoom with Retrodays, it may cause as many as 3000 allocations over the course of single `cata_tiles::draw` call, which even shows up in the Visual Studio profiler.
`map::apparent_light_at` takes up 34% for some reason, that's almost all of `map::update_visibility_cache` …
=> Fix some frequent reallocations when drawing map with tiles

src/monattack.cpp
SUMMARY: Balance "Wraiths don't spawn shadows when idle, DISAPPEAR special attack prevents death drops"
Some adjustments to the behavior of shadow monsters and the wraith. The main objectives are twofold:
1. Adjust for the potential problems that may be caused by six-second turns if a wraith is given free rein to spam shadows out of combat, as one every five seconds is quite a lot more if you accidentally wait in range of one, compared to what was once one every 30 seconds.
2. Added compatibility with Arcana, via allowing shadow monsters to have a more reasonable drop rate, instead of having to worry about shadows that vanish on their own being a completely free source of essence and shadow gems.
1. Moved shadow spawning part of the wraith's special attack such that it only spawns 
2. …
=> Wraith and shadow special attack updates

src/vehicle_use.cpp
SUMMARY: Bugfixes "While flying, warn when letting go of control or stop driving"
- Fixes #1924
when trying to let go of control or stop driving while flying, warn `"Really let go of controls while flying? This will result in a crash."`
- make helicopters be able to fly without controls
- automatically land
either way won't take less than two `if`s.
it works on my machine!
<details>
<summary>Letting go of Control</summary>
</details>
<details>
<summary>Stopping Engine</summary>
</details>
=> While flying, warn when letting go of control or stop driving

.gitignore
SUMMARY: Infrastructure "Add clangd cache to .gitignore files"
clangd stores cache into root directory
- add `.cache/clangd` to gitignore
[clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd
) is fast, provides useful information, and has refactoring.
=> add clangd cache to `.gitignore` files

README.md
SUMMARY: Infrastructure "Fix latest release badge not showing latest release"
fix shields.io url arguments mistake caused by #1939
changed query parameter from `semver` -> `date`
=> Fix latest release badge not showing latest release

src/cata_tiles.cpp
SUMMARY: [Bugfixes] "No more rendering monsters you can't see"
Only render seen creatures. 
Remove the bit that says only check visibility when fov_3d is on. I don't know why I added that with the draw lower z levels but I did and it was a mistake. 
Getting my brain checked.
Whoops.
=> Fixes rendering monsters you can't see when using 2d vision

src/monster.cpp
SUMMARY: Bugfixes "Prevents a dodge gain exploit using vehicle holes"
Fixes #1929. Also prevents dodge gain in the cases where the monster has no attack dice or it's attacking itself but I don't think those matter. 
Moves the dodge roll until after the conditions have been checked. 
We could look into the rest of the AI so it doesn't waste moves trying to do things like this in the first place, but that's a wider issue.
=> Prevents dodge gain exploit

src/grab.cpp
SUMMARY: Bugfixes "Allows pushing vehicles over ramps"
Fixes #1978. 
The problem was that when you went over the ramp and your grab point moved in the z direction, some of the grab code would factor that in and end up having the collision calculated for the opposite direction, causing you to bump into the ground. The code that adjusts the z value has been moved until after the grab's calculations. 
You could also just set z to 0 after doing grab's calculations, it's all much the same. 
You still have to do the awkward push it up and then go up yourself and grab it again, but I think that's the same as before.
=> Allows pushing vehicles over ramps

data/json/items/armor/undergarment.json
SUMMARY: Balance "Add repairs_like to another couple items that lacked it"
Easy fixes for a couple items I sifted through and found were both uncraftable, reasonable similar to craftable items, yet lacked `repairs_like` definitions.
1. Added `repairs_like` to camisole, using jeans as most shirt, pants, and skirt items that use repairs_like target jeans.
2. Added `repairs_like` to leather corset. I targeted leather jacket instead of leather vest (its `looks_like`) target because the default no-suffix recipe for leather vest is the level-zero recipe for cutting sleeves off of a leather jacket, instead of the recipe to actually make the vest from scratch.
Making more random flavor clothing items craftable for the hell of it.
=> Added repairs_like to a couple other items

.clang-tidy, .editorconfig, doc/MODDING.md
SUMMARY: Infrastructure "Format .clang-tidy and append .editorconfig"
- `.editorconfig` does not have config for markdown and yaml where indent 2 is used
- `.clang-tidy`'s file extension is `yaml` yet it's not formatted properly
- add configs for `.editorconfig`
- format `.clang-tidy`
- disabled `readability-identifier-length` because almost every file uses variables with 1~2 length and it's clogging error messages
=> Format configs

data/json/overmap/overmap_special/specials.json, data/mods/Aftershock/maps/overmap_specials.json, data/mods/DinoMod/overmap/overmap_specials.json, data/mods/Magiclysm/worldgen/overmap_specials.json
SUMMARY: Content "Added electric grid flag to saw mills, relevant mod locations"
This started as just something someone requested over on the BN discord, as it came up that with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1866 being merged we can probably justify adding the `ELECTRIC_GRID` flag to at least a couple more locations we would've avoided earlier, and then roll them back in favor of partial grid coverage once we have support for junction boxes.
This quickly got derailed by me realizing we oughta check mods for any overmap specials obviously in need of the grid flag too, as presently it looks like only No Hope has gotten to make use of it so far.
Added `ELCTRIC_GRID` flag to lumber mills, per request. Normally I'd avoid doing this since it does have a decent chunk of …
=> Add grid flag to more specials, mods in particular

src/game.cpp
SUMMARY: Bugfixes "Prevent duplicates in the item view when 3d vision is on"
No more duplicates.
Better math on the iteration over z levels, it was doing 0 twice.
=> Fix duplicates in item view

data/json/mutations/mutations.json, src/consumption.cpp
Add ablitlity to Gourmand to overeat without bloating 
Fixes #790
Adjust behaviour to work more in line with description. 
Added check for gourmand in place where bloated effect is added
Modifying maximum stored calories for gourmand. 
Changing description of gourmand to be consistent with how it works. 
Leaving as it is. 
Adding check so gourmand will get bloated only if all of calories/quench are excess calories. 
Checked how gourmand works
It's behaving now how I remember when I played DDA
=> Allow gourmand overeating. 

src/melee.cpp
SUMMARY: Balance "Change impact of melee skill on melee stamina cost to be proportionate, consistent with effect on movecost"
So one thing I noticed while poking through the code is that the stamina cost of melee attacks has a pretty bad flaw in it: it gives you a bonus for melee skill, but the bonus is so pathetically small that it basically does not matter.
It takes your melee skill out...directly. So a maximum of 10 stamina taken out of the stamina cost. In contrast, every 16 grams tacks on a point of stamina, so 1 kilogram of weapon has a base cost of 62.5 stamina. On top of that, every point of arm encumbrance (that is, per invividual arm) tacks on 2 more stamina cost.
In contrast, melee has a much more dramatic impact on movecost calculation:
```
const int skill_cost = …
```
=> Melee skill actually impacts attack stamina usage

data/mods/Graphical_Overmap/modinfo.json, data/mods/Graphical_Overmap_FujiStruct/modinfo.json, data/mods/Graphical_Overmap_More_Locations/modinfo.json, data/mods/Graphical_Overmap_Urban_Development/modinfo.json
SUMMARY: Mods "Obsolete Graphical Overmap mod, rename to Larwick's Overmap"
When people see nice screenshots of the graphical overmap with UDP, they frequently assume it's the "Graphical Overmap" mod they see in the new world menu. Furthermore, not all people see "please refer to readme" note that describes additional installation steps required in order for the mod to work.
Get rid of the footgun by obsoleting the mod and giving it a somewhat obscure name. There were no actual changes done to its content or id, so existing saves will work as is.
Tried starting a new world, the mod is not there. Can still be activated after pressing `o` (`Toggle showing [o]bsolete mods`).
=> Obsolete Graphical Overmap mod, rename to Larwick's Overmap

data/json/player_activities.json, src/activity_actor.cpp, src/activity_actor_definitions.h, src/game.cpp, src/game.h, src/gates.cpp, src/gates.h, src/iexamine.cpp
SUMMARY: Bugfixes "Fix mechanical gates randomly failing to close"
- `gates::open_gate` fails because `forced_door_closing` returns `false`
- `forced_door_closing` randomly fails because it checks room for pushback regardless of whether there's item/monster
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/6b7f879b6e6247d628d4ba2ae4680d8d86d770d8/src/game.cpp#L5117-L5121
- 1724e0b7ccf051646cbc286e9bf2091dbefa0f17, 1724e0b7ccf051646cbc286e9bf2091dbefa0f17: lazy evaluate pushback check until `pushback()` and item moving is actually done
- 88c3ab07fb54c2db4dcda08b3a2c65285f5b1dfa: renamed `open_gate` and releated function name to `toggle_gate`
- 70708db39bb4d2a6150fba1641c49eeb5529ce5d, 29e5683b3d4120edab58786eeb2e0cafae1bdef8: removed duplicate points
=> Fix gate failing randomly

data/json/martialarts.json, data/json/techniques.json
Balance "Rebalance barbaran montante MA"
Barbaran montante was too powerful at low STR level, because you could reach 300% armor penetration, scaling with strength.
The description was also changed a bit to better reflect historical accuracy. (thanks krwak)
The impaling technique was also a bit useless (10% damage bonus, applied before armor reduction, which usually makes close to no difference).
After a very long discussion, we agreed on a different value: 200% total armor penetration (arpen).
The static bonus is changed from 75% arpen to 100%.
The onpause bonus is changed from 225% arpen to 125%.
Also, the impalade technique is changed from +10% damage to +30% damage.
A gazillon, but at some point we need to choose.
Tested with 6 skills in everything, except dodge which I increased or …
=> [FIX] rebalance barbaran montante MA

src/vehicle.cpp, src/vehicle_use.cpp
SUMMARY: Interface "Prettier fuel selection menu"
- engine entries have lots of duplicate names, so thought it'd be better to only print unique ones
- also make them look pretty
now even prettier with same ui as aiming menu
=> Prettier fuel selection menu

src/fungal_effects.cpp
SUMMARY: Bugfixes "Fix burnt mycus ground burning road"
Fixes #1882 but it pushes the change further.
Mycus spread was always kind of a nightmare. It made entire zones a no go, adding a ton of lag etc.
Well I won't detail this part, you know what I mean. A lot of people just use a mod to remove it, so in the end, is this a fun feature?
With this change they can still be a pain, but only on terrains like dirt, grass, trees etc.
So they will now mostly take over part of the wild.
Allowing it to convert wood.
I think it makes sense, but would require some changes to wood terrains.
After 2 hours wait this is the conversion result:
From top to bottom
- 1st row: dirt, grass etc. -> converted
- 2nd row: tree, bushes etc. -> converted
- 3rd row: wood stuff -> not converted
- 4th row: metal, …
=> Fix burnt mycus ground burning road

src/activity_actor.cpp, src/activity_actor_definitions.h
SUMMARY: Bugfixes "Forbid firing bow when out of stamina, consume stamina after firing"
Fix couple bugs:
1. Entering aiming menu with a bow and immediately closing it without doing anything consumes stamina
2. Starting to aim with a bow when low on stamina would trigger "catching breath" activity, which is frequently not desired when in the heat of a battle
3. It's possible to draw a bow when out of stamina, making it essentially free in that case
4. If "catching breath" activity is interrupted, the bow is never unloaded and keeps its arrow
Move stamina consumption to fire action (after aiming), forbid aiming if not enough stamina to fire.
Removing stamina consumption from `do_turn()` makes it so stamina stays the same during activity and `ACT_WAIT_STAMINA` isn't triggered.
Refactoring …
=> Forbid firing bow when out of stamina, consume stamina after firing

msvc-full-features/Cataclysm-lib-vcpkg-static.vcxproj, msvc-full-features/Cataclysm-test-vcpkg-static.vcxproj, msvc-full-features/JsonFormatter-vcpkg-static.vcxproj, msvc-full-features/prebuild.cmd
SUMMARY: Build "Tweak msvc version generation script to reduce recompilations"
Reduce recompilations caused by `prebuild.cmd` updating timestamp on `version.h` on each build.
Port https://github.com/CleverRaven/Cataclysm-DDA/pull/60754 and a single commit from https://github.com/CleverRaven/Cataclysm-DDA/pull/56875
Editing tests' cpps and rebuilding no longer causes the lib to rebuild.
=> [DDA Port] Tweak msvc version generation script to reduce recompilations

.github/workflows/pull-translations.yml, .github/workflows/push-translation-template.yml, .tx/config
SUMMARY: Infrastructure "Misc improvements to GA Transifex workflows"
1. Don't pull translations on forks
2. Migrate to new Transifex cli (python client is deprecated and will stop working on Nov 30, 2022)
3. Optimize start conditions, reduce run time
Source DDA PRs:
https://github.com/CleverRaven/Cataclysm-DDA/pull/54645
https://github.com/CleverRaven/Cataclysm-DDA/pull/52219
https://github.com/CleverRaven/Cataclysm-DDA/pull/54644
https://github.com/CleverRaven/Cataclysm-DDA/pull/54892
https://github.com/CleverRaven/Cataclysm-DDA/pull/55126
https://github.com/CleverRaven/Cataclysm-DDA/pull/55150
https://github.com/CleverRaven/Cataclysm-DDA/pull/55530
https://github.com/CleverRaven/Cataclysm-DDA/pull/55193
Can't really test outside merging into `upload`
=> [DDA Port] Misc improvements to GA Transifex workflows

src/cached_options.cpp, src/cached_options.h, src/descriptions.cpp, src/item.cpp, src/monster.cpp, src/options.cpp
SUMMARY: Interface "Adds Display Mod Source to the debug tab in settings."
Follows up on #1875 Coolthulhu asked that I make it into a setting, which makes sense since just today I forgot about it's existence while helping someone debug their game.
Display Mod Source has been added to the debug tab of settings. It is on by default so people know it exists, but is toggleable if players think it is too intrusive.
... Ignore?
Started game with Aftershock, checked that items properly attributed and UPS displayed that it is from BN and altered by Aftershock. Turned off the setting and checked that it didn't display anymore.
I removed the empty line between skill rust and skill gain debug options since they honestly feel like they should be in the same "block" so to speak. If this is not desired …
=> Adds Display Mod Source as an option instead of tying to Debug Mode

src/map.cpp, src/map.h
SUMMARY: Bugfixes "Fixes labs missing roofs"
The recent changes I made to roof generation included an optimization that only newly generated tiles were roofed. This didn't play nice with special mapgen like labs. Depending on how they were loaded in it could miss that some of the tiles were new.
It now roofs newly loaded tiles, regardless of if they're newly generated.
Fixing working out which tiles were newly generated but I don't want to make it too complex and this way it also fixes any old saves that have roofs missing. 
Labs now get a roof no matter which direction you come from, or if you teleport into them.
=> Fixes labs missing roofs

tests/npc_test.cpp, tests/rng_test.cpp, tests/state_helpers.cpp
SUMMARY: Infrastructure "Fix test isolation failures and some broken tests"
The name generation tests were a source of isolation failures when npcs were created. If the name generation test had been ran beforehand it would iterate the rng differently when coming up with a name. 
There's also some fixes for specific problem tests. The tests for the rng distribution have been disabled. They're just not really suitable for a suite. They will fail some seeds that have outlier distributions and using a fixed seed or expanding the bounds defeats the point. They're something to run a bunch of times if you change the rng rather than as part of the normal suite. 
One of the NPC tests involving putting them in a reinforced glass box full of acid had the problem that some seeds would spawn an NPC …
=> Adds loaded names to the cleared state and fixes some buggy tests

src/debug.cpp, src/debug.h, src/debug_menu.cpp, src/game.cpp, src/game.h, src/wish.cpp
SUMMARY: Features "The debug menu can look across z levels and reset ignored messages"
The various tile selection things in the debug menu no longer respect the 3d vision settings. They always let you select any z level. There's also an additional option under the info menu that clears the list of ignored debug messages. 
look_around has gained a bool to force the full 3d range and there's a new menu option that clears the ignored list.
None really.
I checked looking around with fov_3d and z levels on and off and resetting works on the message you can generate in the debug menu.
=> Debug menu can look across z levels and reset ignored messages

src/vpart_position.h
SUMMARY: Bugfixes "add GCC unreachability intrinstic on false branch of assert"
```c++
/home/scarf/repo/cata/Cataclysm/src/vpart_position.h:52:20: error: ‘*(const vpart_position*)((char*)&<unnamed> + offsetof(vehicle_part_iterator<vehicle_part_range>,vehicle_part_iterator<vehicle_part_range>::vp_.cata::optional<vpart_reference>::<unnamed>)).vpart_position::part_index_’ may be used uninitialized [-Werror=maybe-uninitialized]
52 |             return part_index_;
|                    ^~~~~~~~~~~
```
- fix maybe-uninitialized compilation error
- fix from https://github.com/CleverRaven/Cataclysm-DDA/pull/58210
- redefine `assert` to use `__builtin_unreachable()` on GCC
- only applied on vpart_range.h since BN does not have cata_assert.h
- cherry-pick `cata_assert.h`
Compiles on GCC
=> add GCC unreachability intrinstic on false branch of assert

src/bionics.cpp, src/suffer.cpp
SUMMARY: Bugfixes "Fix some suffer and bionic messages acting like the player is receiving effects applied to NPCs"
Was reminded recently that there's a good chunk of messages in the code that tell the player something is happening to them when it's actually happening to an NPC instead.
* Fixed Narcolepsy message to use `add_msg_player_or_npc` so that the player will be alerted if an NPC passes out due to it, instead of printing the same message as if the player passes out.
* Fixed some nonsensical Psychosis messages to use `add_msg_if_player` so NPCs with Psychosis won't secretly gaslight the player.
* Fixed some faulty bionic effects triggering as `add_msg` incorrectly, plus in one case converted a use of `add_msg_if_player` with `add_msg_player_or_npc` since it has effects the player …
=> Fix messages involving NPC suffering

src/pathfinding.cpp
SUMMARY: Bugfixes "Fixes a bug where pathfinding could go through vehicle holes"
In some cases vehicles holes wouldn't be checked properly when building a path. 
Moves checking holes to an earlier point in the check of the tile, so it's done regardless of the tile's properties. 
The easiest way to trigger this is to let an npc melee something through a hole. So long as the tile that's targeted doesn't have any movement affecting properties it'll be allowed.
=> Fixes a bug where pathfinding could go through vehicle holes

.github/workflows/manual-release.yml, .github/workflows/msvc-full-features.yml, .github/workflows/release.yml, msvc-full-features/vcpkg.json
SUMMARY: Build "Bumped vcpkg version to fix msvc builds"
Closes #2082
Bump vcpkg version to latest-ish. It includes the change to zlib port file that makes it download the source code for version 1.2.12 from github mirror where it's still available.
It's a trivial change, yet should last us for another half a year or so if the trend continues.
Compiles locally, no game-breaking issues were noticed.
Opened the PR to test GitHub workflow, should work with no further changes.
People with existing VS+vcpkg build setups will need to manually update their vcpkg.
Assuming the setup matches one described in the doc, this can be done in 2 steps:
1. Open vcpkg folder in cmd and run:
```
git pull --ff origin master
```
2. Open the solution in Visual Studio and do a "Clean Solution" + "Build …
=> Bump vcpkg version to fix msvc builds

src/debug_menu.cpp, src/map.cpp
SUMMARY: I18N "Added positional arguments to a few strings"
Fixing i18n updates warnings
```
Checking ko.po => 3 error(s) detected:
original  :Refreshed %d times in %.3f seconds.  (%.3f fps average)
translated:%.3f 초 동안 %d번 새로고침 (평균 %.3f fps)
original  :Drew %d times in %.3f seconds.  (%.3f per second average)
translated:%.3f초 동안 %d번 그림 (평균 초당 %.3f회)
original  :It should take %d minutes to finish washing items in the %s.
translated:%s의 내용물을 세탁하는데 %d분 걸립니다.
Checking pl_PL.po => 1 error(s) detected:
original  :It should take %d minutes to finish washing items in the %s.
translated:Wypranie rzeczy w %s powinno zająć %d minut.
```
Add positional arguments.
Transifex erroneously shows positions for arguments that don't have them, and silently accepts malformed translations, which results in …
=> Add positional arguments to a few strings

.github/workflows/pull-translations.yml
SUMMARY: None
The workflow is failing because I forgot to include this change in #2007
Port of DDA's https://github.com/CleverRaven/Cataclysm-DDA/pull/55342
None
=> [DDA Port] Follow HTTP 302 redirection in installing Transifex CLI for pull-translations.yml

data/json/npcs/holdouts/Mr_Lapin.json
SUMMARY: Balance "give two pet packs for Mr. Lapin's second mission"
- resolved #2068
gives two pet packs for Mr. Lapin's second mission.
reasoning: as in #2068, since first mission gives you two cattle fodder to befriend two rabbits. less trip is good.
=> give two pet packs for Mr. Lapin's second mission

src/game.cpp, src/options.cpp
SUMMARY: Interface "Add option to ignore dangerous terrain warnings"
- resolves #402
- adds an option `Ignore`, which will disable all dangerous terrain check/prompts. live on the edge!
=> Add option to ignore dangerous terrain warnings

src/explosion.cpp
SUMMARY: Bugfixes "Add shrapnel animation"
Fixes #2094 
Shrapnel had no animation, which lead to 2 problems:
1. It was hard to know wether one would be inside the shrapnel radius or not, when the radius is well defined in BN
2. Explosions that only used shrapnel had no animations (at all)
After some exchanges on Discord:
- reuse the code that draws the new explosions, without the damage, part to draw the shrapnel animation
- draw only 1/2 rings to give it a faster visual and reduce the animation time (eg now grenades have 2 explosions animations)
- use the visual of smoke instead of explosion
This solution didn't get accepted (without extra changes), but I'll leave it here in case it inspires someone in the future:
<details>
<summary>details</summary>
Every explosions that use shrapnel …
=> Add shrapnel animation

data/mods/Magiclysm/worldgen/black_dragon_lair.json
SUMMARY: Bugfixes "add enchanted rings back to dragon's lair loot"
Due to some unknown changes, the dragon's lair didn't use his "treasury" item group for the final room.
It used the item group for the random objects in the lair, before the "treasury" final room.
Since the enchanted rings are in the treasury item group, they never spawned in the lair.
Fix this problem by using the item group for the treasury.
This is also on par with the current DDA version, but I couldn't find the commit that resolved that, only the commit that introduced the bug.
- for testing, you might want to increase the probability that a ring appears, because it seems quite low.
- then reveal the map, go one tile below ground 0 and search for white "%" signes
- teleport here and verify that at least one ring …
=> [Magiclysm] add enchanted rings back to dragon's lair loot

src/ballistics.cpp, src/bionics.cpp, src/character.cpp, src/computer_session.cpp, src/explosion.cpp, src/explosion.h, src/explosion_queue.h, src/game.cpp, src/game.h, src/handle_action.cpp, src/item.cpp, src/item.h, src/itype.cpp, src/iuse.cpp, src/iuse_actor.cpp, src/iuse_actor.h, src/magic.h, src/magic_spell_effect.cpp, src/map.cpp, src/mondeath.cpp, src/monster.cpp, src/player.cpp, src/player.h, src/projectile.cpp, src/projectile.h, src/trapfunc.cpp, src/vehicle.cpp, src/vehicle_move.cpp
Explosion kills from player (grenades, launchers...) were not added to his kills list, probably due to the difficulty to know who's responsible for the explosion (it was a TODO somewhere).
Since explosions kills would be added to kills list, it seemed logical to add the player to his kills list if he killed himself.
Note that direct hit that killed a creature (from a grenade or launcher) already counted, but the explosion after the hit didn't.
**Non technical:**
Kills from player with:
- explosive throwing items (eg grenades)
- launchers
- explosions from spells
- the shockwave generator bionic
- explosions from computers and such that can only be triggered by a player
are now added to his kill count list
If the player kill himself through damages triggered/caused by himself (including …
=> Add missing damage sources kills and suicide to kills list

tests/test_main.cpp
SUMMARY: Infrastructure "Removes overmap generation from testing startup"
During test suite initialization create_custom_overmap is called. This isn't needed and can cause debug messages on some seeds. 
Delete.
=> Removes overmap generation from test startup

src/options.cpp, src/sdlsound.cpp, src/sdlsound.h
SUMMARY: Bugfixes "Fix ambient volume not updating after options change"
Fix #2019
Ambient effect volume is not updated after changing it through the options in game.
The volume will only be updated after you move to an other area.
Which can be annoying if you want to test the if you like an ambient sound, to adjust the volume etc.
I first tried to update the volume of the current ambient effect after options change in game (same behavior as music).
But several channels (ambient sounds), can be played simultaneously.
So I now:
- save the last played channel with its options each time a new channel is started
- and on options change
- stop all channels
- start the last played channel with its options and the updated volume
I could keep track of every channel parameters to restart every …
=> Fix ambient sound not updating in game on setting options change

.github/labeler.yml, .github/workflows/label.yml
SUMMARY: Infrastructure "Label new PRs automatically"
It's often hard to see how much impact a PR would make. adding a corresponding label helps identifying each PRs and prioritizing them.
added [labeler](https://github.com/actions/labeler) that labels PRs matching these categories automatically: 
- src/
- tests/
- data/
- data/mods
- lang/
made corresponding labels to be added:
more labels could be added as well (such as `repo`, `lang`, `graphic`, etc)
=> Label PRs automatically

src/game_inventory.cpp, src/inventory_ui.cpp, src/inventory_ui.h
SUMMARY: Interface "Add favorite action in multidrop menu"
Typical case:
- Back at your base you want to drop your loot, so you press "D" (or "d")
- But you notice a few items you want to keep, so you want to mark those items as favorite before using "," to drop all non favorite items
- And you can't, because it's not implemented, so you have to go back to the inventory menu, loosing your potential selection
- Add the ability to mark items as favorite from the multidrop menu
- I tried every edge cases I could think off
=> Add the ability to mark items as favorite from the multidrop menu

src/mattack_actors.cpp
Co-Authored-By: I-am-Erk <45136638+I-am-Erk@users.noreply.github.com>
SUMMARY: Bugfixes "Port over minor code fix to monster spellcasting"
@thelonestander was asking me about a code fix needed for his implementation of flesh raptors in a mod for BN, to fix an issue where monsters casting summoning spells would always magic them right next to the player.
Ported over update from DDA fixing `mon_spellcasting_actor::call` in mattack_actors.cpp, to be able to cite the position of themselves as well from what I understand of the change.
1. Pestering Lone to do it when he finally escapes Florida and can return to making PRs.
2. Also porting over flesh rapters, dunno how well it'd work nor what niche it'd really fit other than "generic pest creator"
2. Temporarily …
=> Port over fix for spellcasting monsters and summon spells

data/json/monsters/nether.json
SUMMARY: Balance "Shadow and related nether monsters favor cold theming over electric, other overrides ported from Arcana"
This effectively ports over some of the last remaining changes to vanilla monsters from Arcana, except for stuff specific to the mod like the death drop overrides. This is mainly to further flesh out and make certain monster interactions a bit weirder without having to keep them in a mod override.
1. Ported over the concept of shadow monsters (for now just shadows, shadow snakes, and wraiths) dealing cold-type damage, with a corresponding adjustment of their base melee damage. also have those values standardized a bit more compared to how they are in Arcana. Part of the goal for the damage results (as seen below) was to make their approximate average damage progress …
=> Shadow and cult creature updates from Arcana

src/cata_unreachable.h, src/lightmap.cpp
SUMMARY: Build "Fix false positive no return warnings in msvc"
Fix warnings in `lightmap.cpp`:
```
src\lightmap.cpp(1148): warning C4715: '<lambda_5114cbcce979430cdc53a0f312cda1c1>::operator()': not all control paths return a value
src\lightmap.cpp(849): warning C4715: '<lambda_97faf4a5c59a05aa0c0ff99c9f164228>::operator()': not all control paths return a value
```
Add a platform-independent `unreachable()` hint found at Stackoverflow (https://stackoverflow.com/a/65258501)
c++23
Game compiles with no warnings in VS, does not crash and burn when loading a save.
=> Fix false positive no return warnings in msvc

data/json/itemgroups/tools.json
SUMMARY: Balance "Set used_UPS to have 0-100% charge as comment states, instead of identical to charged_UPS"
Another thing I forgot in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1109, there's a distinction between used UPS and nearly-fully-charged UPS in itemgroups, but they were both set to have the exact same range of charges.
Set `used_UPS` to actually vary between 0 and 100% charge.
Setting it to a minimum of 20% instead and updating comment accordingly.
Tested affected file for syntax and lint errors.
=> used_UPS and charged_UPS itemgroups now differ

src/savegame_json.cpp
SUMMARY: Bugfixes "Fix `overmap_debug_mongroup` debugmsg on save+load"
One of the recent PRs added a field, a line to save it, but no line to read it. This caused a debugmsg on load. This PR adds the line to read the field.
As above.
Don't save the field.
1. Save
2. Load the just saved game
3. No debugmsg
=> Fix `overmap_debug_mongroup` debugmsg on save+load

src/submap.cpp
SUMMARY: Bugfixes "Fix vehicles being incorrectly rotated when spawning"
Fixes #2107. 
This is something I broke when changing ramps. The rotation wasn't taking into account the vehicle's current facing. 
I generated a dairy farm house at a bunch of rotations. The truck outside was oriented correctly.
=> Fix submap rotation rotating vehicles

src/vehicle_move.cpp, tests/vehicle_rails_test.cpp
SUMMARY: Bugfixes "Fix edge case in movement over diagonal rails"
Fix a bug with rail movement discovered during development.
"Shifting" movement (see #1634) on diagonal rails didn't work properly at some rotations when shifting right.
Fix vector math, add tests. Also add tests for shifting left on straight rails to ensure correctness.
Automated tests, also tested on practice in an in-progress dev branch.
=> Fix edge case in movement over diagonal rails

src/vehicle_autodrive.cpp, src/worldfactory.cpp, tests/colony_test.cpp
SUMMARY: Build "Remove some unused variables"
Newer versions of clang will throw warnings regarding some set but unused variables.
Get rid of the unused variables.
=> Removed unused variables

src/lightmap.cpp, src/lightmap.h, src/map.cpp, src/map.h, src/point.h
SUMMARY: Bugfixes "Crouching next to a vehicle hole limits visibility appropriately"
Fixes the bug where you could see through vehicle holes between transparent parts even when crouching should have rendered them opaque and changes coverage for vehicle parts so that protrusions don't provide cover and so don't affect crouching vision (same as aisles don't currently). It also incidentally fixes an almost unnoticeable issue that until you actually look at a z level, it will still be using uninitialized all solid transparency. 
This hauls out the old crouching visibility system, which was a separate transparency cache per z level for the player. Every turn the level that you're looking at would be copied from the main cache and maybe have the 9 tiles around the player altered. It wasn't used …
=> Crouching beside vehicle holes

data/json/construction_category.json, data/raw/keybindings.json, src/construction.cpp, src/savegame_json.cpp, src/uistate.h
SUMMARY: Interface "Allow marking construction recipes as favorite, sort recipes by name in construction UI"
- Allow marking construction recipes as favorite
QoL feature, useful for highlighting some of the common recipes like furniture disassembly or cleaning window from shards
- Sort recipes by name in construction UI
To make skimming the list not painful with languages where "build" can be translated differently depending on context
- Add separate construction category for favorites, add a keybind to toggle favorite, store favorite list in `uistate`
- Use `localized_compare` to sort by translated name according to user locale
Added and removed some recipes to/from favorites, saved & loaded to ensure they keep their favorite status.
Switched to Russian and ensured the construction order …
=> Allow marking construction recipes as favorite, sort recipes by name in construction UI

data/json/furniture_and_terrain/furniture-storage.json, data/json/furniture_and_terrain/terrain-zlevel-transitions.json, src/iexamine.cpp, src/iuse_actor.cpp
SUMMARY: Bugfixes "Fix several prying/picking tools bugs"
Fixes #2130 
- manholes and coffins were missing a json field
- when checking for the best items with lockpick/prying qualities, wearable items weren't taken into account
Fixes #1923 
- basically what is in the issue, the parameter was passed to the function but never used
- add the missing json field so that they can be pried open with examine
- remove the check on wearable item
- you can directly lockpick a lockpickable thing with a worn hairpin
- you can also pry a pryable thing with crowbar in a toolbelt
- make the function ask for a direction only if the parameter passed isn't valid
- worn item: hairpin (action and examine key)
- sealed coffin: no
- crate: no
- man hole: no
- locked wood door: yes
- gun safe: yes
- worn item: …
=> Fix several prying/picking tools bugs

data/json/npcs/TALK_COMMON_ALLY.json, data/json/npcs/talk_tags.json, tests/npc_talk_test.cpp
SUMMARY: Content "Add some more NPC talk tags, allow backing out of aim preference menu, fix some dialogue oddities"
This fixes some issues with NPC talk tags and some annoyances in the companion setting menu, allong with adding some additional lines to areas that could use more variety.
1. Fixed some NPC rule talk tags using * instead of the actual NPC pronoun.
2. Fixed response for toggling NPC follow distance quoting the opposing talk tag instead of actually being a command.
3. Added "never mind" as a response to the aim setting menu, fixing the aim setting menu forcing you to change the setting instead of letting you leave it the way it is.
4. Added an assortment of additional talk tags for some that were lacking in variety.
More memes and references in talk tag snippets.
1. Checked …
=> Expand NPC talk tags, dialogue fixes

src/avatar_action.cpp
SUMMARY: [Category] "Fix deactivate robot message spam"
When you move on the same tile as a friendly robot, you automatically get a message to deactivate it.
This makes having several robots following you a real pain.
If you want to deactivate a robot, you can just use "Examine".
Remove the prompt.
Now you just swap positions with it, like you do with pets. 
If you want to deactivate it, you can use "Examine".
- spawn manhacks
- move in them, no more prompt!
- use "Examine", you can deactivate them that way
=> Fix deactivate friendly robots message spam when moving on same tile

pch/main-pch.hpp, src/diary.cpp
SUMMARY: Bugfixes "Loop element hotfix"
fix build error, failed to build because each element was being copied
```c++
1 | Error: /home/runner/work/Cataclysm-BN/Cataclysm-BN/src/diary.cpp:751:25: error: loop variable ‘folded_text_char’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Werror=range-loop-construct]
-- | --
2 | 751 \|         for( const auto folded_text_char : folded_text ) {
3 | \|                         ^~~~~~~~~~~~~~~~
4 | /home/runner/work/Cataclysm-BN/Cataclysm-BN/src/diary.cpp:751:25: note: use reference type to prevent copying
5 | 751 \|         for( const auto folded_text_char : folded_text ) {
6 | \|                         ^~~~~~~~~~~~~~~~
7 | \|                         &
```
use [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_s …
=> Loop element hotfix

src/string_editor_window.cpp
SUMMARY: Bugfixes "Fix android build StopTextInput error"
(Should) fix #2158 
Use SDL_StopTextInput() instead of StopTextInput().
SDL_StopTextInput() being a wrapper that we didn't port yet from DDA.
I can't test it (I can't build the Android version locally).
But, since it uses a known function instead and that was already what was used in precedent versions of DDA.
Worse case scenario, the diary is buggy on Android.
Best case scenario, everything works perfectly.
In both cases, the Android build won't be broken anymore, so people will be able to download the experimental again.
=> Fix android build StopTextInput error

src/game.cpp, src/item.cpp, src/iuse_actor.cpp, src/magic_spell_effect.cpp, src/monexamine.cpp, src/npctalk.cpp, src/projectile.cpp, src/ranged.cpp, src/suffer.cpp
SUMMARY: Infrastructure "Clean up some uses of the old globals"
Gets rid of a bunch of uses of g->m and g->u replacing them with the function alternatives. 
Just elbow grease. With the idea that we want to bind the values to a local variable most of the time automating it isn't so easy. There's still plenty to go, even some the files touched here aren't totally finished. 
Doing the rest of them right now or waiting with the PR until they're done, but I think I want to spread it out a bit and this way means less conflicts and it's good that as much of our code as possible is a template for what new code should look like. 
They're all nothing changes. It's a pretty mechanical process and if it compiles it's hard to mess anything up. The only caveat to that is being careful when choosing …
=> Globals cleanup

src/savegame_json.cpp
SUMMARY: Bugfixes "Remove overmap_debug_mongroup"
While porting #2089 I accidentally included this into `savegame_json.cpp` under write but not read. It's a variable used in DDA but not in BN that I accidentally included while solving merge conflicts.
Removes `overmap_debug_mongroup` from `savegame_json.cpp` entirely.
- Add in whatever it's supposed to reference.
I actually have no clue what it actually does and looking for it might take a while. I'd rather do that some other time, especially if it turns out that it's not something we even want.
Save load, then turn on "Report Unused JSON Fields", verified that the error no longer triggered.
I really need to set "Report Unused JSON Fields" as true for all my test builds.
=> Remove overmap_debug_mongroup

src/mondeath.cpp
SUMMARY: Bugfixes "Fix explosions delayed on special monster death effects"
Fixes #2189
The problem is linked to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2092 , on top of the fact that explosions from monster deaths are delayed by one turn, when they should happen instantly.
A quick explanation:
PR 2092 added the tracking of the source of an explosion (the caster of the spell, the thrower of a grenade, a monster that triggers a special attacks etc.).
This allowed kills from explosives to be added to the player's list.
Before that, explosions were supposed to have no origin/source.
Problem: explosions from monsters death are **assumed** to happen instantly, not 1 turn after.
Trigger the explosion just after a monster death, for monsters with on_death effects:
- "EXPLODE" (eg …
=> Fix explosions delayed on special monster death effects

src/editmap.cpp, src/game.cpp, src/game_constants.h, src/options.cpp, src/overmap_ui.cpp
SUMMARY: "Interface" Reduce blinking effects speed from 300 to 800ms, and add an option for change in game
Blinking effects speed was 300ms, and could make people sensitive to high blink speed uneasy (most notably on the map).
Change the blinking effects speed from 300 to 800ms.
Add an option to change it in game, since we all have our own idea of the ideal blinking effects speed.
Set the blink speed to the old 300ms
https://user-images.githubusercontent.com/71428793/200147650-3d3bb6f3-6170-4208-bcec-c6df94bf3487.mp4
Change the blinking effects speed from 300 to 800ms
https://user-images.githubusercontent.com/71428793/200147583-c29c37d9-149e-4a66-ab84-e6779a53b231.mp4
=> Reduce blinking effects speed (300 -> 800ms), and add an option to change it in game

data/json/vehicleparts/boards.json, data/json/vehicleparts/cargo.json, data/json/vehicleparts/combustion.json, data/json/vehicleparts/doors.json, data/json/vehicleparts/engineering.json, data/json/vehicleparts/frames.json, data/json/vehicleparts/lights.json, data/json/vehicleparts/manual.json, data/json/vehicleparts/seats.json, data/json/vehicleparts/tanks.json, data/json/vehicleparts/vehicle_parts.json, data/json/vehicleparts/wheel.json
SUMMARY: Balance "Allow installing or removing a wider range of lighter vehicle parts with level 1 tool qualties"
This seeks to add a wider variation to the tool usage for installing and removing parts on a vehicle, with the added goal of making it possible to potentially get sheet metal and the occasional frame out of vehicles with level 1 tool qualities.
1. Boards, quarterpanels, and roofs that return sheet metal or pipes set to allow level 1 metal sawing to remove instead of level 2. Level 2 quality stays for heavier panels and the like.
2. Wire baskets set to allow level 1 sawing to remove instead of level 2, except for lighter baskets that already used just screwdriving quality.
3. 1-cylinder scooter engines set to allow level 1 bolt turning to install and remove instead of level 2. …
=> Allow easier installing/removing of some parts

data/json/items/armor/cloaks.json, src/itype.h
SUMMARY: Bugfixes "`maximum_charges()` now defaults to 0. Optical Cloak changed to TOOL_ARMOR category"
Players reported an issue where ups conversion mods carried with an active UPS or other similar item would be charged, causing an error report on load since the item isn't supposed to carry charges.
Also noticed that while doing #1505 I'd neglected to make the base version of the optical cloak TOOL_ARMOR, which contributed to the same issue.
The base optical cloak is now TOOL_ARMOR, which should prevent edge cases of it gaining charges through battery mods or other arcane methods from causing errors.
`maximum_charges()` was updated such that it defaults to 0 if the item is not a tool, this is consistent with `itype::can_have_charges()` which assumes that any non-tool, non-gunmod, …
=> `maximum_charges()` now defaults to 0. Optical Cloak changed to TOOL_ARMOR category

src/inventory_ui.cpp
SUMMARY: Bugfixes "Fix rare crash when unfavoriting an item twice"
A crash could be triggered when doing a specific chain of action, eg:
- have some rocks on you
- have some unfavorited rocks on you
- place the cursor on the favorited rock
- press favorite key twice
This impacted the drop menu and the inventory menu
Add a check to execute the favoriting action only if the cursor points to an item
Repeat the steps described in Purpose of change, no more crash
=> Fix rare crash when unfavoriting an item twice

.github/workflows/manual-release.yml, .github/workflows/release.yml
SUMMARY: Build "[DDA Port] Pin mac_alias to 2.2.0 to fix dmgbuild"
Fix osx build
Cherry-pick https://github.com/CleverRaven/Cataclysm-DDA/pull/62402
Tried on my fork, release compiled
=> [DDA Port] Pin mac_alias to 2.2.0 to fix dmgbuild

lang/extract_json_strings.py
SUMMARY: I18N "Extract furniture switch prompt for translation"
Allow translators translation "Switch on/off the floor lamp" and similar messages.
Add new field to string extraction script.
On local clone, diffed freshly generated `cataclysm-bn.pot` before and after change, saw new strings appear.
=> Extract furniture switch prompt for translation

data/json/furniture_and_terrain/furniture-medical.json
SUMMARY: Bugfixes "Autodoc Deconstruction now gives same amount of materials as installation."
Unlike lamps, batteries and similar appliances, the Autodoc installation consumes 2 power converters, 2 heavy batteries and 40 copper wires while deconstruction only refunds the Autodoc.
It makes moving the autodocs a real pain in the ass, and consumes power converters which are fairly rare and bulky.
Autodoc deconstruction now regurgitates the same amount of materials you shoved into it.
- Create an autodoc specifically for home use that requires heavy batteries to indicate that autodocs in laboratories and similar areas are powered by their grid.
Note that autodocs don't actually consume power anyway, so this is realismic, not useful.
See that it is possible to construct and deconstruct …
=> Autodoc Deconstruction update

data/json/items/armor/undergarment.json, data/json/recipes/armor/torso.json
I noticed while playing that the camo tank top cannot be repaired regardless of the players skill. This was because there was no repairs_like for the camo tank top. This changes it. 
Added a recipe for the camo tank.
Leave it be with no ability to repair it? 
But also the main game has a normal tank top that you can repair? 
Tested in game, can repair it now! 
N/A
=> Camo tank top recipe

src/monattack.cpp
SUMMARY: Bugfixes "Grappler zombies can't grab through vehicle holes"
Fixes #2198 
Was missing the check on the final tile.
=> Fixes grappler zombies going through holes

src/veh_type.cpp
SUMMARY: Build "Fix MSYS2 build by rewriting turret ammo finalization check"
Fix MSYS2 build
I'm not sure why GCC trips up here, but this fixes the issue.
Compiled locally, game builds and runs.
=> Fix MSYS2 build by rewriting turret ammo finalization check

data/json/construction.json
SUMMARY: Bugfixes "Fix freezer construction recipe"
I apparently didn't edit the construction recipe properly when I did #2172. Freezer recipe uses fridge.
Edit `construction.json`
Construction uses freezer to make freezer.
=> Fix construction recipe

data/json/vehicleparts/vehicle_parts.json
SUMMARY: Bugfixes "Makes Autodoc Couches assignable as seats in vehicles."
ulila on the Discord suggested it and it made sense since companions zoom to unoccupied seats, making use of the autodoc in vehicles on companions very difficult.
@leoCottret suggested that comfort be added as it was not copied appropriately when he made the couch a vehicle part. I also copied over the bedding warmth. So now your NPCs can sleep under a bunch of sharp needles and scalpels fairly comfortably.
Add `SEAT` flag to vehicle autodoc couches.
Copy over `comfort` and `floor_bedding_warmth` from the furniture version of the autodoc couch.
- Have examining the autodoc allow you to assign NPCs to the couch.
Would be useful on furniture, but in a vehicle it's just extra steps. And C++. ~I hate C++~
- Have …
=> Makes Autodoc Couches assignable as seats in vehicles. Adjust autodoc couch capacity.

src/cata_tiles.cpp
SUMMARY: Bugfixes "Fix a rendering bug in lower z levels when flying"
Fixes a bug that would cause tiles that are out of sight without any map memory to not be rendered at all when fov 3d was on. 
When rendering fails to find a good lower tile to render the terrain of, it will still render the lowest visible tile.
=> Fixes a rendering bug with lower z levels

src/item.cpp
SUMMARY: Interface "Display name of loaded ammo instead of ammo type (#51439)"
It's nice to know which one of my guns is loaded with FMJ or JHP so I can figure out which gun I should use on the armoured enemies
Ports [#51439](https://github.com/CleverRaven/Cataclysm-DDA/pull/51439).
- Make it display the full name of the default ammo when it's not loaded.
Much less useful, I'd prefer it tell me the ammo group usable for the gun rather than the specific default ammo it assumes.
Spawned multiple Barrett rifles and M1911, loaded them with different ammunition and checked that they displayed correctly. Unloaded all of them and checked that they still displayed ammo group as expected.
Came across it while looking over the Proportional and Relative support PR
=> Display name of loaded ammo instead of ammo type (#51439)

data/json/items/armor/power_armor.json
SUMMARY: Bugfixes "Updates field combat exoskeleton to have the same materials as its helmet"
Fixes a mistake I made while updating power armor to make use of carbide. Turns out I'd added carbide to light power armor helmets, but not to the light power armor suit itself.
Set light power armor to use the same materials as the helmet, becoming superalloy/carbide instead of superalloy/plastic.
Waiting for someone else to fix my mistake.
2. Copied affect file to a release to test out and compare to other power armor items.
3. Confirmed protection value of field combat exoskeleton was now 54/54/77, matching that of the helmet.
PR where I made this mistake: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1493
=> Fix light power armor being weaker than its helmet

.github/workflows/manual-release.yml, .github/workflows/release.yml, build-scripts/requirements.sh, src/debug.cpp
SUMMARY: Build "Build from custom MXE GCC 11"
Fix failing mxe builds.
1. GCC provided by mxe's apt repositories does not support c++17
2. There are no mxe repositories for `ubuntu-22.04`
3. `ubuntu-22.04` doesn't have `python` package, only `python3` and `python-is-python3`
* Port https://github.com/CleverRaven/Cataclysm-DDA/pull/52023
* Port https://github.com/CleverRaven/Cataclysm-DDA/pull/53837
* Downgrade runner to `ubuntu-20.04`
Built a mxe release in a fork, downloaded it, tested backtrace generation on Windows
=> [DDA Port] Build from custom MXE GCC 11

doc/COMPILING/COMPILING-VS-VCPKG.md
SUMMARY: Build "Bumped OS and VS requirements in vs-vcpkg builds"
Win 7 is out of support and almost noone uses Win 8.1, so bump min OS requirements for Visual Studio+`vcpkg` builds to Win 10.
Also bump min Visual Studio version to 2019, as I'm not sure whether older ones work with our `vcpkg` setup.
It came up on Discord that Win 8.1 does not support TLS v1.2, which is needed for `vcpkg` to download some of the sources from xiph.org to build `libogg`.
=> Bump OS and VS requirements in vs-vcpkg builds

src/cata_tiles.cpp, src/cata_tiles.h, src/debug_menu.cpp, src/game.cpp, src/game.h, src/handle_action.cpp, src/options.cpp, src/sdltiles.cpp
SUMMARY: Infrastructure "Show missing tiles from the debug menu"
Make it easier for people to find this feature. 
The reporting function takes a new argument of a function returning a stream and outputs to that stream. When triggered from the debug menu this is sent to a string and then added to the message log. 
Using a popup rather than the log, but they don't do scrolling.
=> Debug option to show missing tiles

src/cata_tiles.cpp
SUMMARY: Bugfixes "Fix bad layering in iso mode"
Fix the player appearing on top of terrain in iso mode. There's also a small fix in that revival and zone indicators will display across z levels now. 
Similar to the old algorithm the drawing is done a row at a time again and within a z level we do more tile by tile rather than layer by layer. 
It could use a lot more work, lower z levels still looks kinda pants in iso. 
Errr looks ok I guess?
Old:
New:
=> Fix terrain rendering above character in iso mode

gfx/MSX++UnDeadPeopleEdition/tile_config.json
SUMMARY: Bugfixes "Fix mountable autodoc/autodoc couch having a transparent background (undead tileset)"
kwark reported that the background was missing from the mountable autodoc/autodoc couch
Cf above, mountable versions have a black background, normal versions don't
=> Fix mountable autodoc/autodoc couch having a transparent background (undead tileset)

data/json/furniture_and_terrain/furniture-appliances.json, data/json/items/fake.json, data/json/items/tool/metalworking.json, tests/iteminfo_test.cpp
SUMMARY: Features "Add item repair use action to charcoal forges, electric forges, and grid forge fake item."
Something I'd wanted for years but only realized I could implement while working on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2187. This is basically why can forges in Cataclysm++ have a use action, because for the longest time you couldn't have forges do repair actions without it causing weird behavior with the furniture version.
1. Added repair action to electric forges. Uses fabrication skill and targets all metal materials that welders and soldering irons target, uses tool quality and charges per use just below that of welders.
2. Added repair action to charcoal forges. Like with welders vs makeshift welders, charges consumed and time take is doubled while tool …
=> Allow repairing items with forges

.github/workflows/android.yml, src/mutation_ui.cpp
SUMMARY: Build "Added android builds to CI"
Fix #2243 and prevent future android build failures.
Add a separate PR workflow that builds an android build.
Broken PR builds report error and a failed check: [run link](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/3725085964/jobs/6317665520)
```
[arm64-v8a] Compile++      : main <= mutation_ui.cpp
/home/runner/work/Cataclysm-BN/Cataclysm-BN/android/app/jni/src/mutation_ui.cpp:245:35: error: use of undeclared identifier 'my_mutations'
ctxt.register_manual_key( my_mutations[p].key, p.obj().name() );
^
/home/runner/work/Cataclysm-BN/Cataclysm-BN/android/app/jni/src/mutation_ui.cpp:248:35: error: use of undeclared identifier 'my_mutations'
ctxt.register_manual_key( my_mutations[a].key, a.obj().name() );
^
2 errors generated.
``` …
=> Fix android build, add android to CI

.github/workflows/manual-release.yml, .github/workflows/release.yml
SUMMARY: Build "Release experimentals as pre-releases on GitHub"
Fixes #2231
Mark new experimental releases as pre-releases.
Also made manual release actions produce draft releases, so they could be reviewed before going public.
Existing releases would still remain as pre-releases, but they can be marked as pre- en masse with [a python script](https://gist.githubusercontent.com/olanti-p/6f30e959ee326832fec8222e9393dcba/raw/9de6efe28a21233c4c58a6ff9a09212c6ac826b0/mark_all_releases_as_pre).
Switching over to the newer version of the action (https://github.com/softprops/action-gh-release) and enabling a bunch of new features (changelog autogeneration, new discussion per release). 
Tried this on my fork, works as expected.
=> Release experimentals as pre-releases on GitHub

.github/workflows/msvc-full-features.yml, .github/workflows/msys2.yml, tests/basecamp_test.cpp
SUMMARY: Build "Added MSYS2 builds to CI"
MSYS2 builds are the 2nd build option on Windows after MSVC, it'd be nice to know when it breaks.
Added MSYS2 builds to CI.
~~It took 1h 11m 17s to complete on my fork, so we may want to run these on `upload` only~~
Could've been some kind of throttling, the run on this PR completed in 25 minutes.
~~The [run](https://github.com/olanti-p/Cataclysm-BN/actions/runs/3726748032/jobs/6320393782) on my fork failed, I'll assume it's rng-related unless this one fails too.~~
It was an issue with the test, fixed it.
=> Add MSYS2 builds to CI

.github/ISSUE_TEMPLATE/bug_report.yml
SUMMARY: Infrastructure "Fix broken `README` link on bug report"
Relative link does not work when issue form is rendered in issues page.
changed link to README to absolute URL.
=> Fix broken `README` link on bug report

src/avatar_action.cpp
SUMMARY: Bugfixes "Fix ammo conversion not working"
Ammo conversion gunmods do nothing. This should fix it.
Fixes #1377 
Avatar action for shooting used weapon type's ammo type set, not current type's. This changes it to the calculated ammo type set.
N/A
* Spawn M27, Blackout ammo and Blackout conversion kit
* Unload M27, then the magazine, then reload it with blackout ammo
* Try to fire it - it should complain about incompatible ammo type
* Unload M27, apply conversion kit
* Reload M27 and try to fire it - it should work this time
* Reload M27 with its old ammo
* Try to fire it - it should complain now
Does anyone know if there might be an edge cases where the weapon type's ammo set may have been preferable? I'd rather not replace this bug with another.
=> Fix ammo conversion not working

tests/translations_test.cpp
SUMMARY: Infrastructure "Don't skip translations test"
After #1433 it's no longer necessary to build en_US translation files for a libintl-related workaround, but the tests erroneously expect them anyway.
Don't require en_US translation files.
Run tests locally, works as expected.
=> Don't skip translations test

data/json/items/faults_bionic.json
SUMMARY: Bigfixes "Fix phenol being used 1 mL at a time instead of 250 mL by CBM sterilization option"
Simple problem Krwak spotted over on the BN discord, where it takes only a single milliliter of phenol to sterilize a CBM in the mending menu. Turns out in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1665 I failed to notice that phenol is one of the only chemicals in the JSON that has a volume of 1 mL instead of going the "volume of 250 mL per stack but 250 charges per stack" like you normally see, and thus assumed it was like water (no stack, 250 mL per unit).
Changes the higher-level sterilization recipe in faults_bionic.json to use 250 mL of phenol as originally intended.
1. Making more chems use this method instead of having a stack size of 250.
2. Screaming.
Checked …
=> Fix alternative sterilization using 1 mL of phenol

src/filesystem.cpp
SUMMARY: Infrastructure "Don't show warnings in log when scanning for files in non-existent dirs"
There are warnings about missing directories in `debug.log` when game tries to load data from nonexistent user dirs:
```
15:11:02.060 WARNING : opendir [./user_dir/sound/] failed with "No such file or directory".
15:11:02.060 WARNING : opendir [./user_dir/gfx/] failed with "No such file or directory".
15:11:02.060 INFO : Number of render drivers on your system: 3
15:11:02.060 INFO : Render driver: 0/opengl
15:11:02.060 INFO : Render driver: 1/opengles2
15:11:02.060 INFO : Render driver: 2/software
15:11:02.073 WARNING : opendir [./user_dir/mods/] failed with "No such file or directory".
```
These are entirely benign, but the word "failed" seems to be an attention grabber whenever people try …
=> Don't show warnings in log when scanning for files in non-existent dirs

src/options.cpp
SUMMARY: Interface "Enable SDL Graphical Overmap by default"
Simple answer to all these "what mod?" and "how did you make it this way?" questions on Discord.
Enable SDL Graphical Overmap by default.
People who dislike it can still turn it off in settings.
None should be needed.
=> Enable SDL Graphical Overmap by default

src/options.cpp, src/sdltiles.cpp
SUMMARY: Interface "Get rid of linear texture scaling option"
Closes #2185
Closes #1888
Current issues with scaling options:
1. `Scaling mode` and `Scaling factor` options are worded similarly and placed in same block, which makes it look like they're responsible for single feature (scaling game display), but de-facto scaling mode is for _all_ texture scaling (tiles & display scaling) while scaling factor is for display scaling only.
2. `Scaling mode` option implies that `linear` scaling is of the higher quality, which may be true when it comes to 3D games and moving and/or natural textures, but BN is a 2D game with static pixel art, any scaling except nearest turns the pixel art into blurry mess whenever you zoom in.
1. Add `Display` to `Scaling factor` option name to better reflect its …
=> Get rid of linear texture scaling option

src/veh_interact.cpp
SUMMARY: Bugfixes "Fixed volume display in vehicle tanks"
Fix #1186
Get rid of roundabout charges logic and just use contents volume.
Volume shows up as expected
=> Fix volume display in vehicle tanks

data/json/itemgroups/supplies.json, data/json/mapgen/helipad.json
@KheirFerrum had mentioned that helipads themselves don't have any helicopter parts. So I added the civilian and the military parts group to the crates that spawn. This allows for motors, rotors and now steel plating/military plating to the loot locations.
Added the groups for civilian and military helicopter parts to the crates that spawn. I also added military plating and steel plating to these groups. 
not doing it
Tested in game. New parts show up in helipads now!
=> Added new helicopter parts group to helipad

src/json.cpp, src/json.h, src/magic_enchantment.cpp
SUMMARY: None
Make it so old enchant values removed in #2264 show warning instead of preventing world loading.
I did not think any mods would be using the non-implemented values, but in hindsight I'm not sure why I thought that, of _course_ some mods would.
Add try-catch block.
Tested locally, works as expected
=> [Hotfix] Warn on unknown enchant_val instead of error

data/json/items/containers.json, data/json/items/vehicle/utilities.json, data/mods/TEST_DATA/furniture.json, src/iexamine.cpp, src/item.cpp, src/item.h, src/item_factory.cpp, src/itype.h, src/map.cpp, src/map.h, src/vehicle_part.cpp, tests/rot_test.cpp
SUMMARY: Bugfixes "Fix actualize causing rot in working freezers"
`map::actualize` doesn't pass the freezer/fridge/etc. flags to rot check functions. Now it should do it.
* Pass the temperature flags in `map::actualize` rot functions to items "being actualized"
* Rename `item::has_rotten_away( tripoint )` to `item::actualize_rot`, to distinguish it from the actual `has_rotten_away`, which is only a check, not an update.
* Remove `insulation` along the way - it's unused anyway
* Pass weather generator to rot functions to minimize effects of global state weather on tests
* Add a test that loads a tinymap, spawns things to rot, unloads the area, advances time, then reloads (and thus actualizes) the area again
* The test uses a debug "atomic freezer" furniture, to avoid possible bugs from …
=> Fix actualize causing rot in working freezers

data/mods/TEST_DATA/relic_test.json, doc/JSON_INFO.md, doc/RELICS.md, doc/TRANSLATING.md, lang/extract_json_strings.py, src/character_turn.cpp, src/item.cpp, src/item.h, src/json.h, src/json_source_location.cpp, src/json_source_location.h, src/relic.cpp, src/relic.h
SUMMARY: Features "Relics can recharge now"
Working towards #1816 (implements step 3)
~~Depends on #2283 and #2254~~ Rebased on latest `upload`, does not depend on them anymore.
This PR implements relic recharge that mirrors existing artifact recharge code, except it works for NPCs and also has a variety of knobs accessible from JSON.
Tweaked behavior of "close to skin" to be more transparent.
* Porting DDA relic recharge.
I'm not sure how reliable it is. Also, no `ARTC_PORTAL`, which is a thing CV wants.
TODO:
=> Implement relic recharge

src/mattack_actors.cpp
SUMMARY: Bugfixes "Turrets won't shoot vehicles on another z level when 3d vision is off"
Fix the bug where turrets weren't respecting fov3d when firing at vehicles. 
Just a simple fov3d and z level check.
=> Turrets won't shoot vehicles on another z level when 3d vision is off

data/json/bionics.json, src/bionics.cpp, src/bionics.h, src/bionics_ui.cpp, src/character.cpp, src/character_functions.cpp, src/game.cpp, src/iuse.cpp, src/melee.cpp, src/monattack.cpp, src/player.cpp, src/suffer.cpp
SUMMARY: Interface "[DDA Port] Show bionic trigger cost in UI"
Alarm System bionic consumes quite a bit of energy when triggered, but that's not communicated in UI in any way.
Fix #1640
Fix #2236
Cherry-pick https://github.com/CleverRaven/Cataclysm-DDA/pull/49635
Most of it applied cleanly, but I had to hack around for the probability travel and active defense system bionics since their behavior is completely different from DDA.
=> [DDA Port] JSONize bionic trigger costs, show them in UI

data/json/recipes/electronic/parts.json
no alternator is craftable, so producing electricity is a thing you need loot for. The smallest alternator in the game is the bicycle one, and since it is possible to produce a dynamo by yourself, why shouldn't you do it in-game as well? The recipe is autolearing in electronics lvl 4, can be uncraft-learned at lvl 2 and is in 3 electro books.
=> make bicycle alternators (dynamos) craftable.

data/json/items/comestibles/wheat.json, data/json/obsoletion/recipes.json, data/json/recipes/food/pasta.json
Fast noodles were odd. 500 ml of volume (where from?) and have no special use, which can't be handles by macaroni or other noodles. The recipe got obsoleted and is now found in the wild only. 250 ml is the new volume.
=> obsolete fast noodle recipe, lower volume

src/iuse_actor.cpp
SUMMARY: Bugfix "Add Active Exception to `deploy_furn`"
Arcana's candle of warding couldn't be set to active when actually active as it would proc the `deploy_furn` iuse action on every turn. A closer look revealed that it was because unlike most other iuse_actors it didn't check the bool that denoted that an item was being processed because of active item processing.
Adds the check that most other iuse_actors use to prevent undesired triggers of iuse_actor. This merely prevents it from continuously proc'ing when active, it doesn't prevent the player from activating an item and using the `deploy_furn` action.
-Rework entire system so that we know what iuse actors are active/passive.
Not particularly useful unless we actually have a way to json define iuse_actors, future project?
Installed …
=> Add Active Exception to `deploy_furn`

data/json/recipes/other/vehicles.json
Steel frames had the oddity that there was the requirement for glare protection, even if no torch was needed (forged). This will split those 2 recipes into a dedicated forged and welded version.
=> remove glare protection requirement for forged frames

data/json/recipes/other/vehicles.json, data/json/vehicleparts/wheel.json
steerable mounts were blocked behind "paywall" (which is arc welding), so getting your own bike was nearly endgame material, especially, when playing with low item drops to get any sunglasses.
This should make it a bit easier building a bike.
Light mounts can be installed via bolting.
Light mounts can also be forged.
=> make light mounts bolt install and add forging recipe

src/advanced_inv.cpp, src/crafting_gui.cpp, src/enums.h, src/examine_item_menu.cpp, src/game.cpp, src/game_constants.h, src/game_inventory.cpp, src/gamemode_defense.cpp, src/iexamine.cpp, src/item.cpp, src/item.h, src/iteminfo_query.cpp, src/iteminfo_query.h, src/itype.h, src/iuse.cpp, src/map_item_stack.cpp, src/map_item_stack.h, src/npctrade.cpp, src/output.cpp, src/output.h, src/pickup.cpp, src/recipe_dictionary.cpp, src/rot.cpp, src/rot.h, src/vehicle.h, src/wish.cpp, tests/iteminfo_test.cpp, tests/rot_test.cpp
SUMMARY: Interface "Display fridge/freezer buff to rot time in `item::info`"
Close #1443
* Refactored `item::info` to return the vector that it had as one of the arguments, rather than a string based on it - it seems to be used more than the string it returned before
* Created `item::info_string` that returns said string
* Added a new argument to `item::info` - a `temperature_flag` (as a simple enum right now, we may want a struct if we get more of those "context arguments", like "it is wielded by this NPC, so also print statblock modified by their stats")
* Remove sneaky +5 F temperature penalty for items carried on person
* Use `units::temperature` in few more places
* Currently: "It is/isn't protected from rot in current storage. It will last at least [time it will last at highest …
=> Display fridge buff in `item::info`

src/game.cpp
SUMMARY: Bugfixes "Fix autoforage ignoring harvestable furniture if underlying terrain has no examine action"
After much struggling to figure out why auto-harvesting dandelions wasn't working right (only triggering when on water or other examinable terrain, hence why cattails were working, per Lamandus' findings), Coolthulhu found the exact cause pretty quickly. Figured I'd try to implement the fix for it while I've got the time.
1. In game.cpp, `game::place_player`, changed the section checking for auto-foraging to only bail out if both the terrain AND furniture have no examine action detected, instead of only checking for whether terrain can be examined.
1. Removing the check entirely, if we feel the performance hit wouldn't matter.
2. Going back to procrastination and letting Coolthlhu …
=> Fix autoforage failing with dandelions

src/item.cpp, src/item.h, tests/iteminfo_test.cpp
SUMMARY: Interface "Adjust 'protected from rot' lines in item description"
Making the new "item is protected from rot" descriptions less confusing.
* Don't show duration for unprotected items - it was remaining shelf life divided by ~6
* Fix "indefinite" duration for contained items - it tried to show rot duration for the container
1. Spawn a burger, confirm it has no duration line
2. Spawn a fridge, turn it on, give it power
3. Spawn a jug of milk and store it in the fridge
4. Confirm it has sane guaranteed freshness time in description
=> Adjust "protected from rot" lines in item description

data/json/uncraft/ammo/signal_flare.json
SUMMARY: Balance "Allow disassembling signal flares for materials"
Thing thing I'd been wanting to do for a while was be able to uncraft signal flares. Because of the standard that shotshells use cutting quality instead of bullet pulling, this warrants assigning it an uncraft rather that making the recipe reversible like one would normally do.
1. Added an uncraft result for signal flares, based off the uncraft for 00 shot and returning all the things the signal flare recipe requires as components. Realistically 12 guage flare rounds are often longer than normal shotshells, but that only really concerns crafting them in the first place since if there was excess material it could be cut down to length.
2. Also updated its tool requirements to be consistent with other shotshell recipes. This …
=> Allow uncrafting signal flares

data/json/recipes/armor/feet.json
Crafting winter boots takes extremly long with 6 hours. It reduces it to 2 hours, to fit more to the "non survivor stuff" crafting times.
=> Winter boots now take 2 hours to craft

README.md, doc/TESTING.md
SUMMARY: Infrastructure "Update badge text to stable 0.2"
update badge in README to match with stable 0.2
link badge to 0.2
it'd be great if there was a link to latest non pre-release release, but there wasn't.
=> Update badge text to stable `0.2`

src/character_turn.cpp
SUMMARY: Balance "Patting down fire has more impact, stop drop and roll triggers earlier"
A thing @KheirFerrum looked into on the BN discord recently, it was found that the "attempt to put yourself out if on fire" behavior was a bit flawed. Part of it was because DoT from being on fire itself appears to be add more duration from it dealing `DT_HEAT` hits depending on the clothing worn, which is fair since clothing is good fuel.
But where this became a problem was when it intersected with the code to try and put yourself out. The baseline reduction in duration does almost nothing, while the more effective "stop drop and roll" action was locked behind a threshold of more than a minute duration before your character would be willing to choose the (vastly more effective) option. Needless to …
=> Updates to putting self out when on fire

data/json/bionics.json, data/json/items/bionics.json, data/json/items/generic.json, src/bionics.cpp
SUMMARY: Bugfixes "Fix Active Perpetual Power Gen and Charge Timer Handling"
Was reminded to look into power gen, originally to check if Joint Torsion Ratchet actually works and why the Atomic Battery CBM from Cata++ doesn't work when active.
Adds a consideration in `bionics.cpp` for active perpetual power gen that isn't sunlight/wind. Fixed how charge timers are reset for power generators based on `attempt_recharge()` so that `"time": 1` means it gives power every turn, which is the intended approach as seen by how every other power drawing bionic uses that convention and 0 means it never recharges.
- Leave broken for kicks
- Alter the Joint Torsion Ratchet efficiency
Balance thing, best kept separate from bugfixes.
Installed the Cata++ mod, edited it to have `fuel_efficiency` and …
=> Fix Active Perpetual Power Gen and Charge Timer Handling

data/json/furniture_and_terrain/furniture-storage.json
SUMMARY: Balance "Allow prying open coffins with level 1 prying"
This was brought up in the alternatives section of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/837 a while back, I noted that it did seem to be like a closed coffin would be a comparable level of effort to prying a crate open.
Lowered `pry_quality` of closed coffin from 2 to 1, and removed `pry_bonus_mult`. Kept `difficulty` at 7 so that it still take a bit more effort to pry open that a crate.
Accepting that prybar is love, pry bar is life.
=> Allow prying coffins with makeshift crowbar

data/json/items/ammo/223.json, data/json/items/ammo/270win.json, data/json/items/ammo/300.json, data/json/items/ammo/3006.json, data/json/items/ammo/300blk.json, data/json/items/ammo/308.json, data/json/items/ammo/4570.json, data/json/items/ammo/50.json, data/json/items/ammo/545x39.json, data/json/items/ammo/700nx.json, data/json/items/ammo/762.json, data/json/items/ammo/762R.json
SUMMARY: Balance "Ammo Rebalance projectile part 8, applying new armor penetrationg standard to rifle ammo"
As seen in part 7 (https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2121), while we've now got every ammo item updated, a less-broken scheme for calculating armor penetration was introduced in that PR for the ammo items that I updated in it. This PR starts backporting that new method to the other ammo items I'd already gone over, to make them less horrifically lethal against ballistic armor that's obstinately expected to make those hits survivable.
For the moment, I'm only focusing on applying this to the other rifle rounds, to make things a lil less cluttered but also due to a question posed in the alternatives section.
Said method is, per the documentation:
```
The relative …
```
=> Ammo Rebalance, Part 8

src/activity_handlers.cpp
SUMMARY: Features "Make NPCs care more about how they cut down trees"
NPCs only consider critters when cutting down trees. This can lead to vehicles being crushed or structures having their walls collapsed. This makes NPCs look really dumb.
Check for Terrain, Furniture, and Vehicles in addition to Critters.
Additionally, if a direction is viable throw it into a collection to be randomly selected from so trees don't consistently fall in the same direction.
Spawned NPC with a start at LMOE shelter so I'm surrounded by trees. Set up a chop zone near the LMOE entrance and let the NPC get to work.
=> Try to pick a safe direction to cut down a tree

data/mods/No_Fungi/comestibles.json, data/mods/No_Fungi/furniture.json, data/mods/No_Fungi/recipes.json, data/mods/No_Fungi/terrain.json
SUMMARY: Mods "Update No Fungal Monsters mod with much-needed JSON modernization and maintenance"
I noticed during gameplay that a marloss gelatin dropped from a zombie scientist (90% certain it was some weird luck with Arcana's injection of magitech and biological samples into their monsterdrop entry) and realized that the item is pretty old and jank:
Reason for it is No Fungal Monsters mod, despite being still available and certainly still a mod I personally use out of force of habit, could use a touch of updating. In particular, evidently whenever I ages ago figured out how to set fungal spires to not spawn, I forgot to account for the fact that the items no longer really need to have any big tweaks made to them, since they won't spawn in vanilla with the mod enabled. What little …
=> Maintenance for No Fungal Monsters mod

data/json/overmap/map_extras.json, data/json/regional_map_settings.json, src/map_extras.cpp
SUMMARY: Balance "Jabberwock map extra cleaned up and given more usage, allows fleshy shamblers and flesh golems to actually exist"
This aims to make use of some unused pre-evolutions of the jabberwock monster, and in the process make it feasible to make use of the rare jabberwock map extra a bit more. Adding them to confined locations like building map extras seems like the sanest approach to introduce them with less risk of them wandering off and ganking players, Magiclysm-style.
1. Jabberwock map extra code set to place a fleshy shambler instead of a jabberwock. Since it can then evolve into flesh golems and then jabberwocks, this allows for the entire evolutionary chain to spawn in-game instead of only the original and final variant ever showing up. Additionally, due to its extremely …
=> Updates to jabberwock map extra

data/json/itemgroups/Weapons_Mods_Ammo/ammo.json
.22 Ammo only spawned as rifle ammo. Problem is, we have 5 .22 pistols, 1 revovler and 1 smg. It makes sense, putting it also in the pistol ammo group, since .22 is extremly plentiful.
=> Make .22 ammo also appear in the pistol ammo drop list

data/json/items/gun/22.json, data/json/items/magazine/22.json
The J22 used wacky values for their magazines. It seems it wasn't updated to the "magazine well" standards. This will correct the issue.
=> Correct J22 magazine volumes

data/json/npcs/isherwood_farm/NPC_Claire_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Eddie_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Jack_Isherwood.json, data/json/npcs/isherwood_farm/NPC_Jesse_Isherwood.json
SUMMARY: Balance "Isherwoods can now trade nearby owned items, minor dialogue updates"
I noticed most of the Isherwoods were given dialogue to allow you to trade with them, and tend to be entirely surrounded by goods on shelves practically set up on display, but they all have very little in their baseline inventories and weren't set to use shopkeeper behavior. This is needed for an NPC to see nearby faction-owned goods as being valid for sale.
Also found some other things I could fix along the way.
1. Set the NPC mission of Jack, Eddie, and Claire from 7 (stand around) to 3 (stand around but also sell nearby stuff).
2. Removed a redundant mission entry from Jesse Isherwood's mission chain that was just getting overidden by a near-identical mission anyway.
3. Also made Jesse's mission …
=> Isherwoods trade nearby items, dialogue updates

data/json/items/containers.json, data/json/recipes/other/containers.json
gallon jugs and plastic jerrycans couldn't be crafted with mold from scratch. This will change it. It makes them craftable with plastic chunks and crafting times got tweaked. Also made the gallon jug lighter to be comparable to the 2 litre bottle.
=> Make plastic containers craftable from scratch (Jug+jerrycan) + tweaks

data/json/furniture_and_terrain/furniture-sleep.json
Destroyed ground mattresses didn't drop scrap, now they do. It is the same amount as if they were still on the bedframe.
=> Add scrap to laid down mattresses.

Makefile, src/veh_interact.cpp, src/vehicle.cpp, src/vehicle.h
SUMMARY: Interface "Show maximum buoyancy"
- resolves #2276 
calculate maximum buoyancy using archimedes's law, that is `volume * density of water * earth gravity`.
display method is identical to #1631 .
- change `water_hull_height` as mutable?
- instead show 'mass left until sinking'? (max buoyancy - total mass)
**boat**
<details>
<summary>screenshots</summary>
</details>
created a canoe, calculated maximum buoyancy was 2880kg.
the canoe sank at approx. 2890kg.
**seaplane**
<details>
<summary>screenshots</summary>
</details>
created a seaplane, it both shows maximum lift and buoyancy accordingly.
=> Show maximum buoyancy on vehicle info

data/json/items/classes/gun.json, data/json/items/gun/22.json, data/json/items/gun/223.json, data/json/items/gun/3006.json, data/json/items/gun/308.json, data/json/items/gun/38.json, data/json/items/gun/40x46mm.json, data/json/items/gun/4570.json, data/json/items/gun/flintlock.json, data/json/items/gun/shot.json
SUMMARY: Balance "Standardize use of stock mount slot vs stock slot for eventual implementation of sawing off stocks"
As mentioned in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2314, I was planning to update some issues with stock mount slots, mainly:
1. It's inconsistent, most guns in the game that have a plain wooden stock can have their stock swapped out. Example: The M1 Garand and M1918 BAR can have their stocks modified from the get-go, but not the M1903? The M24 Sniper Weapon System can't have an adjustable stock (standard on the A2 version IRL) slapped on it by default? It seems to me like this would be better served using it primarily to represent guns that don't have a stock to begin with.
2. One of these days I plan to add some way to saw stocks off, and that would …
=> Standardize use of stock mount gunmod slot

data/mods/Generic_Guns/vehicles/ammo_redefine_hacks/temp_ammo_redefine_hack.json
Found another small error in the naming. This will fix it.
=> Small name error correcting in Generic Guns

data/json/recipes/food/drinks.json
Maple syrup recipe was quite bulky. you needed 40*x amounts of maple sap to create 16*x syrup units.
This will change to 5*x sap and it will produce 2*x syrup units
=> lower "bulkiness" of maple syrup recipe

data/json/vehicleparts/seats.json
This makes it that installing a cloth sheet seat doesn't require a wrench (?) but rather a hammer and some nails to put it in place ontop of the frame.
=> Make the foldable sheet seat use nails instead of "bolts" to install

data/json/uncraft/generic.json
Some recipes took a very high amount of time to uncraft, giving a relatively low amount of stuff back. This will reduce the times like this: 
3 hours -> 2 hours
5 and 6 hours -> 3 hours
7+ hours -> 4 hours.
=> Reducing uncraft times.

src/magic.cpp, tests/enchantment_test.cpp
SUMMARY: Balance "Bionic power no longer affects maximum mana"
Per discussion on the BN discord, implementing an in-repo example of mana-casting that isn't affected by the bionic energy penalty was running into delays (as the main example of it in action was planned to be Arcana mod, when it's ported over to become an in-repo mod), and most opinions have weighed in favor of it being fine to just axe the feature outright.
1. In magic.cpp, updated `known_magic::max_mana` to remove the `bp_penalty` feature entirely.
2. Updated enchantment_test.cpp, removing test cases and data only relevant to testing if the now-removed penalty is working correctly.
1. Rigging a quick-and-dirty in-repo solution to allow https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1823 to be merged without any more …
=> Remove bionic mana penalty

data/json/items/armor/holster.json
fast draw holsters only hold weapons up to 400 ml, like deep concealment and ankle holsters. But there are quick draw holsters on the market for glocks as well. Raising the possible volume to 500 ml should make sense.
https://www.kurt24.eu/airsoft/taktische-ausruestung/holster/4523/fast-draw-holster-glock-17-22-31-gen-1-4
=> make quick draw holsters hold pistols up to 500 ml (glocks)

data/json/furniture_and_terrain/terrain-flora.json
SUMMARY: Balance "Set blackjack oak to yield as much bark as birch and willow trees do"
Back when tanbark could be used to do the job of several pine boughs, it made sense for blackjack oak to give less bark than birch and willow trees, since tanbark had a use case for which a little went a long way. But one side effect of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1164 is that now tanbark is massively less effective than it used to be, and is instead functionally as good as pine boughs.
Updated tanbark yield of blackjack oak from 1-2 to 2-8, identical to that of birch and willow trees.
Rigging crafting such that you can in some way use tanbark and brains more efficiently than pine boughs, but eh.
Side note, it to this day bugs …
=> Blackjack oaks give as much bark as birch/willow

data/json/recipes/weapon/ranged.json
No crossbow version was autolearn. This will change it, that the standard version is now autolearn at 5 fab and 2 mech. I can alternatively use "skill_requiered" for 2 mechanics.
=> make standard crossbow autolearn at 5 fab+2 mech

src/options.cpp
SUMMARY: None
Follow-up to #2139.
Move 'Requires restart' from option name to option description to be consistent with other options.
=> Fix description of "minimize on focus loss" option

src/item.cpp
SUMMARY: Bugfixes "Fix magazine weight being counted twice for non-guns"
Fix #2399
Loaded tank was counted twice: first as the magazine, then as item contents.
Add magazine weight only if we're dealing with a gun.
Spawned loaded acetylene torch, its weight is now as expected 1.6+6=7.6kg
Spawned loaded Beretta M9A1, its weight remains as expected 0.96+0.24=1.2kg
=> Fix magazine weight being counted twice for non-guns

src/mattack_actors.cpp
SUMMARY: Bugfixes "Fixed laser lock from enemies"
Fixes #2014
Fix deserialization code.
Removing this functionality. It's only used by couple robots from Aftershock and a few other robots from obsolete mods.
Spawned a railgun robot from Aftershock, got a warning message about laser targeting a few turns before getting shot.
=> Fix loading of laser_lock

data/json/items/comestibles/med.json
Using antiseptic soaked cotton balls/rags lead to filthy end objects. It was just unnecessary button presses to get them clean again, since soap or normal water rarelly are an issue. This will turn the balls and rags to their "normal" form, making them reusable again.
=> Remove filthy tag of used antiseptic cotton balls and rags.

src/options.cpp
SUMMARY: Bugfixes "Fix black map screen on curses build"
Fix #2333
Don't attempt to draw map with tiles on curses build.
=> Fix black map screen on curses build

data/json/monstergroups/zombie_upgrades.json, data/json/monstergroups/zombies.json, data/json/monsters/zed-animal.json, data/json/monsters/zed-classic.json, data/json/monsters/zed_explosive.json, data/json/monsters/zed_soldiers.json
SUMMARY: Balance "Increase variety of spawns for zombie evolution"
A small improvement that came to mind, and one I might someday follow up on by either porting over some monsters from DDA, or devising other fitting evolutions to add in.
1. Defined `GROUP_BOOMER_UPGRADE` for boomers to evolve into, defaulting to huge boomers and a small chance of becoming a gasoline zombie. One of my random ideas for the future is an acidic variation that'll likely be quite a bit more common an evolution than gasoline zombies (since acid can't burn your house down).
2. Increased the odds of grabber zombies evolving into slavering biters instead of grapplers, for increased variation since `GROUP_ZOMBIE_GRAB` has grapplers as the default outcome.
3. Increased the weights for non-kevlar evolutions in …
=> Add more variation to some zombie evolutions

src/cached_options.cpp, src/cached_options.h, src/descriptions.cpp, src/game.cpp, src/item.cpp, src/iteminfo_query.h, src/monster.cpp, src/npc.cpp, src/options.cpp, src/veh_interact.cpp
SUMMARY: Interface "Add debug option to show object IDs in game"
Closes #2225
Items
Item contents
Furniture and terrain
Furniture (extended view)
Terrain (extended view)
Monsters
Monsters (extended view)
NPCs
NPCs (extended view)
Vehicles
Light blue color for ids inspired by id display in Minecraft UI.
~~For terrain and furniture, we have id display in mouse look & plain examine that can be activated by enabling debug mode, should it be rolled into this option?~~ Done.
See screenshots. With option off, works as before.
=> Add debug option to show object IDs in game

src/overmap.cpp
SUMMARY: Bugfixes "Fixed downstairs generating in labs at z = -10"
Fix #496
Don't generate stairs if we're at the bottom layer.
Reworking lab mapgen.
Somewhat hard to test given how our mapgen is semi-random.
I teleported around overmaps and checked that labs that reached the bottom don't have downstairs, so it seems to be working.
This should also fix the occasional CI final lab error.
=> Don't build stairs going lower z = -10

data/json/vehicleparts/turret.json
SUMMARY: Content "Add a few extra options for vehicle mounted guns"
Minor item on my idea list I started work on earlier today, while out and about on my laptop and thus wasn't able to do C++ stuff, adding a bit more variety to the options for what weapons you can mount on vehicle, in particular including more missile, survivor-made, and ballista-like options.
1. Added a turret vehiclepart for huge crossbows. This particularly fits the role of a ballista-style vehiclepart, something that blazemod had in most versions of it, with the big-ass crossbow being the most fitting vanilla counterpart.
2. Added a turret vehiclepart for repeated crossbows, also seemed fitting for a light ballista role.
3. Added the RM451 flamethrower as an option to mount on vehicles, fitting with regular …
=> Add a few more fitting options for vehicle turrets

data/json/items/armor/belts.json, data/json/items/armor/storage.json
SUMMARY: Balance "Adds repairs_like entries for remaining uncraftable belts and storage items"
Quick lil fix for some uncraftable items missing `repairs_like` while I'm getting ready to head out and about for some stuff.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2425
1. Defined `repairs_like` for tactical dump pouch, set to repair like the drop leg pouch.
2. Defined `repairs_like` for firefighter belt, police duty belt, and webbing belt, pointing to the tool belt.
3. Gave the judo belt template and obi gi a `repairs_like` of leather belts.
Waiting to do this when I next get wifi once I'm out, and/or seeing if someone else will have already PR'd a fix by then.
1. Searched in recipe folder to double-check which items in the relevant files were uncraftable.
2. Checked …
=> Add repairs_like to a few more items

data/json/mapgen/lab/lab_rooms.json
Removed the rubble tiles that spawned on lab kennel gates, by changing the gate symbol from caret ^ to H.
SUMMARY: Content. Removed the rubble tiles that spawned on lab kennel gates, by changing the gate symbol from caret ^ to H.
Always seemed like a very old oversight. The caret symbol is used for rubble in many places IIRC. For some reason it was also defined for the kennel gates in this case.
Played with this changed over many releases, always doing it manually for myself for each version. Got tired of doing it, so here we are. A smallest changed that has been, to put it mildly, overtested. CAUTION: wait for me to edit the No Hope mod too, because I forgot it has to be edited too, and idk how to cancel this.
=> Removal of lab kennel gate rubble tile

src/activity_item_handling.cpp
SUMMARY: Balance "Auto-eat can target valid low-calorie foods, remove behaviors related to old freezing code"
Per Viss' request, a bit of cleanup on auto-eat behavior in preparation for later on maybe trying to make its behavior a bit saner in a later PR, if either of us gets around to it.
In `find_auto_consume` of activity_item_handling.cpp:
1. Removed references to unused `MELTS` and `EDIBLE_FROZEN` flags, as freshly-frozen hot meat is no longer a thing in BN.
2. Per Viss' request, removed the check that removes otherwise-valid items with less than 50 calories from the list. This allows stuff like cooked dandelion greens to be selected. Additionally, the character will automatically eat enough stuff to become sated when auto-eat triggers anyway, and we don't have massive time inflation …
=> Updates to auto-eat filtration behavior

data/json/items/book/maps.json
Summary
Military helipads aren't added to your map when using military operations map. This adds them to it.
Add military helipads to the military operations map.
See above.
Describe alternatives you've considered
Not adding them but this seems like an oversight.
Testing/Additional context
This is my first time doing something like this in a long time. I'm still trying to figure out how to compile and test, it should work fine thou?
=> Add military helipad to military operations map

data/json/items/tool/tailoring.json
SUMMARY: Balance "Tailor and sewing kit hold more charges"
Sewing kit should be some kind of improvement over the basic wooden needle. By raising its max. charges, it doesn't need as many reloads as the wooden needle, but the tailor kit is superior (in reload and in upgrading stuff).
Raise sewing kit max charge to 400, tailor kit to 600.
Lowering the max charges the wooden needle would take. That would lead to errors to people having more than 100 charges already loaded into the needle. So rather raising the others than nerfing is a more sensible approach.
=> raise max charges for tailors kit and sewing kit

src/item_factory.cpp, src/item_group.cpp, tests/item_group_test.cpp
SUMMARY: Bugfixes "Fix issue with the durability of monster drops"
Fixes #2400 
The damage range was previously multiplied by 1000, which meant for a damage range of [0, 1] in JSON, a number between 0 and 1000 would be rolled for item damage. With the damage range no longer multiplied by 1000, the RNG rolls either 0 or 1 at a 50% chance for each, which then can be multiplied by 1000 to get the final damage value.
Spawned a bunch of zombie cops, killed them, made sure roughly 50% of dropped weapons were damaged.
Might affect things other than monster drops, and could be considered a balance change since it does change the distribution of item damage a bit. I had to change a test that didn't make sense.
=> Fix issue with the durability of monster drops

data/json/overmap/map_extras.json
SUMMARY: Content "typo fix: Shrubberry to Shrubbery"
This typo is older than time.
Keyboard smash until typo fix. Groknak fixes typo.
Drugs. Violence. Rock 'n roll. Other miscellaneous depravity. Even computer games.
After deleting a single character from a single file, using an advanced text editor, and after playing with this change for dozens of hours, recreating it multiple times in multiple versions over the past years, I can confidently say that I have no idea if this profound change - a downright overhaul - has had any adverse effects. I fully expect the economy to crash if this gets merged.
=> fix typo `Shrubberry` to `Shrubbery`

data/json/items/ammo/40x46mm.json
SUMMARY: Balance. "The 'abstract' section of the file had no volume defined for the grenades."
All the 40x46mm copy and get most their settings from the "abstract" section, so they had no volume, thus presumably defaulting to 0.010 litres per grenade IIRC. This repeated to ALL types (HEDP, buckshot,etc) since NONE of them had individual volumes defined either. Quick math shows that the volume of a cylindrical object with dimensions 40x46mm is around 260ml. In this case one end of the cylinder is round, which would make the volume smaller. However, if you were to put a number of these grenades into a container, there would be inevitable unfilled gaps, like with any objects that aren't perfect cubes, hence increasing the space they take. Also, 250ml appeared in a mod or two as their …
=> Fixed 40x46mm grenades not having volume

src/crafting_gui.cpp, src/recipe.h, src/recipe_dictionary.cpp
SUMMARY: Interface "Add mod source & id display to recipes"
Confusion over inability to see recipe source or id has come up multiple times on Discord.
Add mod source tracking & debug id display to crafting recipes.
=> Add mod source & id display to recipes

src/assign.cpp, src/assign.h, src/cellular_automata.cpp, src/cellular_automata.h, src/coordinates.cpp, src/coordinates.h, src/event.cpp, src/event.h, src/font_loader.cpp, src/font_loader.h, src/generic_factory.cpp, src/generic_factory.h, src/itype.cpp, src/itype.h, src/map.cpp, src/map.h, src/npc.cpp, src/npc.h, src/output.cpp, src/output.h, src/point.cpp, src/point.h, src/scent_block.cpp, src/scent_block.h, src/sdl_utils.cpp, src/sdl_utils.h, src/submap.cpp, src/submap.h
SUMMARY: Build "Move large functions to `.cpp` files"
reduce large header sizes.
manually moved implementation to cpp files using [C-mantic vscode extension.](https://marketplace.visualstudio.com/items?itemName=tdennis4496.cmantic)
keep them as-is, to be honest i'm not sure if build time is reduced at all.
tested using cmake + ninja, compiled without error.
=> Move large functions to `.cpp` files

data/json/items/ammo/40x53mm.json
SUMMARY: Balance "Gave volume to 40x53mm ammo"
Two of the 40x53mm ammo types had volume defined, the other two did not. Additionally, the defined volumes were irrationally small.
Added 260ml volume to 'abstract' section. Deleted the 137ml and 132ml volumes.
Blank thoughts.
Spawned humvee, fired few rounds, seemed to work. Spawned grenade belt to make sure the volume wasn't excessive or anything. It was not.
=> Give 40x53mm ammo volume

data/json/item_actions.json, data/json/items/gunmod/stock.json, data/json/tool_qualities.json, src/game_inventory.cpp, src/game_inventory.h, src/item.cpp, src/item_factory.cpp, src/iuse_actor.cpp, src/iuse_actor.h
SUMMARY: Features "Port over and adjust sawing off of firearm stocks"
This PR aims to implement sawing off stocks, and in the process also simplifies the behavior of stock-modified weapons. The goal here is to set it so, combined with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2315 and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2316, it will be possible to saw off the barrel and stock of a double-barreled shotgun and have it just about fit in an XL holster.
Makes use of some of changes in DDA's implementation of the idea, with some changes.
1. Defined a stock gunmod in json/items/gunmod/stock.json. Unlike the shortened barrel's effects, the actual gameplay effects of the shortened stock are handled purely through the gunmod for visibly, utilizing the same flag as other …
=> Port over sawing off stocks, plus adjustments

data/mods/No_Explosive_Zombies/modinfo.json
SUMMARY: Mods "No Explosive Zombies mod also removes bloated zombies"
- fixes #2391
remove bloated zombie and fungal bloated zombie.
maybe also remove all zeds with `emit_fields`, but that feels too broad.
=> feat: `No Explosive Zombies` also removes bloated zombies

.github/workflows/astyle.yml, .github/workflows/clang-tidy.yml, .github/workflows/json.yml, .github/workflows/label.yml
SUMMARY: Infrastructure "Only run lint workflow when relevent files are modified"
- astyle doesn't needs to be ran on pure json changes.
- style-json doesn't needs to be ran on pure src changes.
add [`paths` filter](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) for lint workflows.
skip build matrix could be skipped for json only changes
=> Only run lint workflow when relevent files are modified

.github/workflows/clang-tidy.yml
SUMMARY: Infrastructure "Add problem matcher for clang-tidy"
Make arcane fails from clang-tidy more managable
- ci: bump ubuntu version
- style: add some newlines
- ci: add problem matcher for clang-tidy
port this PR from DDA: https://github.com/CleverRaven/Cataclysm-DDA/pull/56454
=> Add problem matcher for clang-tidy

.gitattributes
SUMMARY: Infrastructure "Force using LF for text files"
hopefully fixes CRLF-LF issues for windows users.
see https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-Settostringvaluelf
become linux master race
=> use eol=lf for `.gitattributes`

data/json/construction.json, data/json/construction_group.json, data/json/furniture_and_terrain/furniture-appliances.json, data/json/items/vehicle/utilities.json, data/json/vehicleparts/vehicle_parts.json
SUMMARY: Content "Add construction for grid-placed recharging stations, consistency update for vehiclepart battery chargers"
As requested by Chorus System on the BN discord, having grid-placeable recharging stations would be something neat to add. However in the process, it was discovered that the `bonus` value of charger vehicle parts is used in the exact same manner as the `power` value of grid rechargers.
Power values of vehiclepart and grid chargers were found to behave identically, so per feedback basic chargers were tweaked to be consistent across versions.
1. Added furniture definition, construction recipe, and construction namegroup for grid recharging stations. Uses a `power` value of 600, matching the `bonus` value of vehiclepart recharging stations.
2. Per Coolthulhu's …
=> Implement grid recharging stations, battery charger tweak

data/json/itemgroups/Locations_MapExtras/locations.json, data/json/monsterdrops/zombie_technician.json, src/mapgen.cpp
SUMMARY: Balance "Dead bodies in mines use same gear as zombie miner death drops, miner zeds actually have potential loot, sulfur can spawn near lava in mines"
A few of the relatively simple parts of my todo list I was reminded up recently by stuff, while trying and failing to go the fuck to sleep.
1. Set it so the dead bodies that spawn in the mines call `mon_zombie_miner_death_drops` instead of a simple chance of spawning `mine_equipment`.
2. Miner death drops now include a chance (60%, same as the chance bodies would have of calling `mine_equipment`) of spawning an extra item. This is now 50/50 odds of either `mine_equipment` or `mine_materials`, adding a bit more variety to loot and reducing relative odds of getting extra tools or CBMs or the like now that the miners also drop them. …
=> Adjustments to mine and zombie miner item spawns

data/json/furniture_and_terrain/terrain-floors_indoor.json
SUMMARY: Bugfixes "Give junk metal floor a roof"
Was missing its roof. Clearly an oversight as the roof is mentioned in the description and it's part of the indoors file.
t_flat_roof
=> Give junk floors a roof

data/mods/CRT_EXPANSION/items/crt_ammo.json, data/mods/CRT_EXPANSION/items/crt_ammotypes.json, data/mods/CRT_EXPANSION/items/crt_armor.json, data/mods/CRT_EXPANSION/items/crt_gun.json, data/mods/CRT_EXPANSION/items/crt_item_groups.json, data/mods/CRT_EXPANSION/items/crt_recipes.json, data/mods/CRT_EXPANSION/items/crt_tools.json, data/mods/CRT_EXPANSION/scenarios/crt_classes.json
SUMMARY: Mods "Update C.R.I.T. Expansion professions, itemgroups, further rebalances"
Follow-up improvements to C.R.I.T. Expanision mod, fixing and/or rebalancing assorted things spotted along the way.
Profession fixes:
1. C.R.I.T. ROTC Member: SCAR-H now actually starts loaded and with mil-spec ammotype, spare mags start off in their chestrig via defining new contents group `crit_mags_scarh`. Uses `"ammo": 100,` like the other professions so gun now actually starts loaded.
2. C.R.I.T. Janitor: Removed polo shirt since the belt is on the same slot, split off the swiss army knife and belt since that item's a pocket knife without valid holster flags, removed redundant specification of clean water having clean water as its ammotype.
3. C.R.I.T. NCO: Swapped the now-obsoleted kevlar-plated …
=> Further C.R.I.T. Expansion updates

data/json/construction.json, data/json/construction_group.json, data/json/furniture_and_terrain/terrain-floors_indoor.json, data/mods/No_Hope/terrain.json
SUMMARY: Balance "Make all carpets destroyable and easily deconstructable"
Being able to salvage carpets found in different structures to either cut them into rags or lay them elsewhere.
- Got rid of the generic Remove Carpet construction recipe which didn't yield anything, as well as `RUG` flag used by all carpets to utilize said recipe.
- Made all carpets `EASY_DECONSTRUCT`able.
- Deconstructing Red, Purple, Green, and Yellow carpets yields corresponding carpet types and 4 nails. Additionally, Concrete and Bunker carpets return 2 plastic chunks and 2 felt patches correspondingly.
- Made all carpets `bash`-able.
- Made Concrete and Bunker carpets turn into their corresponding terrain type once they're deconstructed/destroyed, unlike Remove Carpet which converted everything to wooden …
=> Make all carpets destroyable and easily deconstructable

data/json/mutations/mutations.json, src/character_turn.cpp, src/debug_menu.cpp, src/debug_menu.h, src/mutation.cpp, src/wish.cpp
SUMMARY: Interface "Allow installing and removing bionics through debug menu"
We already have 3 debug mutations that help with debugging bionics, but they have multiple shortcomings:
1. Are clunky to use
2. Don't allow removing bionics
3. Don't work on NPCs
Add new debug menu entry in Character section that allows installing and removing bionics, as well as editing power level and power cap.
For convenience, power manipulation functions can prompt in both joules and kilojoules.
Delete the clunkier debug mutations.
Leave debug mutations in - someone's bound to try to use them by mistake, and it's not really a mutation you're supposed to have, so I think it's fine to delete them outright. Test saves with that mutation will show a debugmsg on first load, but then they fix themselves.
=> Allow installing and removing bionics through debug menu

src/explosion.cpp, src/options.cpp
Enable Rule of Cool explosions by default
SUMMARY: Content "Enable Rule of Cool explosions by default"
Rule of Cool explosions is useful addition, but it require testing. For the long time we had this option as disabled by default. It is time to feature more public to get more test results. Otherwise we are having a risk to forget about that feature.
1) Create new option called Old explosions that is  to false by default. 
2) Use that option in inverted sate to check if  new explosions is enabled
This way new explosions system will be enabled for all players, but with ability to disable it if needed.
Forget about feature.
1) Observe effect of new options. If true - old explosions system should be used. If false - new explosion system should be used. Default should be false.
Save for quick …
=> Enable Rule of Cool explosions by default

src/ranged.cpp
SUMMARY: Bugfixes "Fix possible segfault caused by #2468 when guns are fired."
Fixes #2512 
#2468 has an apparent issue due to how I structured an if block. Fix that ASAP.
Basically, if the gun doesn't use ammo, it will still try to check the amount of ammo passed by the ammo item_location, which will lead to a null reference that crashes the game.
Restructures it so it doesn't route through ammo.get_item()->count() unless the item actually exists.
Fire A7 laser rifle, it doesn't crash.
I'm an idiot and I should've playtested this a lot fucking more.
=> Fix possible segfault caused by #2468 when guns are fired

src/ranged.cpp
SUMMARY: Bugfixes "Fix more segfault behaviour for turrets."
Fix #2468 causing issues with manually aimed turrets because they don't use the aim_activity_actor, so activity in target_ui leads to a nullptr.
Removes that consideration entirely for turret aiming.
Make turrets route through same aim_activity_actor code.
- One day maybe? Dunno if it's worth it or not.
Need to stand on the location of the turret in the vehicle part and fire it manually.
Probably the worst PR I've screwed up yet.
=> Fix more segfault behaviour for turrets.

src/character.cpp, src/melee.cpp
SUMMARY: Bugfixes "Stop NPCs from using arms to pseudo-block."
#1883 Cancelled the blocking action when NPCs had no arms, but stopped it too late, where `bp_hit` had already been updated to one of the limbs.
As a consequence, NPCs would also always block every single hit to their bodies with their arms even when they should get hit elsewhere.
#2534 is a different take that could still live alongside this one, but may not be necessary, since the solution _should_ make NPCs much less tanky.
Rewrites limb selection so `bp_hit` is only updated when there is a viable limb to block with.
Spawn NPC, get a baton, reduce their arm HP to half and wail on them until limb breaks (checking that we always use the highest HP limb to block when possible)
Check that once arms were broken blocking messages …
=> Stop NPCs from using arms to pseudo-block.

deno.jsonc
SUMMARY: Infrastructure "Add deno typescript support to repository"
[deno](deno.land/) is a cross-platform runtime for running typescript in local environment. some of its benefits:
> **TypeScript out of the box**
> First-class support for TypeScript – no need to spend hours configuring things that break as soon as you update a dependency.
> **Great all-in-one tooling**
> Built in linter, code formatter, ability to build a self-contained executable, test runner, IDE integration, and more.
also, packages are imported from URL, making deno script very portable.
```ts
import { brightGreen } from "https://deno.land/std@0.182.0/fmt/colors.ts"
const world = "World"
console.log(`Hello, ${brightGreen(world)}!`)
```
some examples of deno's benefits in #2544: 
- [fully type safe argument …
=> build: Add deno typescript support to repository

data/mods/No_Fungi/modinfo.json
SUMMARY: Mods "add more monster blacklist for No Fungal Monsters mod"
https://gall.dcinside.com/board/view/?id=rlike&no=437222&page=1
no fungi mod was missing some fungal monsters.
searched and added new fungal monsters to blacklist.
=> fix: add more monster blacklist for fungi

data/mods/No_Rail_Stations/modinfo.json, data/mods/default.json
SUMMARY: Content "Enable No Rail Stations mod by default, tweak description"
Rail stations exist, with rails leading to nowhere.
Disable them by default until something is done to the railroads.
Should require no testing.
=> Enable No Rail Stations mod by default, tweak description

data/json/items/melee/bludgeons.json
SUMMARY: Bugfixes "Nerf nerf bats"
#1709 accidentally made Foam Rubber Bats as powerful as regular bats for less weight.
Set it back to the default bashing damage of 0.
Cry?
An 8 strength character with 0 skill shows the foam rubber bat to have bashing damage of 3 and critical bashing of 6.
=> Nerf nerf bats

data/json/achievements.json, data/json/statistics.json
SUMMARY: Content "Port over achievements with some name changes, add descriptions to them"
Adding more achievements for some major accomplishments, in this case mutation thresholds.
Added achievements and relevant statistic stuff for crossing mutation thresholds. Since we're still using older achievement code I copied the actual JSON from Arcana's threshold achievements instead of DDA's. I used some of the names JByTheWay picked but cooked up new names for others (bird threshold's achievement name being "Look, Ma, I can fly!" is particularly mean-spirited given https://github.com/CleverRaven/Cataclysm-DDA/pull/25582). Also had to write descriptions and decided to think one up for Mycus threshold too. Have them self-hidden to not clutter the achievements screen with a long list of …
=> Mutation threshold achievements

src/inventory.cpp, src/profession.cpp
SUMMARY: Performance "Use move semantics for some items in profession and inventory"
- port https://github.com/CleverRaven/Cataclysm-DDA/pull/55100
- port https://github.com/CleverRaven/Cataclysm-DDA/pull/55127
=> perf: port `std::moving` items

src/game.cpp
SUMMARY: Interface "Allow cancelling waiting with main_menu(ESC) key"
- fix #2128
over 4+ years of cata i wondered why it was not allowed to cancel `wait N hours` activity.
it was only a few weeks ago i found out there was a `pause` keybinding (default: `.`, `5`).
probably there were lots of people like me who instinctively presses ESC to cancel waiting when things get laggy only to find out they don't.
made `game::handle_key_blocking_activity` also check for `main_menu` keybindings for keyboard interruptable activities.
remove `pause` keybinding altogether, but it'd probably have its uses.
waited 3 hours, pressed ESC during waiting and `Confirm: cancel waiting?` prompt popped up.
=> feat: allow cancelling activity with `main_menu(ESC)` key

.github/workflows/pull-translations.yml, .github/workflows/push-translation-template.yml, doc/CONTRIBUTING.ko.md, doc/CONTRIBUTING.md, doc/TRANSLATING.md
SUMMARY: None
Transifex are changing their domain for the web interface
https://help.transifex.com/en/articles/7171815-web-application-s-domain-change
Change `www.` -> `app.`
Bump transifex cli to version that uses the new domain ([1.6.7](https://github.com/transifex/cli/releases/tag/v1.6.7))
=> Update Transifex links in docs, cli version in actions

src/character.cpp
SUMMARY: Infrastructure "Use vector based check for Character::can_use_floor_warmth"
nothing much, just short nitpick on using std::find
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/c3726d99ca2ab500ad6e357dbdc0e7665903eeb8/src/character.cpp#L9183-L9187
define string_view array and std::transform to construct activity_id array, but that's overkill.
=> refactor: use vector based check for `Character::can_use_floor_warmth`

.clang-tidy, data/raw/keybindings.json, src/avatar.cpp, src/avatar.h, src/cata_utility.cpp, src/cata_utility.h, src/character.h, src/debug_menu.cpp, src/enums.h, src/game.cpp, src/game.h, src/gamemode.cpp, src/gamemode.h, src/gamemode_defense.h, src/gamemode_tutorial.h, src/init.cpp, src/main_menu.cpp, src/main_menu.h, src/mapbuffer.cpp, src/mapbuffer.h, src/newcharacter.cpp, src/overmap.cpp, src/player.h, src/savegame_json.cpp, src/scenario.h, src/trait_group.cpp, src/worldfactory.cpp, src/worldfactory.h, tests/map_helpers.cpp
SUMMARY: Interface "Ported DDA title screen update with BN-specific tweaks"
Supporting change for #2451
Title screen controls are a mess, you sometimes scroll with up/down arrows, sometimes with left/right; sometimes you select with up and sometimes with right.
It would be nice to have the controls somewhat consistent.
Main source PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/57764
There were uncountable conflicts, so I had to grab along commits from various PRs that happened to contribute code before/after the change.
Mouse support had to be left out.
Additional changes:
1. Get rid of "Special" tab, merge tutorial and defense mode into "New Game" tab
2. Mute colors a bit, bright white seems too aggressive
3. Increase amount of space reserved for tip of the day by 1 line because …
=> Port DDA title screen update with BN-specific tweaks

.github/workflows/manual-release.yml, .github/workflows/matrix.yml, .github/workflows/release.yml, Makefile, build-scripts/build.sh, doc/COMPILING/COMPILER_SUPPORT.md, doc/COMPILING/COMPILING.md
SUMMARY: Build "Bump images version to latest"
fix regresssion in  https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/4638418360/jobs/8208653611#step:15:78
found out by [@olanti-p](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2525#issuecomment-1500477778)
cherry-pick latest image version from #2341
=> ci(fix): bump images version to latest

tests/translations_test.cpp
SUMMARY: Bugfixes "Missing translation hotfix from #2519"
title text got changed to `Play <N|n>ow!` in #2519. however, other translation files haven't translated them (yet), hence test regression.
test with `<R|r>andom Character` instead
<details><summary>Succeded after changing.</summary>
```
[2/2] Linking CXX executable /home/scarf/repo/cata/Cataclysm/cata_test-tiles
23:17:24.756 INFO : Randomness seeded to: 0
23:17:24.756 INFO : C locale on startup: 'ko_KR.UTF-8'
23:17:24.757 INFO : C++ locale on startup: 'ko_KR.UTF-8'
23:17:24.757 WARNING : Failed to detect system UI language.
23:17:24.757 INFO : Number of render drivers on your system: 3
23:17:24.757 INFO : Render driver: 0/opengl
23:17:24.757 INFO : Render driver: 1/opengles2
23:17:24.757 INFO : Render driver: 2/software
Starting …
```
=> test: missing translation hotfix from #2519

src/lightmap.cpp, src/shadowcasting.h, tests/shadowcasting_test.cpp
SUMMARY: Performance "Optimizations to 2d shadowcasting"
Optimizations for 2d shadowcasting. 2d shadowcasting now supports lookup tables that let it avoid transparency calculations. In practice this means that light and vision now run about 30-40% faster in most situations. 
Two lookup tables are maintained, a constant one for open air and one that changes with the weather. They store a table of distance -> attenuation assuming their constant transparency. When a cast starts the first tile is sampled to see if it's open air or weather to select a table. After that the table will be used until a tile of a different transparency is found. The recursive cast caused by this change will use normal transparency calculations from there on out. So so long as a cast moves through one of open air …
=> 2D shadowcasting optimizations

tests/translations_test.cpp
SUMMARY: Bugfixes "Fix yet another translation fail"
for some reason local po and CI po are different so #2602 was not enough
"Случайный персонаж" to "<R|r> Случайный персонаж"
for some reason local test fails while CI test works
=> test: fix yet another translation fail

data/json/items/robot_parts.json, data/json/uncraft/generic.json
SUMMARY: Balance "Allow uncrafting robot chassis for raw materials, make police/military secubot chassis a source of alloy sheets"
While looking into where else superalloy could be made obtainable in vanilla, I noticed that copbots have a slight chance of dropping an alloy sheet. Deciding to take this idea and run with it, I then noticed that robot chassis were the only leftovers from broken robots you could not salvage for materials.
1. Changed materials of broken copbot chassis to steel and superalloy to hint at being a source of the material. Also updated name and description to reflect that it's also used in military secubots, dispatch, and the like.
2. Changed materials of turret chassis to all-steel, to reflect its uncraft recipe below.
3. Added uncrafts for the three chassis items. …
=> Allow stripping bot chassis for parts, potentially superalloy

src/game.cpp, src/options.cpp
SUMMARY: Interface "Prompt player to return to main menu on character death"
port https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/9 by Night-Pryanik  
[output.webm](https://user-images.githubusercontent.com/54838975/230632032-0f129eb4-d555-4573-ae11-8a2318e8b66e.webm)
turned the option on, attempted suicide and returned to main menu. the save was not removed.
=> feat: prompt player to return to main menu on character death

src/options.cpp
SUMMARY: Interface "Change interface to use SI units as the default"
give a small nudge to use SI units by setting it to be default.
- metric system is the global standard for measurement
- help players from countries outside US
- existing users wouldn't have to modify settings (probably)
changed defaults as following:
| Unit | Before | After |
|--------|--------|--------|
| temperature | fahrenheit | celsius |
| speed | mph | km/h |
| mass | lbs | kg |
| distance | imperial | metric | 
port over DDA's 
- https://github.com/CleverRaven/Cataclysm-DDA/pull/58779
- https://github.com/CleverRaven/Cataclysm-DDA/pull/58784
- https://github.com/CleverRaven/Cataclysm-DDA/pull/58789
after build, checked on settings and new defaults were correct.
blocked by #2517 until 2023-04-08 12:00:00 UTC+09:00
=> feat: use SI units as the default option

data/json/recipes/food/brew.json
**Summary**
SUMMARY: Balance "Allows rehydrated fruit in the fruit wine must recipe"
**Purpose of change**
Allows the fruit wine must recipe to use rehydrated fruit. This is common in real life as dried and frozen fruit both work, but all recipes I have found online recommend you rehydrate fruit beforehand. The overall sugar content does not change from dehydration, instead the water content being removed concentrates the existing sugars. This means the overall fermentation wouldn't really change. In-game this lets you preserve fruits in summer during harvest, and do your brewing in winter, and adds more value to dehydrating over just freezing everything. 
After a few google searches I came to my conclusion on the realism part. These two links I found via searching "can dehydrated …
=> Rehydrated fruit for fruit wine must recipe

.github/workflows/matrix.yml, Makefile
SUMMARY: None
Trying to enable OSX CI tests for #2216
Enable test stage
Waiting for CI
=> Run tests on OSX in CI

data/json/npcs/TALK_COMMON_MISSION.json
SUMMARY: Bugfixes "Fix dialogue saying goodbye but still using TALK_NONE"
Fixed an annoyance in NPC dialogue I keep forgetting to fix.
Set it so selecting "I'll get back to it, bye!" when asked about an active mission correctly calls `TALK_DONE`  instead of `TALK_NONE` because there's already an option to dismiss the mission prompt and go to the NPC's normal dialogue.
Putting the laptop away and actually trying to get some sleep.
Double-checked that I hit `D` instead of any of the other letters on my keyboard, and that I'm actually in the response where the PC says goodbye to the NPC in question. It's a one letter change.
DDA's got the same issue: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/npcs/common_chat/TALK_COMMON_MISSION.json#L146
=> Fix an incorrect use of TALK_NONE instead of TALK_DONE in mission dialogue

src/character.cpp, src/character.h, src/character_display.cpp, src/character_turn.cpp, src/creature.cpp, src/creature.h, src/monster.cpp
SUMMARY: Bugfixes "Fix weird speed buff/penalty stacking. Add Speed Mult. Update Character display for speed."
Fixes #2620.
Issue is that in `recalc_speed_bonus` the math is wrong because it's trying it's damnedest to use `set_speed_bonus` for `mod_speed_bonus()`
It also does this weird thing where it multiplies the current speed by the multiplier then modifies the speed bonus, which looks weird to me and may have weird behaviour down the line as we've already seen.
Character display for speed is somewhat inconsistent, and assumes Quick is the only mutation that modifies player speed.
Swap to `mod_speed_bonus()` so we don't need to do more than basic math.
Add speed_mult that is used where appropriate.
Reorganize character display so it supports translation and also accounts for more …
=> Fix weird speed buff/penalty stacking. Add Speed Mult. Update Character display for speed.

src/activity_handlers.cpp, src/iuse_actor.cpp
SUMMARY: Bugfixes "Spellcasting tools no longer waste charges if you cancel out and don't actually cast the spell"
So, working on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2617 revealed to me exactly what's needed to fix the "spellcasting items always consume charges, even if you back out of the spell aim menu or if it's interrupted" bug.
1. In activity_handlers.cpp, changed `activity_handlers::spellcasting_finish` to have a check at the end for if the activity was assigned an item target, and if so checking whether the item has `USE_PLAYER_ENERGY` (since if it does, energy draw is already handled by the spell menu stuff). If the flag is absent, then call up `charges_to_use` like normal. Based off the finisher functions as seen with jackhammering and shearing.
2. In …
=> Fix spellcasting items consuming charges when canceled

src/handle_action.cpp, src/panels.cpp
SUMMARY: Bugfixes "Spellcasting menu cancels out early if all spells out of energy, don't show max mana unless you actually know a mana-casting spell"
This fixes two bits of weirdness with spellcasting and associated UI.
1. In handle_action.cpp, changed `cast_spell` so that the "check if you're too out of energy to cast any spells" check to properly return out of the function instead of continuing, fixing the issue where it would say "you can't cast any of the spells you know" but still open to a menu of currently-uncastable spells.
2. In panels.cpp, changed `spell_panel` to check the player's known spells for any mana-casting spells to determine if it returns true. This fixes it so that mana and max mana only shows on your sidebar if one of your spells actually costs mana.
I'm not 100% …
=> Touchups to spellcasting behavior and UI
