- data/json/items/ammo/atgm.json
- data/json/items/ammo/cannon.json
Yet more tinkering with damage balance of superheavy ammunition. In this case, I was once again off tinkering with Tankmod: Revived when I double-checked the ATGM and realized that, not only is its damage still barely a step above handheld rocket launchers despite being vastly more rare and vehicle-only, the blackpowder cannons deal much more damage and are craftable.
1. Swapped the base damage values of ATGM and explosive shells, those being 250 and 450.
2. Adjusted round shot accordingly, and toned arpen values down to be more in line with blackpowder ammo.
3. Exploding cannon shells also now get `EXPLOSIVE_BIG` instead of having both `EXPLOSIVE` plus `FRAG`.
Unending screaming at ammo balance.
I crave the true ultimate weapon:
> feat(balance): swap damage bracket of ATGM and blackpowder cannon so civil war guns don't kill tanks better than a TOW

- data/json/mapgen/nested/residential_personal_items.json
increase variety in res_personal_items nested container in houses. 
add 13 more variants that will spawn in people's bedrooms/closets/etc. 
linted and tested in game
Clothing Rack - dresses
Clothing Rack - Mascot costume
Clothing rack - Clown costume
Clothing Rack - competitive fencer
box of fishing gear
Clothing Rack - Historical Reenactor
Bookshelf (changed from box as in picture) - Horror Novel collection
Box of LARPer gear
Bookshelf - Esotericist - Rare Books
Box of RPG stuff - Dungeonmaster
Box of boardgames
> feat(content): more res_personal_items chunks

- data/json/monster_factions.json
Zombies had a habit of ignoring things that were trying to kill them aside from the player, this was because they were set to be passive (no matter the circumstances) against the following factions: small_animal, insect, and fish. 
Modifies the neutral option so they are still initially peaceful against the categories above, but will fight back if the animals start to attack them (I'm looking at you, wasps and bees). Also modified the associated allied zombie aquatic fishes (which had the same feelings as normal zombies toward other wildlife). They still maintain their neutral position towards nether creatures, which I think is in the lore *somewhere*. Fixes #4554.
Spawned a zombie and one of each class of animal. Noticed the zombie started to fight back when attacked.
> fix(content): Make zombies fight most things when angry

- data/json/items/ammo.json
Tinder appeared to be able to be burned for a LOT longer than a fuel briquette. This was because it was set to use the 'wood' material instead of the 'dry_plant' material, which burned a lot better.
Changed it to dry_plant. Fixes #4673.
Buffing fuel briquettes to wood, but this should be better reflected in weight / volume changes instead. It appears to burn for around 10~ish minutes already, but this can be tweaked in a different PR if required.
> fix(content): Make tinder made of dry plant instead of wood.

- src/activity_handlers.cpp
This fixes an issue that I overlooked when implementing https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4890, where if a fireplace/brazier/etc already had fuel in it it would completely skip calling `try_fuel_fire`, and thus never get the chance to check for much-needed tinder to use.
In activity_handlers.cpp, set `activity_handlers::start_fire_do_turn` so that the if function that calls `try_fuel_fire` also triggers if the tool being used has the `RERQUIRES_TINDER` flag, if the location also lacks valid tinder already. Also moves the definition of `firestarter` a bit earlier in the function since it's being checked for earlier.
screm
2. Placed a plank in a brazier, then more planks and tinder in a firewood source.
3. Tried lighting it with a fire drill, …
> fix: fire drills also grab tinder from firewood sources if target location already has fuel in it

- data/json/monster_factions.json
This fixes a mistake made in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4898, nether monsters were already neutral towards zombies but that PR forced them to infight.
Restored zombie factions viewing nether monsters as neutral.
Thing is, while it's perhaps reasonable that zombies chase after all other living things, nether monsters explicitly are not meant to be fighting with zombies right now. Main reason is gameplay-wise, I intend to make more use of nether monsters as a way to escalate things later in the game, making a threat that feral survivors in the affected scenario can't ignore, etc. Main thing delaying me there is I want to tie that escalation to the endgame so that completing it will cause those added spawns to start dying off.
Lore-wise, main thinking is nether …
> fix: zombies and nether monsters are chill again

- data/json/mapgen/map_extras/corpses.json
- data/json/overmap/map_extras.json
This converts another couple of the old hardcorded map extras to use nested chunk spawns instead.
1. Set `mx_military` and `mx_science` to use `update_mapgen` as their generation method instead of `map_extra_function`
2. Defined nested chunks for the above to use. The science one was the simplest, spawning a scattered number of subchunks that randomly pick between picking a dead scientist or a monster spawn, then some bonus nether spawns and a chance to spawn an item from group `rare` at 50% chance (up slightly from 45%). Main changes are the max number of corpse checks were set to 2-6 instead of 2-5, 1-3 nether spawns instead of 0-3 as did with college spawns, and the "spawn a zombie instead of a corpse" function now varies the spawn results a bit to include occasional labsec zeds or …
> refactor: JSONize `mx_military` and `mx_science`

- data/json/itemgroups/Locations_MapExtras/map_extras.json
- data/json/mapgen/map_extras/corpses.json
- data/json/overmap/map_extras.json
And now this JSONizes the last major corpse spawn map extra, the drug dealer one.
1. Converted `mx_drugdeal` from the `map_extra_function` method to `update_mapgen`.
2. Defined the mapgen update for drug deals. As before, this roughly mimics the dead bodies with blood spawning in trials to imply a shootout, along with nether monsters. As before, 1-3 nether monsters now instead of 0-3. The orientation of bodies and the blood trails also work a lil different from the hardcoded version. In addition, instead of only ever sometimes replacing dead bodies on one side with smokers and dead bodies on the other with spitters, it now can replace any dead body spawn with a slightly wider variety of zeds at a flat 10% rate per corpse.
3. Added a bonus call to a random pick of either `baddrugs` or …
> refactor: JSONize drug deal map extra

- src/newcharacter.cpp
- src/player.h
- fixes #4625
Scent was a field in both the player and character class, leading to mishaps where the game updates the character scent field but uses the player scent field for calculations.
Remove player scent field so that when referenced it will always go to the character scent field.
- Keep player scent field instead.
- Rejected as player class is slated to be merged with character class eventually.
One of these days we need to continue the work olanti started merging player and character properly.
> fix: Remove scent from player class

- src/activity_actor.cpp
- src/character.h
- src/game.cpp
- src/melee.cpp
- src/player.h
- src/ranged.cpp
- Updates #2786, moving `last_target` and `last_target_pos` into Character class and removing unnecessary `as_player()` conversions.
Remove from Player class, move into Character class, reformat code to remove `as_player()` conversions for both.
- Keep as is.
- Rejected. Continuing work to merge Player class into Character class.
> fix: Move `last_target` and `last_target_pos` into `Character` class

- data/json/recipes/ammo/components.json
- data/json/recipes/armor/head.json
- data/json/recipes/other/materials.json
- data/json/recipes/other/other.json
- data/json/recipes/other/traps.json
- data/json/recipes/weapon/cutting.json
- data/json/recipes/weapon/mods.json
- data/json/recipes/weapon/ranged.json
- data/json/requirements/materials.json
- data/mods/Magiclysm/recipes/magic_tools.json
This rebalances the use of bone glue vs superglue, and tweaks a few recipes that use adhesives and superglue.
1. Defined `adhesive_proper` crafting quality, for recipes where superglue or bone glue are reasonable but tape shouldn't be allowed. In addition, it now uses 2 bone glue per 1 superglue, making superglue properly more efficient and fixing the oddity where making superglue from 20 bones offered no benefit when bone glue only needed 10 bones for the same number of charges.
2. Reworked `adhesive` and `nail_glue` to use `adhesive_proper` inside them in place of superglue or bone glue.
3. Updated makeshift macuahuitl recipe to require hammering and cutting quality since you're likely having to shape the rocks into blades and set them in the edges of the club, implemented use of …
> feat(balance): define crafting quality for superglue and bone glue, adjustments to relevant recipes

- src/cata_utility.cpp
Thanks to Oren, he very quickly found a fix for a weird issue with radios causing the game to crash, a simple DDA port.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4920
In cata_utility.cpp, ported changes to `obscure_message` that should make radios not crash the game.
screm
1. Compile-tested.
2. Load-tested the following save provided below.
3. Turned the radio on and scanned it.
4. Waited 30 minutes, no crashes.
5. Scanned again, repeated wait test with no crashes.
6. Repeated tests in the 0/0 overmap chunk.
[Snowmass Village.zip](https://github.com/user-attachments/files/16063046/Snowmass.Village.zip)
Source PR: `Bugfix: Prevent segfault when listening to radio msgs`, by @inogenous: https://github.com/CleverRaven/Cataclysm-DDA/pull/68142
> fix(port): Prevent segfault when listening to radio msgs

- src/char_validity_check.cpp
- src/worldfactory.cpp
- tests/char_validity_check_test.cpp
This ports another character entry fix Kenan requested I grab that the accessibility PRs overlooked.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4816
C++ changes:
1. In char_validity_check.cpp, ported addition to `is_char_allowed` to make it support `char` being negative for signed unicode shenanigan purposes.
2. In worldfactory.cpp, ported over saner error-checking of unicode characters and error printing for `worldfactory::valid_worldname`.
Test changes:
1. Updated char_validity_test.cpp with the check that the source PR also removed.
1. Waiting until I get home to do this and hope I don't get distracted by shit again.
2. Bullying Kenan into doing it instead. :3
1. Compiled-tested.
2. Per source PR, named a world `テスト`.
3. Was able to start a game in that world, save, …
> fix: port over saner unicode handling for worldnames

- data/json/mapgen/nested/roof_nested.json
Currently, rooftops offer a little bit of safety early game, and that's pretty much it.  When you climb up in order to escape hordes or to move around towns/cities undetected you're pretty much guaranteed that nothing super interesting is going to happen. I think roofs can be a little more interesting than that. I don't think there should always be something up there, but there should at least be a passing chance of something useful, interesting or just dangerous to happen. 
Added a few new entries to my already created "roof nested chunk container" entry I've been adding to some houses. I've added two potential enemy encounters (there aren't many enemies that make sense on a roof) and a few potential loot drops (ditto). There's not enough here to make people want to actively seek out or …
> feat(content): more residential roof chunks

- src/iexamine.cpp
Fixes #4446. Verify by attempting to fertilize any planted crop, which would previously cause a seg fault and crash the game.
I believe this was caused by the order of the code in iexamine::fertilize_plant. I'm skipping some of the steps, but the relevant ones were in this order before: get a pointer to the seed item being fertilized -> spawn fertilizer item on that tile (so it can only be fertilized once) -> use seed pointer to format a game message with the proper plant name. I think that spawning the fertilizer would invalidate the seed pointer and cause the seg fault when trying to get its name. I just changed the order so that the fertilizer is spawned before we use the iterator to get the seed pointer.
Still new to C++ so this was the only solution I could come up with. I'm more …
> fix: fixes crash when fertilizing crops

- data/json/construction.json
- data/json/furniture_and_terrain/furniture-domestic_plants.json
- data/json/items/comestibles/mushroom.json
- data/json/items/comestibles/seed.json
- data/json/recipes/food/seeds.json
Some needed followups to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4927 to sanity-check some things.
1. Added the `dirtmound` examine action to mushroom racks. Turns out it works fine here because it lacks the `PLANTABLE` flag, and thus it'll correctly only allow you to plant shrooms on it.
2. Bumped default `charges` of mushrooms up, 10 for regular shrooms and 6 for morels, as this it seems was the intent behind the accidental change to dried mushrooms in said PR. Now farming is actually worth it.
3. Made mushroom culture consistent, both now give culture as seeds and used the standard default growth rate instead of the much bigger values that were given (back to same values spores had). Also reworked description to give a clearer idea of what these items actually are and how …
> feat(balance): sanity-check and rebalance mushroom farming, culture is easier to make, mushroom racks can be planted on via examine

- src/char_validity_check.cpp
- src/input.cpp
- src/input.h
- src/string_editor_window.cpp
- src/string_input_popup.cpp
- src/string_input_popup.h
- src/worldfactory.cpp
- tests/char_validity_check_test.cpp
- Related to #4713.
- Revert #4918 (for the modifications to `is_char_allowed()` were better at silencing errors than catching true issues) update the game so that we now have a way to feed the string input popup printable, file/foldername safe characters only through `ANY_PRINTABLE` (name subject to change)
- Hopefully resolve #4816 (Hopefully because I don't know how to even produce the error, so maybe someone like scarf can test it) If it does, please link it back to this PR as fixed by, thank you.
~~Use new input context `ANY_PRINTABLE` that acts like `ANY_INPUT` except when it comes to text output. It prevents non-printable and non-file/folder name safe characters from being printed into textboxes to prevent world names from being impossible to save.~~
Give `query_string()` another …
> fix: Sanity check worldname at input instead of confirmation

- data/json/flags.json
- data/json/items/comestibles/seed.json
- doc/src/content/docs/en/mod/json/reference/json_flags.md
- src/activity_handlers.h
- src/activity_item_handling.cpp
- src/flag.cpp
- src/flag.h
- src/iexamine.cpp
- src/vehicle.cpp
- src/vehicle_part.cpp
- src/weather.cpp
This continues the follow-ups from the mushroom overhaul by adding support for planting stuff underground, and allowing you to grow shrooms underground. This WAS going to also close the exploit of being able to grow anything underground if you provide heating but I was talked into hacking my way around leaving the loophole in, so mushrooms mainly benefit from not having to set up a space heater or build near lava to work underground.
C++ changes:
1. In activity_item_handling.cpp and activity_handlers.h, added separate handling of planting seeds while farming to `can_do_activity_there` and `generic_multi_activity_check_requirement`, where seeds no longer consider it too cold to plant if the target location is underground, and instead trigger `do_activity_reason::NEEDS_ABOVE_GROUND` as a …
> feat: can now plant mushrooms underground

- data/json/recipes/ammo/arrows.json
- data/json/recipes/ammo/other.json
- data/json/recipes/armor/arms.json
- data/json/recipes/armor/feet.json
- data/json/recipes/armor/hands.json
- data/json/recipes/armor/head.json
- data/json/recipes/armor/legs.json
- data/json/recipes/armor/other.json
- data/json/recipes/armor/suit.json
- data/json/recipes/armor/torso.json
- data/json/recipes/other/containers.json
- data/json/recipes/other/vehicles.json
- data/json/recipes/weapon/cutting.json
- data/json/recipes/weapon/magazines.json
- data/json/recipes/weapon/piercing.json
- data/json/recipes/weapon/ranged.json
- data/json/requirements/toolsets.json
This implements some general rebalancing and fleshing out of 3D printing recipes.
1. Converted tool use of 3D printers, and plastic component use, into a standard tool quality for all relevant recipes to use. Printers should now be more efficient compared to using a hotplate to melt and shape plastic.
2. In the process, converted recipes to use amounts of plastic generally equal to the weight of the end item rounded up to the nearest multiple of five chunks, except for the recipes directly equivalent to a specific plastic mold recipe, and except for items that now include some extra materials in the recipe. Time requirements also now lean towards 1 minute per plastic chunk used, again except for recipes note das deliberate exceptions.
3. Speaking of, carbon fiber arrows now use the same …
> feat(balance): standardize current 3D printing recipes

- .github/pull_request_template.md
many forget to remove optional section in checklist and it's a visual clutter.
comment out  that section.
pester github why we don't have PR forms like [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
> chore: hide optional checklist by default in PR template

- CMakeLists.txt
- doc/src/content/docs/en/dev/guides/tracy.md
It was not possible to build tracy because [while it used older commit `GIT_SHALLOW` was also set to true.](https://discord.com/channels/830879262763909202/830916451517857894/1257792450190245938)
please check individual commits.
> build: fix tracy builds

- src/CMakeLists.txt
- tests/ranged_aiming_test.cpp
suppress these annoying false positives.
- fixes #3989
- ranged aiming test: completely commented out the entire section because it seems to be a false positive
- tmpnam: added `LUA_USE_LINUX` or `LUA_USE_MACOSX` flag on cmake builds.
also do makefile, but for now only fixing cmake because 1) we plan to remove makefile 2) we don't do lua build with makefile
will have to check CI output
> test: suppress ranged and lua warnings

- doc/src/content/docs/en/dev/guides/building/cmake.md
While it can generally be expected that anyone doing c++ changes to the game presumably can also handle finding the relevant packages on their own, this will save future contributors time and annoyance tracking down a few of the ones with package names dissimilar to those found in the instructions.
Adds the relevant command to install all the packages listed as required in the 'Building with CMake' section on Fedora-based distributions of Linux.
- Leave it for someone else to do
- Let it be an introductory ritual for anyone contributing on Linux to find the packages themselves
The command does indeed install the packages without errors, as tested by me.
I was thinking about doing the command for Debian-based distros as well, but looking into the maw of the beast that is Debian's package …
> docs: Add Fedora package installation instructions for CMake builds

- .github/workflows/documentation.yml
[prevent documentation deployment from failing](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/9832860878) due to  [`ERR_INVALID_THIS` error](https://github.com/pnpm/action-setup/issues/135)
bump `withastro/action`  to v2 in which bumps [pnpm/action-setup](https://github.com/withastro/action/blob/v2.0.1/action.yml#L60) internally
escape the node ecosystem (it can be done but needs some time)
haven't. has to be tested on CI.
> ci: bump `withastro/action` to v2

- data/json/item_actions.json
- data/json/items/tool_armor.json
- src/item_factory.cpp
- src/iuse.cpp
- src/iuse.h
Combat armor was hardcoded with a unique use action. It was shown on the Discord to eat 5 charges when being disabled, but not when being enabled. This will convert it to a JSON use action, which will fix the combat armor. However, I don't know if the hardcoded use action is the culprit or if it's an issue with JSON inheritance (That's a lot of fancy code, too bad I can't read it), so this needs further investigation by someone actually competent with C++
Delete every reference to the now-orphaned C++, and converts the combat armor to JSON
Making Kheir do it. Keeping this use action for flavor purposes but making Kheir fix it.
This should work right out of the box given it's a fully functioning JSON use action we use in a lot of other items, and since code is only being removed. That …
> refactor: Obsolete Combat Armor hardcoded iuse

- data/json/items/comestibles/med.json
- data/json/items/generic.json
- data/json/recipes/chem/drugs.json
Raw tobaccos cant be dried without player crafting, that makes thing much slower. Chewing tobacco is also uncraftable, despite its recipe videos are all around and not much complex
Add SMOKABLE flag to raw tobacco, add recipe for chewing tobacco and replace "mint flavored" in description into "fruit flavored" because recipe uses fruit.
Keep uncraftable chewing tobaccos
Local JSON edits
Midst of writing json, i had to clean my bag from tobacco remains. A rechargable battery accidentaly dropped from balcony while i was trying to shake off tobacco dust. Does that mean i will do a PR about rechargable batteries in future?
> feat(content): add chewing tobacco recipe, edit chewing tobacco description and make raw tobacco dryable by smoke rack

- data/json/items/items_holiday.json
- data/json/items/tool/electronics.json
- data/json/items/tool/fire.json
- data/json/items/tool/lighting.json
- data/json/items/tool/misc.json
- data/json/items/tool_armor.json
- data/mods/Aftershock/items/tool_armor.json
- data/mods/Aftershock/items/weapons.json
- data/mods/CRT_EXPANSION/items/crt_toolarmor.json
- data/mods/CrazyCataclysm/crazy_items.json
- data/mods/Magiclysm/items/enchanted_misc.json
- data/mods/No_Hope/Items/tools.json
- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/character.cpp
- src/iuse_actor.cpp
- src/iuse_actor.h
- fixes #4966 which was due to https://github.com/CleverRaven/Cataclysm-DDA/pull/16061 8 years ago.
`transform_charges` defines charges used when an item successfully transforms.
Shuffled code in character.cpp to fix issue where items that are called to consume charges without a `charges_per_use` field are consumed themselves. Now it also checks if the item has charges available at all as well.
- Leaving it alone.
- Honestly a thing I would have considered were it not for some of the panic in the Discord. Main use case for this is to prevent the ability to turn on an item, and benefit until charges are consumed later. Now many items with charge usage less than 1 charge per turn will use a charge when turning on, which was an edge case exploit at best in my opinion, but I'm already here …
> fix: Add `transform_charges` so that transform `iuse_actors` can use charges on transform again.

- doc/src/content/docs/en/dev/guides/building/cmake.md
It generally helps to have a c++ compiler when compiling c++ code, and as demonstrated by my own use, it's not safe to assume that someone running the script would have one already.
Adds gcc-c++, the c++ compiler for gcc, to the install script for Fedora-based distros.
- Provide Clang instead
Personal preference / taste really, but I figured I might as well use the gcc c++ compiler given I've already put gcc in the script.
- Add an instruction telling people to grab either gcc-c++ or clang instead
Open to the idea, but felt like just keeping it in one script was nicer.
CMake does indeed recognize gcc-c++ after installing it as a valid CXX compiler.
Thanks to Scarf for their help with my CMake issue earlier
> docs: Add gcc-c++ to Fedora install script

- .github/workflows/matrix.yml
- .github/workflows/release.yml
- Makefile
- build-scripts/SDL2-devel-2.26.2-mingw.tar.gz.sha256
- build-scripts/gha_compile_only.sh
- build-scripts/requirements.sh
Once every few months we get someone in the Discord that can't run the Mac version of the game. One solved it by downloading a library that was missing. I looked for libvorbis on the DDA side and it seems using SDL2 means this might solve the missing library problem. I discussed with @scarf005 and it was okay to attempt ports of DDA's relevant PR's and letting the build process on the PR run to see what happens, as none of us run a Mac and a lot of us don't understand the build process code. There are two relevant ports I found. One that will switch to SDL2 on Mac builds, and another that I think is required due to Git blaming some of the required SDL2 library links.
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2309
Refer primarily to …
> build: port related DDA MacOS build changes

- doc/src/content/docs/en/dev/guides/building/cmake.md
continuation of #4957, #4971
list fedora packages required to build BN tiles.
was able to locally build on fedora 40 docker with following command:
```
sudo dnf install git cmake ninja-build mold clang17 ccache \
SDL2-devel SDL2_image-devel SDL2_ttf-devel SDL2_mixer-devel \
freetype glibc bzip2 zlib-ng libvorbis ncurses gettext flac-devel
mkdir -p build
cmake \
-B build-fedora \
-G Ninja \
-DCATA_CCACHE=ON \
-DCMAKE_C_COMPILER=clang-17 \
-DCMAKE_CXX_COMPILER=clang++-17 \
-DCMAKE_INSTALL_PREFIX=$HOME/.local/share \
-DJSON_FORMAT=ON \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCURSES=OFF \
-DTILES=ON \
-DSOUND=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DCATA_CLANG_TIDY_PLUGIN=OFF \
-DLUA=ON \
-DBACKTRACE=ON \
-DLINKER=mold \
-DUSE_XDG_DIR=ON \
-DUSE_HOME_DIR=OFF \
-DUSE_PREFIX_DATA_DIR=OFF \ …
```
> docs: fix required fedora packages

- data/json/recipes/electronic/tools.json
- data/json/recipes/other/tools.json
- data/json/requirements/electronics.json
- data/json/requirements/toolsets.json
This aims to give players a few more options to make crafting a soldering iron less restrictive, along with some related fixes and updates. In particular, this sets electric irons back to being the default tool mentioned when viewing what an item needs to uncraft it, something that had been bugging me a bit.
1. Reordered soldering irons in the `soldering_standard` crafting requirement so they show up as the most obvious tool to use for disassembling items, with `add_grid_connection` reordered for consistency too.
2. Added spikes as a potential alternative to nails or wire for both soldering recipes, opening up an additional potential material option for the soldering tip.
3. Added heating element as a potential alternative to electronic scrap and glow plugs as an alternative component in …
> feat(balance): add more component options to soldering iron recipes, related tweaks

- data/json/itemgroups/Locations_MapExtras/locations_commercial.json
- data/json/mapgen/homeimprovement.json
- data/json/mapgen/homeimprovement_superstore.json
- data/json/mapgen/homeimprovement_superstore_new.json
- data/json/mapgen/s_furniture.json
I noticed that space heaters don't actually spawn anywhere, and likewise I didn't give AC window unit items any store spawns since the player could just loot them from houses instead. Decided to fix that, and in the process provide a reason for the player to hit up furniture and home improvement stores, two store types I normally overlook due to being inferior to hardware stores.
1. Defined itemgroup `home_improvement_housewares`, containing a broad mix of tools and appliances that fit the general idea of household items that might be generally lumped under "housewares" on store shelves. Also means a place for space heaters and AC units to actually spawn.
2. Set aside some shelf space in home improvement stores for the new itemgroup, additionally fixing it trying to spawn rugs in the …
> feat(balance): add houseware spawns for ACs, space heaters, etc to home improvement and furniture stores

- Makefile
- build-data/osx/Cataclysm.sh
- build-scripts/windist.ps1
- cataclysm-launcher
- deno.jsonc
- doc/src/content/docs/en/dev/guides/building/cygwin.md
- doc/src/content/docs/en/dev/guides/building/makefile.md
- doc/src/content/docs/en/dev/guides/building/msys.md
- doc/src/content/docs/en/dev/guides/building/vs_cmake.md
- msvc-full-features/Cataclysm-vcpkg-static.vcxproj
- scripts/gen_cli_docs.ts
- src/CMakeLists.txt
- src/debug.cpp
- tests/CMakeLists.txt
- tools/windows_limit_memory.py
Apps detecting games, such as Discord considers this game as Cataclysm DDA as they both has same exe name. So i added -bn to this fork, giving a way to differ.
Replaced cataclysm-tiles with cataclysm-bn-tiles and replaced cataclysm on cmake files with cataclysm-bn. 
Look deeply on game detecting apps and make them recognize CBN by just from window name, not the executable one.
MSYS2 tiled version showed bn name both on console and task manager. Additional OS and curses tests are welcome.
Should help with #3497.
Discord saying it gets game data from https://www.igdb.com/ , as Discord-recognized CDDA has its own page on it: https://www.igdb.com/games/cataclysm-dark-days-ahead .
We need to do some off site work for recognition.
> build: change executable name into "cataclysm-bn-tiles"

- .github/workflows/release.yml
As discovered by the user known as milky in the Discord, RoyalFox accidentally removed LUA from the cmake command for mac. This means that it didn't support LUA in the built version, and in general resulted in various errors regarding LUA.
Adds back `LUA=1` to the CMake command for MacOS
Wait for Chaosvolt to do it
I don't own a mac, so testing is limited to github test builds
Experimental build on my fork of the repo
I'm pretty sure this will work even without testing
> build: Restore LUA to MacOS

- .github/workflows/release.yml
fix generation of empty release note on daily release when yesterday had no release (this is because in that case nonexistant tag is passed to fromTag)
1. compare with tag of last release, not from the day before.
2. always create/update releases so release note can be updated when manually ran.
remove usage of YESTERDAY_TAG_NAME completely? head foggy so not sure if it'd work
- ran https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/9950837172/job/27489346015 
- it correctly updated previously empty release note of https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/2024-07-15
- existing release assets were kept intact.
> ci: fix no release note on day after no commit

- .gitignore
This fixes the issue where, due to renaming what the exe is when compiled, compiling in VS2019 would cause file changes that should be ignored in gitingore instead.
Added the new manifest file to .gitignore.
screm
Saw that the file change it keeps trying to put in my PRs is automatically absent from listed file changes.
> fix: add `cataclysm-bn-tiles.exe.manifest` to .gitignore

- data/json/mapgen/city_blocks/urban_7_house_garden.json
Replace urban_7_house_garden outdoor terrain with regional terrain.
Override some of the terrain.
Add a mailbox somewhere, given that almost every house has one.
none
Before:
After:
> fix: replace urban_7_house_garden outdoor terrain with regional terrain

- data/json/items/ranged/crossbows.json
As helpfully pointed out by Hegamonia on the Discord, the normal crossbow's mod slots and the compound crossbow's mod slots seemed completely the wrong way around. I agreed with this, because holy hell is how it was wacky.
Swaps the slots for gun mods that the crossbow and compound crossbow have.
- Leave the normal crossbow alone and just give its superior mod slots to the compound crossbow
Also valid
I swapped pretty much a single line of JSON around, if it breaks I will be very concerned.
https://tenor.com/view/threatening-sergei-kravinoff-aaron-taylor-johnson-kraven-the-hunter-holding-a-crossbow-gif-10776485014161891611
> feat(balance): Swap mod locations for compound and normal crossbows

- data/json/mapgen/city_blocks/urban_8_house_brick_garden.json
Replace urban_8_house_brick_garden outdoor terrain with regional terrain.
Override some of the terrain for now, standard_domestic_palette and the other house palette will be slapped here later.
Add a mailbox somewhere, given that almost every house has one.
none
Before:
After:
> fix: replace urban_8_house_brick_garden outdoor terrain with regional terrain

- data/json/construction.json
- data/json/furniture_and_terrain/terrain-floors-indoor.json
- data/json/furniture_and_terrain/terrain-floors-outdoors.json
- doc/src/content/docs/en/mod/json/reference/json_flags.md
After some confusion in the BN server I eventually figured out that you can't use the "extract clay" construction on the mounds of clay found in landscaping stores, because the constructions in question were only checking for a specific terrain ID, and it was different from the one used in the store.
JSON changes:
1. Converted the extract clay, extract sand, and extract bog iron constructions from using `pre_terrain` to `pre_flags`, defining an appropriate flag for each: `SOURCE_CLAY`, `SOURCE_SAND`, and `SOURCE_IRON`.
2. Added the `SOURCE_CLAY` flag to clay floors and clay mounds, both indoors and outdoors.
3. Added the `SOURCE_SAND` flag to indoor and outdoor sand terrain.
4. Added the `SOURCE_IRON` flag to bog iron.
5. Converted the clay and sand mounds to turn into dirt when bashed, …
> fix: `extract clay` and related constructions can now target mounds and underground terrain

- src/activity_handlers.cpp
- src/activity_item_handling.cpp
- src/iuse.cpp
I'd been meaning to finally update mining activities, so that their fake exertion penalties actually scale with time taken. This also tweaks it so the time requirements are a bit more consistent all around, and strength impacts all three types a bit more sanely.
1. In activity_handlers.cpp, standardized the rate of needs gain for `activity_handlers::burrow_finish`, `activity_handlers::pickaxe_finish`, and `activity_handlers::jackhammer_finish`. They now all use the same rate derived from how long the action takes to compete, so crafting helpers and strength directly impact each the same rate. In addition, the pain infliction has been removed since no other activity forces this sort of thing on you.
2. In iuse.cpp, updated the logic for calculating moves for burrowing, pickaxe use, and …
> feat(balance): standardize time taken by mining tools, needs gain scales with time taken, remove pain penalties

- src/map_extras.cpp
I did not particularly like the hackery I put together for mapgen craters back when I started adding explosive cratering effects.
In map_extras.cpp, changed `mx_crater` to no longer haphazardly destroy a single patch of terrain and then convert any deep pits it finds to shallow pits.
Instead, it defines two sizes of blast radius, for an outer and inner crater layer. Instead of resorting to `map::destroy` (which goes way too hard for multi-step destruction like this), it calls `map::bash` with comparable strength, one for each size of radius defined, so it generates a crater that looks a bit more like an authentic crater generated by explosives.
A bonus side effect of this is the max radius of the crater as a whole has gone up from 2-6 tiles to 5-8, in order to give the epicenter some …
> feat: rework crater map extra, increased crater size and properly carves out an epicenter like explosives do

- data/json/furniture_and_terrain/terrain-floors-indoor.json
- data/json/furniture_and_terrain/terrain-floors-outdoors.json
- data/json/itemgroups/misc.json
- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/iuse.cpp
- src/mapdata.cpp
- src/mapdata.h
This fixes up a thing @EkarusRyndren reminded me about, where "so lemme just dig in this clay by the river with a shovel aw fuck it just gave me soil" serves as a common newbie trap.
C++ changes:
1. In iuse.cpp, converted `dig_pit_moves_and_byproducts` to also grab the position being dug in, and uses that to determine what itemgroup it spawns on digging via grabbing the terrain there and checking a newly-defined JSON property, `digging_result`.
2. In mapdata.cpp and .h, defined `digging_result` as a property of terrain JSON, which defaults to the original hardcoded `digging_soil_loam_50L`.
JSON changes:
2. Defined two new itemgroups, `digging_clay_50L` and `digging_sand_50L`. These resemble `digging_soil_loam_50L` except 10% of the soil volume is set aside for a guaranteed spawn of a …
> feat: JSON byproducts generated by digging pits, digging in sand and clay produces reasonable amounts of expected product

- .github/workflows/manual-release.yml
- .github/workflows/release.yml
Following a change made in the process of getting mac builds to work appropriately by RoyalFox, non-MSVC Windows builds were not building. Naturally, this fixes it so that they build again (even though MSVC is generally preferred, it's nice to have a backup in case MSVC ever goes wonky)
Bumps the version of Ubuntu used to build the non-MSVC Windows releases to 22.04 instead of 20.04.
Also changes package request to python3 instead of python (Technically grabbing python3 is redundant given it already ships with 22.04 in the first place, but a bit of extra redundancy won't hurt there)
- Let these versions rot on the vine
- Upgrade to 24.04 instead
"Bleeding edge" is not always desirable, plus it could come with the dreaded too high of a gcc version.
Manual release on personal fork, it …
> build: Fix non-MSVC windows builds

- data/json/mapgen/recycle_center.json
Use regional terrain for recycling centres.
Also, fix the style.
none
Before:
After:
> fix: use regional terrain for recycling centres

- src/iexamine.cpp
Minor tweak to make backing out of an accidental examination of a ledge less annoying.
Set it so the "you decided to step back from the ledge" message that appears when you cancel out of examining a ledge is printed as a regular message, not a popup that completely interrupts you. You already had to get past a prompt to select whether to jump or climb down, and if the chosen action was dangerous you'd get a yes/no prompt too, so not need to be so dramatic about informing the player they changed their mind about (accidentally, 99% of the time) submitting to the siren song of the ledge.
screm
2. Went up to the roof, examined the ledge, and backed out of the menu.
3. No more popup informing me of my cancellation, instead left as a message.
Second late-night C++ …
> fix(UI): stepping back from ledge prints a message instead of an extra popup

- src/activity_handlers.cpp
This fixes a weird issue in which taking water from filthy canteens dropped by zombie soldiers behaves differently depending on whether you chose to unload the filthy canteen vs reloading your canteen. Unloading the filthy container works just fine and doesn't make the receiving container filthy, but the reload method does.
In activity_handlers.cpp, set `activity_handlers::reload_finish` so that the definition of `ammo_is_filthy`, used for contaminating objects loaded with filthy ammo, ignores containers so that filthy canteens and the like don't contaminate the receiving container with contents that can be proven non-filthy if you use the unload method instead.
Removing filthiness entirely because @Coolthulhu keeps saying he intends to one of these days.
2. …
> fix: reloading liquid out of a filthy canteen no longer contaminates the receiving container, consistent with refilling it via unload

- data/json/mapgen/city_blocks/urban_40_house.json
Replace urban_40_house outdoor terrain with regional terrain.
Override some of the terrain.
Add a mailbox somewhere, given that almost every house has one.
none
Before:
After:
> fix: replace urban_40_house outdoor terrain with regional terrain

- data/json/professions.json
- data/json/scenarios.json
A few modernization updates to professions, changes for the sake of variety, and the like.
1. Stashed the loose magazines on security guard profession in a leg pouch.
2. For the sake of variety, swapped the police detective's basic .357 619 for a .44 629. Mixing the detective movie references a bit by having a film noir style outfit with the model made famous by Dirty Harry, but it seems fitting for a throwback profession not at all dressed like a modern police detective to mix their references a bit. Also gives them a pouch for speedloaders, and swapped the holster for a shoulder holster.
3. Set the archeologist profession up with a speedloader pouch with some of the .38 ammo shifted to it.
4. Gave hitman profession a Walther .45 PPQ with a supressor and ergonomic grip, basically mashing …
> feat(balance): item updates to various professions, add a new profession, updates to scenario profession lists

- data/json/items/melee/bludgeons.json
As noted by Phoenix in the Discord, ironshod quarterstaff was not properly inheriting any flags extended onto the base quarterstaff. This fixes that by using json inheritance instead of overwriting the flags just to add nonconductive.
Uses `"extend":` to add the NONCONDUCTIVE flag to the ironshod quarterstaff instead of having it overwrite the flags inherited from the base quarterstaff
Have people continue to need to specify that their changes are meant to apply to both the ironshod and the normal quarterstaff
None
Shock staff correctly just lets inheritance do the work by inheriting from ironshod, so no need to worry about that one.
There are probably other examples of situations like this in the JSON just waiting to be discovered
> refactor: use extends instead of overwrite on Ironshod Quarterstaff

- data/json/mapgen/sports_store.json
Use regional terrain for sporting goods store.
none
Before:
After:
> fix: use regional terrain for sporting goods store

- data/json/mapgen/office_doctor.json
Change the `fill_ter` of the mapgen `office_doctor_2` because it seems to be unused and also because it places dirt under the swivel chairs.
Use "t_floor" instead of "t_dirt" for the "fill_ter".
none
Before:
After:
> fix: change the `fill_ter` of the mapgen `office_doctor_2`

- data/json/flags.json
- data/json/items/comestibles/carnivore.json
- data/json/npcs/missiondef.json
- data/json/npcs/refugee_center/surface_staff/NPC_old_guard_doctor.json
- doc/src/content/docs/en/mod/json/reference/json_flags.md
- src/computer_session.cpp
- src/flag.cpp
- src/flag.h
- src/item.cpp
- src/iuse.cpp
- tests/item_type_name_test.cpp
This aims to make it so that the same blood taken from a zombie will work for the "analyze zombie blood" whether it's taken via blood draw kit or from harvesting, instead of the same corpse yielding different types of blood.
C++ changes:
1. In computer_session.cpp, reworked how `computer_session::action_blood_anal` works. Now instead of the weird old behavior of saving the monster type of the offending blood and only checking for a specific item ID of blood, it accepts any valid item with the `IS_BLOOD` item flag, and triggers the "uh oh, zombies!" alert the mission is looking for if the item it's fed has the `POISON` use action used by tainted blood. Afterwards it can still print the flavor messages for human blood and generic animal blood if it didn't find the poison action. Also …
> fix: make blood draw kit and harvesting blood more consistent, centrifuge now looks for tainted blood

- src/character_display.cpp
- src/melee.cpp
In a shellnut:
Basically follows up on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4160 by picking the alternative balancing method that came up in the PR as a potential option.
1. In melee.cpp, set `Character::roll_bash_damage` so that the bonus damage granted by skill is no longer restricted to pure empty-handed combat, but in exchange it's now only 1x unarmed skill instead of 2x unarmed skill.
2. In character_display.cpp, changed `character_display::display_empty_handed_base_damage` so that it defines `empty_hand_base_damage` as equal to unarmed skill instead of double unarmed skill.
Adding the bonus arpen that came up as a potential option to make up for the damage nerf. Actually having any bonus unarmed damage with skill is already more than what DDA does last I checked, so. …
> feat(balance): reduce unarmed skill bonus damage, but allow it to affect unarmed weapons

- .github/workflows/matrix.yml
Been noticing that build matrix wasn't running. turns out [broken indentation borked the whole workflow from running](https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/10086721419).
fix the indentation
should run in CI.
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4970/files#diff-ad27b48237ca3d400ad6724d82df1ba3293e68054182a87a0aa219df064d6f52R177-R183
hecc, it was broken for 2 weeks.
> ci: fix broken matrix.yml indentation

- Makefile
- src/character_preview.cpp
- src/newcharacter.cpp
- tests/Makefile
- fix matrix (again)
- turns out i've made an logic error in #5065 so without this fix curses selection will be borked
- rename stuff
- fix tiles macro
purge makefile
- it still fails but fails less
pls merge
> build: try fix curses build again

- data/json/construction.json
- data/json/construction_group.json
- src/construction.cpp
This makes it a bit easier to wrangle bodies for burial, having noticed that coffins are pretty intensive in terms of wood required.
C++ changes:
1. In construction.cpp, changed `construct::done_grave` so that the furniture destruction part of it only triggers if furniture on the targeted tile has the `SEALED` flag (used by sealed coffins but in theory will apply to any burial constructions players may mod in). In addition it halves the morale bonus from performing a burial without valid furniture to target, as a balance for the below JSON change.
JSON changes:
1. Defined a shallow grave construction option, which lets you build a grave directly over a shallow pit. Triggers the `done_grave` special as indicated above. So now it's possible to bury your NPC friends for flavor but putting on …
> feat: add construction for shallow graves not requiring a coffin

- data/json/recipes/other/tools.json
@Lamandus pointed out the autolearn levels for the retorts are a lil all over the place in a way that can make them hard to actually autolearn within a reasonable timeframe, and I realized a simple universal +1 over the recipe skills is more reasonable to achieve since the biggest roadblock is typically hitting cooking 5.
Set copper and clay retorts to autolearn at fabrication 4, cooking 4, and survival 3 since those are all 1 level higher than the recipe's actual skills, instead of being a mishmash of same level, +1 skill, and +2 skill.
Screaming.
1. Checked affected file for syntanx and lint errors.
2. Load-tested in compiled test build to ensure this doesn't make the autolearn code scream.
> feat(balance): set autolearn skills for retorts consitently 1 level higher than recipe levels

- data/json/mapgen/shooting_range.json
Fix misplaced items in the shooting range.
Change { "chance": 25, "item": "office", "x": 3, "y": 4 } to { "chance": 25, "item": "office", "x": 4, "y": 3 }
none
Briefcase on the desk, so correct now.
> fix: misplaced items in the shooting range

- doc/src/content/docs/en/mod/json/reference/creatures/monsters.md
The previous docs were incorrect regarding how to add and remove entries. Additionally, "delete" works slightly differently with special attacks compared to how one might expect based on how "extend"s work.
Updates the docs, with examples of proper JSON code
Just remove the outdated parts, and let people continue to suffer when trying to use "delete".
I have confirmed that the game considers my examples for "extend" and "delete" valid.
In the process of doing this, I have discovered how misinformed the Limit Fungal Growth mod is and how it's not using "delete" correctly, but rather overwriting the inherited special attacks anyway. Expect a future PR to remedy its shortcomings.
> docs: Update Special Attacks docs

- src/character_preview.cpp
- src/character_preview.h
- fixes #5080
- More clearing after exiting traits tab.
None.
Works locally.
None.
> fix(UI): character preview side effects bug fix

- .github/semantic.yml
- data/mods/rural_biome/modinfo.json
- doc/src/assets/semantic.json
Rural mapgen is a DDA-era mod by Erk that we've inherited, it contains a single regional map settings overwrite. It's been unmaintained for the time I've been in the project as I previously had to fix the mapgen settings due to things like burdock spawning and bog iron not spawning. It was also largely replaced by our version of innawoods mod by Zlor in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4224 I'm flagging it as obsolete but keeping it in the repo to ensure anyone can work on it and re-enable it if they want to still run it.
I replaced obsolete false with obsolete true. I also removed it from Semantics.
Deleting it, as you're likely forced to re-create the regional map settings file from scratch just to save the mod due to all the changes we've been doing.
It's gone.
I …
> feat(mods/ruralbiome): Obsolete rural mapgen mod

- .github/workflows/autofix.yml
diff of typescript lint and `semantic.yml` update script was ignored by `autofix.ci` because it ran after autofix ran in #5103. prevent this from happening
move autofix to the bottom.
only move semantic update script before autofix since tests don't edit files, but that wouldn't save more than few seconds.
will check on CI
> ci: run typescript test before autofix

- .github/semantic.yml
- data/mods/Monster_Girls/categories.json
- data/mods/Monster_Girls/migration.json
- data/mods/Monster_Girls/modinfo.json
- data/mods/Monster_Girls/mutagens.json
- data/mods/Monster_Girls/recipes.json
- data/mods/Monster_Girls/thresh_mutation.json
- data/mods/Monster_Girls/vanilla_mutations.json
- doc/src/assets/semantic.json
- scripts/monster_girls_mutations/mutation-conversion.py
- scripts/monster_girls_mutations/threshConverter.py
(Added this checklist just in case, the mod does appropriately use migrations)
A wide variety of players may be dissatisfied with the vanilla mutation categories (I, personally, am one of them). They may have been wanting their survivor to turn into a more anime-like catgirl, rather than a character from the 2019 movie *Cats*. This mod aims to satisfy them, and make mutations good again.
- Replaces many of the vanilla mutation categories with new, much more pleasant, monster girl mutation categories
- Uses `"delete"` to remove all the mutations from the vanilla categories
- Creates new monster girl mutation categories
- Uses `"extend"` to add the mutations to their relevant monster girl categories (after personally going through the mutations by hand to decide what was kept)
- Adds …
> feat(mods/Monster_Girls): Add a mod for Monster Girl mutations

- src/iuse_actor.cpp
When I was doing #4968 there was a comment that remained from the time I was thinking of more convoluted solutions.
Removes the comment line.
Leaving it alone and laughing maniacally when someone looks at it in confusion several months down the line
If a comment removal ends up breaking the game I will exile myself from the project in shame and horror.
> fix: Update now unneeded comment

- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/ranged.cpp
`drop` field for ammo drops the item as a full stack instead of a single item as is the norm for `dont_recover_one_in` which it is "complementary" to.
Neither of the two are documented either which is _great_.
Fixed the way `drop` spawns so that it will actually drop only a single item instead of a full stack for anything that is `count_by_charges`.
Adds documentation because why the hell isn't this documented?
- Leaving it alone until I refactor it.
- Great idea, if only I could pull time for it.
This whole system is cursed as shit and needs refactoring when I have time.
> fix: `drop` only drops one item

- data/json/mapgen/power_station_small.json
Turn the small power substation so that the entrance is on the road side.
Add "rotation": 2 for the mapgen `pwr_sub_s`, `pwr_sub_s_roof`
none
Before:
After:
The entrance is on the road side.
> fix: turn the small power substation so that the entrance faces the road

- data/json/items/bionics.json
Terrain memory is infinite in Bright Nights. This description is wrong.
Removes mention of terrain memory in this CBM.
Let players be confused because its funny.
the tests
My lawyer advised me to say the alternatives considered is a joke.
> fix: update memory banks CBM description

- data/json/mutations/mutations.json
Fixes #5123
Make Prime Dex and Prime Int require and build-in Very Dexterous and Very Intelligent, so a character with 8 baseline stats ends up with 14 stats across the board.
Making Prime Strength and Prime Perception require and build-in the +1 version of the stat mutations instead, making a 8 stat baseline character end up with 13 stats across the board instead of 14.
Made the JSON changes on my install and checked to be sure it worked properly.
> fix: Prime stat weirdness #5123

- data/json/overmap/overmap_special/specials.json
Change the road connection of the `Wasp Tower` so that it is identical to its non-wasp-infested counterpart.
Change a number in specials.json
none
Before:
After:
> fix: Wasp Tower uses the same road connection as Radio Tower

- data/json/items/armor/ammo_pouch.json
There are two leg magazine storage items, the pouch and the satchel. The pouch allows 2 magazines up to 0.5L in size, the satchel is identical other than allowing 2 magazines or ammo belts up to 1.25L in size and is therefore strictly better. The description says the satchel only allows one magazine/ammo belt and this should actually be the case for balance reasons.
Delete the line of JSON that allows two magazines.
Increasing the encumbrance of the leg magazine satchel, but this would probably allow for too much ammo to be easily carried.
Tested the JSON changes on my end to be sure they worked properly.
> feat: balance fix for leg magazine satchel allowing 2 ammo belts or large magazines

- data/json/mapgen/farm_dairy.json
- data/json/mapgen_palettes/farm_dairy.json
Use regional terrain for the dairy farm.
Remove the "fill_ter" of `dairy_farm_NW`, `dairy_farm_NE` because it's unused.
Set the status of the bike that can be placed in the farm to -1.
Fix the waterless toilet.
none
Before:
After:
> fix: use regional terrain for the dairy farm

- data/json/mapgen/farm.json
Put dirt floor under the gun safes on the farm.
Put in terrain "ü": "t_dirtfloor" for the mapgen `farm_2` and all its variants.
none
Before:
After:
> fix: put dirt floor under the gun safes on the farm

- data/json/mapgen/s_gun.json
Use regional terrain for `s_gun` (gun store).
Also, put concrete floor under the reinforced vending machine and the targets.
none
Before:
After:
> fix: use regional terrain for `s_gun` (gun store)

- data/json/items/comestibles/nuts.json
This fixes hickory nut ambrosia being about 4 times as dense as it's expected to be. A quick glance at the recipe showed that the issue was that `charges` divides its volume into 4.
The expected fix WOULD be to just divide weight by 4, but...it takes 10 charges of water in addition to nuts, sweetener,and milk while outputting 10 charges, so the ACTUAL answer is it clearly needs a stack size defined, derp.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5114
Added `stack_size` value of 1 to hickory nut ambrosia.
1. Screaming because I was this fucking close to going the "divide weight by 4" before I thought to actually check what the recipe implies.
2. Making the recipe less watered down. I dunno what the intended proportions are for this blursed nut pilk, since this is a …
> fix: correct `stack_size` of hickory nut ambrosia to make sense with recipe requirements

- data/json/mutations/mutations.json
- data/mods/Monster_Girls/vanilla_mutations.json
Added Strong Back to Cattle and Ursine categories and Optimist to Mouse and Rat categories.
Currently there's no way to mutate away Bad Back or Bad Temper. If you start with them then there's no way at all to get rid of them aside from getting lucky with completely random mutation, and if you get them from mutagen then getting rid of them requires using purifier. Bad Back in particular is very awkward to work around and with the amount of mutagen lines that give you strength, I'd think a few of them would also strengthen your back.
Add Strong Back to Cattle and Ursine categories and Optimist to Mouse and Rat. Cattle and Ursine want Strong Back the most because they cramp up in vehicles and it's thematically appropriate. Mouse and Rat seem the most appropriate for Optimist to me given that …
> feat(balance): Add Strong Back to Cattle and Ursine and Optimist to Mouse and Rat categories

- .gitignore
make it easier to test multiple cmake builds without polluting git
> chore: add `build.*` path to gitignore

- .github/workflows/matrix.yml
fixes #5081
turn off macos matrix tests  (i know it's workaround)
actually fix the mac builds but it may take longer than expected and until then the tests will constantly fail due to mac test which is confusing when reviewing
> ci: disable mac matrix test

- data/json/items/melee/unarmed_weapons.json
Added BELT_CLIP tag to all unarmed weapons that aren't sheathable.
Allow unarmed weapons that don't have blades or edged parts to be as quickly wielded as those that do.
Add the BELT_CLIP tag to all the unarmed weapons that don't have SHEATHE_KNIFE.
Continue to take 130 moves to wield my impact knuckles from the inventory.
Completely rework unarmed weapons to be worn on the hands and add damage to your base unarmed attacks so you can drop your gun and "wield" them in 0 moves.
Made the JSON changes on my end and made sure they worked.
> feat(balance): Allow belt clipping of unsheathable unarmed weapons

- doc/src/content/docs/en/mod/json/reference/json_flags.md
- src/creature.cpp
- src/monster.cpp
- src/monster.h
Monsters don't require a separate function specifically for them, as the standard `Creature::deal_damage_handle_type` already handles monster immunities within it. `monster::deal_damage_handle_type` also usually routes into the above function after it is done, making it redundant, skipping over it as the `PLASTIC` flag used to do means that damage is disproportionately reduced at higher skill levels or when using techniques, as both are never accounted for in the monster function.
The only unique bit is the `PLASTIC` flag, which has been merged into the Creature function. Documentation has also been updated to explain _what_ exactly the flag even does.
Deleted `monster::deal_damage_handle_type` entirely from the code. Added the only special consideration `PLASTIC` into the Creature …
> refactor: Merges `deal_damage_handle_type` together.

- data/json/mapgen/nested/basement_nested.json
Fix misplaced items in `room_10x10_junk_N` and `room_10x10_junk_S`
Change the position where "bikeshop_tools" is placed in the two nested mapgen.
none
Before:
Since the items are placed on a wall, they end up outside the room.
After:
> fix: change the position of misplaced items in `room_10x10_junk_N` and `room_10x10_junk_S`

- data/json/mutations/mutations.json
- tests/mutation_test.cpp
Feline and Lupine have both Ugly/Deformed and Pretty/Beautiful in their mutation categories, so often instead of advancing other mutations they will swap back and forth between Pretty and Ugly and waste your mutagen.
Pick either being pretty or being ugly. I picked pretty.
Cat and Dog mutants could be ugly instead, but we've got a bunch of ugly mutants and not a lot of pretty ones.
> feat: remove Ugly/Deformed from Feline/Lupine mutation path

- data/json/martialarts_fictional.json
- data/json/techniques.json
- data/mods/MMA/techniques.json
When PR #4516 happened a few rapid strike techniques got missed. This brings them consistent with the rest. See previous PR for justifications, this just ensures all are consistent. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5169
I fixed all instances in mainline and MMA mod. I did not touch CRIT, it does its own thing with movecost and scaling damage so it was never inline with the rest of the game and this is not a balance PR.
question life
this is fine
> fix: all rapid strike techniques are consistent with PR 4516

- doc/src/content/docs/en/mod/json/reference/creatures/martialart_json.md
I was working on martial arts and got annoyed that ninjutsu had fields that aren't listed in the docs. I fixed it.
I scoured the martial art code for declared JSON that wasn't listed in the docs and put it in
Complain
you can't make me test docs.
>:(
> docs: add missing martial art fields

- data/json/regional_map_settings.json
Burdock is a fully implemented plant with a number of recipes and is farmable. It wasn't spawning ever. This just lets it spawn in the region data once again. I prefer not to obsolete stuff people might like, and it sits on similar terms with dandelions so if we're going to audit what crops should exist, they all need an audit.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4065
Changes region data to make it spawn similar to dandelions.
obsolete it.
should be fine
> fix: let burdock spawn again

- data/json/monsters/zed_fusion.json
Welcome to Arby's, we've got the meat. Except right now we don't. Our flesh walls are made of air and customers aren't happy.
changes the harvest from exempt to zombie because its flagged as zombie and is a zed_fusion like a dissoluted devourer which is also a zombie harvest entry
Going to Wendy's.
github tests for my one json line change
Drain the blood, cure and slice the flesh, season and fry the potatoes, feed them the sugar water. Be born. Toil. Die. Arby's, we sell food.
> fix: flesh walls are actually made of meat

- src/activity_actor.cpp
- src/activity_item_handling.cpp
- src/consumption.cpp
- src/crafting.cpp
- src/inventory.cpp
- src/item.cpp
- src/pickup.cpp
"What're ya gonna do if I nick yer stuff, shoot me again?"
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5156
1. In activity_actor.cpp, updated `move_items_activity_actor::do_turn` so that moving items will also glom onto items not owned by you if they faction that owns them would attack you on sight, letting you haul drops from dead bandits or other hostiles.
2. In activity_item_handling.cpp, updated `activity_on_turn_move_loot` and `find_auto_consume` to disregard faction ownership of items if the faction in question hates your guts, for more item movement related purposes and for auto-eat zones.
3. In consumption.cpp, `query_consume_ownership` no longer checks thief mode if you're eating a hostile faction's lunch.
4. Likewise in crafting.cpp, `prompt_disassemble_in_seq` …
> feat: don't query the player about stealing from hostile factions, npcs trying to kill you won't stop mid-fight to complain about theft

- data/json/npcs/talk_tags.json
Most/all NPC's have a chance of using male pronouns when you're playing a woman. This is not an ideal solution because we would ideally allow checking gender in the dialogue snippets, however that's a code refactor I can't do. These snippets can be added back later.
Removes amigo, lad, and bruv. Amigo is Spanish and a male gendered word, the female equivalent would be Amiga. Lad is also male gendered and the equivalent would be lass. Bruv is slang for brother.
Dude can stay, because that's just non-gendered stoner slang from my real life experiences.
Gendered dialogue checks so we can have more. This can be closed/reverted if someone is going to work on those checks.
yes
The lumberjack camp in-game is rude.
> feat: stop misgendering players in name_g dialogue snippets

- src/activity_handlers.cpp
- src/avatar_action.cpp
- src/avatar_functions.cpp
- src/bionics.cpp
- src/character.cpp
- src/explosion.cpp
- src/handle_action.cpp
- src/iexamine.cpp
- src/item.cpp
- src/item.h
- src/iuse.cpp
- src/iuse_actor.cpp
- src/magic_enchantment.cpp
- src/map.cpp
- src/map.h
- src/monattack.cpp
- src/mondeath.cpp
- src/newcharacter.cpp
- src/npc.cpp
- src/npcmove.cpp
- src/ranged.cpp
- src/savegame_json.cpp
- src/vehicle.cpp
- src/vehicle.h
- src/vehicle_part.cpp
- tests/active_item_cache_test.cpp
Code handling `active` field for items is very haphazard. `active` by itself also doesn't guarantee processing, only processing for items in a character's inventory. Items on the submap, or in the cargo section of a vehicle, must be added to the active processing list for both in order for them to function.
This makes the code open to pitfalls in the future for any use actions that may want to activate an item, as much of the codebase uses `active = true` rather than proper standardized functions.
Makes the `active` field private, so that it will not be otherwise accessed and won't be seen as the appropriate method to set an item as active. `_active()` is now the function used to check if an item is set as active or not.
`activate()` now activates items and calls `make_active()`, it …
> refactor: Privatize active field. standardize functions for activating, deactivating and reverting items

- data/json/monsters/reptile_amphibian.json
Sewage Gators had a no infect chance of 2, which guaranteed they would infect you. In the future infection attacks should be redone but this is good enough. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4667 As I noted, 66% of sources of bite infection are animals and not zombies, it is not a zombie infection but we could always add a deadlier zombie infection later if it's desired.
Sets no infection chance to 17 for about 50% chance. It may not be a rotting corpse but it's swimming in sewage and has a stronger bite.
buffing it, because it lives in the sewers. Adding sepsis or other illnesses.
we do that?
That's how you get sepsis.
> fix: sewage gators no longer have a near-guaranteed infection from bites

- data/json/flags.json
The flag already exists, it just wasn't defined. This causes errors with any mods that use it. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4261
Defines the flag.
cry about it
bot
aaaaaaa
> fix: define JSON flag for BIO_IMMUNE

- data/json/construction_group.json
- data/json/furniture_and_terrain/terrain-floors-indoor.json
- data/json/furniture_and_terrain/terrain-walls.json
Walls and floors confuse people in the construction menu. They're made of wood but aren't descriptive enough in their name. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5111
Actually label floors as wooden floors instead of "floor" and walls as plastered wooden walls.
Make it worse (im kidding)
bot
you have a sudden realization floors are made of floor.
> fix: label wooden walls and floors better

- data/json/overmap/overmap_special/specials.json
- data/json/scenarios.json
This aims to make crazy party scenario less likely to break.
Hopefully fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5015
1. Made the city size and distance ranges of private resort overmap special a bit less restrictive, and upped unique spawn chance from 35% to 50%.
2. Flagged Crazy Party as `CITY_START`, as the minimum city size of its associated overmap special is above zero.
1. Wrapping this starting location in with a fitting generic scenario and removing the associated scenario.
2. Allowing private resorts to spawn in city-size-zero worlds too.
3. Letting you spawn in mansions as an alternative starting location?
3. Spawned in the scenario a few times in a default world, no …
> fix: private resort spawns made a bit less restrictive, crazy party scenario marked as `CITY_START`

- src/iexamine.cpp
Fix #3710
In iexamine.cpp, fixed `iexamine::fvat_full` to not treat the liquid handling as an if statement, and instead just have it do the expected "print message about emptying the vat and convert it to an empty vat" code directly after liquid handling, instead checking to see if the full vat is now empty. This makes it no longer error due to liquid handling never triggering the effect it's supposed to even if you drain the last of that liquid.
screm
2. Set up a fermenting vat and let it brew up a gallon of vinegar.
3. Tested taking a sip of vinegar from the still-full vat, then also partially draining it into a smaller container. No odd behavior.
4. Emptied the rest into the gallon jug the unfermented vinegar came in, the "last drops" message correctly …
> fix: fermenting vat no longer errors due to not converting when emptied

- src/consumption.cpp
- src/item.cpp
- tests/iteminfo_test.cpp
This aims to fix the lag spike that hovering over food recipes with giant component lists generate.
1. In consumption.cpp, `Character::compute_nutrient_range` has been set to only run calculations on components for a recipe if the player actually has said components available for crafting, so iterating over a gigantic list of potential components should lag the game less unless the player actually has everything the recipe allows. It also returns early with the item's average value if the player can't craft that item at all, to prevent the "only regard component we have" from telling the player an item they can't craft only has zero calories. If it did that, the player would have no way of knowing the calorie value might actually be above zero and they'd potentially assume the item isn't …
> perf: combat lag spikes from recipes with large component lists, calorie range now respects what ingredients you actually possess

- src/magic.cpp
When attempting to learn a spell (from a spellbook) that has a class associated with it, the warning about closing off an opposing class would show up even when there was no closing off of another class (and the relevant spot would appear blank). This did not look good, and could be confusing for users.
This PR adds a check for if the spell class cancels mutations, and only shows the prompt if it does.
- Leave it be
- Continue weh'ing eternally
Built and tested locally on my machine. It still shows the prompt when it should, and doesn't show it when it shouldn't.
Using Magiclysm as an example, you can see that it still shows up as expected
Meanwhile, you just learn the spell in Magical Nights (and thus indeed doesn't show up)
Woohoo, c++ PR! This was mostly an issue affecting Magical …
> fix: Add check to class-limitation warning on learning spells

- data/json/mapgen/fema/FEMA_te_03.json
Replace the wooden floor under the sandbags outside `FEMA_te` armory variant with dirt.
Add "N": "t_region_soil" in the mapgen terrain.
none
Before:
After:
> fix: replace the wooden floor under the sandbags with dirt in `FEMA_te` (FEMA camp)

- src/character.cpp
- fixes #5222 which is caused by a mutation setting your HP down to 0, `recalc_hp` actually has a caveat to make it minimum 1 for max hp, but does it too late so the max_hp_ratio ends up being 0, which multiplies your current max and makes it 0 too.
~~Uses the `std::max` function earlier in the code so that max HP will actually remain correct. This will drop you to a minimum of 1 HP due to new current being a ceiling function.~~
Reworks function to use the current ratio of health to max health to decide new current health values, this should in theory be more robust as it doesn't use any values that aren't set in stone.
- Having it max out only in character creation
- Would solve immediate problem but also cause HP to flatline if you gain a mutation of that nature in game. This solution …
> fix: rework `recalc_hp()`

- doc/src/content/docs/en/dev/guides/building/cmake.md
Ubuntu-based distros represent a fairly large chunk of Linux users, and smoother package installation is better.
Creates a script with package-parity to the currently existing Fedora example as best I can. **HOWEVER!** this means that, due to the use of clang-17 as a package, the script currently only works on the most recent release of Ubuntu (24.04). Hence the notice in the docs. Due to the nature of Ubuntu's releases being LTS, it's not as much of a guarantee that users will be on the latest one compared to Fedora's fairly cutting edge behavior.
- Leave out clang and instead use g++ since 24.04 appears to still ship with g++ 13.
This would be a GREAT solution, but it'd break package parity with the Fedora script (unless I also updated that to use gcc-13 now that that package has a …
> docs: Add Ubuntu package installation script

- src/item.cpp
- src/iuse.cpp
- fix #5225, fix #5221.
- Updates #5188 
- Deactivate required the item to have tooldata originally due to it's purpose in reverting items, removed that requirement.
- Bionic scanner relied on deactivate to revert the item to it's original off state, added revert to the code.
> fix: Fix `deactivate()`, add revert to `iuse::note_bionic()`

- data/json/mapgen/nested/fema_nested.json
Put dirt under the tent chairs in the nested mapgen `fema_mess_hall`.
Dirt under the chairs.
none
Before:
After:
> fix: put dirt under the tent chairs in `fema_mess_hall`

- data/json/furniture_and_terrain/furniture-storage.json
- src/activity_actor.cpp
- src/iexamine.cpp
Follows up on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5217 by coding in support for waving a halligan bar at all three types of safes, not just one of them.
C++ changes:
1. In iexamine.cpp, changed `iexamine::safe` and `iexamine::gunsafe_el` and so that it's now able to check for prying data too. If the player has a good enough prying tool then, like with locked gun safes, it will prioritize prying if standing, hacking/safecracking if crouching, and skip over trying to pry in favor of the sneaky action if you examine it while standing when you lack a good enough prying tool to attempt it.
2. Moved `find_best_prying_tool` and `apply_prying_tool` up a bit as they're static functions now being called for a bit earlier in the file than they previously were.
3. Misc: in …
> feat(balance): support use of prying on other types of safe

- data/mods/Monster_Girls/recipes.json
The crafting recipes had no requirements because `copy-from` did not grab components properly.
Yoinks the crafting components my self for the recipes.
- Create custom recipes
I'd like to, but Later(tm)
Tested locally, it works and gives the correct requirements
My first instance of `copy-from` failing me, woooo
> fix(mods/Monster_Girls): Fix crafting recipes for monstergirl mutagens

- data/json/furniture_and_terrain/terrain-walls.json
Reinforced glass was described as weaker than other types of walls. Technically it's correct but that doesn't make it right. A lot of walls are stronger and weaker than it. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5239
New description. Won't confuse people as to where it stands.
none
aaaaaaaaaaaaaaaaaa
Some research on this topic.
https://www.youtube.com/watch?v=xLV2Nd77lmY
https://www.youtube.com/shorts/37q4VRSW458
> fix: make reinforced glass description less confusing

- data/json/items/comestibles/dairy.json
When https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4113 ported Nonperishable overhaul the spoil time for ghee was deleted, but it copies from butter. It was meant to not spoil in that PR, this overwrites it to not spoil.
Spoils in is set to 0 days
None
Tests.
Not a day goes by when I don't hate copy-from.
> fix: stop ghee from spoiling as fast as butter

- data/json/items/comestibles/fruit_dishes.json
- data/json/recipes/food/drinks.json
- data/json/recipes/food/veggi.json
- data/json/requirements/cooking_components.json
Cooked fruit lets you avoid using sugar, but canning it doesn't. Jam allows you to use sugar to can your fruit, but IRL canned fruit can be preserved without extra sugar. This makes it easier for a player to can their fruits without relying on high level cooking recipes to create sustainable sugar. This does however lower calories from the canned fruit, because you will not be adding sugar.
Michigan State University confirms sugar isn't relevant for preservation of the food itself, but it will lose color and texture.
https://www.canr.msu.edu/news/home_canning_without_sugar
Changed the recipe and description a little bit. I'm also forced to change comestible value for canned fruit which will soft nerf food spawns, in the future I can see about converting those to canned jam spawns.
Well I …
> feat(balance): remove sugar in canned fruit recipe

- data/raw/keybindings/keybindings.json
We constantly get players confused about auto-travel mode (the one where your character tries to avoid high-movecost terrain automatically, not fast travel) because it's very easy to hit the default key for it, being right between the key for your map and the "wait a turn" key for when your hand isn't already near the numpad at the moment.
Set the default bind for "toggle auto travel mode" from `,` to `CTRL+M`.
Unbinding it and trusting the player to pick something convenient for them if they want to use it.
1. Deleted my config folder, weh. :<
2. Opened up compiled test build.
3. Checked keybindings, it shows the expected key combo.
4. Load-tested and confirmed it works as expected.
5. Searched in the keybindings folder as a whole to make sure nothing else used that key combo, just to …
> fix: move default keybind for auto-travel mode to something less likely to be hit by accident

- .github/labeler.yml
- there's no need to have separate `data` and `JSON` labels.
- the label `JSON` is widely used.
- it is argued by other dev members that `JSON` sounds less intimidating than `data`.
make [labeler](https://github.com/actions/labeler) label data paths as `JSON`
rename back to `data` but let's see how it goes
> ci: rename `data` to `JSON`

- data/json/items/comestibles/med.json
- data/json/recipes/other/medical.json
Antiseptic-soaked cotton balls and rags duplicate the component items due to their `used_up_item` being set wrong. You use 8 cotton balls to get 8 soaked ones, and 4 rags to get 4 soaked rags, so it should not be creating 2 byproducts per use.
1. Set the heal actions of disinfectant-soaked rags and cotton balls to correctly produce 1 charge of byproduct instead of 2.
2. Misc: Set the disinfectant power of soaked cotton balls to be half that of disinfectant-soaked rags, because you're using twice as many balls per craft and still only 1 dose of antiseptic.
3. Misc: Allowed hydrogen peroxide as an alternative to antiseptic in the recipes, because they have the same stats.
Screaming.
3. Checked …
> fix: antiseptic-soaked items yield correct byproducts when used, sanity-check stats, allow hydrogen peroxide too

- data/json/mapgen/fema/FEMA_re_03.json
Put dirt under the tent chairs in the mapgen `FEMA_re`
Dirt under the chairs.
none
Before:
After:
> fix: put dirt under the tent chairs in `FEMA_re`

- data/json/itemgroups/Weapons_Mods_Ammo/guns.json
- data/json/npcs/NC_BANDIT.json
- data/json/npcs/NC_THUG.json
- data/json/npcs/classes.json
- data/json/npcs/npc.json
- data/json/npcs/tacoma_ranch/NPC_ranch_carpenter2.json
- data/json/npcs/tacoma_ranch/NPC_ranch_farmer1.json
This finally actually defines itemgroups for bandit and thug NPC items, so they favor more biker and Mad Max style gear instead of mostly using the same itemgroups as generic NPCs.
1. Defined a new NPC class `NC_BANDIT`, which is similar to `NC_THUG` except getting a broad focus on ranged skills instead of melee.
2. Set generic ranged bandits to use `NC_BANDIT` instead of `NC_SCAVENGER`.
3. Defined a bunch of accompanying itemgroups for bandit armor. Generally leans a lot more towards the expected biker and Mad Max asthetic as you'd expect with less normal clothes. Their "extra" items also include less jewelry but a better variety of such when they do spawn it, allowing for a few other alternatives like elbow+knee pads or even shields.
4. Rigged it so that `NC_THUG` automatically gets the …
> feat(balance): define itemgroups for bandit armor and weapons

- src/magic.cpp
As noted by Phoenix in the Discord, the mutations were not being properly applied in Magical Nights. I then realized "Oh wait, that's a self-own because *I'm the one who added the check to get rid of the prompt when it was unnecessary*". This fixes it so that the mutations do get properly added
Just adds the mutation-adding code to an `else` block
- Explode
- Re-arrange the code somehow
Compiled locally, and it works
The rare self-own
> fix: Correctly add class mutations when class is non-exclusive

- data/json/overmap/overmap_special/specials.json
Fix because the trailer park `overmap_special`, the one placed outside the cities doesn't use roofs.
Modify `Trailer Park` in json/overmap/overmap_special/specials.json to make it place `trailerparksmall0_roof`, `trailerparksmall1_roof` and `trailerparksmall2_roof`.
none
Before:
After:
> fix: missing roofs in the trailer park outside the cities

- data/json/recipes/other/containers.json
We lacked this recipe, most other plastic items were 3D printable. Plastic bags are for vacuum sealing food.
Adds plastic bag recipe, same cost as not using a 3D printer, same recipe as the small plastic bottle.
None
Tests
> feat(content): 3D print plastic bags

- doc/src/content/docs/en/dev/guides/building/atomic_cmake.md
- doc/src/content/docs/en/dev/guides/building/cmake.md
With atomic linux distros gaining popularity, having instructions for them seemed worthy of a docs page. Plus, as I helped Royal Fox out with compiling on Bazzite anyway, I already had the information all ready to go.
Additionally, I noticed a small inconsistency with the CMake command on the normal CMake page, and thus I edited it to better reflect the command right before it.
- Adds a page for cmake builds on atomic distros
- Fixes a small inconsistency in the cmake command on the main cmake build page
- Put the atomic guide on the same page as the rest of the instructions for cmake
Fair, but I felt that it would have bloated it a bit and in general that it was better for a separation between atomic and non-atomic (Funnily enough, embodying the exact ideals of the containerization used …
> docs: Atomic builds documentation

- data/mods/Item_Category_Overhaul/zones.json
When I was directed to rename unsorted tools to Other tools via review comment, We managed to all miss that the zone was never renamed. That was mostly on me as author. This fixes it.
Rename it.
Nah
Tests
aaaaaaaaa
> fix: Other tools zone is named correctly

- data/json/ammo_effects.json
- data/json/items/resources/misc.json
- data/json/items/tool/explosives.json
This adjusts the impact against armor of fragmentation explosives, which is planned to make them a bit less wonky against some armored enemies.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5082 technically, though it will need a companion PR I have planned to get a bit better at actually tackling this problem, and even then I'm not yet 100% happy with the results.
1. Lowered the `armor_multiplier` for fragmentation of dynamite bombs, ANFO charges, improvised frag devices, and barrel bombs from 3 to 2.5, matching that of 12 gauge scrap shot.
2. Lowered the `armor_multiplier` of proper frag grenade's fragmentation from 3 to 2, matching that of 12 gauge standard buckshot.
3. Lowered the armor multiplier of the `FRAG_SMALL` ammo effect from 3 to 2.5.
4. Lowered the armor …
> feat(balance): reduce `armor_multiplier` for larger and military-issue explosives

- data/json/mapgen/music_venue.json
Use regional terrain for the mapgen `music_venue`
none
Before:
After:
> fix: use regional terrain for `music_venue`

- data/json/mapgen/fema/FEMA_tlc_01.json
- data/json/mapgen/fema/FEMA_trc_01.json
- data/json/mapgen/fema/FEMA_trc_03.json
Replace the gates in the corners of several mapgen in the FEMA camp with chain link fence.
Replace the gates in the corners of the fence in `FEMA_tlc`, `FEMA_trc` with a chain link fence.
none
> fix: replace the gate in the corners of several mapgen in the FEMA camp into chain link fence

- data/json/furniture_and_terrain/furniture-industrial.json
- data/json/furniture_and_terrain/terrain-manufactured.json
- data/json/mapgen/wind_turbine.json
- data/json/obsoletion/uncategorized.json
- data/json/overmap/overmap_special/specials.json
We are once again screaming at wind turbines. Makes it so the free powergen that snuck into https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4447 is instead tied to the spinny thing so taking it off makes it stop, but also had to migrate it to a furniture because `active` doesn't work on terrain.
1. Added the `ELECTRIC_GRID` flag to the overmap special for wind turbines, since the apparent idea is you can use them for free power if you connect your base to one since it has free powergen furniture in it. However...
2. Removed the `active` data from electrical conduits and capacitor banks. Their power supply rate was noted to be fast enough to risk creating lag for some players, we might end up using that furniture elsewhere that have no business generating free power from nothing, and …
> fix: shift power generation of wind turbine location to the rotor itself, add `ELECTRIC_GRID` flag

- src/sounds.cpp
There are a number of gun onomatopoeia in the game, for different types of weapon and grades of loudness, but these are only shown if someone else uses a gun within hearing range. Due to an ancient bug, or perhaps an undocumented feature, player guns have been silent for almost six years.
Having the sound descriptions visible provides better feedback, letting you see in the message log that the gun is working, whether it's firing a single shot or burst, and get a general idea of how loud it is based on the sound effect printed.
The solution is to just flip combat sounds to the other side of the switch that selects which sounds to print. I think they can hypothetically interrupt long actions, but since it's not possible to fire a gun in the middle of a long action, I can't think of a way …
> fix: Print the sound guns make to the message log

- data/json/itemgroups/Clothing_Gear/clothing.json
- data/json/itemgroups/Locations_MapExtras/locations_commercial.json
- data/json/itemgroups/Locations_MapExtras/mall_item_groups.json
- data/json/items/armor/bandolier.json
- data/json/items/ranged/throwing.json
- data/json/professions.json
- data/json/recipes/armor/storage.json
This makes it possible to actually store throwing knives and axes somewhere other than loose in your inventory, and adds an item that caters to one of said throwing weapons.
1. Added the `SHEATH_KNIFE` flag to throwing knives.
2. Added the `SHEATH_AXE` and `BELT_CLIP` flags to throwing axes. Right now the former flag is irrelevant for this item as axe ring holsters are too big (also too big for hatchets I should add), but the latter works.
3. Added a new item, throwing knife bandolier. Serves the role of a torso-waist slot item capable of holding up to 10 knives, with the same 250-ml size limit as wrist sheathes.
4. Moved the assassin profession's throwing knives to a throwing knife bandolier.
5. Added recipe for throwing knife bandolier, generally comparable to most of the standard …
> feat(balance): allow sheathing throwing knives and throwing axes, add a storage item for throwing knives

- data/json/items/gunmod/rail.json
Rail crossbows made no noise, this is because bolts don't have loudness, instead the crossbow does.
Give it loudness 10 like the crossbow. This is attached to the gun data of the rail crossbow gunmod, so the other items which inherit it will correctly inherit loudness.
Make the problem worse
Tests
Scream for me, crossbow-chan.
> fix: assign loudness to rail crossbow

- data/json/overmap/overmap_special/specials.json
These are very powerful locations and up to 8 were spawning on my overmaps. This drowns out other locations and also causes issues with the supply of materials it brings. The materials is another issue as `advanced_object_deconstruction` appears to be broken in the code, I'll ask around on that. Basically it seems to ignore the advanced recipe and allow a deconstruct furniture on electrical conduits which erroneously grants up to 800 copper wire.
Change occurrence to 0, 10. This should to my understanding halve it.
Overhaul overmap generation.
Tests.
It is what it is. @chaosvolt GUESS WHAT, WE'RE ABOUT TO SUFFER WHEN YOU GET BACK HOME! :D
> fix: lower wind turbine overmap occurrence rate

- data/json/deconstruction.json
- data/json/furniture_and_terrain/furniture-industrial.json
Electrical conduits gave between 200 and 800 copper wire, and 9 spawned per wind turbine. This removes the deconstruct and sets it to require the advanced object deconstruction. I also put an electrical skill of 1 so it can train electronics and so it requires some skill to take apart.
Remove the deconstruct entry, add electronics 1
Redoing all electrical furniture to add skill value and convert some to advanced object.
Tests
Pain
> fix: wire conduits give sane copper wire quantities

- src/character_turn.cpp
`scent_modifier` was multiplying the scent value after addition/subtraction. Meaning that if you had a value less than 1 and just created the character/loaded it, the scent map would be 0 and increased to 1, then multiplied by 0.x which is then truncated to 0 by the game to fit it into the int value.
This also means that the only way it does work is by multiplying any existing scent by the value, meaning that any value greater than 1 will cause runaway compounding until scent hits the max value. (example courtesy of @RoyalFox2140)
Make `scent_modifier` multiply your scent equilibrium instead, and multiply it _after_ all scent affecting addition/subtraction to make the expected values more intuitive.
- Multiply before scent mask effects
- Rejected on basis that it makes them produce …
> fix: make `scent_modifier` affect your scent equilibrium.

- data/json/furniture_and_terrain/furniture-storage.json
- data/json/furniture_and_terrain/furniture-tools.json
Some assorted ideas that came up to allow more options for breaking into certain locked objects.
1. Gave display cases lockpick and prying data. Idea being that getting around to the employee side to get at the sliding door to access it with a bit less smash and grab. Prying data uses same general difficulty as prying windows. A successful pry or lockpick turns it into...
2. Added an unlocked state for display cases, resembling locked ones but accessible like broken ones.
3. Also allowed you to deconstruct broken and unlocked display cases, now with some nails in bash results of busted cases.
4. Added `oxytorch` data to reinforced vending machines, allowing you to cut them open as an alternative to using a jackhammer.
Adding a reinforced or laminated version of display cases and using …
> feat(balance): allow oxytorching reinforced vending machines, lockpicking and prying display cases

- data/json/items/vehicle/battery.json
Large storage battery has a plural of storage batteries. This confused me when looting. It's because I used the menu to find nearby items but when I went into loot the tile it showed up as "storage batteries".
Add large to the plural. I also checked all batteries in the file, they're all good. Normal tool batteries should all be all good as I never noticed a problem.
None.
Tests.
> fix: fix large storage battery plural

- data/json/mapgen/military/mil_base/mil_base_z2.json
- data/json/overmap/overmap_special/specials.json
- data/json/overmap/overmap_terrain/overmap_terrain_military.json
In the military base:
Create a proper roof above `mil_base_3g1` because `mil_base_3g1` has no roof.
Create the mapgen `mil_base_3g2` and place it above `mil_base_3g1`
none
Before:
After:
> fix: create the mapgen `mil_base_3g2` and place it above `mil_base_3g1`

- data/json/furniture_and_terrain/furniture-appliances.json
- data/json/furniture_and_terrain/furniture-industrial.json
- tests/electric_grid_test.cpp
A lot of steady consumers were set to fast intervals. This sets them to slow ones to avoid lag. Also adds a note to avoid setting it to fast.
Steady consumer is generally set to 300 seconds, with a few exceptions for 1 minute. Note added to avoid under 300 seconds.  Also, heaters and AC's have insane power draw so this is bad, I don't know how to solve that, but it doesn't matter if its 1 in 1 second or 300 in 300 seconds its still the same insane draw.
Pain
Tests
aaaaa
> perf: Update steady_consumer to longer intervals to avoid lag

- data/mods/innawoods/regional_settings.json
wasp nests are too frequent in innawoods mod, which doesn't seem to be done on purpose.
matches wasp spawn weight to that of regular map extra rate.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/629979e4fbefa1ee9bdbe144acd8d23d64729a7d/data/json/regional_map_settings.json#L489
- reduced `field` wasp nest spawn weight from 200 -> 5, same as vanilla `field` wasp nest spawn weight.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/629979e4fbefa1ee9bdbe144acd8d23d64729a7d/data/json/regional_map_settings.json#L399
- added `forest_thick` wasp nest spawn weight as 100, same as vanilla `forest_thick` wasp nest spawn weight.
asking @Zlorthishen whether the numbers are correct
haven't, but should work since it's just a number change.
opened PR since it sounded like a easy fix.
original …
> feat(balance,mods/innawoods): reduce wasp nest spawn weight

- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/magic_spell_effect.cpp
- src/ranged.cpp
This fixes a couple long-running annoyances in spellcasting code I figured out solutions for. Also technically opens up unrestricted controlled teleportation as something spells can do without even needing a new spell function.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4216
C++ changes:
1. In magic_spell_effect.cpp, changed `swap_pos` so that it only tries to move any creatures found in the epicenter if there actually is one. If the tile targeted is empty, now instead of the game just imploding like before, it simply warps you over there without any complaints, meaning you can freely use `SWAP_POS` spells on any tile you want if you write the spell's JSON to permit targeting the ground to just use it for teleportation if you so choose.
2. In ranged.cpp, set …
> fix: ally-only spells no longer autotarget enemies, fix crash when casting `SWAP_POS` on a tile with no creature to swap with

- data/json/ammo_effects.json
- data/json/items/ammo/84x246mm.json
- data/json/items/ammo/rpg.json
- src/explosion.cpp
- src/ranged.cpp
- src/sounds.cpp
Much as I liked https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5309, turns out it also prints the sound your melee attacks in the message log, which is a bit less desirable. So time for the alternative idea I mused upon in said PR discussion, and as a bonus fixing the issue with fragmentation ammo effects Soad spotted.
C++ changes:
1. In explosion.cpp, `explosion_funcs::regular` is now able to look for fragmentation in the explosion definition it's handed. If the explosion has fragmentation defined, it'll use the damage value for that instead of the raw explosive damage as the starting point for noise calculation. This fixes ammo effects and explosives that have fragmentation but no regular explosion being dead silent when they go off.
2. In ranged.cpp, defined static function …
> feat: firing message instead of printing all player-made combat sounds, allow fragmentation explosions to create sounds

- data/json/mapgen/bank.json
Use regional terrain for the mapgen `bank` and `bank_1`
none
Before:
`bank`:
`bank_1`:
After:
> fix: use regional terrain for `bank` and `bank_1`

- src/vehicle.cpp
So, I looked into how sail code works. Face the wind and no sailing for you, sail with the wind at your back and you go fast. One problem though: you don't merely lose power sailing directly against the wind, but instead as soon as you're 90 degrees to the wind your power drops to a near useless amount.
Considering that sails can be adjusted to differing angles, this is a tad silly, at bare minimum you shouldn't have power drop down to the point of stopping the vehicle until you're actually close to sailing into the wind. But arguably for game purposes it'd be reasonable to just permit some level of movement regardless of facing.
In vehicle.cpp, reworked the handling of wind power in `vehicle::part_vpower_w` a bit. Thanks to Soad explaining out the multiplier works, it's been adjusted to …
> feat(balance): sanity-check power curve of sails with angle, allow minimum power even when sailing into the wind

- data/json/mapgen/microlab/microlab_connector.json
Change the `fill_ter` of the mapgen `microlab_generic_surface` because placing an outdoor terrain (`t_concrete`) indoors underneath the furniture is not good.
Use `t_thconc_floor` instead of `t_concrete` for the `fill_ter`
Replaced "t_grass" of the terrain " " by "t_region_groundcover"
Replaced `t_pavement_y` (yellow pavement) inside the building with `t_thconc_y`
none
Before:
After:
> fix: change the `fill_ter` of the mapgen `microlab_generic_surface` and use the regional terrain

- data/json/furniture_and_terrain/furniture-decorative.json
- data/json/furniture_and_terrain/furniture-domestic_plants.json
- data/json/furniture_and_terrain/furniture-fungal.json
- data/json/furniture_and_terrain/furniture-industrial.json
- data/json/furniture_and_terrain/furniture-terrains.json
- data/json/furniture_and_terrain/furniture-tools.json
I noticed that opaque furniture can stop bullets if they lack ranged bash info, destroying the furniture but perfectly preventing any overpenetration. Decided to fix it so relevant affected furniture will be shot through as expected, and applied ranged bash info to a few more furniture items I spotted along the way.
1. Added ranged bash info to decorative trees, being a weirdo opaque furniture capable of always absorbing bullets, and set wreathes to be transparent and permit walking under them to stop being an obstacle.
2. Added ranged bash info to planters and mushroom racks, with planters getting `str_max` raised a bit and ballistic resistance fitting for an item stuffed with soil.
3. Added ranged bash info to the two fungal furniture entries that're opaque.
4. Updated coverage and …
> feat(balance): fix opaque furniture absorbing bullets, add ranged bash info to a few more furniture entries

- doc/src/content/docs/en/mod/json/reference/graphics/external_tileset.md
I was gonna add this to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5361 but forgor
Update documentation for external tileset.
Continue to forgor
> docs: update external tileset documentation

- data/json/mapgen/microlab/microlab_connector.json
- data/json/overmap/overmap_special/specials.json
- data/json/overmap/overmap_terrain/overmap_terrain_microlab.json
Prevent sewer from passing under the surface entrance of `4x4_microlab_surface` because there is an elevator on the mapgen `microlab_generic_surface` and `microlab_generic_surface_connector`
Create the mapgen `microlab_under_connector` and place it under the surface entrance of `4x4_microlab_surface` to prevent sewer from passing between `microlab_generic_surface` and `microlab_generic_surface_connector`
none
none
> fix: prevent sewer from passing under `4x4_microlab_surface` entrance

- data/json/itemgroups/Locations_MapExtras/locations.json
- data/json/mapgen/cave.json
- data/json/recipes/ammo/components.json
Had an idea to make saltpeter less hassle to deal with, but along the way I started sanity-checking my math in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1268 and realized I completely bungled it such that the recipe was only like 50% saltpeter, when it wasn't that hard to calculate a ratio that's more accurate but not absurdly wasteful.
1. Gave cave entrances a chance to spawn items of group `cave_mineral`, mainly representing bat activity in conjuction with the below change but still potentially spawning some other loose minerals.
2. Adjusted weights of contents in `cave_minerals` to favor niter 75% of the time, with some chances of spawning sulfur, rock salt, or iron ore. Limestone no longer present since it's already widely available from mining rocks or smashing boulders, …
> feat(balance): cave entrances can spawn niter and other minerals, sanity-check gunpowder recipe

- data/json/items/generic.json
- data/json/recipes/other/other.json
- data/json/uncraft/generic.json
- data/json/vehicleparts/vehicle_parts.json
- tests/vehicle_drag_test.cpp
- tests/vehicle_efficiency_test.cpp
This started at first as just "swap in different items for two specific vehicleparts" but since one of them happened to be mattresses, that turned into a minor rabbithole of sanity-checking some associated recipes and uncrafts.
JSON updates:
1. Set it so that vehiclepart beds use a mattress to construct instead of a seat, and uses bolt turning quality of 1 instead of welding to install. Also updated its `breaks_into` entry to be consistent with uncraft results. Lastly, bumped its `floor_bedding_warmth` up to 800 to match that of a floor mattress.
2. Added a recipe for mattresses, like how you can craft down-filled and wool mattresses. Made it however use springs instead of wire and scrap, along with enough cotton balls so the total materials (minus the thread in `sewing_standard`, …
> feat(balance): use mattresses for vehicle beds and clocks for vehicle clocks, balance updates to associated items and recipes

- .github/workflows/release.yml
People have continued to be scared of using the so-called "Experimental" builds, and thus running stables, often to their own detriment. 
- Renames the builds currently called "Experimental" to "Nightly" instead.
In my opinion, as well as the opinion of several others who provided their input as to the idea, Nightly is a far less intimidating name that fits our current build type perfectly. It still (to those familiar with the term, at least) comes with the connotation of a few bugs not being *unusual* to see, but without the heavy-handed "There WILL be bugs, and lots of them" that Experimental generally implies. 
Additionally, it (generally) fits literally, as for many the builds are in fact done every *night*. 
- Leave it be out of tradition
- Change "Stable" as well
I see less of a …
> ci: rename from Experimental to Nightly

- data/json/items/containers.json
- data/json/items/tool/cooking.json
- data/json/items/tool/science.json
- data/json/items/tool_armor.json
- src/item.cpp
This tweaks it so that items which aren't made purely of glass, like glass fridges famously, won't instantly melt when hit by stuff.
C++ changes:
1. In item.cpp, `item::can_shatter` changed so that it asks if the item is made exclusively of glass via `only_made_of`, instead of if it's made of glass period. This excludes multi-material items from being in danger of shattering unless they're given the `SHATTERS` flag.
JSON changes:
1. Glass flasks and test tubes given the `SHATTERS` flag so they'll still break like expected when tossed.
2. Fermenting jars of eggs, yeast, and the like given the `SHATTERS` flag.
3. Added `SHATTERS` flag to separation funnel.
4. `FRAGILE` flag given to binoculars, to make it vulnerable to being wrecked but not as much as it was beforehand.
Going to bed, it's …
> feat(balance): glass items only shatter if made solely of glass

- data/json/items/melee/spears_and_polearms.json
- data/json/items/tool/woodworking.json
Gives a bit extra throwing utility to a couple items.
1. Adds baseline `thrown_damage` to stone and copper tomahawks. Went with about the same proportions relative to their melee damage that throwing axes have.
2. Added a basic bit of throwing damage to pointy sticks so they can be used as makeshift javelins. Set the values to be lower than the wooden javelin.
I'm tempted to add woodcutting quality to tomahawks, but doing so would make the stone one have to be equal to the stone axe quality-wise since 1 is already the lowest you can go with it, or else rigging it so only the copper version has axe quality which would look weird.
1. Checked affect files for syntax and lint errors.
2. Tested throwing stone tomahawks at a debug monster in my laptop save, prior to porting over JSON changes. …
> feat(balance): add `thrown_damage` to tomahawks and pointy sticks

- doc/src/content/docs/en/dev/guides/building/atomic_cmake.md
followup of #5287, attempt to address the situation when you exported clang and suddenly build doesn't work inside distrobox
add an troubleshooting guide
https://github.com/89luca89/distrobox/issues/1548
> docs: troubleshoot guide for distrobox exports

- src/cata_tiles.cpp
Fixes #5402 
Near the end of tileset loading there is a step to remove any tile information with no valid foreground or background sprite set. It does this by removing it from the `tile_ids` unordered_map. During tile creation, however, a pointer to that tile_type information is stored in seasonal variation maps. We do not currently search for and remove the bad tiles from the seasonal variation maps and this causes the crash.
Removing bad tiles from seasonal lists looks to be enough to solve the problem, and a SIGSEG I encountered using a different compiler.
Loading a save with Hoder's Tileset active (the only one in repo that is known to cause these crashes)
BEFORE: crashed as soon as a relevant removed tile is encountered (`t_trunk` in repeated tests)
AFTER: no crashing
> fix: also remove bad sprites from seasonal variations

- .github/workflows/autofix.yml
deno packages weren't being properly cached due to `~` not getting expanded.
> ci: fix deno cache

- data/json/items/comestibles/raw_fruit.json
Some berries and fruits still had the `RAW` flag but most do not.
Removed `RAW` from lemons, cranberries, raspberries, elderberries, rose hips, and blackberries. All of these are specifically fruits that can be eaten raw (though I can personally confirm cranberries really suck to eat raw IRL despite my love of sour foods, while quick lookup says elderberries will make you sick if not cooked and rose hips contain hairs that'll cause irritation).
I left cacao pods unchanged since you're expected to roast the beans before use, and nopales unchanged since they're the pads of cactus rather than fruit, so being expected to cook both is a bit more justified.
1. Saying "fuck it" and making raw cacao pods fully edible as-is. This would render cacao nibs pointless however, so at that point we might …
> feat(balance): remove `RAW` flag from more edible fruits

- data/json/furniture_and_terrain/terrain-windows.json
Because I didn't catch that the window with metal bars didn't have bash data assigned other than the resulting furniture, it was un-bashable after I merged https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5326
Yet another day where copy-from makes clowns of us all.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5432
Adds back the bash data from t_window.
Make Chaos do it, for making the original PR. Leave it as is, nuclear weapons to breach windows is funny.
The tests.
This is why I refuse to have copy-froms in 2200, unless it's to overwrite a field on a base-game ID.
> fix: re-allow players to smash windows with metal bars

- data/json/items/tool/explosives.json
Makeshift gas canisters get 10/3 charges on activation. This fixes that.
Initial and max charges on the activated version is set to 10. This coincides with 10 charges on the target_charges
None
Tests
> fix: makeshift gas canisters have correct max charges

- src/sol/sol.hpp
[lua bindings fails to build on clang 18](https://github.com/ThePhD/sol2/issues/1581)
applied following workaround: https://github.com/ThePhD/sol2/issues/1581#issuecomment-2103463524
wait for LLVM backports, but it'd take a long time.
was able to build locally.
> build: fix build failure in clang 18

- doc/src/content/docs/en/dev/guides/building/atomic_cmake.md
- doc/src/content/docs/en/dev/guides/building/cmake.md
With Scarf fixing Clang-18 builds, there is no reason to specify an older version of clang and thus the build scripts can now just use `clang` instead of `clang-17` for greater compatibility with a variety of systems.
- Replaces `clang-17` with `clang` in build docs
- Lightens the warning in the atomic docs regarding bazzite's outdated fedora image.
- Do nothing
- Completely remove Bazzite warnings due to no longer being needed
Fair, but I feel like noting that Bazzite has an outdated Fedora image by default can still be helpful on the off chance something borks itself in the future related to it.
I can confirm it is indeed legible
Woohoo, we support an up-to-date compiler now ^-^
~~Now to go test AOCC and see how that works for us~~
> docs: Replace `clang-17` with just `clang` in the docs

- data/mods/Monster_Girls/categories.json
- data/mods/Monster_Girls/migration.json
- data/mods/Monster_Girls/mutagens.json
- data/mods/Monster_Girls/recipes.json
- data/mods/Monster_Girls/thresh_mutation.json
- data/mods/Monster_Girls/vanilla_mutations.json
Standpipe maintenance log served no purpose in the mod previously, and elves are historically lumped in with monster girls anyway. Besides, more direct mutation path equivalents between the mod and base BN is always good!
Adds an Elf mutation path based on, you guessed it, ~~Medical~~ Elf-A!
- Leave the standpipe maintenance log useless
Load tested, it works.
Now to debate whether to fix the issue of regular mutagen in theory still allowing you to get the undesirable mutations from base game, or to treat it as sort-of chimera. If I do fix it, it'll mean more work on the scripts to help others maintain it tho...
> feat(mods/Monster_Girls): Add elves to Monster Girl Mutations

- data/mods/Monster_Girls/thresh_mutation.json
Spelling / grammar mistake thanks to homophones and a word pretty much exclusive to archery.
'knock' -> 'nock'
- leave it be
Funnily enough, both Discord and Github / Firefox are unaware of 'nock' being a valid word
Thanks jetscooters for promptly noticing my error ^-^
> chore(mods/Monster_Girls): Use 'nock' instead of 'knock' for archery

- src/activity_handlers.cpp
Butchering an animal should not produce more weight in drops than the animal weighs to start with.
fixes #4523
I fixed the issue by setting the weight of a given drop to the lesser of the calculated weight and monster weight * mass ratio of the drop (which should be the maximum possible drop.)
I noticed at line 1275 (1277 if this is merged) of activity_handlers.cpp, there's a multiplier that looks like it's supposed to add up to 1 which is used to calculate the weight of butchering drops. The second term of this calculation, 0.3 * ( factor + 50 ) / 100, looks like it assumes the butchering quality of a tool will be between -50 and 50 for the multiplier to make sense. Another solution could be changing this to 0.3 * (some function that approaches 0 at negative infinity and approaches 1 at …
> fix: Butchery yield needs to be capped

- data/json/monsters/bird.json
Chickens in real life are usually a bit bigger, and also are bred for meat.
Set weight from 1kg to 2kg
https://farmhouseguide.com/how-much-chickens-weigh/
None
Tests
> feat(balance): Make chickens fatter

- src/map.cpp
Fixes #3754 
Forges were trying to consume charges of the fake forge item itself (e.g. char_forge) instead of its ammo (e.g. charcoal).
I'm not sure if this does relate to #5439. If someone could check if it's still present that would be great but I'm guessing it will be.
Also notice there's a very similar thing just above this (line 5099) for the power grid charge consumption. Again it's using the fake item as what it's depleting but I'm not sure if that's correct for power? Could you take a quick look @chaosvolt and make sure it's ok?
> fix: Corrects charges draining from forges

- data/motd/en.motd
As I discovered looking at #5463 , the messages in the MoTD regarding Experimental / Nightly builds were still the same-old fearmongering DDA ones regarding unbalanced, half-baked features and rampant bugs. Considering the testing we're doing on PRs, and our general philosophy regarding Nightly releases, this felt out of place and thus I aim to correct it.
Rewrites each of the "answer" portions regarding nightly builds to better reflect our current philosophy and ideas behind Nightly builds.
- Completely rewrite that section of the MoTD rather than leaving the questions in-tact
Fair, the questions are still a *bit* off for our current idea of Nightly builds, but that's a bit more work. Could easily be an alternative solution though.
My spell checker seems happy with it, and if anything …
> style: Less hyperbolic MOTD regarding nightly builds

- src/character_preview.cpp
Alternate PR to #5393 
Copying its Purpose of change:
> Modifies #5031 to stop altering the actual character at game start, this was causing a lot of unintentional behaviour and is _incredibly problematic_.
Fixes #5120
Fixes #5317
Instead of modifying the input character directly we use an adapter of `cata_tiles` to customize character drawing and a temporary `avatar` where appropriate to contain changes necessary to keep character preview working properly.
While this works I don't particularly like this solution. It feels a bit hacky, and will require maintenance whenever `cata_tiles::draw_entity_with_overlays` or `Character::get_overlay_ids` are modified.
Make `avatar`'s copy constructor usable. Doing this may have undesirable side effects and I don't have the time to put into making …
> fix: don't modify character while drawing character preview

- src/map.cpp
Fix my lack of testing. 
It seems forge charges not being consumed was masking the problem that they're always considered consumable. Now it will only accept them if the tool or ammo type is correct.
Both draining charges from forges and crafting normally now seem to work.
> fix: Stop using forge charges for all crafts

- data/json/bionics.json
- data/json/professions.json
- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/bionics.cpp
- src/bionics.h
- src/item.cpp
ports 
- https://github.com/CleverRaven/Cataclysm-DDA/pull/66996
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5455
ports the dda change which can allow bionic  A to require bionic B to already be installed prior to installation of Bionic A
> feat(port): Bionics can require another bionic

- src/avatar_functions.cpp
Instead of eating the dog food (or any other pet food) that's in a container, it gets unloaded to the inventory, where it can be used.
modifies is_pet_food bool on avatar_functions.cpp to reflect json changes on pet food.
Crying.
Before:
After:
> fix: prevents eating canned dog food after activation

- .github/workflows/pull-translations.yml
automate weekly i18n PR review process
- uses https://github.com/marketplace/actions/git-auto-commit to directly commit to `main`.
- uses https://git-scm.com/docs/git-sparse-checkout to only checkout relevant directories and speed up cloning.
keep opening PRs but it's rather cluttered and requires human intervention.
should probably work... probably...
can be also ran manually to debug it
> ci(i18n): commit translation files directly to `main`

- .github/workflows/pull-translations.yml
fix bug in #5492 where the workflow would freeze on pushing
remove `sparse-checkout` option
[actually tested it works on fork this time.](https://github.com/scarf005/Cataclysm-BN/actions/runs/11157508424)
> ci(i18n): fix pull translations action freezing

- data/json/items/comestibles/meat_dishes.json
Most meat dishes have a special name when made with either human flesh or mutant meat, both to provide flavour and help identify which food has mutagenic toxins or a cannibal morale modifier. Previously, cracklins did not.
Cracklins made of human fat are now called "long pork rinds", while those made of mutant fat are called "cursed cracklins".
"Cannibal cracklins" would also scan, but I feel like actually using the word "cannibal" would be too unimaginative.
Butchered and cooked an NPC. Loaded a save with an existing stockpile of mutant cracklins. Names were rendered correctly.
> feat(content): conditional names for cracklins

- data/raw/keybindings/keybindings.json
- src/advanced_inv.cpp
- src/options.cpp
Feature was requested in BN Discord server to automatically reset AIM filters
It was easy enough to make the left and right AIM panes clear their filters. I made an **Interface Option** so users can choose what behavior they want, default _false/off_, and also made it possible to toggle that option from within the AIM UI, default _"T"_ but rebindable. Additionally there is a UI element showing the option status near the AIM minimap.
Option is saved properly after toggle.
Set filters with option set to ON. Status UI element displayed correctly. Filters cleared on exiting AIM UI.
Set filters with option set to OFF. Status UI element displayed correctly. Filters not cleared on exiting AIM UI.
Set filters and toggled option from within AIM UI, testing both from OFF to ON and from ON to OFF. …
> feat(UI): add toggle option to automatically reset AIM filter on menu exit

- data/json/obsoletion/recipes.json
- data/json/recipes/chem/chemicals.json
So I looked at the recipe for liquid fertilizer and noticed two recipes that seemed near-identical except in a few narrowly-specific annoying ways, swapping out a single identically-interchangeable component but making the tool requirements radically different.
1. Merged the two recipes for liquid fertilizer into one, obsoleting the "simple" version. This means aluminum sulfate added as an alternative to the ammonia/lye/etc component, using the skill demands and book options of the harder version, but also compromising on what tool quality to use by allowing `CHEM` 1 instead of using `BOIL` 1 or `CHEM` 2.
2. Moved the unneeded other recipe to the obsoletion folder.
screm
2. Ported changes to playthrough release and load-tested.
> feat(balance): merge and rebalance the two liquid fertilizer recipes

- src/examine_item_menu.cpp
- src/examine_item_menu.h
UI improvement for the kill counter added in #5394. @RoyalFox2140 asked me to recolor the Kills button in the examine item menu to make it a bit more visible. While looking through the menu code, I also figured out a way to add a kill counter in the menu, which I'd wanted to have since the beginning.
The Kills menu option was given its own hint color (red). The `add_entry()` function in `examine_item_menu.cpp` was modified to optionally print a number in addition to menu text.
I think dark red has the appropriate connotations of violence, but changing the color is easy if someone has a better idea. Light red is already used in the menu in a different context, but yellow for example might work. 
Thought about adding a new `add_entry_with_number` function instead of overloading the existing …
> feat: Show item kill count in the examine item menu, make the menu option red

- src/item.cpp
- src/item_group.cpp
- src/relic.cpp
- fix #5508, due to #5283 which revealed the issue that our item group code will attempt to insert magazines into items that aren't explicitly labelled as having integral magazines, leading to null items being shoved into them and causing issues. Also fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5396
- fix #5283 where I noticed that my code will attempt to infinitely increment tool charges instead of respecting the maximum charges of a tool.
- item group item spawn code will now only load magazines into an item if it both doesn't already have one, and has a non-null item for a default magazine.
Another shining testament to the spaghetti in our code. If I could eat all of our code spaghetti I'd never have to buy food again.
> fix: Fix itemgroup code and fix recharge scheme code

- src/ranged.cpp
- src/ranged.h
- src/ranged_aoe.cpp
This aims to tackle a bug I encountered last night, in which I blew a hole in me pirate ship trying to give a sludge crawler a broadside with canister shot (spoiler: it wasn't worth it, I just sailed away instead).
1. In ranged.cpp, set `ranged::fire_gun` so that its call to `ranged::execute_shaped_attack` passes the result of `in_veh` to the function like it does when calling `projectile_attack`.
2. In ranged_aoe.cpp and ranged.h, added support for `in_veh` to the args for `execute_shaped_attack`, making it treat vehicle tiles as permeable if it's being fired from a gun mounted on the vehicle said tile belongs to.
Screaming.
2. Installed a 3-inch ordnance rifle on a car.
3. Loaded it with canister shot and fired, no longer blows the shit out of the car I'm …
> fix: AoE ammo fired from vehicle turrets no longer wrecks the vehicle it's fired from

- .clang-tidy
just too many clang-tidy violations atm which makes current clang-tidy rule of warnings-as-errors not desirable.
- disable warnings-as-errors.
- also disable [`SimplifyDeMorgan`](https://clang.llvm.org/extra/clang-tidy/checks/readability/simplify-boolean-expr.html#cmdoption-arg-SimplifyDeMorgan), check commit for details
should work since it loosens clang-tidy tests.
> test: disable clang-tidy warnings-as-error

- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/activity_handlers.cpp
- src/iuse_actor.cpp
- src/magic.cpp
Was noted on the Discord that we had weird behaviour with spell studying where levelling up would not teach you the spell written in `learn_spell`, as it does not send an event for it. Also due to how the notify event works if you miss it in any way you will not learn the spell on later level ups.
Studying a spell now tracks level gained and sends appropriate level up event on level up. (It also shows if you gained a level when the activity finishes, with consideration if you leveled more than once per session)
Updates notify event such that it will grant new spell if the spell level is equal to or greater than target level.
Some of the activity is still weird like storing a whole ass string to remember that this is to gain a level, and spell code could probably be reworked, but that day …
> fix: Rework spell studying and notify

- data/json/skills.json
- tests/iteminfo_test.cpp
- tests/memorial_test.cpp
- tests/reading_test.cpp
able fields need to be added to the `lang/bn_extract_json_strings.sh` script if it does not support them yet.
I think capitalizing skill names looks nicer and is slightly more readable. I'm willing to poll it to the community if there's any opposition.
Capitalizes all skill names
Only capitalize proper nouns instead of each word.
Tests.
People said it looks better so I figured it was worth a shot.
> feat: capitalize all skill names

- data/mods/Magiclysm/modinfo.json
Tiny followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5523
Capitalized skill name of spellcraft in Magiclysm. Bonus dose of {}ifying the name like vanilla skills.
Punishing it with lowercase skill name for its crimes.
Used my eyes.
> feat(UI): also capitalize spell name for Spellcraft

- src/character.cpp
- src/gates.cpp
- src/iuse_actor.cpp
- src/magic_spell_effect.cpp
- src/monattack.cpp
- src/mondefense.cpp
- src/monmove.cpp
- src/monster.cpp
- src/vehicle_move.cpp
- src/vehicle_use.cpp
Some issues were noted in our messages printing the word the multiple times.
Checking further also revealed that some weren't being properly capitalized. In fact, I'm almost 90% sure that I'm the first person to actually _use_ the capitalize first function for `disp_name`
Audits all code that uses `disp_name` in an attempt to standardize our message display.
- Stop using `disp_name` entirely and just use `name`.
- Tempting, probably doable for monster names but breaks down when you use NPCs as you usually don't call people's names with The in front. "The John dodges the zombie's attack" probably means something different from "John dodges the zombie's attack"
If someone wants to test they're welcome, I'll test this shit later this week or something. Main ones are the one's that appear …
> fix: Print messages with monster names properly

- data/json/recipes/weapon/piercing.json
> fix: bone shiv doesnt take survival twice

- src/magic_spell_effect.cpp
Previously spells that give items only give them temporarily at a level less than max, even if a spell is flagged as permanent. This changes that, because permanent flag is permanent. We could eventually add this check back as a new Semi-Permanent flag.
Isolates and removes the level check
Have someone else overhaul it to add a new semi-permanent flag or TRUE permanent flag
Compile tested. Loaded. Used a spell that was partially leveled but with a permanent flag.
:(
> feat: Permanent flagged spells are always permanent, even at min. level

- src/cata_libintl.cpp
- src/cata_tiles.cpp
- src/construction.cpp
- src/debug.cpp
- src/filesystem.cpp
- src/item.cpp
- src/item_factory.cpp
- src/iuse.cpp
- src/json.cpp
- src/language.cpp
- src/overmap.cpp
- src/sdl_font.cpp
- src/string_utils.cpp
- src/string_utils.h
- tests/cata_utility_test.cpp
- tests/test_main.cpp
code is liability; replace them with functions available in C++20 stdlib since we have #5514 
- use C++20 features like https://en.cppreference.com/w/cpp/string/basic_string/starts_with
- remove obsolete benchmarks
> refactor: use C++20 `string::{starts,ends}_with`

- src/assign.h
- src/generic_factory.h
- src/generic_readers.h
- src/numeric_interval.h
followup to #5514; [concept](https://en.cppreference.com/w/cpp/language/constraints) is easier to understand than [SNIFAE](https://en.cppreference.com/w/cpp/language/sfinae), let's use them more!
check individual commits for details.
use less overloading trickery and just use different name for `optional`?
compiled in my machine (tm) but need to check if the concepts translation is correct because they're done 100% manually
i'm dumdum and found this after i've done it manually: https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-constraints.html
> refactor: use concepts more

- src/magic_spell_effect.cpp
This tweaks another weird lil bit of spellcasting code to make the hardcoded "no death drops for you" code only apply to non-permanent summons.
In magic_spell_effect.cpp, set `add_summoned_mon` so that it only does the bit where death drops are turned off in the if statement used by non-permanent summons.
Corpse drop also depends on it being `PERMANENT` already so this makes behavior more consistent.
Removing it entirely, but this is more likely to break in-repo mods since this feature was Korg's bandaid to let him re-use vanilla monsters for summons wholesale, instead of having to specify bespoke versions inheriting from the desired monster like Arcana does (which is a good idea anyway since that lets me tweak their pathing settings, give them regen, swap out monster attacks that only …
> fix: summoned monsters drop items if created by a `PERMANENT` spell

- src/map.cpp
`DL::Error` should be reserved for situations that are exceptional and consequential. In the case of `submap::field_count` it's used to determine if a submap should have fields processed to early out rather than iterate over the submap's field array member. As long as the value is greater than zero the array will be iterated over. The actual value barely matters.
Change `DL::Error` to `DL::Warn` so we can still see occurences in debug.log (if the `Map` context is enabled) but without generating a stack trace.
Change `submap::field_count` into a boolean that is only ever set to `true` when fields are added to the submap and only ever reset to `false` during field processing. That is planned future work, and beyond the immediate scope of removing an unexceptional error.
Employed the …
> fix: change debug level of field count mismatch to DL::Warn

- src/item.cpp
- src/mapgen.cpp
- Extension of #5515. Map extras like supply drop were having the same issue due to faulty code in `place_item()`
- See #5515 solution.
- Add a debugmsg when `put_in()` is fed an invalid item to insert.
- Revert precipitating changes in #5283.
- If someone desires.
Someone needs to play a bit with this change to confirm that we don't feed `put_in()` null items as a norm.
> fix: mapgen grenades stop inserting null items.

- src/vehicle_use.cpp
As noted in the Discord, the engine fail noise for non-battery engines was a clanking noise that generally sounds more appropriate for a v8 than a foot pedal in most soundpacks. This fix silences these woes.
Modify the check to also make sure the engine isn't muscle-powered
- Wait for KorG or someone similar to make a better fix / JSONize everything
- Meme on foot pedals secretly being incredibly tiny v8 engines
None, it's an if statement logic change.
This doesn't cause a regression in notice of a bike failing to start for non-soundpack players because it didn't print a failure message in the first place. Also, how often is a bike in such bad footpedal condition without basically being in pieces anyway?
> fix: Stop muscle engines failing sounding like a V8

- data/json/furniture_and_terrain/furniture-appliances.json
Grid floodlight symbol was difficult to see on a floor when using ASCII graphics.
Changed symbol of `f_grid_floodlight` (all variants) from `.` to `T`, same as the floor lamp. Also changed the "on" state color from white to yellow, to provide a visual indicator that the floodlight is active.
The `t_utility_light` that appears in labs has the same issue, being basically invisible on a concrete floor, but I think it's less of a problem there. They don't use grid power, so there's rarely any reason to turn them off.
Looked at a built floodlight, turned it on and off.
> feat(UI): Change floodlight symbol to 'T'

- data/json/techniques.json
- doc/src/content/docs/en/mod/json/reference/creatures/martialart_json.md
- src/martialarts.cpp
- src/martialarts.h
I was idly thinking that some martial arts, potentially in vanilla but especially Arcana (Via Gladium et Malleo being a style for example that has entirely different buffs and tecs depending on whether you use swords or blunt weapons), could perhaps make use of the ability to restrict martial arts effects based on weapon category.
C++ changes:
1. In martial_arts.cpp and martial_arts.h, defined JSON property `weapon_categories_allowed` in `ma_requirements::load`.
2. Also in martial_arts.cpp, set `ma_requirements::is_valid_character` to check for weapon categories if `weapon_categories_allowed` is defined. In addition, it's been tweaked to not bother checking if the player isn't armed, as if the current buff/technique is explicitly set to permit unarmed use we logically want it to not cause …
> feat(port): add support for martial art buffs/tecs being restricted by weapon category

- src/iexamine.cpp
In an effort to encourage skill training without grinding crafting recipes, I have discovered that foraging bushes is capped by your int score. The current formula seems to be Intelligence divided by 3, plus 1. That means at 12 intelligence you can gain 4 survival from foraging. That's kinda bad as you can grind recipes to level 6 thanks to flint and steel being mainlined. Additionally a 4 int character can only go to level 2.
The formula is set to intelligence divided by 2 plus one. That means at intelligence 12 you can go to 7, and at int 4 you can go to 3. This also means at level 8 intelligence you can go to level 5, which is around the baseline.
This should allow you to gain more survival without being stuck in a bunker doing crafting, and we can tweak it to be more favorable if …
> feat(balance): update max survival skill from foraging

- data/json/mapgen/pizza_parlor.json
Use regional terrain for the mapgen `s_pizza_parlor_1`
Replace non-regional terrain with regional pseudo terrain.
none
Before:
After:
> fix: use regional terrain for `s_pizza_parlor_1`

- src/character.cpp
- fix #5588 which was because the `Character::invoke_item()` doesn't have a consideration for an item that isn't a tool and isn't a comestible.
- Add a consideration such that non-tool, non-comestible items that are `count_by_charges` will consume itself.
> fix: Make rags consume their charges/delete themselves.

- src/url_utility.cpp
Fixes #5585
Allows to build source code on FreeBSD (tested on 14.1-RELEASE-p5).
> fix: use `xdg-open` for opening URL on FreeBSD

- data/json/items/comestibles/carnivore.json
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5602 by setting tainted blood to not be human. This is the easiest way to do it, and tainted flesh doesn't count as human due to recipes like tainted tornado.
Deal with recipe nutrient overrides on a few dozen recipes.
Nah
> fix: tainted blood isn't cannibalism

- data/json/mapgen_palettes/convention_center_palette.json
Since `trash_dumpster` is used to fill most dumpsters in cities, I think it can also be used for the convention center dumpsters.
Use `trash_dumpster`
none
none
> feat(balance): use `trash_dumpster` for the dumpster of the convention center

- data/json/items/armor/belts.json
600 mililiters on the police duty belt does not allow expandable batons to be holstered without being extended, and blocks blackjacks and makeshift saps, the previous change did make it better but you have to expand a baton to holster it and still can't holster the blackjack or sap.
I primarily think it is important to be able to holster a retracted baton so players don't get confused thinking it isn't able to be stored at all.
250 mililiters, this also allows blackjacks, makeshift saps, and batons that aren't extended
A better holster system
Tests
> feat(balance): Allow police duty belts to holster expandable batons

- data/json/recipes/weapon/ranged.json
The coilgun crafting recipe seemed a bit off. Despite it being an electrical device, It uses fabrication as the primary skill, and has mechanics and electronics as additional requirements, with mechanics at a _higher_ level than fabrication. The material requirements are quite a bit lower than the shoddy laser rifle, which is otherwise around the same tier, and it doesn't require a UPS mod which is used in crafting every other energy weapon.
Made electronics the primary skill and increased difficulty from 4 to 5, with mechanics 5 and fabrication 4 as secondaries. For materials, made it use additional power converter, electronic scrap, copper wire and a UPS mod. Also replaced requirement for pipe with plastic chunks, since I'm pretty sure you can't put a barrel made of ferromagnetic …
> feat(balance): adjust coilgun recipe

- data/json/construction.json
Wind turbines and XL wind turbines eat extra steel frames if constructed on roofs, take 40 minutes longer, and requires a wrench. None of that makes sense to me, you additionally lose those frames on deconstruction because its the same terrain ID.
I set it to the same time, requiring a drill instead, and not taking frames.
None
Tests
Each day we stray closer to madness
> feat(balance): stop requesting frames lost on deconstruct

- src/item.cpp
fixes #5612
same as title.
left: before, right: after (this PR)
> fix: only display compatible magazines if they are not empty

- lang/extract_json_strings.py
- lang/update_pot.sh
translation extractor has been always failing.
```
Traceback (most recent call last):
File "/run/media/home/scarf/repo/cata/Cataclysm/lang/extract_json_strings.py", line 1501, in <module>
extract_all_from_dir(state, i)
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
File "/run/media/home/scarf/repo/cata/Cataclysm/lang/extract_json_strings.py", line 1399, in extract_all_from_dir
extract_all_from_dir(state, os.path.join(dir, d))
~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/run/media/home/scarf/repo/cata/Cataclysm/lang/extract_json_strings.py", line 1393, in extract_all_from_dir
extract_all_from_lua_file(state, full_name)
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
File "/run/media/home/scarf/repo/cata/Cataclysm/lang/extract_json_strings.py", line 1430, in extract_all_from_lua_file …
```
> fix(i18n): ignore lua translation errors

- data/json/professions.json
- data/json/scenarios.json
- data/mods/DinoMod/scenarios.json
This adds a profession to post-apoc-focused scenarios aimed towards showcasing the content added in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5466.
1. Added a monster hunter profession, a `SCEN_ONLY` profession that starts with appropriate innawoods gear along with a full set of scaleskin armor, a stinger dagger, composite shortbow, and two quivers to choose between tooth arrows or stinger arrows depending on the situation. Non-combat skills aim to be exactly enough to make all the items they spawn with and any components needed to make those.
2. Added the new profession to Next Summer, Ambushed, and for flavor Mi-go challenge (since rescuer profession similarly is dressed in furs and has post-apoc getup, and the scenario is quite lacking in profession options currently).
3. …
> feat(content): add a new post-apoc profession for starting with scaleskin/tooth gear

- data/json/items/armor/arms_armor.json
- data/json/items/armor/boots.json
- data/json/items/armor/gloves.json
- data/json/items/armor/helmets.json
- data/json/items/armor/shields.json
- data/json/items/armor/suits_protection.json
I was starting to work on something unrelated when I was reminded that https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3861 is still a problem, screwing up acidchitin and plated leather items. Since I don't know how to fix it codewise I'm putting in a workaround.
Converted the encumbrance definitions of acidchitin armor, plated leather armor, and fingerless glove variants to be explicitly set instead of relying on broken `proportional` and `relative` adjustments. Same thing I already had to do with superalloy armor. Even western boots and carbon fiber ballistic shields for that matter used it.
Tormenting Scarf into looking at the code to fix it.
2. Checked the items they inherit from and did basic math to confirm the encumbrance …
> fix: specify emcumbrance for acidchitin, plated leather, etc armor directly instead of using broken inheritance

- data/json/items/comestibles/meat_dishes.json
- data/json/items/comestibles/spice.json
- data/json/recipes/food/meat.json
- data/json/recipes/food/other.json
The food you could make with rice did not inspire joy. Bimbibap, on the other hand, inspires much joy.
In other words: There were relatively few rice dishes available in-game, and I saw the opportunity to add one of my personal favorites.
Adds bimbibap, a korean dish. Also adds gochujang, a new spice that is integral to bimbibap
- Less big recipe for the bimbibap
Fair, but it's based on an IRL recipe I found online and besides, we can always do with tasty culinary flexes.
- Some other rice dish
- Implosion
Loads on my save
Unsure of what groups / cooking requirements, if any, to add these to. Very much so open to input.
If the comestibles test screams at the bimbibap, I shall scream into its ears in kind.
> feat(content): Add bimbibap to the game

- src/item.cpp
- fix #5636 which was caused by my changes to `magazine_integral()` in #5283 revealing more weird code. In this scenario `magazine_integral()` looks for a magazine adaptor and if true returns that it is false, but this doesn't account for speedloader "magazines" that don't change the fundamental nature of the gun.
- `magazine_default()` will now only return non-speedloader magazines, I'm assuming here that if a gun accepts speedloaders it doesn't accept normal magazines, I don't know any mod that does this at the moment, and if some madman does decide to do this they'll be on their own for a few months since fixing this was exhausting as is.
- `magazine_integral()` now piggybacks off `magazine_default()`, so anything that can be loaded with a magazine that isn't a speedloader …
> fix: `magazine_integral` - The Final Fix???

- data/json/effects.json
Discussion in the BN server led me to notice that the triffid pollen effect introduced in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4154 has no max duration, which is generally something we prefer not to pair with an effect being able to inflict damage over time on the player.
Along the way I spotted a few other oddities.
1. Assigned a max duration of 1 hour to triffid pollen.
2. Converted the two venom effects from integer durations to strings.
Screaming.
3. Hotboxed myself in a cloud of alien plant jizz and confirmed the debug menu showed the duration wasn't exceeding the expected amount.
> fix: cap max duration of triffid pollen, string-ify time amounts for venom effects

- src/item_factory.cpp
The morale bonus from eating a specific food drops by two every time you eat it, and slowly returns over time, to represent the PC getting bored of a particular food. The exception to this is things with the `junk_food` material, meaning candy, chips, sugary soft drinks and that sort of thing. It also doesn't apply to things that aren't considered "food" - cigarettes, chewing gum and heroin never get boring.
I think alcohol and coffee should behave more like drugs in this regard. Right now, if you drink three cups of coffee, you lose your ability to enjoy coffee, and won't get it back unless you wait several days before taking more coffee. Given that many people drink several cups per day, I don't think it really gets boring like that.
Made food items with nonzero `stim` value default to …
> feat(balance): no monotony penalty for stimulants or depressants

- data/json/items/book/dodge.json
- src/character.cpp
- tests/melee_dodge_hit_test.cpp
Base dodge is incredibly high without training, with training you become impossible to hit. We don't want to stop dodge builds from existing, but the earlygame math without mutations is too stacked from dex
Every 2 points in dex would raise dodge modifier by 1. This sets it to every 4 points. This means at 8 dexterity you will have 2 modifier without training instead of 4, and at level 10 you wall have 12 modifier. At level 10 you ensure melee 7 enemies only can hit at a 16% chance. This is also before we calculate mutations or CBMs. At level 16 Dexterity it's back to 4 modifier and 14 at level 10.
In an effort to make it easier to train dodge the books now go to 2, 3, and 5. Dodge only trains on success, this is basically mandatory until someone sets it to train on failure.
N/A
I've done …
> feat(balance): Update Dodge modifier calculations, books train you more

- src/activity_handlers.cpp
- src/bodypart.h
- src/character.cpp
- src/character.h
- src/explosion.cpp
- src/iexamine.cpp
- src/iuse_actor.cpp
- src/iuse_actor.h
- src/npcmove.cpp
- src/player_activity.cpp
- src/player_activity.h
- src/savegame_json.cpp
Slowly creeping towards removable/addable body parts
Replaces `hp_part` usage from bandaging/disinfecting `iuse_actor` and regen. For a given body part, its `hp_part` corresponds to its `bodypart::main_part`, but `hp_part` is a separate enum.
* Spawn character, bandages, antiseptic powder
* Hurt character, bandage some wounds, disinfect others
* Save+load
* Parts stay bandaged/disinfected after load
* Set body part hp to full for some bandaged/disinfected parts
* Sleep for one "sleep tick" (nearest 5 minute interval)
* Get a message about "bandaged/disinfected body part healed"
* Set hp of all parts to some value below max
* Bandage/disinfect some
* Sleep for some set time
* Notice bandaged/disinfected wounds healing faster than ones with no treatment
Possibly fixed a bug with …
> refactor: Remove usage of hp_part from bandaging and disinfection

- .github/workflows/manual-release.yml
- .github/workflows/matrix.yml
- .github/workflows/release.yml
- build-scripts/gha_compile_only.sh
Github is deprecating MacOS12. We don't have a choice. https://github.com/actions/runner-images/issues/10721
Well, I hope its as easy as doing macos-14 where macos-11 was. I don't get paid enough for this.
Do Mac players even exist? Sorry that was rhetorical, don't answer.
Nobody I know runs a Mac. We're going to run the tests and get mad in a minute if/when they've failed.
God doesn't let me be happy, he makes me work with the build matrix.
> fix: Upgrade MacOS from 12 to 14 to avoid build failure

- data/json/items/comestibles/meat_dishes.json
- data/json/recipes/food/meat.json
The bimbibap added previously was unrealistic for most survivors to actually obtain. Thus, the joy of bimbibap will be spread further by making simple bimbibap in addition to deluxe bimbibap
Also reverted the red meat part of the recipe to being raw since the fish was, and the reasoning for changing it to being cooked was never noted in the PR that changed it.
Adds simple bimbibap, a much easier recipe to make
- Implode
It loads on my machine
Would not be surprised if the caloric tests become angy on this one
Still no itemgroup additions, sorry.
> feat(content): Add simple bimbibap

- data/json/furniture_and_terrain/terrain-doors.json
Wander spawns cannot spawn on any terrain or furniture flagged as indoors. Doorways and open doors aren't indoors.
This fixes the train wreck by forcing open doors to be indoors.
Escalating.
> fix: stop wander spawns from spawning inside doorways

- data/json/clothing_mods.json
- data/json/flags.json
- data/json/items/tool/tailoring.json
- data/mods/Magiclysm/items/tools.json
Added nomex and pocketed padding, both are fairly minor additions that increase encumbrance by a little bit in exchange for a little more storage space and fire resistance.
Although some items ingame have pockets, you cannot sew pockets onto clothing, and you can't use nomex padding to make them more fire-resistant either. The number of fire-resistant clothes is actually quite few, and to be fair there are very few fire-spewing enemies.
I have added two clothing mods, pocketed and nomex padded. Pocketed gives armor more pockets, nomex padded gives them fire resistance. I also added scute to the possible list of moddable clothing, since it is just bony, scaled leather.
> feat(content): Pockets, nomex padding

- data/json/items/melee/bludgeons.json
Precise strike granting stuns that are easily re-applied is intended and here to stay, but an alternative proposed is to simply take it off specific weapons that probably shouldn't have it.
Cudgel keeps its to-hit, blocking ability, Rapid strike, and its good overall DPS, but loses precise strike.
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5672
Tests.
> feat(balance): Remove precise strike from cudgel

- data/json/clothing_mods.json
- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/clothing_mod.cpp
- src/clothing_mod.h
Lil thing I had in mind as an immediate follow-up to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5671, since coverage alone doesn't seem like an ideal control for adding pockets to clothes.
C++ changes:
1. In clothing_mod.cpp, updated `clothing_mod::load` to support `volume` as a valid modifier for clothing mod effects.
2. Also in clothing_mod.cpp, updated `clothing_mod::get_mod_val` so that volume modifiers work like thickness, except it bases it on the item's base volume in liters (should be rounded down if my understanding of the `int` definition is correct) instead of material thickness.
3. Added definition and default value of `volume_propotion` to definitions in clothing_mod.h.
JSON changes:
1. Nerfed the amount of storage `value` for the new pocket clothing mod from 3 to 1 …
> feat(balance): add support for clothing mods being modified by item volume, convert pocket mod to use that instead of thickness

- src/character.cpp
One noted issue with dodging is that failed dodges don't generate any EXP, only successful ones. This may be a potential issue since base dodge rate has recently been nerfed, and not every player can count on book-grinding using the recently-buffed books (nor do we want book-grinding to be the optimal solution).
A quick search through the files confirms that melee attacks do generate EXP at a reduced rate when you miss, so it's perfectly reasonable to allow failed dodges to also generate EXP at a reduced rate.
1. In character.cpp, updated `Character::on_hit` so that getting hit by an attack still practices dodge skill, at half the EXP gained in `Character::on_dodge`. Unlike the on-dodge one it's set to silence messages about not gaining EXP if you're being slapped by attacks too pathetic …
> feat(balance): gain dodge experience at reduced rate on taking hits

- src/construction.cpp
- src/iexamine.cpp
- src/iuse_actor.cpp
- src/veh_utils.cpp
This aims to tackle several cases where the EXP gain of certain actions pale in comparison to craft-grinding and book-grinding, when I want to generally encourage gaining skills by actually using them during gameplay.
1. In construction.cpp, set the time scaling for EXP gain in `complete_construction` to a value closer to the scaling used by crafting, dividing the duration of construction by 10 minutes (crafting seems to divide by 5, so should scale up at half the rate of crafting) instead of 30 to get the EXP multiplier.
2. Also in construction.cpp, removed the old hardcoded checks in `construct::done_deconstruct` that give you electronics EXP for taking apart a very narrow specific range of terrain, and instead have it grant it for any deconstruction where the furniture being removed …
> feat(balance): sanity-check EXP gain of several activities

- data/json/uncraft/generic.json
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5691
Lament
Tests
That's it, I'm going to bed.
> fix: styrofoam gives scraps and not chunks

- data/json/flags.json
- data/json/items/armor/torso_clothes.json
- data/json/items/book/misc.json
- data/json/items/generic.json
- data/json/items/generic/dining_kitchen.json
- data/json/items/newspaper.json
- src/flag.cpp
- src/flag.h
- src/item.cpp
A lil flavor idea that came to mind.
C++ changes:
1. In flag.cpp and flag.h, added a new item flag, `SNIPPET_NEEDS_LITERACY`.
2. In item.cpp, `item::basic_info` now skips out on printing snippet contents if the player-character has the Illiterate trait and the offending item has the `SNIPPET_NEEDS_LITERACY` flag, in which case it will instead show the item's baseline item description which normally goes unused.
JSON changes:
1. Added new item flag to flag JSON.
2. Added new flag `SNIPPET_NEEDS_LITERACY` to several note, newspaper, and such items that have snippet categories assigned. Generally most stuff whose snippets imply being able to read.
3. Updated the baseline description for several items to not imply an illiterate character can tell what's in it, since the description only shows …
> feat(UI): add a flag for displaying basic description of newspapers and similar items to illiterate characters in place of snippet contents

- data/json/items/melee/swords_and_blades.json
- data/json/mutations/mutation_spells.json
- data/json/recipes/ammo/arrows.json
A few consistency fixes and updates set aside for monster hunter weapons.
1. Gave sharktooth leiomano fine cutting 1, same as razor macuahuitl, since it was overriding the regular version only to give it the same qualities.
2. Set stinger dagger to use the same weight and damage modifiers other monster hunter weapons tend to use instead of being identical to the dagger it inherits from.
3. Removed hammering quality from recipes for stinger arrows/bolts to be consistent with stinger dagger recipe.
4. Moved fix for stinger dagger's on-hit spell not actually existing from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5704 so it can hopefully get merged sooner. No sense having it tied in with a heavier balance tweak.
Removing hammering from tooth recipes because why are you knapping …
> fix: stinger dagger no longer uses nonexistent on-hit spell, other consistency fixes for monster weapons

- data/json/effects.json
- data/mods/Aftershock/effects.json
- data/mods/Magiclysm/effects/effects.json
- doc/src/content/docs/en/mod/json/reference/creatures/effects_json.md
- src/creature.cpp
- src/creature.h
- src/mattack_actors.cpp
- src/monster.cpp
- src/savegame_json.cpp
So, a while back https://github.com/cataclysmbnteam/Cataclysm-BN/pull/89 removed code effects for some effect properties that're still used in effect JSON. Plus it'd be nice to have for the benefit of modders. On top of that, I figured I'd go ahead and use the effects for some more stuff as well.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5705
C++ changes:
1. In creature.cpp and creature.h, re-added `bash_bonus`, `cut_bonus`, and `size_bonus` updates to `Creature::reset_bonuses`, re-added functions `Creature::get_bash_bonus` `Creature::get_cut_bonus` `Creature::mod_bash_bonus` `Creature::mod_cut_bonus` and `Creature::mod_size_bonus`, re-added ability to mod bash/cut bonus in `Creature::mod_stat`.
2. In mattack_actors.cpp, set it so `melee_actor::call` takes bash and cut …
> feat(balance): bring back support for effects modifying monster bash/cut/size, use modifiers in more effects, assorted effect immunity fixes

- data/json/itemgroups/Locations_MapExtras/map_extras.json
- data/json/itemgroups/military.json
- data/json/monsterdrops/zombie_soldier.json
Military corpse drops needed checking. They had issues with what they spawned and how often
Split soldier zeds with pre-existing corpses:
**Both** groups have less shovels, keycards, and first aid kits, but more hemostatic powder and morphine
Soldier Zeds have more guns but damage is guaranteed on the primary weapon spawn. Because you fight them they can keep grenades and rockets.
Corpses have more handguns and a higher chance for primary weapon but can't spawn with grenades, rocket launchers, or grenade launchers. Those are too powerful for corpse spawns. They also have a little less food and medicals.
Overall you're going to find more hardware but less super powered weapons, less free items, and if you find a primary it will have damage.
MORE GUNS, LESS GUNS, Make Chaos do it!
Should …
> feat(balance): Overhaul military drops

- data/json/itemgroups/Locations_MapExtras/map_extras.json
- data/json/monstergroups/nether.json
Camper map extra is likely the worst in the game, it spawns mi-gos on day 1 and no firearms. Nobody loots them, except as an act of desperation or if the Mi-go got lost. Sometimes a kreck will be the problem instead so you can club those but it's not usually worth taking a kreck for the existing loot.
Gatekeep all the spawns in GROUP_NETHER_CAPTURED by time, according to Chaos this will gate it and mi-go scouts were gated correctly. Adds a 5% roll for handguns on all campers, so 1 in 20 college students were camping with hardware.
It's going to become a tiny source of early game weapons that teeters off in usefulness lategame and in general make map extras a lot safer for fresh spawns.
Also, hunters are much more likely to ACTUALLY HAVE A WEAPON TO HUNT WITH. It's almost like sane …
> feat(balance): Gate map extra nether enemy spawns by time, campers get handguns

- data/json/items/armor/power_armor.json
The power armor weapon rack has the maximum volume required to sheath a lucerne hammer (and is the *only* sheath with this distinction), and seems to be set up to allow storing nearly any melee weapon, but a missing flag prevents this.
Add ``"SHEATH_SPEAR"`` to ``power_armor_back_hardpoint``'s ``"use_action"/"flags"`` field.
Inserted and removed a lucerne hammer and survivor naginata without issue.
> feat: Allow power armor weapon racks to sheath spears

- data/mods/Monster_Girls/dreams.json
Monstergirl mutation paths, prior to this, lacked dream entries and thus would not dream. This aims to fix it by yoinking the relevant vanilla dreams and modifying them a little.
Takes the relevant vanilla dreams and modifies some of them slightly.
- Entirely new dreams from scratch
That'd be very cool, but also a lot of work. Besides, a lot of the vanilla dreams actually aren't that objectionable
- Let them be dreamless
- Keep the unused ones there as placeholders for their eventual monstergirl replacements
I just don't see the point, to be honest. It's not like it'll be difficult for me or someone else to just copy-paste them over as needed.
It lints, and I trust find-replace didn't somehow mess everything up. Aka: Eyeball tested.
Wow, someone *really* liked the plant path back when …
> feat(mods/Monster_Girls): Add monstergirl dreams

- data/json/furniture_and_terrain/terrain-windows.json
There was a request to add another variant of broken and empty window frame for tilesets.
Two new variants, with specific windows using the new variant based on request.
More?
Tests. They have looks_like so nothing to see
> feat(content): Add domestic window variants on request for tilesets

- data/json/items/melee/swords_and_blades.json
Presently, turning off an electric chainsaw (ECS) lajatang turns it into a normal chainsaw (CS) lajatang; i.e., it transforms into one that uses gasoline. If you ever turn off an ECS lajatang, it ceases to be an ECS lajatang and can't be restored.
Fixed a typo in ``items/melee/swords_and_blades.json``; the ECS lajatang (on)'s ``use_action`` specified it should become ``cs_lajatang_off`` instead of ``ecs_lajatang_off``.
Turned an ECS lajatang off and on again to confirm resolution of its identity crisis.
Interestingly, if the ECS lajatang had a UPS mod installed, it will 'charge' the CS lajatang's gasoline tank when not in use.
> fix: Stop electric chainsaw lajatangs from reverting to gasoline

- data/json/bionics.json
- data/json/items/fake.json
- src/bionics.cpp
- src/character.cpp
- src/crafting.cpp
- src/visitable.cpp
Now that we have a case where the voltmeter's actually being used as a tool, it'd be good to extend the voltmeter function of the electrosense CBM to be usable for that too.
As a side bonus it comes with taking us another step closer to being able to do more with JSONized bionic functions.
C++ changes:
1. In bionics.cpp, set it so that electrosense's voltmeter uses a different fake item specified below. Nothing really changes with this in how the bionic works when activated, but good for consistency and for later plans I had in mind involving JSONization of activating bionics.
2. In character.cpp, updated `Character::use_charges` to handle charge use when drawing on electrosenses' voltmeter as a tool.
3. In crafting.cpp, set `Character::crafting_inventory` so that the check for bionic …
> fix: electrosense CBM's voltmeter can be used in advanced deconstruction

- data/json/mapgen/nested/residential_lawn_nested.json
because the scooter and its tarpaulin are placed outside the nested mapgen boundary.
I changed the position of the scooter and the tarpaulin.
none
Before:
After:
> fix: change the scooter position in `res_backyard_scooter`

- src/iexamine.cpp
I spent ages gathering the materials to make half a dozen wind mills, a grand army of giants whose mighty arms would be a match for the strongest of Spanish knights, only to find they only hold as much corn as a smoking rack that only takes 8 rocks and 16 planks to make.
Suggested buffing up the capacity and was told to go full send it and make it 100 liters in capacity:
1. In iexamine.cpp, added definition `MAX_FOOD_VOLUME_MILLING` to `sm_rack` namespace (which is also used by mills), set to 100 liters.
2. In ther same file, changed `mill_activate` and `iexamine::quern_examine` to use `MAX_FOOD_VOLUME_MILLING` instead of `MAX_FOOD_VOLUME`, thus bumping capacity from 20 to 100 liters.
1. Only increasing capacity to 50 liters like my very first initial idea.
2. Sanity-checking corn because …
> feat(balance): allow mills to hold more food than smoking racks

- data/json/items/comestibles/drink.json
- deno.lock
Dandelion tea as well as dandelion and burdock tea have the vitamins their respective ingredients have.
Dandelion based teas should have vitamins as they're commonly drank for this reason IRL.
Add the vitamins in their respective ingredients to the dandelion based teas.
Not doing this.
Doing spectroscopic analysis of dandelion tea to ensure exact accuracy of vitamin amounts. Unfortunately I do not own a near infrared spectrometer and they can cost up to $100k, so this would delay the PR significantly.
Made changes on my end and saw that dandelion teas have vitamins.
> feat: Dandelion teas have vitamins

- deno.lock
- src/player.cpp
- src/player.h
Lua currently only binds the `cash` property of `Character`, not `player`, therefore Lua cannot access the actual cash value of NPCs and avatar. Removing the duplicate `cash` from `player` will make C++ use `Character`'s `cash` and for the Lua to work.
- None.
1. Testing whether existing characters retain their cash:
1. Made a new character with a version of the game prior to this change;
2. Placed an ATM terrain and spawned a cash card item;
3. Deposited some cash into the ATM;
4. Saved and exited the game;
5. Loaded the character in a version with the changes;
6. Checked the ATM;
7. The cash amount displayed by the ATM didn't change.
2. Testing whether LUA can change the cash amount now:
1. Loaded a character;
2. Placed an ATM terrain;
3. Checked the current cash amount through the ATM; …
> fix: remove `cash` property from `player` class to use `cash` from `Character` for Lua

- data/raw/keybindings/keybindings.json
- src/character.cpp
- src/character.h
- src/mutation_ui.cpp
- src/savegame_json.cpp
Much like with hiding clothing, hiding traits and mutations is a much-desired feature for various reasons. Considering how much it's desired and how simple it was to port, I see no reason not to bring it in.
Ports https://github.com/CleverRaven/Cataclysm-DDA/pull/52058 from DDA.
- Reinvent the wheel
- Implode
- Explode
- Wait for someone else to do it
It builds, it works (on my machine anyway)
2/3 of the hiding visuals ports that RoyalFox threw at us done. Next up, Bionics! (For whoever ends up taking that one on)
Don't worry Chaos, this time I made sure the keybind was BN-ified the first time ;P
> feat(UI, port): Port hiding traits/mutations from DDA

- data/json/items/fuel.json
During discussion of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5750 it was noted that methanol should have a lower fuel value than ethanol or denatured alcohol, both since that's how it is IRL and for game balance reasons since methanol uses much simpler ingredients.
Bumped the fuel value of ethanol (and by extension, denatured alcohol) from 15.6 to 24, with methanol now being explicitly set to use 15.6 as its fuel value.
In short, 15.6 MJ/L is the general value given for methanol as fuel IRL from most figures I could find, we bsically had it set so that all three alcohol types were using that value. The fuel values for ethanol I've seen range from 21.2 to Kheir saying they saw a value as high as 29, but 24 was the most common answer I could get.
For simplicity, denatured …
> feat(balance): ethanol and denatured alcohol have higher energy density than methanol

- data/mods/Monster_Girls/vanilla_mutations.json
Due to not marking the mutations invalid, even when they had no mutation category, generic mutagen could still mutate a bunch of undesirable mutations. I had never intended for this to be possible, and thus this is to remedy this
Adds `"valid": false` to any mutation that doesn't have a valid monstergirl category for it.
- Leave it be, maybe generic mutagen can be allowed to still be body horror because unrefined and all
Fair, and if opinion swings that way I can definitely consider removing it. But ehhh, it was never my intention in the first place for them to still be mutatable.
If marking mutations as invalid doesn't work properly, that's
A. Not my fault
B. A much bigger problem overall
Gave it the good ol' lookover, everything the script did seems fine.
This also did a lil bit of …
> fix(mods/Monster_Girls): Invalidate non-monster girl mutations

- data/json/items/armor/arms_armor.json
- data/json/items/armor/legs_armor.json
This applies some consistency updates to armguard and legguard/greave items, with the goal of making the layer they're on more consistent with their torso and suit counterparts. The majority of such items tend to be on the outer layer, so it'd be reasonable to have most of the arm and leg items match on layer used. Plate and paper items were notably consistent with this already, being outer layer (as plate cuirass) and strapped layer (as bookplate) respectively.
1. Set bronze greaves and leg guards to `OUTER` layer, matching that of bell cuirass. Also affects metal/item arm guards/greaves, since bronze arm guards inherit from metal arm guards. Bone greaves likewise affected due to inheriting from bronze greaves.
2. Switched hard neoprene arm/leg guards to `OUTER` layer, since the chest …
> feat(balance): set arm guard/greave items to use same layer as comparable torso armor items

- src/catalua_bindings_creature.cpp
- src/mutation.cpp
Current Lua bindings for Creature objects are somewhat incomplete. In particular, there is no way to cleanly disable a mutation, or enable one at all.
Added a couple of lines in ``src/catalua_bindings_creature.cpp``. Now we can do this:
```lua
muti = MutationBranchId.new("WEB_WEAVER")       -- pick a disruptive example
gapi.get_avatar():set_mutation(muti)            -- force it onto the player
gapi.get_avatar():activate_mutation(muti)       -- weave a tangled web
gapi.get_avatar():deactivate_mutation(muti)     -- free the player from themselves
```
I also added a few lines in ``src/mutation.cpp``. Its corresponding activate/deactivate_mutation functions now check if the player has the necessary target—i.e., they have the mutation and it is (in)active.
The alternative looks roughly like …
> feat: Add Lua bindings to toggle mutations on/off

- data/json/itemgroups/Clothing_Gear/clothing.json
- data/json/itemgroups/Locations_MapExtras/locations.json
- data/json/items/tool_armor.json
- data/json/obsoletion/items.json
- data/json/obsoletion/recipes.json
- data/json/recipes/armor/head.json
- data/json/recipes/armor/suit.json
So I belatedly didn't really as deep of a look at https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5679 until recently and realized that the item variations are unnecessary, since having a single piece of clothing with the climate control flag will apply the effect to the whole body, not just the parts covered by that item. We can justify only bothering with the torso+arms+legs version providing a full-body effect via it affecting core body temperature, and obsolete the mask and full-body versions instead.
1. Moved the original full-body cooling outfit and the cooling balaclava to obsolete folder and obsoleted the recipes for them. Also added a JSON comment to the balaclava noting how it might be useful if we make climate control bodypart-specific in the future.
2. Reworded the …
> fix: replace full-body and balaclava cooling items with suit variant, clarify full-body effect in item description

- data/json/items/classes/gun.json
- data/json/items/gun/misc.json
- data/json/items/gun/nail.json
- data/json/items/gun/ups.json
- data/json/items/magazine/chemical_spray.json
- data/json/items/magazine/liquid.json
- data/json/items/ranged/pneumatic.json
- data/json/items/ranged/spearguns.json
- src/character.cpp
This fixes weapons like the BB gun saying they only take 500 moves to reload but then taking entire minutes due to weird code stuff.
C++ changes:
1. In character.cpp, `Character::item_reload_cost` now only multiplies the reload rate of an item by how many bullets it has to insert if the item's a magazine. Guns will always use just the reload rate. This doesn't affect guns swapping mags or `RELOAD_ONE` guns, but instead the few weapons that still use clip size but reload all ammo at once.
JSON changes:
1. Changed reload rate of flamethrower base class from 4 to 400. Flamethrowers no longer have internal mags anymore but use magazines, so the low time it seems was likely a hack for when they used clip size.
2. Set pneumatic speargun's reload rate from an absurd 6000 moves to 1000, to be …
> fix: internal-mag guns that lack `RELOAD_ONE` no longer massively inflate reload cost

- data/json/monsters/nether.json
- doc/src/content/docs/en/mod/json/reference/creatures/monsters.md
- src/monster.cpp
- src/monstergenerator.cpp
- src/mtype.h
@RoyalFox2140 mentioned a desire for a more generic way to spawn a monster on death similar to how `mon_dog` and `mon_tentacle_dog` spawn `mon_thing` on death using the `"THING"` death function which calls `mdeath::thing`.
Added a new JSON field to contain actions to take on monster death, including but not limited to spawning monsters. The solution keeps the current `mtype::dies` functionality using pointers to `mdeath::` functions. Spawning a single zombie is done using:
```json
"on_death": {
"spawn_mon": "mon_zombie"
}
```
and multiple zombies can be spawned using:
```json
"on_death": {
"spawn_mon_near": {
"distance": 3,
"ids": [ "mon_zombie", "mon_zombie", "mon_zombie_anklebiter" ]
}
}
```
When using `"on_death"` and need to specify `"death_function"` values they can be embedded in …
> feat: add generalized monster spawning on death

- data/json/itemgroups/art_antiques_crafts.json
Elephant guns are the only weapon to fire .700 nitro express and they were incredibly rare due to being buried in distributions. Your local antique shop now doubles as an elephant protection shop.
All medieval weapons in antique_rare got moved to antique_medieval_arms which means now antique_rare is funny rocks and guns.
Convert to Collection but Chaos screamed in pain.
I own an elephant gun for home protection because that's what the founding monster hunters intended. Four dragons break into my house "What the devil?" As I grab my elephant gun and funny baseball cap with an inappropriate slogan that won't age well. Blow a golf-ball size hole in the first dragon, its dead on the spot.
> fix: update antique shops, elephant guns are now reasonably obtainable

- src/iuse.cpp
- Fix #5789 which was a bug exposed by #5589. iuse actions in `iuse.cpp` return an int value that indicates charges to be used from an item, but this wasn't properly being used due to a lack of consideration in `use_charges()`.
- The RPG die iuse returns the roll value for no reason whatsoever, as nothing the iuse does is contingent on that return. It's likely some legacy thing from when each iuse had it's own special return function.
- `iuse::rpgdie` now returns 0 in all cases, preventing charges of rpgdie from being used.
- Reverting #5589 
- Would be a dumb idea given that the behaviour it fixes is not expected behaviour.
- Rework `iuse::rpgdie`
- It's on my list, as of current, the die faces and values are totally random, I'll likely convert it into an `iuse_actor` later on so that …
> fix: Fix RPGdie iuse

- src/item.cpp
Currently, books stop showing how far they can teach once they can no longer teach the PC. They're still useful for teaching NPCs, though; after that point, only the ``R``ead command will show the skill they can teach to.
This synchronizes that functionality for the sake of convenience.
I made a few very minor edits to ``item::book_info()``.
N/A. This was pretty simple.
Spawn a book → look at the book → set your skill level higher than the book's cap → look at the book again.
> feat(UI): always show book's skill cap even if the PC has passed it

- data/json/furniture_and_terrain/terrain-manufactured.json
- data/json/recipes/other/other.json
- src/iexamine.cpp
- src/iexamine.h
The [recent changes to Advanced Deconstruction](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5722) make plutonium generators significantly more irritating to retrieve. While this *is* a good change overall, for those of us who took them and disassembled them (instead of installing them somewhere), it's a little frustrating.
I've added a few functions, and adjusted the terrain object's JSON, so that military ID cards can be used to turn the terrain into an item without deconstructing it. I think this is reasonable: military ID cards are typically used to claim military items, so spending one to gain access to a military generator (instead of a military *armory*) seems fair.
Note that this does not give the other items that deconstruction would. The idea is that the generator …
> feat: Military ID cards can deactivate plutonium generator security for retrieval

- data/json/items/gun/20x66mm.json
- data/json/items/gun/shot.json
As agreed by others in the Discord, it makes little sense for even sawn-off shotguns such as these to be classified as 'pistols' skill, especially when they're marked down as shotguns for weapon category purposes.
Changes them over to shotguns skill instead (by just making them not overwrite their copy-from's entry)
- Let it be
None, other than the eyeball test
Just because the terminator can flip-cycle a sawn-off lever action shotgun (with a modified lever mind you) doesn't mean it's now legally classified as a pistol. Shotguns Arnold is an outlier and should be excluded.
> fix(balance): Move 3 small shotguns to shotguns skill

- src/iexamine.cpp
When using the light switch the `iexamine::toggle_lights` was giving the wrong message to the player ("You switched off the lights." when turning them on and viceversa), turn out it was because the function was changing the state of the switch before retrieving it's message.
Simply moving the line displaying the message to before changing the furnitures.
Retrieving and storing the message in a variable so the message still get executed in the end of the function, however this is kinda going back on a scarf review in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5626#discussion_r1826885029_
> fix: Fixed the message given to the player when using the light switch.

- data/json/furniture_and_terrain/terrain-doors.json
- data/json/furniture_and_terrain/terrain-walls.json
- data/json/furniture_and_terrain/terrain-zlevel-transitions.json
Because I made zombies do more damage, they started breaking stairs and ladders, trapping players in basements to die of starvation.
Also, wooden doors and walls are easier to smash which causes problems.
A number of sweeping bash min buffs, just to quickly hotfix this problem out so it stops happening.
Let's just overview the 500 door and wall variants we have, and fix all in one PR. That would be fun.
Tests. I know that zombies do 8-12 damage as is so I know this will work. This isn't going to stop evolutions either, not all of them. You shouldn't get in a basement trap unless its late game evolution, maybe midgame.
You got a license to fix those stairs, m8?
> fix: Stop letting unlicensed zombie contractors break stairs

- data/json/itemgroups/Food/food.json
Make bibimbap (and gochujang) more accessible
- Places gochujang into the `condiments` itemgroup at a similar rate to horseradish
- Puts bibimbap into `fridgesnacks` and `fridge_leftovers_random`
- Put together / wait for a different, more specific itemgroup
- Let someone else decide where to put 'em
None, I don't think adding an item to these itemgroups should ever bork things
I keep thinking it's "bimbibap" rather than "bibimbap" because that's what I called it for the longest time.
> feat(balance): Put bibimbap in itemgroups

- data/json/mapgen/parking_garage.json
Damage all the vehicles in the parking garage because I don't think it's good to have so many vehicles in perfect condition in this location.
Set the status of all vehicles to -1 (light damage)
none
none
none
> feat(balance): light damage to all vehicles in the parking garage

- data/json/effects.json
A suggestion that came up in the BN discord was making the prussian blue and iodine effects visible on the effects screen since it can be hard to tell it's doing anything otherwise, and since antibiotics in BN are directly visible instead of hidden we don't have to fiddle with abstracting it behind a separate dosage-tracker effect.
Along the way I noticed the effect also really doesn't seem like it recovers very much radiation, and after some quick math uh...yeah.
1. Added names and descriptions to the prussian blue and iodine effects.
2. Reduced `chance_min` of prussian blue from 600 to 100. This should make it recover roughly 36 rads across an hour, which combined with the natural recovery rate makes for a 50% increase over just toughing it out (before it made you lose rads ~8.333% …
> feat(balance): prussian blue and iodide effects visble on status screen, increase effectiveness of prussian blue

- src/character.cpp
To try fix the problems described in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5113. I have added an increase to stealth when crouching. Also lowered the minimum visibility you can have via crouching and mutation.
The value used is based on the mutation "Crafty" more or less. 
Would also be nice for player size to have a bigger effect on stealthiness but I leave it for another PR.
Added check for player crouching affecting the total stealthiness rating.
None really.
Loaded new character, crouched around bunnies and see that I can get closer to bunnies without them warping out of the visibility bubble.
This is a starting point to fix https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5113.
> feat: Crouching affective player visibility

- data/json/vehicleparts/motor.json
A lil thing that came up in discussion of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5805, enhanced motor's item form is made of superalloy, flavored as being lighter and more efficient than a regular motor of its size, and if made craftable likely should use superalloy in its recipe, BUT the vehiclepart returns just plain metal in its `breaks_into` entry.
Since balance discussion of a recipe for it is still ongoing I decided to eyeball its breakdown results in a separate PR.
Changed the `breaks_into` entry for an installed enhanced motor, returning as many alloy sheets as it previously did steel lumps. Steel chunks removed from the breakage results outright, scrap metal was retained since it could be from other components in the motor breaking down into scrap.
1. A …
> feat(balance): enhanced electric motor breaks into alloy sheets

- data/json/vehicleparts/frames.json
Somehow, the carbon fiber and plastic frames had their durability stats mixed up, with carbon fiber being weaker than plastic.
Plastic frames now have 250 durability and carbon fiber have 500.
> feat(balance): Plastic and Carbon Fiber Frames Have Appropriate Durability

- .github/workflows/manual-release.yml
- .github/workflows/osx.yml
- .github/workflows/release.yml
- doc/src/content/docs/en/dev/guides/building/makefile.md
- src/sol/sol.hpp
- fixes #5755 
From what I can understand, OSX builds weren't building due to apple clang being different from normal clang.
I've updated the workflow files to use llvm clang from brew (`COMPILER=$(brew --prefix llvm)/bin/clang++`) and install the dependencies required for building (on my Mac, at least): `llvm astyle` from brew and `polib luaparser` from pip.
A line of code in `src/sol/sol.hpp` around line 6759 had to be changed to make the builds work, but I won't admit to knowing what I did to fix it, because chatgpt was a very poor explainer. 
Also adds `osx.yml` for building OSX in the same way that there exists `android.yml` and `msys-cmake.yml`.
1. Fixing the part of the code that broke OSX builds in the first place
It felt like a more complete solution to me to completely decouple …
> build: update OSX builds to llvm clang

- src/game.cpp
- src/game.h
- src/options.cpp
The option "Prompt on death" gives the player the option to keep it's save when dying instead of deleting it, however the prompt it gives for that it's a bit unclear asking if you want to return to the main menu or abandon your character to their fate, it's also a bit of chore having to load the save again from the main menu.
As for the quickload option that's found in `game.cpp` this action seems to have been broken for a long time according to searches in the Discord. 
Now on selecting 'No' it uses the `game::quickload()` function to load the last saved game.
The `game::quickload()` function was fixed by  copying a version of `game::setup()` and replacing the one used by the quickload, this version is the same except it doesn't load the world mod files since they are already loaded and …
> feat: `Prompt on death` quickloads instead of going to main menu

- data/json/mapgen/chemical_lab.json
Replace the wooden floor under the small cabin standing tanks with outdoor terrain.
Set "0" in the mapgen `chemical_lab_ocu` to use the same terrain as "~"
none
Before:
After:
> fix: replace the wooden floor under the standing tanks of the small cabin

- data/json/flags.json
- data/json/mutations/mutations.json
- data/json/npcs/starting_traits.json
- data/json/obsoletion/mutations.json
- data/mods/Aftershock/npcs/Backgrounds/trait_groups.json
- data/mods/Aftershock/npcs/mutant_npcs/trait_groups.json
- doc/src/content/docs/en/mod/json/reference/json_flags.md
- src/morale.cpp
- tests/morale_test.cpp
It felt a little silly to have to spend two whole points on your character appreciating wearing fancy clothing. Plus, it generally makes more sense for liking fancy clothing to be the default behavior.
- Obsoletes `Stylish`, making its behavior the default state
- Adds `Fashion Deficient`, a new negative trait that takes away the morale boost for 1 extra point during character creation.
- Updates the relevant docs on JSON flags (and comments in the json file itself)
- Updates the NPC trait generation lists to instead be `UNSTYLISH` instead of the now-obsolete `STYLISH` (except No Hope, because it's funny)
- Do nothing
- Just reduce the cost of `Stylish`
Still feels a bit weird to have to spend points on what *should be* default behavior (and a 0-point trait would just be weird)
- Increase …
> feat(balance): Make Stylish trait the default behavior, add Unstylish trait

- data/json/deconstruction.json
- data/json/furniture_and_terrain/furniture-appliances.json
There was a way to deconstruct the grid plut gen into components through construction. This takes it out
Sets it so the resources granted on deconstruction of grid generator correctly drops the generator and its power converter/wiring.
More Coffee
Tests
I don't even know how this happened, and I don't think I want to know.
> fix: Stop accidental plut gen destruction

- data/json/mapgen/petstore.json
Add more items to `s_petstore_1` because there's virtually no loot here if we compare this pet store with the others.
Took some of the `items` defined in `s_petstore` and used them here.
none
Before:
After:
> feat(balance): add more items to `s_petstore_1`, replace `cleaning` with `SUS_janitors_closet`

- data/json/monsters/zed-winged.json
Add "path_settings" and `PATH_AVOID_DANGER_1` to flying zombies
Confirmed that Flesh-raptors can attack a character directly below them.
During testing, I noticed that the flying zombies wouldn't go down one z-level.
> feat(content): Add "path_settings" and `PATH_AVOID_DANGER_1` to flying zombies

- data/json/overmap/overmap_terrain/overmap_terrain_commercial.json
Stop showing `loffice_tower_16` as open air on the overmap because like `loffice_tower_13`, `loffice_tower_14` and `loffice_tower_15` `loffice_tower_16` is supposed to be named on the overmap Large Office Tower
Deleted the duplication of `loffice_tower_16` on line 1178 of overmap_terrain_commercial.json
none
Before:
After:
> fix: stop showing `loffice_tower_16` as open air on the overmap

- data/json/construction.json
- data/json/furniture_and_terrain/terrain-manufactured.json
The tarp lean-to's description said it could be used to shelter a fire, but it could not. This lets it be accurate to its description (and have other furniture too I guess)
The fire ring was restricted to only being placeable on specifically dirt and nothing else. This felt like an unnecessary restriction (and didn't allow for the fire ring to be sheltered by the tarp), so I opted to just let it be constructed on any (`FLAT`) terrain.
- Adds `FLAT` to the tarp lean-to
- Removes the pre-terrain requirement in the fire ring's construction
- Specifically allow the fire ring to also be constructed on the tarp lean-to
This doesn't actually solve the issue, because there are innumerable sensible `FLAT` terrain options that it could be put on, and manually adding them all would be ridiculous. …
> fix: Let tarps actually shelter fires, let fire rings be used more

- data/mods/Monster_Girls/categories.json
- data/mods/Monster_Girls/dreams.json
- data/mods/Monster_Girls/migration.json
- data/mods/Monster_Girls/mutagens.json
- data/mods/Monster_Girls/recipes.json
- data/mods/Monster_Girls/thresh_mutation.json
- data/mods/Monster_Girls/vanilla_mutations.json
More monster girl mutation paths is better so as to avoid overly narrowing player choice.
Kitsunes seemed like a fitting choice for a sort-of beast equivalent, being a bit of a mix between dogs and cats.
Adds the Kitsune mutation tree, basing them off of the existing Beast tree (and a little bit of Feline)
- Implode
- See if a mod has done a good Kitsune path and politely ask to base the monster girl one off of theirs
I tried looking for Shard's one, but couldn't find it (and by the sounds of things, that one got left in WIP hell)
It loads on my machine, and the linter didn't complain
Kitsune-Neko alliance goes hard
I should probably make proper orange ears / tail in the future. (even if it's just recolors of what I'm using right now)
> feat(mods/Monster_Girls,content): Add Kitsunes to Monster Girls Mutations

- src/visitable.cpp
Fixes #5026
The inventory now correctly stores the items current location and resets it to that rather than just using itself when it's removing things. 
I managed to reproduce #5026 reliably. The random aspect is due to the call to x_in_y in item.cpp:10013. If you force that to true the bug will happen. 
I'm going to go through the code this afternoon and make sure there's nowhere else that I got it wrong like that.
> fix: inventories not saving locations properly when removing things

- data/json/mapgen/homeless_shelter.json
Replace the linoleum tile under the dumpsters of the homeless shelter with concrete because it seems more logical to me that concrete should be under these dumpsters.
Modify `homeless_palette` to place concrete floor under the dumpsters.
none
Before:
After:
> fix: replace the linoleum tile under the dumpsters of the homeless shelter with concrete

- data/json/vehicles/carts.json
- src/vehicle_use.cpp
Allows folding a vehicle to work (presumably) as intended, and return the specified item. Previously, if someone added a new item `"skateboard"` and refolded it after placing it down, it would return a folding_bicycle item. Now it will return the `"skateboard`" item. Also changes name of the folding wheelchair, and the way folding vehicle names are created. Previously it would fold into "folded Folding wheelchair" now just into "wheelchair."
Unhardcode the string `"folding_bicycle"` and make it return `itype_id` instead when specifying the `folding_veh_item`.
Spawned unicycle and wheelchair, they work as expected upon folding/unfolding. Spawned a folding_bicycle item, works as expected. Created a test item folding_flatbed which unfolds into a flatbed truck, and upon it being refolded it …
> fix: folding vehicles fold up into proper item

- src/character_functions.cpp
- src/character_functions.h
As expressed by many, not allowing the survivor to use a pillow and a teddy bear at the same time is ridiculous. People use multiple pillows, cuddle a stuffed animal or body pillow while using a normal pillow, etc. As such, this is clearly a highly-desired change and is in-fact more realistic than how it was before.
Also, if any balance hinges on only one sleep aid being allowed, we have bigger problems.
- Removes the `break` lines that prevent multiple sleep aids from being used
- Converts `comfort_response.aid` into a vector instead of an item pointer
- Prints out each comfort aid you're making use of instead of just one
- Pillow (not body pillow) specific flag to allow you to use a pillow and a normal sleep aid
Doesn't adequately account for the use cases.
- Simply adjust the limit to …
> feat(balance): Allow for use of multiple sleep aids

- data/json/overmap/overmap_terrain/overmap_terrain_industrial.json
Ensure that the symbol for the light industry roof and the symbol for the data center roof of the industrial center are correctly oriented.
I changed the `copy-from` of `industrial_center_light_industry_roof` and `industrial_center_data_center_roof`
none
Before:
After:
> fix: symbol orientation of the light industry roof and data center roof of the industrial center

- data/raw/keybindings/keybindings.json
- src/bionics.cpp
- src/bionics.h
- src/bionics_ui.cpp
- src/character.cpp
allows bionics to be hidden
ports dda PR
- https://github.com/CleverRaven/Cataclysm-DDA/pull/65243
> feat(port,UI): Allow Bionics to be hidden

- doc/src/content/docs/en/mod/json/reference/json_info.md
DEBUG    : Could not find a trapfunc function matching 'cast_spell'!
FUNCTION : const trap_function& trap_function_from_string(const std::string&)
FILE     : src/trapfunc.cpp
LINE     : 1522
VERSION  : BN 22673e8
~~Maybe everyone should suffer as much as I do~~
My own traps work.
> docs: `cast_spell` doesn't exist, correct function is `spell`

- doc/src/content/docs/en/mod/json/reference/json_info.md
This is invalid, it causes errors if you use it. I don't know why it was removed, I need to ask.
Some secrets are best left buried?
Mine work, the auto sear works.
> docs: `burst_modifier` is orphaned, use `mode_modifier`

- src/iuse_actor.cpp
- Fix #5868 which is due to #5589 which makes iuse actors/iuse returns actually consume charges the way they're supposed to. Exposing code that was written with returns that returned values that _didn't fucking do anything._
- fireweapon iuse code now properly returns 0 if the item is reverted/deactivated instead of trying to consume it's charges.
- Remove fireweapon code.
- That's on the docket and part of the energy rework, but I don't want to produce any conflicts at the moment given that the energy rework is already a monumental PR that will be hell to test.
@chaosvolt Help me test please I have work.
I fucking hate when fixing code causes issues.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/c75fb01f4983c9ab57355e3f0cf0fd39b43b3ba2/src/iuse_actor.cpp#L2260-L2271
Dear lord in …
> fix: More charge usage shenanigans (fireweapon edition)

- src/item_factory.cpp
The previous PR set it so item groups were tested at 1000 hits. This isn't useful to us for getting an accurate picture of what will likely spawn in a run. This has caused difficulty for Chaosvolt and I to work on item groups, and caused Chaosvolt to overlook a flaw in my drugdeal itemgroup PR where he disagreed with my specific spawnrates.
Github Revert
Make Oren code it to be configurable.
Don't need to, it's an automatic Git Revert.
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5033
> revert: "raise amount of itemgroup tests from 100 -> 1000"

- src/item_factory.cpp
When testing item distributions in item groups we don't always need to check 100 or 1000 iterations of item spawning. Making it configurable seems like the best compromise to match user desire by allowing options for how accurate they want to be while testing an item group's spawns.
Compromise for #5033 and #5872 
Adds an additional picker UI for how many iterations to run while testing item group spawns. Provides logarithmic progression options: 10, 100, 1000, 10000. More options can be added, or it can be changed to a text input, in a future PR if these options are not satisfactory.
I'd like to make it so we don't need to spawn items at all, even temporary items, and make it purely mathematical. Pick an item group, and then it calculates the chance of an item to spawn as if there were …
> feat(UI): add iteration config for item group debug spawn test

- src/mutation.cpp
If spells can do it, so should mutations be able to. Plus, it's weird having all the liquids spill on the floor for no good reason.
Basically just yoinks the solution in #3637 by adding a check if the spawned item is a liquid.
- Implode
- Add the rest of the checks from spells spawning items
Not a bad idea, but unsure if all of them are actually desired. Liquids, on the other hand, are clearly wanted.
It builds on my machine, and it works on my machine too.
If you choose the option to store it in a container but have no valid container, it just exits out of the menu without putting it in your inventory, consuming it, or spilling it on the floor.
Unsure if I should give co-authorship to Vollch or not for this, so I opted to credit him in the commit message and split the difference.
Altered …
> feat: Allow mutant-spawned liquids to be stored/consumed

- data/json/items/comestibles/carnivore.json
- data/json/items/comestibles/mutagen.json
- data/json/items/comestibles/other.json
Human fat and several other items got missed in my initial sweep.
Adjusts my local copy of the vitaminer script to lazily add the human flesh vitamins
- Leave it be
- Create a python script instead
I looked at the changes with my eyes and made sure they make sense
Thanks Royal, I can't believe I missed them.
> fix: Properly add human flesh vitamins to several comestibles

- doc/src/content/docs/en/dev/reference/tooling.md
Docs hasn't been deploying since[ approximately 3 months ago](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5497), meaning any documentation changes in the meantime just never showed up on the website.
Fixes the invalid link by properly linking to it instead of trying to do a relative path.
- Let Scarf know and have him fix it
- Weh
Unable
I find it really funny that Scarf literally made the docs, but also made the PR that stopped them from deploying for 3 months
> docs: Properly link to custom clang-tidy plugin instructions

- data/mods/Item_Category_Overhaul/categories.json
We don't want stuff to overlap. Item categories were all 1 after the other. Modders couldn't put stuff where they want.
I staggered every category by 3. Now you get 2 categories to inject between any other. Nothing changed under the hood
Mods can fight if they want, I'm not a cop but maybe try not to use categories unless you **have** to.
Suffering. Making others suffer by figuring out a code-based solution that lets users sort categories themselves.
Someone should code it so users can organize their own categories, but I can't.
> feat: Stagger item categories for modder support

- data/json/items/armor/ballistic_armor.json
- data/json/items/armor/torso_armor.json
- data/mods/TEST_DATA/items.json
- src/item_factory.cpp
Fix #3861
Use `assign` in a hacky way to have it handle the fields properly.
Revert the armor portions thing - it won't help us much, but it is certain to cause trouble until we rewrite the jsons to the new format.
* Spawn chitin gauntlets and biosilicified chitin gauntlets
* Compare encumbrance - biosilicified should have 15 encumbrance, while regular should have 10
* Load world with Magiclysm
* Spawn chitin gauntlets and demon chitin gauntlets
* Demon chitin gauntlets should have 9 encumbrance, while regular should have 10
> fix: Handle "relative" and "proportional" with encumbrance

- data/json/mapgen/nested/roof_nested.json
Solar roofs go from 8, to 9, to 16 panels on residential homes. They're also very common. I think dialing it back should be okay, houses are something you spend all game securing and looting.
The odds were at a distribution with 30 odds of nothing, and 5 odds for 8, 9, and 16 panels respectively. This is 11% chance per solar odd, and a total of 33% for any solar. I think this is too high.
I've set a 15% chance for solar panels, at 2% odds for 16 panels, 8% for 8 panels, and 5% for 9 panels. This is still a significantly large amount as 8 panels is amazing to find. at 15% chance per house you're generally going to find one house in a neighborhood of 10 homes that has these panels. Whereas before every third house would have solar statistically (For each home which calls this nested mapgen …
> feat(balance): House solar odds lowered from 33% per home to 15%

- data/json/npcs/missiondef.json
- data/json/npcs/necropolis/NPC_Old_Guard_Captain.json
- data/json/npcs/refugee_center/surface_staff/NPC_free_merchant_shopkeep.json
- data/json/npcs/refugee_center/surface_visitors/NPC_old_guard_representative.json
- data/json/npcs/robofac/NPC_ROBOFAC_MERC_1.json
- data/json/scenarios.json
- src/mission.h
- src/mission_util.cpp
This extends the range of mission search if search range is undefined, along with some other improvements ported from DDA. Shifting missions to not be limited in search radius will be useful for when https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5723 is merged, as it may become a drunken crapshoot how far off a true-unique location will end up being.
C++ changes:
1. In mission.h, set the default search range to the expanded value used in the above DDA PR. I don't think it's actually unlimited but it is de-facto vastly more than a playthrough will be able to exceed.
2. In mission_util.cpp, ported over the message change where failure to find a mission target now tells you the distance it was told to search.
JSON changes:
1. Removed no longer nessecary search ranges from all missions …
> feat(port): increase default search range for mission placement, sanity-check search properties for scenario missions

- src/inventory.cpp
- fixes #3885
Bugfixing! Multiple faucets (and things that act like faucets, such as the kitchen vehicle part(s)) in a vehicle will, when all within crafting range, *each* report the vehicle's entire quantity of various liquids available...meaning you can get told that you have 2×, 3×, 4×, or more of whatever you need to make something.
Obviously suboptimal.
Made inventory::form_from_map keep a mapping of vehicles and their relevant parts that it has checked (and accepted as providing features), and made each successful vpart_reference check add to the set of parts for that vehicle.
Crying quietly.
Make or find a vehicle with a liquid used to craft; check the crafting menu to see the expected amount of fluid there is to work with; add 2+ water faucets; watch as the found (available) …
> fix: multiple vehicle faucets no longer multiply supposedly-available crafting materials

- data/mods/replacements.json
As pointed out by Oren, I literally touched a solution that's meant to replace mods we deleted... but I didn't actually set it up to replace Magiclysm with Magical Nights. My bad!
Actually marks Magical Nights as a replacement for Magiclysm in the file
- Watch as the world(s) burn
- Explode
I made sure the Magical Nights ID is correct
Thanks Oren!
A day late is better than never, right?
> fix: Migrate worlds with Magiclysm to Magical Nights Properly

- data/json/mapgen/Pottery_Sewing_Shops.json
Sidewalk instead of wooden floor under the vending machines of `craft_shop_2`, because it's obvious that wooden floor has no place under these vending machines.
Place sidewalk under the vending machines.
none
Before:
After:
> fix: sidewalk instead of wooden floor under the vending machines of `craft_shop_2`

- data/json/mapgen/Glassblower.json
Fix because there are flying flat roofs without support on level 3 of the glassblower craft shop.
Replace the wooden floor, `t_floor` on the `craft_shop_roof` patio with `t_floor_noroof`
Remove `t_open_air_rooved` from the mapgen `craft_shop_upper_roof`
none
Before:
After:
> fix: remove flying flat roofs in the glassblower craft shop

- data/mods/Magical_Nights/Spells/monsterspells.json
- data/mods/Magical_Nights/monsters/golems.json
Plastic golems were notoriously cheesable with a spear and a window frame, and this aims to discourage that.
Gives the plastic golems a version of the Magic Missile spell, that way they can attack you at ranged
- Give them the rocket punch from stone golems
- Make them smoler and able to fit through windows
- Let them break walls for the funny
The golems can indeed cast the spells, and it seems to either do considerable damage or very little damage depending on your luck and how exactly you encounter them
Resin golems are still a theoretical infinite skill farm, but that's a separate issue that I'd need to look at (then again, there's a good chance they'll spawn with plastic golems around anyway).
They seem to love targeting the head
Further golem reworks (adding a new clay golem …
> feat(mods/Magical_Nights, balance): Discourage spear cheese against plastic golems

- data/json/artifact/premade_artifacts.json
- data/json/effects.json
- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/magic_enchantment.cpp
- src/magic_enchantment.h
I couldn't apply irradiation on players for being in sunlight, this lets me apply irradiation for players above ground if they're carrying an item.
I checked the underground relic_data condition and wrote one for aboveground. It's incredibly self-explanatory that even I know what I'm doing here.
Make Someone else do it.
Get sunlight as a valid condition. (I'll make someone else do that later)
THE IRRADIATION TRIANGLE IS HERE D: A new debug object was supplied for testing purposes and example artifacts which apply conditions on carrying while above ground.
THAT'S A REALLY MEAN LOOKING TRIANGLE!
> feat(content): Relic_data expanded to support aboveground as a condition

- data/json/itemgroups/Locations_MapExtras/locations_mapextras.json
- data/json/mapgen/map_extras/corpses.json
Another lil entry in my todo list, we've received multiple complaints about drug dealer map extras being a cornucopia of basically-free guns due to how many bodies spawn there.
1. Condensed the weapon and gunmod spawns in `drugdealer` into a single distribution. Instead of rolling for a melee weapon, a gun, AND a gunmod it picks one of each with about 50% odds of it being a gun. Effectively reduces the chance of getting a gun from 50% per corpse (reminder, each map extra will have up to a dozen corpses) to 25%. Additionally, per feedback rifles have been removed from the selection in favor of more SMGs
2. Additionally condensed the snacks, booze, and soft drugs into a single distribution so that the separate rolls for harder stuff with stand out more and not be mixed with a bunch of …
> feat(balance): sanity-check spawns in drug deal map extra

- data/mods/Magical_Nights/tileset-acknowledgement.txt
As it turns out, the tileset we had for Magiclysm (and that Magical Nights thusly inherited) used a bunch of recolors of Dungeon Crawl: Stone Soup and RLTiles item sprites for the wands (if not more). While the wand sprites recolored are under CC0 and public domain for both sources respectively, it still feels best to acknowledge them.
Adds an acknowledgement of where the tiles came from, as RLTiles politely requests and as DCSS likely appreciates.
- Also include a notice asking people to please reach out first if they think they see any violations
- Do nothing, CC0 (and public domain) don't legally require attribution in the first place
I read it and it is indeed intelligible English.
I swear, if there's a tile in the tileset that MN inherited that turns out to be copyright infringement, …
> chore(mods/Magical_Nights): Add an acknowledgement for sources of certain tiles

- data/json/flags.json
- data/json/items/armor/power_armor.json
- src/character.cpp
- src/flag.cpp
- src/flag.h
fixes #5920 
Introduced new "EXOSUIT" flag, so any item with this flag will conflict with eachother, removed "ONLY_ONE" flag, for said items, as obsolete.
Tested so it does not affect other clothing;
Checked all(4) items with both on/off states
> fix: only single exosuit can be worn now

- .github/pull_request_template.md
- checklist was hiding PR details in `#news-bot`
- PR body guideline comments were getting too long, which discourages contributors from reading it fully
| before | after |
| - | - |
| ![image](https://github.com/user-attachments/assets/ce3b9594-0381-49d5-83b1-7d0b6e5fb5dc) | ![image](https://github.com/user-attachments/assets/2fab6b07-cde2-41c7-b3c1-0141b95bfff1) |
- simplifies pull request template
- removed duplicate information in checklist and comments
- section `Describe alternatives you've considered` and `Additional Context` merged into `What does this PR do?`
- puts checklist at the bottom of the PR body
documentation changes only.
> docs: simplify pull request template

- data/json/field_type.json
It was pointed out that sludge trials remain an annoyance for vastly longer than they have any right to be, are just as weirdly widespread in water, and their half-life is long enough that
1. Toned the half-life of sludge trails way the hell down from 6 hours to 10 minutes.
2. Additionally, like with acid and other liquid fields, defined an underwater age speedup of an amount equal to its half-life.
3. Per Oren's advice, also added accelerated decay for out-of-bubble sludge.
4. Spawned in a pupa zed and let it goop around a lil.
5. Waited 15-20 minutes after killing it, slime was gone.
6. Spawned another and lured it into water, slime is even less persistent.
> feat(balance): sanity-check half-life of sludge trail fields

- data/json/external_tileset/External_Tileset_DP_Normal.json
- data/json/furniture_and_terrain/furniture-rural.json
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5943 plus a couple external tileset improvements.
1. Fixed what furniture ID recovering beehives grow into.
2. Assigned the external tileset sprite used by beehives to also be used for the item, as with anvils for example.
2. Used my fucking eyes for once and confirmed the recovering hive is set to grow into the correct furniture ID.
> fix: recovering beehives grow into correct furniture, use external tileset sprite for item form

- .github/workflows/manual-release.yml
Fixes #5946 (at least in theory)
Ports the changes to the mac dependencies from the Nightly build script to the Manual build script.
Make sure everything builds alright
Get a mac user to test it afterwards?
> ci: Fix mac manual releases

- data/json/effects.json
This sanity-checks the fatigue gain from late-stage infections. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/641
1. Reduces `fatigue_min` of infection status from 360/180 to 2/1, and added `fatigue_tick` of 6.
2. Likewise also reduced `fatigue_min` of recovering from infection status from 360 to 2.
As noted in the related issue, previously you were gaining an average of 3.6 fatigue per second, which is absolutely absurd (1080 extra fatigue across 5 minutes when normally you get 1 fatigue across 5 minutes). These changes reduce average fatigue gain to an average of 1 extra fatigue gain per 5 minutes, which is enough to double your default fatigue rate gain.
2. Suffered doing math.
> feat(balance): sanity-check fatigue gain from infections

- src/map_extras.cpp
Supply drops are known for spawning very few items, and in general being very inconsistent on their value. This changes that by buffing their spawned items a good amount and getting rid of some of the silliness that they had with spawning their items. Should hopefully cut down on the disappointing crates.
- Changes the number of crates spawned from 1-5 to 3-7
- Rolls multiple times for itemgroups for the same crate
- Places the itemgroup ids into a vector, then iterates over that vector when it comes time to spawn items
- Rolls for 4 items instead of 2, and does it infinitely more sensibly
- Makes sure that the return of the item-placing function isn't discarded and the variable to put a use for it isn't unused.
- Compile test
- Load into the game
- Spawn a supply drop
- Examine the …
> feat(balance): Buff supply drop items, rework their item spawning

- src/game.cpp
Fixes time to disassemble items displayed on UI.
Rewrites logic ralated to displayed time for item disassembly.
For some reason previous logic showed every items' d. time once, if "dissasemble everything once" option was chosen.
And only sum of times of root items was shown on "dissasemble everything recursively" option was chosen.
Now all items are counted properly, for the 1st option, and estimation with deafault items is shown for recursive option.
Manual checks of time for previous and current versions.
> fix(UI): displayed disassemble time

- data/json/recipes/armor/feet.json
- data/json/recipes/armor/head.json
- data/json/recipes/armor/torso.json
There's no reason clothing made from cloth or leather should be uncraftable.
Adds autolearned recipes for the camisole, corset, and dress shoes. Makes maid hat autolearn.
Load the game
> feat(content): More clothing recipes

- .github/workflows/manual-release.yml
- .github/workflows/osx.yml
- .github/workflows/release.yml
Otherwise the Mac builds will fail because SDL3 just got officially released and Brett's action tries to grab SDL3 and gets very confused when there is no SDL2 framework in SDL3
Fixes issues discovered in Royal Fox's PR, #5957 
Pins all the SDL versions used for OSX builds to actual SDL2 versions everywhere I could find them
Watch to see if the mac builds succeed
Hopefully Brett will fix it upstream so that it targets SDL2 builds only in the first place (given that they should in theory get *some* bug fixes still)
At some point we probably should look into whether SDL2-compat (which runs using SDL3) will be a good fit given that [distros like Fedora are already considering changing over to it](https://discussion.fedoraproject.org/t/f42-change-proposal-replace-sdl-2-with-sdl2-compat-using-s …
> ci: Pin SDL2 used for OSX builds

- data/json/npcs/refugee_center/beggars/BEGGAR_4_Brandon_Garder.json
It removes dialogue that makes the game … dated
changes a few lines in `data/json/npcs/refugee_center/beggars/BEGGAR_4_Brandon_Garder.json`
> feat(content):  Remove dialogue that references specific years

- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/magic_enchantment.cpp
- src/magic_enchantment.h
This is a desired condition among the community to be used for applications where you care about something *not* being active (perhaps as a debuff of some kind?). Besides, more conditions are better, and if we have an `ACTIVE` we might as well have its opposite.
Adds `INACTIVE` as a condition, the opposite of `ACTIVE`
- Build-test
- Add an enchantment with the `INACTIVE` condition onto something that can be used to test it, like a mutation.
- Check to see if the enchantment effects are indeed only working when it is *not* active.
> feat: Add `INACTIVE` condition for enchantments

- data/json/effects.json
This implements some belated adjustments to how the dissoluted devourer's effect scales. In particular make it scale up more slowly so that it takes more HP of absorbed zombies to max out the effects, but also make the recently-ish-restored bash bonuses less massive.
1. Increased max intensity from 480 to 1000.
2. Reduced the numbers of all bonuses so they hit their original max values at this new max, which combined with step one make them essentially scale a bit more than twice as slowly. Size mod scaling additionally was shifted just enough to be a lil more 100% sure it won't be an even +3 bonus at max intensity, since that's one size more than exists in the game due to starting off as a medium creature.
3. On top of that, `bash_mod` given an additional cut in half so that damage bonus …
> feat(balance): dissoluted devourer buff scales more slowly, cut max bashing bonus in half

- data/json/flags.json
- data/json/items/classes/book.json
- data/json/items/tool/deployable.json
- data/json/items/tool/explosives.json
- data/json/items/tool/firefighting.json
- data/json/items/tool/misc.json
- data/json/items/tool/radio_tools.json
- data/json/items/vehicle/cables.json
- doc/src/content/docs/en/mod/json/reference/json_flags.md
- src/character.cpp
- src/flag.cpp
- src/flag.h
- src/iuse.cpp
- fixes #5122 
Fixes cables not being removed after linking vehicles, by revisiting some of the logic changes from #4968, without disturbing the work done
"Using" things that use charges and should or should not "disappear" after.
> fix: cables duplication

- src/iuse_actor.cpp
- fixes #5868 due to #5297 making them get removed like grenades because it gets reverted in iuse_actor code and then tries to get reverted again in process_tool code, which fails and destroys the item.
Removes the extinguish when it hits zero charges, that is handled by process_tool. It just needs to check to proc it's special message.
> fix: Fireweapons stop being destroyed when running out of charges.

- .github/pull_request_template.md
- While I appreciate the goal of #5941 I uh... preferred some of the original titles and liked the alternatives/additional context fields. While they aren't always filled I like to have them there when it comes up, as filling them in when they are relevant is nice, and adding them back to the template does not hamper readability of the PR from the github bot.
-  Yes I know this PR is a bit nitpicky. Sue me.
> docs: tweaks to PR template

- data/json/furniture_and_terrain/terrain-flora.json
It's hard to get renewable sticks, bashing saplings is a nonrenewable way to do it.
Every tree can be harvested for sticks year round.
Making Chaos do it.
It loads, it works.
Maybe now we can make wattle and daub.
> feat: Trees can be harvested for long sticks

- doc/src/content/docs/en/mod/json/reference/creatures/martialart_json.md
- src/character_martial_arts.cpp
- src/character_martial_arts.h
- src/martialarts.cpp
- src/martialarts.h
Sometimes, especially in mods, it'd be nice if you could restrict certain techniques (or entire martial arts styles) to characters with specific traits / mutations.
- Adds a new field to martial arts and techniques that takes a list of mutation ids to be required
- Prevents usage by players without these requirements
- Prints notices of these requirements in the normal places
- Ask someone else to do it
- Just leave it be
- Compiled, it did indeed compile
- Loaded into a world as a character, it did indeed load
- Added a requirement to Barbaran Montante as well as the impaling technique within.
- The requirement on the technique did work, only letting me impale when I had the trait I set as a requirement
- The requirement on the martial art also worked, including restricting the buffs! It …
> feat: Allow martial arts to require mutations

- data/json/items/tool_armor.json
Ekarus pointed out to me that the biomonitor item can accept rechargable and atomic ultralight batteries, but not disposable ones which are the same size.
Added disposable ultra-light batteries to the magazine list for biomonitor.
Allowing regular light batteries for the fuck of it? I dunno.
Displayed basic reading skills and ability to count to three, to confirm the magazine list had three battery options and that they're the IDs you expect.
> fix: radiation biomonitor can now load all three types of ultra-light battery

- data/json/items/armor/sheath.json
Pocket knives have the `SHEATH_KNIFE` flag, but no actual sheath can fit them because back when I sanity-checked the min volume of small sheathes I only had scalpels in mind, and pocket knives are 5 ml smaller.
1. Lowered `min_volume` of wrist sheath from 15 ml to 10 ml.
2. Lowered `min_volume` of ankle sheath from 15 ml to 10 ml.
1. Making pocket knives bigger.
2. Lowering min volume for these items all the way down to 1 ml just to make 100% sure this can never happen again.
Checked that there no longer any vanilla `SHEATH_KNIFE` items below the new volume limit.
Another one spotted by Ekarus. :3
> feat(balance): wrist and ankle sheaths can fit pocket knives

- data/json/items/corpses/inactive_bots.json
- data/json/uncraft/generic.json
Inactive bots can't be disassembled, unlike their broken counterparts
Fixed inconsistency between names pf broken and inactive versions of riot dispatches
~~Added copy-from uncraft recipes~~ Uncrafts implemented sans copy-from and as a bonus fixed a recipe that's broken due to copy-from not inheriting all properties correctly due to bugs. - CV
Check if those now can be disassembled
> fix: disassemble inactive bots

- src/iexamine.cpp
While it's possible to craft charcoal from heavy bones using craft recipies, kiln does not allow to put those inside. This one fixes it.
Add "bone_heavy" to method that handles kilns.
Try putting heavies in, lit kiln, check result.
> fix(balance): kilnable heavy bones

- data/json/items/ammo/20x66mm.json
- data/json/items/ammo/410shot.json
- data/json/items/ammo/shot.json
- data/json/items/ammo/shotpaper.json
One annoying consequence of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4950 is it came with a giant nerf to ranges for affected ammo, which in turn makes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2793 a bit more bothersome. This aims to make things more tolerable at the expense of a bit of width on the AoE cones.
1. Increased 20mm shot's AoE range from 12 tiles to 24, while reducing width from 10 to 5.
2. Increased regular 00 shot's AoE range from 12 tiles to 20, and reduced width from 10 to 8.
3. Increased .410 shot's AoE range from 12 to 16. Allowed to stay at 10 width since shorter range than 00 shot.
4. Increased range of 12 gauge birdshot from 8 to 10, to be exactly half that of buckshot and to be more distinct compared to .22 ratshot and 12 gauge dragon's …
> feat(balance): vary up AoE range of shotshells more, fix paper shot lacking AoE

- data/mods/Magical_Nights/worldgen/overmap_specials.json
Wizard Towers and many similar mapgen features in the mod are NOT SUPPOSED TO SPAWN IN TOWNS.
And yet, thanks to very drunk mapgen, they do. This causes problems for wizard towers in particular thanks to how they place their plastic golems, leading to a very painful time if the tower is in the city (especially with the new anti-spear-cheese)
- Further edit the mapgen values of a bunch of the overmap specials to encourage mapgen to stop being an idiot
- Bump the occurrences of certain specials for the sake of encouraging them to spawn more
- Put wizard towers in forests so that they are even less likely to show up inside of towns
- Also fixes an oversight where forest tombs didn't spawn anymore because of copy-paste error on putting in magic academies
- Fix mapgen myself
- Wait for someone …
> fix(mods/MagicalNights): Attempt to limit mapgen placing things in towns when it shouldn't

- doc/src/content/docs/en/mod/json/tutorial/modding.md
This alarmism harms the credibility of the docs unnecessarily and evidently scares off some people from using them.
Reduce it to a caution from a warning, and in general is less alarmist about the docs being outdated while acknowledging that some parts of them likely are.
- Remove it altogether
I read it with my eyes
I know at least one modder was scared off of using them by it.
> docs: Reduce alarmism about docs being outdated

- data/json/items/melee/axes.json
- data/json/items/tool/entry_tools.json
- data/json/items/tool/firefighting.json
- data/json/items/tool/woodworking.json
- data/json/obsoletion/uncategorized.json
- data/json/weapon_categories.json
- data/mods/CRT_EXPANSION/items/crt_tools.json
- data/mods/MMA/martialarts.json
- data/mods/Magical_Nights/items/class_items.json
Most melee weapon types tend to only really need a one-handed and two-handed category, aside from more complex stuff like swords and polearms. In particular it seems like it'd be better to narrow down the categories for axes and get a fix on what goes well, which in the process also fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5965
1. Per request, set battle axes to category `2H_AXES` instead of `1H_AXES`, as size-wise it's much closer to 
2. Moved hatchet, crash axe, and ice axe from `HAND_AXES` to `1H_AXE`, where you find the simularly-sized tomahawks.
3. Updated Iron Heart style in MMA mod to use one and two-handed axes instead of hand axes, since it allows one and two-handed swords.
4. Removed hand axes from Tiger Claw style in MMA mod since it already has one-handed …
> feat(balance): move battleaxe to `2H_AXES`category, obsolete `HAND_AXES` in favor of `1H_AXES`

- data/json/furniture_and_terrain/furniture-appliances.json
Somehow, Palpatine has returned.
Remove `EASY_DECONSTRUCT` from grid air conditioners, again.
Making royalfox do it.
Used my eyes to confirm the deconstruct flag on grid air conditioners has been executed for its crimes (tax evasion) for the second time in 3 days.
Was first removed in: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5978
Was accidentally re-introduced by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5988 as Royalfox evidently forgot to update from upstream before making the branch and I didn't notice it while rubber-stamping the PR.
> fix: remove `EASY_DECONSTRUCT` from air conditioners again due to it being accidentally re-added

- data/json/items/armor/storage.json
The description of the Survivor Hiking Backpack reads as follows.
"A custom-built backpack hiking.  Durable and carefully crafted to hold as much stuff as possible."
"backpack hiking" didn't quite look right to me, and since I don't go outside too often, I totally looked up the parts of a hiking backpack to see if this is just some uniquely named bit. It's not (as far as I am aware). 
The next conclusion is that it was a typo, so I made an edit.
I swapped the location of the words "hiking" and "backpack" around in the `.json` file.
Telling someone in the Discord, or leaving it be.
I changed the `.json`, loaded in, and saw that the description was changed.
Before:
After:
> chore: survivor hiking backpack description typo fix

- src/consumption.cpp
- src/martialarts.cpp
Delta Epsilon in the Discord had troubles building thanks to these two. For whatever reason, clangd just *loves* choosing to use angle braces on the automatic includes instead of quotation marks. I intend to try and fix this one way or another.
- Changes the hostile lines to nice double-quotes
- Go directly for trying to put in a .clangd file in the project to explicitly try and prevent this from happening
I should *hope* changing includes to be the correct type doesn't break anything!
Auto-includes with clangd seem to be defaulting to <> instead of "" for me, which is very annoying.
> chore: fix my auto-included headers

- src/crafting.cpp
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4860 by making it so crafting tools won't create a weird situation where the item is empty but counts as having an ammotype assigned under the hood.
In crafting.cpp, added a check in the `complete_craft` where it asks if the item being created has no ammo loaded into it, and if so makes sure to unset the ammotype from it so it won't be in a paradoxical "I'm loaded but empty" situation which is only possible to clear by loading the exact ammo it wants and then unloading it.
I was real tempted to be lazy and just fix any items affected by this stupid bug in JSON by removing use of `initial_charges` from offending items...
2. Gave myself debug hammerspace and all recipes.
3. Crafted an alcohol-fueled …
> fix: crafted items no longer try to set default ammotype for items spawned empty

- data/json/items/classes/gun.json
- data/json/items/gun/flammable.json
- data/json/items/gunmod/muzzle.json
- data/json/recipes/weapon/mods.json
- doc/src/content/docs/en/mod/json/reference/json_flags.md
- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/item.cpp
- src/item_factory.cpp
- src/itype.h
Finally got reminded to look into porting the ability to set exactly how much ammo one wants to use on firing a weapon instead of the old legacy flags, which will make things easier and more flexible for mods.
C++ changes:
1. In item.cpp, ported over the change to `item::ammo_required` to make guns cite `ammo_to_fire` instead of a fixed 1 ammo per shot. Unlike the DDA PR, I opted to keep the legacy flags for now because it's literally just changing a number in the `else` at the end, we don't have to break mods immediately. Also includes the support for modifiers and multipliers from gunmods.
2. In item_factory.cpp and itype.h, ported definition of `ammo_to_fire` in `Item_factory::load` (gun version) and `islot_gun : common_ranged_data` with default of one.
3. Also in item_factory.cpp and …
> feat(port): JSONize ammo consumption per shot, allow gunmods to modify ammo use, add a flamethrower gunmod to demonstrate ammo use modifier

- src/item.cpp
Was suggested I make item UI tell the player when a gun uses more than one ammo per shot, just as it mentions UPS costs.
In item.cpp, added a section to `item::gun_info` that checks if the gun's total ammo per shot is higher than one, and if so prints how many are used per shot.
Screaming.
2. Spawned in a normal gun, saw it didn't show me ammo per shot info.
3. Spawned in a flamethrower, it shows 100 ammo per shot.
4. Installed a nozzle on it, it shows the value change.
5. Checked affected file for astyle.
I also wanted to fix reasons-why-you-can't-fire messages printing multiple times when the gun has more than one fire mode but couldn't figure out how.
> feat(UI): show ammo per shot for weapons that use it

- src/assign.cpp
- src/debug.cpp
- src/debug.h
```
Json error: data/json/items/generic/bathroom_house.json:27:14: cannot assign explicit value the same as default or inherited value
"price_postapoc": "150 cent",
"//": "the end of the world doesn't mean everyone is okay with having ZZ Top beards.  disposable razors are a hot commodity.",
"weight":
^
"100 g",
"material": [ "plastic", "steel" ],
"cutting": 2,
```
Hints like this should be an warning, not errors that break builds that has been running for 20 minutes, which is highly annoying.
adds new macro, `debugmsg_of` which accepts debug level as first parameter.
```
21:18:32.078 WARNING DEBUGMSG : /var/home/scarf/repo/cata/Cataclysm/src/assign.cpp:11 [void report_strict_violation(const JsonObject &, const std::string &, const std::string &)] (json-error)
Json error: …
```
> fix: convert strict JSON errors to warning

- src/character.cpp
- src/game.cpp
- src/recipe.cpp
- src/vehicle_move.cpp
those compiler warnings were annoying and kept hiding other important errors
do as the compiler says.
it builds without errors.
```
[121/495] Building CXX object src/CMakeFiles/cataclysm-bn-tiles-common.dir/character.cpp.o
/var/home/scarf/repo/cata/Cataclysm/src/character.cpp:8767:13: warning: unused variable 'rolls' [-Wunused-variable]
8767 |         int rolls = 4;
|             ^~~~~
1 warning generated.
[178/495] Building CXX object src/CMakeFiles/cataclysm-bn-tiles-common.dir/game.cpp.o
/var/home/scarf/repo/cata/Cataclysm/src/game.cpp:8537:31: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
8537 |             for( int i = 0; i < disassembly_stacks_res.size(); i++ ) {
|                             ~ ^ …
```
> refactor: fix compiler warnings

- tools/clang-tidy-plugin/TextStyleCheck.cpp
```
/var/home/scarf/repo/cata/Cataclysm/tools/clang-tidy-plugin/TextStyleCheck.cpp:93:59: error: no member named 'equals' in 'llvm::StringRef'
92 |         } else if( StringRef( SrcMgr.getPresumedLoc( SrcMgr.getSpellingLoc(
|                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
93 |                                   loc ) ).getFilename() ).equals( "<scratch space>" ) ) {
|                                   ~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
ninja: build stopped: cannot make progress due to previous errors.
```
```sh
$ llvm-config --version
19.1.5
```
equals seems to be removed in recent LLVM (at least since 19) and thus it's not possible to build clang-tidy plugin.
use `equals_insensitive`. see https://llvm.org/doxygen/classllvm_1_1StringRef.html#ae46058c90 …
> build: fix clang-tidy plugin build failure

- data/mods/Monster_Girls/thresh_mutation.json
Apparently I typed too fast when putting it in, and put in a typo.
Drayd -> Dryad
- Implode for my typing sins
I used my eyes
Apparently my fingers *nyoom*'d a lil too hard when making the mod.
> chore(mods/MonsterGirls): Fix a typo in Dryad Threshold's displayed name

- .github/workflows/matrix.yml
Artifact actions v3 are retired now and make builds auto-fail
Bumps the versions used to 4.6.0 (the latest)
- Bump to an older version for potential stability purposes
Built on my fork
Bomp
> ci: bump artifact actions to v4.6.0

- data/json/recipes/weapon/mods.json
While we are able crafting multiple quite advanced energo weapons and cbms , yet we are unable to craft relatively simple gunmod.
Add cfafting recipe
Game builds and starts, craft works as intended
Balance suggestions are welcome
> feat(balance): add craftable underbarrel laser sight

- src/ranged_aoe.cpp
Fix #5981
Check for `PERMEABLE` flag on terrain instead of furniture.
Check for furniture as well. Might be preferred, but we barely have `PERMEABLE` furniture and the check might be a bit complicated. The issue is that we'd have to check passability separately for terrain and furniture and then "confirm" it with their specific flags.
* Spawn 00 shotgun (pipe shotgun) + birdshot
* Load shotgun with birdshot
* Spawn a chainlink fence and a monster behind it
* Shoot at the monster through chainlink
* Monster should be hit for full damage
> fix: Fix cone shot not going through fences

- data/json/furniture_and_terrain/terrain-doors.json
- data/json/furniture_and_terrain/terrain-windows.json
We decided windows blocking scent was nice, this does the same for doors. This isn't ideal as we lack a scent map and proper tracking and granularity, but it's all or nothing so it's fine this way.
Also fixes one window with metal bars not being hacksawed
Adds NO_SCENT to the doors that are closed and intact.
Adds hacksaw action to the one specific window
Better scent system overall.
Tests
> feat: Fix no hacksaw on metal bar window, closed doors block scent

- .github/ISSUE_TEMPLATE/bug_report.yml
- src/debug.cpp
- src/debug.h
make debugging issues related to save files easier (e.g #6032)
when generating game report, also display save file version (V1 or V2 - sqlite)
mine:
```
- OS: Linux
- OS Version: LSB Version: n/a; Distributor ID: Fedora; Description: Fedora Linux 41 (Container Image); Release: 41; Codename: n/a; 
- Game Version: 70e9157554 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Save File Version: V2 (compressed with sqlite 3)
- Game Language: English [en_US]
- Mods loaded: [
Bright Nights [bn],
Disable NPC Needs [no_npc_food],
Simplified Nutrition [novitamins],
No Rail Stations [No_Rail_Stations],
Prevent Zombie Revivication [no_reviving_zombies],
Limit Fungal Growth [limit_fungal_growth]
]
```
i never get why report functions are in `debug.h`, adding one function causes recompiling …
> feat: show save file version in game report

- data/json/uncraft/generic.json
Adds spring to telescopic umbrella
Telescoping umbrellas do indeed have springs, and gives players a way to get springs 
Adds a spring to telescoping umbrellas so you can spring while you sproing
Not adding a spring 🔥 
Spawned in telescoping umbrella, cut it up, got spring
> feat(balance): The Springening

- data/mods/Monster_Girls/categories.json
- data/mods/Monster_Girls/thresh_mutation.json
- data/mods/Monster_Girls/vanilla_mutations.json
After #5885, the mod needs to be updated for proper compatibility and also in order to have the new mutation path!
Adds the bunnygirl mutation path based on the vanilla Rabbit path
- Give them the nose and maybe the paws
Current design choices led me to decide against it, but could very well be done if desired
I used my scripts and looked over the changes in github desktop to make sure they all looked right.
I've started to realize that the Kemonomimi names are kinda weird to have for the most part, and if I'm already calling them "X-girl" in the IDs then it would be sensible enough to just go on ahead and change their displayed names in-game too. So that might be a nice small future PR, if it's decided to be a good enough idea.
> feat(mods/MonsterGirls): Add bunny-girl mutation category

- data/mods/Magical_Nights/items/melee.json
Orichalcum fire axes made a claim that doesn't mesh with MN's direction.
Fixes the lore, and also gives it the weight reduction it was for some reason missing.
- Leave out the weight adjustment but increase bash or cutting by a little
Text-editing and copy-paste of a relative field got the eyeball test.
Easing my way back into MN contributions after my C++ adventures.
> chore(mods/MagicalNights): Fix lore issue with orichalcum fire axes

- src/monster.cpp
Fix #3072
Update monster's faction in monster tracker, if the tracker contains said monster.
Only updating the faction in tracker if it actually changed.
1. Clean map of monsters
2. Spawn zombie dog
3. Surround dog with goo pits
4. Spawn light turret where it can see the dog and will target it
5. Wait a turn
6. The dog should walk onto a pit, polymorph into a slime, then get shot (it must all happen in the same turn)
> fix: Fix monster faction debugmsg after monster::poly

- data/json/items/comestibles/brewing.json
- data/json/items/comestibles/carnivore.json
- data/json/items/comestibles/drink_other.json
- data/json/items/comestibles/fruit_dishes.json
- data/json/items/comestibles/junkfood.json
- data/json/items/comestibles/nuts.json
- data/json/items/comestibles/other.json
- data/json/items/comestibles/protein.json
- data/json/items/comestibles/raw_veggy.json
- data/json/items/comestibles/veggy_dishes.json
- data/json/items/comestibles/wheat.json
This moves more items out of the food item category and into cooking ingredients (or other, in a handful of cases).
Added `cooking_ingredients` category to:
1. Unfermented brew items such as whiskey wash and the like.
2. Raw fat/tallow/lard
3. Misc. drinkable stuff like honey, peanut butter, condiments, and other sauces. Also jam.
4. Vinegar and cooking oil
5. Maple syrup and beet syrup
6. Unpopped popcorn kernals
7. Raw acorns
8. Honeycombs and wax
9. Dried beans, lentils, rice and the like.
10. Coffee powder
11. Protein powder
12. Raw cereal grains such as barley, wheat, and oats.
13. Bee balm, hops flowers, dogbane, and raw mugwort
14. Raw tea leaves
15. Canola stalks
16. Starch
17. Items such as flour, cornmeal, and raw oatmeal
18. Dried salad
19. Uncocked pastas, fast noodles was …
> feat(UI): item category audit for comestibles

- data/mods/Aftershock/vehicles/vehicle_parts.json
Cleaner text = happier players.
Removed the underscore.
Leaving it in for that chic jank.
Made the change, loaded the game, looked inside. Since the ID didn't change, no loading errors or anything, despite the fact that I was loading from a save with the typo.
> chore(mods/aftershock): fix typo "robot_carrier" -> "robot carrier"

- data/mods/Magical_Nights/Spells/item_only.json
- data/mods/Magical_Nights/effects/effects.json
- data/mods/Magical_Nights/effects/enchantments.json
- data/mods/Magical_Nights/items/melee.json
The "legendary" weapons from Norse mythos were considered pretty crappy and not-epic by everyone, and I agree. Thus, I felt the need to buff these items to the status they deserve.
Also, in a previous PR (#6043) I used "steal" instead of "steel" in the orichalcum fire axe's new description, somehow, so I fixed that while I was in the file.
- Generally buffs the melee damage and `to_hit` of the relevant weapons
- Adds enchantments to Mjolnir, Gungnir, and Laevateinn
- Gives Gram extra sharpness to match mythos and to partially compensate for lack of cool enchantments
- Fixes the type in the fire axe description
- Get rid of them
I don't want to deal with the migration and also that seems like a bad idea
- Get rid of Gungnir and Gram, replace them with some non-Norse weapons
I'm far more …
> feat(balance, mods/MagicalNights): Buff legendary weapons, fix typo

- data/json/npcs/holdouts/Mr_Lapin.json
When Rabbit Mutations were added to the game, they weren't added to the game's only Rabbit NPC
I added them
> feat: add rabbit mutation to Mr_Lapin

- data/json/overmap/overmap_special/specials.json
- tests/overmap_test.cpp
prevent the spawning of the same NPC (specifically no multiple Mr. Lapins)
In order to prevent NPC's being duplicated, this pull request adds the flag  "GLOBALLY_UNIQUE" to the following overmaps:
- "Cabin_Lapin"
- "Isherwood Farms"
- "St_Johns_farm"
- "Occupied Chem Lab"
- "Occupied Lumbermill"
- "Occupied Scrap Yard"
I had considered not adding the flag to the occupied sites, however since there are tie-ins to the Evac Center's Merchant missions I felt they should be added.
Ran a bunch of random starts and they didn't appear to duplicate.
> feat: make more overmaps with unique NPC globally unique

- data/json/mutations/mutations.json
- data/json/obsoletion/mutations.json
to sum up - night vision mutations are currently togglable, while they don't do anything if u on/off them:
- they don't alter colors;
- they keep giving bonus NV'
- closes #5997.
Proposition is to make those passive, so those don't confuse players
Also as per @RoyalFox2140: "purely beneficial mutations have no right to be toggled on"
Make toggle effect actually do smth
Game is builing and starting, mutations are no longer togglable
> fix(balance): make NV mutations passive

- .github/workflows/manual-release.yml
- .github/workflows/release.yml
In the words of CGP Grey: "1 is none. 2 is one. If it's important, have a backup."
SQLite-save PR passed over the non-MSVC Windows builds, and as it turns out the manual release's build command on OSX builds has been broken the entire time? (Or at least for 2 years). Having a redundant Windows build is a great idea for when MSVC is being weird, and I'm sure the OSX users would like 
- Add SQLite dependencies to the cross-compile build for Windows
- Copy over the Nightly release's build command for OSX manual releases
- Let them suffer, it builds character!
I used my eyes and made sure I was copy-pasting the right things.
Proper testing shall come with actual build attempts
At least OSX users have the Nightlies already
> ci: Fix cross-compiled Windows builds and manual-release tiles OSX builds

- .github/workflows/android.yml
- .github/workflows/matrix.yml
- .github/workflows/msvc-full-features-cmake.yml
- .github/workflows/msys2-cmake.yml
- .github/workflows/osx.yml
no need to run build matrix only to edit markdown files.
update [`paths-ignore`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to ignore all files with [markdown (`.md` and `.mdx`) file extension.](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths)
wait hours on documentation-only changes
shouldn't fail
deno can now format YAML files too, now to format these `.github/` workflows...
> ci: ignore markdown changes

- LICENSE
- LICENSE.txt
- README.ko.md
- README.md
redo of #2770.
Creative Commons licenses are [not suitable for softwares][cc]. see https://github.com/CleverRaven/Cataclysm-DDA/issues/18095 for details.
[cc]: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
we can't change license of older commits, but it's possible to set new license for future contributions.
also [CC-BY-SA 4.0 is nice because it can be updated to GPLv3.](https://www.fsf.org/blogs/licensing/creative-commons-by-sa-4-0-declared-one-way-compatible-with-gnu-gpl-version-3)
as stated in README, mark future commits to be licensed as AGPL-V3 and CC-BY-SA 4.0.
keep previous license but it's unsuitable for source code.
heavily referenced https://github.com/Baystation12/Baystation12?tab=readme-ov-file#license
> chore: license future commits as AGPL-3.0 and CC-BY-SA-4.0

- .github/pull_request_template.md
As pointed out by RoyalFox in the Discord, it's unreasonable to not have these changes noted in a more prominent place. Putting them into the PR template seemed like the best idea to make PR authors aware of this change.
Adds one line to the mandatory checklist, and one to the DDA ports section of the "Optional" section describing current policy on handling ports.
- Mandate that any PRs to port features must now *exclusively* be ports and immediately pertinent fixes related to said ports, and thus content additions related to them must be split off into a separate PR
Generally unfeasible and overly burdensome, and thus undesirable.
I read and generally ran these by Chaos and Royal for their initial opinions before PRing
Comments approach seems the best way to handle properly noting the …
> chore: Add checkboxes related to new licensing policy to PR template

- .github/pull_request_template.md
- .github/semantic.yml
- .github/workflows/autofix.yml
- .github/workflows/clang-tidy.yml
- .github/workflows/documentation.yml
- .github/workflows/matrix.yml
- .github/workflows/msvc-full-features-cmake.yml
- .github/workflows/msys2-cmake.yml
- .github/workflows/osx.yml
- .github/workflows/release.yml
- deno.jsonc
Deno can format yaml files as of v1.46.0, no need to format yaml files manually.
includes `.github` directory for formatting.
run it fully on `data/` but BFN doesn't like it because it makes porting stuff from DDA harder
style only changes
> style: format `.github` directories

- data/mods/Magical_Nights/recipes/weapons.json
Obviously an upgraded weapon should take its base version as a material
Adds the relevant components to the recipes
I read it and linted it
AAAAAAAA why didn't I fix this the last time it got brought up
> fix(mods/MagicalNights): Upgraded dbone weapons take their base versions

- src/world.cpp
Otherwise cross-compile Windows is very unhappy, and others might also encounter issues compiling.
`<>` -> `""`
- Make someone else do it
None
Trying to get 0.8 out but the MSYS2 builds keep pissing themselves
> chore: Fix the sqlite and zlib `include`s in world.cpp

- .github/pull_request_template.md
- deno.jsonc
#6062 uglified checkboxes in PR template so this fixes it
use [`"proseWrap": "preserve"`](https://docs.deno.com/runtime/fundamentals/linting_and_formatting/#available-options) to keep the prose unwrapped.
originally wanted to use "proseWrap": "never" but i remember olanti saying it made writing docs hard.
style only changes.
i really need to revamp docs site aaaaahhhhh
> style: fix prose wrap in PR template

- data/mods/Generic_Guns/modinfo.json
- data/mods/No_Hope/modinfo.json
Both of these mods are generally unmaintained, they both are likely broken in some capacity at the moment, and we already don't recommend playing with either of them. It's time to bite the bullet.
`"obsolete": true` added to both modinfos, removed Pryanik from the maintainer slot of No Hope since I don't think he's been maintaining it here in ages in the first place?
- Delete them outright
Even if we don't recommend it, I'm sure *someone* is running these mods still, and this way they can serve as examples for someone looking to create a better solution for them in the future.
Linted, made sure that I'm not misspelling the field.
We ought to have done this even earlier tbh
> chore: Obsolete No Hope and Generic Guns

- data/mods/Magical_Nights/worldgen/magic_academy.json
- data/mods/Magical_Nights/worldgen/overmap_specials.json
Magic academies might be getting a little too discouraged by their current spawning conditions, which are a little overly cautious.
Also, the doors could be alarmed which would cause eyebots to spawn which is very much so anti-lore
- Changes minimum distance from cities to 20 (from 30, not like mapgen cares anyway)
- Changed wizard tower distances to align (having them at 25 still would be weird)
- Changed magic academies to forests to better encourage not spawning in cities
- Overwrote the default domestic pallete's door selection to not include the alarmed variety in academies
- Make magic academies globally unique
I don't think they quite meet that standard yet, but could rise there later
It loads, the doors don't seem to show up alarmed, academies seem to spawn a little more often …
> feat(balance, mods/MagicalNights): Change magic academy spawning conditions, change door type

- data/json/furniture_and_terrain/furniture-plumbing.json
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6077
Turns out water dispensers, and water purifiers for that matter, just copy from water heaters which already have the flag that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6005 accidentraly overrided their flags to give. So literally just a simple matter of deleting the redundant flag override since they already inherit `ADV_DECONSTRUCT` from water heaters, doi.
screm
1. Load-tested in compiled test build.
2. Spawned in a mine, checked the water dispenser to confirm it doesn't hold dirty water.
3. Can also actually pour the water into a container or try to drink it.
> fix: water dispensers and purifers don't erase inherited flags anymore

- data/json/items/comestibles/carnivore.json
Animal blood should obviously not be cannibalism
Removes the `copy-from` from animal blood so that it isn't inheriting human flesh vitamins, and changes the concentrated stuff to `copy-from` animal_blood
- Hunt down the code that causes vitamins to be inherited instead of overwritten and fix it at the source
Copy-pasting values, so testing was simply making sure it linted and my editor was happy with it as JSON.
Aaaaaaa
> fix: Animal blood isn't cannibalism

- data/json/items/classes/gun.json
- data/json/items/gun/10mm.json
- data/json/items/gun/22.json
- data/json/items/gun/223.json
- data/json/items/gun/270win.json
- data/json/items/gun/300.json
- data/json/items/gun/3006.json
- data/json/items/gun/308.json
- data/json/items/gun/36paper.json
- data/json/items/gun/38.json
- data/json/items/gun/380.json
- data/json/items/gun/38super.json
- data/json/items/gun/40.json
- data/json/items/gun/410shot.json
- data/json/items/gun/44.json
- data/json/items/gun/44paper.json
- data/json/items/gun/45.json
- data/json/items/gun/454.json
- data/json/items/gun/4570.json
- data/json/items/gun/45colt.json
- data/json/items/gun/500.json
- data/json/items/gun/545x39.json
- data/json/items/gun/762.json
- data/json/items/gun/762R.json
- data/json/items/gun/9mm.json
- data/json/items/gun/combination.json
- data/json/items/gun/shot.json
- data/json/items/gunmod/underbarrel.json
This unifies and standardizes the `blackpowder_tolerance` stats for different types of firearm a bit more.
Adjusted blackpowder tolerance values, with more of them being moved to gun templates where possible. Notable values picked:
1. Most autoloading guns are stuck with the default value as usual (8 according to hardcode, or 185 fouling per shot), but autoloaders previously called out as having a notable degree of tolerance (AKs, glocks, homemade SMGs) were standardized at 24 tolerance (153 fouling per shot).
2. Repeating, manual-action firearms in general (bolt-action, revolvers, pump-action, etc) made with modern cartridges standardized at 48 tolerance (105 fouling per shot).
3. Single-shot firearms made for modern cartridges, and repeating firearms designed with gunpowder in mind …
> feat(balance): consistency update for blackpowder tolerance of firearms

- data/json/recipes/other/tools.json
- data/json/requirements/toolsets.json
Some auditing of blacksmithing toolsets that came up in discussion of stuff in the BN server.
1. Lowered hammer quality required by `blacksmithing_standard` from 3 to 2, to make it a bit more of a difference between it and intermediate-tier blacksmithing in terms of simplicity.
2. Sanity-checked forging requirement for tongs recipe and used inline requirement for steel usage, along with scaling down number of steel pipes used as an alternative to match how much steel is being used here (4 chunks woth of pipes).
3. Now that `blacksmithing_standard` no longer requires a full level 3 hammer and thus won't trigger a "first anvil of Armok" situation, compacted the tools explicitly requested by the hammer recipe into a call to `blacksmithing_standard` (forge charges, level 2 hammer, level 1 …
> feat(balance): audit basic-tier blacksmithing

- src/addiction.cpp
Was pointed out in the BN server that meth withdrawal kills you due to unlimited depressant effects, while all other withdrawl effects have some sanity-checking. Turns out it's not quite the case but the limit it was given is a badly-designed one.
In addiction.cpp, set the stim limit for meth withdrawal in `addict_effect` to -75, half that of coke withdrawal. Before it was using an amount that scales with addiction intensity, which is `std::min`'d at 20 to mean it could only ever be worse than -100, and no idea just how severe it could get but clearly the answer is "bad enough to fucking kill you".
Not doing drugs I guess.
2. Started as a tweaker.
3. Waited around a full day, didn't die.
> fix: meth withdrawl won't cause you to die of eepy

- src/character.cpp
- src/character.h
- src/melee.cpp
- tests/char_stamina_test.cpp
Some balancing things that came up in discord. I noted that I did not like the way that stamina penalties seem to punish the player for trying to flee from a fight, but instead encourage the player to caveman their way through a fight if their stamina starts getting low (making their death inevitable if they suddenly realize they aren't going to win, due to movecost tanking horribly if your stamina is low).
In fact in retrospect, your effective move speed being cut in HALF at zero stamina might de-facto be why I tend to play with monster speed at 50% and with the faster stamina mod...
1. In character.cpp, removed the use of `stamina_move_cost_modifier()` from `Character::run_cost`, meaning low stamina will no longer affect how many moves it takes to walk around (run speed still scales …
> feat(balance): stamina no longer affects walking movecost, instead affecting dodge rating and melee damage

- data/json/items/ammo.json
- data/json/items/comestibles/alcohol.json
- data/json/items/comestibles/dairy.json
- data/json/items/comestibles/drink_other.json
- data/json/items/comestibles/egg.json
- data/json/items/comestibles/fruit_dishes.json
- data/json/items/comestibles/junkfood.json
- data/json/items/comestibles/other.json
- data/mods/TEST_DATA/TALK_TEST.json
- tests/npc_talk_test.cpp
Additional auditing of item categories.
1. Moved duct tape and fish bait out of tool categories and into other.
2. Moved all alcohol items to the drug category since generally most players won't treat them like normal drink items due to addiction effects.
3. Per feedback in the BN discord, moved some of the items I'd placed in ingredients back into their default food category, mainly stuff that's perfectly edible by itself (leaving fat/tallow, vingegar, condiments and other things that strongly should not go in your food pile as ingredients).
4. Did however move maple sap to ingredients category, as you'd likely want to process it into syrup before chugging it.
5. Added several inedible powder items  I missed last sweep to ingredient category.
I still kinda want to put raw meat items in …
> feat(UI): further audit of item category

- data/json/furniture_and_terrain/furniture-flora.json
- data/json/items/comestibles/seed.json
Close #5603
Create new seeds for spurge flowers and change seed drops from spurge.
None
1. Find spurge flowers on your game flowers.
2. Harvest them.
3. Should drop its harvest with new seeds.
I have no idea how to make poppy seeds drop, due its examine action being hardcoded.
Also I considered to make seeds for some mainline mods, if needed too.
> fix: add seeds for spurge flowers

- data/json/mapgen/dollar_store.json
`trash_dumpster` is a better option.
"U": { "item": "trash_dumpster", "chance": 80 } instead of "U": { "item": "trash", "chance": 20, "repeat": [ 2, 4 ] }
none
No errors.
none
> feat(balance): use `trash_dumpster` for the dumpster of the mapgen `dollarstore`

- src/monmove.cpp
Monsters will not bash vehicles whose parts are located on flat ground such as roads and what not. This fixes it.
It's a replication of a 5 year old DDA commit: https://github.com/CleverRaven/Cataclysm-DDA/pull/45035
N/A
Just basic normal testing by seeing that things do in fact get bashed.
N/A
> fix: Enemies now bash vehicles and furniture in the way

- .github/workflows/msys2-cmake.yml
This build has been failing for 1-2 years now, and it's annoying.
This looks like a very simple fix, so simple I'm amazed we never did it in the first place.
- Actually install sol2 instead of assuming by some miracle it's already there
- Throw the build in the trash
I was very tempted for a while, but it's a good idea to keep it around if it provides useful data
I confirmed that the package exists on msys2's list
This is really difficult to test without just merging it
Why the hecc was sol2 never added to the package list in the first place, but SQLITE3 WAS??
This codebase is cursed lol
> ci: Install sol2 for msys2 build

- src/activity_item_handling.cpp
- fixes #6024, which is due to the washing activity working fine if an item is washed all at once but doesn't spawn the split portion of an item if they are only partially washed.
- Make the washing activity actually spawn the item it generates for the split.
> fix: Washing activity now appropriately adds item if split.

- data/json/bionics.json
- data/json/items/tool/electronics.json
- src/bionics.cpp
- src/iuse.cpp
- #4107 removes trigger cost for bionic scanner, but this runs counter to the original implementation philosophy. Bionic scanner was always meant to trigger cost based on the corpses scanned, not time based power draw.
- Remove `power_draw` from bionic scanner. In turn, make the bionic scanner use 1 charge per CBM in a corpse.
- If the tool lacks the charges needed for one of the corpses, print a message and continue to the next eligible corpse, deactivate if tool lacks charges needed for even a single CBM no matter the source.
- The bionic instead has a 750 J trigger cost, this can be manipulated freely by mods.
> fix(balance): Adds Electrosense bionic scanner. Removes power draw from bionic scanner. Add trigger cost to bionic scanning.

- src/magic_enchantment.cpp
- fixes #6110 which was caused by #6106 causing relics to also be marked to be processed if left unattended. This caused a nullptr situation in `enchantment::is_active` when it tries to check the carrier for wield, carry, etc.
- Adds an escape clause early to the function where if `guy` is a nullptr it returns false.
> fix: `process_relic` exits early if not carried by a character.

- src/monstergenerator.cpp
Enemies talking or eating doesn't make them any more dangerous to the players.
Requested by "Good Guy" in the Discord
Ports two DDA PR's:
- https://github.com/CleverRaven/Cataclysm-DDA/pull/75716
- https://github.com/CleverRaven/Cataclysm-DDA/pull/75804
- Instead handle this with a flag in the code/JSON for special attacks that causes them to not count towards difficulty
Too much work for too little gain.
- Compiled
- Loaded in pre-changes: Killing a Mi-Go in a STK world gave me 68 EXP
- Loaded in post-changes: Killing a Mi-Go gave me 65 EXP
I also made sure to add a code comment explaining that the blacklisted_specials bit was ported from DDA, even though this probably falls under the "atomic PR's" idea of it being *just* a port anyway.
I changed the list of blacklisted special attacks …
> feat(port): Blacklist certain special_attacks from difficulty assessment

- src/character.cpp
- src/character.h
I screwed up something important in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6095
In character.cpp and character.h, split the move-mode modifier from `Character::stamina_burn_cost_modifier` into a separate function `Character::running_move_cost_modifier`, and re-added that into `Character::run_cost` so that running actually consumes fewer moves again but stamina still doesn't massively tank movement speed.
Screaming.
2. Confirmed running and crouching actually display different movecosts again.
3. Set stamina to zero and confirmed walking still does get a massive spike in movecost.
4. Checked affected files for astyle.
> fix: movement mode changes movecost like it should

- data/json/uncraft/ammo/pistol ammo.json
- data/json/uncraft/ammo/rifle ammo.json
The yes :
It takes 2 minutes to dissasemble most of the ammo types ive thrown into these files. 2 minutes to wiggle a bullet free which isn't really what most of the people in the discord said, or the random yt tutorials of people wiggling bullets free using a spent casing. 
More u crafts! 
Even if we add speedups to dissasembly and make higher quality of tools speed it up, it would be a balance nightmare :
If you make the tool quality affect it too much, some other thing is going to be broke broke. 
As for speedups - even if its slashed to half, it taking a minute is very unrealistic. 
The game didn't crash for me, I've gone through all recipes listed in here twice and they all matched to the recipes. If something did slip past it's either very minor or something that can be adjusted. …
> feat: Rifle and pistol uncrafts

- src/item.cpp
- src/item.h
- src/magic_enchantment.cpp
- src/relic.cpp
- src/relic.h
- #6120 is due to #6106 which gives me massive headaches. It's mainly to do with C++ magic because `process_relic` is passing on a reference that may be generated from a nullptr, so the compiler is optimizing away any checks because it assumes we actually checked that the reference is actually valid. Far as I can tell the optimization only occurs on android builds.
`process_relic` now takes a pointer rather than a possibly invalid reference.
Recharge code can now properly handle all possible recharge options when off the player (except wet requiring being underwater, because for some reason we don't have code to check if an object is submerged, only if the player is.)
Active enchantments don't get checked at all if the relic isn't being carried.
I think it might be difficult to test this …
> fix: Make `process_relic` take a pointer and stop crashing the game.

- src/character.cpp
- src/game_inventory.cpp
- UPS compatible tools can be toggled on/off to use UPS as charger, BUT checks forbid doing that if tool is not charged enough, which is wrong.
- Closes #5536
Omitting charge check for `TOGGLE_UPS_CHARGING` use
1. Compile and start test;
2. Check if UPS can be toggle on/off;
3. Check that uses that need charges can't be invoked.
> fix: Allow UPS charge on/off no matter tools' charge

- gfx/MSX++UnDeadPeopleEdition/tile_config.json
- src/cached_options.cpp
- src/cached_options.h
- src/cata_tiles.cpp
- src/cata_tiles.h
- src/options.cpp
- src/sdltiles.cpp
Navigating while flying on helicopters is hard, because lower overmap layers are not visible, this PR implements overmap transparency.
- closes #1938
Algorithm is quite straitforward:
While rendering, if current tile is "open_air", then we should render lower tile with some blue overlay (like regular rendering)
But there is one problem - UDP tileset contains rooftops tiles with background of open air texture. If we'll just apply aforementioned method result will be quite ugly, Z0 level shows grass and roards and Z1 level shows only rooftop and open air below.
To fix that issue we need to introduce new JSON field for overmap tile textures, that states if this texture contains any transparent pixels on foreground.  If so we'll render tile below first and then render this texture without …
> feat(UI): Draw lower z-level for overmap

- data/json/itemgroups/science_and_tech.json
- data/json/recipes/chem/mutagen.json
- data/mods/Aftershock/recipes/recipes.json
Added a recipe and loot drops for the purifier smart shot. The recipe requires very high skills and the loot table drops are very low chances.
Although purifier smart shot existed in the code, it could only be attained through the lab finale or by crafting it with royal jelly, which itself is extremely rare.
Purifier smart shot's crafting recipe now requires no royal jelly and more slime, and can also be found in the 'mutagens' and 'mutagen lab' loot tables at a minimum chance.
> feat(balance): Purifier Smart Shot Crafting, Loot

- data/mods/Monster_Girls/vanilla_mutations.json
35% carry weight reduction for no gain is undesirable, especially when these trees already have hollow bones to crater their carry weight.
Removes the `extend` from it and marks it as invalid
- PR a change to the mutation in vanilla
- Give them strong backs instead
If deleting the `extend` and marking it with the same invalid as other entries doesn't work, we have bigger issues
I'm kinda surprised I let it slide in the first place
> feat(mods/MonsterGirls): Monstergirls don't get `BADBACK`

- data/json/bionics.json
Although the diamond cornea can cancel out bad vision traits, very few other CBMs currently do that despite their function implying they could.
The Enhanced Hearing, Skeletal Bracing, Diamond Cornea, Air Filtration System, and Joint Servo CBMs have been modified to cancel bad hearing/deaf, bad back, hyperopic/myopic, asthma, and bad knees, respectively, while also leaving other CBMs which cancel out negative traits solely through their actual function untouched.
It's mostly json, so unless I made a typo or broke one of the tests, it should be fine. That said, if I missed over specific CBMs that already cancel out a mutation via hardcode, please let me know.
Enhanced hearing replaces your ears' internals with machinery that hears better than natural human ears, so it would fix poor hearing …
> feat(balance): more bionics can cancel out bad mutations

- data/json/player_activities.json
Falling asleep should not have visible progress, it's a bug I've missed
Hide it
> fix: Hide vebose tooltip for sleep

- doc/src/content/docs/en/mod/json/reference/json_flags.md
Update docs to contain up to date info
And I needed it anyway for updating [cbn-guide](https://github.com/ushkinaz/cbn-guide)
Copy values and descriptions from
- MonsterGenerator::init_death
- MonsterGenerator::init_defense
npm run dev
> docs: updated monster death functions and monster defense attacks

- src/monmove.cpp
Flying mobs physically cannot go down, non-flying mobs can't go down ramps. Fix it.
Direct port of https://github.com/CleverRaven/Cataclysm-DDA/pull/68194 and https://github.com/CleverRaven/Cataclysm-DDA/pull/68213 with some extra changes
N/A
Tested that enemies do, in fact, go down ramps now.
N/A
> fix: flying monsters wouldn't go down in general, non-flying monsters wouldn't go down ramps

- data/mods/speedydex/modinfo.json
- src/character.cpp
It irked me a bit that speedydex has very little impact, mainly because the minimum dex required is so high.
Changed the `SPEEDYDEX_MIN_DEX` setting in speedydex mod from 12 to 10, making its impact noticable a bit sooner.
1. Originally I'd planned to make it so it kicks in above or below 8, with below-average dex penalizing you, as I felt this would be better for making the impact actually noticable to all characters, but this got axed.
2. Increasing `SPEEDYDEX_DEX_SPEED` from 2 to some other amount, dunno how much. If so I might be tempted to suggest additionally defining a `SPEEDYDEX_MAX_DEX` property that puts on a ceiling for how high speed can get if a player's dex gets wacky enough.
3. Mainlining this mod.
Autofix doesn't screm at me.
> feat(balance): speedydex bonus takes effect avove 10 dex

- data/json/items/tool/electronics.json
Added portable_game action to smartphones, allowing them to let the player play games like any good smartphone would.
Smartphones can play games IRL, even some offline ones, and yet the smartphone ingame can only be used to play music and as a flashlight.
Added the portable_game action to smartphones.
Because some mod-added multitool electronics can cause bugs in their own use-actions, I made sure to test the functionality of all three actions myself, and they all work just fine.
> feat(balance): smartphone game playing

- data/json/items/comestibles/mutagen.json
- data/json/recipes/chem/mutagen.json
When I pulled the smart shot recipe from aftershock the other day, I removed the royal jelly, thinking that it was more difficult to get than it was. However, I believe that something called a 'smart shot' which can remove any one specific mutation (plus two other random ones) should require a more high-tech approach to making it.
Instead of smart shots requiring royal jelly, they now require nanomaterial as a material and a control laptop as a tool to craft.
Smart shot implies that it's already technological to begin with rather than purely chemical. Furthermore, nanomaterial canisters are both more numerous than royal jelly, but are still largely found in lab finales and by disassembling CBMs, neatly slotting into the same role royal jelly did.
> feat(balance): make smart shot require nanomaterial 

- tests/monster_test.cpp
- fixes #6159
mark monmove tests as flaky
use deterministic terrain?
should pass
@DeltaEpsilon7787
> test: mark monster movement tests as flaky

- src/bionics.cpp
- Updates #6108 to make electrosense bionic scanner actually shut off if power is insufficient.
- I misunderstood the purpose of the `eff_only` argument being true, which is meant to only trigger the deactivation effect without actually running the check to see if the bionic can actually deactivate or deactivate the bionic. This is apparently done to simulate involuntary deactivations that have no relation to the other pre-reqs like deactivation cost.
- Change the structure of `deactivate_bionic()` such that it will always deactivate the bionic, with `eff_only` affecting whether this is considered an involuntary (no checks for `BIONIC_TOGGLED` or deactivation cost) or voluntary triggering of deactivation.
- Did this because all the true calls needed to set the power off anyway, and I …
> fix: Make the electrosense bionic scanner actually power down

- data/json/items/armor/boots.json
- data/json/items/armor/gloves.json
- tests/ranged_balance_test.cpp
Adjusted encumbrance and flags of various gloves and footwear to be more sensible. Handwraps made of leather, fur, or wool are no longer more encumbering or harder to fit inside other gloves than nomex gloves, for example.
For some godforsaken reason, a significant number of relatively simple to wear boots and gloves have ridiculously high encumbrance values and can never properly fit the player.
Adjusted the encumbrance and flags of multiple boots and gloves in order to make them a bit more sensible.
> feat(balance): reduce encumbrance of gloves and boots

- data/mods/Aftershock/items/weapons.json
Removed the magazine and magazine well fields from the energy saber weapon and its on variant which were causing errors. I don't even know how that got there, the weapon was always powered by UPS.
The aftershock item 'energy saber' was, somehow, coded to use both an internal battery magazine, and to be an non-reloadable UPS-powered weapon, causing errors whenever a player examined it or tried to pick it up.
Removed the magazine well and magazine fields from the weapon and its 'on' counterpart, leaving it UPS draw intact.
It doesn't cause any errors on my end when tested.
> fix(mods/aftershock): energy saber  battery bug

- data/json/items/armor/coats.json
- data/json/items/armor/undergarment.json
- data/json/recipes/armor/legs.json
- data/json/recipes/armor/storage.json
- data/json/recipes/other/vehicles.json
- data/json/uncraft/armor.json
- data/json/uncraft/generic.json
Some things to make synthetic fabric a touch easier to get ahold of, and expand on uses for it.
1. Added a recipe for webbing belts. Implemented as a reversible recipe, using an amount of material roughly consistent with the item's resulting weight. Level matches that of tool belt.
2. Replaced the uncraft for seatbelt with a reversible recipe for it, taking 1 `steel_tiny` and a fitting enough amount of synthetic fabric to make up the remaining weight. Set 2 levels higher than that of webbing belt.
3. Set boy shorts from cotton to nylon to add more variety to synthetic fabric items and to pair up with sports bra having been set to that material already.
4. Set emergency jacket from plastic/cotton to plastic/nylon to likewise help make it more distinct materials-wise.
Making webbing belt …
> feat(balance): use synthetic fabric in a few more items, recipes for seatbelts/webbing belts

- src/character_functions.cpp
- Resolves #5623 
- Resolves #5594
Magazine selection logic had a minor iteration oversight:
Instead of considering accepting a non-empty magazine if the contained ammunition matched ***any*** of the supported ammo types, the magazine was rejected it if it didn't match ***all*** of them,
Insert empty magazines in the weapon and magic-reload the rounds inside it without taking the magazine out.
Vanilla:
* Loaded game, spawned 1911-460, and 3 mags, one empty, one with 460 and one with 45
* Reloading works as expected with any given combination
Modded:
* Tested with Modern Weapon Pack Extended SCAR-H, works as expected too.
> fix: reloading magazine properly shows non-empty magazines with different, but compatible ammo

- src/character_functions.cpp
Went to look back at what broke the mag reloading in the first place, it was introduced with #4817 
#6174 partially reintroduced the issue, but in the form of you could then potentially load unsupported ammo into an empty magazine already inside a gun (300 Blackout on a STANAG on an AR-15)
This should solve that by further checking if the item being reloaded is a magazine, that is contained on a gun/mod that doesn't support said ammunition.
N/A
Vanilla:
* Spawn AR-15, Mags, 556 and 300blk ammo
* Can insert 300blk ammo on an empty mag
* Mag with 300blk can't be inserted in AR-15
* Insert empty mag on AR-15
* Can't load the empty mag with 300blk any longer
* Add underslug shotgun or M203
* Reloading still shows up shot/grenades as potential ammo to reload
Modded:
* Attach MWPE Six12 …
> fix: regression introduced with magazine reload fix

- src/pickup.cpp
Autopickup does not check contents of containers, which can result in strange behaviour with materials: material is whitelisted, but whitelisted item is inside a container, thus not picked up(alcohol for example)
Make pickup code check contents of container if check on item itself failed
- Compile
- Start
- Create material rule
- Check it works on item that's inside a container (bottle)
- Check it does not work on items that are not considered to be containers (magazines, tools with batteries, etc)
> feat: autopickup checks content of containers

- data/json/furniture_and_terrain/terrain-roofs.json
- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/mapdata.cpp
- src/mapdata.h
Add GUTTER to "connects_to" to prevent `t_gutter` and `t_gutter_drop` from connecting to terrain using the connects_to RAILING
Make the necessary changes to add GUTTER to the list of "connects_to"
Replace the "connects_to" of `t_gutter` and `t_gutter_drop` with GUTTER
none
I have no idea if this works or if it's the right approach, as my Visual Studio 2022 keeps failing to build a x64 release.
<details>
<summary>Screenshots:</summary>
<br>Before:
<br><a href="[https://github.com"><img src="https://github.com/user-attachments/assets/1a13ad2c-7571-47f0-b8ab-9f86556f8992"></a>
<br>After:
none
</details>
> fix: add GUTTER to "connects_to"

- src/monmove.cpp
- Saw Cataclysm-TLG/Cataclysm-TLG#457 and... figured we could use a version that appeals to my code aesthetics.
- To reiterate, the old method makes it so that special attacks are attempted in the order they are written into the special attacks entry.
- This meant that your first entry's cooldown decided the maximum number of special attacks you could theoretically give a monster before the first move came off cooldown and rendered the later ones impossible to trigger.
- Redoes the way special attacks are selected.
- First it creates a vector of valid monster special attacks.
- Then it rolls a random option from the vector and tries it.
- If the special attack fails, that option is removed from the list and we retry.
- Porting it?
- I... don't like the way it's written, I don't like the …
> refactor: Make special attack code for monsters choose random special attacks instead of using order of insertion.

- src/advanced_inv.cpp
- src/crafting_gui.cpp
- src/inventory_ui.cpp
Advanced Inventory Manager doesn't currently have filter history. The crafting filter's history scroll method is inefficient and doesn't allow entries to be removed.
Added an identifier for the AIM filter string_input_popup which enables history. Changed the crafting filter's string_input_popup's hist_use_uilist value.
Not doing things efficiently?
Tested in game that the filters were working as expected.
> feat(UI): input history on (adv) inventory, and disassembly

- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/iuse_actor.cpp
- src/iuse_actor.h
Maps (and used maps by extension) are in a weird situation:
* Reading a map reveals the terrain, but you have no idea of what got revealed.
* A previously read map is useless.
This PR makes so that when using a map, and subsequent usages of said map, a prompt is shown to display a non-explored, revealed, eligible overmap tile centered around the map reveal origin and range.
This also introduces *optional* JSON changes for the map iuse_actor, to refine the prompt, in the form of two fields, similar to the existing `terrain` one:
* `terrain_view`: what kind of terrain should be shown on the prompt
*  Defaults to the same as `terrain` if undefined.
* `terrain_view_exclude`: what kind of terrain should NOT be shown on the prompt.
* Defaults to `subway`, `hiway`, `road`, `forest_trail`, …
> feat(UI): Maps now can be (re)used to display a nearby eligible revealed overmap tile

- data/json/overmap/map_extras.json
Close #5250
By making mx_collegekids description shorter.
Change sentence in other way.
1. Teleport all over overmap until you see that map extra.
2. Check, if its description actually fits the screen now.
None
> fix: Shorten mx_collegekids description.

- src/main_menu.cpp
The hotkey for the new save format conversion option in the menu was missing. This leads to UB when it tries to access it. 
Give it a hotkey of 'f' for format.
No UB there now.
> fix(UI): Adds a hotkey for the save format in the main menu

- data/json/monster_attacks.json
Close #5761
Remove mentions of armor in monster_attacks.json
None.
1. spawn a monster or create a monster with "BIO_OP_IMPALE" special attack
2. wait until the monster uses the attack on you
3. read the log to notice difference
> fix: change phrasing in monster_attacks.json.

- src/panels.cpp
To make it easier to see where in the world the player is without having to constantly open the map.
Adds a line under "Place:" in the Location info panel that provides the coordinates.
Hitting the map button all the time while flying around. A total pain.
I ran around and compared the values shown in the info panel with those shown on the map screen. Tried out the various panel layouts to see that it displayed as desired.
> feat(UI): show overworld map coordinates in location infopanel

- src/item.cpp
You can't tell how many nanos an item created in the fabricator will cost until you create it.
Adds the cost as part of the name string on the template
I used a nanofabricator without any canisters with a variety of templates. The missing items message reported the same value as what I am displaying on the template.
> feat(UI): Add cost to the name on the nanofabricator template

- src/iuse.cpp
- fix #6217 which was due to my refactor of bionic scanner back to it's intended functionality being done in haste.
- Instead of `ammo_remaining()`, the game properly calls `has_enough_charges()`
- Removing the check entirely so it just spams the log with a failure to read bionics if it doesn't have enough power.
- Less processing intensive but waaaaay more annoying to the player in my opinion.
- Loaded up a game and tested that UPS consumption works fine and it doesn't automatically shut itself off.
> fix: Fix UPS usage again for bionic scanner.

- data/json/overmap/overmap_special/specials.json
Companion to my musings in the comments of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6223#issuecomment-2742013379.
Make outposts more common again, like I seem to remember them.
Makes the two military outposts `UNIQUE` instead of just limiting their max occurrences to 1, that way percentages are easy to mess with
- Try and mess with overmap terrain generation parameters to less-directly convince it to spawn them more often
It loads, and seems to work rather well.
Given we have 3 mansion variants over 50%, with two of them being 75%+, I think this is relatively fine.
Didn't touch bunkers as they seem to somehow spawn more often anyway
Helipads could maybe do with a reduction
> feat(balance): `UNIQUE`-ify Military Outposts, buff their spawn rate

- data/json/mapgen/lab/lab_surface/lab_surface_nested.json
Some of the nested mapgen used in the research facility used to have fridges, but after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4036, said fridges no longer appear.
Changed all "ḟ" to "f" in every nested mapgen in lab_surface_nested.json that uses `lab_workspace_palette` ("f" in this palette is used to place fridge)
none
none
> fix: missing fridges in some of the nested mapgen of the research facility

- data/json/items/tool/electronics.json
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6228
Adds the `SLEEP_IGNORE` flag to active bionic scanner.
Screaming.
1. Checked affected file for syntax and lint error.
3. Spawned in a scanner, turned it on and forced myself to be fatigued enough to sleep.
4. No more warning about active scanner.
> fix: add `SLEEP_IGNORE` to bionic scanner

- doc/src/content/docs/en/mod/json/reference/items/item_creation.md
- doc/src/content/docs/en/mod/json/reference/mutations.md
- doc/src/content/docs/en/mod/json/reference/vehicles/vehicle_parts.md
I oopsied and did 2 colons at the top instead of 3, and thus the note didn't format correctly. My bad!
Adds missing colons
Let someone else take the easy and tasty PR count
Equipped better eyeballs
At least this motivates us to set up a proper preview on PR for docs changes I guess?
> docs: Fix colon number in new files from #6232

- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/creature.cpp
- src/magic.cpp
- src/magic.h
- src/magic_spell_effect.cpp
Plastic golems were known to be absolute head snipers, and looking into the code, it was the case that all spell attacks had about a 70% headshot rate and the remaining 30% was torso shots. Additionally, it seems desirable for spells to be better or worse at hitting vital areas.
Also, this sort-of sets up for future of spells actually missing.
- Removes the part of the torso's if-statement in body part determinations that would prevent arms and legs getting hit by magic attacks
- adds min, max, and increment fields for "accuracy" in spell JSON
- adds a function to get the accuracy of a spell, with a special return for if the accuracy was defaulted
- changes the `missed_by` portion of the spell attack construction to either use the spell's accuracy if set, or a default of either 0.0 for …
> feat(balance): Allow spells to hit arms and legs, change spell attacks' `missed_by`

- doc/src/content/docs/en/mod/json/reference/tiles/plants.md
Otherwise docs don't build because I was a goober
lowercase the 't' in "title"
- Implode
n/a
And here I was, thinking I got away with no formatting or other errors on that last one.
> docs: lowercase 't' in "title" for plants page

- data/json/recipes/food/other.json
Mushroom spores were made obsolete and replaced by mushroom cultures but the recipe for Bird food still showed spores as a valid ingredient.
Removed mushroom spores (both regular and morel) from Bird food recipe.
Replace spores by cultures in the recipe.
Loaded into world with character who could craft Bird food.
Checked the recipe and saw spores were no longer an ingredient.
Not a hundred percent certain if "fix" is the right prefix for this PR's title. Perhaps "chore" would have been more appropriate ?
Used the single file method since only other.json was edited.
Didn't find any issue for this.
<!--
please remove sections irrelevant to this PR.
> fix: remove obsolete mushroom spores from Bird food recipe

- data/json/items/armor/belts.json
A basic military webbing belt can carry any item up to 2 liters in size, such as a tonfa, but the survivor belt, which is intended to be batman's utility belt, cannot.
Increased the survivor belt to have the same maximum volume and weight as a webbing belt.
> feat(balance): Updated Survivor Belt Maxes

- src/armor_layers.cpp
Fixes #6252 and provides a useful feature for people that don't want to manually go through all their clothing, mutations, and bionics to add it all up manually to see what their total armor value is.
Uses the armor-related functions of `Character` to get the relevant values, then adds them to the armor relayering UI somewhere that looked pretty empty
- Account for coverage
This would necessitate either editing the functions in `character.cpp` or adding new ones, both of which I did not feel like
- Add acid, fire, and env protections
These protections do not work the same way as bash, cut, stab, and ballistic and also I don't want to take up too much space for just protections.
- Compiles
- Loads
- Works for body parts with nothing on them and of course body parts with clothes
- Also …
> feat(UI): Add a total armor section to armor layering

- src/handle_action.cpp
… or above. Adds smaller wait options of 10 seconds, 30 seconds, and 1 minute if flying.
Right now, flying can be a real pain, especially at high speeds. It takes the game so long to advance just one second and traveling long distance means holding the button for a long time.
This makes the wait menu usable while controlling a vehicle if the character's z-level is 4 or more. It also adds a few smaller increment wait times to the menu, only when flying. There are no fuel checks so it is important not to wait past your fuel reserves.
I did not update the menu text out of concern as to how that would affect translations.
I flew a helicopter around trying to use the menu at levels below 4 (got the error message) and at 4+ (where it worked). I checked the timing on the new menu options and …
> feat(UI): waiting allowed when flying high with options for shorter waits

- src/vehicle_part.cpp
- fixes #6261 
Reset tow cables upon removing them as V_part, effectively disconnecting both ends
- Compile;
- Start;
- Connect two vehicles;
- Check towing works as intended;
- Check cable drops resetted, when removed from vehicle.
> fix: tow cables are detachable again

- src/activity_item_handling.cpp
- src/character.cpp
- fixes #6258
- fixes problem with missing tools on ACT_CHOP_TREE and ACT_CHOP_LOGS
- Do not override current mission and attitude if activity is set to `ACT_ASSIST`
- ACT_CHOP_TREE and ACT_CHOP_LOGS search for tools in `tools` vector, not `target` vector
Revisit npc activity logic
???
> fix: npc don't forget attitude after assisting, ACT_CHOP_TREE and ACT_CHOP_LOGS search for tools in proper vector

- data/json/recipes/ammo/components.json
- data/json/recipes/other/traps.json
- data/json/recipes/weapon/explosive.json
- data/json/requirements/explosives.json
- data/json/uncraft/weapon/explosive.json
We've been able to craft landmines and flashbangs for a long time, and a while back C-4 was made craftable, but not some other basic grenades and related components.
1. Added a recipe for standard frag grenades and for incendiary grenades, based on the uncrafts for them but with skill requirements bumped up a bit.
2. Accordingly, removed the uncrafts for frag and incendiary grenades as they're no longer needed, due to using reversible recipes.
3. Adjusted C-4 recipe some, bumping skill requirements up in exchange for adding booklearns. Now requires a circuit board and a proper delay fuse to craft, but in exchange it can now use lamp oil and comp-B as alternatives to the RDX and motor oil respectively, and also made reversible. Set it up such that it still returns RDX when taken apart by …
> feat: recipes for more grenades and fuzes, adjust C4 and landmine recipes

- tests/map_setup_helpers.h
Fix CI error 
Add catch header to relevant file
Move the specialization to a different file `tests/stringmaker.h`
Testing live! If CI doesn't yell at me then it works :D
> build: fix clang-tidy / clang-diagnostic error for StringMaker

- .github/workflows/msvc-full-features-cmake.yml
- .github/workflows/release.yml
As noted in #6274 and #6275, vcpkg currently wants to commit die because of the latest CMake version. This is unacceptable.
Pins CMake used to the most recent version before CMake 4 (3.31.6)
- [Wait Aeons for Microsoft to decide what they want to do about it](https://github.com/microsoft/vcpkg/pull/44273)
It appears to work on my fork.
CMake 4 is a lil asshole and doesn't wanna support stuff configured for older CMake versions
> ci: Pin Windows CMake

- .github/workflows/msys2-cmake.yml
Even after explicitly adding sol2 in the last go-around, it STILL refuses to build for Lua-related reasons that no-one can comprehend. At this point, it's either this or throw it out entirely imo, and having at least one test build without Lua seems like a great indicator for if we ever inadvertently make Lua mandatory in a PR without realizing it.
- Remove the sol2 package from its install script given it's pointless
- Turn Lua from ON to OFF in the cmake
- Delete / retire it entirely
Tempting.
Absolutely none other than using my eyes, but given the current status quo is it failing I consider that to be fine. (Also, testing can only be done by merging into main atm, and as such testing on my fork would be a lil too risky for my liking)
If some poor Windows soul ever decides to get a wild …
> ci: Disable Lua on the MSYS build that runs on every commit

- src/crafting.h
Making the MSYS2 + CMake build not use Lua apparently woke it up about a random instance of bad braces. Why it didn't notice them before, I do not know.
For once, this one isn't my fault, but I'll still fix it nonetheless.
<> -> ""
- Make the original author do it to atone for their sins
Eyeballs confirmed that it's now "" instead of <>
In the process, I also noticed that for some reason we have both a `# pragma once` AND header guards in that header file... and the header guards have been updated more recently than the pragma! Given that we can assume any compiler that can compile the game will support pragma given our use of modern C++ features, we should probably shift to just pragma in the future.
> chore: Fix the latest errant angle-braces on non-system headers

- data/json/loot_zones.json
- src/clzones.cpp
The current best solution for an "everything else" loot zone is a blank Custom Filter zone, but that gets triggered before any other sorting is done. This adds a new zone, called Dump, that collects anything that doesn't have any other place to go after all the checks have been made.
I added a new loot zone type zone_LOOT_DUMP and added checks to the category sort code to check if there's a category zone in range. If not, but there's a zone_LOOT_DUMP in range, it uses that instead.
I briefly considered moving the Custom Filter check to the end if it is blank, but it seems like it just makes more sense to have a new type.
I tested sorting with several item and zone types (including P.Food and Food), both with and without dump zones, and behavior was as expected.
> feat(UI): Adds new dump loot zone for items not otherwise sorted.

- src/monattack.cpp
Lil followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6268 to implement some feedback that got overlooked due to having the fix set to automerge:
In monattack.cpp, moved the uncanny dodge check in `attack::taze` back into the earlier if statement that makes it return without printing a message, since uncanny dodge already prints its own message. Also comes with a code comment to explain why.
Screaming.
1. Compile-tested in main branch prior to making this PR to test uncanny dodge and confirm this was happening.
2. Compiled and load-tested PR.
Skitterdi toilet
> fix: don't print two messages when dodging skitterbots with uncanny dodge

- data/raw/keybindings/keybindings.json
- src/overmap_ui.cpp
- src/uistate.h
While flying, when opening the map, you have to > a whole bunch to see any useful information. This resolves that.
Added a new toggle option that makes the map level default to 0 on opening.
I had my character stand on a building and I opened my map. It worked as normal. I pressed "."  (the default key for this option) and the map immediately went to level 0. I closed the map and reopened and it reopened to level 0. I pressed "." again and the map level switched to my character level. Closing and opening the map again showed that it was still defaulting to my level when the option was disabled.
> feat(UI): Adds new overmap option to default to Level 0 when map is opened.

- src/overmap.cpp
- src/overmap.h
`overmap::layer_backup` is used in `overmap::place_cities` as temporary storage and nowhere else. Does not need to be a part of the class. `array<map_layer, OVERMAP_LAYERS>` is pretty large, around 4.7MB of data. Without `layer_backup` the `overmap` is still bloated quite a bit by `std::array<map_layer, OVERMAP_LAYERS> layer` but at least now we've dropped the size by just under half!
Delete `layer_backup` from the class and make it entirely local to `overmap::place_cities`.
Copying an `std::array` is as simple as assignment, no need to use `std::copy` here so I got rid of that as well. There is nothing complex going on `map_layer`.
None, cutting the size of overmap almost in half with a few lines changed is great.
Started a few new worlds with new characters, mapgen didn't explode, seems …
> refactor: remove layer backup from class overmap

- data/mods/Magical_Nights/recipes/magic_tools.json
They're useful and don't make much sense to be super-duper locked behind booklearn
Makes the infusion bracelets autolearn and also removes the technomancer booklearn from them.
- Swap their primary and secondary skills
It loads
Took me long enough to get around to it lol
> feat(balance, mods/MagicalNights): Make infusion bracelets autolearn

- data/json/items/ammo/12mm.json
- data/json/items/gun/12mm.json
- data/json/items/gun/nail.json
- data/json/items/gunmod/mechanism.json
- data/json/recipes/ammo/other.json
- data/json/recipes/weapon/magazines.json
- data/json/recipes/weapon/mods.json
The H&K G80, despite being one of the most effective railgun weapon types in terms of raw efficiency, is unfortunately very often outshined by the Rivtech weapons in terms of power due to the G80's lower fire rate, relative rarity of the G80 and its ammunition, and the fact that Rivtech ammo is craftable but G80 is not. 
Furthermore, many handmade ranged weapons in the game are designed to utilize reusable ammunition, but they sadly do not scale up to the level of a simple 9mm SMG or a 5.56 or 7.62 rifle, which are very easy to get more ammo for and can be given silencers to reduce their noise levels. Pneumatic weapons have the powered air pump to improve their reload speed, the area they are worst at, but there is no equivalent for the makeshift railguns we can make.
Added steel 12mm …
> feat: H&K G80 steel slugs, handmade coil capacitor, adjustments to coilgun and G80

- data/json/items/armor/bandolier.json
- data/json/items/armor/belts.json
- data/json/items/armor/holster.json
- data/json/items/armor/storage.json
Added compact to bandoliers, belts, holsters, and pouches that could reasonably be made to fit underneath or on top of other things in that slot.
Although several belt items in the game reasonably would be able to be adjusted on top of, underneath, or above or below similar items, they do not have the compact flag, leading to such utterly ridiculous results as the survivor harness- a harness which stretches across most of your upper body and thus would be completely adjustable- causing extra encumbrance when worn with a leather belt or a bandolier, two _other_ things that are completely adjustable and can be moved around.
Added the COMPACT flag to a number of belted items which most likely could be worn next to other items on the same layer and body part.
The back holster is compact but …
> feat(balance): add compact flag to more items

- data/json/items/tool/electronics.json
Bionic scanner when on was multiplying it's value by it's battery charge count because it lacked ammo and magazine definitions.
Make it copy from the off bionic scanner to give it those definitions.
Tossing it into the fiery pits of mordor or something.
> fix: bionic scanner multiplying values

- src/overmap_ui.cpp
- src/string_input_popup.cpp
There were some complaints about the location of the history window (and I didn't like it either). Also, the map search needed history as well.
When defining a custom window area for string_input_popup, it wasn't defining the w_full window that the history popup relied upon so the window was being drawn at 0,0. I updated the window method to create the w_full regardless.
Verified that the windows showed up in better locations (the best I could do without possibly breaking something else) and that the map's search history was functioning.
> feat(UI): relocate history panels, add overmap search history

- data/json/items/tool/tailoring.json
- data/mods/Magical_Nights/items/enchanted/enchanted_misc.json
- data/mods/Magical_Nights/items/tools.json
Added scute to list of items a sewing kit can modify, but not bone or wood needles since scute is hardened bone. Added scute, pocketed, resized_large, and nomex_padded to tailor's kit and enchanted tailor's kit in Magical Nights
Magical Nights overwrote the tailor's kit, removing the pocketed, nomex padded, and resized_large modifications, and the enchanted tailor's kit was also missing those. Furthermore, the enchanted tailor's kit and the basegame sewing kit were missing the ability to repair scute items.
Added missing materials and modifications to the MN tailor's kit and enchanted tailor's kit, and to the basegame sewing kit.
> fix(mods/MagicalNights): tailoring missing materials/modifications

- src/catalua_bindings.cpp
- src/catalua_bindings_creature.cpp
- src/character.cpp
- src/character.h
- src/item.cpp
- src/item.h
There's always room for more lua bindings.
Added bindings for tname and display_name to items
Added all(?) of the "is_[something]" bindings for items
Ammo bindings for items
Some of the "get_[something]" bindings
create_item for lua item creation
docs/removed/fixed a few bindings from #6290
Tested most of them in the lua console, didn't run into any issues but as always ymmv.
> feat: even more lua item bindings

- data/json/mapgen/toxic_dump.json
- data/json/recipes/electronic/components.json
- data/mods/Aftershock/recipes/recipes.json
Aftershock contains two recipes for plutonium fuel cells, but one overrides the other and both are outdated by this point. Furthermore, toxic waste dumps- literally the only place plutonium slurry spawns- only spawn plutonium slurry at 5 or 2 probability depending on the type, while sewage, something that already has its place with sewage treatment facilities and sewers, has a 50 prob chance to spawn.
Removes specified recipes from aftershock files, add new combined and corrected recipe for plutonium fuel cells to basegame. Removed sewage sample chance to spawn in toxic waste dumps and increased plutonium slurry and watery plutonium slurry chances to spawn.
It doesn't cause any json errors on my end.
I'm not absolutely sure
> fix(mods/aftershock,balance): mainline plutonium fuel cell recipe, bump toxic waste dump plutonium slurry spawn chances

- data/json/recipes/chem/chemicals.json
This makes it a bit less hassle to make soap when you've only got a small amount of material.
Cut the lye and fat requirements of the soap recipe in half, and set it to make 5 charges instead of the default of 10. Time requirement also reduced from 45 minutes to 30, not exactly half since it already has batch time savings.
Letting 1 lye and 1 dose of fat make 10 units of soap anyway.
2. Ported to laptop playthrough and load-tested, recipe uses less material and says it gives me 5 units now.
> feat(balance): make soap recipe more granular

- src/player_activity.h
Wrong bool checked on call of is_assistable()
Change to call a correct variable
> fix: player activity assistable() checks wrong bool

- src/catalua.cpp
I wrote a lua iuse_function that displays a message after a few minutes using gapi.add_on_every_x_hook, and I was under the impression that returning false would deregister the hook for a one-time use kind of thing. Testing it resulted in messages being repeated endlessly, and it seems like those hooks never get removed, so every call to add_on_every_x_hook adds another permanent hook to the save.
Change run_on_every_x_hooks to erase hooks that return false on the lua side, returning anything else should work the same as before.
Writing a new function like add_one_time_hook, but this is way easier and requires less C++ knowledge.
I tested an iuse_function returning different values:
return false: hook runs once and stops
return true: hook repeats forever
return 0: hook repeats forever
no …
> feat: allow for lua once_every_x_hooks to remove themselves by returning false

- src/catalua.cpp
- src/character.h
- src/game.cpp
- src/monexamine.cpp
- src/monster.cpp
- src/monster.h
- src/suffer.cpp
Moves per turn calculation is reduced by player_weight / 4.8kg, regardless of how much the mount can carry (calculated from its weight * mountable_weight_ratio) 
* Makes calculation while mounted take into account how much the mount can carry, having only the weight past the mount capacity impact the move cost.
* Changes the downed triggers when overburdened to take into account if the player is mounted or not, and use the mount carry weight instead of the player's.
* Increases the checks for if a given critter is mountable due to weight to a higher threshold (same as player downed, 4*carry weight)
N/A
* Set survival skill to 4
* Spawn horse, 
* Make it mountable with fooder.
* Spawn heavy duty frames and a large rucksack.
* Get over-encumbered by moving frames to rucksack.
* Horse should …
> fix: take into account mount carry capacity when calculating movecost

- src/consumption.cpp
- src/inventory.cpp
* resolves #6305 
Consumables *sometimes*, will lose their assigned invlets.
This is because inventory_location::restack will re-group items and re-assign their invlets, but if the consumed item is not the first on its stack, it will lose its invlet while the rest of the stack keeps it.
Sort the individual item stacks before re-grouping, so the item with less charges is at the front.
Doing so will make so when re-stacking, the used item keeps the invlet, instead of the others.
As an aside, the invlet is applied to the container itself, and not its contents:
So I've made it when a consumable in a container is completely used, it will try to re-assign the invlet to another matching container that has the consumable type inside it, if not favorited or worn.
N/A
* Spawn multiple stacks of …
> fix: keep invlet to the consumed item if it was split off from the main item stack

- data/json/furniture_and_terrain/terrain-doors.json
- data/json/furniture_and_terrain/terrain-fences-gates.json
- data/json/furniture_and_terrain/terrain-windows.json
- doc/src/content/docs/en/mod/json/reference/tiles/furn_and_terrain.md
- src/activity_handlers.cpp
- src/iuse.cpp
- src/mapdata.cpp
- src/mapdata.h
Prior to this PR, this section of the code was a big wall of hardcoded if statements and that was pretty shitty and did not allow for mods to add their own nail-pullable terrain. Naturally, people want this to change.
Also, generally, un-hardcoding things is good.
- Adds two new fields to terrain: `nail_pull_result` and `nail_pull_items`
- `nail_pull_result` holds a terrain ID that it should be transformed into when the nails are pulled
- Defaults to some variety of NULL
- `nail_pull_items` is an array that holds the integer (short) number of nails and planks (in that order) to drop.
- Defaults to {0,0}, and thus is *technically* optional if you don't want it to drop any nails or planks
- Un-hardcoded the check on the hammer itself to check for a non-null `nail_pull_result`
- Un-hardcoded …
> feat: JSONize pulling nails

- src/mapdata.cpp
While testing my previous PR I briefly considered trying to use a reader to get the array values in (long story), so autoincludes fucked it up in VS Code / Clangd
Also, somehow the two readers in the file don't need it pulled in.
Remove offensive line to make msys2 build on commits happy
- Just make it a "" include
It worked before, and nothing in my previous PR actually used it in the final result
Aaaaa why does clangd/VS Code default to <> instead of ""
> chore: Remove unused include in mapdata.cpp

- src/cata_tiles.cpp
- src/cata_tiles.h
- src/iuse_actor.cpp
- src/overmap_ui.cpp
- src/savegame_json.cpp
- src/sdltiles.cpp
- src/uistate.h
Highlight select tiles revealed by the (secondary) map usage action from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6204#issuecomment-2729904542
Using a map will now also highlight the selected POI kind from map usage, if in range.
Highlights are persistent, kept until cleared by:
* (E)xploring the tile
* Opening a map again, but aborting the action
N/A
Launch game.
Spawn any map.
Use it and select a POI kind, either random or closest.
All tiles of the selected kind in the map range will be highlighted on the overmap view.
(E)xploring the tiles will clear the highlight.
Reusing the map and aborting the action will clear all highlights.
Overmap highlights should be persistent (stored in uistate), and kept separate between saves/loads.
Since it can be cleared by using any map, I …
> feat(UI): highlight overmap tiles revealed by map usage

- tools/clang-tidy-plugin/CMakeLists.txt
- tools/clang-tidy-plugin/CataTidyModule.cpp
This needs to go first so that the other two PRs can depend on it
Disable header guards being checked by clang-tidy
- Just merge the previous PR despite clang tidy timing out
Evidently, opinion is against doing that.
It worked before, it ought to work again
After this gets merged, the other 2 PRs will be opened
> ci: Disable clang-tidy header checks (Pragmatization 0/2)

- CMakeLists.txt
- resolves #4983
(long and painful convo with gemini 2.5 pro)
1. uses https://cmake.org/cmake/help/latest/module/ExternalProject.html to clone https://github.com/ianlancetaylor/libbacktrace.git as `libbacktrace_external`
2. adds the build biproduct and include dir to `backtrace`
tell people how you have to build and link libbacktrace manually to get enhanced backtrace speed
```sh
$ mkdir -p build
$ cmake \
-B build \
-G Ninja \
-DCATA_CCACHE=ON \
-DCMAKE_C_COMPILER_LAUNCHER=ccache \
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DCMAKE_C_COMPILER=/usr/bin/clang-19 \
-DCMAKE_CXX_COMPILER=/usr/bin/clang++-19 \
-DCMAKE_INSTALL_PREFIX=$XDG_DATA_HOME \
-DJSON_FORMAT=ON \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCURSES=OFF \
-DTILES=ON \
-DSOUND=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \ …
```
> build: auto-install libbacktrace on Linux

- src/monmove.cpp
fixes #6324 
While not having monsters blob up is usually a good thing it's not useful for monster infighting.
Removing the entire conditional solves the issue. I'm not sure how much of an issue monster balling actually is. Monster ball prevention should probably be handled at the planning phase not the moving phase of monster actions.
Add a mon v mon hostility check so that if a mon it doesn't like is in the goal location it considers it the same as an NPC / Player and willingly ball up around it.
Setup:
1. New world, new character
2. Build the thunderdome (submap or larger sized concrete walled area)
3. Equip player with the architect's cube for clairvoyance effect
4. Spawn a `zombie nurse` and `nurse bot` at the 1/4 and 3/4 partitions of the Thunderdome
Tests:
| Test              | …
> fix: fix monster infighting

- data/json/itemgroups/Locations_MapExtras/map_extras.json
- data/json/itemgroups/Weapons_Mods_Ammo/ammo.json
This tackles some problems with supply crates, following up on https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6223
1. Adjusted the food and drug spawns a bit, with the `mil_food` spawn broken up in half, half that previous weight spawning the same "military food plus sometimes drugs including top-tier stuff" while the other half spawns just the food but more of it (1d2).
2. Fixed ammo belts to not use their intended weights as charge amount, making them more rare but actually spawn with the intended default amount of ammo when they do show up.
3. Tweaked `ammo_launcher_grenade` again, shifting away from the previous 1-50 spawn in favor of 1d3 stacks of default ammocount (so, 6-24 for ), making spawns more consistent. Basically the start of retweaking …
> feat(balance): spawn 1d3 stacks for grenade ammo, more food in supply crates, fix ammobelt spawns

- data/mods/default.json
We realized that this seems like a very popular mod to enable anyway, and even if you feel like it's bloat you can just disable it like you would the no-revival mod (which I would argue is a far more intrusive mod than this to have on by default anyway). 
- Adds `pride_flags` to the default mods json file
- Straight up make it vanilla
**I** certainly wouldn't object or mind it, but for now it seems a fair compromise to make it a default mod instead to satisfy those who have bloat concerns.
It does indeed automatically enable it in the world creation screen
Also, I'm not opposed whatsoever to the mod's scope expanding beyond just pride flags to all sorts of other pride-related and adjacent items. Or to additional (good quality) flag PRs.
> feat: Make the Pride Flags mod default

- data/json/recipes/weapon/explosive.json
Improvised demolition charge can create a massive explosion for a measly 550g~ of ammonium nitrate pellets, an amount even lower than a pipe bomb. It's crude, simple and nonsensically efficient.
Increases the explosive filler cost to be 4x of a pipe bomb (30 for pipe, 120 for demo charge). Item weight checks out.
Demolishing the entire city with one sack of fertilizer
Could be still considered OP when you look at it from certain ways but this seems to be the fastest way to bring it within limits of reason.
> feat(balance): nerf explosive filler cost for improvised demolition charge

- data/json/obsoletion/migration.json
#6346 made it so that `22_cb` ammunition no longer existed and removed them from itemgroups, but did not define a migration for it, meaning any games with them would have them poof out of existence rather than convert into appropriate ammunition.
Define a migration for it.
- Add back the `22_cb` ammunition entry to obsoletion, create a game, spawn in the ammunition and save. Then remove the `22_cb` entry
> fix: migrate `22_cb` to `22_cphp`

- src/activity_actor.cpp
- src/damage.cpp
- src/game_info.cpp
Was mildly annoyed seeing the build warnings whenever I would rebuild the project. This is not an exhaustive sweep of warnings, just ones I encountered very recently. And one bug fix.
in `throw_activity_actor::deserialize` fix bug where we attempt to use an uninitialized (nullptr) unique_ptr. This threw up three warnings about likely accessing something at address zero because `actor == nullptr`.
in `damage_unit::get_name` fixed warning about flow control reaching the end of a non-void function. Added a default return despite probably being unreachable.
in `game_info::save_file_version` we have another flow control warning. It *should* be unreachable, but add a default return string there as well.
in `shell_exec` the compiler was getting mad about ignoring the attributes for `pclose` so …
> build: resolve some build warnings

- src/CMakeLists.txt
> [!IMPORTANT]
> <img width="50%" src="https://github.com/user-attachments/assets/e59956f2-2219-4162-a09a-c5ed1ac9d285">
> disclaimer: commit made by AI (Claude 3.7 Sonnet)
contributes to #3113 by making CMake less headache
extracted common setups to `setup_common_target_properties`
keep it spaghett
| Tiles | Curses |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/3057e947-e94e-4beb-97bb-5a100cde465a) | ![image](https://github.com/user-attachments/assets/8cec2e89-1c81-41f6-8b47-422fc54c5632) |
was able to build both tiles and curses variant with following commands:
<details><summary>Tiles</summary>
```sh
$ mkdir -p build
$ cmake \
-B build \
-G Ninja \
-DCATA_CCACHE=ON \
-DCMAKE_C_COMPILER_LAUNCHER=ccache \
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \ …
```
> build: deduplicate `src/CMakeLists.txt`

- src/activity_actor.cpp
- src/activity_actor.h
- src/activity_actor_definitions.h
- src/activity_handlers.cpp
- src/activity_speed.cpp
- src/activity_speed.h
- src/crafting.cpp
- src/crafting.h
- src/player_activity.cpp
- src/player_activity.h
Part of #6002 
Separating activity speed code should provide:
- cleaner player activity code;
- creation of a separate activity speed entity, that would allow calculating factor-based completion time for activities, for preview purposes.
Moving all `activity_speed` related code to a separate entity
- Compile
- Start
- Check that activities perform same way as before, without crashing.
> refactor: separate activity speed code from player activity

- data/json/items/vehicle/utilities.json
- src/vehicle_part.cpp
Got pinged by @RoyalFox2140 about fridgetanks not working. Was surprised when I looked at the code and realized it'd _never_ functioned as a container to begin with. What the fuck?
Gives fridgetank base items container values so that it is actually considered a container for fluids.
Updates the temp considerations in `vehicle::process_contents()` so that it takes into account fridge and freezer stats.
- Code is shit as always, see additional context.
- Spawn 4 gallon jugs of milk, create a vehicle with a storage tank, a fridge tank, a cargo hold, batteries and an electronics control.
- Fill each of the tanks with a gallon of milk each, then leave a gallon jug on the floor and one in the cargo bay.
The methods used to process items in vehicles is inefficient, as fluids in fluidtanks are …
> fix: Fridgetanks work now

- src/creature.cpp
`no_crits` shots had a random chance of upgrading a hit that would've only hit the torso into becoming a headshot.
Discovered during discussion of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6349
In creature.cpp, changed the logic for no-crit shots in `Creature::deal_projectile_attack`. It now separates the potential head and torso hits by `hit_value` instead of randomly trying to deal either, with headshots now only occurring if the aim is good enough AND if it passes a coin flip, then only allowing a torso shot 75% of the time if the `hit_value` would've been a bodyshot, and then passing it on to the limbs as normal.
Completely removing the chance of getting a headshot with `no_crit` attacks entirely, making all shots of `hit_value` 0.4 or lower only ever able to hit the torso, …
> fix: don't allow `no_crit` shots to upgrade what would've been a torso hit to a headshot

- data/json/uncraft/generic.json
Laptops, despite being, like all computers, deliberately easy to modify and disassemble, take an hour to disassemble in full.
Laptops are now able to be disassembled in 15 minutes instead of an hour.
> fix(balance): laptop uncrafting time

- data/json/professions.json
PR https://github.com/cataclysmbnteam/Cataclysm-BN/pull/550 made it so a hacker spawns with a battery in their laptop and game system. 
I don't know how, I don't know why, at some point both items became UPS compatible non-unloadable non-reloadable devices. I don't know if they were added erroneously in 550, or if we never updated professions AFTER such a UPS conversion PR. Why investigate whose at fault?
Removes the batteries that were forcibly jammed in there.
:(
:(
Why do I always run into these problems?
:(
> fix: Hackers don't jam batteries into their UPS devices

- src/assign.cpp
- src/assign.h
this is the worst linting rule i've ever seen, it has zero pros and causes numerous headaches like #6373
remove the check.
remove `strict` field for `assign` functions as well, but this is more involved, and we might want to use the `strict` parameter for other validation such as #3112
loaded commit before #6373, no errors were generated.
> fix: remove checks forbiding value to be same as default or inherited

- data/json/debug_spells.json
- src/handle_action.cpp
- src/magic.cpp
- src/magic.h
RoyalFox requested it.
Also, it seems helpful in general as a feature, much like my previous change to allow martial arts to require mutations. I may find a usage for it at some point in MN, and it might be nice for anyone else doing traditional methods of learning spells (i.e. not the Arcana way where everything's tied to mutations anyway and thus it's easier cancelled out by the traditional mutation incompatibilities)
- Adds a new optional `"blocker_mutations"` field to spells that takes an array of mutation ids to block casting the spell for having.
- Adds the c++ required to do so
- Prevents you from casting if you have a mutation the spell doesn't like, prints out a message informing you which one is blocking
- Print the blocker mutations in the spellbook UI
- Add a debug spell for …
> feat: Allow for casting spells to be blocked by mutations

- data/mods/MagicalNights/worldgen/wizard-towers.json
Nobody likes the doors being locked like this.
Use the simply closed variety instead
- Improve teleportation and make that mandatory instead
- Add a computer for no good reason
- Use pickable doors
- Supply a pickaxe right there
Loaded in, confirmed it worked correctly
Simple PR I know *someone* has been waiting on.
> feat(mods/MagicalNights,balance): Change wizard tower metal doors to the non-locked variety

- data/json/itemgroups/Drugs_Tobacco_Alcohol/drugs.json
- data/json/itemgroups/vending_machines.json
PR https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5316 Absolutely smashed a lot of balance with how many antibiotics can spawn in grocery stores, this dials it back.
New item group just for medical vendors, focused on OTC stuff with some tramadol and codeine that wasn't looted but is rare.
REDACTED
Loads in my current save file.
:(
> fix: don't overwhelm stores with antibiotics

- .github/workflows/pull-translations.yml
because why not?
faster translation updates are always good.
pull daily instead of weekly
<https://crontab.guru/#0_21_*_*_*>
> ci: pull translations daily

- .git-blame-ignore-revs
makes blame feature more helpful by not showing meaningless formatting changes
add the file. unfortunately, you need to manually enable the feature by running
```sh
git config blame.ignoreRevsFile .git-blame-ignore-revs
```
crave
see:
- https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt
- https://gist.github.com/kateinoigakukun/b0bc920e587851bfffa98b9e279175f2
> chore: add git blame ignore-revs-file

- data/json/itemgroups/Weapons_Mods_Ammo/gunmod.json
- data/json/items/classes/gun.json
- data/json/items/gunmod/sling.json
- data/json/professions.json
- data/json/recipes/weapon/mods.json
- src/handle_action.cpp
PR created on behalf of @Patternseeker to split #6362 
> i want to be able to sling over pistols with stocks & mod foregrips & other shit
>
> - by @Patternseeker
> Adds a pistol lanyard item along with sling slot for most pistols. It's basically a shoulder strap.
>
> - by @Patternseeker
> feat: add pistol lanyards

- data/json/items/ammo/380.json
- data/json/items/ammo/762x25.json
- data/json/items/ammo/9mm.json
I looked up "proportional": { "recoil": and realized something is not quite right with the values. +P is 2 and +P+ is 1.5 despite being way stronger, genius!
9mm +P+ has a recoil proportion of 3
brings 7.62 up to other +P rounds by increasing its recoil proportion to 2
adds a bit of AP to .380 +P
> feat(balance): Make 9mm recoil `+P+` > `+P`, add AP to `.380 +P`, increase `7.62x25mm` recoil

- data/json/construction.json
- data/json/construction_group.json
- data/json/furniture_and_terrain/furniture-appliances.json
- data/json/items/fake.json
Adds a grid gunsmith kit.
My charger is too cluttered and a gunsmith kit uses 25 charges per use, so it requires sitting on the charger constantly on top of a ton of other stuff. I could clear the charger but it would still have a ton of necessary items.
Adds gunsmith repair kit to the grid furniture.
WELL I WANTED TO DO MORE but workbenches don't work with fake items because its examine action is required
It works, it repairs my HK417 and it cleans/lubricates. It's still used in crafting.
None
> feat: add grid gunsmith kit

- data/json/itemgroups/Clothing_Gear/clothing.json
- data/mods/pride_flags/item_groups.json
Mods cannot properly work with inlined distributions and the like, and thus this is good for mod support.
Also breaks it down into smaller chunks that other itemgroups can potentially use later.
- Un-inlines various distributions
- Also simplifies the differences between the childrens and non-childrens versions of the unisex accessories
- Removes a camo tank top that was in the cloaks itemgroup for some reason alongside the vests to make naming the itemgroup simpler
- Makes the pride_flags mod actually put the pride flags in at the same general rate as the American flag so that they aren't about 10x more common (whether the flags in general should be more common is another question, I just think they should be at roughly equal rates)
- Pull flags specifically out of their itemgroups
- Do …
> feat: Un-inline some clothing itemgroups

- data/json/items/ammo/22.json
- data/json/items/ammo/32.json
- data/json/items/ammo/38.json
- data/json/items/ammo/380.json
- data/json/items/ammo/38super.json
- data/json/items/ammo/40x46mm.json
- data/json/items/ammo/40x53mm.json
- data/json/items/ammo/45.json
- data/json/items/ammo/46.json
- data/json/items/ammo/57.json
- data/json/items/ammo/762x25.json
- data/json/items/ammo/9mm.json
- data/json/items/ammo/9x18.json
- doc/src/content/docs/en/mod/json/reference/items/item_creation.md
#6402 made 9mm +p+ as strong kicking as a .308 (oops) and while inspecting the code I realized some inconsistencies and plain goofiness like 5.7 and 4.6mm rounds having 90 recoil along with grenades having 225. This is physically impossible.
Makes the +p recoil proportion multiplier uniform >> 1.2 to represent a 20% increase.
It can be argued that different kinds of ammo from different manufacturers could have 10%-40% of extra recoil compared to the common version but 20% seems like a good rounding.
Sets recoil proportion multiplier for buckshot/flechette grenades to 1.2 and slugs to 1.4
Full list of stuff changes (no abstracts):
22lr CPHP: 1.5 > 1.2 mult
32 ACP: 150 > 250 - almost has twice the energy of .22lr
38 spec: 250 > 350 - almost has triple the energy of 22lr
380 +p:  2 > 1.2 …
> feat(balance): Adjusts recoil values for small caliber rounds and 40mm grenades

- data/json/overmap/multitile_city_buildings.json
I suspect that the road connection and the use of the static road for this location make it somehow fail to appear in town but if that's not the case, the location doesn't need them anyway.
Remove the road connections and static roads from the location.
none
I make my character appear in the game at the location via a scenario.
> fix: remove the road connection of urban_23_dense_office_theater

- src/iuse.cpp
- src/iuse_actor.cpp
remove annoying build warnings
removed unused functions
followup to #6410
> refactor: remove unused functions

- src/npctalk.cpp
Improve roleplaying user experienc
Allow the player to monologue (previously emote) to themselves for roleplay purposes
Port DDA changes:
https://github.com/https://github.com/CleverRaven/Cataclysm-DDA/pull/61490/
https://github.com/https://github.com/CleverRaven/Cataclysm-DDA/pull/71427/
Additionally, I've added a context feature that allows you to specify if a message is m_good, m_bad, or m_info by adding +, -, or ? at the beginning
Don't make me say it (not adding it)
Spawned in a world, pressed CTRL+C to open speech menu, and verified the user can add messages to the log with proper context
NOTE: All of these have been renamed to "monologue"
> feat(port): add "monologue" action in speech menu with context

- data/json/vehicleparts/utilities.json
pots and pans are not part of the crafting recipe so should not drop from the advanced butchery station
removes the drops from the item
adding more pots and pans
followup to #6166
> fix: remove pots and pans being dropped from the advanced butchery station

- src/monster.cpp
- src/monster.h
Fixes #6412
Bug introduced in #5394
`monster` did not have an overload for 
`Creature::deal_projectile_attack( Creature *source, item *source_weapon, dealt_projectile_attack &attack )` so the call to it in `ballistics.cpp` [L435: critter->deal_projectile_attack( null_source ? nullptr : origin, source_weapon, attack );](https://github.com/OrenAudeles/Cataclysm-BN/blob/152482b5e2e90d240c12dd89b49d5a6ce7721e04/src/ballistics.cpp#L435) would route in all cases to the one defined for `Creature`.
So the solution is to add in an overload so that call resolution goes to the `monster` version properly.
Also forwards the `source_weapon` parameter to through the `monster::deal_projectile_attack` call to where it calls `Creature::deal_projectile_attack`
Ran with debugger gdb and set a breakpoint on …
> fix: monster on_hit actions trigger properly

- src/activity_speed.cpp
- src/crafting.cpp
- src/crafting.h
- part #6002.
- Fixes missing hands workbench type, which was resulting in workspeed penalty in certain circumstances
- Add missing value;
- Add appropriate checks.
- Compile;
- Start;
- Perform an activity that requires workbench;
- Check nothing breaks;
- Check u don't have penalty for missing workbench if item is small enough to work in hands(below 5 kg and 10 L).
> fix: introduce missing `hands` workbench to activity speed formula

- src/world.cpp
resolves #6436
flip enum
not flip enum
defaults to V2 on world creation
> chore: use V2 save format as default

- src/catalua_bindings.cpp
- src/catalua_bindings_ids.cpp
- src/catalua_luna_doc.h
- src/trap.cpp
- src/trap.h
I hoped ever that traps(especially PORTAL) can be handled by somehow.
Add Lua binding for traps and some of member functions of `map`.
The functions enable traps to be set, changed, or removed on map.
Gently weeps
Checking the trap below me:
~~(Don't be surprised. A rollmat is a trap!)~~
Set the trap next to me:
> feat: Add Lua binding for traps

- .github/workflows/manual-release.yml
- builds no longer fails successfully because you forgot to erase existing tags
- easy to understand workflow
[Github CLI my beloved](https://cli.github.com)
- if there's no release with given tag, create one
- build and upload assets
weep violently
https://github.com/scarf005/Cataclysm-BN/actions/runs/14712691311
works on my fork: https://github.com/scarf005/Cataclysm-BN/releases/tag/untagged-373935b5564b20e23f97
> build: simplify manual release

- CMakePresets.json
this is the build preset that i use; using it simplifies build step for everyone and simplifies tech support process 
update the build preset with mine
not do it
run it like this:
```sh
cmake --build --parallel 10 --preset linux-full --target cataclysm-bn-tiles
```
TODO: write build guide using with this preset after mdbook migration
> build: add `linux-full` cmake preset

- deno.jsonc
- doc/src/content/docs/en/dev/reference/cli_options.md
- src/catalua.cpp
- src/catalua.h
- src/main.cpp
- src/path_display.cpp
- src/path_info.cpp
- src/path_info.h
because `PATH_INFO::lua_doc_output` is too flaky. its output path was determined by `config_dir_value`, which differs per OS and build flag. this makes `deno task docs` command unreliable.
make `--lua-doc` accept path to output file instead.
print to stdout instead? tho most of time you'd rather generate the output in file
works in my machine
i need to automate lua docs generation in CI sometimes later aaaaaa
> feat: write lua docs to given path

- data/json/items/melee/swords_and_blades.json
No other item in the game has NO_CVD and other stats reveal this thing hasn't been touched in quite a while.
Updates item desc.
Removes NO_CVD flag
Reduces tohit from 2 -> 1
Increases bashing 2 -> 4, cutting 20 -> 22
Adds steel to materials
Greatly reduces butchering quality
Rarity unchanged. Being the rarest knife in the game it should also pack more punch than a regular medieval dagger, no?
> feat(balance): Removes NO_CVD flag from RM42 knife, adjusts stats

- data/json/items/ammo/46.json
- data/json/items/ammo/57.json
- data/json/items/gun/57.json
Feedback for #6409 and #6362
Makes the 5.7 and 4.6 rounds slightly flatter, increases Five Seven handling and bumps up its damage malus to reflect muzzle length velocity loss compared to the P90.
> feat(balance): decreases 5.7x26mm and 4.6x30mm recoil, increases FN Five SeveN handling

- src/iuse.cpp
If we take that 100 moves = 1 second then it takes about 150ms (15 moves) for a normal human to mop up a small area (1 tile = 2x2 meters?). That's an embarrassingly short amount of time.
I increased the moves required per mopped tile tenfold (to 150 moves). I think it's a good number.
Increasing the time it takes to mop even further (might be too much in case of combat mopping acid pools under yourself)
Trying to speed-mop my house IRL instead of using arbitrary numbers
1. Started a world as a normal human with 100 moves
2. Spawned a mop and some blood splatters
3. Mopped a couple times, with each tile mopped up being 150 moves
Honestly I just wanted an excuse to figure out how to set up git (it took 50 times longer than actually making this change
> feat(balance): increase time it takes to mop tiles

- data/raw/keybindings/keybindings.json
- src/avatar.h
- src/character.h
- src/newcharacter.cpp
Reduce carpal tunnel
based on https://github.com/CleverRaven/Cataclysm-DDA/pull/78634/, I think there was a previous PR that added randomization to other pages but I can't find it so I just recreated the functionality myself from this PR
Also includes changes from PRs
https://github.com/CleverRaven/Cataclysm-DDA/pull/46731
https://github.com/CleverRaven/Cataclysm-DDA/pull/60959
Add a "Randomize selection" keybind to traits, scenarios, professions, and skills tab of character creation. This has been renamed from DDA's "Randomize" to be more descriptive of what it actually does, as there was some discussion on their end that the behavior was odd.
Add a "Randomize avatar" keybind to traits menu
Makes "Random character" start randomize appearance but not "custom character"
The usual
Created …
> feat(port,UI): random selection keybinds for traits, scenarios, professions, skills

- data/json/npcs/isherwood_farm/NPC_Jack_Isherwood.json
Fix mismatch between mission name and item count in `MISSION_ISHERWOOD_JACK_1`.
Updated mission name from "Find 10 3L jars" to "Find 20 3L jars" to match `count` value and NPC dialogue.
Change the `count` value and dialogue line to match the original mission name ("Find 10 3L jars").
```json
"id": "MISSION_ISHERWOOD_JACK_1",
"name": { "str": "Find 10 3L jars" },
"count": 20,
"dialogue": {
"offer": "We could use some 3 liter jars to preserve our produce.  Can you bring me 20 large three liter jars?  I'll give you some preserves in exchange.",
}
```
> fix: update mission name in MISSION_ISHERWOOD_JACK_1 to match count

- src/calendar.h
- src/fmtlib_format.h
- src/units_angle.h
- src/units_energy.h
- src/units_mass.h
- src/units_money.h
- src/units_probability.h
- src/units_temperature.h
- src/units_volume.h
https://github.com/fmtlib/fmt/issues/3607
clang 20 complains about spaces between `operator""` and `_<name>`
> style: remove spaces in `operator"" _<name>`

- data/json/items/bionics.json
> for small documentation fixes, it's okay to ignore the template
> fix: typo in Teleportation Unit CBM description

- src/activity_handlers.cpp
Due to changes in #6146 to  `size_factor_in_time_to_cut()` dissection xp yield increased 100 times
Divide result by 100
Unspagett whole butchery code
> fix: too much dissection xp gain

- data/json/items/gun/8x40mm.json
Gives RM298 HMG 'MOUNTED_GUN' flag, making it require either power armor or be a big strong mutant to wield it, because:
It weighs 25 kilos with ammo
It is literally designated as 'heavy machine gun'
Added "MOUNTED_GUN" flag to it
Honestly, I didn't
1. Spawned as new char
2. Checked its description, tried to shoot it
> feat(balance): give RM298 HMG `MOUNTED_GUN` flag

- src/iuse.cpp
fix this warning
```
[217/327] Building CXX object src/CMakeFiles/cataclysm-bn-tiles-common.dir/iuse.cpp.o
/run/media/home/scarf/repo/cata/Cataclysm/src/iuse.cpp:5860:31: warning: object backing the pointer chq will be destroyed at the end of the full-expression [-Wdangling-assignment-gsl]
5860 |                         chq = string_format( "%d", quality ).data();
|                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
use indexing
> fix: iuse build warnings

- data/json/flags.json
- src/item.cpp
- src/iuse.cpp
To add, expand or better explain some of the json flags. Hand-loaded ammo flag just states that the ammo is hand-loaded, which gives an average user zero useful information (hand-loaded ammo has 1/256 chance to misfire independent of gun condition), exosuits increase speed/strength/carry capacity and some flags just could use better highlights. 
Edited a lot of "info" for flags
1. Loaded new world
2. Started checking new flag descriptions I added
<details>
<summary>Screenshots</summary>
</details>
Purposefully leaving something like DIMENSIONAL_ANCHOR out.
> feat(UI): clearer `"info"` field for some json flags

- .github/workflows/msvc-full-features-cmake.yml
fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6507
see: https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
merge when cataclysm windows build succeeds (seems to work)
> ci: fix vcpkg failure

- tests/monster_test.cpp
1. monster move tests are flaky because the random terrain generation affects test output
2. it clogs up PR files view with false-positives despite marked as `[!mayfail]`
hide it with https://github.com/catchorg/Catch2/blob/74fcff6e5b190fb833a231b7f7c1829e3c3ac54d/docs/command-line.md#specifying-which-tests-to-run
> test: hide flaky monster move tests

- doc/src/content/docs/en/mod/json/reference/items/item_creation.md
The grammar (in particular the use of commas) is bad and the claim that it's specifically mana used to cast spells is likely false.
Also, Scarf pulled a Chaosvolt and merged #6515 wayyy too hastily **while I was writing a review**. When Royal had clearly pinged me about the PR.
Apply what should have just been a suggestion on review in a new PR
Eyes
> docs: fix bad grammar and potential error in cast_spell documentation

- src/monattack.cpp
Improve user experience
I always debug cheat new items in because I notice 10 minutes later my weapon was pulled away by a technician, with this change it feels less cheap when the player loses items because atleast they are properly notified
Adds a popup when a monster successfully performs a magnetic pull special attack and the player or a follower loses their item as a result.
Debug teleported to a roof, spawned in a few magnetic items and a group of zombie technicians. After wielding my weapon the technicians would pull it and the popup displayed as expected
> feat(UI): popup for zombie technician's pull

- data/json/items/gunmod/brass_catcher.json
- src/avatar_functions.cpp
- src/item.cpp
- src/ranged.cpp
gunmods have been only accepting hardcoded `brass_catcher`. make mods be able to create custom brass catcher items.
make use of unused flag `BRASS_CATCHER`.
1. spawn brass catcher and rifle of your choice (mine m16a4)
2. fire some rounds, check casings are ejected
3. attach brass catcher
4. fire some more rounds
5. confirm it works as usual
found while reviewing https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6495
> feat: flagify `BRASS_CATCHER`

- data/json/debug_spells.json
- src/handle_action.cpp
- src/magic.cpp
- src/magic.h
As raised by Kheir and a few other members of the community, wholesale banning Brawlers from casting spells is perhaps a bit overkill.
While my initial stance was that those who opposed it and wanted to let spells through should code in the exceptions, I realized that this was a far better solution and one that I'd end up likely needing in some capacity in the future.
I'm somewhat surprised I didn't think of this initially.
- Adds a new spell flag, `"BRAWL"`
- Changes the check that prevents Brawlers from casting spells to instead also check for the spell flag, and let it through if it's detected
- Keeps a wholesale "You can't cast any of your spells because you're a brawler!" style of message around for the sake of it.
- Adds a debug spell for testing reasons
- Do it via an actual entry …
> feat: Allow for enabling specific spells to be cast by Brawlers

- doc/src/content/docs/en/mod/lua/reference/lua.md
- src/catalua_bindings.cpp
Patch for #6485 
Change entry color from variable to function.
Now it works as `UiListEntry:txt_color(Color)`.
Open lua console and input below.
```lua
local ui = UiList.new()
ui:title("Color Testing")
ui:text("What color?")
ui:add(-1, "red")
ui:add(-1, "blue")
ui:add(-1, "yellow")
local ents = ui.entries
ents[1]:txt_color(Color.c_red)
ents[2]:txt_color(Color.c_blue)
ents[3]:txt_color(Color.c_yellow)
gdebug.log_info("your select number is", ui:query())
```
> feat: allow choosing color of uilist entry in Lua

- src/map.cpp
closes #6453 
When doing that, bug occurs always like [this issue](https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6453).
The problem is that `map::reachable_flood_steps()` doesn't run properly at `range = 0`, so the game on the situation says "Hey, the ammo on there are consumed too much!"
I finally found what the problem is, but can't fix fundamental problem by lack of understanding codes. At least make the exception.
Quitting things about `use_furn_fake_item`
For testing, the mod with 2 things is needed.
1: Fake tool for furniture, running with ammo:
```json
[
{
"type": "TOOL",
"id": "furn_fake_tool_test",
"name": { "str": "Furn Testing" },
"copy-from": "fake_item",
"use_action": "MEDITATE",
"charges_per_use": 3,
"ammo": [ "tinder" ]
}
]
```
`MEDITATE` is good iuse_action for …
> fix: make furnitures able to accept items as charges

- data/json/items/armor/power_armor.json
- data/json/items/tool_armor.json
> feat(balance): make exosuits incompatible with power armors, make dimensional anchor power armor compatible

- data/json/construction.json
- data/json/furniture_and_terrain/terrain-traps.json
Floor is floor, currently some terrain calls for dirt pits or for flat dirt.
This causes problems if you want to do anything with regions. Now you can't dig wells nor can you construct a number of things like brick walls or concrete walls.
Pits and shallow pits are now flagged PIT_SHALLOW and PIT_DEEP. This could be useful to farm mods, but it's mostly necessary right now to say "A pit is a pit." for the sake of construction. Different soil types like a sandy pit aren't important here for the construction.
Constructions that call for t_dirt now call for FLAT. So now you don't need to dig up moss and fill it back in to build a brick wall, for example.
None, but we need to update digging result to also use terrain setting like deconstruct does. We also need a way for constructions to …
> feat: Update terrain flags to support different pits and ground types

- data/json/uncraft/tools.json
The copper frying pan required ten scrap copper to make, but returned 12 when uncrafting.
Reduced the uncraft of the copper frying pan from 12 to 10 to match its crafting recipe.
> fix: copper frying pan uncraft

- data/json/furniture_and_terrain/terrain-roofs.json
Tar paper roofs aren't considered a roof, you can't build wind turbines on them.
"A flat, gray section of rooftop covered with tar paper." The tar paper has no reason to make it too unstable. The reason is the flat roof: "A flat, gray section of rooftop." Some tar paper makes no difference on structural integrity when you're already drilling the turbine in.
Makes them flagged as a Roof
Violence
Tests
WTF
> fix: flat tar paper roofs are roofs

- data/json/overmap/multitile_city_buildings.json
Remove shoddy road connections and static road that are worse than useless for multiple locations.
In the file multitile_city_buildings.json delete the static road and road connection of the following `city_building`:
"urban_24_dense_bank_house", "urban_25_dense_diner_apt", "urban_27_dense_barber_apt", "urban_28_dense_cafe_laundry", "urban_29_dense_row"
none
I make my character appear in the game at the concerned locations via a scenario.
<details>
<summary>urban 24 (before):</summary>
<br>I made myself appear on the location via a scenario.
<br><a href="https://github.com"><img src="https://github.com/user-attachments/assets/5572a166-c310-47b7-8cd0-b553c7931b1e"></a>
</details>
<details>
<summary>urban 24 (After):</summary>
<br><a …
> feat: remove the road connection of multiple urban locations

- data/mods/ebook_lua/main.lua
- data/mods/ebook_lua/preload.lua
- data/mods/saveload_lua_test/main.lua
- data/mods/saveload_lua_test/preload.lua
- data/mods/smart_house_remotes/main.lua
- data/mods/smart_house_remotes/preload.lua
- data/mods/teleportation_mod/preload.lua
- data/raw/generate_docs.lua
- data/raw/generate_types.lua
- dprint.json
- tests/lua/called_from_cpp_test.lua
- save that vertical space!
- makes writing single-line lambda less painful than necessary
- set [`collapseSimpleStatement` as `Always`](https://github.com/RubixDev/dprint-plugin-stylua#configuration)
- apply changes
> style: collapse simple statements

- data/raw/generate_types.lua
- lua_annotations.lua
as shown in #6541 fields sorting weren't stable, causing unnecessary diffs
sort fields alphanumerically in following order:
- variables
- methods
- `serialize`
- `deserialize`
- [metamethods](https://www.lua.org/pil/13.html)
> chore: better lua field annotations sorting

- doc/src/content/docs/en/dev/explanation/design_document.md
We have too much bloat. We have too many people angry about removals. We can't have both without mainline mods.
Merge should be held off for a little while. Gives time for discussion.
Codify into our design document our official stance on bloat, removals, and mods.
In short: 
No removing stuff. Make it a mainline mod. 
Stop adding new guns to the main game, put those in a mainline mod.
Make someone else do it, or quitting.
> docs: Redo design document to prevent destruction of additions & prevent bloat

- data/json/overmap/multitile_city_buildings.json
Same as https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6539
In the file multitile_city_buildings.json delete the static road and road connection of the following `city_building`:
"urban_26_dense_club" and "urban_30_dense_subway"
none
I make my character appear in the game at the concerned locations via a scenario.
The buildings after these changes appear against the road in town, just like any other town building.
none
> feat: remove the road connection of two urban locations

- data/json/furniture_and_terrain/furniture-surfaces.json
typo was made.
typo was fixed
Well I did on my local copy when I fixed it for unrelated testing reasons to isolate a different bug.
none
> fix: fix typo in robotic workbench looks_like

- src/vehicle_use.cpp
In #6363 `Get items` button was accidentally removed from vehicle interaction, this one brings it back
* Compile;
* Start;
* Check button is in place and works.
> fix: return `Get items` button for vehicles

- data/mods/ebook_lua/main.lua
Fix bugs below:
- interrupting user to say degrading, even when it isn't (https://discordapp.com/channels/830879262763909202/830916451517857894/1373685002730082394)
- showing left turns of an e-book as `(xx.000000 turns)`
- sometimes an e-book is loaded as a real book
Edit main.lua
:(
Now the message doesn't interrupt you to say the e-book disappears which is reloaded already.
Loading a book spawns an e-book properly and `xx turns` instead `xx.000000 turns`.
> fix(mods): some bugs of e-reader mod

- .github/workflows/experimental-release.yml
- README.ko.md
- README.md
- make it more visible
- hard to see when the last experimental was released
show release timestamp more visibly
should work
> ci: timestamp and links for experimental releases

- data/json/game_balance.json
- src/magic.cpp
Mana regenerating fully (roughly) in 8 hours by default isn't always desirable, and is very clearly based on D&D. In particular, RoyalFox very much so would like this to be adjustable.
Adds three new external options:
- `MANA_REGEN_IS_FLAT`, which is a boolean for whether the rate should be a flat rate per hour or not by default
- `MANA_REGEN_HOURS_RATE`, the number of hours that your mana should (roughly*) take to regenerate if not a flat rate
- `MANA_REGEN_FLAT`, the integer amount of mana that the flat rate should be if enabled.
They default to False, 8, and 100 respectively.
- Just make the number of hours adjustable and not worry about the flat rate idea
- Also change the default number of hours
In my opinion, the default number of hours should be its own PR if we want it changed. …
> feat: Allow mana regen rates to be adjusted in JSON

- .github/workflows/android.yml
- CMakeLists.txt
- src/activity_item_handling.cpp
- src/cata_algo.h
- src/map_utils.cpp
- src/map_utils.h
- tests/algo_test.cpp
finally, after 2 years (#2402), we can use std::ranges to simplify auto consume logic.
adds:
- flat_map (haha monads go brrrrrrr)
- null-safe `max`, `max_by`, `min`, `min_by` that returns `std::optional<T>`
- convenience function to get all items on given position, including vehicles
- cry on for loops
- min/max functions use loops over ranges variant because while flat_map returns input_iterator, ranges variants requires forward_iterators.
1. created auto eat zone.
2. debug edited my character's hunger to 16000kcal (hungry).
3. kept it empty and waited for 5min.
4. no crashes.
5. spawned cheese pizza (1week to rot) and cornbread (1season to rot) on auto eat zone.
6. waited for 5min.
7. player ate pizza first then cornbread
maybe this could be merged as rebase-merge? idk
> refactor: use c++23 ranges on find_auto_consume

- data/json/requirements/cooking_components.json
Sake, despite being a fairly high-ABV wine, could not be used as one for crafting recipes.
Sake is now in the worthy_wines requirement group.
> fix: sake in worthy_wines requirement group

- data/json/recipes/chem/mutagen.json
- data/mods/Monster_Girls/recipes.json
Although many mutagens are craftable ingame, some of them are more tedious to craft than others, such as the bird mutagen which requires bird eggs, the lizard mutagen which requires reptile eggs, and the animal mutations which require large amounts of unmutated animal blood.
- resolves #6177 
Bird mutagen now can be crafted using feathers and down feathers, lizard mutagen can now be crafted using scute pieces, and animal mutagens which previously required 9 concentrated animal blood now only require 3. Furthermore, the equivalents of the first two mutation lines in the MonsterGirls mod have also been updated to match.
It's pretty basic changes, but overall balance is something to keep in mind, so I'm open for suggestions.
> feat(mods/MonsterGirls): Mutagen Recipe Improvements

- data/json/items/comestibles/med.json
Joints and blunts have the "smoke" effect, as in smoke inhalation, upon their use. This results in a coughing fit whenever consuming either of the two.
Neither joint nor blunt produce the "fd_weedsmoke" field upon their use. This is despite all the other smoked drugs producing their respective smoke fields upon use (marijuana included).
Remove "smoke" from effects and add "fd_weedsmoke" to fields
Continue choking on nonexistent smoke
Spawned in and consumed a joint with no coughing, and was weed smoke produced.
The same result occured with a blunt
Originally attempted to add "fd_cigsmoke" alongside "fd_weedsmoke" to the blunt, seeing as It is both tobacco and weed, however "fields_produced" will not accept more than one value.
> fix: stop choking on joints and blunts

- src/bionics.cpp
- src/character.cpp
- src/character.h
- src/character_turn.cpp
- src/crafting.cpp
- src/memorial_logger.cpp
- src/mutation.cpp
- src/savegame_json.cpp
- src/suffer.cpp
- src/wish.cpp
`Character::get_bionics` allocates a vector of the `bionic_id`s for each installed `bionic`. Most uses of the function are just looping over the contents of the vector and calculating something using it, not going on to make changes to the source `bionic_collection my_bionics`. Any allocation is slower than no allocation.
Create a function `Character::get_bionic_collection()` returning the dereferenced `bionic_collection`. Loop over this and use the `bionic_id` directly instead of allocating a vector of them using `Character::get_bionics` and very quickly throwing it away.
There are also a lot of raw accesses to `Character::my_bionics` so included is some minor, non-exhaustive, cleanup changing some uses of `*my_bionics` to `get_bionic_collection()`.
Move the looping logic into …
> perf: don't use Character::get_bionics most of the time

- src/magic.cpp
Some of these color choices, such as bash being magenta, made no real sense. This was noted in #6569 , but was determined to be better to sort out in a separate PR.
- Bash is now brown (if light_brown was an option, I'd have chosen it instead)
- Cold is now blue, as the world has conditioned us to associate it with
- Dark is now magenta, because that's a fairly common choice (especially given how black is absolutely not an option)
- Light is now white (Both because of the association with actual light, as well as the use of it for 'holy')
- Psi is now pink, a classic association for psychicness
- Electric is now light_cyan instead of light_blue because light_cyan really looks like electric blue
- True is now light gray (even though I think that what is currently called light gray really …
> chore: Use better colors for the damage types in spells

- data/mods/UDP_BN_FAKE_SNOW/mod_tileset.json
- gfx/MSX++UnDeadPeopleEdition/tile_config.json
Sets the overwrite in the mod to _season_winter
I fixed it on my local copy. It was pissing me off.
> fix: stop junk metal palisades from being snowy in summer

- data/json/items/tool_armor.json
Light amp goggles and infrared goggles currently have 20 eye encumbrance when turned on, and a whopping 40 when turned off. This is quite annoying, since you need extra keypresses to remove the goggles when you want to turn them off. Sometimes, like in partially lit labs, you need to toggle them quite frequently.
It's not immediately obvious WHY this is. While real-world night vision equipment does tend to limit your vision, you generally _cannot see through at all_ when it's turned off, which is why they have some way of lifting the goggles away from your eyes and out of the way when you're not using them.
Made the "off" variant both types of goggles cover the head instead of eyes. Reduced encumbrance to 5 and coverage to 10, since the head is quite a bit larger than the eyeball. Gave …
> feat: don't try to look through night vision goggles and infrared goggles when they're turned off

- data/mods/MagicalNights/Spells/animist.json
- data/mods/MagicalNights/Spells/classless.json
- data/mods/MagicalNights/Spells/monsterspells.json
- data/mods/MagicalNights/Spells/technomancer.json
- data/mods/MagicalNights/monsters/golems.json
- data/mods/MagicalNights/monsters/monsters.json
We have new damage types, so I should probably use them.
Makes a few light-related attack into light damage, usually replacing fire. Also makes a couple spells dark instead of bio
Granted some of the new immunity flags, particularly to the golems (no psi for them, and I missed them on the bioproofing)
- Also remove a bunch of true damage from the magus spells
Unsure of what I want to do with them at the moment
Loadtested, so the JSON is valid
I'll probably make more use of the damage types in the future, especially for any animist expansions.
> feat(mods/MagicalNights): Apply new damage types

- data/json/items/ammo/20x66mm.json
- data/json/items/ammo/40x46mm.json
- data/json/items/ammo/40x53mm.json
- data/json/items/ammo/shot.json
- data/json/items/ammo/shotcanister.json
Shotgun slugs, despite being functionally an FMJ round fired from a shotgun, have a positive armor multiplier due to my own relative newness at game balancing and how the code worked when I increased shotgun damage. Flechette shells similarly simply have a flat reduction and cancel out the armor multiplier.
Further reduced the armor multiplier of 12 gauge, 20x66mm, 40x53mm, and pneumatic shotcanister flechette and slug rounds, causing slugs to have zero armor multiplier and flechette shells to have a negative armor multiplier. Did not touch the black powder shells due to black powder inherently being weaker than smokeless gunpowder.
Made sure to test it so it works ingame, fixing any errors on my end.
> fix(balance): shotgun slugs & flechette rebalance

- data/json/items/ammo.json
I should not be able to cut up loose copper, it already is the base item.
Liberal application of NO_SALVAGE
NO!
Tests
Just got my internet back. Florida woes.
> fix: NO_SALVAGE applied to copper charges

- data/mods/MagicalNights/Spells/earthshaper.json
As Phoenix noted, the cast time was a little off for rock tomb. Looking over the stats for the meteor spell, I noticed that they also seemed just a touch off.
- Lowers the casting time of rock tomb by a bit under 50%
- Lowers the casting time and energy cost of meteor by a bit
- Adjusts rock tomb's description a little (it sounded like it should be dealing terrain damage before)
- Do it as part of the batch of re-balancing relating to shrinking the maximum levels later
Better to have this done before hand, keep that future PR simpler
Nothing new added, just some numbers tweaked to values that seem better and I know the game wouldn't freak out over.
The two kelvinist spells introduced with rock tomb may need a check-over and potential nerf to their casting time and energy as well, but …
> feat(mods/MagicalNights, balance): Lower rock tomb and meteor casting time

- src/salvage.cpp
- src/salvage.h
On rare occasions when item consists of different materials that salvage into the same resulting item, this said item reported twice, which may appear as a bug and possibly is annoying.
Check if `salvage_results` already contain the item and increment it, instead of adding new entry.
- Compile;
- Start;
- Check old things salvaged properly;
- Check reported case works properly. Heavy duty frame is a good example, since it's made of steel and hardsteel, both are salvaged into `steel`.
Appropriate looking result:
> fix(UI): salvage seemingly double report resulting items

- data/mods/MagicalNights/items/enchanted/enchanted.json
125% extra mana capacity on the lesser staff was particularly crazy
changes the progression to be more sane, going from 25% bonus to 50% bonus to 125% bonus at the greater level.
- Implode the staves
- Give mana regen bonus (Possibly in exchange for some cap bonus)
Number tweak
Phoenix with the good balance notes as usual.
My bad for not looking over the questionably high bonuses when I originally accepted the PR that added them (when MN was out-of-repo)
> feat(balance, mods/MagicalNights): Nerf mana cap bonuses from magi staves

- data/json/effects.json
- data/json/game_balance.json
- tests/char_healing_test.cpp
We heal too fast. We heal too slowly without any mending at all. I absolutely smashed the healing rate a few weeks ago in my work, and after playing with it, it's all but required for base game balance.
Heal rate is always going to be insane at high first aid, so we're testing the early game here, this will disproportionately hit you at 3 first aid or lower, while at 6 it will barely be noticeable.
Reduces the healing_torso from 150 to 75 on bandaged and disinfected, along with the healing_rate scaling from 2 to 1, and the base_mod healing_rate to 1. Healing_head untouched because its already super slow.
According to the C++, you can expect an 8.6 HP per day heal rate with no mending at the base player healing rate per turn. of 0.0001
Far greater nerfs. I am in camp "realismic" with heal …
> feat(balance): Thermonuclear nerf to mended heal rate, double natural heal rate

- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/magic.cpp
- src/magic.h
- src/magic_spell_effect.cpp
As Chaos pointed out in my PR to document the noise spell effect, spells were duplicating the noise they made. This seems rather silly to do by default, but some spells may want to do it intentionally.
- Adds a check to the playing of sound to make sure it doesn't play more than once by default
- Add a spell flag to let it play multiple times
- Short-circuit the OR to make Oren happy
- Update docs
- Make the spells play the sound once, period
- Not apply the change to summoning monsters since it makes decent sense to play multiple sounds there, and it's already under a few if statements.
Compile-tested (of course)
Acid-bombed some flesh walls before and after the change. Before it gave me 45x hearing an explosion, after it gives me 1. 
Now the derg can in-theory remove the workaround on …
> feat: prevent duplicated noise from spells by default

- tests/char_healing_test.cpp
Fix issues in test `"healing_rate_medicine with bandages and/or disinfectant"` in `tests/char_healing_test.cpp` introduced in #6663. 
fixes #6668
1. Changes return type of `bandaged_rate`, `disinfected_rate`, and `together_rate` to `double` so that if they do fail again we get a more informative failure message. Previous failure message was along the lines of:
`0.00001f == Approx( 0.0000099537 )` which is unhelpful when the actual value was `0.000005787`, a large difference from the displayed `0.00001f`.
2. Largely removed monolithic magic numbers. Base healing rate when bandaged ^ disinfected is 1 while awake and 2 while asleep, and 4 and 8 respectively when bandaged & disinfected.
3. Bodypart healing rates differ slightly, with Head healing at half the rate of limbs and Torso healing at …
> test: Fix issues in bandaged/disinfected healing test

- data/json/furniture_and_terrain/terrain-floors-indoor.json
Junk metal floor was previously represented by a horizontal line, an unfortunate choice since the same symbol is used for walls. Junk metal floors are fairly rare in worldgen structures, but it's quite easy to build yourself.
Symbol is now "`". This is also used for cardboard and paper (as items on the ground), but I doubt that will cause any serious confusion, and it feels appropriately junky.
"." and "," are the obvious choices for floor, but I wanted it to be distinct. The horizontal line was that, even if it was hard on the eyes.
Looked at tile in game
Before - I don't think the person who picked this played with ASCII:
After - Note clear distinction between open space and solid wall:
> fix: change junk metal floor symbol to "`"

- src/activity_handlers.cpp
- src/activity_item_handling.cpp
- src/pickup.cpp
fixes #6653
- Remove `getlocal()` from distance calculations, since `position()` already returns local coords and `getlocal()` creates some insane coordinates;
- Safeguard in crafting code, so delta does not go negative due to negative player `moves`;
- Protection from int_64 overflow due to `trait_DEBUG_STORAGE` in `cost_to_move_item()`.
- Compile;
- Start;
- Perform activities mentioned in issue;
> fix: negative crafting progress from eating

- data/json/items/comestibles/carnivore.json
Due to copy-from shenanigans, tainted blood spoils super-fast whereas all other blood items last forever. Can make things annoying when trying to make mutagenic stuff (and Arcana stuff).
Added `spoils_in` of zero to tainted blood, which as a consequence also affects concentrated tainted blood.
Doing the inverse and making regular blood spoil, possibly just setting zero spoilage for concentrated blood explicitly if so.
Ported and load-tested change to playthrough build.
> fix: tainted blood doesn't spoil

- data/json/furniture_and_terrain/furniture-recreation.json
Fuckery abounds with furniture and copy-from code once more.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6691
Set downed steel targets to explicitly turn into `f_null` when bashed, because for some reason it inheriting from propped-up targets causes it to still inherit the old `furn_set` value even though it provides a new `bash` entry.
1. Figuring out why the code is being stupid about this and fix that, which I currently can't do unless I can figure out how to make VS2022 work on my laptop.
2. Converting downed targets into standalone furniture that doesn't inherit from anything. Given the differences in coverage, move cost modifier, and how inheritance doesn't correctly copy over `color` and `symbol` the line count would probably be similar either way.
Ported file …
> fix: override `furn_set` for downed steel targets

- data/json/items/ammo.json
- data/json/items/chemicals_and_resources.json
- data/json/items/comestibles/carnivore.json
- data/json/items/comestibles/drink_other.json
- data/json/items/comestibles/other.json
- data/json/items/fuel.json
- data/json/items/generic.json
- data/json/items/resources/home_improvement.json
- data/json/recipes/other/materials.json
- data/json/recipes/other/other.json
- data/json/recipes/other/tools.json
- data/json/recipes/other/vehicles.json
- data/json/recipes/weapon/bashing.json
- data/json/recipes/weapon/cutting.json
- data/json/recipes/weapon/mods.json
- data/json/recipes/weapon/piercing.json
- data/json/recipes/weapon/ranged.json
- data/json/requirements/materials.json
Varnish and sanding were applied far too liberally when I first designed them, and the later PR to try and prevent them from being salvaged broke engine salvaging; this PR reverts most of the changes caused by the latter, removes sanding and varnish from almost everything but specifically wooden non-reversable items, and changes descriptions to not mention varnish.
Varnish was applied far too much for items that barely had any wood to them, and my attempts to correct the varnish being gotten back from uncrafting wooden items broke engine salvaging.
Varnish as an ingredient has been removed from all items that are not purely wooden and that can be uncrafted, and sanding as a tool quality has similarly been removed from most recipes. Varnish has been removed from the description of multiple …
> fix(balance): varnish changes, undo #6589

- data/json/recipes/other/tools.json
We had no valid crafting recipe for the normal crucible recipe, and we may want to differentiate between the poor-quality clay crucible and a good quality crucible in the future.
Historically, the Hessians made crucibles with very high temperature maximums that were popular for alchemy and the like through the use of mullite. Mullite is obtained by firing kaolinite clay at very high temperatures.
- Adds a recipe based on the re-discovered hessian method.
- Graphite crucible
- Advanced ceramics crucible
- Leave it loot-only
- Use aluminum powder as well to cover all the bases
Load-tested.
[Wikipedia Article](https://en.wikipedia.org/wiki/Hessian_crucible)
[Actual paper abstract](https://ceramics.onlinelibrary.wiley.com/doi/10.1111/j.1551-2916.2008.02383.x)
I like doing these things the …
> feat: Add a historical recipe for the `crucible` item

- data/mods/MagicalNights/items/enchanted/enchanted_boots.json
Description mentions steel, instead contained plastics because hiking boots are plastic (and have been for 9 years)
Instead of changing the hiking boots to be steel, change the enchanted boots to override material because that's less intrusive
- Make hiking boots steel instead of plastic
I would love to, and if that solution is preferred for vanilla BN too then I'll gladly do that instead.
However, I thought maybe it was that way to increase distinction from steel-toed boots.
ctrl-c ctrl-v, looked over my changes
I have no idea why whoever made the boots in Magiclysm thought they were made out of steel.
Not giving steel to the boots of grounding for thematic effect and because steel is a conductor.
> fix(mods/MagicalNights): Manually specify enchanted boot materials as leather and steel

- src/catalua_bindings_creature.cpp
- src/character.cpp
- src/character.h
- tests/health_test.cpp
Healthy tests `tests/health_test.cpp` are not reflective of actual health normalization. This is because they simulate a diet eating once a day, and updating health once a day. This is malformed in multiple ways.
1. The test is supposed to simulate up to 4 meals a day, but actually does a single meal per day
2. Simulates a single health update instead of the actual update rate of once per 30 minutes (48 times per day).
Because of both issues the values used as multipliers to dampen `healthy` value toward `healthy_mod` is far too aggressive, moving it by 10% per call, and slightly too aggressive when dampening `healthy_mod` towards zero (0).
@RoyalFox2140 brought this to my attention as a long standing thorn in the side as being far too fast to move around. 
A number floated was that it …
> fix: fix healthy tests, additionally slow down health normalization

- data/json/items/tool/science.json
fills butane tanks found in labs and other industrial locations, as someone seems to have went around and used it all
add initial_charges
spawned a tank, it was full
> fix: fill butane tanks

- data/mods/MagicalNights/items/enchanted/enchanted_misc.json
- data/mods/MagicalNights/items/tools.json
It was brought to my attention that the tailors kits weren't letting you pad with superalloy in MN. Oops.
I also moved the nomex padding option just to align the ordering with vanilla and so it's obvious to anyone in the future if MN is missing one properly.
- Add the alloy_padded option back
- move nomex_padded
- Just add alloy_padded
- Do nothing
- Look into how a previous PR might allow me to extend use_actions
I probably should, but I also get the feeling this wouldn't be what it actually enabled.
Lints
ctrl-c ctrl-v hopefully doesn't let me down
It is pretty annoying that registering new repairable materials and the like seems to necessitate overriding the use_action.
> fix(mods/MagicalNights): Fix missing `alloy_padded` option for tailor's kits

- data/mods/TEST_DATA/magic.json
- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/magic.cpp
- src/magic.h
- src/magic_spell_effect.cpp
- src/ranged.cpp
- tests/magic_spell_test.cpp
Step 1 towards Weapon Artes, physical spells, and potentially stuff like martial arts using spells to represent techniques that the user can activate at their leisure.
Additionally, the work required for this will make subsequent future additions of more possible modifiers much easier because the structure will already be in place.
- Adds a new function, `damage_as_character`, which takes a character parameter and returns the base damage + any special modifiers.
- Makes `damage_string` take a character parameter because the only current uses I can find are ones where the player is casting anyway
- Adds and makes use of the damage_instance helping functions for character-based damage
- Adds a spell flag to allow the highest melee weapon damage to be added to the spell's damage (i.e. …
> feat: Allow for spell damage to be augmented by melee weapon damage

- data/json/mapgen/house/urban_4_house_basement.json
- data/json/mapgen/nested/basement_nested.json
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6680 has made the wheels placed in one of the nested mapgen in urban_4_house_basement too close to the walls and door in the basement.
Since this bothers me, I want this to change.
Add `11x11_gym_open_1` to basement_nested.json, a variant of the nested mapgen `11x11_gym_open`
Replace `11x11_gym_open` with `11x11_gym_open_1` in the basement of urban_4_house_basement
none
No errors when I started a new game.
<details>
<summary>Screenshot (Before):</summary>
<br><a href="https://github.com"><img src="https://github.com/user-attachments/assets/dd43fd4c-7e2a-4be8-aabe-4529bd2804aa"></a>
</details>
<details>
<summary>Screenshot (After):</summary>
<br><a href="https://github.com"><img …
> feat: replace `11x11_gym_open` with another nested mapgen in the basement of urban_4_house_basement

- data/json/mutations/mutations.json
The only way for a player to have tentacles and claw-like equivelents was supposed to be by going post-threshold cephalopod and mutating tentacle rakes (CLAWS_TENTACLE). However, it is currently possible for a player to have retractable claws before mutating tentacle arms, thus smuggling in the claws.
Add retractable claws to the "cancels" list of tentacle arms
Continue allowing players with tentacle arms to also have retractable claws protruding from fingers they don't have.
Spawned in, 
injected feline serum until retractable claws,
injected cephalopod serum until tentacle arms,
was no longer able to keep retractable claws after mutating tentacle arms.
The entire ARM_TENTACLES entry was replaced because the linting machine told me to.
But then the other machine told me to put it back.
> fix: remove retractable claws + arm tentacles exploit

- data/json/construction.json
- data/json/gates.json
Allows the mechanical winch "t_gates_mech_control" to work with more different walls.
Make the mechanical winch work with these walls:
[pink wall](https://cbn-guide.mythoscraft.org/terrain/t_wall_P)
[adobe wall](https://cbn-guide.mythoscraft.org/terrain/t_adobe_brick_wall)
[simple concrete wall](https://cbn-guide.mythoscraft.org/terrain/t_sconc_wall)
[stone wall](https://cbn-guide.mythoscraft.org/terrain/t_rock_wall)
Updated the description of the mechanical winch construction to specify which wall is compatible.
none
No errors when I started a new game.
<details>
<summary>Screenshot (Before):</summary>
<br><a href="https://github.com"><img src="https://github.com/user-attachments/assets/046b1db3-eed8-48d4-b574-5e0ff819abc1"></a>
</details>
<details>
<summary>Screenshot (After):</summary> …
> feat: allows the mechanical winch to work with more different walls

- .gitignore
- Makefile
- README.md
Players keep making the (understandable) mistake of placing their 3rd-party mods into `data/mods`. It is fairly desirable to attempt to help them out with this, especially given that it's such a simple change.
Similarly, it is not clear to a new user where to put their soundpacks.
- Adds `mods` and `sound` to the root of the repo with an empty text file in each to explain their purpose with its name.
- Adds them into the `bindist` in the makefile if neither XDG nor Home directories are being used.
- Updates the readme
- create the folders in the makefile instead of having them sit around in the repo
Also valid, but I think this is clearer.
I looked over the makefile to try and make sure my syntax is correct and that I'm adding it to the tars/zips the correct way.
In theory I could test …
> chore: Add default folders to the repo for player mods and soundpacks

- data/json/monsterdrops/zombie_default.json
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6422 made dab pens ABSURDLY common on monster drops. Most of the weights for smoker items on the associated distribution have a weight of 10, and dab pens were given a nonsensical weight of **50**, when most of the items on the list except the expected basic cigs have a weight of 10. Dab pens were added twice in fact, one with no other items at a weight of 10, and one at the giant 50 weight as a collection with THC liquid.
1. Toned down the collection of dab pen+THC liquid's weight from 50 to 10.
2. Removed the redundant extra spawn of just an unusable dab pen by itself.
The amount of THC liquid could be made variable, but on the other hand the regular vapes already come with a 100% spawn of nicotine liquid at a fixed amount so eh.
Used …
> feat(balance): reduce weight of dab pens from monsterdrops to same range as most other items on the list, remove redundant spawn

- data/json/items/furniture.json
- data/json/items/vehicle/utilities.json
Disassembling a 75L plutonium generator will produce a 100L minireactor.
This is physically impossible unless it was **really** packed in there good and only decompressed after it was removed from the generator, like a new mattress.
swap the volume of the two
Brainstorm on new volumes, so long as the minireactor is smaller than the generator.
Custom-built reactors that are even bigger.
Spawned in
The "small portable plutonium reactor" is now more portable.
The "compact nuclear reactor" is now less portable
I wanted to make a joke about Chernobyl and nesting dolls, but I couldn't get it to fit.
> fix: swap volume of minireactor and generator

- data/json/emit.json
- data/json/field_type.json
- data/json/items/generic.json
This fix resolves https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6725. EDIT: In my testing, blunts do give the weed effect. HOWEVER after publishing the PR I noticed the issue (hardcoded in item::process_litcig and item::process_extinguish), which is a C++ change. I plan on tackling that as soon as possible, and either adding the changes to this PR, or just splitting it into a separate C++ PR as I need to fix blunt_roaches as well.
(don't know if the above satisfies auto-close, so resolves #6725 )
Add fd_bluntsmoke and emit_blunt_trail. Change the blunt item to produce this new smoke variant instead of the normal tobacco smoke. (Which was chosen because we can only have one emit_field effect, but this should solve the confusion.)
Smoked a blunt. Got high. It made smoke.
(the time …
> fix: make blunts produce blunt smoke

- data/raw/keybindings/keybindings.json
F11 is almost universally recognized as the "fullscreen button" across most applications.
Currently the debug menu is bound to F11, making it useless for just about anyone who hasn't bound it to a different key.
Why have a default keybind that >90% of players must change anyway?
Changing the default keybind from F11 to F12
Binding it to any other key that doesn't already do something for almost everyone.
Spawned in
I can now open the debug menu without putting my game in windowed mode.
Many versions back, debug menu was bound to F12 by default, but at some point it was left unbound by default.
Later in #4503, Debug menu was bound to F11.
This is a very small thing, but it seems silly to have a keybind that nobody can use by default (unless they shift +F11 every single time without fail).
> fix: keybind debug menu to F12 by default

- data/json/furniture_and_terrain/terrain-liquids.json
Allows the player to dive underwater in rivers, resolves https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6678.
Adds the relevant GOES_UP and GOES_DOWN flags to the proper terrain.
Swam in the river. Went underwater, and it worked.
> fix: diving in rivers

- data/json/furniture_and_terrain/terrain-floors-indoor.json
resolves https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6497
update utility light ter_set to `t_concrete` from `t_floor` (which is wood)
broke a light, got a concrete floor
> fix: update utility light ter_set to `t_concrete`

- data/mods/Civilians/civilians.json
- data/mods/Civilians/monstergroup.json
Increase civilian spawns & add make civilians less trigger happy.
Doubles the monstergroup's spawns, and add `"aggro_character": false` to the base civilian.
Before this change, overconfident officers would shoot on sight in a field. After, they no longer attack the player without first being provoked and agitated by another enemy.
I doubled the spawn rate because they were almost nonexistent before. Considering these enemies stop spawning on day 3 anyways, I figured the new amount is reasonable.
> fix: double spawns, friendlier civilians

- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
It was an average Wednesday, which meant I got mad that another spell code field went undocumented. I documented sprite
Writes the actual documentation
I make YOU, the reader, do it.
No
https://youtu.be/lcBUNSbMW3k?t=4509
> docs: document sprite selection on spells

- data/json/furniture_and_terrain/furniture-tools.json
Found typo in flags for `f_butcher_rack`
`"FLAMABLE_ASH" -> "FLAMMABLE_ASH"`
No testing, `"FLAMABLE_ASH"` isn't referenced anywhere within the game while `"FLAMMABLE_ASH"` is so it should properly apply the relevant effect now.
> fix: typo FLAMABLE_ASH -> FLAMMABLE_ASH

- src/character.cpp
This tones down "your heart races as you recall your latest hunt" message spam while asleep, where sudden stim boosts are a tad out of place.
In character.cpp, set `Character::do_skill_rust` so that the bonus message and stim boost that predator characters get don't trigger if the character is asleep.
1. Still letting you keep the stim boost and just skipping the message spam. I figured it might be good to not grant stim boosts while asleep since if it triggers too often I dunno what that'll do to a sleep in progress.
2. Reflavoring the message to check if you're sleeping and post a more dream-flavored message if asleep.
3. Being mean and not letting predator characters skip skill rust for combat skills if they're asleep.
Used my eyes, still can't get laptop to work with VS2022 and still …
> feat(UI): don't trigger "recent hunt" event while asleep

- src/creature.cpp
RoyalFox discovered a nasty bug with one of her effects that was meant to remove some of her effects that happen to have add_on_remove defined which caused the game to spit out a debug message per removed effect EVERY TURN AFTER THEY GOT REMOVED.
As it turns out, the game tried to remove effects that weren't even present on the player because it just assumed all the effects that are removed by another effect should be removed.
Made it so that the handling for effects that remove other effects only adds to the removal queue if the effect that should be removed is actually present.
Also adjusted the debug message slightly to better indicate that it is now instead indicating that an effect that was found earlier was not found for that function.
- Remove debug message entirely because the …
> fix: Fix trying to remove effects that aren't present in `Creature::process_effects()`

- doc/src/content/docs/en/mod/json/reference/creatures/magic.md
- src/magic.cpp
- src/magic.h
Another addition in my quest to allow for everything needed to make fully physical techniques in the spell system, as well as enabling more cool features with spells in general.
This allows a spell to scale based off your Strength, Perception, Dexterity, and/or Intelligence. Damage goes up 10% for every point over 8 in every relevant stat you have, and down 10% for every point under 8 you have. Casting time and cost goes down 10% for every point over 8, and up for every point under 8 (with a cap on the high end to prevent values going negative).
Also causes failure rates to correctly use the scaling stats. Note, however, that to preserve consistency I made it so that not setting any stats means that stats contribute 0 to your spell failure rate. (For the prior mentioned areas of scaling, …
> feat: Allow spells to scale based on caster's stats

- data/json/items/tool_armor.json
Fun is illegal, as you are all aware. That's why the code forcibly sets an item to an active geiger counter if it's used to scan for radiation and has the item use. Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6778
Takes off geiger usage.
Letting it fester until someone fixes the iuse because I don't know how. But we don't maintain noob traps.
No need in this case. It's either THIS, or THIS doing it. 
```cpp
// Otherwise, we're activating the geiger counter
if( it->typeId() == itype_geiger_on ) {
add_msg( _( "The geiger counter's SCANNING LED turns off." ) );
it->convert( itype_geiger_off );
it->deactivate();
return 0;
}
```
```cpp
case 2:
p->add_msg_if_player( _( "The geiger counter's scan LED turns on." ) );
it->convert( itype_geiger_on );
it->activate();
break;
```
> fix: stop cancelling fun by turning scouters into active geiger counters

- src/mondeath.cpp
It's rare enough to meet a Jabberwock as it is, and there is no real reason for vorpalization to require a weapon to be CVD'd.
Vorpalization does not make sense for weapons that do not have much cutting damage due to how the technique works, and in general does not make sense for weapons whose primary focus is cutting.
500 mL seems to be a nicer cutoff, that way knives can (in theory at least) also become vorpalized (without leading to too much shenanigans with unfitting items being vorpalized)
- Remove CVD requirement for a weapon to be vorpalized
- Add a requirement that cut damage must be at least 1.5x larger than bash damage on the weapon
- Lower volume requirement to 500 mL instead of 750 mL
- Put a raw cutting damage requirement instead of a requirement that it be over bash by a …
> feat(balance): change vorpalization requirements

- src/game.cpp
- src/iexamine.cpp
- src/options.cpp
Allows the player to set auto-forage category to specifically forage for flowers, similarly to how we can forage bushes and trees specifically.
New option in settings & small switch statement changes.
Compiled, walked through a field and auto-foraged some flowers. Confirmed it works.
> feat: add flowers category to auto-forage

- .astylerc
Some options used in `.astylerc` have been deprecated for ~10 years!
Update the options used.
None
Check if the `astyle` step throws errors.
> ci: fix deprecated astyle options

- doc/src/content/docs/en/mod/json/reference/json_info.md
- src/item.cpp
- src/item.h
- src/item_category.cpp
- src/item_category.h
- src/item_group.h
- src/map.cpp
- src/map.h
- src/mapgen.cpp
- src/options.cpp
Ports a few DDA PR's:
https://github.com/CleverRaven/Cataclysm-DDA/pull/37346/
https://github.com/CleverRaven/Cataclysm-DDA/pull/37407/
https://github.com/CleverRaven/Cataclysm-DDA/pull/62583/
https://github.com/CleverRaven/Cataclysm-DDA/pull/64586/
Documents `Item Category` ripped directly from these DDA PR's. As far as I can tell, it is accurate to our own but probably does need checked over.
Separates item spawnrates into categories and displays them in the World Settings using our own categories instead of DDA categories. (of course)
Giving up because of pointers
Set books to 0.0, teleported to a bookstore or library, confirmed no books spawned. Set books to 20.0 and confirmed that a large amount spawned, however I have not done any calculations or verification that this is exactly …
> feat(port): per category spawnrate control in world options

- data/json/items/comestibles/drink_other.json
- data/json/items/comestibles/sandwich.json
1. After noticing that carnivores were able to eat peanut butter, I quickly realized that peanut butter and peanut butter sandwiches did not have `nut` in their materials.
2. Imitation peanut butter was misspelled as "imitation peanutbutter".
1. Add `nut` to their materials 
2. Add space between "peanut" and "butter".
Adding futher more nut containing foods to justify creating a nut allergy mutation that can be picked as a starting trait.
spawned in
peanut butter, imitation peanut butter, and peanut butter products are now made of nut
carnivores can no longer eat peanut butter
It's odd that there hasn't already been a nut allergy trait, given how prominant of a food source nuts are in the Fall, and how common the allergy is in real life.
> fix: peanut butter is made of nut

- data/json/overmap/overmap_special/aircraft_carrier.json
- data/json/overmap/overmap_special/specials.json
Ref Center lags when you try going into it, and the aircraft carrier almost crashed my PC. We found out it was the grid doing it after profiling it with tracy.
Just delete the electric grid flag from places that have way too big of grids until a better fix happens.
!!! THIS SHOULD PROBABLY BE REVERTED AFTER A FIX !!!
None due to severity of this problem.
No lag
https://www.youtube.com/watch?v=6KezlDabqfY
> fix: temporarily remove massive electric grids from locations

- data/json/monsters/zed-animal.json
They're zombies, they shouldn't have that kind of fear.
Remove the "fear_triggers" "FIRE" from the following monsters:
grim howler
zombear
festering boar
zombeaver
antlered horror
decayed pouncer
none
none
> feat(balance): remove fear of fire from multiple zombie animals

- data/mods/lethal_zeds/monster_overwrites.json
I made a fake rock gun from what I learned with fake rifles, rather than wholesale copy feral rocks. This means I didn't realize I had to use NO_PENETRATE_OBSTACLES and it wasn't caught in reviewing.
Adds NO_PENETRATE_OBSTACLES as an ammo effect. Reopened from https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6800 because of weird makefile changes when I merged changes.
Magical Night wizard ferals that teleport rocks through walls.
Ferals already use this flag.
> fix(mods/lethal_zeds): Stop rock guns from bypassing terrain

- data/json/items/armor/sheath.json
Halberd is the only weapon of spears and 2h axes category that doesn't fit into spear strap, while there doesn't seem to be any issues doing so irl https://artisansdazure.com/cdn/shop/products/polearm-holder-scabbards-les-artisans-dazure-939943_1800x1800.jpg?v=1682735742
Increase spear strap volume limit from 3.5L to 4L
Tested as a mod
> feat(balance): store halberd in spear strap

- data/json/mapgen/nested/shelter_nested.json
I decided to always let it spawn a working console while also making sure it actually always generates with a use prompt
Nah
> fix: vandalized shelter always has working computer

- .github/workflows/experimental-release.yml
#6811 missed a spot
Kill 32 bit experimental builds too
Leave them be, for it to be truly experimental / for us to know when exactly we break 32 bit support by accident
Reading
In my defense, the experimental build isn't the most prominent
> build: Kill 32 bit experimental builds

- src/item.cpp
- src/map.cpp
- src/map.h
- src/mapgen.cpp
- src/options.cpp
In my initial PR I missed the new `SOIL` category, left in an unusued function, and I also broke spawnrate scaling. This fixes those issues. Additionally, it improves the perishables/canned logic and fixes another change I made that may have affected canning rotten food.
Revert a few changes and ensure the code quality is better now.
Spawned at the bottom of a mine, and ensured the issue related to the missing category no longer shows. Canned perishables and perishables seem to spawn less/more if you turn their rates up or down, but for whatever reason can't be completely disabled. This may be related to SUS_fridge type categories being placed differently or related to the bug mentioned by Pyrocyonae in the last PR's discussion, I am unsure.
I still haven't quite cracked the issue with …
> fix: adds "SOIL" spawn rate category, fix total spawnrate scaling

- data/json/game_balance.json
- data/mods/StatsThroughSkills/modinfo.json
- data/mods/stats_through_kills/modinfo.json
- src/magic.cpp
Stats Through Kills and Stats Through Skills can make mages a little too strong too easily.
I decided it'd be better to do as an external option rather than hardcoding in that the stats-through-X mods cause the rate to be halved.
Adds `MAGIC_STAT_SCALING_PERCENT` as an external option, defaulted to 10 but set to 5 in STK and STS. 
- Make the option directly a float
I felt that this method (integer converted to float) is more clear, especially regarding precision.
It compiles, the math checks out, and this change is very simple conceptually
Admittedly balance should not necessarily be assumed with STK / STS in the first place, but I still think it's a good idea so that other mods can adjust the values in theory too.
> feat(balance): Make stat scaling percentages for magic an external option

- data/json/furniture_and_terrain/terrain-floors-indoor.json
Radiation platform's description is made up of broken english.
copy DDA's description
Continue giving Godzilla a stroke
1. Spawned in
2. Looked at radiation platform
3. Its description now reads smoothly
I couldn't find the original DDA PR wherein this new description was introduced, otherwise I would have linked it.
> fix: typos in radiation platform desc.

- data/mods/Monster_Girls/thresh_mutation.json
Flight got merged, so harpies can fly now.
Update description to reference their ability to fly and make a new joke.
- Deliberately remove flight for them for some reason
I read
I also realized bunnygirls currently do not appear to have dreams set. I must check to see if vanilla bunny mutants have any to cannibalize.
> feat(mods/MonsterGirls): Update Harpy Description due to gaining flight

- data/mods/Monster_Girls/dreams.json
Bunnygirls had no dreams.
Give bunnygirls dreams
- Wait for Vanilla / donate some to Vanilla
I read, and this was a simple copy-paste then swap text from how Kitsune are formatted.
I tried to not lean *too* much into the adult side of jokes about bunnies / bunnygirls. (At least not yet)
> feat(mods/MonsterGirls): Add bunnygirl dreams

- src/game.cpp
fixes #6833
Allows players to climb when they could not before due to changes made during the flight PR 
Re-add a climbing check that was removed for some incomprehensible reason during the flight PR.
- Make shmakota do it as penance
I loaded into the game, and could once again climb up downspouts and trees.
Also, I tested it with flight enabled: Flight takes priority over climbing anyway.
The fact it was so simple is both infuriating as well as joy-inducing
> fix: Allow players to climb again

- data/json/construction.json
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6840
Added a `delete` entry to the `copy-from`'d second stage of constructing a log wall, removing the demand for a shallow pit from the second stage.
Not using `copy-from`.
2. Ported JSON change to laptop playthrough.
3. Checked construction for log walls, second stage no longer asks for the `PIT_SHALLOW` flag.
4. Also checked visually that `copy-from` didn't fail to inherit any important info from the first stage.
> fix: fix paradox in log wall construction

- data/json/furniture_and_terrain/terrain-doors.json
- data/json/furniture_and_terrain/terrain-fences-gates.json
Locked wire gates and locked bar doors (the ones for jail cells) are not pry-able.
Add pry
Add pry but with different values than the one's I've suggested. I only assume that the values I applied were reasonable after comparing them to the values other doors use being pried.
Spawned in
Bar doors and wire gates can now be pried, in addition to the other things.
I wanted to add the "byproducts" field to the locked wire gate (as in the lock braking and turning into 3 scrap, like how the boltcutter does), but the "pry" attribute does not accept "byproducts."
While I was in the neighborhood I noticed that open metal garage doors were burrowable. Not only are they almost always placed on concrete (or otherwise hard) floors, but they're already open.
> fix: make locked wire gates and bar doors pry-able

- data/mods/MagicalNights/worldgen/wizard-towers.json
Fridge goods should not be spawning in the furnace
Fix the items entry from `"f"` to `"F"`, thus putting them in the fridge instead of the furnace
None
I made sure that `"F"` was the correct letter for Fridges.
Gotta love finding small issues during normal gameplay
> fix(mods/MagicalNights): Fix fridge goods spawning in wizard tower furnaces

- src/start_location.cpp
This scenario gives a good amount of points, and it would be rather anticlimactic if you could just somehow come out of the wreck completely unscathed.
Continue to loop over body parts until at least one hits the damage condition
None
Loaded into scenario ~4-6 times, and made sure I had gotten damaged each time.
Testing took longer than coding the change
> fix(balance): Make sure at least 1 body part is damaged from helicopter crash scenario

- src/descriptions.cpp
So, I found this little gem on examining terrain with `;` while debug mode was on:
I decided with some cleaning up, knowing how much cover terrain provides might be useful outside of debug.
In descriptions.cpp, tweaked `map_data_common_t::extended_description` so that ranged bash info isn't debug-only, and greatly cleaned up how it displays. Shows the damage reduction as either a single number or a range depending on if it varies, and shows block chance as an actual percentage instead of a `_pm` probability unit. Lastly, it also shows destroy threshold when debug mode is turned on, as for now I left "how high a roll to destroy" as debug info since that was the only other bash-related property left hidden in the UI. Gave it some newlines here and there to not be a giant mess as well.
1. …
> feat(UI): show terrain/furniture value as cover in "look around" menu

- data/json/items/generic.json
- data/json/uncraft/generic.json
Anti-materiel turret and grenade launcher turret would call for a broken_turret_antimateriel or a broken_turret_mark19, but neither of those items exist, nor is there an option to uncraft them
Add broken turret items and associated uncraft results for the above mentioned turrets.
Spawned in turrets
killed them, broken turrets produced
disassembled them, appropriate componants produced
Why are they so disproportionatly heavy?
> fix: new turrents have corresponding broken item

- src/pickup.cpp
Wearing is now the first option in the UI
closes #5425
changes the order of wearing to be the first option in the menu if you don't have enough space in your inventory for an item
doesn't need testing as no code was added
> feat(UI): make `Wear` the first option in the menu

- data/json/materials.json
Seems reasonable to just rename the material to make it sound better. This won't affect any gameplay.
Renames it.
idk
https://en.wikipedia.org/wiki/Carbide
> feat: change name of layered carbide to graphene composite

- data/json/monsterdrops/zombie_child.json
I did a dumb and accidentally borked zombie children spawning with random damage on their clothes.
Moved use of `damage` from `default_zombie_children_clothes` to `default_zombie_children_death_drops`.
Screm
> fix: move damage to top level to fix zombie child clothes

- src/map.cpp
Caught a SIGSEGV while trying to craft something from within a vehicle with a butchery station installed. Poking around with a debugger pointed me to this possible copy-pasted line.
Use correct pointer.
None, hard crashes always point to a bug.
Same crafting recipe in the same world started working flawlessly after applying this.
Skipped astyle/formatting, a this is a trivial one-word diff.
> fix: make crafting inside a vehicle with a butchery station not crash

- src/creature.cpp
#6787 accidentally reverted #6770 entirely.
Re-do the changes from #6770
- Make Retagin do it to atone
Absolutely zero, this code worked before it should work again. (Royalfox is better equipped to test anyway)
Gotta love when git / github accidentally does a fucky and causes accidental reverts like this.
> fix: fix #6770 being reverted by #6787

- src/map.cpp
followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6858 to make debugging bash info easier, was merged bit too early
to test, toggle debug mode
> feat(UI): debug info for bullets hitting cover

- src/translations.cpp
- tests/json_test.cpp
- tools/clang-tidy-plugin/CMakeLists.txt
- tools/clang-tidy-plugin/CataTidyModule.cpp
resolves #6814
removed its invocation. kept the typewriter rule checker as we may want to rewire it into single space in the future
comment it out? idk
loaded gun that has description with broken spacing without issues.
ran clang-tidy with cata plugin and it didn't trigger warnings
> feat: disable typewriter rule check

- data/json/mutations/mutations.json
- data/json/obsoletion/mutations.json
- src/character.cpp
- src/iuse_actor.cpp
- src/mutation.cpp
- src/options.cpp
- src/panels.cpp
This is a useful QoL but does not *really* justify being a trait at chargen. Plus, this was brought up as another desired change around the time of Stylish's changes.
- Add a new option to the settings menu: Health Display Style.
- Changes most checks of Self-Aware to instead check for the setting in the options
- Made the first aid bit just use the first aid and perception.
- Going the complete Stylish route of making an inverse trait instead
There are pros and cons to both styles of Health Information display, so being able to freely change between it seems good.
It compiles, and it correctly displays HP and Hunger in-game.
Now HP math is able to be done a hell of a lot easier
Perhaps we can also change the stamina display to do something similar in the future, and also maybe add more …
> feat(UI, balance): Change self-aware effects to an option in the settings

- data/json/construction.json
Digging up grass for material can be a pain at times, and is a bit inconsistent in that cutting long grass into regular grass and then digging up the grass yields 1-2 straw, while removing long grass entirely only yielded 1 straw. Likewise cutting tall grass and then digging it up afterward would give 1-3 grass total while digging it up directly only gave 1-2. And of course, a good chunk of that grass will give nothing half the time...
1. Made it so that digging up regular and dead grass always yields 1 straw pile, instead of sometimes yielding nothing.
2. Bumped up the yield from digging up long and tall grass accordingly to yield exactly 2 and 2-3 respectively, so that digging them up will yield the same amounts as cutting the grass then digging it up would (1 + 1 for long grass, 1-2 + …
> feat(balance): increase yield of removing grass to match cutting grass

- src/activity_handlers.cpp
It was brought up to me that, when stopping part-way-through a study session, the XP is not properly communicated to the player. Additionally, it looks to the player that all the XP is gained at the very end rather than progressively throughout.
Makes the game report the XP you've gained every 10 minutes
In particular, reports the amount of XP you've gained *since* 10 minutes ago.
- Report every minute instead
It compiles and works for me
I have not actually tested if the push_backs of the values vector are necessary. I figured it would be good to have them there just in case.
> feat(UI): add XP progress reporting to studying magic

- data/json/construction.json
The requirement for a pit made it impossible to construct multi-story log houses in-game.
This is not realistic, as there are many multi-story log houses irl.
Overall, the restriction made no sense and hampered player building for no good reason.
Removes the pit requirement, as well as the digging requirement, from the half-built log walls. Also removes relevant bits from the "fortifications" and the flag deletion from the full log wall.
- Add some sort of special exception to allow stacking log walls on top of each other but not allow constructing them on other wall types.
Simple JSON change, just made sure it lints and makes sense.
Continuing to make player constructions suck less
> feat(balance): Remove pit-digging from log walls

- src/catalua_bindings.cpp
- src/catalua_bindings_coords.cpp
- src/catalua_bindings_creature.cpp
- src/catalua_bindings_game.cpp
- src/catalua_bindings_ids.cpp
- src/catalua_bindings_magic.cpp
- src/catalua_bindings_map.cpp
- src/catalua_bindings_mutation.cpp
- src/catalua_bindings_recipe.cpp
- src/catalua_bindings_ui.cpp
```diff
-        luna::set_fx( ut, "is_filthy", []() {
-            return false;
-        } );
+        luna::set_fx( ut, "is_filthy", []() { return false; } );
```
now that we've got #6573, save that vertical space!
check individual commits
be verbose and unhappy
seems to work normally
i hate astyle so much why are we always burdened with our choices of the past aaaaaaaaaaa
> style: use oneline style for Lua bindings

- data/mods/speedydex/main.lua
- data/mods/speedydex/preload.lua
- docs/en/mod/lua/reference/lua.md
- docs/en/mod/lua/tutorial/modding.md
- lua_annotations.lua
- src/catalua.cpp
- src/catalua_bindings.cpp
- src/catalua_hooks.cpp
- src/catalua_hooks.h
- src/character_turn.cpp
- src/debug_menu.cpp
https://github.com/user-attachments/assets/09c6476a-2a1a-4352-a3dc-e043b193bcc4
fixes #6912
adds a new hook, `on_character_reset_stats`, which gets triggered on `character::reset_stats`
cc @olanti-p
> feat: `on_character_reset_stats` lua hook

- data/json/items/ammo.json
You could buy copper wire for free because its price was too small ($1 per 200, which means half a cent per wire, and the game presumably does not like fractions of a cent)
Set the price of copper wires to $4 per 200
- Set it to the minimum, $2 (1 cent per wire)
- Set it to the price pre-apocalypse, $20 (10 cents per wire)
Maths checks out to give whole cents
The only copper that should be free is from Ea Nasir, but we're not in Mesopotamia.
> fix(balance): Make copper wire no-longer free to buy

- data/mods/speedydex/preload.lua
#6914 not actually working due to last minute changes
`preload.lua` runs _before_ `main.lua`. unless wrapped with closure, mod.speedydex is `nil`
screm
1. add speedydex to world mods.
2. debug increase dex to 30
3. see that speed is increased
4. debug decrease dex to 10
5. see that speed is decreased
> fix(mods/speedydex): make speedup actually work again

- data/json/construction.json
Log walls could not be finished because copy-from made them inherit a requirement for nothing to be there from the half-log-wall.
Just stop using copy-from
- fix the copy-from
it works on my save
Continuing to slowly make construction more viable for players
> fix: fix log walls being unable to be finished

- data/mods/smart_house_remotes/main.lua
- data/mods/speedydex/main.lua
- data/mods/speedydex/modinfo.json
- data/raw/generate_types.lua
- lua_annotations.lua
- src/catalua.cpp
- src/catalua_hooks.h
- src/character_turn.cpp
https://github.com/user-attachments/assets/bb9c7076-2ad8-4763-84dd-92b2db6aed2e
> "you have a sandevistan?!"
> "a rudimentary implant."
1. `on_game_save_hooks` didn't pass which character was calling hooks, so NPCs with high dex didn't get speed bonus.
2. variadic templates take a long to compile, whereas passing param-setter fn approach is less compilation-time heavy due to being non-generic.
3. named parameters are a good way to type and document parameters.
please check individual commits.
1. enable speedydex
2. spawn a NPC
3. give them dex 1000
4. confirm that NPC is way faster than you
this may or may not affect performance in a negative way.
> feat: easy parametric hooks™

- .github/workflows/clang-tidy.yml
fixes recently broken clang-tidy pipeline. tested on https://github.com/scarf005/Cataclysm-BN/actions/runs/16849645093/job/47733952037
> ci: fix clang-tidy build

- docs/en/mod/lua/reference/lua.md
- lua_annotations.lua
- src/catalua_bindings.cpp
resolves #6868
1. become debug invincible
2. spawn and spawn grenades
3. run following lua script:
```lua
local grenade_id = ItypeId.new("grenade")
local grenade_act_id = ItypeId.new("grenade_act")
local u = gapi.get_avatar()
local items = u:all_items(false)
for _, v in pairs(items) do
v:convert(grenade_id)
if v:get_type() == grenade_id then
gdebug.log_info( v:get_type(), grenade_act_id)    
v:convert(grenade_act_id)
v:activate()
end
end
```
3. congratulations! you have now become a grenade person
not to be confused with kevin _granade_
> feat: bind `item::{,de}activate`

- data/json/martialarts.json
More rifle adjacent/shaped guns should be usable with Krav Maga. They all buttstroke just the same.
Make the following categories applicable to Krav Maga
- SMGs - They are pretty much rifles, but smaller
- Machine guns - They are pretty much rifles, but bigger
- Grenade launchers -  They are (excluding the mark 19) rifle shaped and held the same way a rifle is
Giving players the option to disable the "(weapon) is not a valid (martial art) weapon!" message.
Spawned in
Beat zombies with affected weapons, krav maga style.
Rocket launchers, gatling guns, etc are not included in this because they are neither shaped nor held like a rifle.
> feat: more guns compatible with Krav Maga

- docs/en/mod/json/reference/creatures/monsters.md
- src/damage.cpp
typo in #6569 unnoticed for months prevented `dark`, `light` and `psi` damages from loading because they were all mapped to `cold`
rename stuff.
should work?
> fix: dark, light, and psi damage not loading

- src/options.cpp
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6586 Was sitting too long unmerged and couldn't merge main branch. Trying to merge main branch caused thousands of file changes and I wasn't going to deal with the chance it borked the branch when I can reopen. Reopened up to date.
It's fairly irresponsible and dangerous to let players to completely disable overmap specials from their game entirely. If it actually worked correctly (Kinda feeling like it doesn't since stuff still spawns at 0 as if it was at 0.1 or maybe 0.5) then it would brick possibly half the starting options in the game and maybe lab generation if its not hardcoded.
Additionally, since density doesn't work to a satisfactory level, I thought it would be ok to allow 4x the max spacing, at 72. It should still properly …
> feat(UI): Update the overmap special options

- data/mods/ebook_lua/preload.lua
- data/mods/saveload_lua_test/preload.lua
- data/mods/smart_house_remotes/main.lua
- data/mods/smart_house_remotes/preload.lua
- data/mods/teleportation_mod/main.lua
- data/mods/teleportation_mod/preload.lua
- data/raw/generate_docs.lua
- docs/en/mod/lua/tutorial/modding.md
[`table.insert`](https://www.lua.org/pil/19.2.html) is the recommended and simpler way to insert element to the end of lua table.
use it
none
played with some lua mods and they all work
> refactor: use `table.insert`

- data/mods/JP_Weather_Variants/weather_regional_map_settings.json
I've gotten multiple reports that the mod is unintuitive to use, as a result of the region being different than default. This can only be changed at the start of a world, so this is a potentially breaking change and additionally meant anyone wanting to apply this mod to an old save was impossible (atleast, without routine maintenance)
Rename the region "default_copy_jp_weather" to "default"
Created a new world, loaded in and the expected weathers appeared unlike before.
I actually don't know if anyone has used the mod. In my testing today, I couldn't get the region in world settings to change even with the mod installed. I seem to remember doing this before and it working as expected, so unless we have somehow broken that feature since I may have been mistaken.
> fix(mods/JP_Weather_Variants)!: rename weather region for accessibility

- data/json/item_actions.json
Because, as finger firelighters revealed, it otherwise says "turn on" no matter what, which may not be accurate.
Also, I can't do any fancy stuff here (unlike if it was actually in C++) afaik
Just make it "Transform" instead
- Implement the ability for the item's iuses to be able to override their names in there with a field.
String change, I used my eyes.
I don't quite understand why these are in JSON to begin with if they're the names of entire categories and thus you can't give individual items different ones.
> feat(UI): Change `transform` item action's name in the menus to be more accurate

- data/json/items/fluff.json
The chemist made a typo when writing out that writ of trade.
The plural form of "chemical" is "chemicals;"
given the context, multiple chemicals are implied.
s
(s)
spawned in
"chemicals" observed
I've only ever met the chemist once.
I tried to mug her but she just laughed at me.
> fix: typo writ of trade

- src/map_extras.cpp
We need to make craters non-radioactive for a few reasons, and since mx_crater is hardcoded it has to be done on this side. There's talk of making special craters with loot that are radioactive, so this will come later because we need to decide how to implement that. We would ideally use an un-hardcoded crater for the special radioactive ones, or at least an implementation more controllable to the average user.
So the reasons I have for this being generally; 
It's a noob trap (Not a lot of players realize it, and it just happens to someone and they don't know why, see Discord on this.), 
Radiation **NEVER** decays so it is always a sizeable threat to where it's located which players can do nothing about, 
It is an uneven threat added to locations that already have no value I.E. radiation …
> feat(balance): Remove radiation from hardcoded mx_crater

- data/json/mutations/mutations.json
Chitinous Plate and Furred Plate restrict headgear.
This doesn't make much sense that having thicker skin would preclude the use of helmets, especially when no other skin mutations have any equipment restrictions.
remove the head gear restriction
Remember the reason why the restriction was put in place to begin with
(I can't find it if any such reason does exist)
Spawned in
mutated Furred Plate
Put on a helmet
nothing weird happened
Spider-Man, Spider-Man
Does whatever a spider can!
Put on a hat? No, he can't!
Skin is too thick, helmet no fit!
Look out!
Here comes the Spider-Man!
> fix: Chitinous Plates no longer restrict headgear

- docs/en/mod/lua/explanation/lua_style.md
needs to install the extension first to use it
> docs: update dprint vscode guide

- data/mods/MagicalNights/items/enchanted/enchanted_misc.json
Just getting 5 unlocks period is really lame.
Make them recharge once every 24 hours
- Longer recharge time
- Fuel them with crystalized mana or the like
Loaded in, picked a gun safe with the key, waited 6 hours a few times, got the charge back.
> feat(balance, mods/MagicalNights): Make skeleton keys recharge

- docs/en/mod/lua/reference/lua.md
- lua_annotations.lua
- src/catalua_bindings.cpp
- src/catalua_bindings_creature.cpp
resolves #6952
```lua
local you = gapi.get_avatar()
print("are you uncanny dodging? " .. (you:uncanny_dodge() and "yes" or "no"))
local items = you:all_items(false)
for _, item in pairs(items) do
print(
item:tname(1, false, 0) 
.. "{ attack cost: " .. item:attack_cost() 
.. ", stamina cost: " .. item:stamina_cost()
.. ", melee stamina cost: " .. you:get_melee_stamina_cost(item)
.. " }"
)
end
```
> feat: bind more item functions

- data/json/items/tool/smoking.json
Disposable dab pens have 30 charges of battery that can be unloaded as free floating battery energy.
Remove battery as their ammunition
give it that NO_UNLOAD flag
Spawned in
I can still hit the disposable dab pen, a charge is consumed
I can no longer unload battery charges
none given
> fix: stop unloading disposable dab pens

- data/json/recipes/other/materials.json
- data/json/uncraft/generic.json
Extra uncrafts with wrong components are bad. Pipes uncraft into 7 scrap but saw into 5 chunks.
Remove all recipes that solely are hacksawing something into metal. Does not touch ones so small they can't be salvaged, as Chaos hasn't allowed salvaging to grant scrap metal yet. This would leave players without a ton of uncrafts.
Also doesn't touch multi uncrafts like tires. Those give rubber too.
idk
basic json
> fix: Remove redundant metal sawing uncrafts

- data/json/mapgen/lake.json
- data/json/overmap/overmap_terrain/overmap_terrain_river.json
- data/json/vehicle_groups.json
- data/json/vehicles/boats.json
Boats should spawn in rivers too!
Adds river_boats vehicle group which is used for boats that spawn in rivers. This generally excludes the larger watercraft.
Additionally, adds a motorized kayak and jetski vehicle.
Spawned both vehicles, ensured they work and look how I'd expect. Explored the rivers a bit and found some naturally occurring boats.
The weight of the spawns has been increased from 1 to 2, as there are many less river tiles on the map than lake tiles, so there should still be a fewer amount of boats spawning here overall.
> feat: jetski, motorized kayak & river boat spawns

- data/json/requirements/materials.json
- data/json/vehicleparts/boards.json
- data/json/vehicleparts/cargo.json
- data/json/vehicleparts/frames.json
- data/json/vehicleparts/rams.json
- data/json/vehicleparts/rotor.json
- data/json/vehicleparts/seats.json
- data/json/vehicleparts/tanks.json
- data/json/vehicleparts/vehicle_parts.json
- data/json/vehicleparts/wheel.json
This makes some tweaks to vehicle part repairs to make some things a bit less clunky to fix when innawoods.
1. Defined crafting requirement `nail_any_adhesive` as a counterpart to `nail_glue` that allows tape as well.
2. Changed vehicle repair for all wooden parts from using `adhesive` to `nail_any_adhesive` so that nails become usable for repairing wooden parts.
3. Standardized all vehicle repairs that use cloth to repair to use `sewing_standard` instead of `adhesive`, and at a saner amount of thread per repair. Some were using barely any, some way too much.
4. Changed seats and beds from requiring full-on welding to sewing to patch up the cloth parts, and leather seats and saddles using leather/fur instead.
5. Set all repairs using `fabric_standard` or `fabric_hides_any` to use both …
> feat: allow nails for repairinng wooden vehicle parts, use sewing for cloth vehicle parts

- docs/en/dev/explanation/code_style.md
Our existing C++ style guide hasn't changed since C++14. now that we have [better tooling (clangd)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6690) and language [(C++23)](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6500), some of these rules are outdated and needs to be updated.
> docs: modernize C++ style guide

- data/mods/MagicalNights/items/ethereal_items.json
These items were in a weird place stats wise, with certain choices I do not support (like giving the tentacle whip Parry)
Changes some of the damage stats, removes or lowers block rating on a few weapons, changes the distribution of animist's sword to be a bit more light-heavy (despite that sounding like an oxymoron)
- Nuking magical focus from the summoned weapons completely
Still considering it, but better left to a much wider reconsidering of what it means to be a magical focus.
Lints, primarily number tweaks and removing some flags.
> feat(balance, mods/MagicalNights): Rebalance ethereal items

- data/mods/MagicalNights/items/ethereal_items.json
This is technically very goofy behavior if someone makes the mistake of summoning two flesh pouches, especially with how long they last.
Change `NO_UNWIELD` to `NO_TAKEOFF` ~~Thus preventing them from flying VFR to San Diego~~
- Keep it because it's funny
I was actually really tempted to label it intended behavior, but unfortunately it just is a lil too jank for my liking. Maybe if someone makes a Magical Nights: Hard Mode or something. (Or I start adding more to the currently microscopic Manic Magical Nights)
These flags are documented
If it has nowhere to grow on the back, it shall grow on thine hands
> fix(mods/MagicalNights): Allow unwielding flesh pouches

- data/json/items/melee/misc.json
- data/json/recipes/weapon/cutting.json
- data/json/recipes/weapon/piercing.json
Per discussion in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7020, moved this to a separate PR since it was basically unrelated. Makes glass shivs stabby instead of cut-only, like most other small knives.
1. Added `STAB` flag to glass shiv.
2. Moved the recipe from the cutting weapons subcategory to the piercing subcategory.
3. In addition, broadened the variety of options for handle material.
Screm.
Also, right below it is a plastic shiv, which I'm noticing got improperly obsoleted as there's a copy of it in the obsoltion folder anyway while its recipe got removed. I'm assuming it got removed when toothbrushes were obsoleted for being bloat, but we could still make it use plastic chunks?
2. Used my eyes to confirm I actually …
> feat(balance): make glass shivs stabbing weapons, more handle material options

- data/json/achievements.json
- data/json/mutations/mutations.json
We added flight but forgot to change the description for bird threshold and the related achievement.
Changed the relevant descriptions to no longer imply that flight isn't in the game yet when it is.
Falling with style.
Used my eyes.
> fix: bird achievement and threshold no longer imply you can't obtain flight

- data/json/mapgen_palettes/house_general_palette.json
Because gray linoleum is the only color for kitchens in houses using `standard_domestic_lino_kitchen`
Add the palette `parameterized_linoleum_color_kitchen` to house_general_palette.json
none
Like `parameterized_linoleum_color_bathroom`, `parameterized_linoleum_color_kitchen` is unused for the moment but will be used in future PR.
> feat: add a parameterized palette to allow different linoleum colors in houses kitchens

- data/json/recipes/ammo/arrows.json
- data/json/recipes/ammo/other.json
- data/json/recipes/other/containers.json
- data/json/recipes/other/materials.json
- data/json/recipes/other/other.json
- data/json/recipes/other/tools.json
- data/json/requirements/toolsets.json
- data/mods/CheesyInnaWoodsFixes/recipes/existing_recipe_changes/tool_recipe_bn.json
- data/mods/MagicalNights/recipes/weapons.json
In preparation for the blacksmithing tool quality PR, this PR migrates a ton of recipes to tool qualities without actually changing anything. Qualities aren't added and things are more internally consistent.
This has the benefits of:
- Less JSON lines
- Easier to update crafting as a whole, for harder or easier
- Easier for modders
- Globalized standardization
This brings us in line where I need to change the fewest recipes possible from direct tool calls to qualities.
Migrates recipes to correct blacksmithing or to one of the new glassblowing crafting standards. 
This only touches what ISN'T going to change balance. And it only changes stuff that doesn't require ridiculous new hyper-specific craft standards.
That is to say, casings doesn't get touched. It would require decision making …
> refactor: move dozens of recipes to crafting standards

- src/item.cpp
At now, `combat_info` from `attacks` shows itself from `itype`, not reflecting current state.
If your rising sun(on) has `DIAMOND` flag, its info shows you the data without cut dmg bonus from `DIAMOND`.
This PR fixes it.
In `item.cpp`, `item::combat_info`, changes `type->attacks` to `get_attacks()`.
`get_attacks()` reflects the item's current state on the data.
Both have same as std::map<string, attack_statblock>, so one change doesn't bother other codes.
scream
> fix(UI): show up-to-date item info for attacks

- data/json/recipes/other/vehicles.json
- data/json/vehicleparts/vehicle_parts.json
- data/json/vehicles/boats.json
- tests/vehicle_drag_test.cpp
This updates some wooden vehicle parts so you don't have to get a full forge setup and make a wood saw (or scrounge up some copper) to make a basic canoe.
1. Set wooden boat boards to use `wood_structural_small` instead of being limited to just planks, since they're the main boat board option for making boats.
2. Set oar recipe to use `wood_structural` instead of just planks, making it possible to make them from sticks.
3. Merged and consistency-checked the use of planks vs sticks in the recipe for light wooden frames via `wood_structural_small`, since we've generally been moving away from recipes using twice as many sticks when both weight about the same. In addition, lowered amount of rope required from 3 to 1, which combined with it still needing 1 rope to install cuts the total ropes …
> feat(balance): simplify and standarize wooden vehiclepart recipes, add light wooden seat

- data/json/vehicleparts/cargo.json
- data/json/vehicleparts/frames.json
- data/json/vehicleparts/rams.json
- data/json/vehicleparts/vehicle_parts.json
This is an idea that came up while discussing adding shock-resistance flags to more vehicleparts, the idea of making carbon fiber and superalloy parts take less indirect damage from collosions to encourage players to dabble in the fancier materials for their deathmobile. Making superalloy in particular even better for this came up in the BN server as potentially neat given superalloy can't be crafted barring nanofab shenagians, while carbon fiber is craftable later in the game.
1. Added `SHOCK_RESISTANT` to all carbon fiber parts.
2. Added `SHOCK_IMMUNE` to all superalloy parts.
3. Misc: Fixed a couple carbon fiber parts not yielding filaments when broken.
Making superalloy parts merely resistant and not immune.
Note to self: add carbon …
> feat(balance): carbon fiber parts are shock resistant, superalloy parts shock immune

- data/json/construction.json
- data/json/furniture_and_terrain/furniture-appliances.json
- data/mods/CRT_EXPANSION/constructions/crt_constructions.json
Royal reminded me that a lot of constructions are dumb and call for steel chunks exclusively instead of using relevant crafting requirements, which would be a mild annoyance had I not made salvaging return scrap metal instead.
1. Took every reference to steel lumps/chunks or I saw in construction.json and converted to either `steel_tiny` or `steel_standard` based on how much it called for, leaving behind only cases where it called for just scrap metal in an amount that didn't neatly equal a multiple of 5 (since `steel_tiny` calls for 1 steel chunk or 5 scrap metal).
2. Per suggestion, removed the need for steel chunks from grid turbines and water wheels because these are more ready-to-use than solar panels are.
3. Converted some more constructions to use `wood_structural` or …
> fix: update construction to use wood and steel crafting requirements

- data/json/vehicleparts/turret.json
This lowers and/or drops weapon subskill requirements for installing some of the more simplistic vehicle-mounted guns, but in exchange makes a couple others higher level. Makes the most basic turrets usable without skill grinding for their combat skill.
Reduced skill requirements for the following weapons: huge crossbow, repeating crossbow, carbon fiber repeating crossbow, .50 cal sawn-off, BAR, makeshift cannon, slingshot cannon.
Conversely, increased skill requirements for the following: gatling shotgun, pneumatic bolt driver, pneumatic assault rifle, RM298 HMG, RM614 LMG.
1. Removing weapon subskill from turret installation entirely.
2. Adding ballistas as another potential launcher option innawoods.
3. Making heavy crossbow use launcher skill and giving it the `MOUNTED_GUN` flag? Foot …
> feat(balance): adjust turret install diffuculties

- src/npc.cpp
Its very annoying to babysit Npcs reading sessions.
Please, Npc, when I tell you to read the book, read the mf book!
Added a check to see if the Npc exceeds the book's skill level and only early return if it does.
Raised my speech skills to 10, recruited the starting npc, spawned a first aid book and an atomic lamp.
We spent the first day calmly reading the same book awkwardly.
She started with level 1, ended up at level 3, and finished gracefully.
> feat: Make npcs finish their books

- data/json/npcs/TALK_COMMON_OTHER.json
- src/npctalk_funcs.cpp
A player can continuously request an NPC for an item, which is a super grindy but stupid way to level up a skill.
This happens because the effect "asked_for_item" is never actually applied.
Properly add the effect and remove the chat option that disrespects consent and loops.
Tried pestering the starter npc with the lowest chance of success, then looked at it's status effects to confirm it had the proper effect and tried to ask for more stuff, which it denied.
Fixes https://github.com/cataclysmbnteam/Cataclysm-BN/issues/6694
This still lets you request several items IF you succeeded, because it lowers that NPC's opinion of you.
Might be worth eventually having a limit on that too.
> fix: prevent infinite speech loop via requesting equipment

- src/character.cpp
fixes #6809
It's should not be possible to mass produce NPCs
Like the "place_monster" action, "place_npc" now self combusts upon use.
Fix the uses of place_npc to use DESTROY_ON_DISCHARGE, an unintuitive requirement
- Mainly to ease maintaining the Kenan modpack, if they mean for multi use hologram generators
Spawn into a game with aftershock, debug in Frankenstein, place him down. The inactive Frankenstein disappears, a Frankenstein appears.
- It modifies the current seemingly bugged behavior of place_npc
> fix: NPC generating items are no longer reusable

- src/magic_spell_effect.cpp
Cones currently have blind spots of random tiles that don't get hit by them for some reason
Reduce the increment of drawing the rays to construct the cone to half a degree instead of a full degree (meaning we draw twice as many rays to construct the cone)
- Figure out how to make a cone without doing all this silly ray stuff
Fixed a smol one in my own testing, but RoyalFox likely has better test candidates
Before:
After:
We don't draw that many cones, so I could see going to even more fine-grained angles if this doesn't quite fix the issue entirely
> fix: Fix cones having weird blindspots at certain angles and rotations

- docs/en/mod/json/reference/creatures/mutations.md
Read the code and attempted to explain some of the healing rate changes from healing_awake and healing_resting
Not great, because the math is complicated.
> docs: Attempt to explain mutation healing changes

- src/locations.cpp
Fixes #6433 #6584 No more crashes if you lose clothing from a mutation. 
Removes the items directly on detach rather than recurring into remove_worn_items_with. 
I need to look more into some of the safety stuff around this. It's meant to give red text on bad recursion like this, but it went wrong here because it never actually got to removing an item and triggering that. 
Giving myself freakishly huge doesn't crash anymore.
> fix: stop recursively using remove_worn_items_with when removing gear

- data/json/bionics.json
- data/json/items/bionics.json
- src/npcmove.cpp
Solar Panels are very good CBMs for powering things during the day.
NPCs should be able to use it
Additionally NPCs should not complain about lacking sunlight or wind. That is just odd.
Add the BIONIC_NPC_USABLE flags to the bionic items
Where NPCs complain about lacking fuel, skip if the fuel is sunlight or wind.
Lament that I can't not use the Metabolic CBM... Feels cheaty with unlimited food NPCs.
Spawn NPC, give it solar panel CBM, you can install it.
During the night, they don't complain about lacking sunlight
> feat: NPCs can use CBMs using Solar or Wind Power

- docs/en/dev/explanation/code_style.md
Chaosvolt will remember me accedentially changing nearly every file, that was because I was using astyle 3.6.6
Then I installed 3.0.1, which had only a few issues.
When looking into the github action of the fix-bot, I found it installed astyle from Debian repos each time it ran.
That astyle version is 3.1 see [debian docs](https://manpages.debian.org/trixie/astyle/astyle.1.en.html)
So the docs needed to be updated to the new versioning, along with adding a warning regarding much newer versions.
Also the Doc commands and .astylerc do not match, make the doc commands match .astylerc as that is used by the autofix bot.
Also orders the Documentation commands in the same order as .astylerc for clarity.
> docs: fix documentation around astyle

- data/json/items/comestibles/med.json
- src/iuse_actor.cpp
Drugs should follow their set JSON time like any other sane effect, like magic (does that even use json?).
@chaosvolt You said "Someone open an issue for it plz", I hope skipping that step is fine.
Removed the duplicated section of code around applying the effect.
If only Github would show one more line so you didn't need to dig through the file to see...
- Double the effect time of all in game drugs so that I don't destroy anyone's playstyle
- Keep the current double call, but half each applied time, so that you don't need to use double the painkillers at one time
- It seems to be an issue at least, but either way drugs would be halved in effectiveness.
Spawn in a drug and it should have half the length it used to, and is at the JSON length.
- Specifically Drugs now have half of the …
> fix: Drugs no longer have double the effect time

- data/json/items/comestibles/med.json
Somehow my brain did a smooth when I gave GHB a quickfix in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7101 and I accidentally deleted the activation line.
Undeletes the line that should not be deleted.
screm
Used my fucking eyes for once.
> fix: restore accidentally deleted line

- data/mods/teleportation_mod/item.json
- data/mods/teleportation_mod/main.lua
The teleportation mod while functional currently has two issues.
- Teleport anchors and stations are not consumed upon placement
- Teleport anchors and stations are not returned upon deconstruction
Adds the "DESTROY_ON_DECHARGE" flag to the undeployed teleport station and anchor
Upon deconstruction of deployed version, place an undeployed item in it's place.
None
Spawn in a teleporter anchor, place it down, the item disappears.
Use the teleporter remote to deconstruct it, the teleporter anchor item reappears
Repeat for the teleporter station.
> fix(mods/teleportation_tech): make teleport furnitures deploy/collectable

- src/ballistics.cpp
- src/mondefense.cpp
fixes #6869 
Turrets should not return fire when attacked by EMP weapons, due to the property of them causing explosions.
Currently the chain goes as such:
- Player attacks with EMP
- EMP bullet attacks light turret
- Turret returns fire
- EMP explosion occurs
- Turret Dies
Changes it so that the chain is:
- Player attacks with EMP
- EMP explosion occurs
- Turret Dies OR EMP bullet attacks light turret
- If bullet attacks and is still alive, turret would return fire
Additionally before return fire, the creature will make sure it is still tracked in "creature_tracker"
- As that is how the EMP explosion "kills" the creature, not by losing health.
Remove the damage of the EMP projector's bullet, as it is designed for anti-turret alone
Move all explosions to occur before the bullet, so other …
> fix: Turrets will no longer return fire when using EMP weapons

- data/json/items/comestibles/other.json
- data/json/monsters/bird.json
- data/json/monsters/mammal.json
- data/json/recipes/food/other.json
Taming animals is fun, we need to have more fun, so we need more tamable animals!
Added petfood to many animals who are peaceful enough to do so.
Added a new type of petfood for bats, and made them tamable (except vampire bats for now).
Added the possibility to tame a bear cub IF you are post-thresh ursine or have ANIMALEMPATH, like elf-a
Spawned a new empty world, spawned monsters, gave them food.
Mutated to Ursine, spawned a bear cub, gave it food.
Relates to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7049 , https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7070 , https://github.com/cataclysmbnteam/Cataclysm-BN/pull/6996
> feat: add more tamable animals

- data/json/recipes/ammo/components.json
Minor lil fix, we got the ability to take apart casings including spent .22 cases, and can take apart primers, but can't take apart a reprimed .22 casing.
Makes reprimed .22 casing recipe reversible, matching how primers currently are uncrafted via reversible recipe. Also added a decomp learn 2 levels higher than recipe difficulty, as primer recipes use.
Adding an explicit uncraft for them instead.
Used my eyes.
> fix: also allow taking apart primed .22 casings

- data/json/vehicles/boats.json
- tests/vehicle_drag_test.cpp
This makes a couple tweaks to two of the boats.
1. Removed two of that cannons on pirate ships, as even when completely empty its minimum weight as spawned was getting kinda close to the edge of what a single large sail could reliably power.
2. Reduced powder keg spawns from 3 calls of `supplies_powder_mag` to just one, in exchange for making it a 100% chance instead of 50%. Basically means each ship goes from spawning 0-6 powderkegs to a more consistent 1-2.
2. Misc: Fixed only half the seats on canoes being replaced with wooden varient.
Removing the restriction on installing multiple sails on a vehicle so that players can build big-ass galleons loaded with multiple cannons.
2. Ported file change to playthrough build and load-tested.
> feat(balance): reduce number of cannons and powderkegs on pirate ship, fix canoes

- data/json/professions.json
Lil oversight, turns out while testing https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7035 I gave the pirate profession a vehicle but forgot to remove it after I added the pirate captain profession.
Remove pirate ship from the lower point cost landlubbin' fella.
Walkin' the plank fer me crimes.
Used me eyes an' confirmed I gots no eyepatches on.
> fix: don't give regular pirate profession a vehicle

- data/json/furniture_and_terrain/terrain-fences-gates.json
Smol thing I spotted while working on another PR, wooden railing had a weirdly low destroy threshold that didn't match its max bash roll, like terrain normally has. But then I further realized its bash resist was the same as metal railings.
1. Raised destroy thresh of wooden railing to 80, matching its `str_max`.
2. Bumped bash values of metal railing from 20-80 to 25-100.
3. Along the way I further realized that guard rails have 8 `str_min` which is wacky when glass rails have 10, bumped those up to 25 to match metal rails.
Not buffing metal railings.
2. Confirmed my brain retains enough wrinkles to verify that the number 25 is higher than the numbers 10 and 20.
> feat(balance): metal railing has higher bash resist than metal railing, correct `destroy_threshold` of wooden railing

- data/json/flags.json
- data/json/items/tool/electronics.json
- data/json/items/toolmod.json
- data/json/recipes/electronic/components.json
- docs/en/mod/json/reference/items/item_creation.md
- src/avatar.cpp
- src/character.cpp
- src/character_turn.cpp
- src/flag.cpp
- src/flag.h
- src/item_factory.cpp
- src/item_factory.h
- src/itype.h
@RoyalFox2140 wanted to be able to recharge items with a replaceable battery using a UPS, this would provide that.
In addition, it makes a UPS recharge all objects at a set rate, so connecting more objects does not increase total recharge rate.
Coverts code from using charges and maximum_charges() to ammo_capacity(), ammo_remaining() and ammo_set()
Adds a new field "ups_recharge_rate" which sets how many charges the UPS recharges each turn IN TOTAL.
Adds a new flag "ADD_UPS_TOGGLE", which adds the UPS_TOGGLE action to an item.
This new thing replaces the previous UPS mod
Change the flag for recharging from ups from USE_UPS to UPS_RECHARGE or even the RECHARGE flag to differentiate using the UPS as an ammo source or recharging internal batteries.
- Note: this provides very little …
> feat: UPS can recharge both internal and reloaded batteries

- data/json/items/containers.json
- data/json/items/tool_armor.json
Fixes some items I overlooked that would make sense to be wearable with snake tails.
Added the flag to:
1. Canteens/waterskins that go on the leg slot.
2. Holo cloak.
3. Emergency blanket.
4. Towels.
5. Electric blanket.
Screaming.
Used my eyes. :D
> fix: add `ALLOWS_TAIL_SNAKE` to overlooked containers and tool armors

- src/iexamine.cpp
Crafting a liquid while adjacent to a keg/standing tank will give you a prompt to pour it directly into the keg. 
Selecting the option to pour liquid into a keg will correctly add the liquid to the tank, 
However if the tank already has that same liquid in it, the menu will not close after transferring all liquid charges
This appears to be because all other code paths return detached_ptr<item>() when all liquid charges have been transferred except for this one
Correctly return detached_ptr<item>() when all liquid charges have been transferred into a partially full keg
Uhh, not fixing this I guess?
Placed a oven next to a standing tank and partially filled it with clean water
Batch crafted some clean water (with the hammerspace mutation turned off)
Checked that the menu now correctly …
> fix(UI): pouring liquid directly into an adjacent keg after crafting it wont lock you in a menu

- src/character.cpp
fixes #7095 
Diving underwater and then equipping a flotation vest increases your swim speed enough that your stamina does not drop while swimming. 
This is presumably unintended given items with the flotation flag prevent you from diving
Simply disable the swim speed bonus from flotation devices when underwater
Additionally preventing a player from wearing a flotation vest while underwater
Making the flotation vest drag the player back to the surface somehow?
Located the nearest lake and swam to the bottom of it
Wore a flotation vest and swam around to confirm stamina depleted normally
> fix: flotation device doesnt give a swim bonus underwater

- data/json/items/tool/cooking.json
fixes #6637 
Currently, there is a decent chance a multicooker will disappear when cooking recipes that are around 3-4 minutes long (when unupgraded). 
This is because the multicooker has a 50% chance of using 1 charge per turn and a 50% chance of using 2 charges
Subsequently a recipe may then take more charges then the multicooker has which sends it to the void
Adjust power draw to 1 charge per turn so its consistent
That does mean this is also a buff but theres not exactly a lot of other options to fix this issue so
Adjusting it to 2 charges per turn instead?
Spawned several multicookers and cooked rice with them
Verified it took 410 charges consistently every time
(3 minute recipe * 2 = 360 charges + the initial 50 charge cost = 410)
> fix: multicooker no longer has a chance of disappearing when cooking food

- src/construction.cpp
- src/crafting.cpp
- src/player_activity.cpp
The previous intended followup PR to fix this issue did NOT fix it. followup to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7146
Flip a fraction again. And again. And again.
Giving up
// TEST 1 (CONTROL):
// 50% speed
// straw hat = 42 minutes total. UI displays: 10 minutes and 10 minutes respectively. (200 speed mult displayed)
// 100% speed
// straw hat = 21 minutes total. UI displays: 20 minutes and 21 minutes respectively.
// 200% speed
// straw hat = 10 minutes total. UI displays: 40 minutes and 40 minutes respectively. (50 speed mult displayed)
// TEST 2 (AFTER CHANGES):
// 50% speed
// straw hat = 12 minutes total. UI displays: 10 minutes and 10 minutes respectively. (50 speed mult displayed)
// 100% speed
// straw hat = 21 minutes total. UI displays: 20 minutes and 21 …
> fix: make world settings for crafting work as intended

- src/animation.cpp
- src/catalua_hooks.cpp
- src/catalua_hooks.h
- src/character_turn.cpp
- src/visitable.cpp
apply belated review suggestions in #7118 #7128 and clang-tidy warnings
> refactor: fix build and lint warnings

- msvc-full-features/vcpkg.json
The build is failing due to being unable to download libogg.
This appears to be because the gitlab for libogg is VERY unstable now, likely for AI-related essentially DDOS reasons.
A fix was merged a few days ago in vcpkg, but we won't catch it unless we update the package baselines.
I decided to just update the commit hash to the latest commit to the file, and if necessary will work backwards from there.
Updates the vcpkg baseline for packages to the latest commit to the JSON file.
- Manually specify it
- Be more conservative with the commit hash to update to
I'm not on Windows, so my testing will be done through Github building
What the fix actually is, is literally just changing the download source from the gitlab for OGG to the git*hub* for OGG
I learned of this fix from searching …
> build: update vcpkg package baselines

- data/json/items/armor/holster.json
- data/json/items/gun/40x46mm.json
Some adjustments to launchers after discussion in the BN discord. Idea is make grenade launchers work in appropriate holsters, and adjust some things to fit better.
1. Allowed holsters, XL holsters, and survivor harness to hold launchers. This allows the XL holster to hold an M79 as-is or an MGL with the folding stock mod, and a regular holster to hold one that's had the stock cut off (see below).
2. Bumped volume of M79 from 1 liter to 1300 ml, idea being it stays in XL holster range by default but gets pushed back into holster range if you cut the stock off.
3. Adjusted makeshift launcher up to 1500 ml to remain beefier than the proper factory version, still makes the single-barrel version fit within an XL holster normally and a normal holster when stockless, while making the …
> feat(balance): allow holsters to accept launchers, increase volume of M79, add folding stock to MGL

- data/json/items/armor/holster.json
- data/json/items/armor/storage.json
- data/json/recipes/armor/storage.json
The survivor harness was already fairly good as an upgraded back holster, but sadly it was no true MOLLE rig, and neither was the MOLLE pack. Until armor mods are added, giving a use to webbing belts other than disassembling them and giving the survivor harness and MOLLE pack some holster slots should help.
Literally the entire point of the MOLLE pack IRL is that you can hang a wide variety of equipment loadouts from its belts, allowing you to load it with the kit you need without making custom backpacks for each soldier.
The MOLLE pack and the survivor harness have been modified to have a number of holster slots for a wide variety of equipment, allowing you to finally actually use the MOLLE system, at least in some fashion.
Hitting my head against a table until I've decided creating a …
> feat(balance): MOLLE pack, Survivor Harness have more holsters, holster options

- src/game.cpp
- src/game.h
- src/options.cpp
- src/overmap_ui.cpp
- src/sdltiles.cpp
- src/sdltiles.h
People may prefer the overmap tiles of one tileset but the main tiles of another.
Adds a setting to use a different tileset for the overmap. This results in a different tilecontext object being made and used for the overmap. Also includes some changes to how the overmap gets drawn, since otherwise the overmap ends up displayed incorrectly (offset from center) if there's a difference in tile size between the two tilesets.
Deal with not liking the overmap tiles of my preferred tilesets.
I loaded up the game and ran around for a while, checking the map frequently, making sure everything seems to be showing up properly. Tried it with a few different combinations of tilesets, sometimes with the same tile size and sometimes differing.
PRs that have been ported in here:
- …
> feat(port): port overmap tileset option from DDA

- data/json/item_actions.json
- data/json/itemgroups/Clothing_Gear/clothing.json
- data/json/itemgroups/Clothing_Gear/gear_civilian.json
- data/json/itemgroups/Locations_MapExtras/locations.json
- data/json/itemgroups/Locations_MapExtras/locations_commercial.json
- data/json/itemgroups/Locations_MapExtras/mansion.json
- data/json/itemgroups/collections_domestic.json
- data/json/itemgroups/electronics.json
- data/json/items/tool/electronics.json
- data/json/recipes/electronic/tools.json
- data/mods/MagicalNights/items/enchanted/enchanted_misc.json
- src/item_factory.cpp
- src/iuse.cpp
- src/iuse.h
- src/iuse_actor.cpp
- src/iuse_actor.h
- src/locations.cpp
The existing VIBE iuse was clearly made exclusively for vibrators, and also only for a specific *kind* of vibrator. As such, two changes were desired:
1. A more generalized sex toy iuse that functions similar to the old VIBE iuse
2. A method of representing toys such as bullet vibrators, where the user could conceivably move around and do things while still using them.
- Creates a new iuse_actor `sex_toy`, which is meant to be a more generalized form of the old VIBE iuse
- Adds a BULLET_VIBRATOR_ON iuse, which functions very similarly to the MP3_ON iuse.
- Also changes the vanilla vibrator and MN's mana-powered vibrator over to the new iuse_action
- Adds a bullet vibrator item
- Adds the bullet vibrator item to the same "normal" itemgroups as the basic vibrator at the same odds.
- …
> feat: Enable a wider variety of Adult Toys

- data/json/items/gun/9mm.json
kel-tec 2000 has no underbarrel slot despite having a barrel, and a space underneath that barrel.
add underbarrel slot
add a second rail instead
spawned in
kel-tec 2000 had underbarrel
I always thought it was weird, but hadn't thought much of it until I saw a picture of one.
Did you know they fold in half? That's cool.
> fix: kel-tec 2000 has underbarrel slot

- src/locations.cpp
It's an evil issue
Make it check for the action, not for the action being usable (I.E. it having room)
None
Spawn in leg mag pouch, fill it, it is no longer slower then inventory.
SCREM
> feat(balance): Reloading from bandoliers and pouches is no longer slower when full

- data/mods/Monster_Girls/migration.json
- data/mods/Monster_Girls/mutagens.json
- data/mods/Monster_Girls/recipes.json
I forgot, in my haste to add bunnygirls, to actually give them a mutagen. And to migrate rabbit mutagen.
Adds the relevant mutagens and migrations
- Implode
I made sure I got the recipes ans the names of the rabbit mutagens correct. It also lints.
Wow, that's embarrassing of me.
> fix(mods/MonsterGirls): Add forgotten bunnygirl mutagen

- data/mods/CRT_EXPANSION/items/crt_item_groups.json
- docs/en/mod/json/reference/items/item_spawn.md
- src/item_factory.cpp
- src/item_group.cpp
- src/item_group.h
Seemed to be a wanted change,
And 100% needed for the CRIT mod
So here you go!
Add the "remove" array to item groups
With an { "item": item_id } it will remove the item from the group
With an { "group": group_id } it will remove the subgroup from the group
This may not function for nested distributions or collections, but is much better then the current state.
Don't add it?
Change the variable names
Go into a military gear installation with CRIT on, see that it properly deletes only certain items
Or add it to your own mods and watch the fix work
THE PRIORITY LIST NEEDS TO EXIST, SAVE ME FROM THE TEDIUM OF JSONIZING THE CHARCOAL COOKER!
> feat: Item groups can now be reset and have some items deleted & make CRIT use it

- docs/en/mod/json/reference/items/item_spawn.md
I'm really bad at missing little things
Followup to the mildest mistake in #7191 
Add purge field docs to missing spot
Leave the docs that way, It sounds fine :)
Eyes
> docs: place purge itemgroup documentation in both places it should be

- data/mods/CRT_EXPANSION/items/crt_armor.json
- data/mods/CRT_EXPANSION/items/crt_clothes.json
- data/mods/CRT_EXPANSION/items/crt_item_groups.json
- data/mods/CRT_EXPANSION/scenarios/crt_classes.json
Follow up to #7169 with regards to CRIT balance
Also does some work following up on #7191 for CRIT (as it only changed clothing_military, not clothing_military_winter)
Buff the CRIT backpack to add the new holster slots (So it aint worse all around)
Have starts that use the CRIT (solar/back)pack use it in replacement of holsters and sheaths
Add CRIT Solider Gear as a rare possibility for solider shirts
Buff the CRIT chestrig to be able to hold small tools & knives so it is distiguishable from the chestrig
Removes duplicated definition of crt_belt, other copy is in crt_armor.json
None
Spawn in, it loads, can pull and place the weapons from the professions backpacks
My eyes don't see any spelling errors!
It does not show stuff in the solarpacks in the Choose character screen, I have no clue …
> feat(mods/crt_expansion): More CRIT rebalances and use of new MOLLE holsters

- src/newcharacter.cpp
It's unclear why certain things in the PROFESSION tab of character creation have "Profession" in front of their names, for example: "Profession items", "Profession bionics", etc. Additionally, it's unclear why others don't. For example, "Pets", "Vehicle", etc.
Remove the "Profession" prefix from entries that have it. This seemed redundant, and therefore the better choice between renaming everything to start with "Profession" and removing it from everything that has it.
Changing them all to start with "Profession", this seemed redundant.
Compiled and loaded, everything worked as expected.
> fix(UI): standardize profession variable names

- src/world.cpp
Chaosvolt has repetitively demonstrated the need for it
Don't crash, just copy the save file like it should
Also delete the old save file
Use the Debug menu -> player -> change thingies -> change save name
Unlike before it no longer crashes and you save and load right
This issue has been persistent and with recent changes is a ticking bomb
> fix: Resolve Save Id changing errors

- data/json/itemgroups/Locations_MapExtras/map_extras.json
- data/json/mapgen/map_extras/corpses.json
The corpse sites from `corpses.json` (`mx_military`, `mx_science`, etc.) ignore the global item spawn rate multiplier and always spawn very generous amounts of loot, which for those playing with reduced spawn rates can ruin the challenge. I can only assume this is unintentional, because the old C++ implementation of these extras generated fewer bodies (and therefore less loot) at lower spawn rates.
This happens because the use of `place_loot` with the chance of exactly 100 makes the loot guaranteed. The solution is to use `place_items`, for which no such special case exists.
Simply switching to `place_items` restored the old behavior exactly, but there is one enhancement that is possible: place the corpse itself separately as guaranteed loot, so that the bodies are always there, but their …
> fix: Item spawnrate applies to corpse loot once more

- data/mods/Monster_Girls/vanilla_mutations.json
- scripts/monster_girls_mutations/main.ts
followup to #7207
filter out threshreqs not in category
to test:
1. revert `vanilla_mutations.json` to before the new migration script by `git restore --source dfe25f1~1 data/mods/Monster_Girls/vanilla_mutations.json
`
2. run the script with `scripts/monster_girls_mutations/main.ts && tools/format/json_formatter.cgi data/mods/Monster_Girls/vanilla_mutations.json
`
3. check that the output is identical to python version (except ordering, but script output is idempotent so that'd be ok)
https://discord.com/channels/830879262763909202/1415736824025972918/1415774492654833666
> fix(mods): match monstergirl script behviaor to old one

- src/sounds.cpp
The recent changes to sound messages in the log didn't account for quotations.
Add a tiny change to fix it.
Spawn skeletons and a few friendly NPCs, notice that the log now properly displays `"What was that? I heard <noise>..."` instead of `"What was that? I heard <noise...".`
Before:
After:
> fix(UI): ensure_punctuation handles quotes properly

- data/json/items/gun/66mm.json
- data/json/items/gun/84x246mm.json
- data/json/items/tool/explosives.json
- data/json/uncraft/weapon/explosive.json
- src/item.cpp
- src/iuse_actor.cpp
I figured it'd be neat to allow slapping a shoulder strap on more rocket launchers since soldiers frequently carry it that way, but then in the process of trying to make the packed version wearable by default with I discovered that guns equipped with slings have encumbrance but no coverage percent, meaning they're entirely safe from damage when things like the pistol lanyard indicate that it's expected that a gun will be more at risk of damage when worn on a sling compared to a holster (which takes the damage instead of the gun it holds).
C++ changes:
1. In item.cpp, `item::get_avg_coverage` now assigns a coverage percent to guns the same way `item::get_encumber_when_containing` does, only difference is set it at 1% coverage per 500 ml of volume, contrast 1 encumbrance per 750 ml volume. …
> feat(balance): guns on slings gain coverage percent based on volume, allow slinging more rocket launchers, M72 LAW can be worn when packed

- data/json/recipes/other/tools.json
aaaaa
Changed one letter.
Embrace snail.
> fix: survivor lighter takes 45 minutes instead of 45 hours

- data/json/mapgen/nested/residential_lawn_nested.json
- data/json/mapgen/nested/roof_nested.json
- data/json/npcs/classes.json
- data/json/npcs/npc.json
- data/json/professions.json
The camper NPC that spawns in the middle of the city makes absolutely zero sense.
Replace it with a more fitting NPC and adds a rooftop variant.
Adds sunglasses to the exterminator profession, to better match the intended look.
Making the NPC use a more toned down NPC_mutation trait group? I imagine most of the time this NPC is going to die anyways, considering they're spawning on a lawn in the city.
Teleported around a bit, it was still hard to find (I couldn't in my testing). Spawned it in using debug, NPC spawned as expected.
Various NPCs spawned using this nested mapgen. It would be nice to gate this after a certain time period, but the rarity should be enough.
> feat: replace camper NPC with mutant wandering scavenger

- data/json/npcs/starting_traits.json
delet
screm
Searched the file to confirm no more hits for `""`
> fix: remove empty trait entry from `trait_group_EARS`

- data/json/flags.json
Smol lil punctation fix caused by some copypaste errors on my part.
Eliminated redundant period in descriptions for `ALLOWS_X` flags.
MORE PUNCTUATION...?!
Demonstrated the mathematical prowess to observe that one period is fewer periods than two periods.
> fix: remove redundant punctuation from `ALLOWS_X` flags descriptions

- data/json/furniture_and_terrain/terrain-roofs.json
- src/cata_tiles.cpp
- src/map.cpp
- src/map.h
- src/map_memory.cpp
- src/mapdata.cpp
- src/mapdata.h
Allows for transparent floors. Mostly to alleviate the performance problems of flying over forests.
Expands the Z_TRANSPARENT flag to make the floor truly transparent. Also removes the hard coding on open air not being added to map memory. There's now a NO_MEMORY flag which is also used by the "fake" open air tiles. This means they now render correctly.  
There's a bit of overlap between the behavior of NO_FLOOR, Z_TRANSPARENT and NO_MEMORY, but this should be convenient to build tiles with. 
Flying over a forest is significantly faster and skylights now look like a hole and work like a floor rather than the other way around.
Note that skylights are bulletproof but this is an existing bug that bullets don't bash floors, there's a todo about it in the ballistics code.
> feat: transparent floors

- data/json/professions.json
Couple lil profession fixes pertaining to mutant clothing restrictions.
1. Gave avian heli pilot a leather jacket instead of a tank top as it was being eaten by bird wings.
2. Set subject suit to be swapped for a long-sleeved shirt and a tail warmer instead of the more odd-looking rag tunic when a profession starts with snake tail.
Giving tank tops `ALLOWS_WINGS` because they're short enough you can probably just have the back just on the bases of the wings. Mmm, birdgirl underboob...
Used my eyes.
> fix: give avian heli pilot torso clothes they can wear, better substitution for subject suit with snake tails

- data/json/requirements/toolsets.json
I seem to have missed this in #7276. woops
Add wrist computers to relevant toolset crafting standards. Those include utility, coding, hacking, and math.
Removes the control laptop from the medical standard, as intended.
Loaded in, didn't get any errors related to the changes and the game still works.
> fix: add wrist computers to crafting standards

- data/json/skills.json
- data/raw/tips.json
- src/activity_handlers.cpp
- src/character.cpp
- src/character.h
- src/character_turn.cpp
- src/game.cpp
- src/magic_spell_effect.cpp
- src/relic.cpp
- tests/ranged_balance_test.cpp
It was discussed in a development thread that we'd like to implement skill benefits based on the skills we currently have implemented. This is part one of the athletics portion.
Renames the swimming skill JSON to athletics, while leaving the code version the same as it'd likely cause issues with saves and such.
Modifies Character::calc_encumbrance to account for the current athletics skill. It then subtracts a point of encumbrance per level for each body part.
The player can now gain skill by any stamina burn. This is currently around 20% skill gain from level 0 for a sprint cycle.
Spawned in as a Punk Rock Girl, stripped to only my leather jacket (7 encumbrance). Noticed that at 0 athletics, it is the same as before. At 7 athletics, my encumbrance is effectively 0. At 10, my encumbrance …
> feat: rename swimming to athletics, encumbrance benefit

- data/json/skills.json
- data/raw/tips.json
- docs/en/mod/json/reference/json_flags.md
- src/character.cpp
- src/skill.cpp
- src/skill.h
Follow-up to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7294 to make stamina burn affected by athletics skill, and allow for skills that are automatic and thus don't interact with focus at all.
1. In character.cpp, `Character::mod_stamina` now takes athletics skill into account, reducing stamina burned by up to a third at 10 athletics skill.
2. Also in character.cpp, moved the debug messages for printing stamina burn/recovery from `Character::burn_move_stamina` and `Character::update_stamina` to `Character::mod_stamina`, so that it prints an accurate number.
3. Set `Character::practice` so that skills with the new `unaffected_by_focus` tag (as defined below) no longer gain any modification from focus pool, and additionally no longer drain focus in turn.
4. In skill.cpp and …
> feat(balance): althetics skill reduces stamina burn, athletics and driving now no longer drain and are unaffected by focus

- data/json/items/book/maps.json
- src/character_turn.cpp
Fix the null ammo error when using a UPS to reload by falling back on ammo_default
Also fixes the lack of dams on maps, a true tragety
Fixes the error
Add dams to maps
Split this into 2 PRs
Read for the map
And attempt to replicate the UPS reload issue and fail ( I couldn't at least :) )
I named the branch fixmymistakes for a reason :)
> fix: Fix Null Ammo Error & add dams to maps

- src/avatar_action.cpp
- src/character.cpp
- src/character_turn.cpp
Waiting an hour in deep water while wearing a life jacket was generating several level's worth of swimming EXP. Far as I can tell this has always been a problem, but back when the swimming skill was as useless as it is in Deus Ex it didn't matter. Now that it's the athletics skill and does useful stuff elsewhere however...
1. In avatar_action.cpp, per feedback I've kept the EXP gain to atheltics when actually moving around in the water, but nerfed it a bit to only be a 75% chance of granting 1 per turn whether underwater or not, which now no longer applies if you're wearing a life jacket.
2. In character_turn.cpp, removed the free EXP practice in `do_pause`.
3. And in character.cpp, after some testing and discussion in the discord, nerfed athletics gain from EXP a bit more in …
> fix: remove bonus EXP from swimming now that burning stamina generates EXP

- data/json/items/fake.json
Forgot to do it in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7295
Makes the treadmill furniture and ball machine furniture's fake item require power
Doing it flintstones-style?
> fix: make treadmill & ball machine powered

- src/activity_handlers.cpp
- src/iuse_actor.cpp
Mirrors aren't powered right?
Shuffle some stuffs around
Make sure the power if statement applies only when there is ammo needed
Do some more early returns
Stuff like that
Screm
The order looks slightly better, it might be able to give 1 extra tick though, I'm not sure
> fix: train skill actor once again supports unpowered items

- data/json/recipes/electronic/tools.json
Fix an exploit introduced in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/7158 by having the improved multi cooker cost a multi cooker. This stops a steel exploit.
Recipe costs prerequisite
More reviewers 
Unnecessary
> fix: update improved multi cooker recipe
